### ISSUE TITLE
format_suffix_patterns applies them after trailing slash.

### ISSUE THREAD

**Issue by aop** [tomchristie/django-rest-framework#1516]
According to http://www.django-rest-framework.org/api-guide/format-suffixes the suffices should be used directly after the resource name like http://example.com/api/users.json but format_suffix_patterns applies them after the trailing slash if one is used in the urlpatterns it gets (like the DefaultRouter does)

This results in 404 when trying to use them in the tutorial app for example: http://restframework.herokuapp.com/users.json

**Comment by mmarvick** [comment]
I agree with this. This is coming from someone completely new to the framework and going through the tutorial, so take that as you wish. However, the tutorial even gives the example that using `format_suffix_patterns` should make it so the API `will be able to handle URLs such as http://example.com/api/items/4.json`

See here: http://www.django-rest-framework.org/tutorial/2-requests-and-responses/#adding-optional-format-suffixes-to-our-urls
