### ISSUE TITLE
Support grouped choices.

### ISSUE THREAD

**Issue by ameyc** [tomchristie/django-rest-framework#1533]
**Update from @tomchristie**

**Closing off some related tickets and rolling them into this one...**

- [ ] Include core support.
- [ ] Render in browsable API. - #1636
- [ ] Display as metadata in response to `OPTIONS` requests. - #3101

---

One of our models has a Choicefield with following choices:

```
TYPE_CHOICES = (
        ('Default', (
            (1, 'Option 1'),
            (2, 'Option 2'),
            (3, 'Option 3'))),
        (4, 'Option 4'))
```

Now in the serializer if i have something _self.field.from_native(3)_, we get a ValidationError. Upon inspection of the DRF code we found that logic for valid_value method in the Choicefield is incorrect if you have nested sets with integer keys.

```
def valid_value(self, value):
        """
        Check to see if the provided value is a valid choice.
        """
        for k, v in self.choices:
            if isinstance(v, (list, tuple)):
                # This is an optgroup, so look inside the group for options
                for k2, v2 in v:
                    if value == smart_text(k2):
                        return True
            else:
                if value == smart_text(k) or value == k:
                    return True
        return False
```

Line _if value == smart_text(k2):_ should really be: _if value == smart_text(k2) or value == k2:_

**Comment by maxpeterson** [comment]
This appears to be broken again in the latest release (3.1.3) it appears that the test `test_nested_choices` was commented in https://github.com/tomchristie/django-rest-framework/commit/de301f3b6647e1c79a506405a88071ef977418d1#diff-92133d9c634f57bfbbad89754f6713af  and then removed in https://github.com/tomchristie/django-rest-framework/commit/c8764de7881f419c9269913ec3654fc1d904ab2e#diff-92133d9c634f57bfbbad89754f6713af - it is worth noting that [`CHOICES_NESTED`](https://github.com/tomchristie/django-rest-framework/blob/3.1.3/tests/test_validation.py#L148-L155) used by the test is still there.

Has support for grouped choices been dropped?

**Comment by maxpeterson** [comment]
I will take a look at fixing this

**Comment by tomchristie** [comment]
@maxpeterson - When mapping model fields to serializer fields we do use the model field `.flatchoices` attribute, so this should currently work...

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L113

True, you can't pass nested choices as the *argument* to the serializer choice field, tho.

**Comment by maxpeterson** [comment]
@tomchristie I am not clear. Are you suggesting we put the (new) flattened list of choices in `.flatchoices`, if so what goes in `.choices`?
