### ISSUE TITLE
TemplateHTMLRenderer is poorly documented and unintuitive.

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#1673]
1)
I believe that `data` is a list here so if there is an exception, then this assignment will fail:

```
    def resolve_context(self, data, request, response):
        if response.exception:
            data['status_code'] = response.status_code
        return RequestContext(request, data)
```

2) These dict reads use `[ ]` rather than `get` so will fail if `renderer_context` is null or empty when passed in even with the `or`:

```
        renderer_context = renderer_context or {}
        view = renderer_context['view']
        request = renderer_context['request']
        response = renderer_context['response']
```

3) There is no documentation on how to write a template that works with this renderer. Specifically it is not clear what gets set in the context. 

4) I actually think that nothing gets set in the context and this render should be fixed as (at least for Listing):

```
class TemplateHTMLRenderer2(TemplateHTMLRenderer):
    def context_object_name(self, renderer_context):
        renderer_context = renderer_context or {}
        view = renderer_context['view']

        if hasattr(view, 'get_context_object_name'):
            return view.get_context_object_name()
        elif hasattr(view, 'context_object_name'):
            return view.context_object_name

    def render(self, data, accepted_media_type=None, renderer_context=None):
        data = {self.context_object_name(renderer_context): data}
        return super(TemplateHTMLRenderer2, self).render(data, accepted_media_type, renderer_context)
```

**Comment by tomchristie** [comment]
Pushing all further HTML specific stuff to 3.2.0.

**Comment by carltongibson** [comment]
I ran into this again yesterday. 

Having not used `TemplateHTMLRenderer` since around the time this thread opened, I'd totally forgotten all the lessons I'd learnt. 

Reviewing the docs I'd say the ["HTML & Forms" Topic Page](http://www.django-rest-framework.org/topics/html-and-forms/) in fact does a good job of explaining what you need to know. 

I think with a link from the Renderers docs this could be closed. 

(Hang tight...)
