### ISSUE TITLE
Test models should exist in corresponding test case, not in a global `models.py`.

### ISSUE THREAD

**Issue by xordoquy** [tomchristie/django-rest-framework#1777]
Due to a side effect with Django 1.7, some test models have been moved within the models file of the test application.
Following what has been said in #1398 this may not be what we want.

I'm fine with models being defined in the test application models file. This is open to discussion.

**Comment by xordoquy** [comment]
Was #2161 enough to close this issue or do we still have some related work ?

**Comment by tomchristie** [comment]
Mostly resolved. Remaining stuff isn't worth keeping on our todo list anymore.
Perhaps if we reach a static point with very little ongoing feature work then we could consider further test cleanups.
