### ISSUE TITLE
Review what/who we list in the credits.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#1835]
At some point in the past we stopped being consistent in adding contributers [to the credits](http://www.django-rest-framework.org/topics/credits), and eventually gave up on adding anyone at all, due to:

* Wasn't clear if we should add folks for single-character docs fixes.
* Not clear if we add someone if they did some work, that got rolled into a subsequant PR from someone else.
* We simply had too many ! :) new contributions and it was awkward updating that page all the time.

We need to decide what to do with this page.
GitHub's [list of contributors](https://github.com/tomchristie/django-rest-framework/graphs/contributors) only includes 100 people of 291. Can we get everyone through the GitHub API. Do we want to try to update that page all the time or is it too difficult? What process do we use for updating the page if we do want to? Perhaps just include text on that page saying something along the lines of "If you've made a contribution to Django REST framework please feel free to make a pull request adding yourself to this list" etc.etc.

For context:

![screen shot 2014-09-05 at 13 05 54](https://cloud.githubusercontent.com/assets/647359/4164475/168510e4-34f5-11e4-99f1-8868795d8034.png)
...[continues]

**Comment by tomchristie** [comment]
With the 3.1 release I've simply dropped that page - we're not doing anything about this at the moment, so unless someone wants to be proactive about deciding on a good way to layout the credits let's just drop it.

Perhaps we need to consider a new format for it that doesn't require us to manually list everyone. Alternatively if anyone wants to be proactive about making it possible to list all our contributors we can reopen this.

**Comment by thedrow** [comment]
You can just link or embed https://github.com/tomchristie/django-rest-framework/graphs/contributors

I think that would be best.

**Comment by tomchristie** [comment]
Possibly. Only lists the top 100.
