### ISSUE TITLE
Handle ATOMIC_REQUESTS correctly.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2034]
We should include some documentation around sensible ways to deal with atomicity in transactions, and also deal properly with `ATOMIC_REQUESTS` correctly. This needs both documentation, and probably also enhancements for handling `ATOMIC_REQUESTS = True`, which is complicated by the fact that we use a custom exception handler.

PR #1787 was an attempt at this but doesn't take the right approach, unsure how to resolve currently.

**Comment by alvarocavalcanti** [comment]
@tomchristie this question may seem dull but this point isn't clear to me: Does it mean that DRF do not support `ATOMIC_REQUESTS = True`? Because we're just trying to use it in our project and it does not seem to be working. I even posted a [question on StackOverflow](http://stackoverflow.com/questions/29652511/django-atomic-requests-not-working).

**Comment by xordoquy** [comment]
@alvarocavalcanti This is confirmed. I'll try to see if I can get a test case for this.

**Comment by xordoquy** [comment]
@tomchristie can you be more specific about why #1787 doesn't take the right approach ?

**Comment by tomchristie** [comment]
Well, stupidly I don't recall - so let's put it another way around.
We need to be able to write tests that verify any proposed fix.
Until and unless we've done that we shouldn't accept something. (including #1787)

**Comment by xordoquy** [comment]
@tomchristie fair enough

**Comment by tomchristie** [comment]
(Or if not tests, then at least a process by which we can verify the proposed fix.)

**Comment by tomchristie** [comment]
Any other handling gets dealt with by the Django stack. We only need to special case APIException because we’re returning responses from the view.

**Comment by xordoquy** [comment]
Thinking about it, we could call the rollback on `handle_exception` which calls the exception handler. That would secure the current non obvious behavior.

**Comment by kakulukia** [comment]
Well, i wanted to report that bug, because Django didnt care about catching my exception as claimed and DRF was only handling APIExceptions. So im going to figure out why. Could someone point out the Django part that should trigger the rollback? That might speed up my investigations. 
A general rollback on `handle_exception` would be nice tho!

**Comment by bramski** [comment]
This is still broken. If I use @transaction.atomic on a view and raise APIException my transaction is not rolled back.  That is a huge gotcha and unexpected behavior in my opinion.

**Comment by xordoquy** [comment]
At this point, a failing test case would be required to figure out whether or not it's broken

**Comment by tomchristie** [comment]
There's no indication that there's an issue.

A quick sanity check looks exactly correct: https://github.com/encode/django-rest-framework/blob/master/rest_framework/views.py#L67-103 and we've not had a bunch of users raising this, which I'd strongly expect.

@bramski Perhaps you've some custom exception handling or something, or there's some other integration issue that we could do a better job of documenting?
As @xordoquy say, if you believe there's an issue we'd need to have a simple reproducible example we can work against, or something more compelling than "this is broken" to demonstrate that it needs looking into.

**Comment by jmo-qap** [comment]
It is possible that @bramski was using `@transaction.atomic` on the non-default DB. https://github.com/encode/django-rest-framework/pull/7739 may help fully resolve https://github.com/encode/django-rest-framework/issues/2034.
