### ISSUE TITLE
Support 1.8's ArrayField

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2107]
Users can already support the model `ArrayField` using `serializers.ListField` (eg see https://groups.google.com/d/msg/django-rest-framework/Rolw5yEQ8cU/-rJYT_4i3iYJ ) 

However, we should deal with this creating mapping by default when using a `ModelSerializer`.

**Comment by jpadilla** [comment]
Are we planning anything possibly special when rendering `serializers.ListField` in an HTML form?

**Comment by tomchristie** [comment]
Hoping to support it in due course yes. We support a list HTML form syntax that'll be generated so it'll be a case of sorting the templates/JavaScript to enable it.

**Comment by jpadilla** [comment]
Tracking in #2496

**Comment by tomchristie** [comment]
Closed by #2496.
