### ISSUE TITLE
Search and filter controls for Browsable API & Admin

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2180]
The search and filter classes should render in the browsable API in a way that ensures they can be used without having to manually edit the URL querystring.

**Comment by thedrow** [comment]
@tomchristie This issue should probably be labeled as ```Browseable API```.

**Comment by tomchristie** [comment]
Not a distinction that we make any more: https://github.com/tomchristie/django-rest-framework/labels

**Comment by tomchristie** [comment]
Still very much on the roadmap but I'd like to start tying up 3.1.0 since there's a bunch of great improvements in there already. We may have 3.2.0 for the first portion of HTML stuff and 3.3.0 for the final bit of the admin api work, but currently undecided (may just all be 3.2.0)

**Comment by mihow** [comment]
Are there any branches that include this feature or any commits related to the issue? I'd love to test it.
