### ISSUE TITLE
Can't cache a ReturnDict.

### ISSUE THREAD

**Issue by StevenVeshkini** [tomchristie/django-rest-framework#2360]
Has anyone been able to cache `serializer.data` from a custom Serializer on one object? Seems like there's no way to store the ReturnDict that results from `serializer.data`.

**Comment by StevenVeshkini** [comment]
Any luck?

**Comment by tomchristie** [comment]
So the right way to resolve this would be either...

* Make serializer instances picklable, which oughta resolve this.

Or...

* Make `ReturnDict`'s pickle representation *not* include the serializer backlink. Given that we render the `.content` that oughta be okay in most cases anyways, not clear if accessing `response.data` from *cached* responses is something that should happen or not.

My personal take is that using pickle to deal with HTTP caching is a wonky approach. Rather store the raw headers and content, and return a newly created response instance when returning cached content. (Then you don't bump into all this horrible sorts of cases.)

**Comment by picturedots** [comment]
I encountered this problem (I think) when I was trying to set up caching
and gave up on this approach.  I ended up caching the entier rendered
response instead, using the URL as the key, but only if the accepted
renderer wasn't api, i.e.
should_cache = *self*.request.accepted_renderer.format != *'**api**'*


On Mon, Jan 5, 2015 at 12:31 PM, Tom Christie <notifications@github.com>
wrote:

> So the right way to resolve this would be either...
>
>    - Make serializer instances picklable, which oughta resolve this.
>
> Or...
>
>    - Make ReturnDict's pickle representation *not* include the serializer
>    backlink. Given that we render the .content that oughta be okay in
>    most cases anyways, not clear if accessing response.data from *cached*
>    responses is something that should happen or not.
>
> My personal take is that using pickle to deal with HTTP caching is a wonky
> approach. Rather store the raw headers and content, and return a newly
> created response instance when returning cached content. (Then you don't
> bump into all this horrible sorts of cases.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tomchristie/django-rest-framework/issues/2360#issuecomment-68743332>
> .
>



-- 

Mark Chackerian

VP Engineering, Architizer <http://www.architizer.com/>
646.812.0994

**Comment by thedrow** [comment]
@tomchristie Sometimes you want different levels of caching. Especially in cases where your API has many reads.
First level is always the complete response. If it's not cached or invalidated then the serializer's output should be used.
I agree that in this specific case it's a better idea to save the final serialization result (usually JSON) but in most cases when you cache python objects it's better to use pickle in order to store the value in the cache.

**Comment by Gaffney** [comment]
I just encountered this issue as well.  It also happens with a `ReturnList`:

(Error lines: [cPickle.c #L2100-2106](https://github.com/python-git/python/blob/master/Modules/cPickle.c#L2100-L2106))

      subl /Users/_/.virtualenvs/_/lib/python2.7/site-packages/django/core/cache/backends/locmem.py:67
        pickled = pickle.dumps(value, pickle.HIGHEST_PROTOCOL)
    PicklingError: Can't pickle <type 'generator'>: attribute lookup __builtin__.generator failed
