### ISSUE TITLE
serializer.data returns ReturnDict and OrderedDict instead of dict object.

### ISSUE THREAD

**Issue by learner010** [tomchristie/django-rest-framework#2364]
I have written a model serializer class for a model. When I test to see if it serializes properly I get following error.
`AssertionError: ReturnDict([(u'id', 1), ('apple', OrderedDict([(u'id', 1), ('data', u'this is a apple data.')])) ...`
I tried converting it to dict wrapping aserializer.data to dict function like
`dict(aserializer.data)`
I get following error.
`AssertionError: {'status': False, 'http': OrderedDict([(u'id', 1), ...`

How to get dictionary data from a serializer.

**Comment by xordoquy** [comment]
Just fall on it again.
The assert works under Python 3 but fails for Python 2.7

**Comment by xordoquy** [comment]
Forget the previous comment.
