### ISSUE TITLE
Notes on migrating from DRF 2.4 to 3.0

### ISSUE THREAD

**Issue by maennel** [tomchristie/django-rest-framework#2375]
Hi, I've promised you some summary of migrating from 2.4 to 3.0 a while ago. Let me tell you that I've started the migration when there was only the "What's new in 3.0" page published, which may have as a consequence that I've pointed out something well-documented in the meanwhile.
Also, I think 3.0 was a big step in the right direction and I appreciate a lot what you, Tom together with everyone contributing on DRF did here!
So, hereafter you'll find most of the points that made me struggle in some way during migration.

# Invocation order of 'save' and 'restore_object/create/update' got inverted

In the docs for DRF 3.0 it says somewhere that DRF 2.4's 'restore_object' has been replaced by the create/update functions. 
However, I believe that this sentence is not entirely correct. In DRF 2.4 'restore_object' was followed by a call to 'save' (on the Serializer), which called 'save' on the model. In DRF 3.0 we have 'save' (on the Serializer) calling 'create/update' directly.

# (self.)instance

It is not clear, whether (on a Serializer instance) 'self.instance' or 'instance' (available inside 'update' as an independent object) should be used.
I went on by using the provided 'instance' object and return the updated instance. The availability of self.instance seems, however, confusing to me.

# Serializer Workflow

It would be good to have some graphical representation of a workflow through a serializer to find out, where DRF hooks in and what is up to the user (if anything ;) ).

# Object creation

DRF 3.0 calls the model's 'create' method which implies calling the '\_\_init\_\_' constructor with all supplied arguments directly followed by the save() method. 
DRF 2.4 did not act this way - it called the constructor without arguments and initialized properties one by one afterwards. 
Currently, there is no mean to use '\_\_init\_\_' decoupled from save(), except overriding the create method completely. 
In our use case, we should be able to call the constructor, do some actions on the object and then save the object. With the DRF 3.0 way of doing things, either we're obliged to accept two DB round-trips (which is not really an option) or we can overwrite 'create()' completely, which does the trick, but is not very nice.

# Reversed Relations (like ManyToManyFields) are not considered inside Serializers

*This issue is not new in DRF 3.0, but was already there in DRF 2.4*
It is documented [here](http://www.django-rest-framework.org/api-guide/relations/#reverse-relations).
However, I think this is a big lack and should, if possible, be addressed. The suggested way of working around the issue requires one to specify *all* the model fields in the 'Meta.fields' property, which - in my opinion - violates the [pythonic DRY principle](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

**Comment by tomchristie** [comment]
> With the DRF 3.0 way of doing things, either we're obliged to accept two DB round-trips (which is not really an option) or we can overwrite 'create()' completely, which does the trick, but is not very nice.

I'd be interested in talking through that with you on the mailing list if you can provide a simple example case. I'm entirely happy with the move to single-step creation but talking through examples of how to do that well may be useful for other readers.

**Comment by xordoquy** [comment]
> However, I think this is a big lack and should, if possible, be addressed. The suggested way of working around the issue requires one to specify all the model fields in the 'Meta.fields' property, which - in my opinion - violates the pythonic DRY principle.

This definitively doesn't violates the DRY principle as you *should* specify fields for security reasons.
Github has been compromised with this kind of issue so it's something one should take seriously (see https://github.com/rails/rails/pull/4062)

This being said, I wonder if we should make meta's fields required.

**Comment by tomchristie** [comment]
> However, I think this is a big lack and should, if possible, be addressed.

As with @xordoquy I don't agree. We're optimizing for simplicity and maintainability. That's not the same thing as 'never have to write any code, ever, we'll just magically know what you want'. In the general case the API representation will not just be a dumb mapping to the complete set of database fields and reverse relationships. The user *should* be forced to be explicit about what fields are used in the representation.

>  I wonder if we should make meta's fields required.

I'm happy with the status-quo. You'll almost always want to list the fields explicitly, but it's reasonable enough to have a default of all for folks to get started quickly.

**Comment by tomchristie** [comment]
> It would be good to have some graphical representation of a workflow through a serializer to find out, where DRF hooks in and what is up to the user

Subscribe to https://github.com/tomchristie/django-rest-framework/issues/2085 if you want to follow any progress on that.

**Comment by tomchristie** [comment]
> In the docs for DRF 3.0 it says somewhere that DRF 2.4's 'restore_object' has been replaced by the create/update functions. 

Have updated the docs for more clarity.

**Comment by tomchristie** [comment]
> I went on by using the provided 'instance' object and return the updated instance. The availability of self.instance seems, however, confusing to me.

Would 'init_instance' (available always) and 'instance' (only available after save) be preferable? If not what.

**Comment by tomchristie** [comment]
Really appreciate the feedback and happy to talk any of this through further (on discussion group prob best), or spin off individual issues if anyone wants to raise particular bits of this in an actionable way.

In the meantime let's close this as it's more general discussion, than a single, well-defined, actionable issue.
