### ISSUE TITLE
ValidationError response doesn't include 'detail' key

### ISSUE THREAD

**Issue by mikewirth** [tomchristie/django-rest-framework#2378]
As stated [here](http://www.django-rest-framework.org/api-guide/exceptions/), all error responses based on `APIException` should include a `detail` key in the response body.

Because of the special handling of `list` and `dict` in `exception_handler(exc)` (see [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L67)) this is not the case for ValidationErrors.

I think the behavior should be changed, such that `dict` and `list` details are also wrapped in a `detail` key.

**Comment by tomchristie** [comment]
Customize the exception handler if that's the behavior you want.

http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

**Comment by mikewirth** [comment]
Thank you for the quick response. I did that.

In any case, I think the wording in the [documentation](http://www.django-rest-framework.org/api-guide/exceptions/) is misleading and should be adjusted:
> By default all error responses will include a key `detail` in the body of the response, but other keys may also be included.

A possible change could be:
> By default all error responses (except ValidationErrors) will include a key `detail` in the body of the response, but other keys may also be included.
