### ISSUE TITLE
Visualizing the data

### ISSUE THREAD

**Issue by Black-Star** [tomchristie/django-rest-framework#2381]
created new serializer with list field and some of them are not mandatory. 
After initializing serializer with corresponding data and below is the attribute error 

Serializers declared with fields required=False

class DummySerializer(serializers.Serializer):
	dummy1 = serializers.CharField(required=True)
	dummy1 = serializers.CharField(required=True)
	dummy2 = serializers.CharField(required=False)
	dummy3 = serializers.CharField(required=False)

class DummyList(serializers.ListField):
	child = DummySerializer()

class SuperDummy(serializers.Serializer):
    primary_super_dummy = serializers.IntegerField(required=True)
    dummy_data = DummyList()

 
data = {'dummy_data': [{'dummy1': 'assd', 'dummy2': 'second'}],
 'primary_super_dummy': 123}

dummySerializer = SuperDummy(data = data)
dummySerializer.is_valid()
out:True

dummySerializer.data
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-7bf1a20b2d38> in <module>()
----> 1 dummySerializer.data

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/serializers.pyc in data(self)
    418     @property
    419     def data(self):
--> 420         ret = super(Serializer, self).data
    421         return ReturnDict(ret, serializer=self)
    422 

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/serializers.pyc in data(self)
    174                 self._data = self.to_representation(self.instance)
    175             elif hasattr(self, '_validated_data') and not getattr(self, '_errors', None):
--> 176                 self._data = self.to_representation(self.validated_data)
    177             else:
    178                 self._data = self.get_initial()

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/serializers.pyc in to_representation(self, instance)
    387                 ret[field.field_name] = None
    388             else:
--> 389                 ret[field.field_name] = field.to_representation(attribute)
    390 
    391         return ret

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/fields.pyc in to_representation(self, data)
   1093         List of object instances -> List of dicts of primitive datatypes.
   1094         """
-> 1095         return [self.child.to_representation(item) for item in data]
   1096 
   1097 

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/serializers.pyc in to_representation(self, instance)
    383 
    384         for field in fields:
--> 385             attribute = field.get_attribute(instance)
    386             if attribute is None:
    387                 ret[field.field_name] = None

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/fields.pyc in get_attribute(self, instance)
    276         that should be used for this field.
    277         """
--> 278         return get_attribute(instance, self.source_attrs)
    279 
    280     def get_default(self):

/data/dataBackend/local/lib/python2.7/site-packages/rest_framework/fields.pyc in get_attribute(instance, attrs)
     68                 return instance[attr]
     69             except (KeyError, TypeError, AttributeError):
---> 70                 raise exc
     71         if is_simple_callable(instance):
     72             instance = instance()

AttributeError: 'OrderedDict' object has no attribute 'dummy3'

dummySerializer.validated_data
OrderedDict([('primary_super_dummy', 123), ('dummy_data', [OrderedDict([('dummy1', u'assd'), ('dummy2', u'second')])])])

**Comment by tomchristie** [comment]
`required=False` currently means that the data is not required for *input*.
The incoming v3.0.3 modifies this so that `required=False` means that the data is not required for *input* or *output* which will resolve what you're seeing. Suggest you install from master until 3.0.3 is released (which will be very soon now)
