### ISSUE TITLE
DjangoObjectPermissionsFilter requires guardian

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2387]
Why does `DjangoObjectPermissionsFilter` require `guardian` as opposed to working with any "object-permissions-enabled backend"?
`DjangoObjectPermissions` for example does not require guardian.

Perhaps the class name should more explicitly call out the fact that django-guardian is required?

**Comment by tomchristie** [comment]
Because there's no general purpose `get_objects_for_user` API that we can hook into, although there is one specifically for guardian... https://github.com/tomchristie/django-rest-framework/blob/3.0.2/rest_framework/filters.py#L192

**Comment by cancan101** [comment]
@tomchristie Understood, but does it make sense to either rename the class or at the very least add a comment to the docs? Right now the docstring does not indicate the requirement on guardian.
