### ISSUE TITLE
is_valid() does not need to be called during read-only operations

### ISSUE THREAD

**Issue by bendavis78** [tomchristie/django-rest-framework#2389]
I'm trying to supply initial data to a serializer by overriding `get_serializer()` on a ModelViewSet. When trying to perform a simple GET request on the model, however, an error is raised complaining that `is_valid()` was not called before accessing `serializer.data`.

**Comment by carltongibson** [comment]
This is going to be wrong usage. If you see the serializer docs, data is provided when instantiating:

```
# .save() will create a new instance.
serializer = CommentSerializer(data=data)

# .save() will update the existing `comment` instance.
serializer = CommentSerializer(comment, data=data) 
```

If you need it you can access `initial_data` inside the serializer but `data` is deliberately not available until after validation. 

This seems more a usage issue. Please follow up on the mailing list if you're still stuck.
