### ISSUE TITLE
Use `install_requires` to enforce minimum Django versions.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2390]
Currently it's way too easy for our users to accidental use an unsupported version of Django.
Eg. 1.6 instead of 1.6.3+, see: http://stackoverflow.com/questions/27497676/django-rest-api-urlsplit-error

We should probably add a range of minimum requirements to the `install_requires` key in `setup.py`. We may choose not to cap the maximum version? Be nice if we can ensure there's no conflict with eg installing against a PYTHONPATH forked version of Django - we don't want to stomp on users if they're confident in a different setup.

**Comment by tomchristie** [comment]
I guess this... http://stackoverflow.com/questions/12759761/python-pip-force-install-ignoring-dependencies

**Comment by tomchristie** [comment]
May as well make this a 3.1.0 thing I guess - that way we can call it out sufficiently.

**Comment by xordoquy** [comment]
Alternatively we could test the Django version in the `rest_framework/__init__.py` so that it won't install a new version behind user.
I'm not sure using the `install_requires` would do something if the user does a `pip install -r requirements.txt`

**Comment by tomchristie** [comment]
> I'm not sure using the install_requires would do something if the user does a pip install -r requirements.txt

If you mean `pip install -r requirements.txt` from their project, which includes rest_framework as a dependancy, then yes it'd ensure the Django version is correct too.

If you mean `pip install-r requirements.txt` from inside this project's directory, then it wouldn't but that's not something I'm much concerned about (although I guess we could also version Django there too)

**Comment by tomchristie** [comment]
> Alternatively we could test the Django version in the rest_framework/__init__.py so that it won't install a new version behind user.

We could, although that'd be more awkward to work around for eg users using who have a forked version of Django that doesn't meet the versioning requirements, but is actually compatible within the context of their particular project, (or other non-standard installation case.)

**Comment by xordoquy** [comment]
@tomchristie should be fine if we issue a strong warning but not more

**Comment by tomchristie** [comment]
Dropping this as I don't consider it worthy of our consideration right now.
