### ISSUE TITLE
Add Cursor based pagination.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2393]
With 3.1's new pagination API the initial styles will be `PageNumberPagination` and `LimitOffsetPagination`.

We should also add an `CursorPagination` that uses cursor based pagination for use with very large data sets, where indexing into the result set is infeasible.

However, let's not let this block the 3.1 release - we'll slate this for 3.2 instead.

**Comment by samrad** [comment]
+1 Tom.

**Comment by tomchristie** [comment]
For reference: http://cramer.io/2011/03/08/building-cursors-for-the-disqus-api/

**Comment by tomchristie** [comment]
Also http://www.sitepoint.com/paginating-real-time-data-cursor-based-pagination/

**Comment by maryokhin** [comment]
This is great and is really needed!

**Comment by tomchristie** [comment]
Bumping to 3.1

**Comment by tomchristie** [comment]
Now in the `version-3.1` branch.

![screen shot 2015-01-22 at 17 44 33](https://cloud.githubusercontent.com/assets/647359/5861129/5f62f21e-a25e-11e4-9dc9-b1cb73c9f89a.png)

Few tweaks to follow up on being tracked against #1169.
