### ISSUE TITLE
Accept "on" as a boolean field value.

### ISSUE THREAD

**Issue by iamit** [tomchristie/django-rest-framework#2394]
In am using a django form as a way to filter my list response (see http://stackoverflow.com/questions/27782251/django-rest-framework-serializer-as-a-form-in-get-deprecated ).

Beside the question whether this is the proper way (which I already suspect, it's not) i runned in to this when putthing the django from data in the serializer:

the django form returns 'on' in case the boolean field is selected,

so in the boolean field, this list should be extended with the 'on','ON' and 'On':

TRUE_VALUES = set(('t', 'T', 'true', 'True', 'TRUE', '1', 1, True,'On','on','ON'))

**Comment by tomchristie** [comment]
I don't see that string in quotes anywhere here... https://github.com/django/django/blob/master/django/forms/widgets.py

Currently closing this off, but could be persuaded to reopen if that string really is used inside Django someplace. Link me to it and we can reconsider.

**Comment by iamit** [comment]
python 2.7
django 1.4.14

I realy get 'on' back

if I do not use this patch:

    class FormToSerializerBooleanField(serializers.BooleanField):
        ''' workaround to convert django form field to serializer form field
        see my issue https://github.com/tomchristie/django-rest-framework/issues/2394
        '''
        TRUE_VALUES = set(('t', 'T', 'true', 'True', 'TRUE', '1', 1, True,'On','on','ON'))
        FALSE_VALUES = set(('f', 'F', 'false', 'False', 'FALSE', '0', 0, 0.0, False,'Off','off','OFF'))

I don't think the flase value is needed by the way.

I did not look for documentation, but without it i get this error:

"`on` is not a valid boolean."


it does not work for me.

**Comment by iamit** [comment]
By the way, it is in combination with the hack of putting the django form in the BrowsableAPIRenderer

    class SomeApiForm(forms.Form):
        field1 = forms.CharField(max_length=17,help_text='help text with form 1')
        field2 = forms.IntegerField(required=False,help_text='another help text')


    class MyBrowsableAPIRenderer(BrowsableAPIRenderer):
        def get_context(self, *args, **kwargs):
            context = super(MyBrowsableAPIRenderer, self).get_context(*args, **kwargs)
            context['display_edit_forms'] = True
            form = SomeApiForm()
            context['post_form'] = form 
            return context 

and the the forms.BooleanField

**Comment by tomchristie** [comment]
Fair enough - but we do need confirmation that it's really a Django built-in default.
It could be a quirk of some third-party forms package you have or similar, in which case it'd be hard to justify supporting that particular string.

**Comment by iamit** [comment]
I Agree with you, In case I find out where the 'on' string comes from... I'll let you know.

**Comment by iamit** [comment]
could this be it?

http://stackoverflow.com/questions/12911787/html-checkbox-default-value

(I Am using firefox in ubuntu)

**Comment by tomchristie** [comment]
Sounds likely, yes.

**Comment by iamit** [comment]
Thanks

**Comment by tomchristie** [comment]
Moving to 'Needs further review' as it's unclear to me if the literal 'on' string really is used as suggested in this answer, or if we should simply be testing against *any* value existing.

**Comment by tomchristie** [comment]
I'd like to see a more through/demonstrable review of *what* possible range of values we should be expecting from the browser before progressing this. Can any non-empty value potentially be sent - is it just the value of the checkboxes 'value' attribute. If so should we just note that and enfore that it needs to be a "true"-like string in the HTML?

**Comment by tomchristie** [comment]
At the moment this is waiting on some kind of confirmation. Going to close this off, pending some more actionable information.

**Comment by vstoykov** [comment]
What I see in the Django form widgets is that they define string which will be explicitly casted to given value but then a returned value is `bool(value)`. This means that any value will be converted to `True` for checkbox widget.

This was done with this commit:
https://github.com/django/django/commit/be29329ccd49a84d3f7238111aebf97c4aaac581

And is related to that issue:
https://code.djangoproject.com/ticket/16820

Probably DRF need to behave the same way, but for convenience to have more options to set false.

**Comment by xordoquy** [comment]
You van easily override the booelanfield ans change the allows true or false acceptable values

**Comment by vstoykov** [comment]
I think that we need to reopen this ticket. I can provide a PR for it and make the behavior closer to that in Django.

@tomchristie @xordoquy what you think?

**Comment by tomchristie** [comment]
@vstoykov Depends what the proposal is *exactly*?

> so in the boolean field, this list should be extended with the 'on','ON' and 'On'

I never saw any demonstration/justification for that.

So:

* What do you believe the behavior current is?
* What would you be proposing to modified behavior to be?
* What does Django do?

**Comment by carltongibson** [comment]
If you want to support 'on','ON' and 'On' (or anything else) it's easy to create a [custom widget that overrides `value_from_datadict`](https://docs.djangoproject.com/en/1.8/ref/forms/widgets/#django.forms.Widget.value_from_datadict) to map whatever set of values you want from the query parameters to the value received by the field.

**Comment by tomchristie** [comment]
@carltongibson - Tho we don't use widgets in REST framework's HTML form fields. (Not since the templated HTML forms came in.)

**Comment by vstoykov** [comment]
@tomchristie I posted a link to Django issue with the same logic behind BooleanFields and also link to the commit which fixed the issue.

The behavior of Django is to define some values as `False` and then to use `bool(value)`. And by this any string is considered `True` (except empty string of course).

I made a change here https://github.com/vstoykov/django-rest-framework/commit/529727f2c2b26b6ab90e4f78abaf673f23e8b94c if you are ok I can create PR.

**Comment by tomchristie** [comment]
Okay, so I'd be inclined to accept something closer to "And by this any string is considered True" *but only if* we strictly limited that to HTML form inputs.

For JSON I think we want to retain the 'invalid' case as that'll typically be more obvious/useful behavior. Eg. I'd want send `'is_activate': 'foo'` on a boolean field to result in an error.

**Comment by tomchristie** [comment]
Retitled the ticket to be more specfic and accepted as an enhancement.

**Comment by carltongibson** [comment]
> Tho we don't use widgets in REST framework's HTML form fields. (Not since the templated HTML forms came in.)

Right. That explains a lot. A weekend with the source code I think. 🍸

**Comment by carltongibson** [comment]
OK. I've had a look at this. Not sure what the conclusion is — but there's some interesting room for play in Django's **use** of widgets, as a bridge between the QueryDict and the Field, vs DRF's **not using** them. 

> ... but only if we strictly limited that to HTML form inputs.

The initial thought here is that it would have to be done at the **parser** level — you need to map Any-Old-String to a boolean. _That_ is immediately followed by a look to the heavens; it wouldn't work: you'd have to allow the parser to introspect the serialiser, to know which fields to were meant to be bools — Argh! 

So then you start thinking about how it could be done at the field level... Maybe if this were a method call...

             if data in self.TRUE_VALUES:

... with the field accessing the request, and re-doing the work already handled by the parser...

You pretty quickly come round to @xordoquy's:

> You can easily override the booelanfield and change the allows true or false acceptable values

**But**, then I think, hang on. What does Django know that we don't:

>  ...the same logic behind BooleanFields and also link to the commit which fixed the issue.

The issue and the commit there **are not** on `BooleanField` but on `CheckboxInput` a widget, and only one of several the are appropriate for use with a `BooleanField`. The point (here) being that they don't map as being immediately applicable to `rest_framework.fields.BooleanField` 

Widgets in Django serve — going this way, from the QueryDict to the Field — as a sanitisation layer that lets you strip out all sorts of gnarly. DRF can no longer utilise this. It's a bit of a loss. 

Is that loss worth it? Maybe. A whole layer inlined for not much more than: 

    TRUE_VALUES = set(('t', 'T', 'true', 'True', 'TRUE', '1', 1, True))
    FALSE_VALUES = set(('f', 'F', 'false', 'False', 'FALSE', '0', 0, 0.0, False))

(Aside: It's very easy to miss set literals here.)

But, by eliminating widgets you are making this `Field`'s responsibility — and so there are going to be questions of this sort. They're fair game.

For DRF* it comes down to:  

1. What's the line that's drawn for out-of-the-box support? (Probably as-is)
2. What's the best advise to give users who need to customise. 

On 2 I think "override the BooelanField" is the 80% answer.

For the case where people really do need different behaviour for JSON vs HTML Form requests the simplest thing (I can see) is (as so often) override `get_serializer`, or `get_serializer_class`, and choose a serialiser using `BooleanField` or your subclass dependent on the request. 

I appreciate this is quite long/rambly. Sorry for that. 

* What _is_ the phrasing to avoid the agent noun?

**Comment by xordoquy** [comment]
I'm missing the point about why one wants a different behaviour between regular API and html forms here.

**Comment by carltongibson** [comment]
This was @tomchristie's point above: 

> For JSON I think we want to retain the 'invalid' case as that'll typically be more obvious/useful behavior. Eg. I'd want 'is_activate': 'foo' on a boolean field to result in an error.

You want to allow bad HTML Form clients to send weird truthy values, such as `'0'`, without letting anything goes when validating JSON. 

But looking at it, the current behaviour's not great here: JSON has `true`/`false` for booleans, the string equivalents should raise a validation error. (It's probably a good middle ground; happy to implement a StrictBooleanField for when it's actually an issue.)

**Comment by tomchristie** [comment]
On reflection, kicking this firmly into the "do not care" pile right now.

If someone can show that there are browsers that disregard the 'value' attribute on checkbox input then I can see why we'd want to change this, but I haven't seen that yet.

Fully *document* which values we accept, sure?
Allow easy overriding of which set of values are considered true/false/invalid, sure?

If the behaviour should be changed I'd like to see a obvious simple case of why.

I think our differing usage (primarily API vs django's HTML forms only is sufficient enough to merit the different behaviour, and it's in any case only evident *if* the developer uses a custom string value in the HTML form - if you want  to support that, then override the field and the set of allowable values.
