### ISSUE TITLE
PATCH requests don't check trailing /

### ISSUE THREAD

**Issue by samuelcolvin** [tomchristie/django-rest-framework#2405]
With `POST` requests there's a hard check that urls end with a `/`, with `PATCH` that doesn't occur. I'm assuming this is because the check is done by django for `POST` requests, but not `PATCH` as standard django doesn't support it?

This caused me a lot of grief today both the initial problem, then finding it.

I see this isn't actually a bug, but I think a fix which raises an exception and returns a 500 response as with `POST` would be prudent.

Currently the request seems to get all the way to the view's save method with `request.DATA==None`, which seems like the wrong behaviour.

version 2.4.4

**Comment by tomchristie** [comment]
I'm sorry, but I don't understand the issue as phrased here.

> With POST requests there's a hard check that urls end with a /

What and where?

A failing example case might help explain your issue better, although at a guess it seems like you're bumping into some kind of usage issue rather than a bug.

**Comment by samuelcolvin** [comment]
Sorry explanation last night wasn't clear, it was late. Here's how I see it:

Lets say we have a view/model/item:

    Request: GET /api/people/3/
    Response:
        status code: 200
        data: {"first_name": "Jane", "last_name": "Doe", "age": 30}

I Can change that model with a Post request:

    Request: POST /api/people/3/, data: {"first_name": "Jane", "last_name": "Doe", "age": 40}
    Response:
        status code: 200
        data: {"first_name": "Jane", "last_name": "Doe", "age": 40}

But if I miss the trailing slash from the URL I would get:

    Request: POST /api/people/3, data: {"first_name": "Jane", "last_name": "Doe", "age": 40}
    Response:
        status code: 500
        data: Exception Value: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/people/1/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.

(Data is actually a horrible html page which has to be parsed to get the exception shown above, but that's a different issue).

Now lets try updating Jane Doe with a PATCH request:

    Request: PATCH /api/people/3/, data: {"age": 50}
    Response:
        status code: 200
        data: {"first_name": "Jane", "last_name": "Doe", "age": 50}

All is well. But without the trailing slash:

    Request: PATCH /api/people/3, data: {"age": 60}
    Response:
        status code: 200
        data: {"first_name": "Jane", "last_name": "Doe", "age": 50}

The `PATCH` request has failed silently.

I realise now that this is because django is automatically forwarding from `/api/people/3` to `/api/people/3/` but loosing the PATCH data, just what the Exception above is guarding against.

I agree that there's a mistake in the request, but I still think that the request shouldn't return 200 when it failed to do what it's supposed to.

**Comment by samuelcolvin** [comment]
Humm thinking about this, I've realised that I could in fact detect this by detecting the redirect. I'm using the python Requests module which automatically "does" the redirect and returns the last response.

Perhaps the take away here should be to check the response object from requests and throw and exception if any occurred. But personally I would prefer an error as with `POST` requests.

**Comment by tomchristie** [comment]
Gotcha, understand now. This is actually a Django issue, rather than a REST framework issue. Specifically it's `APPEND_SLASH` behavior. See here...

https://github.com/django/django/blob/1.7.2/django/middleware/common.py#L75

    if settings.DEBUG and request.method == 'POST':
                    raise RuntimeError((""
                    "You called this URL via POST, but the URL doesn't end "
                    "in a slash and you have APPEND_SLASH set. Django can't "
                    "redirect to the slash URL while maintaining POST data. "
                    "Change your form to point to %s%s (note the trailing "
                    "slash), or set APPEND_SLASH=False in your Django "
                    "settings.") % (new_url[0], new_url[1]))

The issue here being that HTTP 301 responses allow the client (in particular web browsers) to rewrite HTTP POST/PUT/PATCH requests into HTTP GET requests. The possible resolutions here:

* Raise an issue with the Django project, extending this behavior to include PUT and PATCH methods.
* Raise an issue with the Django project, suggesting the usage of a 307 (or 308) redirect instead of the 301, for POST, PUT and PATCH requests. See: http://trac.tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#section-7.4
* Ignore the issue and disable `APPEND_SLASH` in your Django settings file.

If you do raise a Django issue please do link to it from here, and vice-versa.

Hope that helps!

**Comment by tomchristie** [comment]
See also https://github.com/kennethreitz/requests/issues/1084

**Comment by samuelcolvin** [comment]
Very helpful thank you.

Is there a third option to somehow catch this with DRF? Would it be possible to use `HTTP_REFERER` or something and check if patch, put requests have been redirected?

From experience most suggestions of changes to django get pretty surly responses but I'll try.

**Comment by samuelcolvin** [comment]
Django issue https://code.djangoproject.com/ticket/24145#ticket

**Comment by tomchristie** [comment]
> Is there a third option to somehow catch this with DRF?

Not in any sensible way. `CommonMiddleware` will have already dealt with the request prior to hitting REST framework's view code. Yes we probably could try to eg detect redirected PUT requests, but that'd also involve us erronously marking valid 307/308 requests as invalid and the more sensible approach would just to be to tackle this directly in Django.
