### ISSUE TITLE
Use OrderedDict for RelatedField.choices.

### ISSUE THREAD

**Issue by kylemacfarlane** [tomchristie/django-rest-framework#2408]
The order of choices is useful when returning metadata. For ChoiceFields DRF uses an OrderedDict but for RelatedFields everything is put into a regular dict which loses order.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L106

**Comment by tomchristie** [comment]
Don't see why not.

**Comment by aidanlister** [comment]
This breaks all my unit tests! Should this be documented somewhere? http://share.aidanlister.com/ayni

**Comment by tomchristie** [comment]
@aidanlister dict comparisons against ordered dict still return true if the elements match. Any chance you've missed something unexpected (eg some of the values are subtly different, or you're needlessly performing a comparison of the repr() of the compared items or something)

**Comment by xordoquy** [comment]
IIRC the comparison display is not really usefull with Python 2.7. With Python3 I think it appears as a dict

**Comment by aidanlister** [comment]
Ah @tomchristie I think you're right, the change is how the dates are presented in DRF3.

```
(Pdb) print response.data['results'][0]['updated']
2015-05-17T12:16:36.529346Z
(Pdb) print expected['results'][0]['updated']
2015-05-17T12:16:36.529346+00:00
```

I'll see what I can work out
