### ISSUE TITLE
MergeDict failing in Serializer's .is_valid()

### ISSUE THREAD

**Issue by bacongobbler** [tomchristie/django-rest-framework#2413]
I am sending a blank POST body to my viewsets. To show, I have the following data structures (and test case/response): https://gist.github.com/bacongobbler/ae96d73a618cedef55cc#file-gistfile1-py

The issue I'm hitting is an assertion error when [validating the serializer data](https://gist.github.com/bacongobbler/ae96d73a618cedef55cc#file-gistfile1-py-L108). Throwing myself into a `pdb` shell right before the [serializer's data is validated](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L20) and following BaseSerializer's `.is_valid()` flow, I see the following:

```
(Pdb) serializer.initial_data
MergeDict(<QueryDict: {}>, <MultiValueDict: {}>)
(Pdb) serializer.run_validation(serializer.initial_data)
*** ValidationError: {u'id': [u'This field may not be blank.']}
(Pdb) serializer.to_internal_value(serializer.initial_data)
*** ValidationError: {u'id': [u'This field may not be blank.']}
```

I'm seeing this issue while using DRF 3.0.2. Is there something wrong with my serializers which would cause the above issue, or is this a bug?

**Comment by tomchristie** [comment]
> Is there something wrong with my serializers which would cause the above issue

Looks like you want to be setting `allow_blank=True` on your id field.

In any case going to close this off as a usage question rather than a bug report.
