### ISSUE TITLE
Serializers rendered as HTML may not indicate current value in select widgets.

### ISSUE THREAD

**Issue by xordoquy** [tomchristie/django-rest-framework#2416]
The select combo boxes don't take existing values into account for select widgets. This means that users don't see the selected value in the update view.

The test at https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templates/rest_framework/horizontal/select.html#L11 is failing because:
- key is a string
- field.value is an integer

**Comment by tomchristie** [comment]
Makes sense - maybe worth including a screenshot to make this completely clear to anyone else reading through this.

**Comment by tomchristie** [comment]
Not immediately obvious what the right way to fix this is. Something like either:

* Coerce both the tested values to strings.
* Don't coerce the choice to a string in the first place.

**Comment by xordoquy** [comment]
As one can see hereunder, we do have a value for the user field (user id 4) but it appears as if this field is empty.

![Uploading Capture d’écran 2015-01-14 à 18.43.27.png . . .]()

**Comment by xordoquy** [comment]
I'm not sure which one is the best answer though I tend to prefer to keep the native types - i.e. don't coerce the choice to a string.
I'm not sure either what the test would look like.

**Comment by xordoquy** [comment]
Screenshot take 2
![Uploading Capture d’écran 2015-01-14 à 18.43.27.png . . .]()

**Comment by xordoquy** [comment]
Way better without accents.

![screenshot](https://cloud.githubusercontent.com/assets/2340654/5747347/914cc0e8-9c37-11e4-842e-70eb9834540d.png)

**Comment by tomchristie** [comment]
Changing the milestone on this - likely that we'll work on it as part of the focusing on HTML inputs with 3.2.0. Can reconsider if anyone wants to tackle it prior to that.

**Comment by aericson** [comment]
Seems like an easy picking for me to start up contributing. Considering that in [ChoiceField](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1004) the key is not coerced to string I guess it would be best to keep same approach. Any other thoughts on this?

**Comment by tomchristie** [comment]
@aericson Nothing from me I'm afraid - not given this one much thought lately but it'd be great to see someone have a dig into trying to resolve it.

**Comment by tomchristie** [comment]
Resolved via 6b08e97
