### ISSUE TITLE
Add 1.8 alpha support

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2425]
Add [1.8 alpha](https://www.djangoproject.com/download/) to the test matrix and resolve any issues.

The current builds against Django master indicate that there are some failures that will need resolving. It's unclear what's causing these. If they're not due to us using private Django API and they're not documented changes then it could also be valid to raise any upgrade issues 1.8 alpha presents as Django tickets.

**Comment by xordoquy** [comment]
Is there a PR already for this ?

**Comment by tomchristie** [comment]
Nope nothing yet.

**Comment by DavidMuller** [comment]
I checked this out a few weeks ago: the majority of the failures against Django master (`Failed: Database access not allowed, use the "django_db" mark to enable`) have to do with `pytest-django's` [compatibility with Django 1.8](https://github.com/pytest-dev/pytest-django/issues/189).   

@pelme [recently merged in support for 1.8](https://github.com/pytest-dev/pytest-django/issues/189), but has not released the updates on PyPI yet.

**Comment by pelme** [comment]
@DavidMuller A new version is released now, so it should now be fixed :)

**Comment by tomchristie** [comment]
Closed thanks to work by @DavidMuller  in #2427.

Thanks again!

**Comment by tomchristie** [comment]
Reopening this - hadn't noticed that 1.8-alpha is currently in the "expected failure" column.
Evidently still work to do here.

**Comment by stianjensen** [comment]
Django-filter are working on an update for 1.8 support:
https://github.com/alex/django-filter/pull/210

**Comment by tomchristie** [comment]
Some issues due to this change in Django behavior which I've raised as an issue... https://code.djangoproject.com/ticket/24208#ticket

**Comment by tomchristie** [comment]
Resolved by #2446.
django-filter is currently not included in our test matrix for 1.8 so we don't yet have support there, but we can add that once they've resolved any issues there.

**Comment by xordoquy** [comment]
\o/
