### ISSUE TITLE
Question: ordering according to a field in a ForeignKey

### ISSUE THREAD

**Issue by GerardPaligot** [tomchristie/django-rest-framework#2445]
Hi all,

Currently, I'm developing a API for an french open-source project and I would like to order the results according to a field in a foreign key.

I have a `Profile` class which has a foreign key to `User`. Like the search, I would like to make:

```python
class MemberListAPI(ListCreateAPIView, ProfileCreate, TokenGenerator):
    """
    Displays the list of registered users or create one.
    """

    queryset = Profile.objects.all()
    filter_backends = (filters.SearchFilter, filters.OrderingFilter,)
    search_fields = ('^user__username',)
    ordering_fields = ('user_username')
```

But to order my results, I must make this request:

```
http://localhost:8000/api/membres/?ordering=user__username
```

and not:

```
http://localhost:8000/api/membres/?ordering=username
```

Anyone can help me?

**Comment by tomchristie** [comment]
Howdy! The discussion group https://groups.google.com/forum/m/#!forum/django-rest-framework is the best place to post usage questions.

**Comment by GerardPaligot** [comment]
Ok, sorry for that. I'll ask my question to the discussion group.

**Comment by tomchristie** [comment]
No problem :)
