### ISSUE TITLE
Getting access to response.data in TemplateHTMLRenderer

### ISSUE THREAD

**Issue by yamatt** [tomchristie/django-rest-framework#2450]
Currently I'm using the framework whereby as a browser the data gets rendered using the `TemplateHTMLRenderer` and when the client requests JSON the renderer returns the data using `JSONRenderer`.

To do this on the relevant views I set `renderer_classes`  to:

    (renderers.TemplateHTMLRenderer, renderers.JSONRender)

This works OK when using `generics.RetrieveAPIView` but in my template I only have access to the `results` variable rather than all the stuff that `JSONRenderer` returns. However with a `generics.ListAPIView` that data is not available at all.

Am I going about this the right way? If yes then how should I get access to list data?

**Comment by tomchristie** [comment]
Howdy. Usage questions are best suited for the discussion group rather than the issue tracker...
https://groups.google.com/forum/#!forum/django-rest-framework

Thanks! :)
