### ISSUE TITLE
Unique validators don't treat NULL the same as Django or Postgres

### ISSUE THREAD

**Issue by kylemacfarlane** [tomchristie/django-rest-framework#2452]
When it comes to uniqueness, Postgres (and others) doesn't consider NULL to be equal to NULL and so duplicate NULLs are OK. However DRF merely checks for the existence of rows in a database and raises uniqueness validation errors even when it shouldn't.

I had a look at how Django's model forms deal with it and it seems like if any of the fields to be checked are None then unique validation is simply completely skipped: https://github.com/django/django/blob/f8e4e4a935512aedf815f6aee85bc797b498ea75/django/forms/models.py#L667

**Comment by tomchristie** [comment]
Seems valid. Thanks!

**Comment by Ins1ne** [comment]
Can you show example where validator not work correctly?

**Comment by kylemacfarlane** [comment]
This is a cut down version of a model where I had the problem:

    class Model(models.Model):
        barcode_prefix = models.CharField(
            max_length=2, blank=True, null=True, default=None, editable=False
        )
        barcode_number = models.PositiveIntegerField(
            validators=[
                validators.MinValueValidator(0),
                validators.MaxValueValidator(99999999)
            ],
            blank=True, null=True, default=None, editable=False
        )

        class Meta:
            unique_together = (('barcode_prefix', 'barcode_number'),)

**Comment by tomchristie** [comment]
Closed by #2572.
