### ISSUE TITLE
Checking for request.version raises AttributeError with BrowsableAPIRenderer

### ISSUE THREAD

**Issue by brandoncazander** [tomchristie/django-rest-framework#2455]
I've encountered the following exception when using the Browsable API in conjunction with the new namespace versioning and HyperlinkedModelSerializers:

```python
AttributeError: 'WSGIRequest' object has no attribute 'version'
```

I've implemented `get_serializer_class()` as specified in the documentation:

```python
def get_serializer_class(self):
    if self.request.version == 'v1':
        return AccountSerializerVersion1
    return AccountSerializer
```

I'm also using drf-nested-routers, and this is occurring on endpoints like /api/v1/car/1/tires/ where the Tire model has a ForeignKey to Car.

This only happens on the Browsable API; I can perform a GET request to the same endpoint using the JSONRenderer without exceptions.

**Comment by tomchristie** [comment]
Closed by #2456. Thanks again @brandoncazander!

**Comment by brandoncazander** [comment]
Testing out this change in my environment, I realized I had forgotten an important attribute on the request object! If we don't have the `versioning_scheme` attribute, then viewing the Browsable API will raise an ImproperlyConfigured exception when the reverse lookups for a HyperlinkedRelatedField fail.

The fix is very simple, same place as above. Should I make a new issue/pull request for this?

**Comment by tomchristie** [comment]
Please, yes. :)
