### ISSUE TITLE
Serializing nested generic relations dosn't create/deletes existing sub nested objects

### ISSUE THREAD

**Issue by polvoblanco** [tomchristie/django-rest-framework#2463]
I'm using version 2.4, not sure if this affects version 3.

When your model hierarchy has a generic relation with its own foreign key, then when you save the main model, the main model and generic relation save correctly but the generic models relation is not saved - it even actually deletes the relation if one exists.

I have posted my code on StackOverflow (http://stackoverflow.com/questions/28076639)

**Comment by tomchristie** [comment]
Closing this as a usage question rather than a bug report.

**Comment by polvoblanco** [comment]
Fair enough, however I think the documentation should be updated if this is the case to explain the extra steps that are necessary to make this work, as following the standard practice for non-generic models leads to very bug like results.
