### ISSUE TITLE
Feature to enable CSRF on API Views

### ISSUE THREAD

**Issue by heywbj** [tomchristie/django-rest-framework#2467]
As far as I can tell, by default CSRF protection is removed from `APIView` for the convenience of the developer, since providing a CSRF token requires a little extra work. 

It is an important enough security feature to be enabled by default in Django, and I am having trouble finding any explanation in the rest_framework documentation or otherwise as to why it is disabled by default. In the absence of any concrete justification behind its removal, I would like to see a feature to re-enable it (perhaps via a setting)

It is easy enough to do CSRF protection for AJAX POST requests -- in fact is is baked into core Django already:
https://docs.djangoproject.com/en/dev/ref/csrf/#ajax

**Comment by tomchristie** [comment]
CSRF is explicitly enforced as part of `SessionAuthentication`... https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authentication.py#L101-132

It doesn't make sense on non-session authentication so it's excluded in those cases.

**Comment by tomchristie** [comment]
Some notes on that http://www.django-rest-framework.org/topics/ajax-csrf-cors/#csrf-protection and http://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication but I wouldn't have any problem with docs pull requests that highlighted this more prominently.

**Comment by heywbj** [comment]
Thanks! That link was exactly what I was looking for
