### ISSUE TITLE
Support 1.8's range fields

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2480]
https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/#range-fields

**Comment by tomchristie** [comment]
Not obvious what representation we'd expect. Ignore bounds information and simple treat these as two-tuples?

**Comment by jpadilla** [comment]
I was just checking this out and asking myself the same question. Agree about moving this one out of 3.1.0 milestone.

**Comment by tomchristie** [comment]
Thanks @jpadilla :+1:

**Comment by tomchristie** [comment]
I'm going to go further than that and drop this ticket entirely, at least unless we see some outside motivation on it. Given that it's unclear what representation we'd use, and that this *isn't* something that corresponds to built-in python types, I'm pretty lukewarm on it.
