### ISSUE TITLE
Add `DurationField`.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2481]
For `ModelSerializer ` classes this should be mapped to by Django 1.8's `DurationField`.

**Comment by jpadilla** [comment]
Docs: https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.DurationField

What should the representation for this be?

**Comment by tomchristie** [comment]
Hrm. `JSONEncoder` will currently handle timedelta as a string representation `"123.456788"`, so options would be:

* Use string representation.
* Use `timedelta` and allow `JSONEncoder` to handle the final switch. 
* Follow `DecimalField` and use the string repr by default, but allow the coercion to be switched off.
* Decide that actually this isn't super worthy of 3.1.0 and push it back along with the range fields.

**Comment by jpadilla** [comment]
I personally don't mind pushing this back as well. I like we're already supporting "popular"(or what in my opinion are more seen and useful cases) fields like UUIDField, DictField, and HStoreField.

Perhaps pushing this one back, and work on ArrayField(#2107) for it's current 3.1.0 milestone?

**Comment by kevin-brown** [comment]
> Decide that actually this isn't super worthy of 3.1.0 and push it back along with the range fields.

:+1:

**Comment by willstott101** [comment]
There's some weird behaviour with this at the moment actually. A ModelSerializer with a (dajngo) DurationField serializes to `days hrs:mins:secs` (`1 04:00:00`) however that's not consistent with the (IMO less useful) current JSON encoder which renders to a decimal of seconds. I can do `str(TimeDelta).replace('days, ', '')` to format in Django style. 'ASP.NET' style a la [moment.js](http://momentjs.com/docs/#/durations/creating/) is very similar. As for supporting the field I think normalizing the behaviour must surely be the first step.

**Comment by thedrow** [comment]
Maybe we can provide format options just like we do with the DecimalField.

**Comment by tomchristie** [comment]
@thedrow Sounds reasonable, yep.

**Comment by rpcastagna** [comment]
Is there any guess on when this might sneak into the codebase? I'm just trying to plan for adding a duration field to one of my models.

**Comment by tomchristie** [comment]
@rpcastagna Its absolutely not a priority. If anything it might make sense for it to be considered as a third party package first.

**Comment by xordoquy** [comment]
Closing this as part of #2989. Feel free to reopen if there is more to be done.
