### ISSUE TITLE
TypeError: XXXViewSet() received an invalid keyword 'url_path'

### ISSUE THREAD

**Issue by sh4r3m4n** [tomchristie/django-rest-framework#2484]
I'm trying to customize the URL of a viewset's custom action following the documentation: http://www.django-rest-framework.org/api-guide/routers/#extra-link-and-actions

I have this code:
class XXXViewSet(viewsets.ModelViewSet):
     @detail_route(methods=['post'], url_path='update')
     def software_update(self, request, pk):
         ...

And when i do runserver I get:
TypeError: CameraViewSet() received an invalid keyword 'url_path'

**Comment by maryokhin** [comment]
Are you using `drf-extensions`?
https://github.com/chibisov/drf-extensions/issues/70

**Comment by sh4r3m4n** [comment]
No. I'm using drf-nested-routers==0.9.0 but I don't think it is the problem (i'm not using this ViewSet in a nested router)

**Comment by tomchristie** [comment]
Anyone care to confirm/deny if they can replicate this as presented?
As the issue is worded here it looks like it'd just be completely broken if true - is that the case, or are other folks using this happily?

**Comment by tomchristie** [comment]
I can't replicate this issue.

```python
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    @detail_route(methods=['post'], url_path='update')
    def software_update(self, request, pk):
        return Response({'hello': 'world'})
```

As things stand there's not much more I can do unless there's a clear way I can reproduce this, either as a failing test in a pull request, or an example set of instructions.

**Comment by tomchristie** [comment]
One possibility would be to take this empty project: https://github.com/tomchristie/basic-rest-framework and see what steps you need to make against it in order to replicate - I'd then be able to follow the same steps.

**Comment by sh4r3m4n** [comment]
Hi, i figured out that this problem succeeds in DRF 3.0.0 but not in 3.0.4, i'm not sure why. This is the code that only runs in the newer version if somebody wants it: https://github.com/sh4r3m4n/basic-rest-framework/commit/6e92ffe2f570ccddb9fb193ca8277d6edcc4f6bf

**Comment by tomchristie** [comment]
Do you mean 3.0.4 is okay, or not okay?

**Comment by sh4r3m4n** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 3.0.4 it works ok, in 3.0.0 it don't

On 10/02/15 16:48, Tom Christie wrote:
> Do you mean 3.0.4 is okay, or not okay?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/tomchristie/django-rest-framework/issues/2484#issuecomment-73769989>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJU2od/AAoJEOYNHtvg7gKbqFUP/ipwu311PggXpLVFP1ys2Nrx
6c9F8TdnMW2Vk8XEh6uGD+ylAFr9IHzuRU8kprKoVuAHDXoHkzb8n6J7ftmqPADy
AkDLpnFzNvsX+esUDmPHNcM3sBfFfO0MGIHHlh1Ygwz3r39j1ChBDlIDreiHKFtF
eREkvjhH6MW24vRLDn24zgTYu+ReBdcvZ6psRfIacRqMdjj2P3FxTq0aqZVnbd2p
KgMfH1nDU8xacyIP1RE6E4bimOH23JPVuKMwHtMiRWbFUZDbThUa6AZrmrC7Ju4e
oTaei1SYSyufvyEqSh02ti0+uVG82f8Vt49zOreaF/m/cACtJlhAIkooSBnwqMlu
jYq3LgX0o15KWiEk93g37W5ahSeqoStna1DpguO+2CY7v2d/adhxtCtvAIKu+PI8
auHNer4ZYLelYVX3pAhO5aaDaV4Z5TwRi1wOdnHgk5mM2QrJtg7E75v8z2FAIfFv
qWXS+3Wtp8kYpy4BvuPClRJT1N6uhRNBxcMRMwmoxlcFzQMF6RcmkATNQyUajdOe
eT6dWaSPU5yI4QVKKoC3qVJCa5+jrVp3mNqSHIL/Q8qVER2Xhq1SnuwknaftfAeS
bniT4MRFwXK6b/XSY0FW15orG6m5oLEt7LyfR1yAPs6qWceh60JFs6KQYHYJLG1P
qkA22hSFexKdE82u/eVW
=Hv8a
-----END PGP SIGNATURE-----

**Comment by kasey** [comment]
I ran into this issue today, running 3.0.2.  Looking at routers.py across the last few releases, it looks like this option wasn't added until the 3.0.3 release.  Upgrading to 3.0.5 fixed the problem for me.

**Comment by awbacker** [comment]
I know this is an old issue, but its the only hit that comes up for the google query.   Falling back on the `SimpleRouter()` and not using `drf-extensions ExtendedSimpleRouter()` fixes the issue for me.

The problem is this:  I get this error on _some_ ViewSets in some apps, but not in others, and I have had *no* luck in narrowing down the difference, and using DRV 3.3.1 and Extensions 0.2.8 didn't fix it.

I've changed just about everything possible including the file coding and reduced the troublesome django apps down to a single ViewSet.  Still the issue is there.    All I can guess is it's some sort of import order issue in some code I don't see or control.

**Comment by xordoquy** [comment]
@awbacker If using SimpleRouter fixes the issue, it should be declared to drf-extensions. We can't really do much within DRF if the extensions does something wrong.

**Comment by saitejach127** [comment]
Try changing you Django rest framework version. It worked for me
