### ISSUE TITLE
Borrow ideas from marshmallow

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2487]
This is more of a general suggestion than a specific issue, but are there any ideas in the [marshmallow library](http://marshmallow.readthedocs.org/en/latest/) that are worth incorporating into the DRF Serializers?

**Comment by tomchristie** [comment]
Totally valid question, tho best to put that out onto the discussion group, and if there are any specific actionable issues arising out of that then raise em here.
