### ISSUE TITLE
Accessing serializer.data before saving impedes updating read-only field in response

### ISSUE THREAD

**Issue by ybendana** [tomchristie/django-rest-framework#2490]
I'm using DRF 3.0.4 and I ran into this unexpected behavior while debugging a ModelViewSet.perform_update().  When I print serializer.data before calling serializer.save() it seems to block the update of the read-only field in the response. Here's a simplified example of my code:

    class MyModel(Model):
        myreadonlyattr = None

    class MyViewSet(ModelViewSet):
        def perform_update(self, serializer):
            serializer.is_valid(raise_exception=True)
            print serializer.data # Response will have myreadonlyattr=null
            serializer.save(myreadonlyattr='foo')

    class MySerializer(ModelSerializer):
        class Meta:
            model = MyModel
            fields = ('myreadonlyattr',)

        def update(self, instance, validated_data):
            instance.myreadonlyattr = validated_data.pop("myreadonlyattr", None)
            return instance

**Comment by xordoquy** [comment]
You shouldn't use serializer.data but serializer.validated_data.
See the section "Use .validated_data instead of .object." at http://www.django-rest-framework.org/topics/3.0-announcement/

**Comment by tomchristie** [comment]
At some point we could consider raising an error if calling `.save()` *after* accessing `.data`

**Comment by carltongibson** [comment]
This keeps coming up. I _guess_ it's just a hangover from 2.x habits (and probably many examples on SO etc).

**Comment by ybendana** [comment]
I'm not using serialized.data, I was just printing it out.  I didn't expect that to affect the Response, it's very confusing.  It would be helpful to see an error message on the call to save().

**Comment by DavidBrear** [comment]
I'm running into this issue because I'm trying to log what was changed and what it was changed to. Using serializer.data gave me the original values and allowed me to save in development but fails in test. Is there an easier way to do this?

**Comment by carltongibson** [comment]
@DavidBrear Use `initial_data` or `validated_data` as you need.

**Comment by alitoufighi** [comment]
Sometimes you need to access .data instead of .validated_data.
In my case, I wanted to access media updated url which was available in .data and not in .validated_data
Described here: https://stackoverflow.com/q/52343062/8543203

**Comment by xordoquy** [comment]
As @carltongibson said, you should use `initial_data` -in your case- rather than `.data` is `validated_data` is not what you need.
