### ISSUE TITLE
Image Field required False

### ISSUE THREAD

**Issue by carlware** [tomchristie/django-rest-framework#2494]
I have the following field in a serializer.
```python
image = fields.ImageField(use_url=True, required=False)
```
But when i try to update the the object (by PUT method) and I do not provide an image, the following error show up.
```json
{
    "image": [
        "The submitted data was not a file. Check the encoding type on the form."
    ]
}
```

Maybe I am misunderstanding the required option, is there a way that the image field not be required?

Checking the following code, I am asking me to myself if is there missing checking if the field is required or not before the try? 
```python
def to_internal_value(self, data):
        try:
            # `UploadedFile` objects should have name and size attributes.
            file_name = data.name
            file_size = data.size
        except AttributeError:
            self.fail('invalid')
```

**Comment by tomchristie** [comment]
> when i try to update the the object (by PUT method) and I do not provide an image

What exactly do you mean there - did you submit a blank value? How would I replicate what you're doing? It *looks* like you might be submitting, say, an empty string, rather than omitting the field completely, which is causing this error.

**Comment by carlware** [comment]
I do not provide an image, I used the html form provide it by the rest framework. 
![screen shot 2015-01-31 at 3 54 00 pm](https://cloud.githubusercontent.com/assets/3860869/5989982/a34a242a-a961-11e4-8726-e71d86137df1.png)

I want to be able to update the object even if the image is blank.

**Comment by carlware** [comment]
Only works when I choose an image, but if I left the image field empty does not work.

**Comment by tomchristie** [comment]
Use `allow_empty_file=True` instead of `required=False`. We may want to reconsider the usability aspect there tho'.

**Comment by carlware** [comment]
Still not working using allow_empty_file=True. Also I tried both required=False and allow_empty_file=True.

What I did was the following
```python
class ImageField(fields.ImageField):

	def to_internal_value(self, data):
                # if data is None image field was not uploaded
		if data:
			file_object = super(ImageField, self).to_internal_value(data)
			django_field = self._DjangoImageField()
			django_field.error_messages = self.error_messages
			django_field.to_python(file_object)
			return file_object
		return data

class AutoSerializer(DocumentSerializer):
	location = MongoPointField(read_only=True)
	image = ImageField(use_url=True, allow_empty_file=True)

        def update(self, instance, validated_data):

                # deleting the image because has a None value
		if 'image' in validated_data and not validated_data['image']:
			validated_data.pop('image')
                
                # another stuff
```
 and in this way is working.

**Comment by oskargicast** [comment]
@carlware it works for me. I just change fields.ImageField for serializers.ImageField. Thanks.

**Comment by tomchristie** [comment]
Going to close this of given the "doesn't replicate" comment above.
Will reconsider if raised again, but we've plenty of folks using this without issue, so nothing right now to make me think I want to spend a bunch of time look at this.

**Comment by atmosuwiryo** [comment]
Same case.

Endup with add 

    if data == '' and self.allow_empty_file:
        return ''

to rest_framework/field.py in "class FileField(Field):"


final code:

    def to_internal_value(self, data):
        if data == '' and self.allow_empty_file:
            return ''

        try:
            # `UploadedFile` objects should have name and size attributes.
            pdb.set_trace()
            file_name = data.name
            file_size = data.size
        except AttributeError:
            self.fail('invalid')

**Comment by Pinank** [comment]
from where i can import fields. It's showing me error.

**Comment by Pinank** [comment]
Can anybody help me to out with this,  I have imported fields from 

from django.db.models import fields


But now i'm getting 

ImportError: Could not import 'Users.views.jwt_response_payload_handler' for API setting 'JWT_RESPONSE_PAYLOAD_HANDLER'. AttributeError: 'module' object has no attribute 'ImageField'.

i'm making code in serializers.py

**Comment by tomchristie** [comment]
@Pinank Sounds like something to take to the discussion group, rather than an issue in REST framework that needs resolving.

**Comment by MirzaBaig715** [comment]
Just remove the _use_url_ and it will update.

**Comment by bzhr** [comment]
This is very weird. I have a writable nested model. When I update one of the fields on the parent (from the HTML form) everything goes well.

But when I update one of the nested children models from raw data field I get an error:

> HTTP 400 Bad Request
Allow: GET, PUT, PATCH, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

>{
    "profile_image": [
        "The submitted data was not a file. Check the encoding type on the form."
    ]
}

How do I test the writes to the nested objects? I thought to edit the data in raw input and hit put/patch. Maybe this is not intended...

P.s. profile_image model has blank=True, null=True,
serializer has allow_empty_value=True, required=False.

Seems like I shouldn't get this error, given the provided settings.

**Comment by aladagemre** [comment]
This worked for me: `avatar = serializers.ImageField(allow_empty_file=True, required=False)`
