### ISSUE TITLE
Explore the possibilty to use Cython for (de)serialization speedups

### ISSUE THREAD

**Issue by thedrow** [tomchristie/django-rest-framework#2499]
# Goals

The purpose of this issue is to discuss how Django REST Framework could potentially gain significant performance boost when using Cython when serializing/deserializing objects.
The goal of this issue is to decide whether we'd like to integrate it into the core or not and in which cases the speedups will be used.
If not introduced into the core the result of this research will be published into a third party package.

# Course of action

The first actionable step is to decide when we want to compile Cython.
I think that Cython speedups should be completely optional and if Cython is not available then no extensions are compiled. Moreover I think that if DRF is being installed under PyPy Cython extensions should only be compiled if specified explicitly since Cython only kinda works with PyPy.

After that we'll open a PR against this repository with contributions coordinated from my fork in order to prove that a speedup is even possible and that the speedups do not break any existing tests.
The fact that the PR exist does not mean it should or will be merged.

The next step would be to create a benchmark suite for DRF (which is desirable anyway IMHO) in order to measure what speedups have been gained.
We can use [codespeed](https://github.com/tobami/codespeed/) or [asv](http://spacetelescope.github.io/asv/) which is simpler and does not require a server but quite new. I can open a new issue about it.

After all this is done we can start discussing if we want this in the core or not. It will depend on how extensive the speedups will change the code.

# First steps to implementation

- [x] Set up travis to install Cython
- [x] Create new build jobs that have Cython installed and ensure that the tests are still being run without Cython as well
- [x] Generate speedups for the JSON renderer
- [ ] Specify the return type of to_representation and from_representation methods on fields that have an equivalent C/C++ type. This should be done by declaring them as C functions with Python bindings.
- [ ] Declare attributes with static types with their C equivalent.
- [ ] Your ideas.

**Comment by tomchristie** [comment]
While I'm interested to see where you take this, I'd probably prefer this and the NumPy work to be against a fork for the moment. These would almost certainly need to be third party packages or forks given the *very* different set of constraints they'd place on users of the project. (Possibly NumPy less so, but I'd still need to first be convinced that it's sufficiently better than the plain python improvements that we can make - plenty of low hanging fruit)

**Comment by thedrow** [comment]
I can close the PR but it will make my work less visible and since I want people to participate that's less productive for me.
Feel free to close the PR if you feel strongly about it.

**Comment by tomchristie** [comment]
Closing as per #2500. Not intended as a discouragement, just that these open but currently unvalidated proposals don't fit the way I'd like us to keep the issues managed. Let's see updates on the mailing list, with pull requests if we have clear actionable changes and proven benchmarks.
