### ISSUE TITLE
Basic authentication: raised error message more explicit if inactive user.

### ISSUE THREAD

**Issue by MEmmanuel** [tomchristie/django-rest-framework#2510]
In authentication.BasicAuthentication.authenticate_credentials, 
shouldn't the raised error message be "Inactive user" instead of "Invalid username/password", in case of inactive user?

        if user is None:
            raise exceptions.AuthenticationFailed('Invalid username/password')
        elif not user.is_active:
            raise exceptions.AuthenticationFailed('Inactive user')

Because i spent some time understanding how my credentials could be wrong...

Anyway, thank you for this powerful tool!

**Comment by tomchristie** [comment]
Sure. Feel free to submit a pull request for this.

I'd suggest we use the string "User account is disabled.", in line with this: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authtoken/serializers.py#L20

**Comment by tomchristie** [comment]
Now resolved in 3.1
