### ISSUE TITLE
Update demo site to REST framework 3.

### ISSUE THREAD

**Issue by scott113341** [tomchristie/django-rest-framework#2513]
This demo is linked to from the home page, but is running v2.3.13!

http://restframework.herokuapp.com/

**Comment by tomchristie** [comment]
Paging @markotibold - we I guess ought to hand over ownership of this, or at least document ownership etc. One of the [outstanding tasks on the project management](http://www.django-rest-framework.org/topics/project-management/#project-ownership) section.

**Comment by tomchristie** [comment]
I now have access to this app on heroku.
Reminder to self to ping @markotibold once 3.1 is released, at which point the app will get updated.

**Comment by tomchristie** [comment]
Complete - thanks to @markotibold 

![screen shot 2015-03-09 at 09 13 25](https://cloud.githubusercontent.com/assets/647359/6552322/8fa63a24-c63c-11e4-9f10-bb0f1cffeb52.png)
