### ISSUE TITLE
Trim whitespace by default on CharField.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2517]
See https://groups.google.com/forum/#!topic/django-developers/D1GBj9VB9sk

Suggestion would be a `trim_whitespace` flag that is `True` by default, and the trims leading and trailing whitespace from CharField inputs if set to `True`.

**Comment by JockeTF** [comment]
Makes sense to me. :+1:

**Comment by jpadilla** [comment]
Would we want to introduce any kind of setting for this?

**Comment by tomchristie** [comment]
> Would we want to introduce any kind of setting for this?

No. On by default, can be switched off per-field.

Also note that the ModelSerializer fields API gives users the ability to create a new base class, for example in order to change the default flag on CharField subclasses.

**Comment by jpadilla** [comment]
I can tackle this and include it in 3.1.

**Comment by tomchristie** [comment]
Fab.

**Comment by tomchristie** [comment]
Resolved via #2525, thanks to @jpadilla
