### ISSUE TITLE
Use a Metaclass for the views in order to shave unneeded code

### ISSUE THREAD

**Issue by thedrow** [tomchristie/django-rest-framework#2522]
When a view doesn't use a component that DRF offers the relevant functions are still called.
For example, when filtering is disabled ```filter_queryset()``` is always called anyway.
The solution would be to move that method to a mixin and have the metaclass check if the ```filter_queryset()```, ```get_filter_classes()``` methods exist on the view or if ```filter_classes``` is not empty and if they do exist you add the ```QuerysetFilterMixin``` to the list of base classes for that view.
The ```QuerysetFilterMixin``` (or any other name we'll call it) should override the the ```get_queryset()``` and you'll get exactly the same flow you had before only with less running code that you don't need.

I guess that the same process can be done for other parts of the view but before proceeding I'd like your approval on this.

**Comment by tomchristie** [comment]
The trade-off in complexity this involves really (really) isn't worth it.

It's very unlikely that those function calls will make any meaningful difference in the context of the rest of the stack, and metaclasses introduce substantial extra complexity.

For proposed performance improvements, it might be better to see tickets being led by benchmarking - show the relative speeds of different parts of the system, and then think about how we can speed up any slow components.

**Comment by thedrow** [comment]
I am going to post benchmarks.
