### ISSUE TITLE
`null`  using multipart and `HyperlinkedRelatedField` is triggering error

### ISSUE THREAD

**Issue by spac3-monkey** [tomchristie/django-rest-framework#2536]
As title says, using `multipart/form-data` when creating an object with the proper serializer and having a `HyperlinkedRelatedField` defined as non `required` and `allow_null` it throws a validation error when trying to set to `null` the current field: 'Invalid hyperlink - Incorrect URL match.'

**Comment by carltongibson** [comment]
Can I ask you to provide a clearer explanation of your issue? (I'm afraid I don't quite understand.)

Can you post the code needed to reproduce the issue? (Or even a failing test case.) Thanks.

**Comment by spac3-monkey** [comment]
You can see the code here: http://pastebin.com/w5pn1gmz

I'm building a tree shaped entity object and when creating it with a `null` parent throws the  error showed before. However when doing the same with blank('') parent it's created flawless. 

thanks in advance.

**Comment by carltongibson** [comment]
So you're saying this line: 

         parent = serializers.HyperlinkedRelatedField(allow_null=True, required=False, view_name='entity-detail', queryset=Entity.objects.all())

is leading to  'Invalid hyperlink - Incorrect URL match.' when passed a null value. OK.

What we need is to reduce that down to simple test case, eliminating all the MPTT stuff etc and see if we can reproduce. — Could you do that do you think?

**Comment by spac3-monkey** [comment]
Yes, that's exactly what's happening. 

Ok, I'll reduce it to simple test case.

thanks for the quick response.

**Comment by tomchristie** [comment]
Note that multipart encoding does not support `null` values - only string values (eg blank) or file uploads. Possible that's the root cause of what you're seeing, but not clear yet.

**Comment by tomchristie** [comment]
See this for multipart and `None` - https://github.com/tomchristie/django-rest-framework/pull/2495 - worth having a browse through that thread first to see if this is the same thing.

**Comment by spac3-monkey** [comment]
ok, will see first.

**Comment by spac3-monkey** [comment]
As @tomchristie said it's as #2495
