### ISSUE TITLE
Simplerouter routes initkwargs value is same instance of dict for all instances of Route

### ISSUE THREAD

**Issue by OdifYltsaeb** [tomchristie/django-rest-framework#2537]
For example - All List route Route instances have exatly the same instance of initkwargs dict with {'suffix':'List'} as value of initkwargs.

Most of time it is not an issue, but should you want to extend routes to create nested routes that pass additional kwargs to views via initkwargs, then this becomes an issue. It becomes annoying issue when you pass one route instance additional initkwarg and then suddenly find that all other instances of same Route class are suddenly throwing errors because they recieved an unexpected initkwarg. 

Fix is easy though:
```
    routes = [
        # List route.
        rest_framework.routers.Route(
            url=r'^{prefix}{trailing_slash}$',
            mapping={
                'get': 'list',
                'post': 'create'
            },
            name='{basename}-list',
            initkwargs={'suffix': 'List'}.copy()
        ),
        # Dynamically generated list routes.
        # Generated using @list_route decorator
        # on methods of the viewset.
        rest_framework.routers.DynamicListRoute(
            url=r'^{prefix}/{methodname}{trailing_slash}$',
            name='{basename}-{methodnamehyphen}',
            initkwargs={}.copy()
        ),
        # Detail route.
        rest_framework.routers.Route(
            url=r'^{prefix}/{lookup}{trailing_slash}$',
            mapping={
                'get': 'retrieve',
                'put': 'update',
                'patch': 'partial_update',
                'delete': 'destroy'
            },
            name='{basename}-detail',
            initkwargs={'suffix': 'Instance'}.copy()
        ),
        # Dynamically generated detail routes.
        # Generated using @detail_route decorator on methods of the viewset.
        rest_framework.routers.DynamicDetailRoute(
            url=r'^{prefix}/{lookup}/{methodname}{trailing_slash}$',
            name='{basename}-{methodnamehyphen}',
            initkwargs={}.copy()
        ),
    ]
```
Or you could remove routes declaration out of class declaration and into __init__ method...

**Comment by xordoquy** [comment]
@OdifYltsaeb I'd be interested in a failing test case if possible.

**Comment by OdifYltsaeb** [comment]
Hmmm i'm unsure how test case would help you. Like i said the issue does not affect django-rest-framework at all and appears when you want to further extend routers/viewsets.

Simply put, the issue is
```
da = db = dc = {}
da['a'] = 'anything'
dc.items()
dict_items([('a', 'anything')])
```

**Comment by tomchristie** [comment]
I'm sorry I don't understand this issue as currently presented.
Can you show the simplest possible case that demonstrates the issue?

**Comment by OdifYltsaeb** [comment]
I thought the dict thingy i wrote in my last post was simplest possible case :). Sorry - i'm not very good with english.

Simplest possible Use case is something like
1) installing drf-nested-routers
2) extending drf.routers.NestedSimpleRouter and adding additional keys/values into initkwargs
3) Seeing how all other routers/views start throwing errors when they suddenly get unexpected initkwargs... because of this simple thing:

You are declaring routes in routers.SimpleRouter class. You are assigning pre-defined dict instances as value for route initkwargs. ALL Route instances created based on those routes receive the same dict instance not copy of that dict. 

But like i have said it twice already - the issue has NOTHING to do with django-rest-framework itself. But it is stopping me from extending drf-nested-routers. And imo it is bad practice to assign same dict instance as value to possibly n+1 object parameters.

I'll add my own code below - perhaps this gives you more information about how i'm using django-rest-framework

```
routers.py:

class NestedSimpleRouter(SimpleRouter):
    def __init__(self, parent_router, parent_prefix, *args, **kwargs):
        self.parent_router = parent_router
        self.parent_prefix = parent_prefix
        self.nest_count = getattr(parent_router, 'nest_count', 0) +1
        self.parent_lookup = kwargs.get('lookup', None)
        self.nest_prefix = kwargs.pop('lookup', 'nested_%i' % self.nest_count) + '_'
        super(NestedSimpleRouter, self).__init__(*args, **kwargs)

        parent_registry = [registered for registered in self.parent_router.registry if registered[0] == self.parent_prefix]
        try:
            parent_registry = parent_registry[0]
            parent_prefix, parent_viewset, parent_basename = parent_registry
        except:
            raise RuntimeError('parent registered resource not found')

        nested_routes = []
        parent_lookup_regex = parent_router.get_lookup_regex(parent_viewset, self.nest_prefix)
        self.parent_regex = '{parent_prefix}/{parent_lookup_regex}/'.format(parent_prefix=parent_prefix, parent_lookup_regex=parent_lookup_regex)
        if hasattr(parent_router, 'parent_regex'):
            self.parent_regex = parent_router.parent_regex+self.parent_regex

        for route in self.routes:
            route_contents = route._asdict()

            route_contents['url'] = route.url.replace('^', '^'+self.parent_regex)
            """
            only connnection between route and view seems to be through initkwargs
            so that is why i am setting them here so i would later have access
            to viewset parent object in nested viewset later on - see viewsets.py part
            """
            route_contents['initkwargs']['parent_class'] = parent_viewset.serializer_class.Meta.model
            route_contents['initkwargs']['parent_lookup_kwarg'] = self.nest_prefix + getattr(parent_viewset, 'lookup_field', 'pk')
            route_contents['initkwargs']['parent_lookup_field'] = self.parent_lookup
            nested_routes.append(type(route)(**route_contents))

        self.routes = nested_routes


viewsets.py:
class NestedGenericAPIView(GenericViewSet):
    """
    IF these 3 following attributes are note declared then
    viewset.as_view() will start throwing errors
    """
    parent_lookup_kwarg = None
    parent_lookup_field = None
    parent_class = None

    def get_parent_obj(self, obj):
        fields = obj._meta.get_all_field_names()
        important_attrs = ('parent_lookup_kwarg', 'parent_lookup_field', 'parent_class')
        if not all(getattr(self, att) for att in important_attrs) or self.parent_lookup_field not in fields:
            # Cannot find parent object if any of the important values is missing
            return None

        try:
            return self.parent_class.objects.get(id=self.kwargs[self.parent_lookup_kwarg])
        except self.parent_class.DoesNotExist:
            return None

    def get_queryset(self):
        queryset = super(NestedGenericAPIView, self).get_queryset()
        if not self.parent_lookup_field or not self.parent_lookup_kwarg:
            return queryset

        filters = {self.parent_lookup_field: self.kwargs[self.parent_lookup_kwarg]}
        return queryset.filter(**filters)

views.py:
class RecentProjectViewSet(
        mixins.CreateModelMixin,
        mixins.RetrieveModelMixin,
        mixins.UpdateModelMixin,
        mixins.ListModelMixin,
        mixins.DestroyModelMixin,
        NestedGenericAPIView):

    queryset = RecentProject.objects.all()
    serializer_class = RecentProjectSerializer

    permission_classes = (UserIsAuthenticatedExpert, UserCanModifyCompanyOrExpert)
```

The above code allows me to do stuff like filtering nested viewset queryset by parent object as you can see in NestedGenericAPIView.get_queryset(). But it ONLY works because i have added `.copy()` to initkwargs dicts because otherwise the same dict would be in use for ALL routes of some type and putting additional initkwargs into them makes routers get_urls methods go crazy at this line `view = viewset.as_view(mapping, **route.initkwargs)` in rest.framework.routers.py (at SimpleRouter class)

**Comment by tomchristie** [comment]
This `{'suffix': 'List'}.copy()` doesn't make sense - you're ending up with the same thing there. Perhaps(?) there's some other point in the codebase where you want to be creating an `initkwargs` copy so as not the be using the same dictionary instance in multiple places, but it's not here.

Happy to consider this if I can see a PR and some example code that demonstrates the failure before and success after, but as it stands I've no way of seeing if this is:

* A clear issue.
* Due to REST framework or DRF nested routers.
* If there's a sensible fix.

Again, happy to reconsider if I can see a clearer, simpler "this is what's wrong and how it can be resolved".
