### ISSUE TITLE
How override `page_size` to obtain all objects (equivalent to `page_size=all`)

### ISSUE THREAD

**Issue by spac3-monkey** [tomchristie/django-rest-framework#2538]
I need to override the default behaviour of `paginate_by_param` to when using something like `page_size=all` it returns all available objects ignoring the `max_paginate_by` parameter.

**Comment by spac3-monkey** [comment]
sorry I just read the contributing guide line and post it on Google groups.

**Comment by tomchristie** [comment]
Thanks!
