### ISSUE TITLE
how to use django-rest-framework in tornado app

### ISSUE THREAD

**Issue by hackrole** [tomchristie/django-rest-framework#2541]
the django-rest-framework is really wonderful. I would like to use it in my tornado app. but it seemd can not work. 

In my opinion, the django-rest-framework make up of three parts: 
1) the serializers as a request-form validate and give the validated-data to models or response.
2) the renderers and parserers work with views to parse request and return result during to the media-type.
3) the views, viewsets for restfule-request-handlers.

all this seem not need to be dependent to the django only. and seems should work on others-framework.
but it seems not.

so please tell me, is there any way to use the top three things in tornado without pains?
or would you like to abstract the design for other frameworks?

**Comment by jpadilla** [comment]
The [discussion group](https://groups.google.com/forum/m/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by hackrole** [comment]
@jpadilla, sorry for that.
