### ISSUE TITLE
Logon button disappeared from BrowsableApi in 3.0.5

### ISSUE THREAD

**Issue by debnet** [tomchristie/django-rest-framework#2546]
Everything in the title. ;)

Thanks.

**Comment by tomchristie** [comment]
Doesn't reproduce for me.
If you can give some simple steps that demonstrate the issue reproducing we can reopen this.

![screen shot 2015-02-11 at 15 07 22](https://cloud.githubusercontent.com/assets/647359/6149302/c931ffa4-b1ff-11e4-825e-9f7c2f036067.png)

**Comment by debnet** [comment]
The problem occurs when changing de default namespace of DRF urls in my case:

`url(_(r'^api/'), include('rest_framework.urls', namespace='rest')),` doesn't work for example.

Seems it's not the only case...

**Comment by xordoquy** [comment]
I had the same issue though I don't use namespaces.
I do see two issues here:

1. the rest_framework is hardcoded at https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templatetags/rest_framework.py#L48
Anything against we make it configurable ?

2. The documentation doesn't mention the login view. May be I couldn't find it which is nearly the same (no mention in the authentication page nor in the browsable API). Anything against I add a section about this in the authentication page ?

**Comment by tomchristie** [comment]
Don't do that.
From the docs (homepage)...

> Note that the URL path can be whatever you want, but you must include 'rest_framework.urls' with the 'rest_framework' namespace.

That will always have failed to render the "log in" button

**Comment by tomchristie** [comment]
> the rest_framework is hardcoded - Anything against we make it configurable ?

There's no reason to do so. We're just including the browsable API login and logout views with some known names.

> The documentation doesn't mention the login view. Anything against I add a section about this in the authentication page ?

Yes, we could include something similar to what we say on the homepage in the auth docs too.

**Comment by xordoquy** [comment]
That settles it :)
