### ISSUE TITLE
Is the model-attribute in ModelViewSet depricated?

### ISSUE THREAD

**Issue by ostcar** [tomchristie/django-rest-framework#2551]
The upgrade from 3.0.4 to 3.0.5 broke my code.

I use ModelViewSets with the model attribute, like described in the documentation: http://www.django-rest-framework.org/api-guide/viewsets/#modelviewset

I build the urls for the rest-api with the DefaultRouter and did not specify a base_name. This worked fine in the 3.0.4 release but does not in 3.0.5.

The reason is https://github.com/tomchristie/django-rest-framework/commit/ba7dca893cd55a1d5ee928c4b10878c92c44c4f5 in which the support for model to generate the base_name was removed.

This is probably only a bug in the documentation which does not say that the model attribute is deprecated. But this could also be a bug in your Deprecation policy that indicates that: "Minor version numbers (0.0.x) are used for changes that are API compatible. You should be able to upgrade between minor point releases without any other code changes."

**Comment by tomchristie** [comment]
This was [deprecated in 2.4](http://www.django-rest-framework.org/topics/2.4-announcement/#deprecation-of-model-view-attribute), but evidently we'd left a bit in as an oversight. Probably needed more clearly calling out in the docs - Ideally it should have made it into 3.0, or else with hindsight we should have waited to do the cleanup until 3.1.
