### ISSUE TITLE
Quickstart Tutorial Error

### ISSUE THREAD

**Issue by eltronix** [tomchristie/django-rest-framework#2554]
Under the 'Views' section, the last import statement is raising an error. This is what it looks like currenty:

`from tutorial.quickstart.serializers import UserSerializer, GroupSerializer`

But it should be (remove the 'tutorial' part):

`from quickstart.serializers import UserSerializer, GroupSerializer`

**Comment by jpadilla** [comment]
@eltronix just ran through the quickstart tutorial again and it seems fine to me.

Make sure your file structure looks like this:
![screen shot 2015-02-13 at 11 29 18 am](https://cloud.githubusercontent.com/assets/83319/6189784/afacf33e-b373-11e4-8f96-f6c1edcc2652.png)

**Comment by jpadilla** [comment]
Closing this off, feel free to comment or open again if you're still having issues. Thanks!
