### ISSUE TITLE
implicit object attributes in request

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2557]
Am I correct that [this logic](https://github.com/tomchristie/django-rest-framework/blob/2.4.4/rest_framework/mixins.py#L162) was removed in DRF3? If so, is there any documentation of that fact in the release / upgrade notes?
Also, some notes on how to reproduce the old functionality.

**Comment by xordoquy** [comment]
Please, do not use the issue tracker as a usage forum. There is the mailing list or IRC for it.
To answer you, you should use the serializer's update / create methods.

**Comment by tomchristie** [comment]
No, we do set them, by passing them as keyword arguments to 'serializer.save()'
