### ISSUE TITLE
DRF 3.0: widget_html manipulations equivalent

### ISSUE THREAD

**Issue by nemesisdesign** [tomchristie/django-rest-framework#2561]
While porting https://github.com/djangonauts/django-rest-framework-gis to DRF 3.0 one little problem arised, in the previous version I introduced a little improved that enabled the browsable API to show a textarea with nicely indented GeoJSON, which came really handy when testing PUT/PATCH methods.

After porting to DRF 3.0, with the change at the linked line:
https://github.com/djangonauts/django-rest-framework-gis/commit/b93c9a6172bd76005a6a17e81d7e04fc15c0382f#diff-dc41434392d098f7395c9d89d9a000e8L46
We lost the nicely formatted GeoJSON. Also, on python2 we get something like:
```
{ 'type': u'Feature', 'geometry': { 'type': u'Point', 'coordinates': [0, 0] }}
```
Notice the `u''` of unicode.

This causes annoyances becaue  `u''` is not valid JSON and raises validation errors.

I looked for a way to accomplish the same goal in DRF 3.0 but I'm not sure it's possible at all.

This is how it looked before porting to DRF 3.0:
https://www.dropbox.com/s/gzjly41ougmq0il/geojson-drf-2.png?dl=0

This is how it looks after porting to DRF 3.0:
https://www.dropbox.com/s/qhc4c85g4xghkb6/geojson-drf-3.png?dl=0

The method I could not port to DRF 3.0 is this one:
https://github.com/djangonauts/django-rest-framework-gis/blob/9a903692d5677b6e2b8622d6cca2fec71a53db00/rest_framework_gis/fields.py#L46

The important line is:
```
content = json.dumps(self._value, indent=4)
```

**Comment by nemesisdesign** [comment]
The best way to solve this is by using the `__str__` method of the object returned by `to_representation` as done here:
https://github.com/djangonauts/django-rest-framework-gis/commit/0dda52840af290f5dd289f6c4e268cb9907cfe7e

**Comment by tomchristie** [comment]
Thanks for updating the ticket!

**Comment by nemesisdesign** [comment]
Welcome, I saw the open issues were more than 100 so I wanted to help you guys out in reducing noise.

**Comment by tomchristie** [comment]
:)

**Comment by tomchristie** [comment]
Always very much appreciated!
