### ISSUE TITLE
PEP8 pinning

### ISSUE THREAD

**Issue by phalt** [tomchristie/django-rest-framework#2563]
PEP8 is failing on some new pull requests that use a newer version of PEP8 (see PR #2562).

PEP8 should be pinned.

**Comment by tomchristie** [comment]
I'd suggest that we do both of:

* Update the code in line with the latest version.
* Pin pep8.

The alternative would just be to do the first, and pin to a lower version (whatever was used prior to #2562) Could accept that and then continue a separate issue for the second.
