### ISSUE TITLE
`parse_html_list` Failed to match html list

### ISSUE THREAD

**Issue by H0neyBadger** [tomchristie/django-rest-framework#2566]
Hello,
First of all, thanks for your work !

I have created a serialize that call ListField
```python
computers = serializers.ListField(
    child=serializers.RegexField(regex=r'^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]([a-z]+)$', max_length=64, allow_blank=True, required=True)
)
```
It works perfectly when I use API’s raw data, but when I try to post the following list through the HTML form, the field isn’t parsed as expected.

```python
['computer1.foo.bar', 'computer2.foo.bar', 'computer3.foo.bar']
```

With the side effect that the ListField doesn’t raise validation error

I tried to solve this issue by myself, but I not clearly understand the use case of this regex in parse_html_list
```python
regex = re.compile(r'^%s\[([0-9]+)\](.*)$' % re.escape(prefix))
```

how to test :

```python
from rest_framework.utils import html
dictionary = {'account': 'honeybadger', 'computers': "['computer1.foo.bar', 'computer2.foo.bar', 'computer3.foo.bar']", '_method': 'PUT'}
prefix='computers'

print(html.parse_html_list(dictionary, prefix=prefix))
```

Thanks

**Comment by jpadilla** [comment]
FWIW the result of that print is an empty list.

```python
>>> from rest_framework.utils import html
>>> dictionary = {'account': 'honeybadger', 'computers': "['computer1.foo.bar', 'computer2.foo.bar', 'computer3.foo.bar']", '_method': 'PUT'}
>>> prefix='computers'
>>> print(html.parse_html_list(dictionary, prefix=prefix))
[]
```

**Comment by rvanlaar** [comment]
I made a personal fix for this issue. 
This works since prefix is the name of the field when used when submitting the html data
and I submit an actual JSON list.

https://github.com/tomchristie/django-rest-framework/issues/2566

For it to work the above computer example I replaced " with ' and ' with ".

```
>>> from rest_framework.utils import html
>>> dictionary = {'account': 'honeybadger', 'computers': '["computer1.foo.bar", "computer2.foo.bar", "computer3.foo.bar"]', '_method': 'PUT'}
>>> prefix='computers'

>>> print(html.parse_html_list(dictionary, prefix=prefix))
['computer1.foo.bar', 'computer2.foo.bar', 'computer3.foo.bar']
```

**Comment by tomchristie** [comment]
HTML Form style list support isn't currently supported. It will be in a future release, see #2060 and #2148. Use JSON input if you need list fields.

**Comment by mikofski** [comment]
Sorry for tacking this onto this issue since it is closed and also sorry for not submitting a PR.

Here is a fix for the HTML ListField issue inspired by this [Google Group DRF forum post](https://groups.google.com/d/msg/django-rest-framework/RBy2HbIYDgU/WhMMYlYyxn4J)

    --- rest_framework.fields.py.ORIG	2015-10-14 15:59:28.085932500 -0700
    +++ rest_framework.fields.py.NEW	2015-10-14 16:01:41.943932500 -0700
    @@ -1448,6 +1448,31 @@
             # We override the default field access in order to support
             # lists in HTML forms.
             if html.is_html_input(dictionary):
    +
    +            # BEGIN NEW CODE - MARK MIKOFSKI - 2015/10/14
    +            listval = dictionary.getlist(self.field_name)
    +            if len(listval) == 1 and isinstance(listval[0], basestring):
    +                listval = listval[0]  # get single string in value list
    +                if listval.startswith('[') and listval.endswith(']'):
    +                    # remove any brackets from string
    +                    listval = listval[1:-1]
    +                listval = listval.split(',')
    +                dictionary.setlist(
    +                    self.field_name,
    +                    [self.child.to_representation(v) for v in listval]
    +                )
    +            # END NEW CODE - MARK MIKOFSKI - 2015/10/14
    +
                 val = dictionary.getlist(self.field_name, [])
                 if len(val) > 0:
                     # Support QueryDict lists in HTML input.


As I indicated in my response to the post, you can also just insert this into your `serializers.py` module and then use it instead of `serializers.ListField`

    from rest_framework.utils import html
    from rest_framework.fields import empty
    import logging

    logger = logging.getLogger(__name__)


    class CustomListField(serializers.ListField):
        def get_value(self, dictionary):
            if self.field_name not in dictionary:
                if getattr(self.root, 'partial', False):
                    return empty
            # We override the default field access in order to support
            # lists in HTML forms.
            if html.is_html_input(dictionary):

                # BEGIN NEW CODE - MARK MIKOFSKI - 2015/10/14
                logger.debug('*************** entering get_value() ***************')
                logger.debug('dictionary:\n\t%r', dictionary)
                logger.debug('field name: %r', self.field_name)
                logger.debug('is html input: %r', html.is_html_input(dictionary))
                listval = dictionary.getlist(self.field_name)
                logger.debug('field name MultiValueDict value list:\n\t%r', listval)
                if len(listval) == 1 and isinstance(listval[0], basestring):
                    logger.debug('val list is a single string:\n\t%r', listval[0])
                    listval = listval[0]  # get single string in value list
                    if listval.startswith('[') and listval.endswith(']'):
                        # remove any brackets from string
                        listval = listval[1:-1]
                    listval = listval.split(',')
                    dictionary.setlist(
                        self.field_name,
                        [self.child.to_representation(v) for v in listval]
                    )
                    listval = dictionary.getlist(self.field_name)
                    logger.debug('new dict val:\n\t%r', listval)
                    logger.debug('length of new dict val: %r', len(listval))
                logger.debug('*************** leaving get_value() ***************')
                # END NEW CODE - MARK MIKOFSKI - 2015/10/14

                val = dictionary.getlist(self.field_name, [])
                if len(val) > 0:
                    # Support QueryDict lists in HTML input.
                    return val
                return html.parse_html_list(dictionary, prefix=self.field_name)
            return dictionary.get(self.field_name, empty)
