### ISSUE TITLE
url outdated and probably a typo?

### ISSUE THREAD

**Issue by learner010** [tomchristie/django-rest-framework#2576]
Link at `http://www.django-rest-framework.org/api-guide/testing/#apiclient` is dead.
The one at `Extends Django's existing Client class.`. It should point to `https://docs.djangoproject.com/en/dev/topics/testing/tools/#the-test-client`

Also `The APIClient class supports the same request interface as APIRequestFactory.` should have been `The APIClient class supports the same request interface as Client.`?

**Comment by tomchristie** [comment]
Well spotted! Welcome to make a pull request for them if you like :)

**Comment by learner010** [comment]
This will be my first pull request. Very excited :dancers:

**Comment by learner010** [comment]
Please review pull request `2589`[https://github.com/tomchristie/django-rest-framework/pull/2589]

**Comment by tomchristie** [comment]
Closed via #2589
