### ISSUE TITLE
PUT request to non-existing model resource address

### ISSUE THREAD

**Issue by tsouvarev** [tomchristie/django-rest-framework#2578]
DRF answers HTTP 404 when client try to make PUT request to resource that does not exist. AFAIK, server is expected to create new resource with this content. 
That's because UpdateModelMixin uses basic get_object to, well, get object, but semantics for PUT is different from semantics for GET or PATCH (though, server may create new resource on PATCH request)

**Comment by tomchristie** [comment]
http://www.django-rest-framework.org/api-guide/generic-views/#put-as-create
