### ISSUE TITLE
url_path feature does not work for nested routes

### ISSUE THREAD

**Issue by maryokhin** [tomchristie/django-rest-framework#2583]
As per discussion on IRC with @tomchristie and chibisov/drf-extensions#70, the current <a href="https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/routers.py#L174">popping out</a> of the `url_path` kwarg does not work for downstream packages that reuse the same viewset for constructing nested routes. The reason for that is `get_routes()` being called multiple times (our router only calls it once) for each subsequent nested route, and therefore only the first route will know that `url_path` argument was set.

P.S. As an adhoc example solution, <a href="https://gist.github.com/maryokhin/8765b07aa335b4d4bbcd#file-routers-py-L60">popping back in</a> `url_path` if it diverges from the method name on subsequent routes.

**Comment by maryokhin** [comment]
As a side note, why are the two if blocks separated?
```python
if isinstance(route, DynamicDetailRoute):
    ...
elif isinstance(route, DynamicListRoute):
    ...
```

**Comment by k4nar** [comment]
This is also an issue if one has a mixin with a `list_route` or a `detail_route` that is used in several place.

I'm working on a PR.

**Comment by sfdye** [comment]
This is happening again for `url_name`

**Comment by xordoquy** [comment]
Provided we have test case about it and they pass, we'll need much more than that. Also it would be nice to have a separated issue since this one has already been processed.
