### ISSUE TITLE
lookup_url_kwarg not correctly used by Router

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2591]
[`lookup_url_kwarg`](https://github.com/tomchristie/django-rest-framework/blob/8b0f25aa0a91cb7b56f9ce4dde4330fe5daaad9b/rest_framework/generics.py#L85) does not appear to be used by the router when generating URLs. See:
https://github.com/tomchristie/django-rest-framework/blob/ba7dca893cd55a1d5ee928c4b10878c92c44c4f5/rest_framework/routers.py#L228

**Comment by tomchristie** [comment]
Does look like a defect, yes.
If anyone's able to together a minimal failing test case that's probable the next thing needed to progress this issue.
