### ISSUE TITLE
ChoiceField returning the key instead of display_name

### ISSUE THREAD

**Issue by mochawich** [tomchristie/django-rest-framework#2592]
I've tried many way and still getting the keys instead of the display names. moreover, the validation is failing.

```python
MessageAttachmentSerializer():
    type = ChoiceField(choices=[(1, 'location1'), (2, 'location2')])
```

here it fails:
```
>>> MessageAttachmentSerializer(data={"type": "location1"}).is_valid(True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Volumes/x/dev/xx/lib/python2.7/site-packages/rest_framework/serializers.py", line 194, in is_valid
    raise ValidationError(self._errors)
ValidationError: {u'type': [u'`location1` is not a valid choice.']}
```
however, here not
```
>>> MessageAttachmentSerializer(data={"type": 1}).is_valid(True)
True

>>> MessageAttachmentSerializer(data={"type": "1"}).is_valid(True)
True
```

**Comment by tomchristie** [comment]
This is the way around it should be. The first value is the key and is used to interact with the selector via the API, the second is a display name, that is only used in the form display.

**Comment by pykler** [comment]
shouldn't this line https://github.com/tomchristie/django-rest-framework/blob/0ccb148183ac56eccbd2ac488402f3f075019bbd/rest_framework/fields.py#L1119

Read:

```
(six.text_type(key), val) for key in self.choices.items()
```

Or the more straight forward question, why are we settings display_names if they will never be used to display these fields?

**Comment by tomchristie** [comment]
They're used in the browsable API, but not JSON et al.
