### ISSUE TITLE
Serializer data property does not update on PUT and displays initial values

### ISSUE THREAD

**Issue by tobiaz** [tomchristie/django-rest-framework#2593]
When doing the following:
```
def put(self, request, pk, format=None):
		event = self.get_event(request, pk)
		event_serializer = CalendarEventSerializer(event, data=request.data, partial=True)
		
		if event_serializer.is_valid():
			event_serializer.save()
			return Response(event_serializer.data)
```
Reponse returns dict that does not show updated data. I had to do this for a workaround to make sure data is updated.

```
event_serializer._data = event_serializer.to_representation(event_serializer.instance)
```

I've tried tracing down the issue but can't seem to find it. The _date seems to be using is_initial values as everything else is correct within the serializer instance.

**Comment by carltongibson** [comment]
I'm going to close this for now as I suspect you're accessing `data` somewhere during validation — or such. The bottom line will be "Don't do this". `data` is populated on demand so if you don't call it early you'll get the post-save values you're after. 

See: #2532, #2276, #2289 and probably others for extended discussion of this topic. 

If there's something not covered there please come back here with what we need to reproduce the issue — ideally a failing test case — and we can re-open.

**Comment by tobiaz** [comment]
Thank you for the feedback. You're correct, I was accessing data instead of initial data, apologies. As a side note: this project is one of the best I've ever used, thank you!!!
