### ISSUE TITLE
Allow changing lookup_value logic in GenericAPIView::get_object

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2596]
Allow users to change the logic in [GenericAPIView::get_object](https://github.com/tomchristie/django-rest-framework/blob/8b0f25aa0a91cb7b56f9ce4dde4330fe5daaad9b/rest_framework/generics.py#L74) to get the `lookup_value`. For example:
```python
    def get_lookup_value(self):
        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field

        assert lookup_url_kwarg in self.kwargs, (
            'Expected view %s to be called with a URL keyword argument '
            'named "%s". Fix your URL conf, or set the `.lookup_field` '
            'attribute on the view correctly.' %
            (self.__class__.__name__, lookup_url_kwarg)
        )
       return self.kwargs[lookup_url_kwarg]

    def get_object(self):
        """
        Returns the object the view is displaying.
        You may want to override this if you need to provide non-standard
        queryset lookups.  Eg if objects are referenced using multiple
        keyword arguments in the url conf.
        """
        queryset = self.filter_queryset(self.get_queryset())

        # Perform the lookup filtering.
        lookup_value = self.get_lookup_value()
        filter_kwargs = {self.lookup_field: lookup_value}
        obj = get_object_or_404(queryset, **filter_kwargs)

        # May raise a permission denied
        self.check_object_permissions(self.request, obj)

        return obj
```
That way the user can write more complicated logic to map the URL to the filter without having to copy and paste the rest of the `get_object` implementation.

**Comment by tomchristie** [comment]
Introduces more granularity into the API, which I don't want to see.
The tradeoff here is between overriding with fewer lines vs. less indirection and less API.

The `get_object` method boils down to a 4 liner, if you want to change that behavior, you'll need to override the whole method.

    def get_object(self):
        queryset = self.filter_queryset(self.get_queryset())
        obj = get_object_or_404(queryset, ...)  # Some lookup
        self.check_object_permissions(self.request, obj)
        return obj
