### ISSUE TITLE
Context required, but not used in the exception_handler

### ISSUE THREAD

**Issue by troygrosfield** [tomchristie/django-rest-framework#2604]
The ``rest_framework.views.exception_handler`` method is defined as [1]:

```
def exception_handler(exc, context):
    ...
```
Which requires a context parameter that is never used in the method itself.  I would suggest either removing the context param, or adding **kwargs instead so no context has to be passed.

Or add documentation as to why it would be needed there or what it even is.

[1] https://github.com/tomchristie/django-rest-framework/blob/4248a8d3fc725d9ae3fe7aaaad7ee12479ab07ab/rest_framework/views.py#L52

**Comment by tomchristie** [comment]
If anyone wants to tackle a documentation PR for this if suggest searching the issues to see when (recently) and why it was added.

No we don't use it. Yes there was/is a motivation. Don't particularly care to much about it myself.
