### ISSUE TITLE
ListSerializer object is not iterable

### ISSUE THREAD

**Issue by mgaby25** [tomchristie/django-rest-framework#2607]
When trying to get the values serialized by a subclass of ListSerializer within the browsable API I got the above error. The error is made during template rendering.

Here is the full traceback:
<pre>
Environment:

Request Method: GET
Request URL: http://localhost:8082/categories/fields/

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_auth',
 'django_hstore',
 'django_js_utils',
 'haystack',
 'rosetta',
 'hvad',
 'sjerlok_user',
 'contact',
 'category',
 'case',
 'fileupload',
 'public',
 'compressor',
 'django_nose',
 'haystackbrowser')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Template error:
In template /home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/rest_framework/templates/rest_framework/api_form.html, error at line 3
   'CategoryFieldListSerializer' object is not iterable
   1 : {% load rest_framework %}

   2 : {% csrf_token %}

   3 :  {% for field in form %} 

   4 :     {% if not field.read_only %}

   5 :         {% render_field field style=style %}

   6 :     {% endif %}

   7 : {% endfor %}

   8 : 

   9 : 

Traceback:
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  137.                 response = response.render()
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/template/response.py" in render
  103.             self.content = self.rendered_content
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/rest_framework/response.py" in rendered_content
  59.         ret = renderer.render(self.data, media_type, context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/rest_framework/renderers.py" in render
  733.         context = self.get_context(data, accepted_media_type, renderer_context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/rest_framework/renderers.py" in get_context
  710.             'post_form': self.get_rendered_html_form(data, view, 'POST', request),
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/rest_framework/renderers.py" in get_rendered_html_form
  585.                     [('template', 'rest_framework/api_form.html')]
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/rest_framework/renderers.py" in render
  459.         return template.render(context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/template/base.py" in render
  148.             return self._render(context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/template/base.py" in _render
  142.         return self.nodelist.render(context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/template/base.py" in render
  844.                 bit = self.render_node(node, context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  80.             return node.render(context)
File "/home/mujini/.virtualenvs/sjerlok-env/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  161.                 values = list(values)

Exception Type: TypeError at /categories/fields/
Exception Value: 'CategoryFieldListSerializer' object is not iterable
</pre>

**Comment by tomchristie** [comment]
Pretty hard for us to assess this as it's currently framed.
If more details on how we would reproduce this are provided then we could consider re-opening this.

**Comment by mgaby25** [comment]
To reproduce this create this serializer:

    class CategoryFieldListSerializer(serializers.ListSerializer):
        child = serializers.CharField()

and use it in a view like this:

    class CategoryFieldCreateAPIView(generics.CreateAPIView):
        serializer_class = CategoryFieldListSerializer

**Comment by tomchristie** [comment]
I think there's a misunderstanding here: Don't use a list serializer in a list view unless that data you're providing is a list of lists.

You almost certainly just want to be using a regular serializer. REST framework will handle passing `many=True` to it for list views, and not pass `many` on detail views.

**Comment by sainttail** [comment]
I also got this exact same error as @mgaby25 (probably something wrong with form with browsable API, haven't tried post with ajax)
the error is in `@list_route(methods=['post'])`

```
@list_route(methods=['post'])
    def test(self, request):
        queryset = self.filter_queryset(self.get_queryset())
        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)
```

I don't know why this happen? because I want post action to return update objects
However, if i change to this `@list_route(methods=['get'])` it is working fine

My serializer class is a normal class that extends form ModelSerializer

```
class EventSerializer(serializers.ModelSerializer):
    class Meta:
        model = Event
```

**Comment by zhangguiyu** [comment]
My hack to eliminating this error is 1) override the rest_framework/horizontal/form.html template with a 2) custom filter, as follows:

<pre>
{% load rest_framework %}
{% load YOURAPP_tags %}
{# /template/rest_framework"TypeError: iter() returned non-iterator of type 'ListSerializer"' #}

{% if form|is_list %}
    {% for field in form %}
      {% if not field.read_only %}
        {% render_field field style=style %}
      {% endif %}
    {% endfor %}
{% endif %}
</pre>

<pre>
# YOURAPP/templatetags/YOURAPP_tags.py
from django import template
register = template.Library()
@register.filter(is_safe=True)
def is_list(value):
    return type(value) == list
</pre>

**Comment by Q-FL** [comment]
> To eliminate this error, one way is to
> 
> 1. override the rest_framework/horizontal/form.html template with a
> 
> ```
> {% load rest_framework %}
> {% load YOURAPP_tags %}
> {# /template/rest_framework/horizontal/form.html Fix "TypeError: iter() returned non-iterator of type 'ListSerializer"' #}
> 
> {% if form|is_list %}
>     {% for field in form %}
>       {% if not field.read_only %}
>         {% render_field field style=style %}
>       {% endif %}
>     {% endfor %}
> {% endif %}
> ```
> 
> 1. custom filter, as follows:
> 
> ```
> # YOURAPP/templatetags/YOURAPP_tags.py
> from django import template
> register = template.Library()
> @register.filter(is_safe=True)
> def is_list(value):
>     return type(value) == list
> ```

Your solution just sets the APIView POST form empty.
This fixed it:
```
@register.filter(is_safe=True)
def is_list(value):
    '''
    Fix "TypeError: iter() returned non-iterator of type 'ListSerializer"'
    /template/rest_framework/horizontal/form.html
    '''
    return value.__class__.__name__ == 'ListSerializer'
```
