### ISSUE TITLE
Misleading error on parent class when real error is in subclass

### ISSUE THREAD

**Issue by Gaffney** [tomchristie/django-rest-framework#2610]
Debugging the 3.0 upgrade was sometimes difficult because some the errors I had been receiving were misleading and/or uninformative.  This one in particular told me that "'RelatedManager' has no attribute \<reverse relation field\>" when in fact the real error is that `many=True` is not specified in the child serializer (which was not required prior to 3.0).

See example below:

    class Stats(models.Model):
      my_model = models.OneToOneField(MyModel, primary_key=True, related_name='stats')

    class MyModelSerializer(serializers.ModelSerializer):
    
      class Meta(object):
        fields = ('stats',)
  
    class MyModelSerializerFull(MyModelSerializer):
      children = MyModelSerializer()  # should be many=True

      class Meta(MySerializer.Meta):
        fields = MyModelSerializer.Meta.fields + ('children',)

When attempting to access MyModelSerializerFull(params).data, I get the following error message:

    AttributeError: 'RelatedManager' object has no attribute 'stats'

It would be nice if instead this said something more useful that would help identify the actual problem.

**Comment by tomchristie** [comment]
I'm going to pass on this for now as we'd need to do too much magical intuition to detect this.
Perhaps at a future date when we have less outstanding feature work, then these sort of soft-usability issues might be a higher priority, and could be re-opened.
