### ISSUE TITLE
DictField fixes

### ISSUE THREAD

**Issue by jerzyk** [tomchristie/django-rest-framework#2611]
Dict field was introduced as simple copy of ListField, so there were two errors, first one (to return dictionary) was already fixed (#2485 is also referring to it) but there is a very small issue (as well addressed in #2485) but mistakenly set as enhancement - change initial value from empty list to empty dict {}.

When this will be changed, posting from "Raw" tab in API view should improve (default - empty - value will be set correctly).

**Comment by tomchristie** [comment]
Fancy making the Pull Request for this? Small thing for this particular issue, but it's always helpful! :)

**Comment by jerzyk** [comment]
added :)

**Comment by jpadilla** [comment]
Closed via #2616
