### ISSUE TITLE
Add documentation about ArrayField for Postgres

### ISSUE THREAD

**Issue by rvanlaar** [tomchristie/django-rest-framework#2615]
Django 1.8 supports the Array data type from postgres.

A simple solution is to use a ListField Serializer:
```
    field_names = serializers.ListField(child=serializers.CharField(max_length=32, allow_blank=True))
```
as seen in this issue: https://groups.google.com/forum/#!topic/django-rest-framework/Rolw5yEQ8cU

It would help if this was part of the documentation.

**Comment by rvanlaar** [comment]
Seems this will be supported in DRF 3.1.

https://github.com/tomchristie/django-rest-framework/pull/2496
https://github.com/tomchristie/django-rest-framework/issues/2107

**Comment by jpadilla** [comment]
@rvanlaar yes indeed, we still need docs for those new fields though.

**Comment by johnthagen** [comment]
@encode / @tomchristie Could this be reopened? I don't see any documentation for `ArrayField` currently.

**Comment by xordoquy** [comment]
I think we already got everything covered through [`ListField](https://www.django-rest-framework.org/api-guide/fields/#listfield)

**Comment by johnthagen** [comment]
I guess it's not immediately clear to me how a `ModelSerializer` with an `ArrayField` maps in without an example. Maybe at least mentioning the connection between `ListField` and `ArrayField` would be very helpful.

**Comment by rpkilby** [comment]
A very minimal docs update might be helpful here. Aside from `HStoreField`, `JSONField` and `ListField` don't mention their connection to their postgres counterparts. That said, I wouldn't really consider this an open concern.
