### ISSUE TITLE
Setting DEFAULT_PAGINATION_SERIALIZER_CLASS documented but not implemented

### ISSUE THREAD

**Issue by davidfischer-ch** [tomchristie/django-rest-framework#2620]
See here:

https://github.com/tomchristie/django-rest-framework/search?utf8=%E2%9C%93&q=DEFAULT_PAGINATION_SERIALIZER_CLASS

**Comment by kevin-brown** [comment]
Looks like a breaking change in 3.1 for the new pagination API.

**Comment by tomchristie** [comment]
This is a 3.1 change that is now in `master`. Documentation incoming.
Check the lastest release branch `3.0.5` for the current 3.0 release source.
