### ISSUE TITLE
Nullable ChoiceField doesn't work the same as in a Django form

### ISSUE THREAD

**Issue by jessamynsmith** [tomchristie/django-rest-framework#2623]
I have a ChoiceField defined using an enum, as follows:
```
from django_enumfield import enum
class ClotSize(enum.Enum):
    SMALL = 0
    MEDIUM = 1
    LARGE = 2
clots = enum.EnumField(ClotSize, default=None, null=True, blank=True)
```

In general, when rendered into HTML, this results in an html select with empty string as the value for the empty option, plus options for each value in the enum.
In the Django admin, if I select the empty choice and save, it correctly saves the record with clots=null.

When I try to save the same data via the API, I get an error because empty string cannot be saved to an integer field:
```
InvalidStatusOperationError at /api/v2/periods/
["'' cannot be converted to int"]

Traceback:
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/views/decorators/csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/viewsets.py" in view
  85.             return self.dispatch(request, *args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  407.             response = self.handle_exception(exc)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  404.             response = handler(request, *args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/mixins.py" in create
  21.         self.perform_create(serializer)
File "/Users/jessamyn/Development/eggtimer/periods/views.py" in perform_create
  29.         serializer.save(user=self.request.user)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/serializers.py" in save
  164.             self.instance = self.create(validated_data)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/serializers.py" in create
  768.             instance = ModelClass.objects.create(**validated_data)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/query.py" in create
  370.         obj = self.model(**kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/base.py" in __init__
  442.                 setattr(self, field.attname, val)
File "/Users/jessamyn/.virtualenvs/eggtimer/src/django-enumfield/django_enumfield/db/fields.py" in set_enum
  44.             validators.validate_valid_transition(enum, old_value, new_value)
File "/Users/jessamyn/.virtualenvs/eggtimer/src/django-enumfield/django_enumfield/validators.py" in validate_valid_transition
  11.     validate_available_choice(enum, to_value)
File "/Users/jessamyn/.virtualenvs/eggtimer/src/django-enumfield/django_enumfield/validators.py" in validate_available_choice
  34.             raise InvalidStatusOperationError(message.format(value=to_value))
```

For the time being I have worked around this with a custom ```validate_clots``` method but I don't really want to do that for every nullable choice field, if there is a better way.

Upon delving into the Django source code, I see that it coerces the empty string to empty_value, which in this case is null. Perhaps something similar could work for DRF.
```
class TypedMultipleChoiceField(MultipleChoiceField):
    def __init__(self, *args, **kwargs):
        self.coerce = kwargs.pop('coerce', lambda val: val)
        self.empty_value = kwargs.pop('empty_value', [])
        super(TypedMultipleChoiceField, self).__init__(*args, **kwargs)

    def _coerce(self, value):
        """
        Validates that the values are in self.choices and can be coerced to the
        right type.
        """
        if value == self.empty_value or value in self.empty_values:
            return self.empty_value
        new_value = []
        for choice in value:
            try:
                new_value.append(self.coerce(choice))
            except (ValueError, TypeError, ValidationError):
                raise ValidationError(
                    self.error_messages['invalid_choice'],
                    code='invalid_choice',
                    params={'value': choice},
                )
        return new_value

    def clean(self, value):
        value = super(TypedMultipleChoiceField, self).clean(value)
        return self._coerce(value)

    def validate(self, value):
        if value != self.empty_value:
            super(TypedMultipleChoiceField, self).validate(value)
        elif self.required:
            raise ValidationError(self.error_messages['required'], code='required')
```

**Comment by jessamynsmith** [comment]
Note: I am happy to work on a pull request, but I wanted to see if this is a change you would consider, and how you would like to handle it.

**Comment by tomchristie** [comment]
> I have a ChoiceField defined using an enum, as follows:

I'd be happy to assess this issue, but as currently presented I'd need to go and dig into the implementation of `django_enumfield` in order to determine if this is an issue in how REST framework handles ModelField types, or if it's an unresolvable issue (we don't know anything about that third party package - it may not be possible to automagically generate serializer fields for it), or similar.

Most likely you just need to declare the serializer field for that field explcitly on the class.

Failing that if you can cut this down to an actionable issue presented without any third-party dependancies, then we could reassess it.

**Comment by jessamynsmith** [comment]
I went back and re-wrote my model without the dependencies.
```
CLOT_SIZE_CHOICES = (
    (0, 'Small'),
    (1, 'Medium'),
    (2, 'Large'),
)
class FlowEvent(models.Model):
    clots = models.IntegerField(choices=CLOT_SIZE_CHOICES, default=None, null=True, blank=True)
```
It still fails due to empty string not being a valid value for int. I can work around this as I noted above, by adding a custom ```validate_clots``` method on my serializer class that coerces all empty values to None, similar to the Django forms code.
Traceback is as follows:
```
Traceback:
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/views/decorators/csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/viewsets.py" in view
  85.             return self.dispatch(request, *args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  407.             response = self.handle_exception(exc)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  404.             response = handler(request, *args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/mixins.py" in create
  21.         self.perform_create(serializer)
File "/Users/jessamyn/Development/eggtimer/periods/views.py" in perform_create
  29.         serializer.save(user=self.request.user)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/serializers.py" in save
  164.             self.instance = self.create(validated_data)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/rest_framework/serializers.py" in create
  768.             instance = ModelClass.objects.create(**validated_data)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/query.py" in create
  372.         obj.save(force_insert=True, using=self.db)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/base.py" in save
  589.                        force_update=force_update, update_fields=update_fields)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/base.py" in save_base
  617.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/base.py" in _save_table
  698.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/base.py" in _do_insert
  731.                                using=using, raw=raw)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/query.py" in _insert
  921.         return query.get_compiler(using=using).execute_sql(return_id)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/sql/compiler.py" in execute_sql
  919.             for sql, params in self.as_sql():
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/sql/compiler.py" in as_sql
  877.                 for obj in self.query.objs
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/sql/compiler.py" in <listcomp>
  877.                 for obj in self.query.objs
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/sql/compiler.py" in <listcomp>
  875.                     for f in fields
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/fields/__init__.py" in get_db_prep_save
  627.                                       prepared=False)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/fields/__init__.py" in get_db_prep_value
  619.             value = self.get_prep_value(value)
File "/Users/jessamyn/.virtualenvs/eggtimer/lib/python3.4/site-packages/django/db/models/fields/__init__.py" in get_prep_value
  1601.         return int(value)

Exception Type: ValueError at /api/v2/periods/
Exception Value: invalid literal for int() with base 10: ''
```

**Comment by tomchristie** [comment]
Okay, that looks helpful - could we further break that down into showing the same error, but with a plain Serializer class, rather than a ModelSerializer? Opening the django shell on the above project, and printing the `repr` of the serializer instance will show exactly the serializer class that's been created.

Once it's been narrowed down to a plain serializer class we'll be able to properly asses exactly what needs to be fixed.

**Comment by tomchristie** [comment]
First step - narrowing down to if there's an issue with the modelfield->serializer field mapping, or if there's an issue with some serializer field combinations.

So a model with:

    choices_field = models.CharField(max_length=100, choices=COLOR_CHOICES, blank=True)

will map to this serializer field:

    choices_field = ChoiceField(allow_blank=True, choices=[(u'red', u'Red'), (u'blue', u'Blue'), (u'green', u'Green')], required=False)

The mapping there looks reasonable, but next Q is if `allow_blank` / `required` on a serializer choice field are properly honored.

**Comment by tomchristie** [comment]
We do *have* a test for allow blank on ChoiceField, so surprised behavior wasn't as expected.

https://github.com/tomchristie/django-rest-framework/blob/master/tests/test_fields.py#L1058

**Comment by tomchristie** [comment]
Actually on second thought I think this doesn't present as an issue with char fields (blank is valid) only with non-char fields (that don't end up treating '' as null)

**Comment by tomchristie** [comment]
Right, I *believe* this has since been fixed along the way as we resolved some issues with `None` and HTML inputs. Have added a test case roughly corresponding to this and all passing nicely now.

**Comment by jessamynsmith** [comment]
Thank you for looking at this. My problem is with EnumField specifically, and it not liking '' as a value. It is still a problem in the newer version. I am leaving in my validation for now:

`class FlowEventSerializer(serializers.ModelSerializer):

    class Meta:
        model = period_models.FlowEvent
        exclude = ('user',)

    def _validate_nullable_choice_field(self, value, choices):
        # Coerce empty values to None
        if not value and value not in choices:
            value = None
        return value

    def validate_clots(self, value):
        return self._validate_nullable_choice_field(value, self.fields['clots'].choices)`

**Comment by tomchristie** [comment]
Okay. It's not super clear to me exactly what we do or don't need to do here, but could consider a PR on it's own merits.

If declaring the field explicitly on the serializer provides a way of resolving this then I don't think there's an issue - we can't always determine exactly how a third-party model field should map to a serializer field. On the other hand, if it's the case that our ChoiceField doesn't have sufficiently flexibility to represent this case, even when listed explicitly, then it is possible that we'd accept a fix for that.

**Comment by jessamynsmith** [comment]
If I don't explicitly declare the field in the serializer, then the generated ChoiceField has allow_blank set to False when it hits to_internal_value. If I explicitly declare the field in the serializer with allow_blank=True, then allow_blank is set to True when it hits to_internal_value. This still doesn't fix the problem, unless I change the code to return None instead of empty string. I can see why allow_blank returns an empty string, it just doesn't work for a django_enumfield.EnumField, which inherits from IntegerField. Empty values have to get sanitized somewhere. The most sensible solution might be for me to make a custom DRF Field for these EnumFields.

**Comment by jessamynsmith** [comment]
Leaving a link to my custom field, for posterity: [https://github.com/jessamynsmith/eggtimer-server/commit/d87c7e3c058e65117c5d2340cdde15a9e792cd2c](NullableEnumField)

**Comment by tomchristie** [comment]
👍

**Comment by claytondaley** [comment]
I also ran into this case.  TL;DR the problem is that a `ChoiceField` with `allow_blank=True` will return an empty string which is incompatible with `IntegerField` validation.

Here's the trivial implementation that triggers it:

```
class MyModel(Model):
    # a choices mapping from string => int is essential to the issue
    integer_with_choices = IntegerFIeld(choices=[(0, "a choice')], allow_blank=True)

class MySerializer(ModelSerializer):
    class Meta:
        model = MyModel
```

The UI will typically return either the empty string (i.e. no selection) or the string "a choice".  Now consider the implementation of [`ChoiceField.to_represenation`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L1428):

```
    def to_internal_value(self, data):
        if data == '' and self.allow_blank:
            return ''

        try:
            return self.choice_strings_to_values[six.text_type(data)]
        except KeyError:
            self.fail('invalid_choice', input=data)
```

We expect strings from the UI, but the validation (from `IntegerField`) expects an `int`.  If the string is in the `choices` list, it gets converted into an `int` and all is well.  If the blank string is sent, it triggers the first clause and returns the empty string.  This gets passed to the min/max validators for `IntegerField`.  The resulting comparisons are invalid (e.g. `<str> < <int>`).

In theory, the "fix" is to treat the empty string as a null value (which is what it means semantically).  Since the empty string is valid for some `ChoiceField` (e.g. backed by a `CharField`), the requirement is situational. Some viable alternatives are:

 - Offer a flag like `blank_is_null` that returns `None` instead of the empty string (this could be useful in other cases)
 - Inject `{'': None}` into the choices array in the appropriate cases
 - Adjust min/max validators to treat empty strings as null (but this will likely blow up later)

This second bullet is the best workaround while the issue is open, but this is an extremely common case (i.e. an `IntegerField` with string choices) so it's worth handling correctly in DRF.

**Comment by claytondaley** [comment]
So my example may not be exactly the same.  I missed the fact that the `ChoiceField` for an `IntegerField` is the (stringified) array of the integer values of the choices and not the strings part of the choices meant for display/use.

**Comment by claytondaley** [comment]
OK.  My analysis of ***this*** error is still correct.  I'm running into the same issue for the same reason.  Unfortunately, my proposed "workaround" doesn't work because a mapping like `(None, '')` is blown away in `_set_choices` (which only preserves the empty string).

I also have a deeper problem because I actually want the API to match/accept the string values from the model's `choices` and the `ChoiceField` instead matches the stringified version of the integers.  However, it's not directly related to this bug.

**Comment by claytondaley** [comment]
... an extra wrinkle as I work through the general issue.  Unfortunately, the sequence in `run_validation` means that you can't translate the empty string into `None`.  Specifically, the check for `is_empty_value` comes before `to_internal_value` so returning `None` from `to_internal_value` means that it is passed on to the validators and also fails with an exception (e.g. when it runs a comparison like `None < <int>`).

    def run_validation(self, data=empty):
        (is_empty_value, data) = self.validate_empty_values(data)
        if is_empty_value:
            return data
        value = self.to_internal_value(data)
        try:
            self.run_validators(value)
            ...

**Comment by claytondaley** [comment]
In case it doesn't get fixed, my workaround is currently a custom `ChoiceField` that includes:

    def validate_empty_values(self, data):
        if data == '':
            if self.allow_blank:
                return (True, None)
        return super().validate_empty_values(data)

This translates blank into an empty value early enough to bypass validation.

My solution to the other issue (i.e. accepting the right-hand strings, not integers) is found in [this SO answer](https://stackoverflow.com/a/53378092/1978687).

**Comment by darrin-tomboy** [comment]
@jessamynsmith https://stackdev.space/questions/setting-the-maximum-length-on-an-integerfield-in-django-rest-may-be-done-by-utilizing-the
