### ISSUE TITLE
AuthenticationFailed with JSONRenderer doesn't properly print lists

### ISSUE THREAD

**Issue by nottrobin** [tomchristie/django-rest-framework#2627]
If I run the following with the `JSONRenderer`:

```
raise AuthenticationFailed(detail=['one', 'two'])
```

In version `2.3.13` of `djangorestframework` this correctly output:

```
{"detail": ["one", "two"]}
```

But if I upgrade to `3.0.5` it incorrectly outputs:

```
{"detail": "['one', 'two']"}
```

Outputting the list as a string representation, rather than an array.

**Comment by tomchristie** [comment]
Closing as per #2341.
