### ISSUE TITLE
Consider always returning a QuerySet in paginate_queryset

### ISSUE THREAD

**Issue by JockeTF** [tomchristie/django-rest-framework#2629]
The` paginate_queryset` method of the built in `Pagination` classes return objects of varying type.

- `PageNumberPagination.paginate_queryset` returns a `Page`.
- `LimitOffsetPagination.paginate_queryset` returns a `QuerySet`.
- `CursorPagination.paginate_queryset` returns a `list`.

I suggest that these methods should all return a `QuerySet`.

I need to perform optimizations *after* pagination since I depend on having a complete list of object IDs for raw queries. However, since I also make calls to `annotate` and `prefetch_related` within my optimizers I still would like access to the `QuerySet`.

This makes performing optimizations for list views more difficult since I have to take the different `instance` types into account. Switching from `PageNumberPagination` to `CursorPagination` would also be problematic since I would no longer have a `QuerySet` to work with.

**Comment by tomchristie** [comment]
Thanks @JockeTF I'll take a look at this as I'm tying stuff up tomorrow and later this week.

**Comment by tomchristie** [comment]
We can't make it always be a queryset, as it may not even have been passed a queryset as input (it could just as validly be a plain list) However it would be more consitent if the returned pages were always exposed as plain lists, which they now are.

**Comment by JockeTF** [comment]
I don't think using lists would work for [CursorPagination](https://github.com/tomchristie/django-rest-framework/blob/f7917928/rest_framework/pagination.py#L500-L504) as it is now. Also. perhaps the `queryset` parameter should be renamed to `object_list` or similar to make the intention a bit more clear?

As a side note, this change forces me to either write my own paginator or make optimizations in two steps (pre and post pagination). I'm not against that though since making the optimizations in two steps may actually be better since it makes it clear when the `QuerySet` is going to be evaluated.

**Comment by tomchristie** [comment]
Yes your correct that CursorPagination requires the .order_by interface. Not sure exactly where you mean wrt queryset / object_list but *may* be sensible. Happy with the "return a list" style. Previously only constraint was that'd it'd be an iterable, better to be more consistent there.

**Comment by rishi1804** [comment]
@JockeTF @tomchristie  I am getting a dictionary/list as a result from elasticsearch I want to use CursorPagination with that data . How can I pass that to paginate_queryset?
plz help

**Comment by JockeTF** [comment]
I don't think you can use `CursorPagination` unless you're paginating something that has an `order_by` method.

`CursorPagination` is meant to be used with Django's `QuerySet`. I'd recommend either looking up the objects you get back from Elasticsearch via your [models](https://docs.djangoproject.com/en/3.0/topics/db/models/), or finding another way to paginate the results.

Either way, this discussion may be better suited for the [discussion group](https://groups.google.com/forum/?fromgroups#!forum/django-rest-framework)!
