### ISSUE TITLE
How to resolve the Reverse URL by more than one parameter in URL.

### ISSUE THREAD

**Issue by abdulwahid24** [tomchristie/django-rest-framework#2632]
Looks like this issue exist since long time as there is no solution for http://stackoverflow.com/questions/21047384/reverse-url-by-more-than-one-parameter-in-django-rest-framework since one year. 
I though to create the issue here.

Let's take the usual **Customers** with **Orders** pair of models.

How can we make a HyperlinkedModelSerializer of Order url field reverse to a url like 

`/customers/<customer_pk>/orders/<order_id>/?`

I thought of using the lookup_field in the Meta class but it seems to only accept one field.

Thanks for your help

**Comment by tomchristie** [comment]
Usage questions are best directed at [the discussion group](https://groups.google.com/forum/#!forum/django-rest-framework).

The issues list is reserved for managing work on active bugs, features and other improvements.
