### ISSUE TITLE
Feature request: support protocol for default serializer on fields

### ISSUE THREAD

**Issue by matthewwithanm** [tomchristie/django-rest-framework#2633]
We discussed this previously in matthewwithanm/django-imagekit#289, but it came up on another project so I figured I'd open an issue.

It would be really awesome if DRF allowed fields to define their own default serializer using a simple interface. (I figure it would work something like [`formfield`][1].) This would allow authors of custom fields to bundle serializers for DRF that support common usages and don't rely on how the object is `str`'d.

Thanks!

[1]: https://docs.djangoproject.com/en/1.7/howto/custom-model-fields/#specifying-the-form-field-for-a-model-field

**Comment by xordoquy** [comment]
@matthewwithanm I don't see why a project would define its own serializer. It may use a custom field which is something already possible imho.
I'd like more specific details about what you feel isn't correct at the moment.

**Comment by matthewwithanm** [comment]
Sorry, I'm not following what you're saying. I'm not saying something is incorrect, just asking for a new feature.

If I create a library that contains a custom model field, I'd like to be able to bundle a default serializer with it so that those who use both my library and DRF will get useful serialization out of the box. In other words, users won't have to define a serializer field, it'll "just work."

**Comment by xordoquy** [comment]
@matthewwithanm I feel that what you described should already be possible therefore I'm lost.
In particular, I don't get this part "DRF allowed fields to define their own default serializer"
Serializers is what the developers - not the library ones - will define. Why would they have one by default ?

**Comment by matthewwithanm** [comment]
> Serializers is what the developers - not the library ones - will define. Why would they have one by default ?

So that the developers consuming the library don't have to define one.

DRF [is already mapping Django model fields to serializer fields][1]. What I'm proposing is genericizing this so that third-parties can benefit too. The same arguments that apply for providing a default mapping for, say, [django.db.models.EmailField][2] apply here.


[1]: https://github.com/tomchristie/django-rest-framework/blob/f7917928c080aa0b055cbfc588f61ec01f16771c/rest_framework/serializers.py#L694-L736
[2]: https://github.com/tomchristie/django-rest-framework/blob/f7917928c080aa0b055cbfc588f61ec01f16771c/rest_framework/serializers.py#L719

**Comment by tomchristie** [comment]
The feature request completely makes sense, but I don't particularly see this as a priority, so I'm going to currently treat this as out-of-scope.

**Comment by xordoquy** [comment]
@matthewwithanm I get your point, but you could import ModelSerializer and do something similar to:
```
ModelSerializer. serializer_field_mapping[MyModelField] = MySerializerField
```

**Comment by matthewwithanm** [comment]
@xordoquy Yeah, I linked to that code in my above comment so I'm certainly aware I could do something like that (: But `serializer_field_mapping` is hardly part of the public API (it wasn't even named that in 2.x). What I'm really after is a sanctioned way for third-party model fields to provide default serialization.

@tomchristie Understood. Is this something for which a PR would be considered?

**Comment by xordoquy** [comment]
@matthewwithanm maybe we could simply create a public function that will perform the above code and we'll simply maintain that function to match our internal representation.
@tomchristie does it sound like a sensible tradeoff ?

**Comment by tomchristie** [comment]
> Is this something for which a PR would be considered?

A good (non-coding) preliminary step might be to demonstrate two or three third party applications that *would* actually make use of this API if it existed. That'll help us make a judgement call on how worthwhile it'd be vs. the ongoing cost of the extra API, documentation, implementation it'd introduce.
