### ISSUE TITLE
Recommend django-rest-framework-jwt for token authentication

### ISSUE THREAD

**Issue by jpadilla** [tomchristie/django-rest-framework#2644]
As per a previous conversation with @tomchristie, we're wondering if we should be recommending [djangorestframework-jwt](http://getblimp.github.io/django-rest-framework-jwt/) as a preferred package for *proper* token authentication.

**Comment by maryokhin** [comment]
It would be interesting if more context would also be given on when we should use OAuth and when JWT for API authenticated, in which case one is better than the other and what is to be considered in each case.

**Comment by kevin-brown** [comment]
If you mean recommending it over the default `TokenAuthentication`, I'm fine with that. `TokenAuthentication` is lacking some useful things (token rotation, expiration, etc), and [most people are looking for more](http://stackoverflow.com/q/27852639/359284).

If you're recommending it as the go-to token authentication, I'm less enthusiastic about that. Both it an OAuth have their pros and cons ([social auth support, as a starter](http://stackoverflow.com/q/27051209/359284)) and I'd rather see that be called out in the documentation.

**Comment by jpadilla** [comment]
@kevin-brown definitely not as the only go-to token authentication, but I think it'd be good to recommend it and `django-oauth-toolkit` over the default `TokenAuthentication` because that is meant to be a simple implementation to get you up and running with tokens but lacks x, y, and z which for bigger/production applications most people are looking for more.

As as you said both it and OAuth have their pros and cons which should be interesting to discuss in the docs now that we're also recommending Django OAuth Toolkit for OAuth 2.0 in the docs.

**Comment by tomchristie** [comment]
Would be happy enough to consider docs PRs for this, but not overly fussed about what we do here right now. Going to close this off right now as not significant.
