### ISSUE TITLE
German translation for `min_value` field error message references `max_value`.

### ISSUE THREAD

**Issue by fabianbuechler** [tomchristie/django-rest-framework#2645]
The German translation for the `min_value` error message in `IntegerField`,`FloatField` and `DecimalField`, which is:

```python
'min_value': _('Ensure this value is greater than or equal to {min_value}.'),
```
references `max_value`, which leads to errors when `.format()`-ing this string.

See:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/locale/de/LC_MESSAGES/django.po#L150

```
#: fields.py:659 fields.py:693 fields.py:726
msgid "Ensure this value is greater than or equal to {min_value}."
msgstr "Stelle sicher, dass dieser Wert größer oder gleich {max_value} ist."
```

The relevant part of the error is:
```python
  File "###/.virtualenvs/bk/lib/python3.4/site-packages/rest_framework/fields.py", line 755, in __init__
    message = self.error_messages['min_value'].format(min_value=self.min_value)
  File "###/.virtualenvs/bk/lib/python3.4/site-packages/django/utils/functional.py", line 135, in __wrapper__
    return self.__dispatch[t][funcname](res, *args, **kw)
KeyError: 'max_value'
```

**Comment by fabianbuechler** [comment]
Good response time, Tom :thumbsup:

**Comment by tomchristie** [comment]
Well, ain't fixed it yet, but hey it's a start!
You can sign up to the translation team here if you wanted to help get it resolved... https://www.transifex.com/projects/p/django-rest-framework/

**Comment by fabianbuechler** [comment]
Signed up.

**Comment by Wirzi** [comment]
Same problem here using the PositiveIntegerField.

**Comment by fabianbuechler** [comment]
Just submitted a fix for the translation in transiflex. No idea what the next step is, since I never used transiflex before.

**Comment by tomchristie** [comment]
@fabianbuechler Thank you! You don't need to do anything more - we'll pull in the latest translations and release with 3.1.1.

I'll leave this ticket open until we've pull the latest translations.

**Comment by tomchristie** [comment]
Resolved by c573e7b4a8b4fedfe70b934571284d84e9a81103

**Comment by Wirzi** [comment]
Thanks!

**Comment by tomchristie** [comment]
Welcome - release should be coming soon.
