### ISSUE TITLE
Field level validation method not called if value is null

### ISSUE THREAD

**Issue by delinhabit** [tomchristie/django-rest-framework#2649]
Hello,

I'm porting to DRF 3.1 and I have the following issue:

I have a use-case where sending `null` as a value for a field means unsetting a flag. I also need to enforce that this operation is valid only when`self.instance` is in a particular state. An obvious thing to do is to implement this in the `validate_<field_name>` method on the serializers (since `null` is a valid value I can expect).

The problem is that `validate_<field_name>` is not called if the received value is None, even if `allow_null` is set to True on the field ([here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L401) is the relevant code block).

I can work on a PR if this is accepted as an issue of course. I'm not sure how to fix the problem in the mean-time. Of course I can do the validation in `validate()` but it's not intuitive, since the validation is done for the value of that field and is not an object level validation. This was used to work in DRF 2.x.

Thanks,
Ion

**Comment by kevin-brown** [comment]
> here is the relevant code block

Perhaps I'm missing something (only looked quickly) but that link is just checking to make sure that the validation method (`valid_fieldname`) exists before calling it.

**Comment by delinhabit** [comment]
Yeah, sorry, it was an oversight on my part. 

I'm not sure yet how validation is handled in detail, but the fact is that `valid_<fieldname>` is not called if the value is None.

I'll investigate more.

**Comment by delinhabit** [comment]
So I investigated more and it seems to be a problem on our side. Apparently `validate_<fieldname>` in our use-case was being called in DRF 2.x, but it's no more called in DRF 3.1. 

I could say it was an issue in DRF 2.x that was fixed in DRF 3.1 :)

Thanks!
