### ISSUE TITLE
pagination: cache queryset.count() for performance reasons

### ISSUE THREAD

**Issue by dnelson86** [tomchristie/django-rest-framework#2650]
Hi,

Motivation: I have a partitioned InnoDB database which has ~10M rows per partition. A COUNT(*) on any partition (with or without additional WHERE clauses) takes a few seconds.

In pagination, when walking through the pages, the pagination._get_count() function is called each time, which executes this "global" count each time. In my use case, this can be quite a problem.

I would prefer if pagination_class.paginate_queryset() cached the count, depending on filtering, etc.

My current hack is to replace:
```
    def paginate_queryset(self, queryset, request, view=None):
        self.count = _get_count(queryset)
```
with e.g.
```
    def paginate_queryset(self, queryset, request, view=None):
        from django.core.cache import cache

        cache_key = request.path
        skipGetKeys = ['offset','limit']
        filter_query = [key+value for key,value in request.GET.iteritems() if key not in skipGetKeys]
        cache_key += '_'.join(filter_query)
        
        self.count = cache.get(cache_key)

        if self.count == None:
            self.count = _get_count(queryset)
            cache.set(cache_key,self.count,None)

```
I'm not sure how general this is, but I think could be useful for some cases (for me, each paginated REST response then takes ~300ms instead of ~5000ms).

**Comment by tomchristie** [comment]
Totally reasonable request, but best implemented as a custom pagination class.
You might also consider wrapping it up as a third party package.

**Comment by X17** [comment]
Hey @dnelson86 ,

thanks for suggestion; i worked on the custom class and followed @tomchristie . kindly have a look and do check the implementation

**Comment by jcushman** [comment]
Here's an implementation of the custom class that is a little more robust:

- should work with `PageNumberPagination`, `LimitOffsetPagination`, or custom paginators
- doesn't require duplicating code from DRF, so less likely to break on upgrades
- robust to any filters on the queryset, since the cache key is created by hashing the SQL query instead of inspecting the request

Monkeypatching is unfortunately necessary to get this to work -- the cleaner alternative would require some DRF refactoring to add a `BasePaginator.get_count(self, queryset)` method that could be overridden. 

```
import hashlib
from rest_framework.pagination import LimitOffsetPagination
from django.core.cache import caches


def CachedCountQueryset(queryset, timeout=60*60, cache_name='default'):
    """
        Return copy of queryset with queryset.count() wrapped to cache result for `timeout` seconds.
    """
    cache = caches[cache_name]
    queryset = queryset._chain()
    real_count = queryset.count

    def count(queryset):
        cache_key = 'query-count:' + hashlib.md5(str(queryset.query).encode('utf8')).hexdigest()

        # return existing value, if any
        value = cache.get(cache_key)
        if value is not None:
            return value

        # cache new value
        value = real_count()
        cache.set(cache_key, value, timeout)
        return value

    queryset.count = count.__get__(queryset, type(queryset))
    return queryset


class CachedCountLimitOffsetPagination(LimitOffsetPagination):
    def paginate_queryset(self, queryset, *args, **kwargs):
        if hasattr(queryset, 'count'):
            queryset = CachedCountQueryset(queryset)
        return super().paginate_queryset(queryset, *args, **kwargs)
```
