### ISSUE TITLE
Wrong placeholder in german l10n string (v3.1.0)

### ISSUE THREAD

**Issue by mkemmerling** [tomchristie/django-rest-framework#2653]
There is a wrong placeholder in _locale/de/LC_MESSAGES/django.po_, line 150:

<pre>
#: fields.py:659 fields.py:693 fields.py:726
msgid "Ensure this value is greater than or equal to {min_value}."
msgstr "Stelle sicher, dass dieser Wert größer oder gleich {max_value} ist."
</pre>

The translation string should clearly include _min_value_ instead of _max_value_.

**Comment by jpadilla** [comment]
Duplicate of https://github.com/tomchristie/django-rest-framework/issues/2645

**Comment by mkemmerling** [comment]
Oops,I  just wanted to close the issue myself. Sorry for not checking before committing.
