### ISSUE TITLE
Managing Transifex and translations

### ISSUE THREAD

**Issue by jpadilla** [tomchristie/django-rest-framework#2654]
Not sure if it's possible but I think that the maintenance team should be able to manage the Transifex project to review and handle requests to join translations. It might also be part of the release process and release manager's responsibility to download any new translations before a new release .

**Comment by tomchristie** [comment]
:+1:

**Comment by jpadilla** [comment]
@xordoquy should we add a note to the release process about downloading translations from transifex?

**Comment by xordoquy** [comment]
I didn't read the thread about it yet but we should definitively add some directions about this.

**Comment by tomchristie** [comment]
Just an extra bullet point in the release checklist "Synchronize latest translation strings" with a link to http://www.django-rest-framework.org/topics/project-management/#translations could be sufficient.

**Comment by xordoquy** [comment]
I just realized I haven't downloaded the translation during the latests releases.
Will try to add a step in setup.py to get this working.

**Comment by xordoquy** [comment]
There seems to be 3 pending requests for new languages but I don't seem to be able to accept them.

**Comment by kevin-brown** [comment]
> There seems to be 3 pending requests for new languages but I don't seem to be able to accept them.

Ditto. [Can't find the "Edit languages" button.](http://docs.transifex.com/features/teams#adding-languages-to-a-project)

**Comment by tomchristie** [comment]
I've accepted them for now.

Should look like this?...

![image](https://cloud.githubusercontent.com/assets/647359/7931849/c6c9583a-090b-11e5-8370-e7597d032707.png)

**Comment by xordoquy** [comment]
Actually I didn't have this popup. Only a list of 3 languages that were waiting. No matter where I clicked, I failed to get the popup or something similar.

**Comment by tomchristie** [comment]
Okay we can review if the issue reoccurs.
I've an occassion in the past where there was an odd glitch in the transifex UI, so let just assume it'll sort itself out, unless continues to be an issue.

**Comment by tomchristie** [comment]
We'll consider this issue closed once there's an extra bullet point on the release checklist, here...

http://www.django-rest-framework.org/topics/project-management/#release-process

**Comment by xordoquy** [comment]
I confirm the translation assignment now works - at least in my case.
I'm closing this as the last point has been merged.
