### ISSUE TITLE
Recommended method to test custom throttle classes?

### ISSUE THREAD

**Issue by lightstrike** [tomchristie/django-rest-framework#2657]
I've written a custom throttle based on SimpleRateThrottle and have currently written a test similar to that in test_throttling (https://github.com/tomchristie/django-rest-framework/blob/master/tests/test_throttling.py#L62). 

Is there a better solution? My throttle limits are much higher than 3 which results in my tests taking a while to run.

I'm wondering if there's a way to set a cache value directly and make a single request to return a 429. I recognize this is likely more of a Django question than a DRF question.

**Comment by tomchristie** [comment]
Probably better suited to the discussion group :)

https://groups.google.com/forum/#!forum/django-rest-framework

We reserve the issue tracker for bugs, feature requests and active work on the project.
