### ISSUE TITLE
ModelSerializer - IntegerField broken in 3.1.0

### ISSUE THREAD

**Issue by fpieper** [tomchristie/django-rest-framework#2660]
I get an KeyError u'max_value' in 3.1.0 if one of the fields in the code below is an IntegerField
FloatFields and CharFields are working without a problem.

The same code (with all types of fields) works in 3.0.5 like a charm.

```python
class ProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = Profile
        fields = ('rating', 'rating_votes', 'sub_type', 'sub_expire_date', 'language')
```

Or did I miss anything?

Yours
Florian

**Comment by jpadilla** [comment]
@fpieper might this be related to #2645?

**Comment by fpieper** [comment]
yes, it's the same behaviour => duplicate

@jpadilla thanks for your fast reply :)
