### ISSUE TITLE
Extra router kwargs "url_path" seems not include in the docs.

### ISSUE THREAD

**Issue by BrickXu** [tomchristie/django-rest-framework#2662]
Hi @tomchristie ,

I saw a new paramter which named "url_path", was added to the list_router and detail_router for rename the extra action path, but I did not see any of documents about it, both "API Guide" and "3.X announcement". 

Did we miss it ?

**Comment by tomchristie** [comment]
$ ack url_path ./docs
    docs/api-guide/routers.md
    103:If you do not want to use the default URL generated for your custom action, you can instead use the url_path parameter to customize it.
    113:        @detail_route(methods=['post'], permission_classes=[IsAdminOrIsSelf], url_path='change-password')

    docs/topics/3.0-announcement.md
    885:Also note that you should pass the `request` object to the serializer as context when instantiating it, so that a fully qualified URL can be returned. Returned URLs will then be of the form `https://example.com/url_path/filename.txt`. For example:
    891:If the request is omitted from the context, the returned URLs will be of the form `/url_path/filename.txt`.

    docs/topics/release-notes.md
    97:* Ability to customize router URLs for custom actions, using `url_path`. ([#2010][gh2010])

    docs/tutorial/6-viewsets-and-routers.md
    56:The URLs for custom actions by default depend on the method name itself. If you want to change the way url should be constructed, you can include url_path as a decorator keyword argument.
