### ISSUE TITLE
reverse relationship read_only=False

### ISSUE THREAD

**Issue by ebugfix** [tomchristie/django-rest-framework#2664]
Existe alguma maneira em relacionamento reverso configurar como read_only=False, to create and update models ?

Ex:

class PartnerBusinessSerializer(serializers.ModelSerializer):
    contacts = PartnerContactSerializer(many=False, read_only=False)

  def create(self, validated_data):
     ...
     ...
     ...
     return business

This generates the following error when I create a record, but the record is created in my db

AttributeError at /webapp/partners/business/
Got AttributeError when attempting to get a value for field `contacts` on serializer `PartnerBusinessSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `PartnerBusiness` instance.
Original exception text was: 'PartnerBusiness' object has no attribute 'contacts'.

**Comment by tomchristie** [comment]
This is currently framed as a usage issue, rather than an actionable bug report.

**Comment by tomchristie** [comment]
The discussion group is the best place for this sort of open-ended query... https://groups.google.com/forum/#!forum/django-rest-framework
