### ISSUE TITLE
Question: HyperlinkedModelSerializer

### ISSUE THREAD

**Issue by keradus** [tomchristie/django-rest-framework#2669]
Hi!

I want to use serializer like
```python
class FooSerializer(HyperlinkedModelSerializer):
    class Meta:
        model = Foo
```

Then, on serializing result I have all fields of my Foo model, but without pk and with url.
What I want to achieve is to get both pk and url fields.
I know I could set Meta.fields and there put all my fields explicitly, but then I should do it in all my serializers.

Therefore I want to override `get_default_field_names`, I do it inside my FooSerializer, but if wont run my method at all :(
Could you help with it please?

**Comment by tomchristie** [comment]
In the `Meta` section use `fields = ('pk', 'url', ...)`.
That will actually work just fine on either ModelSerializer or HyperlinkedModelSerializer.
The discussion group is the right sort of place for this type of question: https://groups.google.com/forum/#!forum/django-rest-framework

Thanks! :)

**Comment by keradus** [comment]
From my prev. msg:
> I know I could set Meta.fields and there put all my fields explicitly, but then I should do it in all my serializers.

:(

**Comment by keradus** [comment]
Ref: https://groups.google.com/forum/#!topic/django-rest-framework/BduH9WXZwvk

**Comment by tomchristie** [comment]
A new base class and override `get_default_field_names` if you *really* don't want to include that...

See:

* https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L945-955
* https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L1368-1378

**Comment by keradus** [comment]
```python
class FooSerializer(HyperlinkedModelSerializer):
    class Meta:
        model = Foo
```

Returns fields: url, data

```python
class FooSerializer(HyperlinkedModelSerializer):
    class Meta:
        model = Foo
        fields = ("url", "data", "pk", )
```

Returns fields: url, data and pk

```python
class HyperlinkedAndIdModelSerializer(serializers.HyperlinkedModelSerializer):
    pass

class FooSerializer(HyperlinkedAndIdModelSerializer):
    class Meta:
        model = Foo
```

Returns fields: url, data and pk

But...

```python
class HyperlinkedAndIdModelSerializer(serializers.HyperlinkedModelSerializer):
    def get_default_field_names(self, declared_fields, model_info):
        return ("pk", )

class FooSerializer(HyperlinkedAndIdModelSerializer):
    class Meta:
        model = Foo
```

still returns url, data and pk, not only pk.
(yeah, it's minimal case to show problem with overriding `get_default_field_names` method, it should call super and add pk when it start working.

What am I missing ?
