### ISSUE TITLE
Option to Use Password Input Widget in Browsable API

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2675]
Some way of telling the browsable API to use a [Password Input Widget](https://docs.djangoproject.com/en/1.7/ref/forms/widgets/#passwordinput) for certain fields.

**Comment by jpadilla** [comment]
You can specify `style` in your serializer field. Check out the [core arguments](http://www.django-rest-framework.org/api-guide/fields/#core-arguments) for serializer fields.

```python
# Use <input type="password"> for the input.
password = serializers.CharField(
    style={'input_type': 'password'}
)
```

**Comment by tomchristie** [comment]
As @jpadilla noted yeah.
More formally, a public HTML forms API is due to land with 3.2.
