### ISSUE TITLE
Python 3.4, Django 1.7, Restframework 3.1.0: AttributeError: 'RegexURLResolver'

### ISSUE THREAD

**Issue by jh222xk** [tomchristie/django-rest-framework#2676]
When using Python 3.4, Django 1.7 and Restframework 3.1.0 I get this [error](https://api.travis-ci.org/jobs/54086393/log.txt?deansi=true):

I had to downgrade to Restframework 3.0(3) for it to work...

**Comment by JockeTF** [comment]
The XML support has been moved into an external package:

https://github.com/jpadilla/django-rest-framework-xml

See the [3.1 announcment](http://www.django-rest-framework.org/topics/3.1-announcement/) for a list of all changes.

**Comment by jpadilla** [comment]
@JockeTF yeap, thanks for clarifying that.

@jh222xk `AttributeError: 'module' object has no attribute 'XMLRenderer'` is the root of your problems.

**Comment by jh222xk** [comment]
Oh, I see. My bad, thanks guys!
