### ISSUE TITLE
old-release-notes is 404

### ISSUE THREAD

**Issue by groovecoder** [tomchristie/django-rest-framework#2681]
http://www.django-rest-framework.org/old-release-notes is 404. I'm looking for release notes between 2.3.8 and 3.0.

**Comment by xordoquy** [comment]
You can still access them through the repository (https://github.com/tomchristie/django-rest-framework/blob/master/docs/topics/2.3-announcement.md)

**Comment by xordoquy** [comment]
ok, the url was provided by http://www.django-rest-framework.org/topics/release-notes/ (at the bottom).

**Comment by xordoquy** [comment]
@groovecoder meanwhile, please use https://github.com/tomchristie/django-rest-framework/blob/version-2.4.x/docs/topics/release-notes.md

**Comment by groovecoder** [comment]
Yeah, it would be fine to just update the docs site with a link straight to the topics folder on GitHub:

https://github.com/tomchristie/django-rest-framework/tree/master/docs/topics
