### ISSUE TITLE
Is 3.1.0 the only secure release?

### ISSUE THREAD

**Issue by groovecoder** [tomchristie/django-rest-framework#2684]
The [requires.io monitoring repo only includes version 3.1.0 as a secure release](https://github.com/requires/monitoring/blob/master/requirements.txt#L37-L39)? Is that true?

**Comment by xordoquy** [comment]
We don't have enough ressources to maintain several branches relating security so there's no reason to monitor the other versions.

**Comment by groovecoder** [comment]
For the sake of my future self who might come back here later ... That's a "Yes, the only branch we maintain with security fixes is the 3.1.0 branch."

Right?

**Comment by xordoquy** [comment]
@groovecoder Let's say it's the latest stable branch (master in the repository) which is 3.1.x at the moment. Once 3.2.x will be released the 3.1.x will not be maintained.
I guess if we have a lot of feedback about maintaining security with 2.4.x we might do something about it.

**Comment by tomchristie** [comment]
> The requires.io monitoring repo only includes version 3.1.0 as a secure release? Is that true?

I don't know what the requires.io monitoring repo does/is.
We have some structure around this (eg a private security mailing list), but we don't yet have a formal policy on backporting security fixes. Currently we'd judge severity on a per-issue basis.
