### ISSUE TITLE
Adding field_class to the extra_kwargs

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2686]
In some of my Serializer classes I take advantage of `extra_kwargs` to change some of the behavior of the fields auto generated by the `ModelSerializer`. I like this approach relative to being explicit and specifying the field because that way if I make changes to the `Model` those changes are picked up automatically (DRY).

That being said there does not seem to be any way to specify the class used for the field. Right now that class is resolved from `serializer_field_mapping`. My use case is that I want to use a subclass of the standard `CharField` Serializer for one of my fields. I would prefer to not have to explicitly specify the full field including class for the reasons mentioned above (for example if the  max length changes on the model, I would like to pick up the change).

I suggest adding `field_class` as a valid option in `extra_kwargs`.

**Comment by tomchristie** [comment]
Going to treat the project as being largely in feature freeze until all the kickstarter work is fully delivered to allow us to keep fully focused. We can review feature requests after that if re-raised, but at the moment I'm inclined for us to de-prioritize and close off most feature requests, unless clearly needed.

**Comment by cancan101** [comment]
Thoughts on re-opening this?

**Comment by tomchristie** [comment]
Not really in favor of extra shortcuts in `ModelSerializer`.

**Comment by sshishov** [comment]
How to make to possible now in 2024. We have exactly the same case, we would like to override the field class for one field only.
