### ISSUE TITLE
Translations. Chinese `zh-cn` should become `zh-hans`.

### ISSUE THREAD

**Issue by larryhq** [tomchristie/django-rest-framework#2688]
zh-cn will expired in Django1.9, the new format is zh-hans, but drf3.1.0 does not support this type of language.

**Comment by tomchristie** [comment]
Are you able to provide any more info, links, what we need to do exactly?
Is this just a case of changing the language code / file names?

**Comment by larryhq** [comment]
In drf3.1's Internationalization, i want to translationed the error response . In dango now chinese is config in settings.py like this:
```
LANGUAGES = (
    ('zh-hans', _('Simplified Chinese')),
    ('zh-hant', _('Traditional Chinese'))
)
```
but zh-hans is not support in drf3.1.so, I can't translationed the error response to chinese

**Comment by tomchristie** [comment]
Which of the two language dialects do our current translations match best?

**Comment by larryhq** [comment]
both can, but because of zh-cn is expired in django1.9,so, my settings.py's language config is zh-hans.

**Comment by tomchristie** [comment]
Okay, so let's plan to update `zh-cn` to `zh-hans` then?
In 1.9 does Django simply drop the previous language key? What about users who have that currently in their cookie language settings or whatever?

**Comment by tomchristie** [comment]
Updated the title of this to reflect what sounds like the right action based on this conversation.

**Comment by deronnax** [comment]
zh-cn will become zh-hans ("simplified", mostly used in China), and zh-tw will become zh-hant ("traditional", mostly used in Taïwan). https://docs.djangoproject.com/fr/1.7/internals/deprecation/#deprecation-removed-in-1-9
I don't the answers to the other question :)

**Comment by tomchristie** [comment]
Thanks @deronnax - that's really helpful.

**Comment by nypisces** [comment]
Will this be update at 3.3.0?

**Comment by xordoquy** [comment]
This will be added once we have Django 1.9 support

**Comment by nypisces** [comment]
When will this be support?

**Comment by xordoquy** [comment]
oh wait, this is already ongoing with Django, my bad.
I just added the two languages to the transifex platform. Feel free to join then.

**Comment by nypisces** [comment]
Can not join the team.

**Comment by wtx358** [comment]
In version 3.3.2, I found `zh-Hans` and `zh-Hant` in `locale` folder, but when I set `LANGUAGE_CODE = 'zh-hans'` in django settings, the API response is not Chinese.

So I look up django's `locale` folder, I can see `zh_Hans` and `zh_Hant`, but in drf3.3.2's `locale` folder, they are `zh-Hans` and `zh-Hant`.

**Comment by xordoquy** [comment]
Already solved in #3739 thanks to @nypisces

**Comment by nypisces** [comment]
Need update from tx，rename folder 'zh-Hans' to 'zh_Hans', and 'zh-Hant' to 'zh-Hant'. now the folder name still error.

**Comment by xordoquy** [comment]
Bumping this issue.
@nypisces sorry to bother you. Our transifex issues should now be fixed but my understanding of the translation is extremely basic.
Do we still have issues with `zh-Hans` and `zh_Hant` ?

**Comment by nypisces** [comment]
@xordoquy like [Django](https://github.com/django/django/tree/master/django/conf/locale), zh_Hans and zh_Hant is correct, DRF still have wrong folder(zh-Hans & zh-Hant)

**Comment by xordoquy** [comment]
That's weird, folder name seems to be correct. Could this be this line: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/locale/zh_Hant/LC_MESSAGES/django.po#L17 ?

**Comment by nypisces** [comment]
1. review https://www.transifex.com/django-rest-framework-1/django-rest-framework/language/zh-Hans/ 
translate & review https://www.transifex.com/django-rest-framework-1/django-rest-framework/language/zh-Hant/
2. delete https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/locale/zh_Hans/
delete https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/locale/zh_Hant/
3. sync from transifex again`tx pull -a`

**Comment by xordoquy** [comment]
@nypisces thanks a lot for your guidance !
