### ISSUE TITLE
FR: Response(None) return 204 status code

### ISSUE THREAD

**Issue by BraisGabin** [tomchristie/django-rest-framework#2692]
This is a *feature* request. I'm not even sure if it's a feature... anyway for me this have sense:
```python
return Response(None)  # status code 204
return Response('')    # status code 200
```
If I return `Response(None)` the status code should be 204, isn't it? Right now it returns 200. I think that my proposal follows better the HTTP Standard. I know, all this is very philosophical, it's just my two cents for this great framework.

**Comment by tomchristie** [comment]
Nothing wrong with the feature request, but it'd be an unneeded bit of extra, implicit behavior.
Let's just stick with what we've got for now.

    return Response(status=204)

**Comment by maryokhin** [comment]
You meant `return Response(status=status.HTTP_204_NO_CONTENT)`? :P
