### ISSUE TITLE
Have perform_create in CreateModelMixin return the object

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2699]
Here: https://github.com/tomchristie/django-rest-framework/blob/4248a8d3fc725d9ae3fe7aaaad7ee12479ab07ab/rest_framework/mixins.py#L25
change:
```python
    def perform_create(self, serializer):
        serializer.save()
```
to
```python
    def perform_create(self, serializer):
        return serializer.save()
```
this will allow subclasses to extend functionality while still calling to parent.

**Comment by tomchristie** [comment]
> this will allow subclasses to extend functionality while still calling to parent.

Don't do that.

Calling `serializer.save()` in the child is simpler and more explicit than hiding the behavior away inside a call to `super`.
