### ISSUE TITLE
Typo Mistake in Pagination Documentation

### ISSUE THREAD

**Issue by anoopmalav** [tomchristie/django-rest-framework#2701]
![screenshot from 2015-03-16 18 12 37](https://cloud.githubusercontent.com/assets/9918965/6666249/8a9fdde2-cc08-11e4-98b4-76d944a33b88.png)

## Setup

To enable the ~~PageNumberPagination~~ style globally, use the following configuration:
To enable the `LimitOffsetPagination` style globally, use the following configuration:

**Comment by tomchristie** [comment]
Thanks! Now resolved.
