### ISSUE TITLE
Issues with Serializers and Querysets

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2709]
This code:
```python
        serializer = ThingSerializer(data=things, many=True)
        serializer.is_valid(raise_exception=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
```
yields:
```
{
    "non_field_errors": [
        "Expected a list of items but got type \"QuerySet\"."
    ]
}
```
whereas changing the `is_valid` call to:
```
        serializer.is_valid(raise_exception=False)
```
works without a problem. Removing that entire line yields:
>When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.

**Comment by carltongibson** [comment]
Again this is a usage question. Please use the mailing list so we can keep the issue tracker for issues. 

(Nonetheless: `things` is a QuerySet, so you're trying to serialise objects from the ORM, in which can you  pass them as the first positional argument, rather than via the `data` kwarg.)
