### ISSUE TITLE
CharField: allow_blank=False in combination with trim_whitespace=True does not behave as expected

### ISSUE THREAD

**Issue by johtso** [tomchristie/django-rest-framework#2710]
The two options can not be used in combination to raise a validation error if the incoming data purely consists of whitespace because `to_internal_value` is not applied before validation.

Is this something that could be changed? And is there a way for me to achieve this behaviour currently without writing custom validation?

**Comment by tomchristie** [comment]
Sounds like a totally valid improvement to make, to me.
