### ISSUE TITLE
Converting ChoiceField keys to strings breaks certain use cases

### ISSUE THREAD

**Issue by johtso** [tomchristie/django-rest-framework#2713]
My choice field keys are integers ("magic numbers"), and I have a special object that represents those magic numbers and compares equal to their integer equivalents (along with a bunch of other useful functionality). I try to use the special object exclusively throughout the codebase for clarity and usability, but some parts of the code still use plain integers.

Previously that worked fine, but the `ChoiceField` has since been changed to convert all the keys to strings, and the inputs to a strings as well.. which breaks this kind of use case. The integer converted to a string does not equal the special object converted to a string.

I'm not sure if what I'm doing is too "out there", or whether what DRF is doing is too presumptuous.

**Comment by tomchristie** [comment]
I'd recommend a custom ChoiceField that's specific to your particular use case.
We could do a better job of documenting any limitations/assumptions with the current choice field, and I'd be happy to accept any pull requests for those.
