### ISSUE TITLE
Patch returning stale data after accessing self.data because I can't figure out how not to!

### ISSUE THREAD

**Issue by dllabs** [tomchristie/django-rest-framework#2715]
Apologies. Keyboard mishap. See next comment.

**Comment by dllabs** [comment]
I'm aware we can't call self.data in validate_field because it causes the api to return stale data. The usual solution is to call data (rather than self.data) in validate (rather than validate_field), so as not to trigger the on-demand creation of self.data.
However, data in validate doesn't contain the fields I need, because they are read only, and validate only has the read/write fields.
So how do I do it? I've read you can call initial_data, but it's not well explained. Is this self.initial_data (which doesn't seem to exist) or what?
Here is my serialiser. I am loathe to make 'question' read/write just so I can access question.validation.regex and self.validation.error_message in validate. How else can I do it?

    class AnswerTableSerializer(serializers.ModelSerializer):
      question = AnswerTableQuestionSerializer(read_only=True)
      questionnaire = AnswerTableQuestionnaireSerializer(read_only=True)

      class Meta:
        model = Answer

      #shouldn't be accessing self.data here because then the api returns stale data. need to find another way.
      def validate(self, data):
        validator = re.compile(self.data['question']['validation']['regex'])
        if not ((validator.match(data['answer'])) or (data['answer']=="")):
            raise serializers.ValidationError(self.data['question']['validation']['error_message'])
        return data

**Comment by maryokhin** [comment]
I don't really understand <i>why</i> you need to validate something that is not inputted by the client (read-only fields), as there's nothing to validate. If you actually do have a writable field that you want to validate against information from other fields you can do this by either accessing `self.instance` in `validate()` or by setting a <a href="http://www.django-rest-framework.org/api-guide/validators/#advanced-default-argument-usage">`HiddenField`</a>
This is more of a discussion question though and should probably be directed to the <a href="https://groups.google.com/forum/#!forum/django-rest-framework">discussion group</a>.

**Comment by dllabs** [comment]
I am validating the user-entered Answer.answer, against the read-only question.validation.regex that is part of the same serializer. The whole serializer is read only, except for the one field that users can change.

**Comment by dllabs** [comment]
Apologies for putting the question in the wrong place. And thanks, self.instance was just the tip I needed. self.instance.question.validation.regex is what I needed to use.
