### ISSUE TITLE
Pagination URL options suggestion

### ISSUE THREAD

**Issue by Brobin** [tomchristie/django-rest-framework#2722]
I am working with the new Pagination API for 3.1 and am finding it difficult to replicate the behavior of the old paginated serializer. In the old version I was able to tell it to just include the query parameters in next and previous links like so:

```json
{
    "previous": null,
    "next": "?page=2",
    "count": 384,
    "courses": []
}
```

Currently in 3.1, it would give me `"http://127.0.0.1/api/courses?page=2"` instead of just `"?page=2"` like I want.

To replicate this behaviour, I had to build my own custom pagination class to exclude the url from the result.

```python
class CoursePaginator(PageNumberPagination):
    def get_paginated_response(self, data):
        return Response({'count': self.page.paginator.count,
                         'next': self.get_next_link(),
                         'previous': self.get_previous_link(),
                         'courses': data})

    def get_next_link(self):
        if not self.page.has_next():
            return None
        page_number = self.page.next_page_number()
        page_number = self.page.previous_page_number()
        return self.custom_url(page_number)

    def get_previous_link(self):
        if not self.page.has_previous():
            return None
        page_number = self.page.previous_page_number()
        return self.custom_url(page_number)

    def custom_url(self, page_number):
        url = self.request.build_absolute_uri()
        url = replace_query_param(url, self.page_query_param, page_number)
        if url is not None:
            url = '?' + url.split('?')[1]
        return url
```

Am I completely missing a way to do this easier, or is this the correct way? If this is the only way, I think it might be useful to include an option in the `get_previous_link()` and `get_next_link()` functions to only include the query paramters.

I can work on implementing this if you think this might be a good feature. I know I would definitely use it. It would be a pretty simple fix and would make my custom paginator much less messy.

**Comment by Brobin** [comment]
It might be worth extending `PageNumberPagination` to implement this and just have a class that does this. Thoughts?

**Comment by Brobin** [comment]
This might also be better handled in `utils/urls.py`

**Comment by umutbozkurt** [comment]
Don't pass `request` to serializer context
URLs will be only query params instead of full URLs

**Comment by Brobin** [comment]
I don't follow what you mean. I am not passing the `request` to the serializer, only to the `CoursePaginator` in my view.

```python
    def get(self, request, format=None):
        queryset = Course.objects.order_by('name')
        paginator = CoursePaginator()
        result_page = paginator.paginate_queryset(queryset, request)
        serializer = CourseSerializer(result_page, many=True)
        return paginator.get_paginated_response(serializer.data)
```

**Comment by tomchristie** [comment]
Sorry I don't understand the request?
Doesn't something like this give you what you want?

    def get_paginated_response(self, data):
        return Response({'count': self.page.paginator.count,
                         'next': "?page=%d" % self.page.next_page_number()
                         'courses': data})

I'm going to close this off, until clarified.

**Comment by Brobin** [comment]
Okay, so I have a search endpoint that has it's own query parameters (search, city, state, etc.) and I'd like to get just the query parameters, not the full url.

If I use `"?page=%d" % self.page.next_page_number()`, a request to `www.example.com?search=foo`, would give me a `next` value of `?page=2`, not `?search=foo&page=2` like the full url would return.

If you look at my custom url function, what it does is it gets the full url and then trims off the query parameters.

Would it be possible to include a configuration option `PAGINATE_FULL_URL` that would dictate whether to return the full url or just the parameters like my custom_url function?

**Comment by tomchristie** [comment]
I'm still not entirely sure how/why that was different before, but anyways...

You might want to take a look at `replace_query_param`, [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/urls.py#L4), and do something similar.

**Comment by Brobin** [comment]
On DRF 3.0.1, for some reason I was getting relative urls instead of absolute urls by using the PaginationSerializer. I'm not sure why it behaved like that either. I'm porting the whole thing to 3.1 now, so I'll just use my custom Pagination for now. Thanks.
