### ISSUE TITLE
Maintainers for Q2, 2015.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2723]
This issue is for determining the maintenance team for the Q2, 2015 period.

Please see the [Project management](http://www.django-rest-framework.org/topics/project-management/) section of our documentation for more details.

---

#### Renewing existing members.

The following people are the current maintenance team. Please checkmark your name if you wish to continue to have write permission on the repository for the Q2, 2015 period.

- [x] @tomchristie
- [x] @xordoquy 
- [x] @carltongibson 
- [x] @kevin-brown 
- [x] @jpadilla

---

#### New members.

If you wish to be considered for this or a future date, please comment against this or subsequent issues.

To modify this process for future maintenance cycles make a pull request to the [project management](http://www.django-rest-framework.org/topics/project-management/) documentation.

**Comment by carltongibson** [comment]
I've not been mega-active this quarter. I'm happy to stay in and continue. Equally if there's someone who's extra keen I'm happy to step aside for the now. 

I'm hanging around either way. (It might be annoying not to be able to even adjust issues but I'm sure I'd cope.)

**Comment by tomchristie** [comment]
@carltongibson How about tick yourself provisionally for now?

**Comment by carltongibson** [comment]
@tomchristie Done :-)

**Comment by tomchristie** [comment]
Okay, so the maintenance team is staying the same for Q2 as it was for Q1.
Thanks all - totally happy with that here! :)

Any folks who *do* want to get involved at that level - the ticket for Q3 will be the right place to comment against in order to request that you be considered.
