### ISSUE TITLE
Project maintainers should also be maintainers in transifex.

### ISSUE THREAD

**Issue by xordoquy** [tomchristie/django-rest-framework#2728]
Could you add me (linovia on transiflex) to the reviewer list ?

**Comment by jpadilla** [comment]
It'd be helpful if we could all. Re: #2654

**Comment by tomchristie** [comment]
Invited @xordoquy, @jpadilla, @carltongibson.
Carlton could you confirm that carltongibson is actually *your* transifex username, and not someone elses?
Also @kevin-brown is 'kevinbrown' your transifex username?

**Comment by carltongibson** [comment]
Yep that's me.

**Comment by kevin-brown** [comment]
"kevinbrown" on Transifex is me.

**Comment by tomchristie** [comment]
Okay, all done!
