### ISSUE TITLE
Optimize Queries to Database

### ISSUE THREAD

**Issue by ankitpopli1891** [tomchristie/django-rest-framework#2730]
I was profiling one of my models to serialize the list of countries against DRF and found the following query was being made to the database.

	'SELECT "const_country"."id", "const_country"."name", "const_country"."iso_code_2", "const_country"."iso_code_3", "const_country"."flag", "const_country"."tld", "const_country"."area", "const_country"."population", "const_country"."phone", "const_country"."postal_code_format", "const_country"."postal_code_regex" FROM "const_country" ORDER BY "const_country"."name" ASC, "const_country"."iso_code_3" ASC, "const_country"."iso_code_2" ASC'

> This query runs in ~.04 seconds.

So, I added the [fields](http://www.django-rest-framework.org/api-guide/serializers/#specifying-which-fields-to-include) to make sure only the fields I need are serialized. The serialization was OK, but the query that ran was exactly the same.

As per my limited knowledge, the following query should fire instead:

	'SELECT "const_country"."id", "const_country"."name", "const_country"."iso_code_2" ORDER BY "const_country"."name" ASC, "const_country"."iso_code_3" ASC, "const_country"."iso_code_2" ASC'

> This query runs in ~.004 seconds.

### Environment:
 - Python 3.4.0
 - SQLite version 3.8.2

> Not sure If I missed something, or the issue actually exist. It would be great if someone can look into the issue.

Thanks
Ankit

**Comment by MattBlack85** [comment]
Why not passing a ValuesQuerySet to your serializer if you need performance?

**Comment by tomchristie** [comment]
Hi @ankitpopli1891,

You can make this optimization by adding `.only()` to your queryset.
We'll be documenting this in the future as part of https://github.com/tomchristie/django-rest-framework/issues/1976
We don't attempt to automatically perform this optimization as it'd add complexity and be difficult to work around when it's not what you need, but it'd be great if someone came out with a third party package for optimized serializer classes.

**Comment by ankitpopli1891** [comment]
@tomchristie Thanks a lot.
