### ISSUE TITLE
Allow to set ALLOWED_VERSIONS per view instead of just having a global setting

### ISSUE THREAD

**Issue by pquentin** [tomchristie/django-rest-framework#2731]
We currently have two APIs managed by Django REST framework in the same Django project: an AJAX API and a REST API. They are in two separate apps.

Some settings can be set per view, like the authentication classes and permission classes. We take advantage of this by using a root view for each app, where we set those. For example, the AJAX API auths with Django sessions, while the REST API uses an access token.

We would like the versions of both APIs to evolve independently, but can't, since ALLOWED_VERSIONS is a global setting. Would a pull request that allows setting the allowed version per view be accepted?

Thanks!

**Comment by tomchristie** [comment]
You can override the `version_class` on a per view basis.

You can also override the behavior of the version classes, which are the only place where `ALLOWED_VERSIONS` is used.

Taken together you should be able to customize things to get whatever versioning behavior you want.

One thing to keep in mind is that you'll need to consider how (or if) you want `reverse` to work between your two different sets of versioning.

**Comment by tomchristie** [comment]
The setting is only used by the version classes, so you can achieve this by subclassing them with whatever alternative behavior you want.

Note that you can set `versioning_class` on a per-view basis if needed. - https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L101

You'll want to think about how you want `reverse` to handle - rev
