### ISSUE TITLE
404 errors with Firefox

### ISSUE THREAD

**Issue by brianmay** [tomchristie/django-rest-framework#2739]
Hello,

With Chrome I get:

2001:44b8:4112:8a02:ae22:bff:fe83:498a - - [22/Mar/2015:19:59:27 +1100] "GET /api/photos/87064/ HTTP/1.1" 200 92063 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36"

With Firefox, I make the same query, and I get:

2001:44b8:4112:8a02:ae22:bff:fe83:498a - - [22/Mar/2015:19:59:59 +1100] "GET /api/photos/87064/ HTTP/1.1" 404 2264 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"

In both cases, the query comes out the same, as displayed by django-rest-framework HTML interface:

GET /api/photos/87064/

There are no other parameters passed or used by this query.

This is Django Rest Framework 3.0.5

Can you think of any reason why the behaviour would vary so much, with the only difference being a different browser?

This is rather confusing. Just to add to the confusion, it seems to vary depending on the one-to-many relationships the object I am trying to access has. Or something like that.

Will continue investigating myself tomorrow. In particular, will see if I can reproduce this using runserver (this is using apache+wsgi).

Thanks

**Comment by tomchristie** [comment]
This sounds like a usage question rather than a bug report. Probably best to start on the discussion list.

**Comment by brianmay** [comment]
Turns out I was brain dead. The difference wasn't the browser, but the fact one had a session that was logged in and the other wasn't. Apologies for the noise.
