### ISSUE TITLE
Add 'format' argument to UUIDField

### ISSUE THREAD

**Issue by ovangle** [tomchristie/django-rest-framework#2740]
Currently I'm maintaining my own version of `serializers.UUIDField`, simply to control the output format (I prefer the hex representation). Would you be open to adding a `format` parameter to the field's initializer which determined the output representation to be one of:

- `'hex_verbose'` (or `None`): Hex formating including hyphens
- `'hex'`: Compact hex representation
- `'int'`: integer representation
- `'urn'`: RFC 4122 URN representation

I'll follow it up with a PR if you've got no problems.

**Comment by ovangle** [comment]
ps. Would it also be possible to make the `relations` model support the possibility of non-primitive primary keys?

**Comment by tomchristie** [comment]
Sounds reasonable - does Django core have anything similar?

**Comment by ovangle** [comment]
No, serialization for the UUIDField in django core is determined by the formats that the database backend accepts. Users only ever see the Uuid object and queries only accept a Uuid object or the compact hex representation. 

The form field class always displays the compact hex representation, although that's not really relevant to applications that use the rest framework, since they are most likely not using django forms. 

As far as relations are concerned, all the relations fields support uuid targets.

**Comment by ovangle** [comment]
Sorry for the delay in submitting a PR for this -- I got distracted doing other things.

I'm having a bit of trouble running the tests, there's a whole lot of `no such table` and similar errors, so for some reason the tests aren't registering the models.

**Comment by thedrow** [comment]
This was resolved in #3000. Can this issue please be closed?

**Comment by jpadilla** [comment]
@thedrow thanks for the reminder.
