### ISSUE TITLE
Allow Header Value Does not Seem to Take in to Account permission_classes

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2751]
I see:
```
Allow: GET, PUT, PATCH, HEAD, OPTIONS
```
even though I am not logged in and have:
```python
permission_classes = (permissions.IsAuthenticatedOrReadOnly, )
```
If I remove: `mixins.UpdateModelMixin`, then the list is reduced to:
```
Allow: GET, HEAD, OPTIONS
```
which shows that the list is aware of the supported methods on the endpoint.

My hope was to use this list in my downstream UI.

**Comment by maryokhin** [comment]
[Allow Header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) (see 14.7 Allow) is supposed to tell clients what methods they are allowed to use when they stumble on a 405 response and to raise discoverability. That being said, permissions don't actually disallow HTTP methods, they might deny some request based on the request method, sure, but that doesn't mean the HTTP client still can't make a request with this method.

**Comment by cancan101** [comment]
According to the [REST cookbook](http://restcookbook.com/HTTP%20Methods/options/):
>If resources require authentication, it is possible that OPTIONS returns more methods once you added authentication headers to the request.

Looking at the [newest RFC](https://tools.ietf.org/html/rfc7231#section-7.4.1), there is not a clear stipulation that "`Allow` Header is supposed to tell clients what methods they are allowed to use when they stumble on a 405 response and to raise discoverability":
> The actual set of allowed methods is defined by the origin server at
   the time of each request.

**Comment by cancan101** [comment]
This is what I am trying out:
```python
    @property
    def allowed_methods(self):
        ret = super(MyViewSet, self).allowed_methods

        my_ret = []
        for method in ret:
            request = clone_request(self.request, method)
            try:
                self.check_permissions(request)
            except (NotAuthenticated, PermissionDenied):
                allowed = False
            else:
                allowed = True
            if allowed:
                my_ret.append(method)

        return my_ret
```
It can likely be optimized to run through this logic only on `OPTION`.

**Comment by tomchristie** [comment]
Okay. We could consider a pull request with something like that, and a couple of tests.

**Comment by cancan101** [comment]
How should this contribution be structured? As a Mixin? On by default.

**Comment by tomchristie** [comment]
Just build the behavior into the base view.
Not ready to say it'll definitely get accepted just yet, but the pull request + tests would be enough for us to base the decision on.

**Comment by cancan101** [comment]
One of the issues that I have uncovered with the above solution is that `self.check_permissions(request)` ultimately calls: into the [csrf middleware](https://github.com/django/django/blob/668d53cd125175eb708cc0af143f47b42cd42153/django/middleware/csrf.py#L103) if [`SessionAuthentication`](https://github.com/tomchristie/django-rest-framework/blob/4248a8d3fc725d9ae3fe7aaaad7ee12479ab07ab/rest_framework/authentication.py#L121) is in use. This then [raises "CSRF cookie not set."](https://github.com/tomchristie/django-rest-framework/blob/4248a8d3fc725d9ae3fe7aaaad7ee12479ab07ab/rest_framework/authentication.py#L133). 

My current, ugly workaround:
```python
request = clone_request(self.request, method)
_dont_enforce_csrf_checks_orig = getattr(request._request, '_dont_enforce_csrf_checks', False)
request._request._dont_enforce_csrf_checks = True
try:
    self.check_permissions(request)
except (NotAuthenticated, PermissionDenied):
    allowed = False
else:
    allowed = True
finally:
    request._request._dont_enforce_csrf_checks = _dont_enforce_csrf_checks_orig
```
but I would like to solicit alternative solutions.

**Comment by cancan101** [comment]
A much simpler potential solution:
```python
request = clone_request(self.request, method)
request._user = self.request.user
```

**Comment by tomchristie** [comment]
The big issue with this is that it'd require *every single request* to any REST framework API to run the permissions checks against each method. I can't see that as being acceptable.
I'd strongly suggest keeping this behavior as an optional third party mixin or base class.
