### ISSUE TITLE
STATUS_CODE_TEXT was removed from django in trac ticket #24137

### ISSUE THREAD

**Issue by ovangle** [tomchristie/django-rest-framework#2763]
I'm getting an `ImportError` when using django 1.8 beta and rest framework 3.1.0

    File "/<omitted>/rest_framework/response.py", line 8, in <module>
        from django.core.handlers.wsgi import STATUS_CODE_TEXT
    ImportError: cannot import name 'STATUS_CODE_TEXT'

**Comment by jpadilla** [comment]
Link to relevant ticket https://code.djangoproject.com/ticket/24137. In summary we should probably be able to do something like in [response.py](https://github.com/tomchristie/django-rest-framework/blob/a89e05dc73e2c532372b1f9c51f38100f7f795f6/rest_framework/response.py#L80):

```python
from django.utils.six.moves.http_client import responses
return responses.get(self.status_code, '')
```
