### ISSUE TITLE
Browsable API UI for Date and DateTime fields

### ISSUE THREAD

**Issue by maryokhin** [tomchristie/django-rest-framework#2770]
Dropping this in as an enhancement idea for the browsable API. 
http://eonasdan.github.io/bootstrap-datetimepicker/

Current rendering of `DateField` and `DateTimeField` is just a text field:

![screenshot 2015-03-26 21 40 33](https://cloud.githubusercontent.com/assets/4390231/6856594/62b11426-d401-11e4-98d1-52046c852237.png)

Possibly how it could look:

![screenshot 2015-03-26 21 53 46](https://cloud.githubusercontent.com/assets/4390231/6856802/a9e3ca22-d402-11e4-9ff9-2cd3924d9dab.png)

Would do this myself, but my hands are not very straight with Javascript and @tomchristie needs to decide if it's worth adding a dependency for the browsable API. I think it would be cute and really handy though.

**Comment by kevin-brown** [comment]
These [_should_ be](https://github.com/tomchristie/django-rest-framework/blob/5f3d09a0521b22c819d50833ba3134211fd29d9e/rest_framework/renderers.py#L268-L279) using an `<input type="date" />` which has [mixed browser support](http://caniuse.com/input-datetime) (but it's getting better, slowly). So anyone using supported browsers (WebKit for now with IE in the future) should see an actual date picker that can be used.

**Comment by maryokhin** [comment]
True, I see it in Chrome, looks like the 90s, but it's there.

![screenshot 2015-03-26 22 37 11](https://cloud.githubusercontent.com/assets/4390231/6857709/09041830-d409-11e4-869e-36dac54cbdd2.png)

I turned out to be in the 40% using other browsers.
