### ISSUE TITLE
has_object_permission should only be called once in generic views

### ISSUE THREAD

**Issue by ckaalund** [tomchristie/django-rest-framework#2772]
In a simple RetrieveUpdateDestroyAPIView like so:
```
class ItemView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = PlaceSerializer
    queryset = Item.objects.all()
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (
        permissions.IsAuthenticated,
        HasItemPermission,
    )
```
with a custom permission class like so:
```
class HasItemPermission(permissions.BasePermission):
    def has_object_permission(self, request, view, obj):
        print(True)
        return True
```
Then the HasItemPermission is called 6 times. A small problem with this example but huge when the custom permission contains database queries.

**Comment by tomchristie** [comment]
Assume this is only ever the case for the browsable API rendering?
Shouldn't be the case with a standard JSON rendering.

I expect that you'd see each case checking against a different request method, so may not be anything much we can do here.

**Comment by ckaalund** [comment]
You are right. I was testing with debug toolbar in the browsable API. Have now tested the JSON rendering and that only calls it once.

**Comment by tomchristie** [comment]
Going to close this off given that we're testing different methods in each case.
