### ISSUE TITLE
Document that HTMLFormRenderer is currently intended for internal use by Browsable API.

### ISSUE THREAD

**Issue by roelio** [tomchristie/django-rest-framework#2773]
A 500 occurs when I try to use this renderer and I do not have permissions to the view

Exception Type:	AttributeError
Exception Value:	'dict' object has no attribute 'serializer'

In the render method it looks for the serializer that is normally attached to the data (https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/renderers.py#L333), but cannot find it when a permission or nonauthenticated exception is raised.

**Comment by tomchristie** [comment]
It doesn't really make sense to use HTMLFormRenderer in that case - I can only really see a case for using HTMLFormRenderer *within* a bit of view logic, in order to render a form.

Presumably you're attaching it to a view with `renderer_classes = ...`? What would you expect to see in cases you've given?

Perhaps we need to improve the documentation for `HTMLFormRenderer`

**Comment by roelio** [comment]
An example would be where I have the an Article model that is used in a viewset.
To create the corresponding form for the Article I use an extra list route called form in the viewset.
On the client side I can show this form very quick because there are no queries and I fill it using a client-side call to the article API retrieve endpoint.
I want to protect this endpoint using permissions and expect to see a 403 when I have no permission to this endpoint. 

I've seen that the forms will be one of the next things on the agenda and cannot wait to see what you have in mind.

Thanks for all the work you have done :+1:

**Comment by tomchristie** [comment]
I'm still not sure I understand the ticket.

* What's the smallest minimal example that demonstrates the issue?
* Are you using `HTMLFormRenderer` with renderer_classes?

It may be that the correct resolution here is simply to document that HTMLFormRenderer is only intended for use within a view - it doesn't really make sense to attach as a `renderer_classes` option by itself - how is the remainder of the HTML body included in that case?

**Comment by tomchristie** [comment]
Retitled to what I think might be the best current resolution?

**Comment by roelio** [comment]
`HTMLFormRenderer` was one of the `renderer_classes`, however I realized that I use it only as a field to template mapper.

By using the `TemplateHTMLRenderer` and for example use `Response({'form': self.get_serializer()})` as output, I can generate the HTML form using the `render_field` template tag, However customizing the default field to template mapping is not as easy now.

I agree it's probably best to not use the `HTMLFormRenderer` outside of the Browsable API. Form generation can be done with the serializer in the template context and using the `render_field` tag.

Another approach for me could be to have the forms supplied to the client in JSON and then generate them client-side.

Have you already thought about if and how you will extend the form generation feature? I would like to not diverge too much from the rest framework with my own solution.

offtopic:
On a serializer I have a choice field where the choices depend on the authenticated user. I now alter the choices of the specific field on the serializer in the view after I know the user. Do you have any suggestions on how I can best achieve these kind of dynamic forms?

**Comment by skolsuper** [comment]
+1, glad I found this as I've been stuck on this for a few hours now.  From reading the above it seems like I'm using it wrong, I definitely agree that a note in the docs would be a good idea as the renderer is listed there under the same header (and is in the same source file) with a bunch of other classes that it isn't really the same as.

My use case is to use a /api/my_model/create/.form endpoint to grab a partial html snippet of the form using angular.  The idea being that this will de-couple my app a bit more: if I add a field to the model, once I add it to the serializer it will appear in the forms in my angular app without me having to edit any html or js files.

**Comment by skolsuper** [comment]
In case this helps anyone, I managed to coerce a viewset into working for my use case with the code posted [here](http://stackoverflow.com/a/30068855/2347231)
