### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jairhenrique** [tomchristie/django-rest-framework#2781]
If I define the `DEFAULT_VERSION` of my API, this value does not appear on response header.

Example:

```bash
# request
curl -I -H "Accept: application/json" http://127.0.0.1/endpoint/
```
```bash
# response
...
Content-Type: application/json
...
```

But, if I send the version

```bash
# request
curl -I -H "Accept: application/json; version=2" http://127.0.0.1/endpoint/
```

```
bash
# response
...
Content-Type: application/json; version=2
...
```

Shouldn't the default version always be in the response?

**Comment by tomchristie** [comment]
> Shouldn't the default version always be in the response?

That's not something we aim to provide, no.
You'll need to look at customizing things if you want to do that.
