### ISSUE TITLE
Checkbox Alignment in Browsable API

### ISSUE THREAD

**Issue by ewdicus** [tomchristie/django-rest-framework#2783]
Hello,

The checkboxes in the browsable API in 3.1.1 don't align with the rest of the form. In addition, the labels aren't the same weight.

![image](https://cloud.githubusercontent.com/assets/1026059/6932489/da04db72-d7ce-11e4-831d-0bc9380b72d4.png)

Thanks,
Elliott

**Comment by tomchristie** [comment]
Resolved. Tested in Firefox, Safari, Chrome.

Now looks like this:

![image](https://cloud.githubusercontent.com/assets/647359/8905777/0922be26-3461-11e5-9e52-c937a4efdfae.png)

**Comment by tomchristie** [comment]
Thanks for the report!
