### ISSUE TITLE
django-rest-framework License

### ISSUE THREAD

**Issue by MrZogs** [tomchristie/django-rest-framework#2784]
Hi Tom Christie,

Thanks for  this wonderful framework, it great. Maybe this is not the most appropiate question to put here.
I read the license but I just want to make  sure about if this django-rest-framework app is absolutely free to use and to know if i'm free to apply my logo on API view instead of the anchor "Django REST framework 3.1.1".

Thanks for your time.

**Comment by tomchristie** [comment]
Yes it is, and yes you can.
