### ISSUE TITLE
get_paginated_response and get_pagination_serializer confusion in docs

### ISSUE THREAD

**Issue by skempner** [tomchristie/django-rest-framework#2797]
It seems that the methods get_paginated_response and get_pagination_serializer are the same yet the real method that is implemented is get_paginated_response and get_pagination_serializer is referred to a number of times in the docs:

http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing
http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview

**Comment by tomchristie** [comment]
Thanks for raising the issue.

I'll clarify this: `get_pagination_serializer` is no longer correct - any bits of documentation referring to it need to be updated.

**Comment by markwint** [comment]
FYI:

`get_pagination_serializer` appears on this page: http://www.django-rest-framework.org/api-guide/viewsets/

(Under example for 'Marking extra actions for routing')

**Comment by tomchristie** [comment]
Closing this as `.get_pagination_serializer()` is no longer referenced anywhere in the docs.
