### ISSUE TITLE
page_query_param with square brackets gets double-escaped in browse-able API

### ISSUE THREAD

**Issue by sloria** [tomchristie/django-rest-framework#2802]
Paginators that have square brackets in their `page_query_param` get doubled-escaped when viewed through the browse-able API.

Example:

```python
class JSONAPIPagination(pagination.PageNumberPagination):
    page_query_param = 'page[offset]'
    # ...
```

...results in pagination links that display like:

![django_rest_framework](https://cloud.githubusercontent.com/assets/2379650/7036796/bc4c983e-dd66-11e4-96ef-00f872d0574f.png)

Would be glad to send a patch if this is deemed a legitimate bug.

**Comment by tomchristie** [comment]
I'm disinclined to support this usage. Would involve extra complexity in order to support a use case that feel pretty quirky to me.

**Comment by sloria** [comment]
Thank you for the response. I respect your decision to not support this.

Some context around the use case: `page[size]`, `page[offset]`, etc. are the query parameters recommended by JSON API: http://jsonapi.org/format/#fetching-pagination

**Comment by tomchristie** [comment]
> `page[size]`, `page[offset]`, etc. are the query parameters recommended by JSON API

[insert emoji for face with raised eyebrow]

Fair enough. Looks like those are just examples rather than recommendations, but I think it's slightly questionable to not just use query parameters such as `page_offset=...` which feels more conventional to me.
