### ISSUE TITLE
Nested ModelSerializer are loading VERY lazy 

### ISSUE THREAD

**Issue by bykof** [tomchristie/django-rest-framework#2806]
Hi Tom,
I use django-rest-framework for an internal application in my company. I really love drf and the awesome features it gaves me. But there's one thing which is disturbing me. I have a model with let's say a moderate count of related fields: 
```
class Order(models.Model, BookingModel):
    ORDERED = 'ORDERED'
    WAITING_FOR_DELIVERY = 'WAITING_FOR_DELIVERY'
    DELIVERY_RECEIVED = 'DELIVERY_RECEIVED'
    CREATED_INVENTORY_ITEM = 'CREATED_INVENTORY_ITEM'

    STATUS_CHOICES = (
        (ORDERED, _('Ordered')),
        (WAITING_FOR_DELIVERY, _('Waiting for delivery')),
        (DELIVERY_RECEIVED, _('Delivery received')),
        (CREATED_INVENTORY_ITEM, _('Inventory item was created'))
    )

    bought_by = models.ForeignKey(User, related_name='bought_orders')
    bought_on = models.DateTimeField(default=datetime.datetime.now, blank=True)
    category = models.ForeignKey(OrderCategory, related_name='orders')
    article = models.ForeignKey(Article, related_name='orders')
    supplier = models.ForeignKey(Supplier, related_name='orders')
    purpose = models.CharField(null=True, blank=True, max_length=255)
    payment_method = models.ForeignKey(PaymentMethod, related_name='orders')
    order_number = models.CharField(max_length=255)
    delivery_received_on = models.DateTimeField(null=True, blank=True)
    delivery_received_by = models.ForeignKey(User, null=True, blank=True, related_name='received_orders')
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default=ORDERED)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

```

and I use for the Model surely a ModelSerializer with a ModelViewSet. The only thing I set are the related fields, like this:
```
class ReadOrderSerializer(ModelSerializer):
    bought_by = UserSerializer()
    category = OrderCategorySerializer()
    article = ArticleSerializer()
    supplier = SupplierSerializer()
    payment_method = PaymentMethodSerializer()
    tags = TagListSerializerField()

    class Meta:
        model = Order
```

Now we come to the problem :) 
The problem is that I have to use pagination, because the loading is VERY slow. If I want to receive 25 orders it takes 1,12 secs. 

Do you have a setting to avoid the lazy load or can I change something in the code to do it faster? 

Thank you very much

Best Regards,
Michael

**Comment by xordoquy** [comment]
Please don't use the issue tracker as a support forum.
Usage questions should be asked on the mailing, IRC or StackOverflow.
As for your answer, DRF is built on top of Django. There are plenty blog posts explaining how to track the DB requests and how to optimize them. You likely didn't realize that spanning a relation creates a new DB request which makes the all page slow.
