### ISSUE TITLE
ManyRelatedField.choices tries to iterate over None

### ISSUE THREAD

**Issue by Ian-Foote** [tomchristie/django-rest-framework#2811]
`ManyRelatedField.choices` is a `property` which [iterates over](https://github.com/tomchristie/django-rest-framework/blob/311cad64c998a89b8e8e2394140e0265ff98f53d/rest_framework/relations.py#L376-L383) `self.child_relation.queryset`. This can be `None` if `self.child_relation` is read-only.
I found this when `SimpleMetadata.get_field_info` tried to [check if `field.choices` exists](https://github.com/tomchristie/django-rest-framework/blob/311cad64c998a89b8e8e2394140e0265ff98f53d/rest_framework/metadata.py#L130) and raised `TypeError`.

**Comment by Ian-Foote** [comment]
I'm not sure where the best place to fix this is. A simple fix for my direct issue would be to catch the `TypeError` in `SimpleMetadata.get_field_info`, but I'm not sure `ManyRelatedField.choices` should be raising it in the first place.

**Comment by adm271828** [comment]
I went into similar issue a few days ago. I got this when making an OPTIONS request and it seems the response tries to iterate over field choices, even if field is `read only` (which a simple GET resquest doesn't do).

I fixed this by adding (file: relations.py, line:380)
```python
       iterable = queryset.all() if (hasattr(queryset, 'all')) else queryset
+      if not iterable:
+          return { }
```

This is perhaps a bad behaviour of the OPTION request that could check if field is not read_only before calling `choices()`. But, on the other hand, the `choice` method is not robust...

Best regards.

**Comment by jannon** [comment]
I've just run into this as well.  I think the solution is definitely to change the behavior of the metadata so that it checks if the field is read_only.  After all, there is no point in iterating over the choices for a read_only field.  I'll submit a PR shortly
