### ISSUE TITLE
Contradictory `read_only` and `required` arguments on a m2m through field with uniqueness constraint.

### ISSUE THREAD

**Issue by mitchellrj** [tomchristie/django-rest-framework#2813]
If a field is made `read_only` by DRF automatically by virtue of being a relation with a through-class and the field is also made `required` automatically by virtue of being used in a uniqueness constraint, the `read_only` and `required` arguments clash due to `ModelSerializer.include_extra_kwargs` only checking for `read_only` in `extra_kwargs`.

**Comment by tomchristie** [comment]
Okay. Presumably the end result of that is that you'll always have a validation error for that field stating that: "this field is required", right?

**Comment by jsh2134** [comment]
This same issue was happening to me. Changing from a ModelSerializer to a regular Serializer solved it.

**Comment by xordoquy** [comment]
You should be able to get rid of the constraint by override the contraint. I wrote a mail about this yesterday on the mailing list.

**Comment by tomchristie** [comment]
If anyone's able to search through the list and then link through to past discussion on this that'd help progress this issue.

**Comment by tomchristie** [comment]
Note to self that #2882 is not the same as this issue.
Retitled to make the narrow scope of this issue more prominent.

**Comment by philippeluickx** [comment]
Linked to https://github.com/tomchristie/django-rest-framework/issues/2848 ?

**Comment by xordoquy** [comment]
@philippeluickx looks like, thanks for pointing it.

**Comment by tomchristie** [comment]
Should now be resolved via #4192.
