### ISSUE TITLE
Hide items on HTML form on web view

### ISSUE THREAD

**Issue by autrilla** [tomchristie/django-rest-framework#2814]
I'm using the included generic views, generics.ListCreateAPIView, and on the web view, the HTML form section, it shows every single model instance for each foreign key field. I would only like it to show those that the user is allowed to see. How can I customize which items get shown on the HTML form section?

**Comment by tomchristie** [comment]
Best to direct usage questions to the discussion group.
We use the issue tracker solely for monitoring active work, feature requests and bugs on the project.
