### ISSUE TITLE
django-rest-framework.org link to older release notes 404s

### ISSUE THREAD

**Issue by edmorley** [tomchristie/django-rest-framework#2821]
The "For older release notes, please see the version 2.x documentation" link at the bottom of http://www.django-rest-framework.org/topics/release-notes/ points to:
http://www.django-rest-framework.org/old-release-notes
...which 404s.

Presume it should instead link to something like this?
http://tomchristie.github.io/rest-framework-2-docs/topics/release-notes

**Comment by xordoquy** [comment]
This was fixed in master, it'll be updated once we'll publish the new docs.
(https://github.com/tomchristie/django-rest-framework/blob/master/docs/topics/release-notes.md)

**Comment by edmorley** [comment]
Ah - thanks!
