### ISSUE TITLE
Enforcing Content-Type

### ISSUE THREAD

**Issue by gtrman** [tomchristie/django-rest-framework#2822]
Is there a simple way for enforcing only a certain Content-Type. Now you can set a limited list of parsers, but this does not result in a 415 error for requests with the header Content-Type: application/x-www-form-urlencoded or multipart/form-data.

I would like to have a 415 raised on not listed content types.

**Comment by tomchristie** [comment]
Best to use the discussion group for usage questions.
We use the issue tracker solely for monitoring active work on the project.

As it happens `UnsupportedMediaType` exceptions, resulting in 415 responses *are* raised for unsupported parsers. This occurs when accessing `request.data`.
