### ISSUE TITLE
questionable interpretation of url by APISimpleTestCase

### ISSUE THREAD

**Issue by jxstanford** [tomchristie/django-rest-framework#2825]
Not sure if this is something I'm doing or not, but here's the scenario.  If I add an entry to my nova app urlpatterns like:

```url(r'^hypervisor/spawns[/]?$', SpawnsAggView.as_view())```

I can send a request like this:  http://127.0.0.1:8000/nova/hypervisor/spawns?interval=5m to the running server, and get a non-404 response back.

If I use client.get in an APISimpleTestCase, I get a 404.  If I adjust the pattern to remove the $, like so:

```url(r'^hypervisor/spawns[/]?', SpawnsAggView.as_view())```

then the test will return a non-404 status.  Seems like the $ should only be applied to the path, but might be including the query string as well.

**Comment by tomchristie** [comment]
REST framework doesn't do anything with the URL conf differently to plain Django.
This looks like a Django usage question to me.
