### ISSUE TITLE
Standard response to usage questions.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#2832]
I think we should probably have a standard response to usage questions.

@jpadilla's wording [here](https://github.com/tomchristie/django-rest-framework/issues/2830#issuecomment-93824132) seems suitably brief and appropriate...

> The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

/cc @carltongibson @xordoquy @kevin-brown @jpadilla

**Comment by xordoquy** [comment]
:+1:

**Comment by jpadilla** [comment]
Sounds good to me.

**Comment by tomchristie** [comment]
Don't know if there's anywhere we should put this, but we seem to have settled on a standard enough set of responses at the moment. Perhaps we'll formalize this at a later date, but doesn't seem worth the ticket anymore at this point.
