### ISSUE TITLE
Serializer.__repr__ can produce an unmanageable amount of text.

### ISSUE THREAD

**Issue by dw** [tomchristie/django-rest-framework#2834]
Hi there,

I expect this will be quickly shot down, but I'd lose sleep at night if I didn't at least try: the current `Serializer.__repr__` implementation is basically ruining my life, because I can no longer use the bog-standard, tried-and-trusted-for-almost-2-decades-now print statement to debug code without utterly devastating my terminal window and being flooded with endless amounts of useless information.

I have several serializers in my current project that are nested to such an extent that any reference to the serializer causing its repr() to be called produces 575 lines of junk on my terminal. If I, God help me, accidentally trigger such a reference from within a loop, I basically need a few GB extra disk space just to cope with Terminal.app's scrollback buffer.

Print debugging isn't the only thing Serializer.repr() breaks – for example it doesn't compose with the standard logging package without producing garbage in the resulting log files. The usual habit of using the `%r` format specifier to prevent multi-line splitting in the output has no effect here.

Similarly I cannot simply call `pprint(vars(obj))` or `pprint(locals())` if `obj` or `locals()` happens to refer to a serializer. 600 line mess again.

As for the usefulness of the current repr(), it's really beautiful but I don't think I've ever specifically referred to its output, at least beyond the kwargs supplied to the current instance I'm calling repr() on. Would there be a snowball's chance in hell of perhaps moving it to a helper method? `dump_serializer_tree()` or something.

The only popular precedent I know for multi-line repr() is within Django itself: django.request.Request does the same thing, and I believe it to be broken for the same reasons. Notably, as far as I'm aware the Python standard library never does this.

**Comment by dw** [comment]
What about exposing a setting? repr() isn't a fast path and the setting could default to enabled.

**Comment by tomchristie** [comment]
If we didn't want to addopt a setting, would another acceptable solution be for nested serializers to not be fully displayed? Perhaps we can allow devs to fully dig into the serializer repr if needed, but only display 1 level of fields?

**Comment by maryokhin** [comment]
What about respecting `depth` setting on the serializer and outputting however much the serializer outputs in `to_representation`?

**Comment by dw** [comment]
How about simply including the field path and instance/data? Something like..

For a serializer with no `parent`, `instance` bound to it:

````
<UserSerializer at 0x102604920>
````

With some `parent` bound (recursively walk `.parent` to build the embedded field name):

````
<GroupMemberSerializer user.groups.members at 0x102604920>
````

With some `instance`:

````
<UserSerializer instance=<User: dw> at 0x102604920>
````

That makes the worst case repr something like:

````
<GroupMemberSerializer user.groups.members instance=<User: dw> at 0x102604920>
````

Assuming `instance` has a sane `repr`.

**Comment by tomchristie** [comment]
> How about simply including the field path and instance/data? Something like..

I'd still like to see the fields for a serializer at depth 1 in the repr - unless you're doing something pretty crazy that shouldn't be problematic, right?

Happy to see something like your change applied to any of the *nested* serializer fields tho'

Is that what you were suggesting?

**Comment by tomchristie** [comment]
I'm happy to see this change to a more minimal style that only displays to depth 1, but it's not a priority for me personally and I'm going to close this off. Happy to reopen if someone cares enough about it to issue a potential pull request.
