### ISSUE TITLE
IntegerField.to_internal_value coerces decimal to integer; should fail

### ISSUE THREAD

**Issue by bradford281** [tomchristie/django-rest-framework#2835]
The to_internal_value method coerces data to an int, so when a float/decimal is passed, the int value is saved, rather than raising an exception.

**Comment by tomchristie** [comment]
I'm afraid you'll need to customize the field if you want this behavior.
An integer field that coerces values to an integer wherever possible isn't unreasonable.

While I absolutely understand see why you might want/expect this change, other folks probably wouldn't.

**Comment by bradford281** [comment]
It just seems inconsistent with Django, as entering floats in a Django form for IntegerField will raise a ValidationError, whereas in DRF 3.x it does not (I believe it did in DRF 2.x).

Strangely enough, the expected ValidationError will be raised if the float is wrapped in a string (the attempt to coerce it to int fails "ValueError: invalid literal...") so it may even be inconsistent with itself. To clarify:
    `data = 1 # success`
   ` data = "1" # success; equivalent to data = 1`
    `data = 0.1 # success; unexpectedly equivalent to data = 0`
    `data = "0.1" # fail; expected ValidationError, in line with Django form validation`

This commit seems to return the field to the expected behavior: https://github.com/ryangallen/django-rest-framework/commit/3e6a149c91a5f64f8f90c6bc10a8af8c1273fcf1

**Comment by ryangallen** [comment]
@tomchristie [This pull](https://github.com/tomchristie/django-rest-framework/pull/2836) handles cases where values such as 1.0 or "1.0" pass through as integers but values like 1.5 or "1.5" do not. It matches [Django's IntegerField validation](https://github.com/django/django/blob/b98dfc21770bb0ddc57ca34ddecf1576c2d9f176/django/forms/fields.py#L266) and I believe is the behavior most developers would expect. Changing a clear decimal value, say 0.4 to 0, is not expected and could have negative consequences in an application.
