### ISSUE TITLE
missing url name specification in api_root function documentation

### ISSUE THREAD

**Issue by frnc** [tomchristie/django-rest-framework#2837]
I am going through the tutorial part 5, where function api_root is introduced. Things don't work and an exception "Reverse for 'user-list' with arguments '()' and keyword arguments '{}' not found" is thrown if I don't specify in urls.py `name = "user-list"` in the proper url assignment as in the following:
```python
url(r'^users/$', views.UserList.as_view(), name = "user-list"),
url(r'^snippets/$', views.SnippetList.as_view(), name = "snippet-list"),
```
Unless I overlooked it completely, I can't find this step in the documentation. As it took quite a long time for an absolute beginner like me to find out the solution, I thought it was ok to share just in case. Anyway I ask for forgiveness if I am missing something obvious.

**Comment by frnc** [comment]
Ok, names for URL patterns were just few steps ahead. I tried api_root on the browser a bit too early. Sorry for the inconvenience... maybe a hint might do anyway...

**Comment by jpadilla** [comment]
@frnc A pull request with suggestions on how to improve this would totally rock!
