### ISSUE TITLE
Obtain queryset when deserializing and not OrderedDict

### ISSUE THREAD

**Issue by pbassut** [tomchristie/django-rest-framework#2840]
I'll go straight to the point. Why 
```
serializer = QuestionOptionSerializer(data=options)
serializer.serialized_data
```
returns an OrderedDict?
How do I get the queryset to use it in a view? I browsed the source code and the documentation and I couldn't find anything.

I wanna use the deserialized queryset to assign it to a manytomany relationship with another model.

Any

**Comment by tomchristie** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
