### ISSUE TITLE
DateTimeField should be smarter about timezones

### ISSUE THREAD

**Issue by ntucker** [tomchristie/django-rest-framework#2850]
django.forms.util.from_current_timezone allows you to convert a time to the current set timezone. you don't have to use this method if you don't want to, but you should factor in the current timezone context, not just the default timezone. This is important for instance is an app allows users to set the timezone (i.e., the super common case all your users don't live in one timezone)

**Comment by ntucker** [comment]
def enforce_timezone(self, value):
            """
            When `self.default_timezone` is `None`, always return naive datetimes.
            When `self.default_timezone` is not `None`, always return aware datetimes.
            """
            if (self.default_timezone is not None) and not timezone.is_aware(value):
                return from_current_timezone(value) #operative line
            elif (self.default_timezone is None) and timezone.is_aware(value):
                return timezone.make_naive(value, timezone.UTC())
            return value

**Comment by tomchristie** [comment]
Could you give an example failing test case that we could use to verify a fix here?

**Comment by ntucker** [comment]
Have settings set timezone to UTC or something

Then in your test (set active timezone)
timezone.activate(pytz.timezone("US-Pacific"))
Run enforce timezone with a time based on offset of pacific
Now, timezone.deactivate() to go back to the default, input a different time (based on offset of pacific) and do assertEqual

**Comment by ntucker** [comment]
Do you want me to build a PR? I don't want to write the code unless it will be accepted.

**Comment by tsaylor** [comment]
Here's some test code I wrote based on ntucker's description above.  This is my first time with py.test so I'm not sure if it's proper, but it runs (failing) for me locally.
```
class FakeTimezone(datetime.tzinfo):

    def __repr__(self):
        return "<FakeTimezone>"

    def utcoffset(self, dt):
        return datetime.timedelta(1)

    def tzname(self, dt):
        return "FakeTimezone"

    def dst(self, dt):
        return datetime.timedelta(1)

class TestAwareDateTimeField:

    def test_timezone(self):
        naive_now = timezone.now()
        timezone.activate(FakeTimezone())
        field = serializers.DateTimeField(default_timezone=timezone.UTC())
        aware_now = field.enforce_timezone(naive_now)
        assert aware_now.tzname() == 'FakeTimezone'
```
I'm going to build this enhancement in a fork so I can use it myself. Is there anything I should keep in mind to make it easy for you to merge?

**Comment by tomchristie** [comment]
I'm sympathetic to the intent behind this, but I'd like to see things more clearly specified before accepting anything here. For example: start with the change *at the docs level* - what behavioral changes are we making and why.

There will be plenty of (perhaps a majority) of APIs where the desired behavior will be for datetimes to be unconditionally represented in `UTC` so I'd lukewarm on making this change without either being completely clear about it, or considering if it's in fact should be optional or not.

Any discussion here needs to be in the form of something that we could add to the release notes that makes it crystal clear to users what the current behaviour is right now, and what the changes afterwards would be.

Closing for now, but more than amenable to something more well specified.
