### ISSUE TITLE
Filters applied to late

### ISSUE THREAD

**Issue by jacoor** [tomchristie/django-rest-framework#2852]
Version found: 2.3.14, checking in v. 3.x shows exact same source code, check links at the bottom of this report. 
Use case:

class MessagesApi(ListCreateAPIView):
    """
        Create new message. If thread param is not passed, it will also create new thread.
    """
    serializer_class = MessageSerializer
    model = Message
    paginate_by = 99999999999999999999999999999999999
    filter_class = ThreadMessagesFilter
    ordering = ('id', 'created')

    def get_queryset(self):
        queryset = super(MessagesApi, self).get_queryset()
        user = self.request.user
        message = queryset.first()
        if user not in [message.receiver, message.sender]:
            raise BadRequestException(_("You don't have acccess to this thread"))

        return queryset

Queryset here is not being filtered by filter_class, but filtering works. It looks like filter_class is applied after this get queryset.

Expected behaviour:
queryset should already be filtered by filter_class

Source: https://github.com/tomchristie/django-rest-framework/blob/4248a8d3fc725d9ae3fe7aaaad7ee12479ab07ab/rest_framework/generics.py#L82
in version 3.x
https://github.com/tomchristie/django-rest-framework/blob/version-3.1/rest_framework/generics.py#L82

So it still happens.

**Comment by tomchristie** [comment]
Filtering is applied *after* `get_queryset()`.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L82

Don't see any problem here.

**Comment by jacoor** [comment]
There is a problem still. The method you are refering too is get_object, I am refering to get_queryset. 
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L47
I'd love filter to be applied in get_queryset if possible.

get_object is also fixed in 2.3.14 version.

**Comment by tomchristie** [comment]
Here's what we do in the list method...

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L39

Just do the same in your own view code.
We don't need to push the filtering inside `get_queryset`, it's deliberate that it isn't that way around, and we'd break lots of peoples code if we did so.

**Comment by jacoor** [comment]
Thank you!

**Comment by tomchristie** [comment]
Welcome!
