### ISSUE TITLE
Optional nested serializer field, validation & partial updates

### ISSUE THREAD

**Issue by rapilabs** [tomchristie/django-rest-framework#2865]
Looking over the DRF serialization code, I notice that run_validation() for fields will throw a SkipField exception for empty values when doing a partial update.

Currently, there's no capability to raise a SkipField exception for serializers.  To recreate this behaviour one needs to copy some of the validation code from Field.run_validation() into the nested serializer.

Would adding SkipField exceptions to Serialier.run_validation() be worthwhile?  If not perhaps add a note to the documentation on the best way to do this?

**Comment by tomchristie** [comment]
I'm not 100% sure *exactly* what you're asking for, but almost certainly the answer will be to customize the serializer `.to_representation` or `.to_internal_value` if you need differing behavior.
