### ISSUE TITLE
view description should use method __help__ in  detail_route or list_route

### ISSUE THREAD

**Issue by JocelynDelalande** [tomchristie/django-rest-framework#2866]
The description of a view, as returned by setting `VIEW_DESCRIPTION_FUNCTION` in order to populate *OPTIONS* request or display help text in browsable API, is always set to the viewset docstring.

I think for the case of `@detail_route` or `@list_route`, it should display the help of the method, not the one of the main viewset.

I already wrote some code to do this on my side, if it seems a reasonable feature to you, I can wrap it up for DRF and submit a PR for that.

**Comment by tomchristie** [comment]
There's a whole bunch of valid ways that the view names and descriptions could be generated.
I'd really like to see alternatives (such as this one) as third party pacakges, that we can link to from the main documentation.

You could then simply ask folks to install your package, and set the `VIEW_NAME_FUNCTION` and `VIEW_DESCRIPTION_FUNCTION` settings keys...

http://www.django-rest-framework.org/api-guide/settings/#view-names-and-descriptions

There's plenty of info on creating third party packages here... http://www.django-rest-framework.org/topics/third-party-resources/
