### ISSUE TITLE
validate_<fieldname> needs access to return value of self.to_internal_value

### ISSUE THREAD

**Issue by ntucker** [tomchristie/django-rest-framework#2871]
The whole reason I would want to implement validation at the serializer level for a particular field is so I can use the rest of the data provided as a reference (same way django forms work).

However, the return value is stored in a local value in run_validation and not set on any class level object til all validators are run.

**Comment by tomchristie** [comment]
Use `.validate()` if you want validation between multiple field values.
Otherwise I'm not sure what this ticket is requesting.

**Comment by ntucker** [comment]
if data.get('topic', None) is None and data.get('group', None) and data['group'].required_topics and not set(data['group'].required_topics or []).intersection(data['tags'] or []):
            raise ValidationError({'tags': 'You must include at least one of the following tags: {0}'.format(", ".join(data['group'].required_topics))})


yet my response is

non_field_errors: You must include at least one of the following tags: a, b, c

This is tags field, not non-field errors. The whole reason to have validate_<field_name> is so you can use the context of the rest of the model to validate the field, otherwise it serves no purpose.

**Comment by tomchristie** [comment]
> otherwise it serves no purpose.

It serves to validate the field.

> The whole reason to have validate_ is so you can use the context of the rest of the model to validate the field

Use the `.validate()` method for that instead. If you need to raise a validation error from that against a specific field use `serializers.ValidationError({'field_name': ['whatever']})`

**Comment by ntucker** [comment]
Then why does my response say 'non_field_errors' instead of 'tags'

**Comment by tomchristie** [comment]
> Then why does my response say 'non_field_errors' instead of 'tags'

Could say right now, assume one of:

* Lower version number that didn't yet have that behavior in.
* Not actually being raised inside a `serializer.validate()` or similar.
* A bug in REST framework that it doesn't handle those as it should.

If the `serializers.ValidationError({'field_name': ['whatever']})` inside `validate()` *doesn't* behave as it should then we can treat *that* as a bug. Ideally try to replicate with an absolutely minimal test case if you believe that's what's happening.
