### ISSUE TITLE
exception_handler does not actually handle Django's built-in ValidationError

### ISSUE THREAD

**Issue by allardhoeve** [tomchristie/django-rest-framework#2872]
Unlike the documentation suggests, the function `exception_handler` does not actually handle Django's built-in ValidationError.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L52

**Comment by tomchristie** [comment]
The docstring should be changed there, yes.
We handle django's built-in validation error in serializers, but not here.

**Comment by allardhoeve** [comment]
Would you like a patch for the docstring?

```
We handle django's built-in validation error in serializers, but not here.
```

I am calling `Model.clean` in the serializer `update` and `create` functions but it does not catch django's validation errors. I had to resort to a custom exception handler. Am I missing something obvious?

The documentation speaks of having to code it yourself, but does not elaborate on how to do it.

**Comment by tomchristie** [comment]
> Would you like a patch for the docstring?

That'd be great - I'm happy for us just to drop any mention of Django's validation error there.

> I am calling Model.clean in the serializer update and create functions but it does not catch django's validation errors. I had to resort to a custom exception handler. Am I missing something obvious?

Typically you'd want to handle validation *prior* to update or create.
In the case that you're using, yes you'll either need to catch and re-raise the exceptions as a handled type, or override the handler to deal with them itself.

**Comment by allardhoeve** [comment]
Sadly, validation is also needed in the Django Admin panel. There is currently no easy way to share validation. There was, in DRF 2.4.4 :wink:  So we are stuck with validation-heavy models for a while.

**Comment by tomchristie** [comment]
Sure. :smile: There's some background info on *why* we've taken a slightly different approach now here https://www.youtube.com/watch?v=3cSsbe-tA0E - and yes that does mean a  little more work if you're using both Django's validation style and REST framework together.

**Comment by allardhoeve** [comment]
Yes, I was there. Nevertheless I still need to maintain the admin panel :smile: Patch incoming.
