### ISSUE TITLE
is there a DRF UI for image upload?

### ISSUE THREAD

**Issue by ptchankue** [tomchristie/django-rest-framework#2875]
I am sorry this is not really an issue.

I am using DRF it works fine but there is no option to upload a file from the native UI. I have to use a tool such as Postman to achieve it. 
Is there a way I can do it with DRF's native UI?

**Comment by tomchristie** [comment]
The `ImageField` and `FileField` fields will present a file picker button when using a serializer class on the view.

Generally the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this type of usage question. Thanks!
