### ISSUE TITLE
No way to use to use extra_kwargs to set required=False and read_only=True

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2882]
If the default value for a field is `required=True`, there is no way to change that to `required=False` and `read_only=True` because of this code:
```python
    def include_extra_kwargs(self, kwargs, extra_kwargs):
        if extra_kwargs.get('read_only', False):
            for attr in [
                'required', 'default', 'allow_blank', 'allow_null',
                'min_length', 'max_length', 'min_value', 'max_value',
                'validators', 'queryset'
            ]:
                kwargs.pop(attr, None)
```
Because of that, you get an assertion error here:
```python
assert not (read_only and required), NOT_READ_ONLY_REQUIRED
```

**Comment by tomchristie** [comment]
If you're including `extra_kwargs={'read_only': True}` then `required` should be removed and isn't a valid argument. Perhaps I'm misunderstanding, but the behavior here *looks* right to me as it stands.

Happy to reopen if there's a simple example provided that demonstrates the issue that we can discuss further. (Or similarly, a failing test case also okay of course)
