### ISSUE TITLE
Resolve deprecation warnings with Django 1.8

### ISSUE THREAD

**Issue by dvinegla** [tomchristie/django-rest-framework#2886]
RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.

base.html
{% load url from future %}

**Comment by xordoquy** [comment]
This is blocked by the support of Django < 1.5

**Comment by tomchristie** [comment]
Okay, lets plan to resolve this at the same time as we drop support for 1.4.
I have no issue with us bumping up some versions in our next major release.

**Comment by xordoquy** [comment]
Agreed.

**Comment by foresmac** [comment]
Not sure if this was addressed already or not:
``` python
/usr/local/lib/python2.7/site-packages/rest_framework/settings.py:23: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
```

**Comment by kevin-brown** [comment]
> Not sure if this was addressed already or not:

That was addressed in https://github.com/tomchristie/django-rest-framework/pull/2567.

**Comment by foresmac** [comment]
@kevin-brown Thanks!
