### ISSUE TITLE
JSONRenderer charset

### ISSUE THREAD

**Issue by un1t** [tomchristie/django-rest-framework#2891]
I guess if UNICODE_JSON is True then  JSONRenderer.charset should be 'utf-8'.

Also it would be nice to have setting for indent.

**Comment by tomchristie** [comment]
From [the `application/json` registry](http://www.iana.org/assignments/media-types/application/json)

> Note:  No "charset" parameter is defined for this registration.
> Adding one really has no effect on compliant recipients.

See also:

http://tools.ietf.org/html/rfc4627
http://lucumr.pocoo.org/2013/7/19/application-mimetypes-and-encodings/

**Comment by un1t** [comment]
Right content-type header should be
"application/json; charset=utf-8"

>Adding one really has no effect on compliant recipients.
It is not true. Without charset browsers render unicode chars in response with wrong charset.

**Comment by tomchristie** [comment]
> It is not true.

It is, that's the JSON media type definition. Adding a charset to the media type is incorrect.

**Comment by un1t** [comment]
May be this somehow incorrect in theory. But in reality browsers use this charset parametr.
It not true in part that this not affect recipients. It affects.

So how do you propose to force browsers to use right charset?

**Comment by tomchristie** [comment]
Any clients that *correctly* parse JSON will automatically determine the charset...

https://tools.ietf.org/html/rfc4627#section-3

Also the default encoding is considered to be utf-8, which we use.

What behavior are you seeing that's incorrect, and on which browsers?

**Comment by un1t** [comment]
When you parse it in JS, I guess it would be correct.

But if you just open json url in browser, then it renders wrong.

browsers: Chrome, Firefox  (guess other browsers too, not tested)
You could see it on any non english unicode chars (for example "привет мир").

**Comment by tomchristie** [comment]
True.

So the browser behavior is broken there, not REST framework.

I can see this issue [reported for chromium](https://code.google.com/p/chromium/issues/detail?id=438464), haven't looked any further.

**Comment by tomchristie** [comment]
Example screenshot included for future reference...

![screen shot 2015-04-30 at 14 46 18](https://cloud.githubusercontent.com/assets/647359/7414077/39ffab48-ef48-11e4-8ce2-9208c43cc4d6.png)

![screen shot 2015-04-30 at 14 45 57](https://cloud.githubusercontent.com/assets/647359/7414078/3c9dceb6-ef48-11e4-887b-e8e084fb5f8a.png)

Am going to continue to treat this as a browser issue tho', rather than incorrectly changing the charset in REST framework.

**Comment by un1t** [comment]
Maybe it is browser bug. Not sure, may be be there is some compatibility issues. But seems browser developers won't fix it. Browsers behave such way many years.
But it could be easily fixed on framework side. Why not to fix it? I don't think there would be problems with this.

**Comment by tomchristie** [comment]
> Why not to fix it?

Because we'd then be doing the wrong thing.
There's no "maybe" here - it *is* a browser bug.

**Comment by un1t** [comment]
All browsers bug? I'm not sure.
Wrong is to ignore browsers behavior.

**Comment by tomchristie** [comment]
Browsers are not the only (or even primary) client for the API, and yes, the browser behavior seen *really is incorrect*.

If you would like this behavior, then subclass `JSONRenderer` and set the class attribute `charset = 'utf-8'. You can then configure that class as a custom renderer.

**Comment by tomchristie** [comment]
If anyone want to help move this along I'd suggest searching the firefox, chrome and other bug report lists, and if appropriate, raising an issue regarding the implied charset of JSON responses, and their display as raw documents in the browser.

**Comment by un1t** [comment]
I already subclassed. But I don't like it.
It would be nice to have such option in framework, may be some attribute in settings.py.

**Comment by dmugtasimov** [comment]
Please, let's be practical. People need UTF-8 JSON to be rendered properly. Maybe browsers have bug, but this is the reality. Is it easier to fix in the framework or in all browsers? I guess, you know the answer.

Opera browser is implemented very strictly according the specs. But what is popularity? People do not care about the specs, people care about things done. Personally I will be more productive if my buggy browsers render UTF-8 JSON properly. Respecting the specs is a good thing, giving it a top priority above everything else is bad. There should be a complex of conditions to be considered in any technical decision, sticking with the specs and neglecting everything else is impractical.

Of course I will subclass, monkey-patch or what ever is needed to get my things done if you reject to fix it, but it will be -1 for the framework.

P.S.
Actually, you could do both: forcing browser developers to fix the bug and fixing it on your side, while you are struggling with those "monsters" :)

**Comment by dmugtasimov** [comment]
Ilya, can you share the code you have created to fix this issue? Or even make a pull request to Django REST Framework, although Tom will reject it. It would save me an hour or so.

**Comment by dmugtasimov** [comment]
It looks like APIClient is also broken without `Content-type: application/json; charset=utf-8`:

```python
class CustomAPIClient(APIClient):

    def request(self, **kwargs):
        response = super(CustomAPIClient, self).request(**kwargs)
        import ipdb; ipdb.set_trace()
        return response
```

```
     32         import ipdb; ipdb.set_trace()
---> 33         return response
     34 

ipdb> response
<rest_framework.response.Response object at 0x7faf76a00750>
ipdb> unicode(response)
*** UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 98: ordinal not in range(128)
ipdb> str(response)
'Content-Type: application/json\r\nWWW-Authenticate: Token\r\nAllow: PUT, PATCH, OPTIONS\r\n\r\n{"detail":"\xd0\xa3\xd1\x87\xd0\xb5\xd1\x82\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xb4\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb5 \xd0\xbd\xd0\xb5 \xd0\xb1\xd1\x8b\xd0\xbb\xd0\xb8 \xd0\xbf\xd1\x80\xd0\xb5\xd0\xb4\xd0\xbe\xd1\x81\xd1\x82\xd0\xb0\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd1\x8b."}'
ipdb> print response
Content-Type: application/json
WWW-Authenticate: Token
Allow: PUT, PATCH, OPTIONS

{"detail":"Учетные данные не были предоставлены."}
```

Are you sure you are reading the specs right? Maybe they imply the Content-type value format may be compatible with common HTTP specs? Did you consider that it is a spec bug? Otherwise it looks like everyone else did not read that spec or understood it the other way.

**Comment by dmugtasimov** [comment]
This is good suggestion:
https://github.com/tomchristie/django-rest-framework/issues/2891#issuecomment-97870549

```python

class JSONRenderer(BaseRenderer):

    charset = api_settings.JSON_CHARSET
```

Where `api_settings.JSON_CHARSET = None` by default.

Should I make a pull request?

**Comment by dmugtasimov** [comment]
Unfortunately, creating
```python
class CustomJSONRenderer(JSONRenderer):
    charset = 'utf-8'
```

Does not fix APIClient behavior, but it does fix browsers behavior.

P.S.
Ilya, I revoke my request for help, I figured out how to do it. But I am still not happy with that I have to do it this way.

**Comment by dmugtasimov** [comment]
I am looking into why `unicode(response)` does not work.

Can anyone explain why unicode(response) calls serialize() ? It should call __unicode__() as I know ( https://docs.python.org/2/library/functions.html#unicode ):

> For objects which provide a __unicode__() method, it will call this method without arguments to create a Unicode string. For all other objects, the 8-bit string version or representation is requested and then converted to a Unicode string using the codec for the default encoding in 'strict' mode.

```
     33         response = super(CustomAPIClient, self).request(**kwargs)
     34         import ipdb; ipdb.set_trace()
---> 35         unicode(response)
     36         return response
     37 

> /home/dmugtasimov/gitrep/platformt_core/ENV/local/lib/python2.7/site-packages/django/http/response.py(344)serialize()
    342         self.content = content
    343 
--> 344     def serialize(self):
    345         """Full HTTP message, including headers, as a bytestring."""
    346         return self.serialize_headers() + b'\r\n\r\n' + self.content
```

**Comment by tomchristie** [comment]
If anyone wants to progress this issue I'd suggest determining staring the bug [that has been filed against chromium](https://code.google.com/p/chromium/issues/detail?id=438464) and checking if it also has an equivalent in firefox's issue tracker.

@dmugtasimov Some of the other stuff you're mentioning in this thread would be best addressed as separate tickets if you believe there's an issue.

**Comment by toolness** [comment]
Hey, just wanted to mention that, along the same lines as https://github.com/tomchristie/django-rest-framework/issues/2891#issuecomment-116206889, django 1.9's [`django.test.Response.json`](https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.Response.json) has a similar problem decoding the response, failing with the following traceback:

```.pytb
Traceback (most recent call last):
  File "/hhwc/hhwc/tests/test_api.py", line 64, in test_smoke
    results = response.json()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 13, in _curried
    return _curried_func(*(args + moreargs), **dict(kwargs, **morekwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 662, in _parse_json
    return json.loads(response.content.decode(), **extra)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 253: ordinal not in range(128)
```

It's possible that this is a bug in Django--though if Django's test client has such a bug, and if Chrome does too, it seems likely that lots of other software might as well, if it were written by fallible humans. If there are no *downsides* to adding 'charset=utf-8` to the `Content-Type` header, it seems like it'd just make the world a little more forgiving, but perhaps there are some major downsides that I'm unaware of.

For now I have just set `UNICODE_JSON` to `False` to avoid the issue altogether.

**Comment by xordoquy** [comment]
In order to make sure user's code isn't the root cause here, I'd be interested to see this issue show with Python 3.x.
Python 2.7 offers so many option to mess with encoding issues we can't be sure Django or Django REST framework are to blame here.

**Comment by tomchristie** [comment]
> If there are no downsides to adding charset=utf-8 to the Content-Type header

We're following the JSON spec entirely correctly here - not going to change that.

Incidentally the line you've shown there looks wrong to me, JSON is specced as being 'utf8' encoded, so should probably be...

> response.content.decode('utf-8')

**Comment by toolness** [comment]
Hmm, so the previously linked-to post by Armin Ronacher on [Application Mimetypes and Encodings](http://lucumr.pocoo.org/2013/7/19/application-mimetypes-and-encodings/) does seem to provide some interesting potential downsides to adding the `charset` parameter. (TL;DR is that adding a `charset` parameter ultimately means that clients who *are* following the spec can break.)

> Incidentally the line you've shown there looks wrong to me, JSON is specced as being 'utf8' encoded, so should probably be...
>
>>    response.content.decode('utf-8')

I was thinking that too, and I was about to file a bug on Django's side, but, um, since the JSON spec says:

```
Since the first two characters of a JSON text will always be ASCII
   characters [RFC0020], it is possible to determine whether an octet
   stream is UTF-8, UTF-16 (BE or LE), or UTF-32 (BE or LE) by looking
   at the pattern of nulls in the first four octets.

           00 00 00 xx  UTF-32BE
           00 xx 00 xx  UTF-16BE
           xx 00 00 00  UTF-32LE
           xx 00 xx 00  UTF-16LE
           xx xx xx xx  UTF-8
```

Doesn't that actually mean that the Django test client code actually needs to be examining the pattern of nulls in the first four octets, rather than assuming it's utf-8?

For instance, suppose Django REST Framework (or any other JSON service) suddenly decided that UTF-16 was preferable to UTF-8. According to the spec if *seems* like the service wouldn't have to change any HTTP headers to do so--it would just change the encoding of the content body and expect the client to examine the first four octets to figure out the encoding. (Well, the spec does say "When JSON is written in UTF-16 or UTF-32, the binary content-transfer-encoding must be used", but `Content-Transfer-Encoding` *seems* to be only relevant for email?)

Sorry if this is too much sidetracking... It is kind of a fascinating problem.

**Comment by tomchristie** [comment]
> Doesn't that actually mean that the Django test client code actually needs to be examining the pattern of nulls in the first four octets, rather than assuming it's utf-8?

Maybe so, maybe not, but either way not our issue :sunglasses:

**Comment by sergiomb2** [comment]
> Maybe so, maybe not, but either way not our issue 😎

so you are saying doesn't not work , but is not our fault ? and put this working is not in the plan ?

**Comment by tomchristie** [comment]
Okay that was a silly comment from a year back, so let's get this back on a productive track: No we don't add a charset, because not adding one is the correct thing to do. *If* there's a bug in Django's test client(?) then I'd suggest isolating and demonstrating that issue, and then raising a ticket against Django.

**Comment by sergiomb2** [comment]
@tomchristie I need add it , my client use chrome browser , may I ask what is the simplest way to do it ? 
Thanks in advance

**Comment by tomchristie** [comment]
You be able to add a charset using a custom renderer class.

**Comment by sergiomb2** [comment]
hello @tomchristie @dmugtasimov , I had think about , 
I think we should do a pull request 

```
class JSONRenderer(BaseRenderer):
    charset = api_settings.get("JSON_CHARSET", None)
```

I think, TBH, JSON spec is wrong , the assumption of client guess the charset may be is not easy .
on other hand add charset in HTTP header does do any harm ( unless it have a wrong information ) and make may clients happy , so IMO should be, at least, possible to add charset .

**Comment by tomchristie** [comment]
> JSON spec is wrong

😐

> IMO should be, at least, possible to add charset

It is - use a custom renderer.

**Comment by cdvv7788** [comment]
There is some issue I had recently in dart's http library that was related to json and charset. I know that there are ways to do it without touching DRF, but I leave it here in case you want to check their reasoning to avoid touching the client.
https://github.com/dart-lang/http/issues/175

**Comment by tomchristie** [comment]
@cdvv7788 Responded there.

**Comment by jpmckinney** [comment]
Just a note that Chrome renders application/json as UTF-8. Safari still renders it as extended ASCII with weird characters.

Anyway, TIL that the application/json media type doesn't take a charset parameter.
