### ISSUE TITLE
DRF & JOIN

### ISSUE THREAD

**Issue by frlinw** [tomchristie/django-rest-framework#2892]
Hi,

I have that kind of serializer 
```
class InvoiceListSerializer(serializers.ModelSerializer):
  payer  = ContactListSerializer(read_only=True)

  class Meta:
    model  = X
    fields = (
      'id','number', 'payer'
    )
```
If I want to show a list of 20 invoices, there is 1 SQL request for "id,number" of those 20 invoices AND there are 20 SQL requests for "payer" (one per invoice)

It doesn't seems to be really optimized. Did I miss something? Is it possible to use "join" with DRF ?

Thanks for your help

**Comment by tomchristie** [comment]
For reverse relations, or nested items you'll want to use `select_related` and/or `prefetch_related` on the `queryset` parameter to properly optimize it.

We don't perform this optimization automatically, as it'd introduce too much hidden logic, and would be difficult to debug or override when it doesn't do what you need.

We have [a documentation ticket currently outstanding for this](https://github.com/tomchristie/django-rest-framework/issues/1977) to more adequately describe how and when you should be doing this.

**Comment by frlinw** [comment]
Perfect !
