### ISSUE TITLE
Allow adding Serializer Class to detail_route/list_route

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2895]
I suggest allowing putting a serializer class on the `detail_route` and `list_route`.

This will help tools like [django-rest-swagger](http://django-rest-swagger.readthedocs.org/en/latest/yaml.html#serializers) generate docs for those end points.
`ViewSet.get_serializer` could also be made to work.

**Comment by maryokhin** [comment]
#2736

**Comment by tomchristie** [comment]
I'm assuming this is not jsut related to #2736, but in fact a duplicate?
Closing it as a duplicate for now.
