### ISSUE TITLE
Decimal comma separator

### ISSUE THREAD

**Issue by kaiobrito** [tomchristie/django-rest-framework#2897]
How can i use comma as separator in decimal fields?

In django.forms.DecimalField just need to set locale=True in attributes to work well.

**Comment by tomchristie** [comment]
We don't currently support localized decimal fields, so you'd need to subclass the field and add in any further behavior by overriding `get_internal_value` and/or `get_representation`.

I'd accept a feature request for localization on field types so long as it comprehensively looked at all the various numeric localization that happens across *all* the Django numeric types.
