### ISSUE TITLE
Update example for class based validation callables

### ISSUE THREAD

**Issue by tomleo** [tomchristie/django-rest-framework#2900]
The class `class MultipleOf:` doesn't inherit from object. 
This is a little confusing to people new to python. I think it would be worth documenting the syntax for inheriting from "old-style" python classes.

```python
MultipleOf.__init__(self, *args, **kwargs)
``` 

instead of

```python
super(<ClassName>, self).__init__(*args, **kwargs)
```

**Comment by jpadilla** [comment]
I think we should just change the example to explicitly inherit from object.

**Comment by tomchristie** [comment]
Seconding @jpadilla. `class MultipleOf(object):` would be just fine.
