### ISSUE TITLE
No serializer fields are allowed to use read_only=True

### ISSUE THREAD

**Issue by clarkperkins** [tomchristie/django-rest-framework#2901]
No matter what type of `Field` you use, you always get this error when setting `read_only=True`:

```
AssertionError: Field(read_only=True) should be ReadOnlyField
```

I'm using djangorestframework version 3.1.1, I also tried on 3.0.0 and had the same error.

Specifically, I'm using a `HyperlinkedRelatedField` when having this error.

**Comment by tomchristie** [comment]
You'll only see that error if you're using `Field`.
Subclasses of `Field` won't generate it.
See here: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L184
