### ISSUE TITLE
Include separate license file.

### ISSUE THREAD

**Issue by mrunge** [tomchristie/django-rest-framework#2906]
could you please add the license file to the distribution, e.g to pypi and to github repo?

**Comment by tomchristie** [comment]
We have the license [in the README](https://github.com/tomchristie/django-rest-framework#license) and [on the homepage](http://www.django-rest-framework.org/#license).

**Comment by mrunge** [comment]
Tom, yes.

But neither nor is included on pypi.

**Comment by mrunge** [comment]
I would use pypi as source to package django-rest-framework up for Fedora. 

Github does not leave change dates intact.

**Comment by tomchristie** [comment]
After checking the Django PyPI download I'm happy with the suggestion, yup.
Would accept pull requests moving README license out, and into a seperate `LICENSE.md` to the root of the repo, and adding `include README.md` and `include LICENCE.md` lines to the manifest file.

**Comment by tomchristie** [comment]
Closed by #2907.
