### ISSUE TITLE
DRF performs poorly out of the box

### ISSUE THREAD

**Issue by elioscordo** [tomchristie/django-rest-framework#2916]
Hi,
I just configured a new project and the calls are very slow. 

Could you give me some hints?

Python2.7
Dango 1.6
![drf_poor](https://cloud.githubusercontent.com/assets/477426/7517740/0c895076-f4d7-11e4-89e5-9168ba9fd7af.jpg)

**Comment by tomchristie** [comment]
See https://github.com/tomchristie/django-rest-framework/issues/1977 and the related issues that link to it. You're almost certainly using a serialization style that needs appropraite `select_related` and `prefetch_related` statements on the queryset in order to perform sensibly.

We don't attempt to make those optimizations automatically, as it'd be too much magic.

**Comment by elioscordo** [comment]
Hi Tom,
thank you so much for the amazing framework. I would like to understand more.
As you can see for the statistic, the bottle neck is not in the query part. The same query would take the same amount of time in a normal django view without serializers. Something bad happen in the 
return Response(serializer.data).
Please note:
I am doing nothing with relationships just asking for ids

Could you or some other developer tell more about this?  
thanks and sorry for bothering with probably numb questions.
 


![drf_poor_2](https://cloud.githubusercontent.com/assets/477426/7533395/5aac3648-f571-11e4-85a5-011589ea30ff.jpg)

**Comment by elioscordo** [comment]
![drf_poor_3](https://cloud.githubusercontent.com/assets/477426/7533490/380e2c94-f572-11e4-967c-35dc6f602fa0.jpg)

**Comment by thedrow** [comment]
And yet you have 4 queries.
Serializing without pagination takes a hell lot of time.
DRF can handle with 10 objects at the time in a timely manner.

**Comment by tomchristie** [comment]
@elioscordo If you can provide the simplest possible replicable case I may be able to take a look.
* How many objects are being returned?
* Do you see the same performance if you request JSON from a command line client rather than using the browsable API?
