### ISSUE TITLE
lookup_field error with detail_route

### ISSUE THREAD

**Issue by planners** [tomchristie/django-rest-framework#2925]
Hi,

when i create the following detail_route within a modelViewSet i am facing a problem with the lookup_field. Do you have any suggestions? 

The detail_route shows an error regarding a missing username.
The detail_route method i call like /api/v1/accounts/{username}/user_status/

The modelViewSet looks like: 

class AccountViewSet(viewsets.ModelViewSet):
    lookup_field = 'username'
    queryset = Account.objects.all()
    serializer_class = AccountSerializer

    def get_permissions(self):
        if self.request.method in permissions.SAFE_METHODS:
            return (permissions.AllowAny(),)

        if self.request.method == 'POST':
            return (permissions.AllowAny(),)

        return (permissions.IsAuthenticated(), IsAccountOwner(),)

    def create(self, request):
        serializer = self.serializer_class(data=request.DATA)

        if serializer.is_valid():
            try:
                Account.objects.create_user(**serializer.validated_data)
            except ValueError as e:
                return Response({
                    'message': str(e),
                }, status=status.HTTP_400_BAD_REQUEST)
            return Response(serializer.validated_data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @list_route(methods=['GET'])
    def self(self, request):
        pass

    @list_route(methods=['POST'])
    def check_email(self, request):
        if (Account.objects.filter(email = request.DATA['email']).count() == 0):
            return Response(status=status.HTTP_200_OK)
        else:
            return Response(status=500)

    @list_route(methods=['POST'])
    def check_user(self, request):
        if (Account.objects.filter(username = request.DATA['user']).count() == 0):
            return Response(status=status.HTTP_200_OK)
        else:
            return Response(status=500)

    @detail_route(methods=['GET'])
    def user_status(self, request, pk=None):
        return Response(status=status.HTTP_100_CONTINUE)

**Comment by tomchristie** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
