### ISSUE TITLE
Document Testing Extra Routes

### ISSUE THREAD

**Issue by jpulec** [tomchristie/django-rest-framework#2927]
Because of how DRF handles dynamic routes, doing something like:

```python

class MyViewSet(viewsets.ModelViewset):
  queryset = Account.objects.all()

  @list_route(methods=['POST',], permission_classes=[IsAdminUser,])
  def extra(self, request):
    # do stuff

request = APIRequestFactory().post(reverse('accounts-extra'), {'data': 'foo'})

response = MyViewSet.as_view({'post': 'extra'})(request)
```
Does not work as expected, because the kwargs to @list_route are passed to ```as_view``` during DRF's routing, meaning that the ```permission_classes``` kwarg isn't respected here. The correct implementation looks like:

```python

class MyViewSet(viewsets.ModelViewset):
  queryset = Account.objects.all()

  @list_route(methods=['POST',], permission_classes=[IsAdminUser,])
  def extra(self, request):
    # do stuff

request = APIRequestFactory().post(reverse('accounts-extra'), {'data': 'foo'})

response = MyViewSet.as_view({'post': 'extra'}, **MyViewSet.extra.kwargs)(request)
```

Is this something that should be documented in the 'Testing' section?

**Comment by tomchristie** [comment]
Happy to consider pull requests to the documentation, but not a priority to me unless re-raised.
Happy to reopen if someone wants to take it on or has a concrete suggestion.
