### ISSUE TITLE
Move the `detail_route` / `list_route` lists back to `ViewSet`

### ISSUE THREAD

**Issue by xordoquy** [tomchristie/django-rest-framework#2934]
During a workshop on Django REST framework, I realized the browsable API doesn't have links to the `list_route` / `detail_route` actions.
While I started working on implementing it I realized it should be the `ViewSet` responsibility to provide a list of custom actions. Currently all the work is done by the Router.

I'm opening the issue to discuss the possible directions.
My first though was to move the code that gathers the custom actions to the `ViewSet`. However, I'm not too happy with it as it relies on the `ViewSet` members having or not a `bind_to_methods` attribute attached.
My proposal would be to have two lists (possibly dictionaries) within the `ViewSet` that do hold the `list_route` and `detail_route` members. The decorator would then register their member to the `ViewSet`.

Thoughts ?

**Comment by tomchristie** [comment]
Okay, so my viewpoint best thing would be to rephrase this.
The "Move the `detail_route` / `list_route` lists back to `ViewSet`" is implementation detail.
What's the desired behavior, what do you want the browsable API to look like as a result?

**Comment by xordoquy** [comment]
The initial work is to get links to the list/detail additional routes.
During the workshop, we implemented one of them and I felt there should be a link to them to ease the navigation.

**Comment by tomchristie** [comment]
Okay, we may as well go with a concrete example of the behavior being suggested.

![image](https://cloud.githubusercontent.com/assets/647359/7654869/efcd4c84-fb17-11e4-9db9-365afe779c8f.png)

Where would we be linking to associated actions?

I don't think I've got any particular issue with having this info also (or instead) associated with ViewSets. Havn't done much around that area of the codebase myself lately, so be interesting to see what potential Pull Requests for this might look like.

**Comment by tomchristie** [comment]
I think this is outside of our current scope/bandwidth. I'd be happy to consider this either:

* In response to a proactive pull request.
* If reopened when we're getting closer to 3.3, or more likely 3.4.

If the admin interface has settled down and is being widely used then I think we'll have a good point to discuss it from, until then I don't think it's within what we're able to deal with.

**Comment by Aldarn** [comment]
I would also like to be able to see ViewSet actions in the browsable API. Currently the workaround to this as far as i'm aware is to include a hyperlink to the actions within the ViewSet Serializer, however this has the side effect of actually including the hyperlink in the API output which may or may not be desired.

**Comment by xordoquy** [comment]
@Aldarn this will come back one day or another when we'll have more time to work on this or a client will request it :)

**Comment by stantond** [comment]
Was this ever revisited? And if not, is now maybe a good time to look at this, given 3.4 has shipped?

**Comment by tomchristie** [comment]
Tracking this in #2062, which I believe describes the same thing, right?

**Comment by rpkilby** [comment]
I don't think so - related but different. #2062 seems to be about rendering a different serializer for a specific action (such as a change password form for a user's account). This issue is more about exposing that action as a link. Right now, the browsable API doesn't expose any of the action links - you would just have to know that a change password action exists.

**Comment by xordoquy** [comment]
Moving list/detail routers to view sets sounds to me like an additional API DRF needs.
Since we have more and more schema and stuff like that and some of which are 3rd parties I *strongly* believe we should make an API to "publish" the various routes.

**Comment by tomchristie** [comment]
Okay, so updating #2062 to suggest that we *link* to the actions, rather than including them on the page itself. That sounds sensible.
