### ISSUE TITLE
Add coverage option to runtests script.

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2936]
**Edit: retitled from original 'Improvements to CI'** - @tomchristie

Consider using
* coveralls for test coverage
* [landscape.io](https://landscape.io/) for code analysis

**Comment by tomchristie** [comment]
Don't want to use landscape.io (our tests anyway fail if flake8 fails, so we have pretty strong code-convention enforcement.). I'd consider code coverage as part of the reports.

**Comment by cancan101** [comment]
landscape.io does offer more than flake8 doesn't it?

**Comment by tomchristie** [comment]
It's a different kind of reporting, yes. Lovely looking, but strict flake8 enforcement in the tests is (almost) exactly what I'd want on python projects for style checking.

**Comment by maryokhin** [comment]
What I think would be nice, is to set the line length rule for `flake8` instead of [ignoring](https://github.com/tomchristie/django-rest-framework/blob/master/runtests.py#L15) `E501`.

**Comment by tomchristie** [comment]
@maryokhin There are too many times when strictly requiring the line length ends up making the code less readable. I've no problem with us continuing with a *soft* limit of 80 chars.

@cancan101 I'm going to retitle this issue with what I think is the *first* actionable step toward this - add a coverage option to the `runtests` script. If and when that's completed we could consider including coverage in the travis runs, and perhaps also coveralls (tho I'm not super keen on introducing service dependancies)

**Comment by xordoquy** [comment]
@tomchristie bringing the discussion back here. The fact that we may call py.test instead of runtest within tox can be balanced by the fact that we could / should be using tox to run the tests IMHO.

**Comment by tomchristie** [comment]
> we could / should be using tox to run the tests IMHO.

I personally don't, at least mostly.

I find that the balance of super quick test runs locally, and slower full-platform test runs on travis is perfectly fine for most stuff I work on.

**Comment by xordoquy** [comment]
@tomchristie my point was, runtest in itself doesn't make much sense now.
Advanced users who wants to gain time and run as fast as possible would call py.test. If one wants options such as fail fast they'll know enough to add it.
For beginners, tox or tox -e <env> should do. That would skip the painful part of installing a local env for them. Moreover, one should note that you can activate tox's virtualenv and run py.test directly - which is how I use the DRF's test virtualenvs.

I really don't see why we would keep runtest.

**Comment by tomchristie** [comment]
Having a single command that wraps up the entire set of tests (for a given environment) seems a like a good separation to me. (eg `py.test` isn't enough to know that the build will pass. There's also the flake8 and isort testing.)

I always uses `runtests.py` locally, and occasionally run `tox` additionally if there may be compat concerns.

**Comment by tomchristie** [comment]
Coverage is now included in runtests as part of https://github.com/tomchristie/django-rest-framework/commit/db40b7eb916bbff2d0a4e4a8b5340a3ef866611f

Happy to have a conversation on integrating a coverage service. I'm kinda lukewarm on it (mediocre experience with coveralls in the past, and not super keen on extra service deps) but could be considered.

**Comment by xordoquy** [comment]
I don't care as long as it's a commodity and that we're not dependent on it.
