### ISSUE TITLE
Setting `allow_null=True` on CharField returns `None` as unicode string

### ISSUE THREAD

**Issue by foresmac** [tomchristie/django-rest-framework#2937]
You can set `allow_null=True` on a CharField, but `None` gets converted to a string before going to the validator. I believe the problem is the `to_internal_value()` function, which coerces `None` to a unicode string:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L588:
```python
    def to_internal_value(self, data):
        value = six.text_type(data)
        return value.strip() if self.trim_whitespace else value
```

If you run this on `None`, you just a get the string `u'None'`:
``` python
>>> from six import text_type
>>> text_type(None)
u'None'
>>> 
```

I suggest changing it like so:
``` python
    def to_internal_value(self, data):
        if data is None and self.allow_null:
            return None
        value = six.text_type(data)
        return value.strip() if self.trim_whitespace else value
```

**Comment by foresmac** [comment]
Actually, I feel like I'm missing something here. It looks like `run_validation()` should basically just handle this and skip running validators, but that's not happening in my code. (For reference, I'm using 3.0.5, but the same code is there.) My custom validator is getting called and being passed `u'None'`, so my validator is failing, even though I have `allow_null=True` set on the field.

**Comment by foresmac** [comment]
Ok, I figured it out. It was actually a strange bug. I just needed to explicitly set `format='json'` when making requests with the test client. For some reason, I thought that was the implicit default, and all the other tests were working without that, but I was wrong.

**Comment by xordoquy** [comment]
@foresmac actually, it's not that strange. Django being used under the hood and its default is to work with forms which don't have a null value, only empty strings thus your issue.

**Comment by foresmac** [comment]
I thought the client in the `APITestCase` used `format='json'` by default, that's why I didn't think to consider it was being interpreted as form data.

**Comment by tomchristie** [comment]
@foresmac Yeah, went against that initially as wanted it to default to same behavior as Django's test client. Don't know if the other way around woulda been better or not.

**Comment by foresmac** [comment]
Does it make more sense as a default for DRF's test client since JSON is the _lingua franca_ of APIs? This seems like a legitimate reason to be different.

**Comment by tomchristie** [comment]
On balance, probably yes - but don't know that we'd have any graceful ways to do that given existing projects.
At the time I wanted it to have the same behavior, but just be more functional, but JSON defaults would prob have been worth doing.
You can change the default in `TEST_REQUEST_DEFAULT_FORMAT`, but not totally ideal.
