### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by anoopmalav** [tomchristie/django-rest-framework#2939]
+ **Invalid Title None**
+ **Two Home Buttons**

![screenshot from 2015-05-15 11 46 51](https://cloud.githubusercontent.com/assets/9918965/7647834/dd15469c-faf8-11e4-847b-ae42f50a9b04.png)

**Comment by tomchristie** [comment]
Don't know how that happened. Redeployed the docs now and looking fine again. Thanks for the notification!
