### ISSUE TITLE
PATCHless UpdateModelMixin

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#2945]
Add a `UpdateModelMixin` that does not have `partial_update`.

**Comment by nryoung** [comment]
Can you provide further info on why this is needed?

**Comment by tomchristie** [comment]
Perfectly reasonable request, but we're trying to aim for less not more right now, so going to punt this into the pile of "do so in user code"

**Comment by Achilles718611** [comment]
Now UpdateModelMixin has partial_update, so it's difficult to disable only partial update.
Is there the way to disable only partial update?

**Comment by xordoquy** [comment]
Raising a `MethodNotAllowed` in `partial_update` should do.

**Comment by rpkilby** [comment]
You could also create a PUT-only variant of https://github.com/encode/django-rest-framework/pull/3081#issuecomment-292557589.
