### ISSUE TITLE
Unlike other fields, HyperlinkedRelatedField assumes it's inside a serializer.

### ISSUE THREAD

**Issue by rollokb** [tomchristie/django-rest-framework#2946]
The HyperlinkedRelatedField can't be used outside a serializer as the `context` property is taken from it's [parent serializer](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L450). This is inconsistent with the behavior of other fields with don't need a context.

The error message is also wrong as it asks for a context which can't be set. 

For instance this snippet will throw an error.

    def get_products(self, instance):
        request = self.context['request']
 
 
        field = serializers.HyperlinkedRelatedField(
            view_name='product-detail',
            many=True,
            read_only=True,
        )
 
        representation = field.to_representation(instance.product_set.all())
        return representation

And django-rest-framework will ask for a `context={'request': request}` to be included as a kwarg, it will fail at this point. https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L244

    def to_representation(self, value):
        request = self.context.get('request', none)
        format = self.context.get('format', none)

        assert request is not none, (
            "`%s` requires the request in the serializer"
            " context. add `context={'request': request}` when instantiating "
            "the serializer." % self.__class__.__name__
        )

However if I include the request as part of the context

    def get_products(self, instance):
        request = self.context['request']
 
        field = serializers.HyperlinkedRelatedField(
            view_name='product-detail',
            many=True,
            read_only=True,
            context={'request': request}
        )

        representation = field.to_representation(instance.product_set.all())
        return representation

It again crashes with the error, `can't set attribute`. I suspect  this (https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L449) read only method field is the problem.

**Comment by tomchristie** [comment]
You're correct that hyperlinked fields are different and *do* require being bound to a serializer.
Right now I don't see us doing anything about that. `context` is not a fields argument http://www.django-rest-framework.org/api-guide/fields/#core-arguments and the correct usage is to use the field together with a serializer class. It's possible that we could consider ironing out this sort of thing at some point in the future but right now I'd consider this an incorrect usage, and insufficiently pressing to merit an open ticket. We'll re-assess if it is re-raised in the future. Thanks!

**Comment by rollokb** [comment]
Thanks.

Was just trying out a different way of doing something.

Even though this is an undocumented way of using `HyperlinkedRelatedField`s maybe the error string should be changed if someone else tries to use it that way?

**Comment by tomchristie** [comment]
More that happy to consider suggestions - if you provide before text and after text it'll be super easy to review the suggestion.
