### ISSUE TITLE
`max_decimal_places` in Decimal field are wrong calculated

### ISSUE THREAD

**Issue by bimusiek** [tomchristie/django-rest-framework#2947]
We got an issue when number is formatted as `decimal.Decimal('2E+9')`.

How `DecimalField` counts decimals:

        sign, digittuple, exponent = value.as_tuple()
        decimals = abs(exponent)

However result of `decimal.Decimal('2E+9').as_tuple()[2]` is **9**, which is ok, but there are no decimal places in this number.

My solution is to not do `abs` and instead multiply by `-1`. 

I can prepare PR tonight if you think it is valid.

**Comment by tomchristie** [comment]
So things that would help here:

* Any comparisons between what happens in Django core and what we do (if that's possible/relevant?)
* One or two example cases (In particular pull requests with failing test cases), and expected input/output values.

**Comment by bimusiek** [comment]
@tomchristie I added PR with example and solution. 
Basically we get really huge number, then normalize it with `.normalize()` which resulted in having `2E+9` which resulted in `ValidationError` :)

Hope PR is valid!
