### ISSUE TITLE
DjangoPaginator class hardcoded

### ISSUE THREAD

**Issue by dangusev** [tomchristie/django-rest-framework#2951]
Hey guys. It would be great to be able to override paginator class which used in Pagination-class without patch `paginate_queryset()` method. Thanks!

**Comment by tomchristie** [comment]
Reasonable enough request, and we may re-review this at a later date, but currently not a priority for us to expose the paginator API in more override friendly ways. Closing this off to keep us focused on the big deliverables for now.
