### ISSUE TITLE
default exception_handler doesn't handle Django's ValidationError

### ISSUE THREAD

**Issue by filipposantovito** [tomchristie/django-rest-framework#2954]
the doc for

    def exception_handler(exc, context):

says:

    By default we handle the REST framework `APIException`, and also
    Django's built-in `ValidationError`, `Http404` and `PermissionDenied`
    exceptions.

but the part for ValidationError is missing

**Comment by tomchristie** [comment]
The documentation is incorrect. We handle Django's `ValidationError` at the serializer level. We should alter the docs, rather than the code here. Pull requests most welcome! :)

**Comment by filipposantovito** [comment]
I've created a test to show you what I mean:
https://github.com/tomchristie/django-rest-framework/pull/2955

**Comment by tomchristie** [comment]
ValidationErrors should be raised prior to save, not during save. Handling the logic in the serializer would be a better route here. If you have ValidationErrors or IntegrityErrors that could be raised at the point of save then you need to handle that explicitly.

**Comment by tomchristie** [comment]
Ooops - reopening as we still need to change that paragraph in the docs.

**Comment by tomchristie** [comment]
Assume this is out of date, as the text on the exception handler is currently correct...

    def exception_handler(exc, context):
        """
        Returns the response that should be used for any given exception.

        By default we handle the REST framework `APIException`, and also
        Django's built-in `Http404` and `PermissionDenied` exceptions.

        Any unhandled exceptions may return `None`, which will cause a 500 error
        to be raised.
        """

**Comment by kevin-brown** [comment]
> The documentation is incorrect. We handle Django's `ValidationError` at the serializer level.

Just wanted to confirm this, it was added (back) in https://github.com/tomchristie/django-rest-framework/issues/2145.
