### ISSUE TITLE
Serializer.save() method does not accept boolean 'commit' parameter

### ISSUE THREAD

**Issue by DariaKnyazeva** [tomchristie/django-rest-framework#2958]
Sometimes it can be helpful to pass `commit=False` to serialozer's `save` method to not save object to database yet.

**Comment by carltongibson** [comment]
Hi @DariaKnyazeva — could you give an example? 

I'm thinking most use-cases are covered by overriding your view's `perform_save` and passing extra kwargs to `Serializer.save` — if you can show what you're trying to do we can see... Thanks!

**Comment by xordoquy** [comment]
Actually, the serializer.save(commit=False) will make the commit available within the validated_data in the serializer's create / update which you can easily override

**Comment by carltongibson** [comment]
Hi @DariaKnyazeva — I think @xordoquy's point should cover you. I'm going to close this issue assuming you can work it out. 

If you still have issues come back (or hit the The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) and we can help (or think about re-opening if there's something to address with DRF.)
