### ISSUE TITLE
Documentation quickstart tutorial - settings

### ISSUE THREAD

**Issue by mimoralea** [tomchristie/django-rest-framework#2961]
We need to add the quickstart app to the settings.

```
Settings
We'd also like to set a few global settings. We'd like to turn on pagination, and we want our API to only be accessible to admin users. The settings module will be in tutorial/settings.py

INSTALLED_APPS = (
    ...
    'rest_framework',
    'tutorial.quickstart', # <--- add this line
)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'PAGE_SIZE': 10
}

```

**Comment by xordoquy** [comment]
Actually you don't need this to be added to the settings since it doesn't have models, templates, template tags and so on.

**Comment by mimoralea** [comment]
I tried it with Django 1.8.2 and Django Rest Framework 3.1.2 and it complained about the app not being registered; I added it and it worked.

**Comment by xordoquy** [comment]
Will double check that with Django 1.8

**Comment by xordoquy** [comment]
I just gave a try with Django 1.8.2, DRF 3.1.2 and couldn't reproduce the issue.
Is it possible to have a traceback of the issue ?
