### ISSUE TITLE
Add new package to docs: drf-tracking

### ISSUE THREAD

**Issue by aschn** [tomchristie/django-rest-framework#2968]
Many people have posted questions about the best way to hook into API views to add logging, e.g., https://groups.google.com/forum/#!topic/django-rest-framework/n7iZK2l4VB0. I've done this myself in a couple projects now, so I made a reusable app that implements the recommended strategy and saves the data to a db model:

https://github.com/aschn/drf-tracking

If this package would be useful to others, it could be added to the docs somewhere. Not sure where would be best, though.. maybe [here](http://www.django-rest-framework.org/api-guide/views/#dispatch-methods)?

**Comment by carltongibson** [comment]
Hey @aschn — sounds good. [Here's the place](http://www.django-rest-framework.org/topics/third-party-resources/)

(I'm going to close this assuming your question is answered. Do open a Pull Request adding your package.)
