### ISSUE TITLE
Introduce version into documentation website

### ISSUE THREAD

**Issue by kawing-chiu** [tomchristie/django-rest-framework#2983]
Currently, the documentation site of django rest framework is not versioned. It caused much inconvenience to me, especially when I was reading a book whose code snippets use an older version of django rest framework. It would be great if drf's doc can be versioned (with links in every pages linking to different versions), just as how Python's official documentation and Django's documentation do it.

**Comment by xordoquy** [comment]
This makes sense to me. However, I'm not sure we can focus on that yet.

**Comment by tomchristie** [comment]
Closing as infeasible until and unless supported in MkDocs.
See https://github.com/mkdocs/mkdocs/issues/193
In the meantime we now have the PyPI version visible on the docs homepage.

**Comment by arielpontes** [comment]
It's been almost 4 years since this was closed. Any chance this is more feasible now?

**Comment by tomchristie** [comment]
Currently not.
