### ISSUE TITLE
perform_create need to run before validation

### ISSUE THREAD

**Issue by Tritlo** [tomchristie/django-rest-framework#2988]
When unique_together is declared in the Django model, the validator will try and use that as a validator for a class. However, this validator might be missing information that is requiered, but won't be entered until the perform_create, e.g.

    def perform_create(self,serializer):
        serializer.save(author=self.request.user.profile)

but when you have a requirement in the Django model,

    class Meta:
        unique_together ('post','author')
then you get an error:

    {'author':"['This field is required']"},

because perform_create hasn't been run when that particular validator runs.

**Comment by xordoquy** [comment]
You either need to remove the author field from the serializer or use the `CurrentUserDefault`.
Note that the extra data you pass to serializer.save don't have to be serializer's fields.

**Comment by Tritlo** [comment]
I've gotten around it by defining my own CurrentUserProfileDefault, but that seems like a bit of a hack. The author field is a natural part of the definition of the serializer, and removing it seems weird. Shouldn't there be some way to do this without having to roll your own default?

**Comment by xordoquy** [comment]
@Tritlo What was wrong with the DRF's `CurrentUserDefault` ?

**Comment by xordoquy** [comment]
Forget previous comment, I skipped the profile part.

**Comment by xordoquy** [comment]
@Tritlo actually it seems more sane to define this though it's a bit more work.
Reason being that it's way more explicit when you look at the serializer.
