### ISSUE TITLE
Saving/Patching m2m not sending post remove action with m2m_changed signal

### ISSUE THREAD

**Issue by jsenecal** [tomchristie/django-rest-framework#2991]
I'm trying to get a many to many model to update when I save a related model. This should be possible using the m2m_changed signal (and it works with django itself but not through REST framework)

I'm on Django==1.8.2 and djangorestframework==3.1.2

This seemed to be fixed for the admin portion of django through 
https://code.djangoproject.com/ticket/16073 (symptoms)
and
https://code.djangoproject.com/ticket/6707 (actual bug)

I tried with the API browser and cURL, same results.

Most of the steps to reproduce the problem are explained into the above links. Let me know if you need more info...

**Comment by tomchristie** [comment]
So Django 6707 appears to only be fixed in master.
I'm going to close this for now on the assumption that it'll work against Django master and 1.9 onwards, but I'll reopen if you can confirm that's not the case (ideally with an example failing test case.)

**Comment by jsenecal** [comment]
As I explained in my original comment the signals are properly triggered through django. 

I.e. doing something like this:
```python
t = Tag.objects.all()[0]
s = Snippet.objects.all()[0]

s.tags.remove(t)
s.save()

s.tags.add(t)
s.save()
```
Triggers the appropriate "pre_remove > post_remove > pre_add > post_add"
While doing the same through the API, the signals triggered are "pre_clear > post_clear > pre_add > post_add"

This is exactly the behaviour explained in the tickets referenced above.
pre/post_clear are useless as they does not provide any primary keys :(

Unless I don't understand properly I will try the above using current dev release and keep you posted.

**Comment by xordoquy** [comment]
@jsenecal Actually, you do have different signals whether you're doing with add/remove vs straight assignment. It has nothing to do with DRF itself which is why I was also about to close the ticket.

**Comment by tomchristie** [comment]
> It has nothing to do with DRF itself[...]

Indeed, does sound like the correct assessment.

**Comment by jsenecal** [comment]
Well, for now it seems like django 1.9 is breaking most of the other packages I happen to use.

I'll figure out a workaround for now :(

Thanks @tomchristie and @xordoquy

**Comment by xordoquy** [comment]
DRF won't work as Django removed generic foreign key from 1.9.
