### ISSUE TITLE
datetime field to_representation

### ISSUE THREAD

**Issue by azreda** [tomchristie/django-rest-framework#3001]
Is this really necessary:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L882

```python
            if value.endswith('+00:00'):
                value = value[:-6] + 'Z'
```

Writing a test took a while to figure out that DRF does this transforamtion while vanila Django doesn't, so asserting two string outputs were the same required tracing back to this utility and its change of +00:00 to Z for UTC.

**Comment by kevin-brown** [comment]
This was added in https://github.com/tomchristie/django-rest-framework/commit/20fd738c856dfa21a0d2d251b92459d6641c782c and is [consistent with Django's JSON renderer](https://github.com/django/django/blob/master/django/core/serializers/json.py#L97-L98) (change added in https://github.com/django/django/commit/9b1cb755a28f020e27d4268c214b25315d4de42e).

Technically both representations are valid.

**Comment by tomchristie** [comment]
Either way would be okay, but it's valid for us to normalize that form so going to close this issue.
We could revert it, but we'd likely just have issues with folks who do want the UTC style formatting.
