### ISSUE TITLE
Rotate TokenAuthentication

### ISSUE THREAD

**Issue by s2krish** [tomchristie/django-rest-framework#3002]
django-rest-framework has very simple TokenAuthentication system. Can we add auto rotate function. Let's say, Token has infinite life by default. User has choice to define life in setting.

REST_FRAMEWORK =  {
    'TOKEN_LIFE' : '36'
}

This will cause the token to renew after 36 hours creation. If you guys think, I can improve rest_framework.authtoken.

Thanks

**Comment by xordoquy** [comment]
I'm a bit mixed about this.
I don't think this is a common pattern. Most APIs I've used use a persistent token.
This being said it could be made as a 3rd party module. We have some documentation about this available here: http://www.django-rest-framework.org/topics/third-party-resources/

**Comment by carltongibson** [comment]
> Most APIs I've used use a persistent token.

Very true — or they do something _better_, like OAuth. 

Making the Auth Token app more robust has come up a lot of times. Consistently the answer has been that we keep it as simple as possible and allow users to implement their own solution (or go for a community one) if they need something more. 

There's a list of good options here: [Third Party Resources - Django REST Framework — Authentication](http://www.django-rest-framework.org/topics/third-party-resources/#authentication)

**Comment by kevin-brown** [comment]
I'm -0 on this being implemented in the core, mostly because `TokenAuthentication` is designed to be _basic_.

[It can be done](http://stackoverflow.com/q/27570377/359284), just I personally believe that once you hit that point you are better off with OAuth or JWT.

**Comment by tomchristie** [comment]
> Can we add auto rotate function.

Echoing others. Yes we can have that, but needs to be implemented as a third party app.
