### ISSUE TITLE
"The Browsable API" documentation page makes a reference to a tool that no longer exists

### ISSUE THREAD

**Issue by jaredpetersen** [tomchristie/django-rest-framework#3009]
"The Browsable API" documentation page advises users that they can use the Bootstrap Customize tool to generate new Bootstrap themes. Unfortunately, the Bootstrap Customize tool has been discontinued and the link now points to a page that says as much (http://getbootstrap.com/2.3.2/customize.html).

**Comment by tomchristie** [comment]
Closed by #3010.
