### ISSUE TITLE
get_filter_backends  is present  in documentation, but not exist in code

### ISSUE THREAD

**Issue by malinich** [tomchristie/django-rest-framework#3013]
[django-rest-framework] (http://www.django-rest-framework.org/api-guide/generic-views/)
 i read about method *get_filter_backends*, but in code i see that this module not exist  

```python
    def filter_queryset(self, queryset):
        for backend in list(self.filter_backends):
                queryset = backend().filter_queryset(self.request, queryset, self)
        return queryset 
```
is it norm?

**Comment by tomchristie** [comment]
Documentation looks out of date there. Pull requests welcome.

**Comment by xordoquy** [comment]
Closing this in favor of #3014
