### ISSUE TITLE
Why does APIRequestFactory not return a rest_framework.request.Request object?

### ISSUE THREAD

**Issue by sorreltree** [tomchristie/django-rest-framework#3019]
I was wondering why my requests generated by APIRequestFactory weren't calling the parser or containing a .data attribute.  I may be missing something, but it seems like this test code should pass:

```python
from rest_framework import test, request
req_factory = test.APIRequestFactory()
putreq = req_factory.put(
      '/some/url',
      b'some data',
      content_type='text/plain'
)
self.assertIsInstance(putreq, request.Request)
```

Instead it gets this:

`AssertionError: <WSGIRequest: PUT '/some/url'> is not an instance of <class 'rest_framework.request.Request'>`

Why isn't it?

**Comment by xordoquy** [comment]
Could you be more specific about the issue ?
Where/why do you expect `APIRequestFactory` to provide a rest_framework.request.Request instance ?

**Comment by sorreltree** [comment]
I'm unit testing views, and without things like request.data it's a bit hard.  Something like:
```python
from rest_framework import test, request
from myapp.views import TestView
class ThisTest(test.APITestCase):
  def test_view(self):
    req_factory = test.APIRequestFactory()
    req = req_factory.put('/some/url', b'some data', content_type='text/plain')
    view = TestView()
    response = view.put(req)
    self.assertEqual(response.content.decode(), 'expected return text')
```

**Comment by xordoquy** [comment]
You are supposed to go through the dispatch, not calling put directly

**Comment by sorreltree** [comment]
Hmmm, okay.  My misunderstanding then.

**Comment by xordoquy** [comment]
I think `response = view.put(req)` should be something similar to `response = view(req)`

**Comment by kevin-brown** [comment]
I'm pretty sure it should be

```python
view = MyApiView.as_view()
response = view(request)
```

At least for `APIView` and the related classes. Viewsets require passing in the field mapping into `as_view`.

You can always check the DRF tests.
