### ISSUE TITLE
Inconsistencies with view names

### ISSUE THREAD

**Issue by LuRsT** [tomchristie/django-rest-framework#3021]
Hi,

I noticed this inconsistency, where it's explained [here](http://www.django-rest-framework.org/api-guide/routers/#usage) that one can register a ViewSet passing a `base_name` will override the view names for "detail" and "list".

But [here](http://django-rest-framework.org/api-guide/serializers/#how-hyperlinked-views-are-determined) it says that "By default hyperlinks are expected to correspond to a view name that matches the style '{model_name}-detail' which contradicts the info above.

I checked the code and it [does what it says on the tin](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L54).

Shouldn't everything respect the base_name used when registering the url?

**Comment by xordoquy** [comment]
`base_name` default is `'{model_name}-detail'` which is consistent with the default reverse for hyperlinks.
I don't think there's a consistency issue here.

**Comment by LuRsT** [comment]
@xordoquy, The problem is not the default but the fact that it doesn't respect `base_name`

**Comment by xordoquy** [comment]
ok, let's take it the other way around. If expose a model through two different resources, how is the hyperlink supposed to figure out which base_name it should be using ?

**Comment by xordoquy** [comment]
> But here it says that "By default hyperlinks are expected to correspond to a view name that matches the style '{model_name}-detail' which contradicts the info above.

I realize this may only be semantics. Maybe we should write `'{base_name}-detail'` but this would likely introduce confusion to most of our readers.

**Comment by LuRsT** [comment]
The issue here is that [build_field](https://github.com/tomchristie/django-rest-framework/blob/a3d6601e094b3bde3f7eb9abbb796ac9e222171b/rest_framework/serializers.py#L970) calls `build_url_field` that calls `get_url_kwargs` which calls [get_detail_view_name](https://github.com/tomchristie/django-rest-framework/blob/b07d931261c2e9f722fb2de63ab17f088142b6f1/rest_framework/utils/field_mapping.py#L54) which has an extra 'app_label' passed into a string that doesn't do anything and the model_name. Now what will happen is that if someone uses a `base_name` while registering a URL, this function will never find the correct view.

I hope I made my point clearer

**Comment by xordoquy** [comment]
I need to give this more thoughs as it seems to be more complex than I initially though.

**Comment by LuRsT** [comment]
Cool, shout out if you need any help sorting this out once you know what action should be taken

**Comment by xordoquy** [comment]
Right, so I still don't see where this is inconsistent. The only reason you could see that is because you assume `Router` and `ViewSet` are heavily coupled. However this isn't the case.
You can tune the Hyperlink's view name by using the `view_name` argument. There's no reason it should be linked to the `Router` `base_name` since you should be able to use `ViewSet` even without using `Router`.  In that case you'll have to adapt the hyperlink `view_name` to the view names you actually defined in the urls file.
