### ISSUE TITLE
Recent version unvisible on website

### ISSUE THREAD

**Issue by johnjohndoe** [tomchristie/django-rest-framework#3023]
I noticed that it is hard to find out which is the **current release version** (3.1.3 currently) when I visit [the website](http://www.django-rest-framework.org). I like to suggest that you add the most recent version to the **start page** so people do not have to search or go to this GitHub account.

![website](https://cloud.githubusercontent.com/assets/144518/8078593/12499b36-0f5f-11e5-9b2a-4969c0bec97b.png)

Also the screenshot of the contains version `2.0.0` which might be misleading to a few users.

**Comment by tomchristie** [comment]
I'd suggest that we replace the 'tweet' button with the pypi label that we have on the README.

**Comment by johnjohndoe** [comment]
The button would do the thing. Why replace?

**Comment by tomchristie** [comment]
It would render nicer on mobile if we did remove it, but I'm happy to decouple that conversation from this one - I'd be happy to accept a pull request for this either with or without removing the twitter button.

**Comment by johnjohndoe** [comment]
Nice! Thank you.
