### ISSUE TITLE
Ability to omit value when using "HTML form"

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3036]
In the browsable API, when using the "HTML form" tab, there is no way to omit a given value. Leaving the value as blank is not the same as omitting. For example, I have an `uuid` field that the user can chose to omit (ie not send). If the user _does_ send that value, it is expected to be a valid UUID (ie a blank UUID is not valid).

The current work around is to just use the "raw data" tab and construct the payload manually.

For reference this is:
```
{
 "id": ""
}
```
vs
```
{
}
```

and the Serializer looks like:
```python
PersonSerializer():
    id = UUIDField(required=False, validators=[<UniqueValidator(queryset=Person.objects.all())>])
```

**Comment by xordoquy** [comment]
@cancan101 This is unfortunately how forms do work. I don't see how we could fix that. Do you have some proposal we could discuss ?

**Comment by cancan101** [comment]
In cases in which the field has `required=False`, the generated form could have a check box for the field "omit" which when checked disabled the fields and prevents the key from being sent.

**Comment by cancan101** [comment]
Something like: http://stackoverflow.com/a/15140254/2638485

**Comment by tomchristie** [comment]
Currently don't think the additional UI complexity (and implementation complexity) would be worth it.
Don't have a problem with forms having some limitations myself, and we do always make the raw JSON style also available.
