### ISSUE TITLE
Option for SearchFilter to return 400 if the search query parameter is empty

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3039]
Currently if the search query parameter is empty when using [SearchFilter](http://www.django-rest-framework.org/api-guide/filtering/#searchfilter), no filtering occurs, i.e. the original `queryset` is returned. This is the same behavior as omitting the query parameter entirely. I suggest having an option such that if the query parameter is set to nothing e.g. `?search=` as 400 error should be raised. 

This would be consistent with what github does: https://api.github.com/search/repositories?q=.

Implementation would around [in this line](https://github.com/tomchristie/django-rest-framework/blob/ab7cb44bc514f4bc849ab5a042ced507981673a8/rest_framework/filters.py#L82).

**Comment by xordoquy** [comment]
I had a similar discussion about django-filter. Some API won't return anything, some will return unfiltered data.
This is likely something developer should handle by themselves.
