### ISSUE TITLE
Better error message needed when "many=True" is not included while initializing serializer

### ISSUE THREAD

**Issue by mascot6699** [tomchristie/django-rest-framework#3041]
The error message which is sent when many=true is not set is really absurd. In my case it kept on blaming that a field does not exists in the model rather than telling me that I have a list of objects and thus many=true is need or something like that so that I could figure out the correct error.

**Comment by xordoquy** [comment]
Sounds sensible however a PR would be welcomed.
Closing this meanwhile.

**Comment by mascot6699** [comment]
I will try to dig into this weekend and send a PR.
