### ISSUE TITLE
Send a signal when an ApiToken is requested

### ISSUE THREAD

**Issue by lazerscience** [tomchristie/django-rest-framework#3051]
Sending a signal in the `ObtainAuthToken` would be a useful to let other apps know that a token was requested. (for example to track apps "logging in")
If there's any interested in that I can file a PR for it....

**Comment by tomchristie** [comment]
We have a deliberately simple token API implementation.
Nothing particularly wrong with this suggestion, but tweaks and customizations to this are best handled in your own codebase.
