### ISSUE TITLE
NOT_READ_ONLY_REQUIRED Error Message Not Very Helpful

### ISSUE THREAD

**Issue by jeffasinger** [tomchristie/django-rest-framework#3055]
The way the traceback appears with the NOT_READ_ONLY_REQUIRED error message, it's not possible to tell which field is causing the problem.

It would be nice if it included the field name in the error message.

**Comment by tomchristie** [comment]
There's no obviously easy way for us to do this. I'd by happy to consider any pull requests that inspected the stacktrack to determine what the field name and serializer class was at the point of error, but otherwise we're just going to need the user to dig this out themselves.
