### ISSUE TITLE
Disabling URL_FORMAT_OVERRIDE

### ISSUE THREAD

**Issue by jpadilla** [tomchristie/django-rest-framework#3057]
Should setting `URL_FORMAT_OVERRIDE` to None disable it's behavior similar to the other browser override settings? I think it should. It currently does work although undocumented.

If disabled, we should probably also hide these format choices which link to `?None=json`.
![screen shot 2015-06-22 at 4 13 39 pm](https://cloud.githubusercontent.com/assets/83319/8291796/ac5444bc-18f9-11e5-9af7-2d7a8e61f154.png)

**Comment by tomchristie** [comment]
> Should setting URL_FORMAT_OVERRIDE to None disable it's behavior

Yes

> If disabled, we should probably also hide these format choices which link to ?None=json.

Yes

:smile:

**Comment by jpadilla** [comment]
@tomchristie do we not show the GET button too or just remove the dropdown next to it?

**Comment by tomchristie** [comment]
@jpadilla I'd suggest just hide the dropdown.

**Comment by jpadilla** [comment]
@tomchristie we'd end up with a button that just links to the same page you're on though.

**Comment by tomchristie** [comment]
@jpadilla - I think it's probably reasonable enough tho - may have made a non-GET request to the page previously. Also if it's there or not helps indicate if it's a valid method.
