### ISSUE TITLE
allow_null broken in DateTimeField

### ISSUE THREAD

**Issue by nmgeek** [tomchristie/django-rest-framework#3059]
Today I found that the serializer DateTimeField does not support null values, even when you set allow_null=True.  I ended up making a copy of the DRF implementation (somehow, DRF does not let you derive new classes from existing Serial Field classes??) and adding two lines to the to_internal_value() method.  It looks like this:

```
   def to_internal_value(self, value):
        # allow None as text string since json encodes it that way                                                                 
        if value == 'None':
            return None
        ... rest of the original function ...
```

I'm not sure if this was the right way to fix it but it should give you an idea what the bug is about.

**Comment by tomchristie** [comment]
`allow_null` *is* a valid argument in `DateTimeField`. I don't currently have any evidence to suppose that's broken in anyway and given the large installed base I'm inclined to close this ticket off unless there's a simple demonstration of the behavior being broken. (Eg a failing test or simple instructions on how to replicate)

> somehow, DRF does not let you derive new classes from existing Serial Field classes

Again, not sure what's meant here - you can subclass Field classes. A fuller explanation of exactly what issue you're seeing might tease out if there's any missing or non-obvious documentation that we could improve.

**Comment by nmgeek** [comment]
I didn't just make this up.  It will take some work on my part to produce and post a small test case.  And of course something else in my code could have caused this.

Is it normal for the string, 'None', to be passed into to_internal_value as a representation of a null value?
-Glenn

**Comment by tomchristie** [comment]
> I didn't just make this up. It will take some work on my part to produce and post a small test case.

Appreciate that, but with the current level of information here it's not possible for us to distinguish this from a user issue. Doesn't necessarily need to be a test case - a minimal example of how to replicate and a fuller description of the behavior would also be okay.

We've closed nearly 3,000 issues and pull requests over the lifetime of the project. If someone wants to report an issue we do need to ask for enough information from them to properly triage it without having to put in significant initial effort ourselves. Not doing so introduces an unacceptable drag on other outstanding issues and features.

> Is it normal for the string, 'None', to be passed into to_internal_value as a representation of a null value?

No, I'd expect a `None` value to be passed for nulls, although it won't be passed to `to_internal_value()` as nulls are handled outside of that flow.

**Comment by nmgeek** [comment]
> No, I'd expect a None value to be passed for nulls, although it won't be passed to to_internal_value() as nulls are handled outside of that flow.

Ah.  That is incredibly helpful.  Right.  I couldn't figure out any reasonable thing to do with the 'None' value so my code is really messy right now.  I'm working to boil this down to some root cause.

**Comment by nmgeek** [comment]
Some additional documentation could prevent others from falling into the same 'trap' I fell into.  The client of my rest framework API is another Django app and I was using urllib.urlencode to encode the data arguments for the API calls.  The correct encoding requires json.dumps.  It turns out that urllib works as long as none of the values are None/null or lists.  When you introduce an argument value of None/null you get the problem I reported in this issue.

If you google search for examples of how to call Django REST apis you find examples that use urllib so others could be led astray.  What about a section in the DRF documentation on how to call a DRF API from Python (yes, you have examples with httpie but you have to dig into its source code to see how it serializes and json-encodes the data)?

The code that works for me looks like:
```
import requests

headers = {'Authorization':'Token '+token, 'Content-type': 'application/json'}
if paramData:
    jsonData = json.dumps(paramData)
    response = requests.post(url, data=jsonData, headers=headers)
else:
    response = requests.get(url, headers=headers)
```

**Comment by nmgeek** [comment]
Now that I know the answer, I found just one stackoverflow post that shows how to do it.  But from its title you wouldn't think that's what it shows and the solution is in the question rather than the answer:

http://stackoverflow.com/questions/17560228/how-to-use-tokenauthentication-for-api-in-django-rest-framework
