### ISSUE TITLE
Include pagination override query param

### ISSUE THREAD

**Issue by erichonkanen** [tomchristie/django-rest-framework#3069]
Hello,

Recently I have run into an issue where I need pagination turned on for a resource endpoint but I also need the ability to optionally return the entire dataset.

AFAIK this isn't a feature that's built into pagination. This comes up when using ember.js framework with ember-data as the framework will automatically try to grab records in certain scenarios but it can't fulfill the requested data because it only gets a subset back.

What I'm wondering is if we could include another query param that would tell the backend to return the full dataset? Example

`http://api.myapp.com/v1/organizations/?page_num=all`

Let me know your thoughts thanks!

**Comment by jpadilla** [comment]
IMHO we're very much likely not be including anything like this in core.

You might be able to do something like below:
```python
def list(self, request, *args, **kwargs):
    queryset = self.filter_queryset(self.get_queryset())

    if request.query_params.get('page_num') != 'all':
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

    serializer = self.get_serializer(queryset, many=True)
    return Response(serializer.data)
```

**Comment by erichonkanen** [comment]
hey @jpadilla, 

ok yeah that seems like it should do the trick... out of curiosity, what would be a reason to not include this? I was wondering if it's a case that others run into...

cheers,
-eric

**Comment by jpadilla** [comment]
FWIW you can also implement a custom pagination serializer class if you needed to reuse this elsewhere.

It's usually encouraged that changes and additions like this to be released as a third party package or even a gist, which we can link to from the docs.

**Comment by erichonkanen** [comment]
ok thanks

**Comment by tomchristie** [comment]
> out of curiosity, what would be a reason to not include this?

Mostly just the very large number of feature requests that we get.
It *would* be useful for *some* people, but for anyone else it introduces extra complexity.
Those bits of extra complexity are small by themselves, but if we met each feature request in the core package it'd continually get more complex, overweight and less useable.
Forcing overrides into user codebases (or optional third party packages) ensures we keep the complexity well managed.

Hope that helps explain the motivation. :smile:

**Comment by erichonkanen** [comment]
ok great thanks @tomchristie, makes sense
