### ISSUE TITLE
Combination of ScopedRateThrottle and AnonRateThrottle

### ISSUE THREAD

**Issue by lsapan** [tomchristie/django-rest-framework#3079]
I apologize if this is possible, but from the documentation it doesn't look like you can create a ScopedRateThrottle that only affects anonymous users. (So for example, anyone without an API key is throttled based on certain scopes).

The only solution appears to be a custom throttle class, but it seems like something that would be common enough to have built in. Is there already a way to do this?

**Comment by tomchristie** [comment]
> The only solution appears to be a custom throttle class

That's correct, yup. You probably want to override ScopedRateThrottle and add in the custom behaviour you need. Then set your new custom throttle in the settings.

**Comment by lsapan** [comment]
For anyone looking in the future, the solution to this was actually just overriding the `scope` property on AnonRateThrottle. I should've looked at the code to begin with, it was quite obvious. @tomchristie It might not hurt to mention in the docs that `scope` applies to all three included throttlers. If you're _just_ going off of the docs, you'd never know.
