### ISSUE TITLE
Make trailing slash configurable in settings

### ISSUE THREAD

**Issue by RyanPineo** [tomchristie/django-rest-framework#3080]
I think it would be useful to have the trailing slash default be configurable in the DRF settings instead of having it hard coded in the router.  Right now if you want no trailing slash you have to either subclass the router or pass the argument to every router.

**Comment by tomchristie** [comment]
> or pass the argument to every router.

I don't see much of a problem here. Typically you'll only have one router, or at most one per urls.py module.

Out job here isn't to ensure that there's the most minimal amount of code possible, rather that the code that is written is simple and maintainable.
