### ISSUE TITLE
FileField upload_to not processed

### ISSUE THREAD

**Issue by ybendana** [tomchristie/django-rest-framework#3082]
I'm setting this argument on my model but it appears the ModelSerializer ignores it.  I've printed out the serializer in the Django shell and it doesn't list upload_to in the arguments to my FileField. When I run my app, It just sets the path to the MEDIA_ROOT in my settings file.  I've also tried setting the upload_to to a function and I've verified with pdb that it doesn't get called.  The Serializer FileField documentation doesn't mention upload_to, but since it is part of core Django I assumed it was supported.

**Comment by tomchristie** [comment]
upload_to is the responsibility of the model field to handle. The serializer field just handles the validation and returning an `UploadedFile` object. If you call `serializer.save` then the default model save behavior will handle the file saving for you. Closing along with #3083.
