### ISSUE TITLE
Have to manually call FileField.save() to save uploaded file on update

### ISSUE THREAD

**Issue by ybendana** [tomchristie/django-rest-framework#3083]
I'm using 3.1.3 and my uploaded file is no longer being saved on update using angularFileUpload. This used to work in 2.4, but my code has changed alot to work in 3.x.  In my serializer I have an update() where I do this to update my validated fields:

    MyMgr.filter(pk=instance.id).update(**validated_data)

My uploaded file is in the validated_data but is not saved to the media directory although the FileField.url is updated when the filename changes.  However it does not reflect the upload_to setting as I mentioned in #3082.  The FileField is defined like so in models.py:

    my_file = models.FileField(blank=True, upload_to='files/%Y/%m/%d')

If I call FileField.save() manually like so:

    myfile = validated_data.get('myfile')
    updated_inst = MyMgr.get(pk=instance.id)
    if myfile:
        updated_inst.my_file.save(myfile.name, myfile)

the file is saved in the directory defined by upload_to.

**Comment by tomchristie** [comment]
I think you're having an issue with your usage of Django and UploadFiles here, nothing to do with REST framework itself.

> My uploaded file is in the validated_data

So REST framework has correctly uploaded a temporary file. It's the responsibility of the model field to handle persisting that to a saved upload file. Calling `serializer.save` would do that, or else creating a model instance manually.

> MyMgr.filter(pk=instance.id).update(**validated_data)

I assume that queryset updates won't cause temporary files to be save. (There's lots of ways they will be different to a model instance save) Either way thats a Django usage issue, not a REST framework bug. So I'm going to close this ad #3082.

(And yes I'm sympathetic to this, working with upload files and dealing with all the `MEDIA_ROOT`, `STATIC_ROOT`, `MEDIA_URL`, storage backends, etc is often kinda fiddly)
