### ISSUE TITLE
`has_object_permission()` getting ignored by viewsets.ModelViewSet if `has_permission()` is defined

### ISSUE THREAD

**Issue by Amberdilis** [tomchristie/django-rest-framework#3084]
As title says. Accessing /[model]/[pk]/ results in `has_permission()` getting called instead of `has_object_permission()` if the former is defined.

**Comment by cancan101** [comment]
Can you provide more details of where you think this is happening? The [call to `has_object_permission`](https://github.com/tomchristie/django-rest-framework/blob/3e1687282ba39b0166b7c17e39cdd3a2be7e2bc3/rest_framework/views.py#L318) does not seem to care if `has_permission` is defined and in fact is evaluated later once /if the object is resolved.

**Comment by tomchristie** [comment]
The global `has_permission()` check is always called. The instance level `has_object_permission()` check is called for object level accesses if the global check has passed first (we don't need to check it if they don't have global permission in the first place)
