### ISSUE TITLE
Setting with tuple value shouldn't be converted into list

### ISSUE THREAD

**Issue by devoto13** [tomchristie/django-rest-framework#3087]
When accessing setting though `from rest_framework.settings import api_settings` it will be converted from tuple to list (unless it's empty tuple). This behavior is inconsistent.

### Failing test case

```
from rest_framework.settings import api_settings
from rest_framework.test import TestCase


class TestSettings(TestCase):
    def test_setting_type_is_not_changed(self):
        self.assertTrue(isinstace(api_settings.DEFAULT_THROTTLE_CLASSES, tuple))
```

Will pass with these settings:

```
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': ()
}
```

But will fail with these ones:

```
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    )
}
```

### Expected behavior

Setting type is not changed, when it is imported through `from rest_framework.settings import api_settings`.

### Investigation

It seems issue comes from `rest_framework/settings.py:perform_import()` and can be easily fixed. I can submit pull request if it's considered a bug and not intended behavior.

**Comment by tomchristie** [comment]
Coercing to lists is intended. Don't make assumptions in the code about the type of tuple vs list, just treat them as an immutable iterable. You shouldn't really need to perform type checking on them anywhere, and can just use `isinstance(..., (tuple, list))` if you really do want to do so.

**Comment by devoto13** [comment]
Okey, so then I expect this coercing to be consistent at least. Empty tuple still stays tuple...

My problem comes from different configurations for different environments. I have throttling enabled for production (not empty tuple), but not for development (empty tuple). And I have ViewSet, which adds additional throttling class to default ones, e.g.:

```
from rest_framework.settings import api_settings


class CommentViewSet(...):
    throttle_classes = api_settings.DEFAULT_THROTTLE_CLASSES + (CommentThrottle, )

```

For one environment tuple is returned and for another one - list. And I get TypeError, when trying to join tuple with list. So I can't do it for both environments with the same code.

**Comment by tomchristie** [comment]
Resolved. Will consistently be lists now.

**Comment by devoto13** [comment]
Great! Thank you :+1:
