### ISSUE TITLE
Django REST Framework - how to do Token Authentication with Memcached

### ISSUE THREAD

**Issue by somghosh** [tomchristie/django-rest-framework#3089]
I am using TokenAuthentication for several of my DRF views. The view code itself have optimized logic for to use memcached if the key exists in the cache - to speed up by reducing DB queries. However, I see that for each of the API requests from phone(client), the server still does one query at least - `Postgres authtoken_token select` for validating user for the authtoken sent

Is there a way to avoid this, since the authtoken is rarely changed - by keeping it in the cache?

I am using the following in `settings.py`, but I don't think this is helping my case

    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

**Comment by tomchristie** [comment]
We use the issue tracker for keeping track of active bugs and other ongoing work on the project.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
