### ISSUE TITLE
MappingField addition

### ISSUE THREAD

**Issue by Anton-Shutik** [tomchristie/django-rest-framework#3096]
Hey guys!

Does DRF have smth like MappingField ?

It would work like this:

```
 class MySerializer(serializers.Serializer):
    my_field = MappingField(mapping={'key': 'value'})

ms = MySerializer(data={'my_field': 'value'})
ms.is_valid()
ms.validated_data #  {'my_field': 'key'}

# and backwards

ms = MySerializer(instance={'my_field': 'key'})
ms.data # {'my_field': 'value'}
```

That will be very useful when mapping your model fields with 3rd party service's REST API fields

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
