### ISSUE TITLE
ChoiceField metadata does not support grouped choices.

### ISSUE THREAD

**Issue by maxpeterson** [tomchristie/django-rest-framework#3101]
If a serialiser has a ChoiceField with grouped choices: 

```
TYPE_CHOICES = (
        ('Default', (
            (1, 'Option 1'),
            (2, 'Option 2'),
            (3, 'Option 3'))),
        (4, 'Option 4'))
```
The `OPTIONS` metadata for the field includes the `choices`:

```
[
    {
        "value": "Default",
        "display_name": "((1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'))"
    },
    {
        "value": 4,
        "display_name": "Option 4"
    }
]
```

I am not certain what the behaviour should be, but something including the nested choices would be useful:

```
[
    {
        "choices": [
            {
                "value": 1,
                "display_name": "Option 1"
            },
            {
                "value": 2,
                "display_name": "Option 2"
            },
            {
                "value": 3,
                "display_name": "Option 3"
            }
        ],
        "display_name": "Default"
    },
    {
        "value": 4,
        "display_name": "Option 4"
    }
]
```

If this is not appropriate then a flat list of choices might be appropriate.
```
[
    {
        "value": 1,
        "display_name": "Option 1"
    },
    {
        "value": 2,
        "display_name": "Option 2"
    },
    {
        "value": 3,
        "display_name": "Option 3"
    },
    {
        "value": 4,
        "display_name": "Option 4"
    }
]
```

**Comment by tomchristie** [comment]
The flat list of choices would be my preferred option here.

**Comment by maxpeterson** [comment]
@tomchristie I was hoping you would go for the hierarchical one as I need the hierarchy in an application consuming the api.

If the choices are flat, then how would you recommend we get the hierarchy from the api. My first idea would be to extend `SimpleMetadata` globally or on my view to include an extra attribute for the field.

**Comment by tomchristie** [comment]
> My first idea would be to extend SimpleMetadata globally (or on my view) to include an extra attribute for the field.

Exactly so, yes.

**Comment by maxpeterson** [comment]
Related to #1533

**Comment by tomchristie** [comment]
Rolling this into #1533.

**Comment by wernerhp** [comment]
@maxpeterson @tomchristie I also need the nested/grouped representation on to be returned by the meta for an app.  Can you guys perhaps link me to an example of hot to do this?

**Comment by maxpeterson** [comment]
@wernerhp I have achieved this by adding an additional `grouped_choices` attribute to the meta.  I am afraid the code is in a private repo so hopefully these "snippets" will help:

```
def get_choice(choice_value, choice_name):
    if isinstance(choice_name, (list, tuple)):
        return {
            'choices': [get_choice(*choice) for choice in choice_name],
            'display_name': force_text(choice_value, strings_only=True)
        }
    return {
        'value': choice_value,
        'display_name': force_text(choice_name, strings_only=True)
    }


def grouped_choices(choices_list):
    return [get_choice(*choice) for choice in choices_list]


class GroupedChoiceMetadata(SimpleMetadata):
    def get_field_info(self, field):
        field_info = super().get_field_info(field)

        if not field_info.get('read_only') and hasattr(field, 'choices_list'):
            field_info['grouped_choices'] = grouped_choices(field.choices_list)

        return field_info
```

**Comment by wernerhp** [comment]
@maxpeterson Thanks for the snippet.  I'm still battling a bit.  `choices_list` doesn't seem to be a standard attribute of `serializers.ChoiceField`.  Would you minding including a snippet from your Serializer, Model and your nested/grouped `XYZ_CHOICES` data structure.  Thanks in advance

**Comment by maxpeterson** [comment]
@wernerhp try using [field.grouped_choices](https://github.com/tomchristie/django-rest-framework/blob/4655501d51080fbc7733a81fab1a227229a33e3f/rest_framework/fields.py#L1272) - Sorry about that `choices_list` was based on an earlier version I used

**Comment by maxpeterson** [comment]
Here is the PR https://github.com/tomchristie/django-rest-framework/pull/3225 `grouped_choices` was added and my original one https://github.com/tomchristie/django-rest-framework/pull/3108 (where I suggested `choices_list`)

**Comment by maxpeterson** [comment]
To clarify try ...

```
def get_choice(choice_value, choice_name):
    if isinstance(choice_name, (list, tuple)):
        return {
            'choices': [get_choice(*choice) for choice in choice_name],
            'display_name': force_text(choice_value, strings_only=True)
        }
    return {
        'value': choice_value,
        'display_name': force_text(choice_name, strings_only=True)
    }


def grouped_choices(choices_list):
    return [get_choice(*choice) for choice in choices_list]


class GroupedChoiceMetadata(SimpleMetadata):
    def get_field_info(self, field):
        field_info = super().get_field_info(field)

        if not field_info.get('read_only') and hasattr(field, 'grouped_choices'):
            field_info['grouped_choices'] = grouped_choices(field.grouped_choices)

        return field_info
```

**Comment by wernerhp** [comment]
After some effort I found that `group_choices` is actually a property on `ChoiceField`
This seems to do the trick
```py
class GroupedChoiceMetadata(SimpleMetadata):
    def get_field_info(self, field):
        field_info = super(GroupedChoiceMetadata, self).get_field_info(field)

        if field_info.get('type') is 'choice':
            field_info['grouped_choices']= field.grouped_choices

        return field_info
```
I wonder why `grouped_choices` aren't returned by default?

@tomchristie Do you perhaps have some insights for me?

**Comment by tomchristie** [comment]
@wernerhp - Mostly likely simply historical. Expect they didn't exist when we added the metadata API.
