### ISSUE TITLE
Store OPTIONS requests into viewset's self.action

### ISSUE THREAD

**Issue by normanjaeckel** [tomchristie/django-rest-framework#3115]
At the moment, self.action is None in viewsets if I get an OPTIONS request. I think I can inspect self.request.method.lower() but it would be nice if it is also in self.actions so I can use it as generic point for customized viewset code (customized permission checks in our case: https://github.com/OpenSlides/OpenSlides/issues/1595).

**Comment by tomchristie** [comment]
Reopening this until https://github.com/tomchristie/django-rest-framework/commit/538ffaf6c71944aa4f0d77f1167c2cef570dabe1 has been addressed.

**Comment by catskul** [comment]
I believe I've fixed it here: 
https://github.com/tomchristie/django-rest-framework/pull/3158

**Comment by tomchristie** [comment]
And, resolved again.
