### ISSUE TITLE
Documentation: api-guide should have a testing section about serializers and fields.

### ISSUE THREAD

**Issue by dnozay** [tomchristie/django-rest-framework#3119]
The api-guide should have a testing section about serializers and fields. Those would be helpful.

**Comment by xordoquy** [comment]
I'm closing this as this lacks context. Feel free to reopen if you can provide a bit more informations about what you'd like to see covered.

**Comment by dnozay** [comment]
* how to write / example unit tests for a serializer
* how to write / example unit tests for a field with `default_validators`
etc.

**Comment by dnozay** [comment]
> I'm closing this as this lacks context. Feel free to reopen if you can provide a bit more informations about what you'd like to see covered.
I am merely saying that the api-guide testing section is lacking in terms of examples and searching SO for questions about DRF unit tests points to the same conclusion.

**Comment by xordoquy** [comment]
The lack of SO questions might be because Drf comes with a huge set of tests which you can reuse.

**Comment by tomchristie** [comment]
I'd suggest that if anyone wants to progress this issue the best thing to do would be to come up with an example that we could review, and determine if we think it'd be valuable
