### ISSUE TITLE
Allow related field to be excluded from OPTIONS

### ISSUE THREAD

**Issue by dvinegla** [tomchristie/django-rest-framework#3120]
I have a related field:
    post = serializers.PrimaryKeyRelatedField(
        queryset=Post.objects.all(),
        style={'base_template': 'input.html'}
    )

and when I make an OPTIONS call, it returns a list of all post.
there is a method to disable this behaviour?

**Comment by tomchristie** [comment]
You'd want to cusomitze the metadata class to do that: http://www.django-rest-framework.org/api-guide/metadata/
