### ISSUE TITLE
Related fields with _id suffix

### ISSUE THREAD

**Issue by ostcar** [tomchristie/django-rest-framework#3121]
It would be nice if there were an option, that PrimaryKeyRelatedField adds a _id suffix to the field_name on the serializer.

For example, if there is a user model with a relation to a profile, then the serializer should return:
```json
{
  "id": 1,
  "username": "FOO",
  "profile_id": 1
}
```

instead of:
```json
{
  "id": 1,
  "username": "FOO",
  "profile": 1
}
```

This has the advantage, that the client using the rest api can set the attribute profile on the returned object. At the moment this is not possible.

I was able to get this behaviour in my project with django rest framework 3.1.3, but I had to use a lot of undocumented stuff. So it would be nice if this feature could be implemented in core.
https://gist.github.com/ostcar/eb78515a41ab41d1755b

**Comment by tomchristie** [comment]
Look into overriding `get_fields` and the other hooks on serializer (as it looks like you've done).

I might accept documentation issues against this section http://www.django-rest-framework.org/api-guide/serializers/#customizing-the-default-fields in order to move more of that into public API, but otherwise I think this all needs to be third party package options or gists that we can link to, rather than adding extra options into core.

**Comment by ostcar** [comment]
To override ```get_fields``` or ```get_field_names``` works great for ForeignKeys and OneToOneFields but is hacky on ManyToManyFields.

The problem is, that ManyRelatedField.get_attribute tires to get the attribute self.source_attrs from the django model instance:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L387

This attribute is set by Field.bind()
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L250

It is hard to override the bind method because RelatedField always uses ManyRelatedField. There is no way to change this in another way then override the entire method ```many_init``` .

If you could merge #3122 then this would be fixed.

See the gist how it would be possible after the merge of my pull request.

**Comment by emacsway** [comment]
I think, this should be in core.

**Comment by xordoquy** [comment]
It won't be unless you can provide new arguments to the discussion.
On a side note, I don't see why you can't just make the field explicit with the <name>_id and use source to map to the model.

**Comment by emacsway** [comment]
Thanks for answer.
> I don't see why you can't just make the field explicit with the {name}_id and use source to map to the model.

\- There is one reason: I don't need ModelSerializer if I have to declare fields manually. The main advantage of django-rest-framework is the rapidly development. In 90% cases I don't have to declare fields (except relations). This is a disadvantage, which already has the complete solution (not merged yet).

**Comment by smcoll** [comment]
@ostcar one way that approach breaks down is if i still want to have a serializer using the original field name.  For example, i have a requirement to support a writable serializer `<field>_id` and a read-only nested `<field>` serialization side-by-side:
```
{
  "id": 1,
  "username": "FOO",
  "profile_id": 1,
  "profile": {
    "id": 1,
    "avatar": "http://example.com/foo.gif"
  }
}
```

An `IdModelSerializer` with declared nested serializer `profile` means that `profile_id` won't appear:
```
class UserSerializer(IdModelSerializer):
    profile = ProfileSerializer(read_only=True)

    class Meta:
        model = User
        fields = ('id', 'username', 'profile')
```

Maybe another approach is to support `<field>_id(s)` field names in `Meta.fields`:

```
class UserSerializer(IdModelSerializer):
    profile = ProfileSerializer(read_only=True)

    class Meta:
        model = User
        fields = ('id', 'username', 'profile', 'profile_id')
```

**Comment by xbazhen** [comment]
This have a resolve method

**Comment by Frankitch** [comment]
I'm trying to use @ostcar's gist but this does not work in many cases.
He is talking about the override of `many_init` that is required but I can't see this method the gist.
Any insight please?

**Comment by ostcar** [comment]
I have not used django-rest-framework for some time. Here is the code, that used this change: https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/server/openslides/utils/rest_api.py
