### ISSUE TITLE
Cannot set `unpack_ipv4` with IPAddressField

### ISSUE THREAD

**Issue by brandoncazander** [tomchristie/django-rest-framework#3123]
The [documentation](http://www.django-rest-framework.org/api-guide/fields/#ipaddressfield) states that the IPAddressField takes `unpack_ipv4` as an argument, which is False by default and can only be used when protocol is 'both' (which is in line with Django's GenericIPAddressField).

When I try to use this option, I get an exception: 

>TypeError: __init__() got an unexpected keyword argument 'unpack_ipv4'

It looks like `IPAddressField.__init__` sets unpack_ipv4 to True if the protocol is 'both' (which is contrary to the docs): https://github.com/tomchristie/django-rest-framework/blob/dee5fb56479edc05cd0dcc827607696e58710eda/rest_framework/fields.py#L683

**Comment by tomchristie** [comment]
Good catch.
The code is as it should be, but the docs need updating.

**Comment by brandoncazander** [comment]
I think the code needs an update as well. 

1. If you create a field `serializers.IPAddressField('IPv4')` then you don't get any validation at all.
2. There is no way to disable unpacking of IPv4 addresses when using both protocols.

**Comment by tomchristie** [comment]
I'd be happy to consider either of those if expanded on in their own issues.

**Comment by tomchristie** [comment]
> 1. If you create a field serializers.IPAddressField('IPv4') then you don't get any validation at all.

You get ipv4 validation in that case

> There is no way to disable unpacking of IPv4 addresses when using both protocols.

I'd rather we take an informed decision as to which behavior we should use rather than present it as a flag.

**Comment by brandoncazander** [comment]
My apologies; I just tried the IPv4 validation with a fresh Django project and it returning a ValidationError. The behavior I was seeing must have been specific to my serializer, whoops!

As for the unpacking of IPv4 addresses, I prefer that the default behavior is the same as the model field in Django. (See https://docs.djangoproject.com/en/1.8/ref/models/fields/#genericipaddressfield). If you try to set `unpack_ipv4=True` on a field where `protocol='IPv4'` an AssertionError is raised. On the other hand, if `protocol='both'`, then `unpack_ipv4` is False by default, but can be explicitly enabled.
