### ISSUE TITLE
Adding "required" option to a filter does not give proper result

### ISSUE THREAD

**Issue by qrilka** [tomchristie/django-rest-framework#3124]
django-filter has `required` option for filters and my tests show that if I add that option to a filter and do a request without a value for that filter I get just `[]` as a result. I think it makes much more sense to return an error in that case, probably 400 is a suitable code for such situation.

**Comment by carltongibson** [comment]
Is this a DRF issue; it's a Django Filter one right? 

We just merged in alex/136 which adds an option to `raise` for an invalid value — not identical but similar.  Take a look. Feel free to open an issue over on Django Filter. 

I'm going to close this on the assumption it is a DF thing. If not shout and we can re-open. :-)

**Comment by qrilka** [comment]
@carltongibson looks like a proper solution, we currently use DRF 2.4.4 and with it I get 500 returned - do we need to upgrade to 3rd version of DRF to get proper 400?

**Comment by carltongibson** [comment]
I think we may need to make an adjustment on Django Filter to get the behaviour you want out the box. 

(Although I'm now confused as to exactly what behaviour you do want — how's the empty QuerySet leading to a 500? — Can't you catch that somewhere? If we did `raise` in DF you'd still need to catch that somewhere — maybe override `GenericAPIView.filter_queryset`. ...)

**Comment by qrilka** [comment]
@carltongibson I say I get 500 with `strict.RAISE_VALIDATION_ERROR` in my filterset using DRF 2.4.4

**Comment by carltongibson** [comment]
Right, so you're going to need to catch that somewhere if you want to convert it to a 400. v3 doesn't change the behaviour here.

**Comment by qrilka** [comment]
I.e. `forms.ValidationError` should be wrapped into `serializers.ValidationError` described at http://www.django-rest-framework.org/api-guide/serializers/#validation am I right?

**Comment by carltongibson** [comment]
Yeah, I guess. It's kind of project specific... http://www.django-rest-framework.org/api-guide/exceptions/
