### ISSUE TITLE
UUIDField doesn't allow_blank

### ISSUE THREAD

**Issue by bretth** [tomchristie/django-rest-framework#3130]
I want to create a uuid using uuid = serializers.UUIDField(default=uuid4) if one isn't provided but the data entered via the form is an empty string which is not treated as an empty value thus returns a error response.

**Comment by xordoquy** [comment]
You are missing `allow_blank` without which the validation will fail.

**Comment by bretth** [comment]
The UUIDField doesn't have a allow_blank option.

**Comment by xordoquy** [comment]
Bingo.

**Comment by tomchristie** [comment]
I'm unclear on:

1. What the expected behavior should be here. It's not obvious if an empty string should raise a validation error or use the default. With an HTML form it's clear why you'd prefer it to use the default, but with JSON you'd probably instead want an empty string or None to fail validation, and only use the default if no value is supplied.
2. If we should include an `allow_blank` option, or not. Not obvious to me that if it'd be a valid or useful thing to specify on a UUID field.

I'm probably just being a little slow today, but it'd be good if we could spell those out.

**Comment by xordoquy** [comment]
Even with an HTML form, you'd need `allow_blank` to pass the validation anyway. See CharField for example:
```
>>> field = serializers.CharField(default='a')
>>> field.run_validation('')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/xordoquy/.local/share/virtualenvs/microinvoices/lib/python3.4/site-packages/rest_framework/fields.py", line 585, in run_validation
    self.fail('blank')
  File "/Users/xordoquy/.local/share/virtualenvs/microinvoices/lib/python3.4/site-packages/rest_framework/fields.py", line 438, in fail
    raise ValidationError(message_string)
rest_framework.exceptions.ValidationError: ['This field may not be blank.']
>>> 
```

**Comment by bretth** [comment]
Ok since pg doesn't allow an empty string in uuid type then null or default (a uuid) is what it can be, or it's invalid. So yes, regardless that the other backends use char type for uuid allow_blank doesn't make sense.

**Comment by bretth** [comment]
A default should probably also negate the need for allow_blank in CharField. It's reasonable to assume that default is a proxy for user input - otherwise in the context of a browsable api form it seems pointless.

**Comment by xordoquy** [comment]
The point is that it brings more implicit behaviour which we don't want

**Comment by bretth** [comment]
Going back to the why for a second... 

Getting a product id from an external source that is also their primary key I either want to take a uuid pre-created from uuid5 (ie with a namespace for that source), or (more likely) I'll have a form field for `external key` and `namespace` and create the uuid5 myself, unless the external source is unreliable as a primary key in which case I create a uuid4 (the default) and save it as the primary key (id).

With respect to treating json and forms differently; since you have access to the request object in field validation via context, in theory it is a matter of determining if it is an html form post and evaluating an empty string within the limitations of the form.

**Comment by xordoquy** [comment]
I still don't see how your use case would go against having a `allow_blank` option set to True.
The choice between (`external-key`, `namespace`) vs `default` should be done in the serializer's validation.
I'm feeling like I'm missing your point.

**Comment by bretth** [comment]
No, I've realised my mistake. I was confusing a model uuid with the form field uuid when the two are separate concerns; `allow_blank` is what it should be.

**Comment by tomchristie** [comment]
Okay, now resolved.

UUIDField doesn't support `allow_blank` because it's not valid.

However it does now properly respect `required=False` or `default=...` when it recieves an empty HTML field input. Issue also affected other field types.
