### ISSUE TITLE
request.data is sometimes a django.http.request.Request, sometimes a dict

### ISSUE THREAD

**Issue by gergelypolonkai** [tomchristie/django-rest-framework#3132]
I am testing my REST API in the test server (`manage.py runserver` and using the self-written JS application), the test framework (`manage.py test`) and with [httpie](https://github.com/jkbrzt/httpie). It seems that in viewset methods `self.request` is always a `rest_framework.request.Request`, but `self.request.data` is a `django.http.request.QueryDict` with `runserver` and `test`, but using `runserver` with httpie results in `self.request.data` being a plain `dict`.

Is there a (documented) reason behind this? If not, it would be nice to make this more straightforward. Currently I have to use some extra, seemingly unnecessary checks like

    params = self.request.data
    if isinstance(params, QueryDict):
        params = params.dict()

although I haven’t yet found a `dict` case other than using httpie.

**Comment by tomchristie** [comment]
Most likely you're seeing different data structures due to passing different data.

JSON will result in a plain dict
MultiPart data will result in a query dict (because multipart supports multiple values per key)

**Comment by xordoquy** [comment]
@gergelypolonkai looks like you're sending JSon data with httpie and html form with JS / test framework.
The reason behind is that we need this in some cases for the serializers to work (See `Serializer.get_value` around https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L366)

Why do you need to perform a params.dict ? QueryDict should behave as a dict

**Comment by gergelypolonkai** [comment]
After performing a bunch of checks and popping out some keys I pass the resulting `dict` to another function as **kwargs.
