### ISSUE TITLE
TokenAuthentication does not use result from authenticate_header in authenticate

### ISSUE THREAD

**Issue by jgadelange** [tomchristie/django-rest-framework#3135]
In `TokenAuthentication` I believe that in `authenticate()` the result of `authenticate_header()` should be used when checking the first part of the authorization header. Currently the code just checks on `token`:
```
if not auth or auth[0].lower() != b'token':
    return None
```

When you override the `TokenAuthentication` to use another authenticate header, it will not work anymore.

**Comment by tomchristie** [comment]
If you want to override the class so it doesn't need to use `'Token'` then you need to override both methods.

C'est la vie.
