### ISSUE TITLE
Views should be allowed to return plain objects

### ISSUE THREAD

**Issue by alexpdp7** [tomchristie/django-rest-framework#3136]
Instead of writing:

  return response.Response({'foo': 'bar', 'baz': 'quux'})

it would be nice if you could:

  return {'foo': 'bar', 'baz': 'quux'}

in the cases where it makes sense and it's not a problem.

**Comment by tomchristie** [comment]
One reason don't do this because it'd be difficult to distinguish between valid responses, and accidental code errors. Secondly we're staying consistent with Django here. If this was flask-rest-framework, then sure.

**Comment by alexpdp7** [comment]
That's reasonable, thanks for the feedback!
