### ISSUE TITLE
RelatedField's choices fails when queryset is a manager

### ISSUE THREAD

**Issue by aericson** [tomchristie/django-rest-framework#3145]
`RelatedField.choices()` raises a `TypeError("'*' object is not iterable",)` when queryset is a manager. 

When calling `choices()` from the template this was being [silenced by django](https://github.com/django/django/blob/1.8.3/django/template/base.py#L855).

Using a manager as the queryset for RelatedField happens in quite a few cases, such as in `get_relation_kwargs` which is used by ModelSerializer.

**Comment by aericson** [comment]
Updated an old related pull request to address this on #2558.

**Comment by tomchristie** [comment]
> Updated an old related pull request to address this on #2558.

These are separate issues so best to keep the pull requests separate. :smile:

**Comment by tomchristie** [comment]
Resolved by c14ad7add7de6dcde564a3cf28c68c1399a15659

**Comment by vstoykov** [comment]
I'm very glad that you fixed that.When I proposed a solution for that problem before 6 days it was rejected https://github.com/tomchristie/django-rest-framework/pull/3129.

As I see now I was right that there is a problem here.

**Comment by tomchristie** [comment]
:smile: little by little
