### ISSUE TITLE
Add more anchors to useful sections in the docs.

### ISSUE THREAD

**Issue by Ian-Foote** [tomchristie/django-rest-framework#3146]
I quite often want to link to the `perform_create`, `perform_update` and `perform_destroy` hooks in the [generic views documentation](http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview), but the closest anchor above is `#genericapiview`, which is a lot of scrolling away. The `#mixins` anchor is closer, but requires scrolling up.

**Comment by tomchristie** [comment]
Noted, tho not currently feasible given the constraints of our docs system. We may be able to look into introducing more anchors and better interlinking with future versions of mkdocs. We'll consider those changes as and when they become feasible.
