### ISSUE TITLE
Handle Django ValidationErrors in the default exception_handler

### ISSUE THREAD

**Issue by RockHoward** [tomchristie/django-rest-framework#3148]
I have rest views that do not map to models and yet perform input validation. Django has some nice input validators built right in. It would be handy to use these directly without requiring a reraise wrapper and have the default exception_handler handle them properly.

The change for this is just a few lines in the views.py file. I have that change and corresponding unit tests for both class and function based views in hand.

I understand that it is easy enough for me to define my own exception handler to support this capability and it need not be a built-in to the default exception handler, but I am submitting a pull request nonetheless in case the author agrees that this is a useful addition. This pull request has not yet been tested with Python 3 or tox.

**Comment by tomchristie** [comment]
Okay, that could certainly be considered. Unsure what the outcome would be right now but we make that judgement once there's a PR to review.

**Comment by tomchristie** [comment]
Closing as per #3149.
