### ISSUE TITLE
AllowAny permission will verify token if I has token in header?

### ISSUE THREAD

**Issue by larryhq** [tomchristie/django-rest-framework#3152]
if my api's permission is AllowAny, when I request this api ,if It has token in header,It will verify
 it?  
It's this a Bug?

**Comment by tomchristie** [comment]
No, this is expected behaviour.
The request *will* always be allowed in this case, but we still authenticate it to determine if 'request.user' should be set.

**Comment by larryhq** [comment]
case1： no token in header -> the api request is OK
case2： a error token in header -> It can't request. error_msg: Invalid token
My api permission is AllowAny,  It should be able to request in any case. Why you authenticate  it to determine "request.user"  in case2?

**Comment by tomchristie** [comment]
If you want an unauthenticated request, don't set any authentication classes on the view.

**Comment by larryhq** [comment]
I change my code, let view extend  ObtainAuthToken  "from rest_framework.authtoken.views import ObtainAuthToken".   ObtainAuthToken don't set any authentication , But when I request this api , It can't request like case2.

**Comment by tomchristie** [comment]
If you're still having issues the best thing to do is probably to take them to the discussion group - https://groups.google.com/forum/#!forum/django-rest-framework that'd be a better forum for talking through anything you're finding that the documentation doesn't already help you through enough.

We use the issue tracker for managing defects and ongoing work on the project
