### ISSUE TITLE
Error: 'BoundField' object is not iterable in Python3

### ISSUE THREAD

**Issue by vstoykov** [tomchristie/django-rest-framework#3153]
When I use Python3 an have nested model serializers I see this error:

    'BoundField' object is not iterable

I made a little investigation and found that BoundField proxy does not work for some reason.

I run in Python console (both Python2 and Python3) this example code:

     class I():
         def __iter__(self):
             for i in range(5):
                 yield i

    class BoundI():
        def __init__(self, i):
            self._i = i
        def __getattr__(self, attr):
            return getattr(self._i, attr)

    i = I()
    bi = BoundI(i)

    list(i)  # work
    list(bi)  # work only on Python2. In Py3 the error is "object is not iterable"

These example classes use the same logic as `Serialzier` and `BoundField` classes in DRF.

**Comment by vstoykov** [comment]
Hmm now I see that there is a `NestedBoundField`, but in my case for some reason is created BoundField instead of NestedBoundField.

I will continue with investigation.

**Comment by xordoquy** [comment]
A bit more context would help, in particular why do you have a `BoundField`.
You'd usually want to use the serializer's validated_data instead.

**Comment by vstoykov** [comment]
The problem is caused by this commit https://github.com/tomchristie/django-rest-framework/commit/6b08e97b6af8114d1ad82fc53a9cdf58168a278e

`BoundField.as_form_field` allways returns `BoundField` and then when this method is called on `NestedBoundField` instance then instance of `BoundField` is returned. When DRF renderds the field with it's template `https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templates/rest_framework/horizontal/fieldset.html` then in the `{% for nested_field in field %}` the exception is raised.

@tomchristie can you look at this because you implemented `as_form_field` and probably you have something in mind.

**Comment by tomchristie** [comment]
Yup sounds like a bug against master as part of resolving some other stuff. I'll have a dig.
If you're able to include the *smallest possible* set of code that could replicate this that'd be wonderful, but no worries if not.

**Comment by vstoykov** [comment]
I will try to write something tomorrow.

This affects only browsable API. If you just get JSON responses via AJAX, everything is working normally.

**Comment by tomchristie** [comment]
Now resolved. Thanks for the report!

**Comment by vstoykov** [comment]
I think that it is not. Now it raises `'str' object has no attribute 'get'`. I will check first if this is related to my code but I think that this is not the reason .

**Comment by tomchristie** [comment]
Noted.

**Comment by tomchristie** [comment]
Okay, looks sane to me. Worth  verifying @vstoykov?

**Comment by vstoykov** [comment]
It's ok now. I've created a test that will fail if executed before last change. After the last change is Ok. You can look at it and if you are ok with it I can make a pull request.

https://github.com/vstoykov/django-rest-framework/commit/20e0e6843912c0a29581afb8e275652a14731653

**Comment by tomchristie** [comment]
@vstoykov That would probably be a good plan - thanks!
