### ISSUE TITLE
Serializer Method Field allow_null Issue

### ISSUE THREAD

**Issue by PatrickEGorman** [tomchristie/django-rest-framework#3154]
I'm trying to get a serializer method field to not show up when the value None is passed to it.  However, even when I specifically set allow_null to False, it still shows the value "null".  Any recommendations on a fix to this solution?

**Comment by xordoquy** [comment]
@PatrickEGorman `allow_null` is to make `null` an acceptable value.
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by PatrickEGorman** [comment]
Okay. Thanks!
