### ISSUE TITLE
AuthTokenSerializer - Invalid credentials exception

### ISSUE THREAD

**Issue by gabriel-sevecek** [tomchristie/django-rest-framework#3174]
Shouldn't AuthTokenSerializer raise AuthenticationFailed instead of ValidationError when user provides invalid credentials but otherwise valid request?

**Comment by tomchristie** [comment]
Not really - the `ObtainAuthToken` view isn't authenticated itself. Invalid requests to it should be treated simply as incorrect, rather than unauthenticated.
