### ISSUE TITLE
Serializer with 'many=True' doesn't work with populated properties on models

### ISSUE THREAD

**Issue by Zetch** [tomchristie/django-rest-framework#3182]
I have a Django model with custom properties which are populated on a queryset before it's passed to a serializer with 'many=True' option. It would be something like this.
```python
class Sample(models.Model):
    name = models.CharField()

    def __init__(self, *args, **kwargs):
        super(Sample, self).__init__(*args, **kwargs)
        self._value = None

    @property
    def value(self):
        return self._value
    
    @value.setter
    def value(self, new_value):
        self._value


class SampleSerializer(serializers.ModelSerializer)
    value = serializers.FloatField()

    class Meta:
        model = Sample
        fields = ('name', 'value')
```
If I try to use a queryset with this serializer
```python
samples = Sample.objects.all()
for s in samples:
    s.value = random()

serialized = SampleSerializer(samples, many=True)
serialized.instance[0].value  # 0.123456, instances are populated
```
it outputs something like this
```json
[{"name": "Sample1", "value": null }, {"name": "Sample2", "value": null }]
```
but if I try to do the same thing with a single model
```python
sample = Sample.objects.get(pk=1)
sample.value = random()
serialized = SampleSerializer(sample)
```
it works
```json
{"name": "Sample1", "value": 0.123456}
```
I've also tried using base ```serializers.Serializer``` and the result is the same, model instances are populated but serializers output their initial values.

**Comment by tomchristie** [comment]
Setting values on items in a queryset isn't a brittle thing to do in Django, as various things may cause the queryset to be reevaluted. If you want to do something like this I'd suggest populating a list with the results of the queryset instead.
Eg...

    samples = list(Sample.objects.all())
    for s in samples:
        s.value = random()

I assume you won't have a problem after that - although let me know if otherwise and we can consider re-opening.

**Comment by Zetch** [comment]
It works! Thanks a lot! ;)

**Comment by Veeresh-R-G** [comment]
> **Setting values on items in a queryset isn't a brittle thing to do in Django,** as various things may cause the queryset to be reevaluted.

Could someone explain this a little more elaborately
