### ISSUE TITLE
use multiple serializer to serialize a list of a model?

### ISSUE THREAD

**Issue by pcompassion** [tomchristie/django-rest-framework#3183]
A user can leave a comment to a post.

comment can be visible or invisible.

I'd like to use different serializer to show visible comments and invisible comments.

Sure I can use SerializerMethodField in one serializer class to check whether a comment is visible or invisible, but wonder if it could be done.

**Comment by tomchristie** [comment]
Hiya!
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place for usage questions.
The issue tracker is solely for maanging ongoing work, bugs and features on the project.
