### ISSUE TITLE
No forms in browseable API in Mozilla

### ISSUE THREAD

**Issue by abirafdirp** [tomchristie/django-rest-framework#3186]
I tried to reduce my app to prevent overriding, tested on two PCs (Linux, Windows) 
![image](https://cloud.githubusercontent.com/assets/8951462/8887308/899e5004-32a6-11e5-933f-00f28a0b4595.png)
![image](https://cloud.githubusercontent.com/assets/8951462/8887310/8fd67a82-32a6-11e5-80ac-3c8cd17dbb5e.png)
![image](https://cloud.githubusercontent.com/assets/8951462/8887312/9798b9d8-32a6-11e5-9f6e-aa9e50587781.png)

**Comment by xordoquy** [comment]
Please use the mailing list for usage question.
You probably have an update policy for logged in users only or admin.

**Comment by tomchristie** [comment]
You're logged in to one of those but not the other. Log in and you'll see the forms.

**Comment by abirafdirp** [comment]
Oh I'm so stupid, I will use mailing first next time, so sorry

**Comment by tomchristie** [comment]
No worries :)
