### ISSUE TITLE
Cannot use "source" in "extra_kwargs" for ModelSerializer

### ISSUE THREAD

**Issue by RomuloOliveira** [tomchristie/django-rest-framework#3193]
When a model field is specified only in `Meta` class, adding `source` to `extra_kwargs` does not work as expected. Example:

```python
from django.db import models
from rest_framework import serializers

class TestModel(models.Model):
    name = models.CharField(max_length=32)

class TestModelSerializer(serializers.ModelSerializer):
    class Meta(object):
        model = TestModel
        fields = ('another_name',)
        extra_kwargs = {
            'another_name': {'source': 'name'}
        }

```

This code raises ```ImproperlyConfigured: Field name `another_name` is not valid for model `TestModel`.```.

**Comment by tomchristie** [comment]
Try the other way around...

        fields = ('name',)
        extra_kwargs = {
            'name': {'source': 'another_name'}
        }

Think that'll do it.

Also, note that it's probably simpler just to declare the field on the class instead.

**Comment by RomuloOliveira** [comment]
This didn't work too, the serializer keeps expecting `name`. `source` in `extra_kwargs` just does not works as expected (just like it works in field definition). My code is similar to the following code:

```python
class TestModel(models.Model):
    name = models.CharField(max_length=32)
    parent = models.OneToOneField('self')

class TestModelSerializer(serializers.ModelSerializer):
    class Meta(object):
        model = TestModel
        fields = ('name', 'parent_id',)
        extra_kwargs = {'parent_id': {'source': 'parent'}}
        depth = 0
```

I wanted to be able to return a response containing `parent_id` without having to redefine the field in class, but I will give it a try.

**Comment by jcushman** [comment]
Note for posterity: this appears to have ultimately been fixed in https://github.com/tomchristie/django-rest-framework/pull/4688
