### ISSUE TITLE
ChoiceField validation error has XSS vulnerability

### ISSUE THREAD

**Issue by adam-incuna** [tomchristie/django-rest-framework#3194]
The error message given by a serializer `ChoiceField` when a choice is invalid isn't HTML-safe:

https://github.com/tomchristie/django-rest-framework/blob/0ccb148183ac56eccbd2ac488402f3f075019bbd/rest_framework/fields.py#L1133

A request submitting an invalid value to a `ChoiceField` will see that value reproduced verbatim in the error message.  This means that if the invalid value contains `<script>` tags, an attacker could inject and potentially execute code on the page.

Given the simple nature of this bug, there may be other instances of this vulnerability in DRF.  I'll submit a pull request for this one shortly, but there might be more - worth keeping an eye out I think.

**Comment by tomchristie** [comment]
Thanks for the report Adam!

Closed for lesser visibility.

Not to worry, but worth seeing the note on our security policy here: http://www.django-rest-framework.org/#security

Reporting potential security issues privately first give me a bit more headroom for fixing issues.

---

**Security**

If you believe you’ve found something in Django REST framework which has security implications, please do not raise the issue in a public forum.

Send a description of the issue via email to rest-framework-security@googlegroups.com. The project maintainers will then work with you to resolve any issues where required, prior to any public disclosure.

**Comment by tomchristie** [comment]
Hi @adam-incuna - It currently looks to me like we are properly escaping these at the template level - see below...

![image](https://cloud.githubusercontent.com/assets/647359/8983252/8be86ca0-36c0-11e5-807c-8ecce18e91ca.png)

If you think I'm missing something here please to feel free to follow up on the security list, but otherwise this *currently* look like a false alarm to me. :smile:

**Comment by tomchristie** [comment]
Either way around it's a good reminded - have been bitten by unescaped values in the templates before, so do need to be v careful around it.
