### ISSUE TITLE
Fields with editable=False are still editable

### ISSUE THREAD

**Issue by rodrigopitanga** [tomchristie/django-rest-framework#3195]
Looks like `editable=False` is not always honored.

`DateTimeField` and `CharField` (with choices!) don't honor `editable=False` in the model field or `read_only_fields`.

`read_only = True` in the serializer field is not what I want, as I indeed want to write to the field when the object is created, but not after that.

**Comment by xordoquy** [comment]
Can you provide us a minimal test case for your use case ?
It seems to me that read-only is what you want. It applies to the serialization process

**Comment by tomchristie** [comment]
I'm not able to replicate this...

    class ExampleModel(models.Model):
        choices_field = models.CharField(max_length=100, choices=MY_CHOICES, editable=False)

    class ExampleSerializer(serializer.ModelSerializer):
        class Meta:
            model = ExampleModel

    >>> print repr(ExampleSerializer())
    ExampleSerializer():
        id = IntegerField(label='ID', read_only=True)
        choices_field = CharField(read_only=True)

> read_only = True in the serializer field is not what I want, as I indeed want to write to the field when the object is created, but not after that.

That's a usage question rather than an issue: The right way to handle this is typically to define two differing serializer classes, and switch between them either by overriding `get_serializer_class`, or by setting them explicitly on different views.
