### ISSUE TITLE
M2M models field with `blank=True` should map to a serializer field with `required=False`

### ISSUE THREAD

**Issue by normanjaeckel** [tomchristie/django-rest-framework#3210]
See #2804 and #2674.

An M2M model field with `blank=True` leads to a generic serializer field with `required=True`. This means DRF does not consider it valid to omit the field in the dataset but sending an empty array/list is valid since #2804 was fixed. It should be `required=False` to adapt the Django behavior.

**Comment by tomchristie** [comment]
On further review I think this is valid, yup. Matches the behavior we have on non-relational model fields...

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/field_mapping.py#L100-L101
