### ISSUE TITLE
DictField exception when converting to internal value: TypeError: parse_html_dict() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by Bahus** [tomchristie/django-rest-framework#3212]
Hi!

Currenlty if one have Serializer with DictField and request.data is provided as field value then exception is raised:

```
TypeError: parse_html_dict() takes exactly 2 arguments (1 given)
```

The issues can be clearly identified by this [peace of code](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1357):
```python
if html.is_html_input(data):
    data = html.parse_html_dict(data)
```

However `parse_html_dict` [requires 2 parameters](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/html.py#L65):
```python
def parse_html_dict(dictionary, prefix):
```

Kind regards.

**Comment by tomchristie** [comment]
Is this against master or a pypi version?

**Comment by Bahus** [comment]
@tomchristie current pypi version (3.1.3) is also affected.

**Comment by tomchristie** [comment]
Now resolved in master. Thanks!
