### ISSUE TITLE
Viewset Docstring Shows in Browsable API Even when Method Return 403

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3216]
The docstring for a viewset shows in the HTML browsable API even when the `GET` method returns 403.

**Comment by tomchristie** [comment]
Masking that on 401, 403 sounds sensible, yeah.

**Comment by tomchristie** [comment]
Okay, now resolved.

I considered adding something similar for the view name, but it wasn't immediately clear to me if that'd be sufficient (eg presumbly we'd still have the breadcrumbs) or neccessarily desirable, but I'd accept an issue on that too, if it came attached with before and after screenshots of the behavior as we'd like to see from it.

**Comment by Kos** [comment]
Blast, this was intentional? I almost reported a bug. I kind of depended on the docstrings as publicly available API documentation. Will need to figure something else out.
