### ISSUE TITLE
Define field list for nested representations done via depth=1

### ISSUE THREAD

**Issue by s2krish** [tomchristie/django-rest-framework#3218]
For example I have User and Profile model with one-to-one relation. I have defined ProfileSerializers like:

     class ProfileSerializers(serializers.ModelSerializers)
          
          class Meta:
               model = Profile
               depth = 1

This will get user information. Now, I want to exclude password field. I know there's way when I define UserSerializers. I was wondering if there's way do so without defining UserSerializer (or while using depth).

Thanks

**Comment by tomchristie** [comment]
> I was wondering if there's way do so without defining UserSerializer

Nope. Define `UserSerializer` and use `fields` on it. Then include that in the parent serializer.
