### ISSUE TITLE
Empty list validation is missed for ManyRelatedField in DRF 3.1.3

### ISSUE THREAD

**Issue by esizikov** [tomchristie/django-rest-framework#3224]
In case if we need to require at least one value to be provided for a related field with 'many=True', it does not work as expected. Discovered in DRF 3.1.3.

A possible fix would be to override ManyRelatedField.validate_empty_values() like this:

```python
# rest_framework/relations.py:
class ManyRelatedField(Field):
    ...
    def validate_empty_values(self, data):
        # data is a list for ManyRelatedField, which is not supported by
        # Field.validate_empty_values()
        if not len(data) and self.required:
            self.fail('required')
        return super(ManyRelatedField, self).validate_empty_values(data)
```

**Comment by tomchristie** [comment]
`allow_empty=False` has been added to master and will be out in the upcoming 3.2.0 release.
