### ISSUE TITLE
Admin renderer displays `True` and `False` in place of integers 1 and 0

### ISSUE THREAD

**Issue by jsatt** [tomchristie/django-rest-framework#3227]
When viewing an endpoint using the Admin renderer, cases where the integer 1 or 0 should be displayed, such as object ids and foreign keys, instead display the corresponding `True` or `False` value..
![drf-admin-truefalse](https://cloud.githubusercontent.com/assets/498431/9113843/4f6fc230-3c1c-11e5-920f-d88689b3eb05.png)

**Comment by jpadilla** [comment]
That seems to be because of [this](https://github.com/tomchristie/django-rest-framework/blob/1f55bc747bd33188ca25a166360e8d827e1f929b/rest_framework/templatetags/rest_framework.py#L114) in the `format_value` template filter.

```
>>> 1 in (True, False, None)
True
```

**Comment by jsatt** [comment]
Looks like that should be changed to something like
```python
if isinstance(value, bool) or value is None:
```

**Comment by jsatt** [comment]
Or slightly more to the point:
```python
from types import NoneType
...
if isinstance(value, (bool, NoneType)):
```

**Comment by tomchristie** [comment]
Thanks folks.
