### ISSUE TITLE
Confirm delete modal for browser api and admin

### ISSUE THREAD

**Issue by mcastle** [tomchristie/django-rest-framework#3228]
Should probably have a confirm modal after user presses `Delete` button in the browser api and admin.

**Comment by auvipy** [comment]
is it on 3.2.3 already?

**Comment by tomchristie** [comment]
@auvipy This is an open issue, so no. (Unless I'm being dense)

**Comment by awwester** [comment]
working on this ticket here https://github.com/awwester/django-rest-framework/tree/ticket_3228

**Comment by mcastle** [comment]
Fixed by #3662.

**Comment by tomchristie** [comment]
:+1: Yup, thanks for closing.
