### ISSUE TITLE
ListField seems to miss single values

### ISSUE THREAD

**Issue by kezabelle** [tomchristie/django-rest-framework#3235]
The [get_value](https://github.com/tomchristie/django-rest-framework/blob/37b4d4248895e1583861af863a3906f582e4cd0c/rest_framework/fields.py#L1382) method of `ListField` seems to use `if len(val) > 1:` where I believe it ought to be `if len(val) >= 1: ` or `if len(val) > 0:`

In a Django `QueryDict`, for example, `getlist` will yield a list of 1 item even if there is *only* one item. This seems to miss all the paths currently defined.

By way of example, here's a quick sketch of what I believe is demonstrable of the issue I think we're having:
```
>>> from rest_framework.fields import ListField
>>> from django.http import QueryDict
>>> qs = QueryDict('foo=1')
[u'1']
>>> qs2 = QueryDict('foo=1&foo=2')
[u'1', u'2']
>>> field = ListField()
>>> field.field_name = 'foo'  # for the purposes of getting the prefix right
>>> field.get_value(qs2)
[u'1', u'2']
>>> field.get_value(qs)
[]
```
I'd expect the last, empty list `[]` to be `[u'1']`
This is against drf `3.2.0` and Django `1.8.x`

**Comment by tomchristie** [comment]
What's the behavior against 3.1.3?
Would you be able to create a failing test case pull request for this?

**Comment by kezabelle** [comment]
with `pip install djangorestframework==3.1.3` and the same code, both querydicts (`qs`, `qs2`) yield `[]` when thrown through `get_value`

I ought to be able to produce a PR for it, if testing at this level, rather than a instrumenting from a higher level, is acceptable.
