### ISSUE TITLE
Missing choices for RelatedField (?) in 3.2.0

### ISSUE THREAD

**Issue by SafPlusPlus** [tomchristie/django-rest-framework#3237]
It would appear that in the html api forms the choices for HyperlinkedRelatedFields went missing from version 3.1.3 to 3.2.0. Let me illustrate with 2 screenies:

Form in 3.1.3:

![screen shot 2015-08-07 at 12 30 23 pm](https://cloud.githubusercontent.com/assets/159171/9133981/4e67a30a-3d00-11e5-9807-c988b70b62d4.png)

Form in 3.2.0:

![screen shot 2015-08-07 at 12 33 30 pm](https://cloud.githubusercontent.com/assets/159171/9134028/ccf00708-3d00-11e5-94a7-a0036f5d2f87.png)

serializers.py: https://gist.github.com/SafPlusPlus/dc3b70e5270a3f708edf
views.py: https://gist.github.com/SafPlusPlus/cd25f6871f74586fb34c
models.py: https://gist.github.com/SafPlusPlus/8087fa8916b7e6a1ed26

**Comment by tomchristie** [comment]
Resolved by e63dcab8b3017969fa7db7383f6ed93c1d207e75
