### ISSUE TITLE
request.DATA doesn't raise a loud error in Django test framework

### ISSUE THREAD

**Issue by YPCrumble** [tomchristie/django-rest-framework#3245]
Using the all-caps request.DATA errors on my staging server when I post a request but not when I run tests...is this expected behavior?

**Comment by tomchristie** [comment]
I've no reason to belive this isn't some kind of user error. request.DATA will unconditionally raise an error. Perhaps the view being tested is returning a 500 response.

If you're able to detail behavior and steps to reproducing then we can reconsider this one, but I expect you need to do some more digging first.
