### ISSUE TITLE
format_suffix_patterns

### ISSUE THREAD

**Issue by nordbit** [tomchristie/django-rest-framework#3246]
After upgrade from 3.1.3 do 3.2.1 django resolver can not find my format suffixes
```
 /api/.json
```
do not work anymore, but
```
/api/?format=json
```
work correctly

And yes, i have still 
```
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'html'])
```
in my urls.py

**Comment by xordoquy** [comment]
Linked to #3026.
We should probably add a note about this in the release notes.
Might also add a backward compatibility mode.

**Comment by nordbit** [comment]
Indeed, please add to changelog
