### ISSUE TITLE
invalid default_error_message in EnumField

### ISSUE THREAD

**Issue by Tim-Erwin** [tomchristie/django-rest-framework#3247]
When I make a POST on a viewset with a model that has an EnumField and I use an invalid value for that field, I get the error message

'tuple' object has no attribute 'format'

The reasons seems to be in fields.py:

    default_error_messages = {
        'invalid': ("No matching enum type.",)
    }

It should be not be a tuple but a simple or translated string.

**Comment by tomchristie** [comment]
Agreed. Should be a translated string instead. Pull request welcome.

**Comment by jpadilla** [comment]
This seems to be an issue with [drf-enum-field](https://github.com/seebass/drf-enum-field/blob/master/drf_enum_field/fields.py).
