### ISSUE TITLE
Parsing query parameters

### ISSUE THREAD

**Issue by kentor** [tomchristie/django-rest-framework#3248]
I use the CamelCaseJSONParser (https://github.com/vbabiy/djangorestframework-camel-case) so that I can post CamelCased keys from the client but retrieve them as underscores in python. It would be nice if we can transform query parameters as well.

In other words, a request with query params `?pageSize=100` could be retrieved in python with `request.query_params['page_size']`.

I'm wondering if this is something DRF should consider handling? Is there a way to do that currently in userland?

**Comment by kevin-brown** [comment]
I know [django-filter](https://github.com/alex/django-filter) which powers the [`DjangoFilterBackend`](http://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend) allows for aliasing using the [`name` argument](https://django-filter.readthedocs.org/en/latest/ref/filters.html#name) which is equivalent to the [`source` argument](http://www.django-rest-framework.org/api-guide/fields/#source) on serializer fields.

For other things which depend on query parameters, you can should be able to rename the fields through [different settings](http://www.django-rest-framework.org/api-guide/settings/).

**Comment by kentor** [comment]
Sorry I updated my original post. Basically if we have`?pageSize=100` as the query param, we can get it in the django side with `request.query_params['page_size']`.

**Comment by tomchristie** [comment]
We wouldn't consider adding query parameter transformation no. I'd suggest writing a utility function in your code so that you can do eg:

    camelcased_params(request)

If that's what you want.
