### ISSUE TITLE
Duplicated IPAddressField validation errors with ModelSerializer 

### ISSUE THREAD

**Issue by callorico** [tomchristie/django-rest-framework#3250]
I'm seeing duplicated validation errors being returned from a ```ModelSerializer``` for a model containing a ```GenericIPAddressField``` on Django 1.8.3 and Python 2.7.9.

```{'address': [u'Enter a valid IPv4 or IPv6 address.', u'Enter a valid IPv4 or IPv6 address.']}```

It looks like both the validator from the ```GenericIPAddressField``` and the validator from the DRF ```IPAddressField``` are being called.

https://github.com/tomchristie/django-rest-framework/pull/3249

**Comment by xordoquy** [comment]
Thanks for the failing test case

**Comment by tomchristie** [comment]
Now resolved in master :)
