### ISSUE TITLE
Model._meta API warnings with Django 1.9 (RemovedInDjango110Warning)

### ISSUE THREAD

**Issue by jamesbeith** [tomchristie/django-rest-framework#3252]
Whilst running Django 1.9.dev (master) I'm getting a couple of warnings in relations to the changes in the [Model._meta API](https://docs.djangoproject.com/en/1.8/ref/models/meta/) introduced in Django 1.8.

> .../lib/python3.4/site-packages/rest_framework/utils/model_meta.py:130: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
  for relation in opts.get_all_related_objects():

> .../lib/python3.4/site-packages/rest_framework/utils/model_meta.py:141: RemovedInDjango110Warning: 'get_all_related_many_to_many_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
  for relation in opts.get_all_related_many_to_many_objects():

**Comment by tomchristie** [comment]
Noted, thanks.
We'll aim to clear this up as part of official 1.9 support when that comes out.

**Comment by tomchristie** [comment]
Now resolved in master.

**Comment by jamesbeith** [comment]
Now running Django 1.9b1 and DRF 3.3.0 I'm continuing to get a couple of warnings in relations to the changes in the [Model._meta API](https://docs.djangoproject.com/en/1.8/ref/models/meta/) introduced in Django 1.8.

> ...lib/python3.4/site-packages/rest_framework/utils/model_meta.py:137: RemovedInDjango110Warning: 'get_all_related_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
  for relation in opts.get_all_related_objects():

> .../lib/python3.4/site-packages/rest_framework/utils/model_meta.py:149: RemovedInDjango110Warning: 'get_all_related_many_to_many_objects is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
  for relation in opts.get_all_related_many_to_many_objects():

**Comment by tomchristie** [comment]
Thanks for the report.

**Comment by jsclev** [comment]
It's unclear to me whether this issue is supposed to have been resolved.  I am using Django 1.9 and DRF 3.2.4 and am getting these warnings.  Is there still a plan to fix these?  I have googled a solution to no avail.  I also cannot figure out a way to suppress them.  I care because they output from my automated build, which causes the developers to sometimes think there is an error from the build, when it's really just a warning.

**Comment by xordoquy** [comment]
They are known to be resolved in master

**Comment by jsclev** [comment]
Thanks for the info.  I just upgraded to DRF 3.3.2, ran a build, and the warnings are gone.  Thanks for you help.

**Comment by xordoquy** [comment]
Thanks for the feedback.

**Comment by tomchristie** [comment]
:+1:
