### ISSUE TITLE
perform_*_args / perform_*_kwargs instead of overriding perform_* method

### ISSUE THREAD

**Issue by thenewguy** [tomchristie/django-rest-framework#3253]
It would be much more convenient for mixin based view construction if the perform_create/perform_update/etc methods allowed subclasses to build up the args/kwargs passed to save()

Something like the following instead of https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L25:
```
class CreateModelMixin(object):
    ...
    def perform_create(self, serializer):
        args = self.perform_create_args(serializer)
        kwargs = self.perform_create_kwargs(serializer)
        serializer.save(*args, **kwargs)

    def perform_create_args(self, serializer):
        return []

    def perform_create_kwargs(self, serializer):
        return {}
    ...
```
for each of the relevant methods

**Comment by tomchristie** [comment]
Given that they're currently single line methods this wouldn't save us anything, and the extra indirection is an unnecessary complication.

**Comment by thenewguy** [comment]
@tomchristie  I think it would be generally useful so I wanted to put together a use case before the issue is closed for good.

Say you have the following two abstract model mixins (or more in actual practice to facilitate ease of testing and separation of concerns):
```
class ClientMetadataMixin(APIAbstractBaseModel):
    class Meta:
        abstract = True
    ...
    raw_user_agent = models.TextField(blank=True)
    ...

class OwnedModelMixin(APIAbstractBaseModel):
    class Meta:
        abstract = True
    ...
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    ...
```

Then say these abstract models are inherited by 10 models which are controlled by viewsets and each of the associated viewsets also have conditional logic for `perform_*` methods.

Now each viewset needs to write the following:
```
class FooModelViewSet(viewsets.ModelViewSet):
   def perform_create(self, serializer):
       # viewset specific logic
       ....
       foo_field = "bar"
       ....

       # duplicate inherited logic from simple abstract class #1
       if self.request.user.is_anonymous():
           user = None
       else:
           user = self.request.user

       # duplicate inherited logic from simple abstract class #2
       raw_user_agent = request.META.get("HTTP_USER_AGENT", "")

       # etc

       serializer.save(foo_field=foo_field,owner=user, raw_user_agent=raw_user_agent)

   def perform_update(self, serializer):
       # viewset specific logic
       ....
       foo_field = "bar"
       ....

       # duplicate inherited logic from simple abstract class #1
       if self.request.user.is_anonymous():
           user = None
       else:
           user = self.request.user

       # duplicate inherited logic from simple abstract class #2
       raw_user_agent = request.META.get("HTTP_USER_AGENT", "")

       # etc


       serializer.save(foo_field=foo_field,owner=user, raw_user_agent=raw_user_agent)
```

This makes the view prone to copy/paste or omission errors when the logic changes.  It also isn't very DRY.  The DRY part can be mitigated by helper functions but it seems more complicated than the following:

```
class FooModelViewSet(mixin1, mixin2, viewsets.ModelViewSet):
     def perform_create_kwargs(self, serializer):
          kwargs = super(FooModelViewSet, self).perform_create_kwargs(serializer)
          kwargs['foo_field'] = "bar"
          return kwargs

     def perform_update_kwargs(self, serializer):
          kwargs = super(FooModelViewSet, self).perform_update_kwargs(serializer)
          kwargs['foo_field'] = "bar"
          return kwargs

```

The perform_*_kwarg methods could be condensed into one method by passing along the operation type.

Then something like the following could be done:
```
class FooModelViewSet(mixin1, mixin2, viewsets.ModelViewSet):
     def perform_operation_kwargs(self, serializer, operation):
          kwargs = super(FooModelViewSet, self).perform_operation_kwargs(serializer, operation)
          if operation in ("create", "update"):
                kwargs['foo_field'] = "bar"
          return kwargs
```


The benefits offered by this construction seem worthy of the minimal complications that are introduced.

**Comment by tomchristie** [comment]
Not going to be convinced there I'm afraid! :smile:

There's nothing to stop you using a `perform_*_kwarg` style in your own codebase.

**Comment by thenewguy** [comment]
@tomchristie Understood
