### ISSUE TITLE
Boolean fields not displaying correctly in checkboxes.

### ISSUE THREAD

**Issue by mcastle** [tomchristie/django-rest-framework#3258]
When editing a single user with the Admin browser or API HTML Form, the `Superuser Status` and `Staff Status` are checked by default, even if the user's `is_superuser` and `is_staff` are both `False`.

Furthermore, neither the Admin browser nor the API HTML Form allow setting those attributes to `False` if they are currently set to `True`. The only way to set these attributes to `False` is through the Raw data form.

**Comment by tomchristie** [comment]
Meh. Bit of a dumb regression that - thanks for raising.
Have resolved the input display and will look into the setting values shortly.

**Comment by tomchristie** [comment]
Retitled more appropriately.
