### ISSUE TITLE
Check uploaded file size in POST request before uploading

### ISSUE THREAD

**Issue by a1Gupta** [tomchristie/django-rest-framework#3272]
How to limit file upload size in POST request ? How can i read the file size from request.data before uploading the file to the server ? I am using MultiPartParser, and FormParser

**Comment by tomchristie** [comment]
Actually I don't think the Django documentation does a good enough job of describing this.
Typically the best thing to do would be to set this limit on the server itself (eg in your nginx or apache config)

It's more comprehensively addressed in Django 1.9...

https://github.com/django/django/pull/3020/files

> How can i read the file size from request.data before uploading the file to the server ?

Access the Content-Length header. However for some streaming requests this may not be present. You could always subclass MultiPartParser to error if the returned data is too large (in addition the server configuration, if possible)
