### ISSUE TITLE
AdminRenderer does not work without pagination being enabled

### ISSUE THREAD

**Issue by parisk** [tomchristie/django-rest-framework#3275]
Attempting to load a view rendered with AdminRenderer results to server error, if no pagination class has been set up.

I assume that this should either be fixed or documented at http://www.django-rest-framework.org/api-guide/renderers/#adminrenderer.

**Comment by tomchristie** [comment]
What's the error?

**Comment by parisk** [comment]
It's a `TypeError (list indices must be integers, not unicode)`.

## Screenshot
![screenshot 2015-08-19 15 12 17](https://cloud.githubusercontent.com/assets/1188592/9355811/fac2b8a0-4684-11e5-8e3c-8d18cdb082ff.png)

**Comment by ugurunver** [comment]
Same error here. I use release 3.2.2.

It occured when i give a list to a Response object as data. 
(Actually not just list, all non-dict types cause error at this point, i think)

https://github.com/tomchristie/django-rest-framework/blob/ed65db367ad9cd9d2fbb4da2ef8093b9a93a4fd6/rest_framework/renderers.py#L740

          paginator = getattr(context['view'], 'paginator', None)
          if (paginator is not None and data is not None):
              try:
                  results = paginator.get_results(data)
              except KeyError:
                  results = data
          else:
              results = data


It handles just KeyError and it is only for dict type data. 
And paginator.get_results is:
https://github.com/tomchristie/django-rest-framework/blob/ed65db367ad9cd9d2fbb4da2ef8093b9a93a4fd6/rest_framework/pagination.py#L161

    def get_results(self, data):
        return data['results']

So, when data is a list type object, it makes like [1,2,3]['results']. 
I think one solution may be:

    def get_results(self, data):
        if isinstance(data, list):
            return data
        return data['results']

**Comment by tomchristie** [comment]
Thanks for raising this, folks!
