### ISSUE TITLE
EmailField sometimes returns different value than Django's EmailField

### ISSUE THREAD

**Issue by mcastle** [tomchristie/django-rest-framework#3276]
When passing an email address such as `firstname+lastname@domain.com` to EmailField in the admin browser, it returns `firstname+lastname@domain.com`, which is consistent with Django's forms.EmailField.

But when using the command line, EmailFied returns `firstname lastname@domain.com`.

It seems an issue with serializers.CharField which is subclassed by serializers.EmailField, as using serializers.CharField also replaces `+` with a space.

This is can be especially problematic if using email for authentication, because Django accepts email with `+` as valid yet DRF does not through the command line.

**Comment by tomchristie** [comment]
That sounds surprising. Not aware of any reason we'd strip that char in any case.  Are you able to demonstrate in a test case? The test_fields covers a bunch if example passing and failing validation so that'd be a good place to look at adding a test for this.

**Comment by kevin-brown** [comment]
If by "through the command line" you mean "by sending a request with form-encoded data", the issue _might be_ that you are not escaping the `+` (or just not urlencoding it in general).

A test case would be useful though.

**Comment by mcastle** [comment]
It was an escaping issue with the CLI. Works with requests library. Should've tested this before raising the issue. Thanks for the helpful comments.
