### ISSUE TITLE
DRF ignores select_related / prefetch_related in a nested serialization scenario

### ISSUE THREAD

**Issue by Wingie** [tomchristie/django-rest-framework#3279]
i tried everything, but am not able to avoid a N+1 query scenario...

        logger.error('before serializer')
        serializer = self.get_serializer_class(key=to_import)
        serializer = serializer(data.prefetch_related("project_country","project_stage","project_type","sector","city").only(),many=True)
        data = serializer.data
        logger.error('after serializer')

tried select related / only() also but nothing works

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
