### ISSUE TITLE
Links without spaces are not clickable in the browsable API

### ISSUE THREAD

**Issue by JockeTF** [tomchristie/django-rest-framework#3283]
The clickable links in the browsable API depend on there being a space between the colon and the quotation mark in the JSON response. The following response will yield clickable links in the browsable API:

```json
{
    "id": "1",
    "url": "http://127.0.0.1:8000/users/1/",
    "username": "JockeTF"
}
```

However, the following response will not:

```json
{
    "id":"1",
    "url":"http://127.0.0.1:8000/users/1/",
    "username":"JockeTF"
}
```

This becomes inconvenient when using a JSON library that does not include the space, such as [UltraJSON](https://github.com/esnme/ultrajson/). A custom JSON renderer can be used to to demonstrate this issue:

```python
from rest_framework.renderers import JSONRenderer

class CustomJSONRenderer(JSONRenderer):
    def render(self, data, accepted_media_type=None, renderer_context=None):
        ret = super().render(data, accepted_media_type, renderer_context)
        ret = ret.replace(b'": "', b'":"')
        return ret
```

**Comment by tomchristie** [comment]
:-/

**Comment by tomchristie** [comment]
Any thoughts on how easy/difficult it'd be to resolve? May just be that we accept it as a known limitation.
Can always vary the renderer/representation based on the accepted media type, right?

**Comment by tomchristie** [comment]
I'd consider a pull request resolving this, but otherwise just going to treat it as out-of-scope.
Would proabably suggest modifying the rendering based on the accepted renderer if you really need to get around this.

**Comment by mitar** [comment]
I fixed this with the following workaround:

```javascript
from drf_ujson import renderers

class JSONRenderer(renderers.UJSONRenderer):
    def render(self, data, accepted_media_type=None, renderer_context=None):
        if renderer_context.get('indent', None):
            return super(renderers.UJSONRenderer, self).render(data, accepted_media_type, renderer_context)
        else:
            return super(JSONRenderer, self).render(data, accepted_media_type, renderer_context)
```

(In my [fork](https://github.com/wlanslovenija/drf-ujson-renderer/tree/more-ujson-options) `UJSONRenderer` extends `JSONRenderer`, so `super` above works.)

**Comment by JockeTF** [comment]
Thanks! But, I ended up using [RapidJSON](https://github.com/kenrobbins/python-rapidjson) a few months later. I had no issues getting that to work.

```python
from rapidjson import dumps
from rest_framework.renderers import JSONRenderer


class RapidJSONRenderer(JSONRenderer):
    """
    JSON renderer which uses a native JSON library.
    """

    def render(self, data, accepted_media_type=None, renderer_context=None):
        if data is None:
            return bytes()

        renderer_context = renderer_context or {}
        indent = self.get_indent(accepted_media_type, renderer_context)

        ret = dumps(data, indent=indent, ensure_ascii=self.ensure_ascii)

        ret = ret.replace('\u2028', '\\u2028')
        ret = ret.replace('\u2029', '\\u2029')

        return bytes(ret.encode('utf-8', 'replace'))
```
