### ISSUE TITLE
'select multiple' values not selected in api browser

### ISSUE THREAD

**Issue by leeahoward** [tomchristie/django-rest-framework#3290]
I believe that the issue is in the select_multiple templates.

I changed the '==' to 'in' and that seemed to fix it. 

```
<option value="{{ select.value }}" {% if select.value == field.value %}selected{% endif %}>{{ select.display_text }}</option>
```
```
<option value="{{ select.value }}" {% if select.value in field.value %}selected{% endif %}>{{ select.display_text }}</option>
```

**Comment by tomchristie** [comment]
Good catch - thanks!

**Comment by tomchristie** [comment]
Example for future reference...

This user:

![image](https://cloud.githubusercontent.com/assets/647359/9381985/663c894e-4734-11e5-911b-813b05ac5687.png)

Should render with this form field:

![image](https://cloud.githubusercontent.com/assets/647359/9381981/57c32c24-4734-11e5-9b90-e97e21f0b9b9.png)

Currently neither option is initially marked as selected.

**Comment by jness** [comment]
When using the 'in' operator we can get false positives it seems:
https://gist.github.com/jness/2773ea77acc761bb4328

**Comment by zhenfeng-cao** [comment]
I found in the latest version that I cannot deselect if there is only one option in the list...

**Comment by auvipy** [comment]
can you send an improvement request?
