### ISSUE TITLE
Raise error when `source=` use on a child, not a field.

### ISSUE THREAD

**Issue by rubendura** [tomchristie/django-rest-framework#3292]
I am trying to serialise a related model as a list using their names. I can't use a StringRelatedField as the `__str__` representation of my model doesn't match the desired output.
My approach was to use a ListField specifying a child with a source attribute, such as child=StringField(source='name'), but the inner source is being ignored.
There is no reference in the documentation of this being an issue. It only mentions that ListFields validate lists of objects. Maybe this is not the intended use case but it is not mentioned in the docs, although seems reasonable to me.

```python
class A(models.Model):
    name = models.CharField(max_length=72)

class B(models.Model):
    name = models.CharField(max_length=72, unique=True)
    field_I_care_about_but_not_users = models.IntegerField()
    a = models.ForeignKey(A, related_name='related_bs')

    def __str__(self):
        return field_I_care_about_but_not_users

class ASerializer(serializers.ModelSerializer):
    bs = serializers.ListField(
        source='related_bs',
        child=serializers.CharField(source='name'))

    class Meta:
        model = A
        fields = ('name', 'bs')
```

When using `ASerializer` I get `field_I_care_about_but_not_users` in the list instead of `name`.

I know I can override `to_representation`, but it surprised me when it didn't work.

**Comment by tomchristie** [comment]
Specifying source in that situation doesn't have any meaning.

Normally you're using it to associate a field with a different attribute on the instance than its field name, but when used as a child in a list or other composite element its redundant.

We could consider raising an error in this use-case. I'd rather not go into it in the docs, as I think it'd likely be noise rather than actually helpful.

**Comment by tomchristie** [comment]
Have retitled with what I think would be an appropriate action for this.

**Comment by rubendura** [comment]
Thanks for clarifying this.
