### ISSUE TITLE
Documentation or Router isn't correct

### ISSUE THREAD

**Issue by avinash240** [tomchristie/django-rest-framework#3295]
In the example located here  http://www.django-rest-framework.org/api-guide/routers/#example is generating and url of  "group-names"  for the `@detail_route` decorated function group_names.  However, when done in code underscores aren't converted to dashes for `@detail_route` decorated functions. i.e.

```python
@detail_route()
def sales_history(self, request, pk):
    pass
```

generates

```
/sales_history
```

https://botbot.me/freenode/restframework/2015-08-19/?msg=47554003&page=1

**Comment by xordoquy** [comment]
I don't get where the bug is. Sales_history is the url and sales-history the view name. Which is what the doc mentions

**Comment by kevin-brown** [comment]
It's actually further down towards the end of the section where there's a mistake

![image](https://cloud.githubusercontent.com/assets/1991850/9358560/c18a88d0-465a-11e5-815a-66742f03dd52.png)

I'm all for either fixing the table, or having another example that demonstrates the `url_path` option for decorators.
