### ISSUE TITLE
Custom fields in ModelSerializer

### ISSUE THREAD

**Issue by mhipo1364** [tomchristie/django-rest-framework#3297]
Hi guys

I need some help, I've used `ModelSerializer` in `DRF`, here is the problem:

I want to generate response dynamically, I mean I decide on user's input, so I need to pass request parameter to `ModelSerializer`, then decide if my condition is established, generate fields, otherwise generate some other fields.

Something like this:

```python

class AlbumSerializer(serializers.ModelSerializer):

    class Meta:
        model = Album
        if request.SOME_CONDITION: 
            fields = ('id', 'name_fa', 'name_en', 'price')
        else: 
            fields = ('description', 'image_path_absolute', 'publisher')

```

I've googled and get that I can pass parameters using context to serializers, but in serializer I need to get parameters via `self` object :disappointed: 

How can I do this?

**Comment by mhipo1364** [comment]
I found the answer, you can follow it via [this](http://stackoverflow.com/questions/32088179/generate-custom-response-in-drf-modelserializer/32088180#32088180) link

**Comment by xordoquy** [comment]
Please note that this is an issue tracker. For usage questions we recommend using the mailing list.

**Comment by mhipo1364** [comment]
@xordoquy: Thanks for advice, would you kindly give me mailing list address?

**Comment by tomchristie** [comment]
The discussion group: https://groups.google.com/forum/#!forum/django-rest-framework
