### ISSUE TITLE
About error response formating

### ISSUE THREAD

**Issue by dzen** [tomchristie/django-rest-framework#3301]
Hello,

I had to build an unconventionnal error response from my API.
My Resource is composed of a ListItemSerializer and an ItemSerializer. I wanted customize the output of the error to get something like

[
     {"items_errors":[{item_id: {"field_name": ["related error"]}}]},
     {"global_errors":[{item_id: ["item invalid"]}]}
]

For this I had to override the run_validation method to finally override the get_validation_error_detail to format the error dict.

By the way, I'm not sure this is the right way to manipulate the errors, and to format correctly the exceptions.

How would you handle custom error formatting ?

Thank you.

**Comment by tomchristie** [comment]
Hiya. :smile:

Usage questions such as this are best taken to the discussion group: https://groups.google.com/forum/#!forum/django-rest-framework

We use the issue tracker solely for managing active bugs, issues and other ongoing work on the project. 

There's some docs on custom exception handling here: http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling which doesn't exactly meet the case you describe, but might help you get started.
