### ISSUE TITLE
Limit select dropdowns.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#3309]
Related fields with many possible values will render into select dropdowns with potentially 1000's+++ rows. This will stop the page from rendering and leave the end user at a loss. We should be more graceful here, and also consider ajax-loaded widgets.

**Comment by jefftriplett** [comment]
A default setting of 500 or 1000 would go a long way towards addressing this. On large tables, a dropdown is kind of useful over a few hundred anyways. Thanks!

**Comment by tomchristie** [comment]
Yup, that'd certainly be a good start!...

**Comment by mcastle** [comment]
Another option is to implement something similar to Django's raw_id_field:
https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields

Or django-extensions' ForeignKeyAutocompleteAdmin:
https://django-extensions.readthedocs.org/en/latest/admin_extensions.html#current-admin-extensions

**Comment by jefftriplett** [comment]
Ideally, `raw_id` would be the default to avoid this problems from the start :)

**Comment by kevin-brown** [comment]
I'm going to toss the idea of using [Select2](http://select2.github.io/) out there.

There are a few Django integrations that may be useful to build from

- https://github.com/asyncee/django-easy-select2
  - Pros
    - Uses the newer version of Select2 (4.0.0)
  - Cons
    - Not designed (out of the box) to pull results from AJAX
- https://github.com/applegrew/django-select2
  - Pros
    - Has views for populating results using AJAX
  - Cons
    - Still uses the older version of Select2 (3.5.2)

Considering we already have the API set up, and we aren't tied to Django forms, it would probably be easier to not use a third party app for integrating it.

_**Disclaimer:** I'm the active maintainer of Select2._

**Comment by tomchristie** [comment]
Righty, now resolved, including docs on using plain inputs instead, modifying the cutoff, and changing the display text.

Example:

![image](https://cloud.githubusercontent.com/assets/647359/9406607/02dafa7c-47fa-11e5-9a4e-32e6b32c2c43.png)


Happy to see us also have an 'enhancement' ticket for AJAX driven selects if anyone fancies opening that.

**Comment by jefftriplett** [comment]
:+1: x 1000 -- this is *really* great and extremely useful. Thank you so much!

**Comment by tomchristie** [comment]
Yeah, all the more so for the many hours of head-scratching it's going to save folks.
Thanks for raising the concern!

**Comment by mlissner** [comment]
[Here's the documentation mentioned above].

[1]: http://www.django-rest-framework.org/api-guide/relations/#select-field-cutoffs
