### ISSUE TITLE
Docs reference page

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#3311]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/_tomchristie">@_tomchristie</a> maybe - certainly a quick glossary of key terms + a little detail on each might help too</p>&mdash; Steve Jalim (@stevejalim) <a href="https://twitter.com/stevejalim/status/634362634784088069">August 20, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by pt247** [comment]
Hi Tom,

I am working out a bit of code that automatically generates index page (key term + link + Short description) by looking at existing documentation. So I can generate a page for index in markup. Its sorted and indexed as you would expect any index page and multiple entries for keyword clubbed etc. We will need a test script as well for it. If you are interested PFA output. 
[output.txt](https://github.com/tomchristie/django-rest-framework/files/47022/output.txt)

Is this something you would like to use? 
If yes then, What will be the right place to keep such an index page in website?

**Comment by tomchristie** [comment]
On reflection I think we should pass on this. Appendices type pages never seem terribly well suited to web documents. If anything we should simply work on improving the documentation and ensuring we have good search.
