### ISSUE TITLE
Writable nested serializer with existing objects using Django Rest Framework 3.2.2

### ISSUE THREAD

**Issue by arw180** [tomchristie/django-rest-framework#3312]
I made a SO post about this here: http://stackoverflow.com/questions/32123148/writable-nested-serializer-with-existing-objects-using-django-rest-framework-3-2

Even if it turns out nothing is broken, I think a documentation update would be helpful for this case (a nested write that also uses existing objects). In addition, it seems like the `source` attribute isn't respected by the `SlugRelatedField` serializer, at least on writes.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
Meanwhile, you should have a look at validator and how to remove them to allow the serializer to validate correctly.
Please note that there are so many possible use cases we can't provide examples for all of them.
