### ISSUE TITLE
Multi-level dictionaries not supported in multipart requests

### ISSUE THREAD

**Issue by nazarewk** [tomchristie/django-rest-framework#3314]
`rest_framework.utils.html.is_html_input()` combined with `rest_framework.utils.html.parse_html_dict()` does not detect 3+ level dictionaries, for example.

1. Multipart representation of `{'a':{'b':{'c':123}}}` is `QueryDict([('a.b.c',123)])`, so `is_html_input()` properly detects nested dictionary.
2. On the second pass there is `{'b.c':123}` and `is_html_input()` does not detect the nested dictionary.

My suggestion is to either instantiate or return `MultiValueDict` instead of simple `dict` in `parse_html_dict()` (and possibly `parse_html_list()`)
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/html.py

**Comment by tomchristie** [comment]
Looks like a valid issue on first pass.

**Comment by tomchristie** [comment]
Out of interest what's the use case here, are these HTML forms that you're including on a web site, or is this a client that just happens to be using multipart?

**Comment by nazarewk** [comment]
I have the file upload on 3rd level so i have to use multipart.
