### ISSUE TITLE
Non-obvious Behavior for Nested Writeable Updates

### ISSUE THREAD

**Issue by jpulec** [tomchristie/django-rest-framework#3317]
I have a model structure that looks like the following:

```python
class MenuItem(models.Model):
    ...

class MenuOptionGroup(models.Model):
    menu_item = models.ForeignKey(MenuItem, related_name='menu_options')
    ....
```

And serializers that look like: 

```python
class MenuOptionGroupSerializer(serializers.ModelSerializer):
    class Meta:
        fields = ['menu_item', ...]

class MenuItemSerializer(serializers.ModelSerializer):
    menu_option_groups = MenuOptionGroupSerializer(many=True)

    def create(self, validated_data):
        menu_option_groups_data = validated_data.pop('menu_option_groups', [])
        menu_item = models.MenuItem.objects.create(**validated_data)
        for menu_option_group in menu_option_groups_data:
            menu_option_group['menu_item'] = menu_item
        self.fields['menu_option_groups'].create(menu_option_groups_data)
        return menu_item

    def update(self, instance, validated_data):
        menu_option_groups_data = validated_data.pop('menu_option_groups',
            instance.menu_option_groups.all().values())
        ...
        instance.save()

        for menu_option_group in menu_option_groups_data:
            menu_option_group['menu_item'] = instance
        self.fields['menu_option_groups'].update(instance.menu_option_groups.all(),
            filter(lambda group: 'id' in group, menu_option_groups_data))
        self.fields['menu_option_groups'].create(
            filter(lambda group: 'id' not in group, menu_option_groups_data))
        return instance
```

For awhile I assumed this worked correctly, where I could create or update a ```MenuItem``` with a nested ```MenuOptionGroup``` at the same time when the nested ```MenuOptionGroup``` did not have a ```MenuItem``` id passed, since it hadn't been created yet:

```
{
    <menu_item_data>
    "menu_option_groups": [
        {
            <menu_option_group_data>
        }
    ]
}
```

I recently discovered that creation was failing, because validation runs before the ```create()``` method of ```MenuItem``` and the nested ```MenuOptionGroup``` did not have a ```menu_item``` defined.  However, my updates have been working happily due to:

```python
if getattr(self.root, 'partial', False):
    raise SkipField()
```

https://github.com/tomchristie/django-rest-framework/blob/490f0c9f3426142aa5b7af50f8f9f01dc1d3fd08/rest_framework/fields.py#L436

This behavior was very non-obvious, and I don't think (?) is documented anywhere.

Potentially related to #2585

**Comment by cancan101** [comment]
:+1: On fixing this.

I am running into a similar issue with:
```python
class PersonSerializer(serializers.ModelSerializer):
    tags = TagSerializer(many=True)

class TagSerializer(serializers.Serializer):
    id = serializers.UUIDField(read_only=False, required=True)
```

where if I do a partial update on `PersonSerializer` with `data={'tags':[{}]}`, validation passes even though I don' think that it should.

**Comment by xordoquy** [comment]
@jpulec a bit more context would help to get what doesn't work. Does the creation happens while it shouldn't or the other way round ?
Also note that you shouldn't do things such as
```
self.fields['menu_option_groups'].create(menu_option_groups_data)
```

**Comment by xordoquy** [comment]
@cancan101 IMHO this may be worth investigating further. This looks like a different issue from the OP.

**Comment by cancan101** [comment]
@xordoquy I might haven been confused by the cross link to: https://github.com/tomchristie/django-rest-framework/issues/2585

**Comment by cancan101** [comment]
What is preferred to:
```
self.fields['menu_option_groups'].create(menu_option_groups_data)
```
when dealing with creating related fields?

**Comment by xordoquy** [comment]
@cancan101 I tend to have this code in the top most serializer.

**Comment by cancan101** [comment]
Ah okay. But there is nothing wrong with the code itself, you were just talking issue with where it is placed?

**Comment by jpulec** [comment]
@xordoquy Sorry for the complex example. Let me see if I can clarify a bit.

Additionally, if I'm understanding your comment to @cancan101 correctly, I believe I'm doing just that. My top-most serializer is a ```MenuItemSerializer``` that has many ```MenuOptionGroups``` nested on it. So I think putting the line:

```python
self.fields['menu_option_groups'].create(menu_option_groups_data)
```

is correct as it is in the ```create()``` function of the top-most serializer. If I'm wrong on that, please correct me.

To be clear, my nested serializer ```MenuOptionGroupSerializer``` also has a ```PrimaryForeignKeyField``` to it's parent with the name ```menu_item```, which is the source of some of my issues.

WRT what doesn't work, I believe that expected behavior is for a serializer (```MenuItemSerializer```) that has a nested serializer (```MenuOptionGroupSerializer```) where the nested serializer has a ```PrimaryForeignKeyField``` to its parent (```menu_item``` and instance of ```MenuItemSerializer```, in this case) should fail validation.

This happens currently when validating on creation of a new ```MenuItem```.

However, if one tries to update an existing ```MenuItem```, validation doesn't fail, because of https://github.com/tomchristie/django-rest-framework/blob/490f0c9f3426142aa5b7af50f8f9f01dc1d3fd08/rest_framework/fields.py#L436.

```python
if getattr(self.root, 'partial', False):
    raise SkipField()
```

Since the root serializer has 'partial' set, it ignores that the ```PrimaryForeignKeyField``` ```menu_item``` doesn't validate on the child serializer. This behavior was very surprising to me.

**Comment by tomchristie** [comment]
> Since the root serializer has 'partial' set

*If* you're using `partial=True` on the serializer, *or* if your making a `PATCH` request (which sets `partial=True`, then sure, all the fields are treated as optional.

Failing to see an issue?

**Comment by cancan101** [comment]
@tomchristie Should I open a separate ticket for the issue that I am having? Basically the issue is how to deal with PATCHing where a given field is included in the payload but one of the required subfields is missing.

**Comment by tomchristie** [comment]
> where if I do a partial update on PersonSerializer with data={'tags':[{}]}, validation passes even though I don't think that it should.

Fill me in: What *do* you think should be occurring?

**Comment by xordoquy** [comment]
@cancan101 the goal for partial is to bypass required fields. If you need those required fields, you'd rather not use partials

**Comment by cancan101** [comment]
@tomchristie:
I think that given the `tags` field is specified on the PATCH payload, anything required for a tag should be included. In this case `id` is required.

@xordoquy:
I agree that partial should bypass fields on the top level serializer but I don't think that should apply to nested serializer for fields that ARE specified at the top level.

**Comment by tomchristie** [comment]
`partial=True` is always going to just have to be a little bit on the dumb side.

> but I don't think that should apply to nested serializer for fields that ARE specified at the top level.

{shurg} Not clear to me that it'd be a more sensible default.

**Comment by xordoquy** [comment]
I'm not convinced there's a better default here. We should probably simply make it clear that partial will apply to the top most serializer as well as nested ones and provide a decent way to workaround this behavior if needed.
