### ISSUE TITLE
Serializing Error Bug

### ISSUE THREAD

**Issue by RusEu** [tomchristie/django-rest-framework#3326]
i allways get this error when i try to serialize something:

AttributeError at /webusers/

'BoundField' object has no attribute '_field'

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/webusers/
Django Version: 	1.8.2
Exception Type: 	AttributeError
Exception Value: 	

'BoundField' object has no attribute '_field'

Exception Location: 	/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py in render_field, line 315
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6

**Comment by tomchristie** [comment]
There isn't enough information here right now to treat this as an open issue - what is the traceback, what is the view, what is the simplest possible way you can reproduce the issue you're seeing?

If you can provide suitable information we may reopen the ticket.

**Comment by RusEu** [comment]
need more informations ?

**Comment by RusEu** [comment]
any help please ?

**Comment by RusEu** [comment]
the problem is for django 1.7 .. when i upgrade it to django 1.8 everything works fine .. thanks!
