### ISSUE TITLE
Serializing Error Bug

### ISSUE THREAD

**Issue by RusEu** [tomchristie/django-rest-framework#3331]
I serialized the User model on django and everything worked fine , but then i tried to serialize other models , i get an error.
Now when i try to access the the http://127.0.0.1:8000/apiusers/ ( user serialized data ) i get the same error.
Maybe the serializing method i tryed was not good, but now
it doesn`t matter what i change or what i try .. i still get the same error : 
AttributeError at /apiusers/

'BoundField' object has no attribute '_field'

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/apiusers/
Django Version: 	1.8.2
Exception Type: 	AttributeError
Exception Value: 	

'BoundField' object has no attribute '_field'

Exception Location: 	/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py in render_field, line 315
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6

Error during template rendering

In template /usr/local/lib/python2.7/dist-packages/rest_framework/templates/rest_framework/api_form.html, error at line 5
'BoundField' object has no attribute '_field'
1 	{% load rest_framework %}
2 	{% csrf_token %}
3 	{% for field in form %}
4 	{% if not field.read_only %}
5 	{% render_field field style=style %}
6 	{% endif %}
7 	{% endfor %}
8 	
9 	

User Serializer:

class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

router = routers.DefaultRouter()
router.register(r'', UserViewSet)

Other Models :

class QuoteIdea(models.Model):
	creator = models.ForeignKey(CofifiUser,related_name="creator")
	text = models.TextField(max_length=250)
	votes = models.CharField(max_length=100,default="0")
	votes_received = models.ManyToManyField(CofifiUser)
	created_at = models.DateTimeField(auto_now_add=True)

class CofifiUser(models.Model):
	user = models.OneToOneField(User)
	friends = models.ManyToManyField('self',related_name="user_friends",blank = True)
	bio = models.TextField(default="")
	image = models.ImageField(upload_to="static/user")
	country =  CountryField()
	gender = models.CharField(max_length=1,choices=GENDER_CHOICES)
	birth_date= models.DateField() 

Other Serializers:

class UserSerializer(serializers.ModelSerializer):

	class Meta:
		model = User
		fields = ('username','email')

class CofifiUserSerializer(serializers.ModelSerializer):
	user = serializers.CharField(source='user.username')

	class Meta:
		model = CofifiUser
		fields = ('user',)

class QuoteSerializer(serializers.ModelSerializer):
	#creator = serializers.CharField(source='creator.user.username')
	#votes_received = serializers.PrimaryKeyRelatedField(many=True,read_only = True)
	#creator = CofifiUserSerializer()
	#votes_received = CofifiUserSerializer()
	class Meta:
		model = QuoteIdea
		fields = ('text','votes')
# ViewSets define the view behavior.

class QuoteViewSet(viewsets.ModelViewSet):
    queryset = CofifiUser.objects.all()
    serializer_class = CofifiUserSerializer

quote_ideas = routers.DefaultRouter()
quote_ideas.register(r'quote_ideas', QuoteViewSet)

Any help please ?

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
