### ISSUE TITLE
No way to disable CSRF checks for testing

### ISSUE THREAD

**Issue by kennydude** [tomchristie/django-rest-framework#3332]
I'm trying to test my API using dredd, however CSRF checking is getting in the way of this being tested correctly. I was wondering if there was the possibility of an option to disable CSRF just for testing

**Comment by tomchristie** [comment]
Out of interest what authentication scheme are you using?

Using `.force_authenticate` will do the trick...

http://www.django-rest-framework.org/api-guide/testing/#forcing-authentication

**Comment by kennydude** [comment]
I'm using `SessionAuthentication` and dredd can't do that unfortunately as it is a separate thing. Currently I'm running it as a subprocess from a `LiveServerTestCase` which works fine until I try and do authenticated POST requests.

**Comment by kennydude** [comment]
I have "fixed" this by monkey-patching around it:

```python
from rest_framework import authentication


def noop(self, request):
    pass
authentication.SessionAuthentication.enforce_csrf = noop
```
