### ISSUE TITLE
Mixin fields on nested serializer ignored

### ISSUE THREAD

**Issue by pmdarrow** [tomchristie/django-rest-framework#3334]
With the following serializers:

```python
class FooMixin:
    foo = serializers.CharField()

class BarSerializer(serializers.Serializer, FooMixin):
    bar = serializers.CharField()

class BazSerializer(serializers.Serializer):
    baz = serializers.CharField()
    nested_bar = BarSerializer()
```

The `foo` field from the `FooMixin` is unexpectedly ignored:

```python
>>> from example_app.serializers import BazSerializer
>>> instance = {
...     'baz': 'Baz',
...     'nested_bar': {
...         'bar': 'Bar',
...         'foo': 'foo',
...     }
... }
>>> print(BazSerializer(instance))
BazSerializer({'baz': 'Baz', 'nested_bar': {'bar': 'Bar', 'foo': 'foo'}}):
    baz = CharField()
    nested_bar = BarSerializer():
        bar = CharField()
>>> print(BazSerializer(instance).data)
{'baz': 'Baz', 'nested_bar': OrderedDict([('bar', 'Bar')])}
```

I tried reversing the mixin inheritance order in `BarSerializer` but it didn't have any affect.

**Comment by tomchristie** [comment]
Well, firstly don't do that.

Secondly, unsure if/how we want to resolve this. We *could* try to make this kind of usage work, we *could* consider having the framework error in this circumstance, we *could* document it, or we *could* just treat it as implicitly not supported.

**Comment by xordoquy** [comment]
If I remember correctly, Django has similar issues with models and / or forms.

**Comment by tomchristie** [comment]
Almost certainly yes. I'm not sure I'd describe it as an issue tho. Mixins-as-API tends to be a massive hack, can't just add them to base classes and expect them to magically just work in all cases. But we *could* look at changing this, if we cared enough.

**Comment by pmdarrow** [comment]
@tomchristie is the preferred approach to just make `FooMixin` a `Serializer` subclass? If so, that's fine. An explicit failure would be nice, but documentation would also suffice.

**Comment by pmdarrow** [comment]
Or nothing, since it's pretty easy to figure out how to fix it :)

**Comment by tomchristie** [comment]
>  is the preferred approach to just make FooMixin a Serializer subclass?

The preferred approach is to just add the field(s) to the serializer. :)

What you lose in code duplication you gain in explicit, less indirect code.

**Comment by pmdarrow** [comment]
@tomchristie point taken :). Feel free to close this.

**Comment by tomchristie** [comment]
Grand - if it recurs we could reconsider.
Right now don't consider it enough of a priority to bother addressing.
