### ISSUE TITLE
Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute should be prohibited

### ISSUE THREAD

**Issue by ideallical** [tomchristie/django-rest-framework#3335]
Since Django 1.8 you can't use ModelForms without the **fields** or **exclude** fields attribute:
https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#selecting-the-fields-to-use

I think ModelSerializers should behave the same way because this will make DjangoRestFramework more secure for programming "mistakes", e.g. adding an admin changeable field on a model, later realizing that the field is now editable for the public because you didn't explicitly provided the fields.

This would be a backwards-incompatible update though.

Here's the commit in Django:
https://github.com/django/django/commit/ee4edb1eda2ac8f09eb298929282b44776930c89

What do you think?

**Comment by jpadilla** [comment]
How I'd love for us to keep moving towards "explicit is better" usage/implementation.

**Comment by tomchristie** [comment]
Absolutely in favor, yes, so long as we also use the '__all__' shortcut in the same way as `ModelForm`.
It's an API change, but easy to retain existing behavior - no reason not to have this in 3.3.

**Comment by ideallical** [comment]
How about raising a warning in 3.2.x versions, like Django did?

**Comment by xordoquy** [comment]
@ideallical we already have a deprecation policy we need to follow and that is similar to Django's one ;)

**Comment by ideallical** [comment]
OK great!

**Comment by jpadilla** [comment]
I can work on this.

**Comment by jpadilla** [comment]
@tomchristie just to make sure, do we want to introduce the following behavior on 3.3.

`ModelSerializer`s without explicit `fields` or `exclude` will raise an exception similar to what Django `ModelForm`s do. We'll call out on the release notes that if you previously relied on that behavior you just have to add `fields = '__all__'` to your serializer's meta class.

**Comment by tomchristie** [comment]
What did the Django team do? Treat it as security related and raise an exception, or treat it as deprecation and use a `PendingDeprecation` warning? Whichever it was, we should probably do the same.

**Comment by xordoquy** [comment]
We certainly don't want to raise an exception if there's none of `fields` or `exclude` defined for 3.3.
The [deprecation policy](http://www.django-rest-framework.org/topics/release-notes/#deprecation-policy) will make it:
- 3.3 is compatible with 3.2 and add a `PendingDeprecationWarning`
- 3.4 would escalate these warnings to DeprecationWarning, which is loud by default.
- 3.5 would remove the deprecated bits of API entirely.

**Comment by tomchristie** [comment]
Depends on the assessment - it's arguably security related.
We're essentially mirroring Django's deprecation policy so I've *probably*? no problem also following their lead on however they treated 'fields' on `ModelForms` - in either case let's wait and see - if they went for a standard deprecation then there's no argument in any case.

**Comment by jpadilla** [comment]
As far as I can see this behavior was introduced in [Django 1.6](https://github.com/django/django/blob/stable/1.6.x/django/forms/models.py#L269) and added a pending deprecation warning. [Django 1.7](https://github.com/django/django/blob/stable/1.7.x/django/forms/models.py#L271) still has a warning. [Django 1.8](https://github.com/django/django/blob/stable/1.8.x/django/forms/models.py#L271) raises `ImproperlyConfigured`.

Original [discussion](https://groups.google.com/forum/#!topic/django-developers/io74RDWgiLw/discussion) on django-developers.

**Comment by jpadilla** [comment]
Thanks all! Closed via #3345.
