### ISSUE TITLE
AttributeError: 'function' object has no attribute 'EXCEPTION_HANDLER'

### ISSUE THREAD

**Issue by liquidpele** [tomchristie/django-rest-framework#3337]
```python
Internal Server Error: /rest/v1/updates/status
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/djangorestframework-3.1.3-py2.6.egg/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/djangorestframework-3.1.3-py2.6.egg/rest_framework/views.py", line 456, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.6/site-packages/djangorestframework-3.1.3-py2.6.egg/rest_framework/views.py", line 410, in handle_exception
    exception_handler = self.settings.EXCEPTION_HANDLER
AttributeError: 'function' object has no attribute 'EXCEPTION_HANDLER'
```

This is the logged exception we get...   docs say EXCEPTION_HANDLER should have a default value, so it looks like something is amiss?  

My main issue is that this hides the first exception...

**Comment by xordoquy** [comment]
Looks like you have overridden `settings` in your view likely with a function.
You should consider this name as reserved for the views.

**Comment by liquidpele** [comment]
ooooooh... so if I wanted to have an api url that was like "/updates/settings" then how would I do that?   Right now I'm using a viewset with @list_route on a function named 'settings' within that... looking through the docs/code but I don't see a way to specify that.

**Comment by tomchristie** [comment]
You're gonna want to use a regular view instead for that.

**Comment by liquidpele** [comment]
That would take a lot of work due to custom mixins etc.   I'll make the name different, but that's a pretty annoying limitation and easily breakable.   

Regardless, thanks for the help, that had me stuck for several hours!  :)

**Comment by liquidpele** [comment]
For anyone else that finds this, you can change the url path name like this (from the docs):

    @detail_route(methods=['post'], permission_classes=[IsAdminOrIsSelf], url_path='change-password')

cheers
