### ISSUE TITLE
AdminRenderer Datetime field has "today" button but no "now" button

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3339]
The datetime field widget used by the `AdminRenderer` has a button to auto fill today's date but no similar way to auto fill "now. I believe that the django admin offers both of these auto-fills.
![image](https://cloud.githubusercontent.com/assets/51059/9523948/61f719aa-4caa-11e5-9cb1-96ded871bbc5.png)

**Comment by tomchristie** [comment]
These are just the default HTML5 controls that the browser provides.

Its *probably* nicest for us to just stick with those as the simple base case, but we *could possibly consider* using our own widget as an enhancement.

I'd need a bit more convining first, including a visual demonstrate of what the Django admin does or doesn't do.

**Comment by cancan101** [comment]
This is what the django admin offers:
![image](https://cloud.githubusercontent.com/assets/51059/9524147/50e3be42-4cab-11e5-84f4-5173e068e919.png)

**Comment by tomchristie** [comment]
Blergh. I'd rather stick with the HTML5 native controls. Right way around for us to address this: Do a better job of supporting alternate template packs. I've added that to #2060

**Comment by cancan101** [comment]
Related, looks like DRF is using an input with `type="datetime-local"` which per [the docs](http://www.w3.org/TR/html-markup/input.datetime-local.html): has "no timezone information".

Would using / having the option to use [`type="datetime"`](http://www.w3.org/TR/html-markup/input.datetime.html), "with timezone information", be better?

**Comment by tomchristie** [comment]
The `datetime` control is not widely supported:

![image](https://cloud.githubusercontent.com/assets/647359/9524896/4b6c85ba-4cd9-11e5-979b-b123d2bd0da5.png)
