### ISSUE TITLE
24-hour time support in datetime widgets

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3341]
The datetime widgets use 12 hour time rather than 24-hour time. Ideally there would be an option to use 24-hour time:
![image](https://cloud.githubusercontent.com/assets/51059/9524026/a95d0796-4caa-11e5-856c-46e40291b377.png)

This applies to both the new `AdminRenderer` and the old `BrowsableAPIRenderer`.

**Comment by tomchristie** [comment]
Again, this is a native HTML5 control. In Chrome the AM/PM vs 24hour display depends on your system settings, attempting to mirror the users' locale.

I'd be in favour of us doing a better job of supporting alternate template packs, but I think this is a reasonable base case.
