### ISSUE TITLE
DRF 2.4.6 "Incorrect type.  Expected pk value, received unicode." ERROR

### ISSUE THREAD

**Issue by izzybelll** [tomchristie/django-rest-framework#3344]
So for my django project (I'm using Django 1.8, and Python 2.7, I'm using DRF 2.4.6 because an extension I need - drf-extensions for nested routing - doesn't work on 3.1>), When I want to "PUT" it returns the message: 

"Incorrect type.  Expected pk value, received unicode."

This is how my models are set up:

```
models.py:

class Post(models.Model):
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Comment(models.Model):

    parent_post = models.ForeignKey(Post, to_field='slug')
    text = models.CharField(max_length=30, default="")
```

views.py

```
from rest_framework_extensions.mixins import NestedViewSetMixin

class PostViewSet(NestedViewSetMixin, ModelViewSet):
    model =  Post
    lookup_field = 'slug'

class CommentViewSet(NestedViewSetMixin, ModelViewSet):
    model = Comment
    lookup_field = 'id'
```

When I try to put to the url localhost/api-root/post/this-post-title/comment/1/ for the "parent_post" field it returns: "Incorrect type.  Expected pk value, received unicode." and right now I'm not sure what else to do... Thank so much!!!

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
