### ISSUE TITLE
Unit tests using APIClient `request.DATA` do not use a QueryDict.

### ISSUE THREAD

**Issue by ses4j** [tomchristie/django-rest-framework#3347]
I'm on Django 1.7 and DRF 2.4.x, don't know if that matters.

If I POST to an `APIView`, then inside the view the `request.DATA` is a `QueryDict` (and immutable), correctly.  However, if I write a unit test and do `APIClient().post(url, {})`, the same `request.DATA` returns a regular dict.  In the unit test case, it should normalize it as a `QueryDict`, so unit tests can catch bugs where the developer tries to mutate it.

**Comment by tomchristie** [comment]
> I'm on Django 1.7 and DRF 2.4.x

Sorry to not be more help, but we're only considering issues against the 3.x line at this point (security issues only on 2.x)

I'd reconsider this ticket if you wanted to raise something against 3.x.

**Comment by ses4j** [comment]
Someday.  The upgrade is going to be very painful, unfortunately.  I don't know if it happens on 3.x, but unless someone addressed it specifically, it probably does...

**Comment by pySilver** [comment]
@ses4j this ticket is closed but there is nothing wrong in drf 2.x your problem with QueryDict have different roots. It's actually depends on used parser. If it's formdata – expect to have an immutable QueryDict, otherwise (jsonparser, yamlparser etc) expect a mutable dict here.

**Comment by nryoung** [comment]
yes, this can be surprising. The solution is to explicitly define the content in the request header and you will always get the same object back.

**Comment by carltongibson** [comment]
Just a data point: I just saw this against 3.4 in a production system. Unit test passed. 500 in production.

**Comment by tomchristie** [comment]
Happy to consider an issue for it, if it's replicable. (Doesn't necessarily need to be replicable in a test case so long as someone can give an example of how to demonstrate the issue in a project setup)
