### ISSUE TITLE
base_name must be lower case, allow for any case.

### ISSUE THREAD

**Issue by mcrowson** [tomchristie/django-rest-framework#3349]
When overriding the get_queryset() method, I must specify a base_name.

This is occurring for our users endpoint which uses a custom user module. I can set the base_name argument and it works just fine. My custom user model's name is MyUser
[this works]
`router.register(r'users', views.UserViewSet, base_name='myuser')`

When using the get_user_model() method as suggested in the django docs on how to refer to the custom user though it gives me grief. 
[this does not work]
`router.register(r'users', views.UserViewSet, base_name=get_user_model().__name__)`

Forcing the text to be all lower case makes it work again.

[this works]
`router.register(r'users', views.UserViewSet, base_name=get_user_model().__name__.lower())`

So if lower case is mandated for the base_name, I recommend converting all base_name arguments to lower() in the BaseRouter.register() method.

**Comment by xordoquy** [comment]
I don't think lowercase is required. However, if you don't use lowercase, your reverses should reflect the correct case.
Note that you can skip the base_name as long as `get_queryset` returns a `QuerySet`
