### ISSUE TITLE
Different data on internationalization

### ISSUE THREAD

**Issue by jab3z** [tomchristie/django-rest-framework#3353]
Hi,

The endpoint called in the default language (English) works fine, but in arabic I get None.

Here's the code

serializers.py

    def validate(self, validated_data):
        support_request = validated_data.get('support_request')
        amount = validated_data.get('amount')

        if support_request.raised_in_full():
            raise serializers.ValidationError(_('Targeted amount already received'))

        if amount > support_request.remaining_amount:
            raise serializers.ValidationError(
                _('You cannot support with more than {} KWD'.format(support_request.remaining_amount)))
        return validated_data

models.py

    class SupportRequest(TimeStampedModel):
        @property
        def amount(self):
            try:
                value = self.form_values.filter(field__label=self.amount_field.label).first().value
                value = Decimal(value).quantize(THREEDIGITS)
            except:
                value = None
            return value

        @property
        def remaining_amount(self):
            if all([self.raised, self.amount]):
                return self.amount - self.raised
            return self.amount

        def raised_in_full(self):
            if self.amount == self.raised:
                return True
            return False

The endpoint works perfectly on english, but on arabic it fails.
I've logged all variables and for english all of them has values, in Arabic doesn't.

It's tested with Postman and rest framework form interface.

validated_data looks the same on both languages.
amount is ok
support_request.amount None
support_request.raised is ok
support_request.remaining_amount is None

I don't understand how internationalization can cause this.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
