### ISSUE TITLE
Captcha in Django Rest Framework

### ISSUE THREAD

**Issue by bahmany** [tomchristie/django-rest-framework#3355]
What is the best way to handle captcha fields in django rest serializations ?

UPDATE: the senario is : when my user what to register as a new user in my app, i want to ask him to enter the captcha field. imagin somthing like this :

class UserSerializer(serializers.ModelSerializer):

    # i want something for here,there is no chaptcha feild in drf# 
    captcha = CaptchaField(required=True, label="I am not robot", )

    username = serializers.CharField(...)
    email = serializers.EmailField(...)
    password = serializers.CharField(...)
    confirm_password = serializers.CharField(...)

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
