### ISSUE TITLE
Replace self.tag with self.tag_name in Generic Relationships documentation

### ISSUE THREAD

**Issue by brittdawn** [tomchristie/django-rest-framework#3357]
In the [Generic Relationships](http://www.django-rest-framework.org/api-guide/relations/#generic-relationships) section of the documentation, ``self.tag`` might need to be replaced with ``self.tag_name``. See below:

![django_rest_generic_relationships](https://cloud.githubusercontent.com/assets/3136908/9634149/3caa7134-5145-11e5-956a-7216a2008f93.jpg)

With ``self.tag``, an AttributeError would be raised. See below:

![tagged_item_object_no_tag_attribute](https://cloud.githubusercontent.com/assets/3136908/9634556/1ed4b65e-5147-11e5-9948-36b9d3e5af37.jpg)

``self.tag_name`` returns the expected admin

**Comment by tomchristie** [comment]
Yup, looks right - would accept a PR for that.
Thanks for raising!

**Comment by brittdawn** [comment]
Great! Working on it now!
