### ISSUE TITLE
[BUG] rest_framework.filters.SearchFilter.filter_queryset fails with NoneType not iterable

### ISSUE THREAD

**Issue by erj1** [tomchristie/django-rest-framework#3366]
I updated my code base to use version 3.2.3 now my previously passing tests are now failing.

It seems to be related to [Line: 105 in filters.py](https://github.com/tomchristie/django-rest-framework/blob/b4b2dc18fa4cb6bbe008d4f6e59b58862ed20be6/rest_framework/filters.py#L105).

My view utilizes the module *rest_framework.filters.SearchFilter*; however the request that is failing is a *PUT* request without any search fields.

It seems that [Commit b4b2dc](https://github.com/tomchristie/django-rest-framework/commit/b4b2dc18fa4cb6bbe008d4f6e59b58862ed20be6#diff-01f357e474dd8fd702e4951b9227bffcL102) removes the conditional preventing falsely search_fields from entering into the for loop.

Additional information can be provided upon request.

**Comment by jpadilla** [comment]
@erj1 thanks for the report. At a glance it does seem like a valid issue. We should probably move [L103-L106](https://github.com/tomchristie/django-rest-framework/blob/b4b2dc18fa4cb6bbe008d4f6e59b58862ed20be6/rest_framework/filters.py#L103-L106) after [L109-L110](https://github.com/tomchristie/django-rest-framework/blob/b4b2dc18fa4cb6bbe008d4f6e59b58862ed20be6/rest_framework/filters.py#L109-L110).

**Comment by erj1** [comment]
I looks like that has already been done in the non-released master branch.  Closing ticket.

**Comment by jpadilla** [comment]
@erj1 perfect, thanks! It was fixed in #3324

**Comment by erj1** [comment]
I don't know your release cycle so excuse my ignorance.  But when could I expect this update to be released?

**Comment by xordoquy** [comment]
We'll likely make a release next week.
