### ISSUE TITLE
[Security Issue] OPTIONS method on SlugRelatedField gives all instances in the database

### ISSUE THREAD

**Issue by gabn88** [tomchristie/django-rest-framework#3367]
I have DRF 3.2.2 with CustomObjectPermissions (Including the view permission) and DjangoObjectPermissionsFilter. Both work fine to limit what the user sees when he GETS a list (using the filter) or when he gets a specific instance (using the customobjectpermission).

However, I just recently noticed that the OPTIONS method of serializers.SlugRelatedField gives back ALL instances in the choice field via the 'value' and the 'display_name'. The first I have circumvented by creating a new class:
class NewSlugRelatedField(serializers.SlugRelatedField):
    queryset = MyModel.objects.all()
    def display_value(self, instance):
        return ''

which always gives an empty display_value. But the latter cannot be deleted so easily.

Also I don't like the monkeypatching and would rather see the issue itself resolved, namely that the OPTIONS method does not filter the choices! :)

Please help fix this.

**Comment by jpadilla** [comment]
Thanks for the report @gabn88.

Closed for lesser visibility.

Not to worry, but worth seeing the note on our security policy here: http://www.django-rest-framework.org/#security

Reporting potential security issues privately first gives us a bit more headroom for fixing issues.

---

**Security**

If you believe you’ve found something in Django REST framework which has security implications, please do not raise the issue in a public forum.

Send a description of the issue via email to rest-framework-security@googlegroups.com. The project maintainers will then work with you to resolve any issues where required, prior to any public disclosure.
