### ISSUE TITLE
Track ongoing deprecation

### ISSUE THREAD

**Issue by xordoquy** [tomchristie/django-rest-framework#3372]
While we have a deprecation policy, we don't track the ongoing deprecations.
We need to have something similar to https://docs.djangoproject.com/en/1.8/internals/deprecation/ to help us conform to the policy.

**Comment by auvipy** [comment]
+1

**Comment by carltongibson** [comment]
Do you think it's worth having a wrapper function that takes a version and a message...

     deprecated((3,1,3), "Moved to ... Use ... instead")

or such.

Inside we could check against the current version. Raise the appropriate warning. Assert `False` if too many versions have gone by. 

If we used this everywhere we'd never miss any deprecations. We could also search for it to find all instances.

**Comment by xordoquy** [comment]
@carltongibson Really interesting.

**Comment by tomchristie** [comment]
Neat idea yeah.

**Comment by carltongibson** [comment]
OK. I'll draft something up. 

(Put this in `compat.py`?)

**Comment by tomchristie** [comment]
Closing as per #3404. Don't see this as a priority, hasn't been a problem.
