### ISSUE TITLE
Test upload images in raw

### ISSUE THREAD

**Issue by BraisGabin** [tomchristie/django-rest-framework#3374]
I just found a really odd issue. I create this repo to reproduce it: https://github.com/BraisGabin/drf_upload_raw_test

With the code: https://github.com/BraisGabin/drf_upload_raw_test/tree/it-works both tests work ok. They are exactly the same. The only change is the image.

If I add `'TEST_REQUEST_DEFAULT_FORMAT': 'json',` to the settings file one of the tests fails, the other doesn't. (You can check it in the master).

Is this an issue? Or am I missunderstunding something?

**Comment by xordoquy** [comment]
@BraisGabin Could you be more precise with what doesn't work ? For example pasting here the results of the test runs ?

**Comment by BraisGabin** [comment]
```
Creating test database for alias 'default'...
.F
======================================================================
FAIL: test2 (app.tests.Upload)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brais/PycharmProjects/drf_upload_raw_test/app/tests.py", line 14, in test2
    self.assertEqual(response.status_code, 204, response.data)
AssertionError: {u'detail': u'FileUpload parse error - none of upload handlers can handle the stream'}

----------------------------------------------------------------------
Ran 2 tests in 0.203s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

The problem is that an Exception is raised with the text: `FileUpload parse error - none of upload handlers can handle the stream`. And this happens with one image and not with the other.

https://github.com/tomchristie/django-rest-framework/blob/3e1687282ba39b0166b7c17e39cdd3a2be7e2bc3/rest_framework/parsers.py#L188-L189

**Comment by BraisGabin** [comment]
Ok, I debug a bit the code and I know why the images change the behaviour. Their size is *diferent*. One of them is trated with an `InMemoryUploadedFile` and other with `TemporaryUploadedFile`.

I'm new in python but I think that the problem is the [line 186](https://github.com/tomchristie/django-rest-framework/blob/3e1687282ba39b0166b7c17e39cdd3a2be7e2bc3/rest_framework/parsers.py#L186). Do you want to check if the object is `True` or if the object is `None`?

But I don't know why if I don't set `'TEST_REQUEST_DEFAULT_FORMAT': 'json',` the method `FileUploadParser.parse()` is not called.

**Comment by tomchristie** [comment]
JSON doesn't support file uploads
