### ISSUE TITLE
exception handler doesn't render ValidationError for browsable api

### ISSUE THREAD

**Issue by thenewguy** [tomchristie/django-rest-framework#3376]
I am implementing filtering with django-filter per the drf docs.  It seems that drf does not handle django-filter in strict mode out of the box.

In my base `viewsets.ModelViewSet` I override the `filter_queryset` as follows:
```
    def filter_queryset(self, queryset):
        """
        django-filter raises django.core.exceptions.ValidationError in strict mode
        """
        try:
            qs = super(APIBaseModelViewSet, self).filter_queryset(queryset)
        except ValidationError, e:
            raise serializers.ValidationError(e)
        return qs
```

The [exception handler](https://github.com/tomchristie/django-rest-framework/blob/77867e1eef731853f6270660880b16696fbdec9d/rest_framework/views.py#L65) correctly returns a 400 status with the expected error list when the format explicitly requested (i.e. `/path/to/foo/bar.json?param=invalid`).  However I've encountered an issue where the response is a 500 error when the format is not explicitly requested and an invalid filter param is requested via the browser.

The debug view shows the exception is the django-filter django.core.exceptions.ValidationError exception wrapped in serializers.ValidationError by my overriden `filter_queryset` method.

Shouldn't the [exception handler](https://github.com/tomchristie/django-rest-framework/blob/77867e1eef731853f6270660880b16696fbdec9d/rest_framework/views.py#L65) be outputting a formatted html page listing the errors instead of a 500 response?

**Comment by xordoquy** [comment]
@thenewguy It would be great if you could come with a failing test case. In any case DRF shouldn't return a 500 but at this point I'm not sure whether it's DRF or your code that raise it.

**Comment by tomchristie** [comment]
`serializer.ValidationError` *is* caught by the default exception handler.

It is a [subclass of APIException](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/exceptions.py#L68) so is handled just as our other internal exceptions.

Presumably some other issue here, eg. the try..catch block isn't around the point where the `django.core.exceptions.ValidationError` exception is *actually* being raised.
