### ISSUE TITLE
Handling invalid UUIDs in URL parameters

### ISSUE THREAD

**Issue by monk8800** [tomchristie/django-rest-framework#3377]
I have been looking around forums and within the DRF issues but cant seem to find any examples how to handle invalid UUIDs passed in via browser. 

My REST end point is as follows using default SimpleRouter 
    
    http://localhost/api/v1/customers/3d70aa0089b64e32a358af90c5df57272b7
    
    router = routers.SimpleRouter(trailing_slash=True)
    router.register(r'customers', views.CustomerViewSet, 'customer')

If I was to pass in an invalid UUID i would get html response saying 

    ValueError: badly formed hexadecimal UUID string

Is they any way catch ValueError and return a custom JSON response such as invalid id that can be applied globally as most of my primary keys are UUIDs. Appreciate if anyone can point me to the right direction.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by xordoquy** [comment]
Note that it's up to you to validate it in your view.

**Comment by tomchristie** [comment]
If you're using the generic views they'll catch this automatically and you'll end up with a regular 404, exactly as you would with any other malformed URL.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L21

You probably want to mimic that behavior.

**Comment by monk8800** [comment]
Thanks guys for the feedback guess needed a nug in the right direction and perhaps my lack of understanding of the views. In some of my views am using

**Comment by njamaleddine** [comment]
It looks like Django 1.11 introduced different functionality for `get_object_or_404`. It now returns a `ValidationError` for an invalid `UUID` while in previous versions it returns a `ValueError`. 

Should we catch `ValidationError` in the `except` or should I handle this on a per class basis by monkey patching `get_object_or_404`?
https://github.com/encode/django-rest-framework/blob/a68b37d8bc432fae37ef5880aec500002b59f565/rest_framework/generics.py#L21

**Comment by tomchristie** [comment]
> Should we catch ValidationError in the except in rest_framework.generics

I think so, yes. An incorrect uuid in the URL path should 404.
