### ISSUE TITLE
PUT creates new data instead of updating it (the data includes new PK)

### ISSUE THREAD

**Issue by akbargumbira** [tomchristie/django-rest-framework#3378]
Hi,

I have model that looks more or less like this:
```
class Package(models.Model):
    id = models.CharField(primary_key=True, max_length=64)
    name = models.CharField(max_length=100)
    products = models.ManyToManyField(Product, related_name='products')
```

When doing PUT operation and changing the ID, it seems that it creates new data (with that ID), instead of updating the ID itself (the new data also has empty products even if I specify the products). It's returning 200 though instead of 201. Is this the expected behaviour? I am using version 3.1.3 .

The data that I send looks like this:
```
        new_data = {
            'id': new_id,
            'name': 'An Awesome Package',
            'products': [product_id]
        }
        response = self.client.put(url, new_data)
```

Thanks

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

Note that PUT is to create or update. I believe this is consistent with what Django does. If you change an ID from an object, Django will create a new one by default. You'll have to work this around by yourself.

**Comment by akbargumbira** [comment]
Hi @xordoquy Ok that makes sense. Just wanted a clarification, Thanks!
