### ISSUE TITLE
RFE: Cleaner hyperlink serialization for dict based APIs

### ISSUE THREAD

**Issue by ncoghlan** [tomchristie/django-rest-framework#3384]
(Breaking this out of the "Non-Model ViewSets" documentation discussion in #3373 )

I'm working on a project where I'm creating local proxy APIs for existing remote REST services. This means I'm largely working with data stored as attribute dictionaries, rather than as Python objects. While ViewSets + Serializers has mostly "just worked" for that use case, adapting HyperlinkedIdentityField involved completely overwriting get_url():

    # Adapts HyperlinkedIdentityField to use __getitem__ rather than __getattr__
    class DictBasedIdentityField(serializers.HyperlinkedIdentityField):

        def get_url(self, obj, view_name, request, format):
            # Unsaved objects will not yet have a valid URL.
            try:
                lookup_value = obj[self.lookup_field]
            except KeyError:
                return None
            kwargs = {self.lookup_url_kwarg: lookup_value}
            return self.reverse(view_name, kwargs=kwargs, request=request, format=format)

Would it make sense to have a "get_lookup_value()" method to override?

**Comment by tomchristie** [comment]
> Would it make sense to have a "get_lookup_value()" method to override?

I think that *probably* falls into the category of "not worth the extra API surface area"
After all, you'd only be saving two lines of code, and having less indirection here is a benefit to comprehensibility.
Reasonable judgement?

**Comment by ncoghlan** [comment]
My other thought was that being able to pass a callable for "lookup_value" would be nice, but DRF doesn't tend to use that API style, so it would be a pretty significant divergence.

While it's still early days, I'm starting to think that there may be scope for a "django-rest-framework-api-proxy" package that adds a few helpers specifically around using DRF as a proxy for other REST APIs. That could also be a potential long term solution to the docs discussion in #3373.
