### ISSUE TITLE
RAML integration

### ISSUE THREAD

**Issue by Kmaschta** [tomchristie/django-rest-framework#3389]
What do you think about an integration of [RAML (RESTful API Modeling Language)](http://raml.org/) in DRF, for documentation purpose or whatever ?

Someone has just started to work on this : [Django Rest Framework to RAML (raml's forum)](http://forums.raml.org/t/django-rest-framework-to-raml/962)

I'm looking forward to see that.

**Comment by xordoquy** [comment]
It would likely make a perfect 3rd party package. Have a look at the related topic under the topic menu in the drf documentation. Let us know if you need further help.
