### ISSUE TITLE
Add serpy as a third party serializer alternative

### ISSUE THREAD

**Issue by clarkduvall** [tomchristie/django-rest-framework#3391]
serpy is now compatible with REST framework generic views as a serialization-only alternative.

https://github.com/clarkduvall/serpy

**Comment by xordoquy** [comment]
@clarkduvall I'm going to close this because I have no idea what it is about.
You'll find informations about adding 3rd party software [here](http://www.django-rest-framework.org/topics/third-party-resources/#how-to-create-a-third-party-package).

**Comment by tomchristie** [comment]
It's fine I asked this to be opened as a reminder to myself to add it to the docs as an third party serializers package.

**Comment by tomchristie** [comment]
Anyone else also welcome to take it on. Add to "third party packages" section in serializers. Between marshmallow and mongo would make sense.

**Comment by nryoung** [comment]
I could probably take care of this tonight if nobody else takes care of it before then.

**Comment by tomchristie** [comment]
Welcome to, yup
