### ISSUE TITLE
Serializer validated_data differs depending on request content-type

### ISSUE THREAD

**Issue by ybendana** [tomchristie/django-rest-framework#3392]
I'm seeing a similar issue using DRF 3.2.3 as described here:

https://groups.google.com/forum/?fromgroups#!searchin/django-rest-framework/multipart$20put/django-rest-framework/P3kSd6wG1RY/_Sw9cvpWBwAJ

In my case I'm trying to do a multipart PUT to upload a file for a previously created Experiment.  An additional parameter of the request called analyses is an array of Analysis objects which I want to create/update in my custom serializer.update(). I've implemented this as a nested serializer in ExperimentSerializer like so:

    class ExperimentSerializer:
        analyses = AnalysisNestedSerializer(many=True, required=False)

The Analysis model has a foreign key to Experiment.

The issue is when I make the request, the serializer.validated_data in the ExperimentViewSet.perform_update() has analyses set to an empty array. Even if I don't pass in analyses in the request, it will still have it set to an empty array in validated_data.  I've tried a PATCH request as well and it gives the same behavior as PUT. 

However, if the content-type of the PUT is application/json then the analyses shows up fine in the validated_data. So my workaround is to have to do 2 PUT requests, one for the file upload and the second to update the nested analyses.

**Comment by xordoquy** [comment]
Answered on the mailing list.
