### ISSUE TITLE
The output text at line 184 in docs/tutorial/1-serialization.md is not correct.

### ISSUE THREAD

**Issue by qqbuby** [tomchristie/django-rest-framework#3395]
## env
    >>> import rest_framework,sys,django
    >>> rest_framework.__version__
    '3.2.3'
    >>> sys.version_info
    sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)
    >>> django.get_version()
    '1.8.4'
## Issue
**location** /docs/tutorial/1-serialization.md
**section**

     serializer = SnippetSerializer(Snippet.objects.all(), many=True)
     serializer.data
     # [{'pk': 1, 'title': u'', 'code': u'foo = "bar"\n', 'linenos': False, 'language': u'python', 'style': u'friendly'}, {'pk': 2, 'title': u'', 'code': u'print "hello, world"\n', 'linenos': False, 'language': u'python', 'style': u'friendly'}]
### should be

    >>> serializer = SnippetSerializer(Snippet.objects.all(), many=True)
    >>> serializer.data
    #[OrderedDict([('pk', 1), ('title', u''), ('code', u'foo = "bar"\n'), ('linenos', False), ('language', 'python'), ('style', 'friendly')]), OrderedDict([('pk', 2), ('title', u''), ('code', u'print "hello, world"\n'), ('linenos', False), ('language', 'python'), ('style', 'friendly')]), OrderedDict([('pk', 3), ('title', u''), ('code', u'print "hello, world"'), ('linenos', False), ('language', 'python'), ('style', 'friendly')])]
    >>>

**Comment by jpadilla** [comment]
@qqbuby Yeah sure. We do use the right representation in the example above that with `validated_data`. Want to send a PR our way with that fix?

**Comment by qqbuby** [comment]
@jpadilla 
I’ve fixed it in the branch named “ 3395” in my fork.  FYI.

**Comment by tomchristie** [comment]
Care to make a pull request from it?

**Comment by tomchristie** [comment]
Closed by #3396.
