### ISSUE TITLE
djangorestframework==3.2.3, serializer.DateField returning TimeField and visa versa

### ISSUE THREAD

**Issue by moh-moola** [tomchristie/django-rest-framework#3399]
djangorestframework==3.2.3, serializer.DateField returning TimeField and visa versa

When declaring a serializer with a DateField, a TimeField instance is returned instead this bug also persists when posting data the correct field instance is used to validate the data

**Comment by tomchristie** [comment]
I'm sorry but this isn't sufficient as a bug report. Seems infeasible given lack of other reports, and eg https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1061-L1066

Show us the minimum code you'd need to reproduce this and we can consider - as it stands it's impossible to tell this apart from a user error.
Could be eg. you've mixed up `DATE_FORMAT`/`TIME_FORMAT` in your settings?

**Comment by moh-moola** [comment]
My code looks something like this...

class MySerializer(serializers.ModelSerializer):
    start_date = serializers.TimeField()
...

class MyTest(APITestCase):
    def test_serializer(self):
        response = self.client.get(some_url)
        self.assertEqual(response.data,{'start_date': date.today().strftime(api_settings.TIME_FORMAT)}

**Comment by tomchristie** [comment]
Attempted to replicate. If you pass `Date` object to `TimeField` with ISO8601, then you'll just get the `.isoformat()` representation (so still a date). Assume that's what you're seeing?

(But again - help us out - what's `api_settings.TIME_FORMAT` in your example, what's the *actual* value of `state_date` you example?` Isolate *just the issue itself* and show us eg `TimeField().to_represenatation(some_value) == some_unexpected_value`

**Comment by moh-moola** [comment]
I have solved this issue, it was not the lib itself, after having gone through the code base, I found that there had been a mistake within the api settings

**Comment by tomchristie** [comment]
Grand.
