### ISSUE TITLE
`rest_framework.VERSION` is a string

### ISSUE THREAD

**Issue by carltongibson** [tomchristie/django-rest-framework#3403]
In `rest_framework.__init__.py`:

```
__version__ = '3.2.3'

# Version synonym
VERSION = __version__
```

Looking at #3372, I was hoping for a tuple here. 

Wondering what's best to do?

**Comment by xordoquy** [comment]
In the deprecation function you can VERSION.split('.')[:2]
We won't really care about micro for deprecation.

**Comment by carltongibson** [comment]
OK.
