### ISSUE TITLE
Review supported Django Versions and Compat

### ISSUE THREAD

**Issue by carltongibson** [tomchristie/django-rest-framework#3408]
Following the discussion in #3405

* [ ] Decide what versions of Django are we going to support.
* [ ] Review code in `compat.py` in accordance with that.

**Comment by carltongibson** [comment]
@tomchristie @xordoquy — If you make a decision here I'm happy to tidy up the compat module.

**Comment by tomchristie** [comment]
Well we'll certainly want to drop 1.5 for 3.3 so I'd suggest that as a commit.

**Comment by tomchristie** [comment]
1.6 also possible, but treat as a seperate commit if so.

**Comment by xordoquy** [comment]
Seconded. This will allow us to drop support for Python 2.6 as well.

**Comment by tomchristie** [comment]
I think dropping 2.6 for 3.3 should be unambiguous as well, right?

**Comment by xordoquy** [comment]
We'll make it clear but once Django 1.5 / 1.6 will be removed from the supported version we won't have any Django compatible with Python 2.6.

**Comment by carltongibson** [comment]
So drop 1.6?

**Comment by tomchristie** [comment]
I think we should drop python 2.6.
I don't think that should have any influence on which Django versions we support (tho dropping 1.6 could be valid in its own right)

**Comment by carltongibson** [comment]
OK, I'll make the PR assuming dropping both — we can always change our minds before merging. 

(Anyone on Django 1.6 could use v3.2.x — which would still work for them — they can't be that bothered about what versions they're on anyhow...)

**Comment by tomchristie** [comment]
py1.7+ dj1.6+ would seem reasonable to me at this point, but deps on how much of compat we can remove if we also drop dj1.6

**Comment by xordoquy** [comment]
I'd rather we align the supported Python version to what Django does but won't oppose it.

**Comment by carltongibson** [comment]
> I'd rather we align the supported Python version to what Django does but won't oppose it.

I agree here. If we keep Django 1.6, we should keep Python 2.6. (Opinion)

I'll do it in stages, keeping 2.6/1.6 to begin. Then I'll have a look at what we can drop if we get rid of it and we can decide then.

**Comment by xordoquy** [comment]
Let me know if / how I can help here.

**Comment by carltongibson** [comment]
OK. Will do! 👍

**Comment by carltongibson** [comment]
@xordoquy Let me know if you want #3404 — happy to finish it if so. (Equally happy to let it go if you don't think it's a helper)

**Comment by xordoquy** [comment]
Got some time this evening, will do.

**Comment by carltongibson** [comment]
I'm going to close this. Whatever we decide on #3429 settles it.
