### ISSUE TITLE
Document differences in auth scheme drf <-> django

### ISSUE THREAD

**Issue by belegnar** [tomchristie/django-rest-framework#3416]
Problem described in #760 takes some hours to be investigated. May it be possible to describe in drf docs the difference between django/drf auth scheme used? Due to my poor english i can't do it myself, sorry.

**Comment by xordoquy** [comment]
The documentation already mentions some differences. You need to know how Django authentication works but I think this is a sensible requirement.
I'm fine reopening this as long as we have more accurate details about what's missing.
