### ISSUE TITLE
Query paramater to control page size in CursorPagination

### ISSUE THREAD

**Issue by benoitguigal** [tomchristie/django-rest-framework#3417]
I am connected a DRF backend to a GraphQL endpoint. In GraphQL, you can paginate with a cursor and specify a page_size like this:
```
viewer {
   items(first: 10, after: "some_id") {
      edges {
         node {
            name
         }
      }
   }
}
```
I do not think it is possible to do that with CursorPagination in DRF. Would this feature be feasible ?

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
