### ISSUE TITLE
unhashable type error in BoolenaField.to_representation

### ISSUE THREAD

**Issue by augonis** [tomchristie/django-rest-framework#3418]
BooleanField serialization fails if fields source points to an unhashable, yet bool()-able value.

In my case I'm using django-bitfield to store flags on my model and I try to serialize a single flag with `BooleanField(source='flags.changed)`, but bitfield represents flags with custom (unhashable) type.
As a workaround I pointed fields source to flags `__bool__` method e.g. `BooleanField(source='flags.changed.__bool__)`.

**Comment by tomchristie** [comment]
Don't particularly see that the built-in BooleanField needs to support all bool-able cases. I'd be willing to consider Pull Requests, and if a small footprint then cleanups in this area might be accepted, but not interested in treating this as neccessary otherwise.
