### ISSUE TITLE
Model with blank=False should map to model with required=True.

### ISSUE THREAD

**Issue by nchampsavoir** [tomchristie/django-rest-framework#3422]
Currently a field with null=True and blank=False is mapped to a serializer field with required=False. This contradicts Django docs for blank fields:

>Field.blank
>If True, the field is allowed to be blank. Default is False.
>Note that this is different than null. null is purely database-related, whereas blank is validation-related. >If a field has blank=True, form validation will allow entry of an empty value. If a field has blank=False, >the field will be required.

If blank is False, field should be required=True.

A model field with null=True and blank=False is useful when you want to force a user to set a foreign key (blank=False) upon object creation or modification but you want to allow the related object to be deleted with no impact on the object at hand (on_delete=SET_NULL, null=True).

**Comment by xordoquy** [comment]
Django only deals with forms where there's no such thing as null field:

```
{}
{'field': None}
{'field': ''}
{'field': ‘content'}
```

The two first cases won't happen with Django while this will with Django REST framework.
Therefore, DRF considers that a null=True / blank=False should match #1, 2 and 4 but not #3 while Django will only accept #4. #1 implies required=False.

**Comment by nchampsavoir** [comment]
Ok.Thanks for the quick reply, It seemed logical to me that blank=False should only match #4 but I understand why the current behaviour might match the most common use cases better.
