### ISSUE TITLE
Allow TRUE_VALUES/FALSE_VALUES to be imported before Django configuration 

### ISSUE THREAD

**Issue by sloria** [tomchristie/django-rest-framework#3430]
`BooleanField.TRUE_VALUES` and `BooleanField.FALSE_VALUES` cannot currently be imported before `settings.configure()` has been called. It would be great if these constants could be accessed before configuration.

Our use case is that we have utility functions for conditionally changing responses based on query string params. We want to use the same truthy/falsy values defined by `BooleanField`. These utility functions may be imported before `settings.configure()` is called. Current workaround is to copy and paste the values.

This change can be made without breaking compat; I'd be glad to make a PR if the maintainers give the go-ahead.

**Comment by tomchristie** [comment]
Does #3363 adequately address this?

**Comment by sloria** [comment]
Yes, with that patch, I confirmed that BooleanField can be imported without an error.

**Comment by tomchristie** [comment]
Great. I'll close this off in pref to that. Hopefully in 3.3, should be ~3 weeks away.
