### ISSUE TITLE
UniqueTogether should be put automatically on ModelSerializer

### ISSUE THREAD

**Issue by JocelynDelalande** [tomchristie/django-rest-framework#3436]
While I understand that form-level validators should be copied to serializers by hand (or not), the case of the `unique_together` on model is different, as it triggers a DB error (at least with PostgreSQL).

So is the fact that by default, DRF will let an `IntegrityError` pop back to client into a 500 error intended ?

**Comment by JocelynDelalande** [comment]
@tomchristie Sorry for not providing description initially, I clicked sooner than i wanted, I'm writing the description right now, please reopen.

**Comment by tomchristie** [comment]
We *do* handle unique together constraints on ModelSerializer.
(See https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L1224-L1229 for example)

**Comment by JocelynDelalande** [comment]
@tomchristie Thanks for your reactivity and answer. Agreed it is not a bug, in my case it was caused by the fact the `unique_together` includes a field that is not part of the serializer. 

I was thinking about adding a note in the documentation, but reading it again, it seems ok to me.

**Comment by tomchristie** [comment]
:+1:
