### ISSUE TITLE
Extend user auth via AbstractApplication

### ISSUE THREAD

**Issue by ctippur** [tomchristie/django-rest-framework#3439]
Hello,

I am having trouble extending AbstractApplication to include fields from auth_user.
In my serializer, if I use the field from auth_user, I get a error:

Field name `email` is not valid for model `MyLogistics`.

Model:

class MyLogistics(AbstractApplication):
    govt_id = models.IntegerField()
    user_type=models.CharField(max_length=3, blank=False, default='USR')
    is_admin = models.BooleanField(default=False)

Serializer:
class CreateUserSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyLogistics
        fields = ('email','govt_id',)
        extra_kwargs = {'password': {'write_only': True}}

    #@method_decorator(login_required)
    def get_queryset(self):
        print ("Here")

    def create(self, validated_data):
        logistics = MyLogistics(
            email=validated_data['email'],
            username=validated_data['username'],
            first_name=validated_data['first_name'],
            last_name=validated_data['last_name'],
            address=validated_data['address'],
        )
        logistics.set_password(validated_data['password'])
        logistics.save()
        return logistics

View:
class AddUser( generics.ListCreateAPIView):
    permission_classes = (permissions.AllowAny,)
    queryset = MyLogistics.objects.all()
    serializer_class = CreateUserSerializer
    model=MyLogistics

Appreciate any inputs on this.

- Shekar

**Comment by carltongibson** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
