### ISSUE TITLE
Error with using filter

### ISSUE THREAD

**Issue by Eduard90** [tomchristie/django-rest-framework#3443]
Hello.
My code:
```
class PostFilter(django_filters.FilterSet):
    class Meta:
        model = SawPost
        fields = ['city']

class PostViewSet(ReadOnlyModelViewSet):
    queryset = SawPost.objects.filter(is_active=True).all()
    serializer_class = PostSerializer
    pagination_class = PostLimitOffsetPagination
    filter_backends = (filters.DjangoFilterBackend,)
    filter_class = PostFilter
```

I installed django-filter, but get error:
```
global name 'django_filter' is not defined
```
If i remove __init__ method from DjangoFilterBackend - all right.

**Comment by xordoquy** [comment]
You need to import django_filter.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by carltongibson** [comment]
Check your imports and references. The string is `django_filters` — note the `s`. Your error is lacking it. Search for `django_filter` without the `s`. There's your error.

**Comment by Eduard90** [comment]
I installed django-filter (pip install django-filter) but i can't import django_filter, only django_filters. I imported django_filters (with s), but in DRF - 
```
def __init__(self):
        assert django_filter, 'Using DjangoFilterBackend, but django-filter is not installed'
```

if i add 's':
```
def __init__(self):
        assert django_filters, 'Using DjangoFilterBackend, but django-filter is not installed'
```
All right ...
I don't installed django-filters (with s) - it's another package.
