### ISSUE TITLE
More graceful handling of misbehaving third party validators

### ISSUE THREAD

**Issue by ncoghlan** [tomchristie/django-rest-framework#3446]
After the long detour described below, I eventually figured out that a third party validator was throwing a ValidationError that had a list in "exc.details", rather than the mapping DRF expected.

This misbehaviour currently shows up as an internal server error, as `Serializer.errors` property attempts to feed the non-mapping to the `ReturnDict` constructor, leading to the confusing behaviour described below, and in the section titled "Snag 2: Invalid Validation Error" in http://devblog.kogan.com/django-rest-framework-features/

---

I'm currently attempting to debug an issue in RepoFunnel where submitting a POST command using the HTML Form in the browsable API works, but the raw HTTP+JSON submission fails.

The full serializer definition is at https://github.com/ncoghlan/repofunnel/blob/master/copr2pulp/restapi.py#L16, but the relevant aspects seem to be:

```
class FeedSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = models.Feed
        fields = ("id", "name", "url", "feed_url")

class Feed(models.Model):
    name = models.CharField(max_length=30, unique=True)
    pulp_repo = models.CharField(max_length=35, null=True)
    feed_url = models.URLField(unique=True)
```

Both the HTML Form and the raw JSON submission correctly pick up that only the "name" and "feed_url" fields need to be populated on submission, but the form submission works, while the raw JSON submission fails with a validation error.

Unfortunately, the Django DEBUG traceback is unhelpful, as it reports an unrelated error in attempting to construct the ValidationError exception. Using the Werkzeug debugger via RunServerPlus I believe I've traced that back as far as this line: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L209

The problem appears to be that `self._errors` is a list rather than a mapping:

```
['This field may not be null.']
```

That list presumably came from `exc.details` on a ValidationError thrown somewhere else. The call to the `self.errors` property then fails as it attempts to interpret the list as a mapping while initialising the ReturnDict instance.

Patching the code to use `self._errors` instead allows the page to render, but doesn't seem like the correct fix (since the returned error still doesn't say _which_ field isn't allowed to be NULL).

**Comment by xordoquy** [comment]
Html forms don't send null values. They send an empty string which is probably the reason why it works with them and not with the JSON.
It would be helpful to know which DRF version you're using and what you are submitting.

**Comment by ncoghlan** [comment]
Sorry about that. Version is 3.2.4.

The failing JSON submission looks like:

    {
        "name": "make-it-fail",
        "feed_url": "https://copr-be.cloud.fedoraproject.org/results/rhscl/rh-postgresql94/epel-7-x86_64/"
    }

I've tried adding "pk", "id", "self", "url", and "pulp_repo" to the submitted JSON as empty strings without any change - I still just get the cryptic "This field may not be null." error.

I think I see where in fields.Field to replace those default error messages with ones that include the field name, so I'll make that change locally and then submit a PR for it (assuming I'm right about where to make the change).

**Comment by ncoghlan** [comment]
Curiouser & curiouser - I changed the "null" and "required" default error messages to use "{field_name}" instead of "This field", and updated `field.Field.validate_empty_values` to pass `field_name=self.field_name` as a keyword argument to `field.Field.fail`.

Doing that produces `None` in the error message, so at the point where this field validation is being done, the field objects haven't actually been bound to a serializer instance yet (so my simple PR won't work).

**Comment by ncoghlan** [comment]
OK, I figured out the underlying bug that was triggering the secondary failure - it turns out that had nothing to do with DRF itself, and everything to do with the jsonapi.org parser I'm using, which expects JSON submissions in a different format, but is still a relative young library and doesn't emit nice error messages for validation failures yet. I figured that out after I found that the entire data attribute on the incoming request was `None`. Form submission was working because it bypassed the third party parser.

So that means the only potential change here would be an RFE to better tolerate misbehaving validators that provide details as something other than a mapping.

**Comment by xordoquy** [comment]
What was the input to the serializer then ?

**Comment by ncoghlan** [comment]
It appeared to be `None` - that's what made me suspect the problem was earlier in the parsing process.

Unfortunately, I'm not really familiar with the exact sequence of events between "bits arrive on wire" and "Serializer.is_valid() is called", so my description of what's going wrong is based on learning that flow as I tried to trace the origins of this particular error.

**Comment by tomchristie** [comment]
Howdy Nick,

Struggling a little to understand the crux of this issue.

> I eventually figured out that a third party validator was throwing a ValidationError that had a list in "exc.details", rather than the mapping DRF expected.

Okay, so can we take the jsonapi package out of the issue here, and demonstrate a test case which raises the (correct but unhelpful) exception?

(Aside: RFE?)

**Comment by xordoquy** [comment]
@tomchristie I assume it stands for Request For Enhancement.

**Comment by ncoghlan** [comment]
Aye, RFE=Request for Enhancement. Including it is a habit from Red Hat's main issue tracker where putting RFE in the subject will automatically flag the issue as a feature request rather than a bug report.

I'll attempt to put a minimal reproducer for the secondary failure together tomorrow using the Django shell.

**Comment by tomchristie** [comment]
:+1:

**Comment by tomchristie** [comment]
No problem with a resolution to this coming in time for 3.3.0, but its not a blocker for it, so dropping the milestone.

**Comment by ncoghlan** [comment]
To trigger the secondary failure, a test case like the following appears to be sufficient:

    # Always fail validation, but pass a string as the details rather than a mapping
    class BadValidation(serializers.ModelSerializer):
        class Meta:
            model = <any properly defined model class>
        def run_validation(self, data):
            raise serializers.ValidationError("Example")

    s = BadValidation(data={})
    s.is_valid(raise_exception=True) # It's reading s.errors to build the exception that fails

The resulting traceback will look something like this:

    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/srv/repofunnel/lib64/python3.4/site-packages/rest_framework/serializers.py", line 210, in is_valid
        raise ValidationError(self.errors)
      File "/srv/repofunnel/lib64/python3.4/site-packages/rest_framework/serializers.py", line 498, in errors
        return ReturnDict(ret, serializer=self)
      File "/srv/repofunnel/lib64/python3.4/site-packages/rest_framework/utils/serializer_helpers.py", line 19, in __init__
        super(ReturnDict, self).__init__(*args, **kwargs)
      File "/usr/lib64/python3.4/collections/__init__.py", line 56, in __init__
        self.__update(*args, **kwds)
      File "/usr/lib64/python3.4/_collections_abc.py", line 602, in update
        for key, value in other:
    ValueError: too many values to unpack (expected 2)

**Comment by tomchristie** [comment]
Great, thanks

**Comment by zubairalam** [comment]
`run_validation` is defined as following in `serializers.py` module, `djangorestframework==3.5.4`.

    def run_validation(self, data=empty):
        """
            We override the default `run_validation`, because the validation
            performed by validators and the `.validate()` method should
            be coerced into an error dictionary with a 'non_fields_error' key.
        """


OP has overrided run_validation method of his serializer class in a way which voilates the intented behaviour of `run_validation`, which eventually returns an error dictionary made out of an OrderedDict, which expects a list(or tuple) of tuples or a dictionary.

There is already sufficient inline documentation of `.run_validation` method, though it can also be documented explicitly in `serializers.md`.
This explicit documentation of `.run_validation` will help in a case when error messages produced by validators and `.validate()` method needs to be handled in a custom way.

I'll love to submit a PR, if needed.

Rest of the queries of OP are sorted by himself. So this issue can be closed, if explicit documentation is not needed.

**Comment by tomchristie** [comment]
@zubairalam Sounds right. Also I don't want us to document `run_validation` - it's private API.
