### ISSUE TITLE
IntegerField accepts "", DecimalField does not

### ISSUE THREAD

**Issue by sehmaschine** [tomchristie/django-rest-framework#3452]
When trying to reset the value of a field, I can use both ```""``` (empty string) as well as ```null``` with an ```IntegerField```, but I'm not able to use an empty string with a ```DecimalField```. This is especially weird since the ```DecimalField``` is being returned as a string (due to ```COERCE_DECIMAL_TO_STRING```).

I'm not sure if the empty string should be possible with both fields, but at least it should be consistent from my point of view.

**Comment by tomchristie** [comment]
> I'm not sure if the empty string should be possible with both fields, but at least it should be consistent 

Seconded - I'd say it should be an error for both. Not sure what you meant "trying to reset the value of a field" tho?

**Comment by sehmaschine** [comment]
Sorry, I'm not able to describe that better/different. But I hope the issue is understandable anyhow.

**Comment by jpadilla** [comment]
@sehmaschine could you perhaps put together a serializer that shows the problem, that'll help progress this along.

**Comment by mmedal** [comment]
Unless @sehmaschine can describe what he means by "reset the value of a field," I don't see an issue here. Here's a test case showing IntegerField and DecimalField working as intended:

    class TestIntegerAndDecimalFieldsSerializer:
        def setup(self):
            class ExampleSerializer(serializers.Serializer):
                integer = serializers.IntegerField()
                decimal = serializers.DecimalField(max_digits=5, decimal_places=2)
            self.Serializer = ExampleSerializer

        def test_invalid_null_data_values(self):
            serializer = self.Serializer(data={'integer': None, 'decimal': None})
            assert not serializer.is_valid()
            assert serializer.validated_data == {}
            assert serializer.errors == {
                'integer': [u'This field may not be null.'],
                'decimal': [u'This field may not be null.']
            }

        def test_invalid_use_of_empty_string_data_values(self):
            serializer = self.Serializer(data={'integer': '', 'decimal': ''})
            assert not serializer.is_valid()
            assert serializer.validated_data == {}
            assert serializer.errors == {
                'integer': [u'A valid integer is required.'],
                'decimal': [u'A valid number is required.']
            }

        def test_valid_string_data_values(self):
            serializer = self.Serializer(data={'integer': '4', 'decimal': '3.2'})
            assert serializer.is_valid()
            assert serializer.validated_data == OrderedDict([
                (u'integer', 4),
                (u'decimal', Decimal('3.2'))
            ])
            assert serializer.errors == {}

**Comment by sehmaschine** [comment]
I've implemented the above testcase (thanks @mmedal) with our setup and I do get the same results – which means Integer and Decimal both work the same way indeed. I'll try to figure out why we have this issue and why our test results are different.

In the meantime, feel free to close this. And SORRY for the confusion ... my bad!

**Comment by tomchristie** [comment]
Thanks for the follow up, folks! :+1:

**Comment by litchfield** [comment]
We're seeing this one too-- very strange
