### ISSUE TITLE
Django model fields validators incorrect inheritance (required=False)

### ISSUE THREAD

**Issue by Ales86** [tomchristie/django-rest-framework#3456]
I have a Django Model defined as follows:

```python
class TestModel(models.Model):
    """
    Test model
    """
    id = models.SmallIntegerField(primary_key=True, editable=False)
    name = models.CharField(max_length=64, editable=False, unique=True)
    transparent = models.BooleanField(blank=False, null=False)
    hex_code = models.CharField(max_length=7, blank=False, null=False)
```
Specifically, I expect the fields `transparent` and `hex_code` should be to be considered as required:[DjangoDoc](https://docs.djangoproject.com/en/1.8/ref/models/fields/#blank)

The `ModelSerializer` has been left with the default values:

```python
class TestModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = TestModel
```
Opening a shell and typing the following:
```python
from myapp.serializers import TempModelSerializer
serializer = TempModelSerializer()
print repr(serializer)
```

This is what I see:
```python
TempModelSerializer():
    id = IntegerField(read_only=True)
    name = CharField(read_only=True)
    transparent = BooleanField(required=False)
    hex_code = CharField(max_length=7)
```

The `required` parameter for some reason is set to `False` instead of `True` (when not present, the default should be `True`, right? [DRFDoc](http://www.django-rest-framework.org/api-guide/fields/))

Lastly, if I send a POST request with the following body:

```json
{
    "hex_code": "#FFaFFF"
}
```

The validator validates the message as correct even though some fields (e.g. `name` which should be `required=True` by default) have not been sent.

**Comment by xordoquy** [comment]
How would you have a `read_only` field that is `required` ?

**Comment by xordoquy** [comment]
Reopening because I haven't stated on the `BooleanField`'s `required` state.

**Comment by tomchristie** [comment]
> The required parameter for some reason is set to False instead of True

It should be `required=False` because the model field has a default.
(Not quite the same thing as adding a default to a serializer field)

**Comment by Ales86** [comment]
I am not entirely sure about what you mean by "The model field has a default". 
I have posted the model definition and there are no default values specified ([DjangoDocsDefault](https://docs.djangoproject.com/en/1.8/ref/models/fields/#default)).

The only times I mentioned default values I was referring to the default values of the serializer field options.
