### ISSUE TITLE
Adding drf-haystack to third party resources.

### ISSUE THREAD

**Issue by rhblind** [tomchristie/django-rest-framework#3458]
Hi,

I've been working on [drf-haystack](http://drf-haystack.readthedocs.org/en/latest/index.html) for a while and would like to add it to the Django REST Framework Third party resources.

It's a small bridge library for using Haystack as a datasource with REST Framework.

- Github repo: https://github.com/inonit/drf-haystack
- Travis: https://travis-ci.org/inonit/drf-haystack

Thanks

**Comment by xordoquy** [comment]
Sure, here are the directions for that:
http://www.django-rest-framework.org/topics/third-party-resources/#once-your-package-is-available
