### ISSUE TITLE
Explain how exceptions in a custom authenticator are used in the response

### ISSUE THREAD

**Issue by kumar303** [tomchristie/django-rest-framework#3467]
It wasn't totally obvious to me from the [custom authentication docs](http://www.django-rest-framework.org/api-guide/authentication/#custom-authentication) that an exception message is used in the response (unless there is DRF configuration to turn this off?). 

This is an important detail because my inclination in Python is to raise exceptions with detailed information and that could give an attacker clues about how to break my authentication.

It would be great to amend the `ExampleAuthentication` code with this note:

When this example code raises an `AuthenticationFailed` exception, the request will result in a 401 response containing the exception message. It would look like this this if you're using a JSON encoder:

````
{"detail": "No such user"}
````

**Comment by xordoquy** [comment]
This is explained in the Exception part of the Django REST framework documentation:
http://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views

**Comment by xordoquy** [comment]
Longer response: maybe we could link to that documentation section but I feel it's a bit too much to explain it again there.

**Comment by kumar303** [comment]
I understand the RTFM argument for sure but if someone is looking to implement a custom auth backend this is a pretty crucial detail. Even just a link to the exception handling page right after the sentence "If authentication is attempted but fails, raise a AuthenticationFailed exception" would be hugely helpful.

**Comment by tomchristie** [comment]
Happy to consider a change - go ahead and make a pull request and we can review from there.
