### ISSUE TITLE
DRF - get access user from token

### ISSUE THREAD

**Issue by ctippur** [tomchristie/django-rest-framework#3468]
I am using DRF. I want to get the username from the token I am passing.

Here is my curl command:

curl -H "Authorization: Bearer $access_token" -X GET http://localhost:8000/getBlah

Here is what I have so far:

from rest_framework.authtoken.models import Token

class getTokenl(generics.RetrieveDestroyAPIView):
    permission_classes = [permissions.IsAuthenticated, TokenHasReadWriteScope]
    queryset = Parcel.objects.all()
    serializer_class = ParcelGetSerializer
    model=Parcel
    def dispatch(self, request, *args, **kwargs):
        tok=request.META['HTTP_AUTHORIZATION'].replace('Bearer ','')
        print (Token.objects.get(authtoken=tok))

With this, I get a error:

type object 'Token' has no attribute 'objects'

**Comment by xordoquy** [comment]
Answered on the mailing list. Please don't post usage question on the issue traker.

**Comment by ctippur** [comment]
Xaviar,

Which mailing list are you referring to?
https://docs.djangoproject.com/en/1.8/internals/mailing-lists/

- Shekar

**Comment by ctippur** [comment]
Also,

what is my best bet to get an answer? I dont seem to get answer on google groups :/.

- Shekar

**Comment by tomchristie** [comment]
https://groups.google.com/forum/#!forum/django-rest-framework
