### ISSUE TITLE
perform_create documentation issue

### ISSUE THREAD

**Issue by MattBroach** [tomchristie/django-rest-framework#3470]
on the Generic Views page, the documentation says:

> These hooks are particularly useful for setting attributes that are implicit in the request, but are not part  of the request data. For instance, you might set an attribute on the object based on the request user, or  based on a URL keyword argument.

>```
> def perform_create(self, serializer):
>     serializer.save(user=self.request.user)
>```

In that case, if if the model has as *required* user field, the above code will actually raise a validation error, because the serializer validation is called **before** `perform_create` is call called in the `create` function.  I was able to solve this problem by overriding the create function like so:

```
def create(self, request, *args, **kwargs):
     request.data['user'] = request.user.id
     return super(NewArticleView,self).create(request,*args,**kwargs)
```

Which ensures that the user is added to the data before serializer validation.  Is it worth added a note to the documentation about this? Going off the documentation alone, it wasn't clear to me that validation had already been called until I dug into the actual source code of the class.

**Comment by xordoquy** [comment]
@MattBroach The serializer won't raise any validation warning if the field isn't part of the serializer.
If it does, you're looking for a default value, not an implicit attribute.

**Comment by xordoquy** [comment]
Also note that a required field should not be left to a default because required means you want an explicit field to be provided by the caller.
