### ISSUE TITLE
Customization of generic.GenericAPIView.get_object()

### ISSUE THREAD

**Issue by eugena** [tomchristie/django-rest-framework#3473]
Hello, I propose to add the ability to customize the get_object function in this way:

    filter_kwargs = {self.lookup_field: self.get_lookup_kwarg(lookup_url_kwarg)}

    def get_lookup_kwarg(self, lookup_url_kwarg):
            """
            Returns lookup kwargs
            """
            return self.kwargs[lookup_url_kwarg]

with the ability to override the get_lookup_kwarg() method in concrete viewset instead of:

    filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}

Current version seems to be not enough flexible.

Thanks.

**Comment by xordoquy** [comment]
What use cases would that change solve ?

**Comment by eugena** [comment]
I can't use


    filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}


because I need to do some actions with self.kwargs[lookup_url_kwarg] before putting to the filter.

Therefore, I override my get_object method:

    def get_object(self):
        """
        Returns the object the view is displaying.
        """
        ...
        obj = generics.get_object_or_404(
            self.get_queryset(),
            **{self.lookup_field: SOME_FUNCTION(self.kwargs.get('SOME_KEY'))})
        self.check_object_permissions(self.request, obj)
        return obj


We can see then some functionality has moved from framework to my method, but I don't want that.

**Comment by xordoquy** [comment]
I think this use case is too specific for us to bring to core.
Note that this can be generalized with a Mixin class for your project and externalized as [a 3rd party package](http://www.django-rest-framework.org/topics/third-party-resources/#how-to-create-a-third-party-package).
