### ISSUE TITLE
Need method to pass extra data before validation

### ISSUE THREAD

**Issue by vitaly-nevgen** [tomchristie/django-rest-framework#3486]
So, for example we have this code. One user can leave only one message:

```python
class Message(models.Model):
   ...
   author = ForeignKey(...)
   body = TextField(...)

   class Meta:
       unique_together = (('author', 'body'), )


class MessageSerializer(serializers.ModelSerializer):
    ...
    class Meta:
        model = Message
        fields = ('body', )

def perform_create(self, serializer):
    ...
    serializer.save(author=author)
```

The problem is that second message from the same author will fail with IntegrityError, because no validation was made after new data was added. Serializer not validating fields what was not listed in Meta.fields. But if we'll add this fields to serializer - DRF will wait this data from user, but user must have no ability to set this data by himself.

Or may be I missing something?

**Comment by carltongibson** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. 

However, check out the docs on [Specifying read-only fields](http://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields) — it should have what you need.
