### ISSUE TITLE
`serizlizer_class` argument in @detail_route decorator

### ISSUE THREAD

**Issue by prudnikov** [tomchristie/django-rest-framework#3491]
I tried this but it seems that it doesn't work this way.
    @detail_route(methods=['get'],
                  url_path="some-thing",
                  serializer_class=SomeThingSerializer)
    def some_thing(self, request, pk=None):
        return Response(self.get_object().some_things())

I wasn't able to find it in the documentation either. If it is not supported, treat it as a feature request.

**Comment by tomchristie** [comment]
Override `get_serializer_class` if you want dynamic serializer behavior.

**Comment by prudnikov** [comment]
This will define a serializer class for the whole viewset, but not this particular view decorated with `@detail_route` decorator.

**Comment by xordoquy** [comment]
@prudnikov seconding @tomchristie, you can return the `Serializer` from `get_serializer_class` according to the action used.

**Comment by prudnikov** [comment]
@xordoquy @tomchristie `get_serializer_class` is called for standard set of operations on ViewSet. But I'm talking about the view decorated with `@detail_route`. For this view `get_serialized_class` is never called. 

Docs http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing

**Comment by xordoquy** [comment]
@prudnikov it's called if you call it, but the point was that it was a way to figure out what serializer to use for - say- description in metadata.

**Comment by prudnikov** [comment]
@xordoquy right, you can do a lot of things manually, for example without ModelViewSet using APIView, or even without Django Rest Framework using just Django. But why if it can be simplified.
