### ISSUE TITLE
remove south migrations

### ISSUE THREAD

**Issue by auvipy** [tomchristie/django-rest-framework#3495]

**Comment by xordoquy** [comment]
Once all the supported Django versions will have migrations.

**Comment by xordoquy** [comment]
Reopening as Django 1.6 - the latest before migrations - is now unsupported.

**Comment by auvipy** [comment]
yup.

**Comment by auvipy** [comment]
hei If I want to send PR what works should I do? removing the south_migrations files? any bc issue?

**Comment by xordoquy** [comment]
I think removing the south_migrations directory should do.

**Comment by tomchristie** [comment]
Good catch

**Comment by auvipy** [comment]
ok will send the PR for review. what is the deadline for 3.3?

**Comment by auvipy** [comment]
PR #3502
