### ISSUE TITLE
Permission class for Read Only access to all Authenticated users

### ISSUE THREAD

**Issue by avinassh** [tomchristie/django-rest-framework#3496]
I needed a permission class which has read only endpoints to authenticated users. In docs I couldn't find anything similar so I implemented own: 

    class IsAuthenticatedAndReadOnly(permissions.IsAuthenticated):
        def has_permission(self, request, view):
            if request.method in permissions.SAFE_METHODS:
                return super(IsAuthenticatedAndReadOnly, self).has_permission(
                    request, view)

do you think this has a place in DRF? Then I could send a PR :smile:

**Comment by tomchristie** [comment]
As a custom permission in your application would be best :)

**Comment by avinassh** [comment]
Sure :+1: 

:beers:
