### ISSUE TITLE
IDE breakpoint does not work for Serializer methods

### ISSUE THREAD

**Issue by liminspace** [tomchristie/django-rest-framework#3505]
I use PyCharm for my work and I noticed that breakpoints are not working when I use rest framework.
For example, I created serializer class:

    class CountrySerializer(serializers.HyperlinkedModelSerializer):
        name = serializers.SerializerMethodField()

        class Meta:
            model = Country
            fields = ('id', 'iso2', 'iso3', 'name', 'lat', 'lon')

        def get_name(self, obj):
            print 'test'  # <= breakpoint is here
            lang = translation.get_language()
            if lang != settings.LANG_DEFAULT:
                try:
                    return obj.name_trans.get(lang=lang).text
                except obj.name_trans.model.DoesNotExist:
                    pass
            return obj.name

In debug mode in my IDE breakpoint does not work, but `print` works.
If I set `settings.DEBUG = False` then breakpoint works.

Why it so works and how to fix it?

**Comment by xordoquy** [comment]
You should try the  [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) rather. You might also want to give the Django user mailing list a message about this, someone may have had this issue with other software.
