### ISSUE TITLE
status.py repackged with invalid license

### ISSUE THREAD

**Issue by gdude2002** [tomchristie/django-rest-framework#3506]
See [this project](https://github.com/avinassh/status) - I know django-rest-framework is an open source repo, but I thought you guys may want to be aware that someone's pretty much just copied the `status.py` and added a `setup.py`, with an invalid project license.

Up to you if you guys want to poke the guy, but it's worth noting that their repo appeared in the Import Python newsletter, and as an open source dev myself, I wouldn't want it being misattributed.

**Comment by carltongibson** [comment]
The author there has opened a PR adding the original copyright and disclaimer to the main licence file. https://github.com/avinassh/status/pull/6

I think that should cover it. 

I'm going to close this here. @gdude2002 Thanks for the report! 

@tomchristie Unless you shout, I'll assume you're happy with the change.
