### ISSUE TITLE
ModelSerializer cannot generate field for virtual field automatically

### ISSUE THREAD

**Issue by lexdene** [tomchristie/django-rest-framework#3522]
In Django models, there are some fields called `virtual_fields`.
ModelSerializer cannot generate serializer fields for them automatically.

example code:

```python
from django.db import models

from rest_framework import serializers


class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)


class Album(models.Model):
    artist = models.ForeignKey(Musician)
    name = models.CharField(max_length=100)


class AlbumSerializer(serializers.ModelSerializer):
    class Meta:
        model = Album
        fields = ('id', 'name', 'artist_id')


album = Album.objects.last()
data = AlbumSerializer(album).data
```

that will raise an error:

    ImproperlyConfigured: Field name `artist_id` is not valid for model `Album`.

**Comment by xordoquy** [comment]
`artist_id` is a model's property, not a field.

**Comment by tomchristie** [comment]
You'll need to add fields for properties or methods explicitly.

Eg.

    artist_id = serializers.IntegerField()
