### ISSUE TITLE
boolean field in nested serializers view renders html checkbox always True

### ISSUE THREAD

**Issue by mikofski** [tomchristie/django-rest-framework#3523]
DRF: 3.2.4
Django: 1.8.5

**expected:**
checkbox input should show same as rendered json.

**observed:**
If a nested serializer contains a boolean field, then when it's view is rendered as html, the boolean field is always shown as true

example:

    class NestedSerializer(serializers.Serializer):
        is_always_true = serializer.BooleanField()
        def create(self, validated_data):
            return Nested(**validated_data)

    class MainSerializer(serializers.Serializer):
        nested = NestedSerializer()
        def create(self, validated_data):
            return Main(**validated_data)

I don't understand how to write a test for the html renderer to check why the checkbox input has the "checked" attribute - if I figure it out, I will add a test.

**Comment by xordoquy** [comment]
I'm missing a point here. When you say "the boolean field" you mean the output displayed as JSon in the browsable API right ?

**Comment by mikofski** [comment]
Yes, in the HTML form of the browsable api. Do a GET and even if the nested boolean field shows as false in the JSON, the HTML form always shows a checkbox input in "checked" state. I will paste a screenshot tomorrow.

**Comment by xordoquy** [comment]
I'm a bit surprised here because forms don't support nested relations yet.

**Comment by tomchristie** [comment]
Actually we do render nested serializers, but only for to-one relationships (not to-many)

**Comment by xordoquy** [comment]
Right, I forgot that one.
Does this related to #2776 ?

**Comment by tomchristie** [comment]
Believe this is a different issue.

**Comment by mikofski** [comment]
I was unaware of #2776 (altho I did search for relevant issues).

On an slightly tangential note: @tomchristie you said that nested relations were only available for `many=False`; I have enabled support for nested serializers with `many=True` by monkey-patching `get_value()` inside the view. It seems to work okay for inputting data as a JSON string into HTML forms. I also set the serializer style to `{"base_template": "textarea.html"}` for that. It always displays the output data as an `OrderedDict` which is fine with me. I just posted something on it [here](http://poquitopicante.blogspot.com/2015/10/rest-ful-revelations.html).

**Comment by dursk** [comment]
Submitted a patch for this: https://github.com/tomchristie/django-rest-framework/pull/3544

The issue was in the `NestedBoundField.as_form_field()` method. What was happening was `False` was getting converted to the string `'False'`, so in the template `{% if field.value %}` was evaluating to `True`, causing the checkbox to be checked by default.

Similar to the way both `NestedBoundField` and `BoundField` handle `None`, the fix was to set `.value` to `''` when it the real value is `False` (`BoundField` did this already).
