### ISSUE TITLE
tests fail - TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by brianmay** [tomchristie/django-rest-framework#3524]
Suspect this might be a Django 1.7 specific issue.

```
Creating test database for alias 'default'...
......................................................................................................................................................................................................................................................................................................................................................................................................E................................................................
======================================================================
ERROR: test_duration_field (tests.test_model_serializer.TestDurationFieldMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/tree/debian/python-modules/djangorestframework/django-rest-framework-3.2.4/tests/test_model_serializer.py", line 329, in test_duration_field
    class DurationFieldModel(models.Model):
  File "/home/brian/tree/debian/python-modules/djangorestframework/django-rest-framework-3.2.4/tests/test_model_serializer.py", line 333, in DurationFieldModel
    duration_field = ModelDurationField()
TypeError: 'NoneType' object is not callable

----------------------------------------------------------------------
Ran 455 tests in 1.648s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

**Comment by xordoquy** [comment]
Closing because there's not enough informations (which tox env is run for example) plus our builds are free (https://travis-ci.org/tomchristie/django-rest-framework/builds/81369932.

**Comment by brianmay** [comment]
As the maintainer of the Debian package I need this to work in order to continue packaging it for Debian.

This error is expected, because ModelDurationField is in tests.test_model_serializer is set using:

```python
from rest_framework.compat import DurationField as ModelDurationField            
```
In rest_framework.compat it is defined as

```
if django.VERSION >= (1, 8):                                                     
    from django.db.models import DurationField                                   
    from django.utils.dateparse import parse_duration                            
    from django.utils.duration import duration_string                            
else:                                                                            
    DurationField = duration_string = parse_duration = None
```

As you can see it is nothing to do with the test environment. It is an expected error with Django 1.7

I would appreciate it if you didn't close the bug report without at least glancing at the code first.

If you don't want to help with this - e.g. maybe you don't want to support Django 1.7 anymore, I will just disable that test or something.

**Comment by tomchristie** [comment]
> I would appreciate it if you didn't close the bug report without at least glancing at the code first.

Our tests are all passing against 1.7, so it's unclear why you're seeing an issue when we're not?
Any information on exactly how you're replicating this?

**Comment by xordoquy** [comment]
There's no reason this test is run provided that it's skipped if Django < 1.8:
https://github.com/tomchristie/django-rest-framework/blob/3.2.4/tests/test_model_serializer.py#L325

**Comment by brianmay** [comment]
Ok, I missed seeing that test.

I just saw in the source code:

```python
@pytest.mark.skipif(django.VERSION < (1, 8),  
                      reason='DurationField is only available for django1.8+')
  class TestDurationFieldMapping(TestCase):
```

So the test should not have been executed.

Looks like a problem with pytest. This is version 2.7.3-1 - wonder if that is a problem...

So you probably can close this bug report, I will try to chase up what is going wrong - maybe tomorrow.

**Comment by brianmay** [comment]
I notice that the CI tests use python-pytest version pytest==2.6.4 and the latest version is 2.8.2. So possibly a regression in python-pytest.

**Comment by xordoquy** [comment]
Ran the tox suite with pytest / pytest-django unpinned and it worked.
Versions for py34 / django17:
- cov-core==1.15.0
- coverage==3.7.1
- Django==1.7.10
- django-filter==0.10.0
- django-guardian==1.3
- djangorestframework==3.2.4
- Markdown==2.5.2
- py==1.4.30
- pytest==2.8.2
- pytest-cov==1.8.1
- pytest-django==2.9.1
- six==1.10.0
- wheel==0.24.0
