### ISSUE TITLE
DRF 2.x docs are unstyled

### ISSUE THREAD

**Issue by jdunck** [tomchristie/django-rest-framework#3529]
n Chrome 45.0.2454.101, the DRF 2.x docs fail to load properly.  The pages are served from:

https://tomchristie.github.io/rest-framework-2-docs/...

but the CSS is from http://..., and chrome blocks the mixed-mode content.

This causes the pages to be unstyled and a bit harder to use.

Hopefully it's a simple thing to regenerate to use //tomchristie... or https://tomchristie... ?

**Comment by jpadilla** [comment]
@jdunck thanks for the heads up. Want to fix those? You should be able to edit [this](https://github.com/tomchristie/rest-framework-2-docs/edit/gh-pages/index.html) file and send a PR on that repo. Closing this on the mean time.
