### ISSUE TITLE
serialization of models use HyperlinkedModelSerializer without having the request context

### ISSUE THREAD

**Issue by cosmosgenius** [tomchristie/django-rest-framework#3532]
We are having a scenario wherein we were using a HyperlinkedModelSerializer to serialize a model which is not under the request-response flow.

on DRF 3.1.x we would simple pass and empty request object to the serializer context which makes the url to be relative to root than having an absolute url.
https://github.com/tomchristie/django-rest-framework/blob/version-3.1/rest_framework/reverse.py

since DRF 3.2 there is an addition check in the request.GET to preserve the query param from the request object, which as you can see break the above flow.
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/reverse.py#L52

So the question is how can we use HyperlinkedModelSerializer without the request context? Getting a relative url to the root is an acceptable scenario than having no urls at all.

Sample code
```
data = PostsSerializer(post, context={'request': {}}).data
```
This flow doesn't have request object. eg: Get a data from third party using celery beat. Storing in db. Serializing it to json and sending it to firebase, The same data can be fetched via DRF directly or via firebase.

**Comment by tomchristie** [comment]
> on DRF 3.1.x we would simple pass and empty request object to the serializer context which makes the url to be relative to root than having an absolute url.

Could you give a code example of this?

**Comment by cosmosgenius** [comment]
> Could you give a code example of this?

The attached code sample is how we are doing it in DRF 3.1.x

Attaching class definition for serializer and model as well 
The `PostsSerializer` is a HyperlinkedModelSerializer for the model `Post`

```
class Post(models.Model):
        field1 = models.CharField(max_length=75)
        field2 = models.CharField(max_length=75)

class PostsSerializer(serializers.HyperlinkedModelSerializer):
        field1 = serializers.CharField()
        field2 = serializers.CharField()
        class Meta:
              model = Post
```

**Comment by tomchristie** [comment]
Thanks, tho I was referring to the "empty request object", do you mean eg?...

    context = {'request': Request()}

**Comment by cosmosgenius** [comment]
eeh...nice i didn't think of doing that...I was just passing a simple dict `{}` instead of `Request()`. My wording were poor when i referring tp "empty request object". This pretty much solves the problem i had.

If using HyperlinkedModelSerializer outside request context is being provided by DRF itself as an option rather than this work around it would be great.

If not it would be nice idea to add this
> ```
> context = {'request': Request()}
> ```

to the docs for HyperlinkedModelSerializer as this may be a valid to others as well. I can do a PR for the docs if we are doing with this.

**Comment by cosmosgenius** [comment]
Using Request() alone does not. I am passing it now as 
```
context  = {'request': Request(HttpRequest())}
```
Where HttpRequest is the django request object.

This also doesn't work as some details about the server is missing.
Adding partial stack trace for the error.

```
"/home/nabeel/VirtualENVs/Brandy/local/lib/python2.7/site-packages/rest_framework/relations.py", line 264, in to_representation
    return self.get_url(value, self.view_name, request, format)
  File "/home/nabeel/WebApps/Brandy/brandy_project/core/serializers.py", line 31, in get_url
    format=format
  File "/home/nabeel/VirtualENVs/Brandy/local/lib/python2.7/site-packages/rest_framework/reverse.py", line 26, in reverse
    return _reverse(viewname, args, kwargs, request, format, **extra)
  File "/home/nabeel/VirtualENVs/Brandy/local/lib/python2.7/site-packages/rest_framework/reverse.py", line 39, in _reverse
    return request.build_absolute_uri(url)
  File "/home/nabeel/VirtualENVs/Brandy/local/lib/python2.7/site-packages/django/http/request.py", line 151, in build_absolute_uri
    host=self.get_host(),
  File "/home/nabeel/VirtualENVs/Brandy/local/lib/python2.7/site-packages/django/http/request.py", line 83, in get_host
    host = self.META['SERVER_NAME']
KeyError: u'SERVER_NAME'
```

**Comment by gcbirzan** [comment]
The way I got it to work is to send False to the context, due to a bug on https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/reverse.py#L64, it skips that (doesn't check against None). That also requires disabling querystring format overrides, though, so it's ugly.

My question is, should this be supported? If so, changing the code to check for request being falsey (vs None) in https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/reverse.py#L20 would probably fix it.

The API, however, would be a bit weird, so there's that...

**Comment by tomchristie** [comment]
Closed by https://github.com/tomchristie/django-rest-framework/commit/75751cc64ec8aa5bbff51d225f8979ee73f2d3c6 (accidently pushed to master rather than branch / pull request)
