### ISSUE TITLE
Having Token & Sessions Auth classes clash if user is previously authenticated via session auth

### ISSUE THREAD

**Issue by timworx** [tomchristie/django-rest-framework#3538]
My scenario:

 - Django Admin (which uses session auth) is used for some admin tasks.
 - DRF browable API used in dev/staging (which, as far as I can tell, only uses session auth)
 - Angular SPA hooks into DRF API using Token auth

My settings file had:

```
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
```

This worked fine for enabling the browsable API and the Angular app. However, I started running into this response when authenticating from the Angular app (that uses token auth) `"CSRF Failed: CSRF token missing or incorrect."`

It was just sending a `Authentication: Token xxxxxxxxxx` header for auth so it was peculiar to receive this error in response. 

I noticed that logging out of Django admin would first would fix the issue (then you could log back into django admin).

What I found to ultimately fix the issue was simply removing `'rest_framework.authentication.SessionAuthentication'` from the auth classes in my `settings.py`.

The downside, though, is that the browsable API seems to use session auth, so I've lost access to that. 

Any thoughts on why this was an issue in the first place? I haven't had time to dig into DRF to see why this would be an issue on token auth.

**Comment by marctc** [comment]
I have the same problem. Any news regarding this issue?

**Comment by tomchristie** [comment]
I wouldn't expect to see this unless:

* SessionAuth was configured *before* TokenAuth.
* No token header was being passed.

Those are the only circumstances when the session auth would kick in. (Ie if TokenAuth successfully authenticates, and is configured first, then the SessionAuth will never run and you won't have to pass CSRF)

Any chance that either of those two options above are possible?

> the browsable API seems to use session auth, so I've lost access to that.

We may be able to address that in a future version. But that's rather an aside to you bumping into an issue here.

**Comment by tomchristie** [comment]
If anyone's able to come up with a simple "do this to replicate" I'm sure we'd be able to dig out whatever usage issue / documentation problem / whatever is at root here.

**Comment by marctc** [comment]
>No token header was being passed.

In my case, I'm not passing any Token because I'm trying to do a login request. However, If I only set `TokenAuthentication` on settings it works

**Comment by tomchristie** [comment]
> I'm not passing any Token because I'm trying to do a login request.

Looking at their view... https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py#L30

Bit unclear on if that view is supposed to mean 'login' (which'd imply session log-in to me) or if its supposed to mean 'obtain token'.

Assuming the later it'd make sense for the view to explicitly have `authentication_classes = ()` set, so that it doesn't fall back to the global defaults. (SessionAuth doesn't make sense to apply to a 'give me the token view', and as you've seen will result in a CSRF failure)

**Comment by DKey96** [comment]
If you want to use both, SessionAuth and TokenAuth, then the TokenAuth Middleware must be inside setting BEFORE the SessionAuth Middleware. Why so? 

As your API is using the TokenAuth  as soon as it receives request, first it checks, if there is a Token in Authorization header. If so, user is authenticated and the other auth methods will be skipped. If you have WebApp that is not sending Token but uses Sessions (tokens inside cookie), it will be used instead as Token auth would fail.
