### ISSUE TITLE
Django 1.9 raw HTML in header

### ISSUE THREAD

**Issue by aidanlister** [tomchristie/django-rest-framework#3545]
I just upgraded to 3.2.4 and this is what I see:

<img width="1002" alt="screen shot 2015-10-25 at 8 35 12 pm" src="https://cloud.githubusercontent.com/assets/54896/10714927/f175ae3a-7b57-11e5-94ab-bb253219113f.png">

**Comment by tomchristie** [comment]
Notes on how to replicate would be great, as we've not had this raised elsewhere. Does it replicate on a clean install, and what exact steps are required?

**Comment by jpadilla** [comment]
Oh yea, I just replicated this.

```
$ git clone https://github.com/tomchristie/rest-framework-tutorial.git
$ pip install -r requirements.txt
$ pip install --upgrade --pre django
$ pip install --upgrade djangorestframework
$ ./manage.py runserver
```

Might be because of this [change on simple_tag on Django 1.9](https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape). Checking it out.

**Comment by tomchristie** [comment]
Okay, odd. Note that this is only against 1.9, which isn't yet on our supported list (it will be imminently tho, with the upcoming 3.3 release). The Django docs happen to be down ATM, so not easy to review what the change/cause is until it's back

**Comment by jarekwg** [comment]
These docs are still up though, if that helps. :)
http://django.readthedocs.org/en/latest/releases/1.9.html#simple-tag-now-wraps-tag-output-in-conditional-escape

**Comment by tomchristie** [comment]
See also #3550.
