### ISSUE TITLE
Create a django-rest-localflavor

### ISSUE THREAD

**Issue by gilsondev** [tomchristie/django-rest-framework#3552]
I'm have use the DRF to project, and need to create serializer fields, to parse and validate local data (e.g:  in Brasil is CPF, Zip Code, etc), and create a project to this, based in [django-localflavor](https://github.com/django/django-localflavor), the [drf-localflavor-br](https://travis-ci.org/hackultura/drf-localflavor-br).

But, I'm thinking if it is interesting create a localflavor to DRF too. What do you think about this?

**Comment by tomchristie** [comment]
Sounds like a great idea, yup. (For a third party project) We've some good guidelines in getting started with third party projects in the docs, and always happy to provide support in that area where poss. If you do decide to start one is suggest linking to it from this thread.

**Comment by gilsondev** [comment]
Ok. Thanks!
