### ISSUE TITLE
Assumes primary key called `id`, breaks HyperlinkedModelSerializer

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3555]
Does [this line](https://github.com/tomchristie/django-rest-framework/blob/3.3.0/rest_framework/serializers.py#L1134) assume now that the primary key of a model is called `id`?

In the past the `ModelSerializer` generated (In this case the primary key on the `Order` model is `order_id`):
```
order = PrimaryKeyRelatedField(read_only=True)
```

Now I get:
```
order = SlugRelatedField(read_only=True, slug_field='order_id')
```

The issue comes up in that if instead I use a `HyperlinkedModelSerializer`, I no longer get a hyperlink for that field.

**Comment by xordoquy** [comment]
@cancan101 it indeed looks like it assumes the PK to be "id" which doesn't look right.

**Comment by cancan101** [comment]
Looks like this was relatively recent PR: https://github.com/tomchristie/django-rest-framework/pull/3526/files.

**Comment by tomchristie** [comment]
Thanks for the report and the digging @cancan101!
