### ISSUE TITLE
BooleanField with modelSerializer

### ISSUE THREAD

**Issue by gabn88** [tomchristie/django-rest-framework#3557]
If you have a BooleanField on the modelSerializer, where on the model the BooleanField is defined as:

    models.BooleanField(blank=True, default=None)

The modelSerializer still parses it as False instead of None. ~~This is different from the ModelForm (which leaves it empty, so you can set it in the save method or anywhere else), and therefore unexpected.~~

It is the same as the modelForm. But still... I think that when you submit JSON, omitting the booleanfield alltogether, it should be null (as in unset), because I have literally specified blank=True, meaning that it should have required = False...

**Comment by xordoquy** [comment]
If you don't set null=True, default=None doesn't make sense.
Still the issue with DRF as opposed to Django forms is that we have more options, one being when the field is omitted which won't happen with a form.
Thus you should set required=False for this in the serializer.

**Comment by gabn88** [comment]
Okay, I have now solved it by using a NullBooleanField, but your way of doing it is much better, since it keeps the validation at database level the same. thank you!
