### ISSUE TITLE
Viewsets without a filter_class break Browser Viewer

### ISSUE THREAD

**Issue by ericholscher** [tomchristie/django-rest-framework#3559]
The `to_html` function doesn't check if the `cls` exists in this line:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L121

It should have logic checking for a `None`, similar to the above bit:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L112-L114

Causes this error when viewing those pages: `'NoneType' object is not callable`

**Comment by gabn88** [comment]
Just found the same issue :+1:

**Comment by jackmccloy** [comment]
:+1:
