### ISSUE TITLE
ListSerializer and ListField returning a proxy object in validation response

### ISSUE THREAD

**Issue by awbacker** [tomchristie/django-rest-framework#3563]
I upgraded to 3.3 and starting using the new ListField (and trying ListSerializer).  I have a series of "bad values" I test on, and in 3 of those 5 cases I get a `proxy` object back instead of a validation error message.

The test case looks like this:
```
# in the serializer
corner_points = serializers.ListField(child=serializers.IntegerField(), required=True)

# test case's invalid values, for one reason or another
test_cornerpoints = [   [1, 2, 3, 4, 5, 6, 7], [], ['abc'], 'efg', 1 ]
for cp in test_cornerpoints:
    self.api = APIClient()
   # also has an image, so this posts as multipart form-data
    resp = self.api.post(url, data={ 'corner_points': cp })  
    print(resp.data)
```

** I should mention that I have a custom validate_corner_points function ** I'm checking into that now, it just requires that the list length be divisible by 2.

And the output from the print statement above (the status code is 400)
```
{'corner_points': [<django.utils.functional.__proxy__ object at 0x1154b9090>]}
{'corner_points': [<django.utils.functional.__proxy__ object at 0x115232d10>]}
{'corner_points': [u'A valid integer is required.']}
{'corner_points': [u'A valid integer is required.']}
{'corner_points': [<django.utils.functional.__proxy__ object at 0x1153011d0>]}
```

Prior to this I was using a custom list serializer that handed the `field_name[]` format that arrays come in in FormData.  So far I think the new version is working with this, but the docs should make note that `request.POST` is gone now, and you can only use `requests.data`.  At least in my case, there were no values in `request.POST` for multipart/form-data.

**Comment by kylefox** [comment]
I ran into this issue while setting up token authentication, and haven't found a solution

From what I can tell the problem is not related to the auth system, but perhaps the serialization of lists:

```python
response = self.client.post('/api-token-auth/', {
            'username': 'test_user',
            'password': 'incorrect'})

print response.data
# {u'non_field_errors': [<django.utils.functional.__proxy__ object at 0x10302e390>]}

print response.data['non_field_errors']
# [<django.utils.functional.__proxy__ object at 0x10871e390>]

print response.data['non_field_errors'][0]
# u"Unable to log in with provided credentials."
```

**Comment by xordoquy** [comment]
@kylefox your issue is a non issue. print() is not be recursive, if you want the error message to show up, you'll probably want to print the json.dump(response.data).
I suspect the same applies with the OP where 2 of the responses are untranslated strings while the 3 "proxy" ones are translatable strings.

**Comment by kylefox** [comment]
@xordoquy I used `print` only for example's sake. In fact using `json.dumps` is how I discovered the problem in the first place:

```python
json.dumps(response.data)
# TypeError: <django.utils.functional.__proxy__ object at 0x108ea6d90> is not JSON serializable
```

**Comment by xordoquy** [comment]
ok, this it's not just a display issue.
Next step here would be to have a failing test case. OP's code is a good base to get one.

**Comment by jpadilla** [comment]
This looks like it might have been fixed already. @kylefox want to give master a try? https://github.com/tomchristie/django-rest-framework/pull/3908

**Comment by xordoquy** [comment]
@jpadilla good catch !

**Comment by kylefox** [comment]
@jpadilla Beautiful — you're absolutely correct, works as expected using the master branch. Thank you!!

@xordoquy does [this](https://github.com/tomchristie/django-rest-framework/milestones/3.3.3%20Release) mean we are close to a 3.3.3 release? :grinning: 

![image](https://cloud.githubusercontent.com/assets/37838/13611625/b9f8f8d0-e520-11e5-938f-cb55ae1efe7d.png)

**Comment by jpadilla** [comment]
@kylefox thanks for reporting back :fireworks:

**Comment by kylefox** [comment]
@xordoquy Just wanted to bump — any loose timeline for the 3.3.3 release? (#3925) I don't mean to be pushy :grin: and am happy to help if I can.

The reason I ask is, this issue is causing errors in our production environment. Pointing requirements.txt to a git commit (rather than a pinned PyPI release) has proven to result in unpredictable scenarios with the way our hosting provider handles buildpacks.

(I realize this is an issue with our hosting provider rather than django-rest-framework itself, which I'm working to fix. But in the meantime a 3.3.3 release would help me fix the immediate problem :smile: )

**Comment by kylefox** [comment]
Just a note to self/others — I now see that #3908 is part of the 3.4.0 release, not 3.3.3.
