### ISSUE TITLE
Partial updates always change fields that are not in data, read only, and have a default

### ISSUE THREAD

**Issue by melinath** [tomchristie/django-rest-framework#3565]
This is kind of an edge case, maybe? Maybe not. I ran into it because I have a field which is readonly on update but has a default for the create case.

See [Serializer._writable_fields](https://github.com/tomchristie/django-rest-framework/blob/322bda8/rest_framework/serializers.py#L344). I'm trying to do a partial update on one field, but I have another field that's readonly on update. BUT instead of being left alone, since it has a default, it always gets set TO THAT DEFAULT.

From my reading of writable_fields, it looks like this would happen with *any* field that has a default and isn't included in a partial update, but for it to happen on a read_only field seems particularly egregious to me. :-p

**Comment by melinath** [comment]
(My expectation would be that a partial update would only affect the fields that have data being sent their way.)

**Comment by tomchristie** [comment]
Is this still occurring against the latest release?

**Comment by melinath** [comment]
I tried upgrading to the latest stable release (3.3.1) and still had the issue, and I didn't see any changes between that and master in the relevant parts of the code.

**Comment by gcbirzan** [comment]
This is still present. The documentation ([3.0 announcement](http://www.django-rest-framework.org/topics/3.0-announcement/#the-required-allow_null-allow_blank-and-default-arguments), which is the only place I could find a reference to this) is also wrong: it doesn't mention that it'll only be used for read_only fields.

**Comment by tomchristie** [comment]
Milestoning to confirm against latest vesion.

**Comment by tomchristie** [comment]
Right - thanks for having raised this @melinath, and for having confirmed @gcbirzan.
Fix now incoming.

(Yay for now having a funded project where long-standing issues like this can finally get resolved!)

**Comment by MarkusH** [comment]
I just updated to a DRF 3.4.5 and noticed this change in behavior between 3.4.1 and 3.4.2. This change is breaking a couple of tests for us and is also changing the semantics of how defaults are treated in DRF.

May I ask to not have such backwards incompatible changes in patch releases in future versions. Thank you.

**Comment by tomchristie** [comment]
Sure. That's always a bit more gray when the behavior is classified as a bug, but yes I *do* think that we'll start being more cautious about *any* change that affects behavior, even in bug cases, and deferring those to major releases.

**Comment by MarkusH** [comment]
Thanks @tomchristie :smile:
