### ISSUE TITLE
render() must be called with a dict, not a RequestContext (RemovedInDjango110Warning)

### ISSUE THREAD

**Issue by jamesbeith** [tomchristie/django-rest-framework#3573]
Got the following warning on Django 1.9b1 whilst testing out the [Rendering HTML](http://www.django-rest-framework.org/topics/html-and-forms/#rendering-html) example.

```
.../python3.4/site-packages/rest_framework/renderers.py:171: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
  return template.render(context)
```

**Comment by tomchristie** [comment]
Okay, thanks for raising that.

**Comment by benred42** [comment]
I was looking into this and it appears to have been fixed in #3654.

**Comment by tomchristie** [comment]
Closing given above comment. Welcome to reopen if needed. Thanks @benred42.

**Comment by 2tunnels** [comment]
Getting the same warning when using class based view (TemplateView).
