### ISSUE TITLE
HTML form in generics.listCreateAPI is not taking values

### ISSUE THREAD

**Issue by hawksterdhruv** [tomchristie/django-rest-framework#3574]
When we try to submit json through the HTML form where the view is created with ListCreateAPI, it is not saving the values. If we save it using the application/json, it saves the values.
This was working fine in version 3.2.5 but it is not working in version 3.3.0

**Comment by xordoquy** [comment]
Is it possible to come with the simplest test case to demonstrate what doesn't work ?

**Comment by knoppo** [comment]
same here,
I'm able to reproduce this in a fresh install with a required charfield:

```python
# models.py
class Forum(models.Model):
    title = models.CharField(max_length=50)

# serializers.py
class ForumSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Forum
        fields = ('url', 'title')

# settings.py
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'PAGE_SIZE': 10,
}
```
I can post new data by using "Raw Data" with a media type "application/json", but "multipart/form-data" gives a **400 Bad Request** with a validation error `{"title": "field is required."}`

After some debugging I found out that when calling `DjangoMultiPartParser` a second time  (from `MultiPartParser`) it seems like the stream is already consumed. (parsers.py:114)

broke: drf 3.3.0, django 1.8.5
works: drf 3.2.5, django 1.8.5

**Comment by xordoquy** [comment]
Ok, this seems linked with the permission class.
Could reproduced the issue with the permission class set but it works when the permission isn't set.
