### ISSUE TITLE
API browser not displaying POST form

### ISSUE THREAD

**Issue by nfletton** [tomchristie/django-rest-framework#3578]
There seems to be an issue with the display of the POST form in the 3.3.0 api browser and it's related to the switch to using bootstrap tab panes in the browser base template.

In 3.2.5:
![selection_059](https://cloud.githubusercontent.com/assets/1591068/10861407/6f64fa3c-7f43-11e5-994d-89e72b0b4729.png)

In 3.3.0:
![selection_060](https://cloud.githubusercontent.com/assets/1591068/10861426/2215474a-7f44-11e5-9879-e78e7badbf51.png)

Adding an 'active' class to the tab-pane containing the POST form with DevTools results in the form displaying correctly.

**Comment by jpadilla** [comment]
@nfletton it'd really help to have some steps to reproduce this.

**Comment by avara1986** [comment]
For example, if i have this ViewSet:

```
class FooViewSet(viewsets.ModelViewSet):
    authentication_classes = (
        authentication.TokenAuthentication,
        authentication.SessionAuthentication,

    )
    permission_classes = (
        permissions.IsAuthenticated,
    )
    @list_route(methods=['post'], parser_classes=(MultiPartParser,))
    def foo_bar(self, request):
        ....
```
And send this request with Token Authorization from an external host:
```
POST /api/v1/foo/bar/ HTTP/1.1
Authorization: Token 628129ba5429fee459cf1e3b873a3fb8679e218b
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="msg"

test
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="attached"; filename="upload_test.txt"
Content-Type: text/plain
....
```
**request.data** return:

```
>> print request.data
<QueryDict: {u'msg': [u'test'], u'attached': [<InMemoryUploadedFile: upload_test.txt (text/plain)>]}>
```

But, if i send this request from a web form in the same host, with a started session.
```
POST /api/v1/foo/bar/ HTTP/1.1
X-CSRFToken:wTgUevurtyRQZW4yiiy4MyxH0UEeDdVO
Cache-Control: no-cache
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="msg"

test
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="attached"; filename="upload_test.txt"
Content-Type: text/plain

```
**request.data** return:

```
>> request.data
<QueryDict: {}>
```
But, **request.POST is not empty**:
```
>> print request.POST
<QueryDict: {u'msg': [u'test'], u'attached': [u'', u'']}>
>> print request.FILES
<MultiValueDict: {}>

```
If you need any further explanation, please let me know. :smiley: 

Thanks! :+1:

**Comment by tomchristie** [comment]
I'd suggest upgrading to 3.3.1 first and seeing if that resolves - if not then we'll consider looking into this further.

**Comment by avara1986** [comment]
Ok, it's solved :+1: 

Thanks a lot!

**Comment by tomchristie** [comment]
Great!

**Comment by nfletton** [comment]
Can we leave this one open? For me, 3.3.1 does not solve the original problem I reported.

I think the problem is that the POST form renders inside Bootstrap style tabs. In my scenario there's only one tab rendered by the template (tab-pane with id = post-generic-content-form) and as a consequence of the conditional code in base.html no Bootstrap tab markup is generated (i.e. the Nav tabs markup http://getbootstrap.com/javascript/#markup). Without the tab markup the code in default.js to activate a tab, has no effect. That JS code is:
```javascript
} else {
    // If no tab selected, display rightmost tab.
    $('.form-switcher a:first').tab('show');
}
```

I'll take a further look but I have not seen what historical change is causing this for me.

**Comment by xordoquy** [comment]
Closing this as #3600 was merged.
