### ISSUE TITLE
Why is HTTP_422_UNPROCESSABLE_ENTITY missing in rest_framework.status?

### ISSUE THREAD

**Issue by vakorol** [tomchristie/django-rest-framework#3587]
Status 422 suits very nice when one needs to return some kind of "processing/validation" error. Why is it missing in the `.status` module?

**Comment by xordoquy** [comment]
I assume it's because it's specific to webdav that DRF doesn't support.

**Comment by tomchristie** [comment]
Not part of the HTTP spec. I assume the original listing follows RFC2616, possibly with a couple of additions.

On review, its very marginally different from the updated HTTPbis spec... https://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-26#section-6
