### ISSUE TITLE
Values for nested serializer fields don't appear in admin browser

### ISSUE THREAD

**Issue by mcastle** [tomchristie/django-rest-framework#3594]
For example, if I have two HyperlinkedModelSerializers and nest one in the other, the value for the nested serializer does not appear in the admin List view nor in the admin Instance view of the Parent serializer. The values do appear, however, in the api view and json view.

**Comment by mcastle** [comment]
Nevermind. This was just fixed with v 3.3.1

**Comment by tomchristie** [comment]
Okay, good to hear.
