### ISSUE TITLE
Serializer.validate_parent doesn't trigger

### ISSUE THREAD

**Issue by robinchew** [tomchristie/django-rest-framework#3601]
Hello,

I have a model with a foreign key field named 'parent'. Serializer.validate_parent doesn't trigger on validation, probably to do with Serializer having an attribute also named 'parent'.

Kind regards,
Robin

**Comment by tomchristie** [comment]
Can you put together the minimum case required to replicate this?
Are you able to demonstrate the issue in a test case?

**Comment by robinchew** [comment]
Sorry, my mistake. In the middle of migrating to version 3.
