### ISSUE TITLE
api html - html form post fail

### ISSUE THREAD

**Issue by xhs3t7d** [tomchristie/django-rest-framework#3603]
i have 2 fields in my models: title, description. I am walking trough tutorial on 4 part. When i click on post button fields are EMPTY. This what i get: 
```
HTTP 201 Created
Content-Type: application/json
Vary: Accept
Allow: GET, POST, HEAD, OPTIONS

{
    "id": 8,
    "title": "",
    "description": "",
    "owner": "dima"
}
```

**Comment by xhs3t7d** [comment]
But when i try to edit these fields it saves succesfully (When i click PUT button
![screenshot from 2015-11-05 19-14-44](https://cloud.githubusercontent.com/assets/1331563/10974409/09873e14-83f3-11e5-8599-bf0f0c3ea3f3.png)
)

**Comment by xhs3t7d** [comment]
![screenshot from 2015-11-05 19-37-59](https://cloud.githubusercontent.com/assets/1331563/10974785/d0b90200-83f4-11e5-9d7e-abdd3ce53838.png)

**Comment by xhs3t7d** [comment]
views.py:

from django.contrib.auth.models import User
from snippets.models import Snippet
from snippets.serializers import SnippetSerializer
from snippets.serializers import UserSerializer
from snippets.permissions import IsOwnerOrReadOnly
from rest_framework import generics
from rest_framework import permissions

class SnippetList(generics.ListCreateAPIView):
	queryset = Snippet.objects.all()
	serializer_class = SnippetSerializer
	permission_classes = (permissions.IsAuthenticatedOrReadOnly, )

	def perform_create(self, serializer):
		serializer.save(owner=self.request.user)
		print 'test'

	def post(self, request, *args, **kwargs):
		print 'test2'
		return self.create(request, *args, **kwargs)


class SnippetDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = Snippet.objects.all()
	serializer_class = SnippetSerializer
	permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly,)


class UserList(generics.ListAPIView):
	queryset = User.objects.all()
	serializer_class = UserSerializer

class UserDetail(generics.RetrieveAPIView):
	queryset = User.objects.all()
	serializer_class = UserSerializer

**Comment by xhs3t7d** [comment]
models.py:

from django.db import models

# Create your models here.
class Snippet(models.Model):
	owner = models.ForeignKey('auth.User', related_name='snippets')
	created = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=100, blank = True, default='')
	description = models.TextField(blank=True, default='')

	class Meta:
		ordering = ('created',)

**Comment by xhs3t7d** [comment]
serializers.py:

from rest_framework import serializers
from snippets.models import Snippet

from django.contrib.auth.models import User

# class SnippetSerializer(serializers.Serializer):
# 	pk = serializers.IntegerField(read_only=True)
# 	title = serializers.CharField(required=False, allow_blank=True, max_length=100)
# 	description = serializers.CharField(required=False, allow_blank=True)

# 	def create(self, validated_data):
# 		return Snippet.objects.create(**validated_data)

# 	def update(self, instance, validated_data):
# 		instance.title = validated_data.get('title', instance.title)
# 		instance.description = validated_data.get('description', instance.description)
# 		instance.save()
# 		return instance


class SnippetSerializer(serializers.ModelSerializer):
	owner = serializers.ReadOnlyField(source='owner.username')
	class Meta:
		model =  Snippet
		fields = ('id', 'title', 'description', 'owner',)

class UserSerializer(serializers.ModelSerializer):
	snippets = serializers.PrimaryKeyRelatedField(many=True, queryset=Snippet.objects.all())
	class Meta:
		model = User
		fields = ('id', 'username', 'snippets',)

**Comment by xordoquy** [comment]
Please use the mailing list for usage questions.
Note that you're sending a POST with a code key which doesn't exist in the serializer.
