### ISSUE TITLE
Documentation for writing updates for ListSerializers should include "extra_kwargs = {'id': {'read_only': False},}"

### ISSUE THREAD

**Issue by jonathan-golorry** [tomchristie/django-rest-framework#3607]
The documentation for writing a custom ListSerializer uses book.id to determine matches between instances and validated data. It appears that the validation of ListSerializers calls the child Serializers' validation methods. This validation by default removes non-writable values from data, including any id information, making it impossible to match instances and validated data.

This is preventable by making the ID not read_only in the child serializer, but that is not documented or even included in the example (though it would have saved me a lot of time).

**Comment by Cheglader** [comment]
It looks like this was fixed with https://github.com/tomchristie/django-rest-framework/pull/3650

**Comment by xordoquy** [comment]
thanks @Cheglader !
