### ISSUE TITLE
error __init__() got an unexpected keyword argument

### ISSUE THREAD

**Issue by Six-wars** [tomchristie/django-rest-framework#3609]
I've upgraded all the django apps and on my website and djangorestframework which serves data to a mobile app crashed. The issue seems to end at simplejson http://stackoverflow.com/questions/33562605/django-rest-framework-simplejson-error-init-got-an-unexpected-keyword-argu

**Comment by xordoquy** [comment]
simplejson 3.3.1 doesn't have the fix. This isn't related to Django REST framework.
