### ISSUE TITLE
validation errors possibly due to unique_together

### ISSUE THREAD

**Issue by richardjmarini** [tomchristie/django-rest-framework#3611]
Being trying to trace down this issue for a few days now.  I've been using the below model and serializer for a few months now: 

```python
class UserRelationship(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4,editable=False)
    user_profile = models.ForeignKey(UserProfile,  related_name= 'relations')
    related_profile= models.ForeignKey(UserProfile, related_name='related')
    relationship = models.ForeignKey(Relationship, related_name= 'related_relationships')
    class Meta:
         db_table= 'user_relationship'
         unique_together= (('user_profile', 'related_profile'), )

class UserRelationshipSerializer(HyperlinkedModelSerializer):
    class Meta:
        model = UserRelationship
        fields = (
            'id',
            'url',
            'user_profile',
            'related_profile',
            'relationship',
            'guardianship_flag'
        )
        read_only_fields= ('guardianship_flag',)
```

However, all of a sudden I started getting the following validation errors from the serializer:

```python
related_profile": ["This field is required."], "user_profile": ["This field is required."]}
```

It only occurs after a second post to it's view.  If I restart the API it works fine once -- then I get the above error after the second post.   

I was running 3.1.3 and tried upgrading to 3.3.1 as well and have the same issue. 

The fields are indeed populated.  I followed the data down through the run_validators method.   It seems these fields are somehow winding up with a read_only= True which then causes the below lines of code to ignore them (but only the second time I POST after the API has been restarted -- so I'm also assuming this has something todo with it being a cached property):

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L343-L348
 
I tried forcing read_only= False via the serializers extra_kwargs property:

```python
extra_kwargs= {'user_profile': {'read_only': False}, 'related_profile': {'read_only': False}}
```

but this gives me bizarre results.  I still get the "This field is required" error except it then shows fields intermixed with fields from the user_profile model.   

It seems this issue may be related to the following issues in some way as well:

https://github.com/tomchristie/django-rest-framework/issues/2848
https://github.com/tomchristie/django-rest-framework/pull/2796
https://github.com/tomchristie/django-rest-framework/issues/3598

which all touch on one aspect or another of it but I just can't seem to narrow it down further.  I tried overriding various methods (`validate_<field>`, `to_internal_value`, etc..) to try and work around it -- but I keep running ending up dead end.

**Comment by xordoquy** [comment]
Hi,

This seems fairly complex to reproduce. Could you come with a simple test case to help us reproduce the issue ?

**Comment by richardjmarini** [comment]
Yes, I'll post a simple example in a few days.  As another component to this (which maybe our usage) we're also dynamically modifying the serializer's parameters (such as depth) which will allow consumers of our API to pull in to hyperlinked related structure when they desire. On some models we do have unique constraints which include "required" fields.  However, when using the depth parameter the nested representation becomes "read_only" and therefore raises a "May not set both 'read_only' and 'required' error via an assertion Field.__init__().  In any event, I'll post a simpler example of what we're experiencing (in the original post above) soon.  Thanks.

**Comment by richardjmarini** [comment]
I'm going to close this issue since the core of it was an implementation side on our end and the issue that popped up as a result of that is already an open issuke labelled as bug 2848 and therefore the one I opened is a duplicate issue.. We've built a rather complex CRM with DRF for which we dynamically modify the serializer based on the user that's consuming the API. This not only includes modifying which field a  user has access to but also the depth.  Since the depth is part of the Meta class one users request would modify the meta class

**Comment by xordoquy** [comment]
@richardjmarini thanks for your analysis and your feedback about this.
