### ISSUE TITLE
When/ Why use APITestCase over the normal TestCase that ships w/ django?

### ISSUE THREAD

**Issue by toranb** [tomchristie/django-rest-framework#3613]
@tomchristie I'm helping mentor a team and noticed our lead django engineer was using APITestCase instead of TestCase and I wanted to ask when you would consider this a good use case. "back in my day" we didn't have or use this api so I'm curious about it's value-add /etc

I tried to do my homework by reading over the history/commits about this but it's still less /(un) clear for a "hobbyist" django developer like myself :)

https://github.com/tomchristie/django-rest-framework/commit/ae63c49777f4d5b766b85a4b28f6328bd6f9516a

**Comment by tomchristie** [comment]
Use it if you want to:

* Use `.format` to more simply send encoded data.
* Use `.force_authenticate` to provide authentication credentials on every request.

Otherwise I believe there's no difference.

**Comment by tomchristie** [comment]
Possibly worth documenting more clearly tho.

**Comment by toranb** [comment]
Thanks @tomchristie !!!!
