### ISSUE TITLE
Nested serializers aren't recognized as read_only in the HTML input form

### ISSUE THREAD

**Issue by jonathan-golorry** [tomchristie/django-rest-framework#3615]
I have a serializer with a field that is a list of subobjects (specified by `subobjects=SubobjectSerializer(many=True, required=False)`). The subobjects field has the extra_kwargs `'subobjects': {'read_only': True}`. The serializer's `create` method creates the subobjects, not needing any data for them.

The bug is that the html input form isn't recognizing that the subobjects field is read-only and thus is still displaying the `Subobjects: Lists are not currently supported in HTML input.` warning and throwing a TypeError exception upon creation because `"subobjects": []` is being passed to the object creation and is not an explicit field in the object (it is the related_name of the foreignkey field of the subobject).

Edit: Just remembered this is version 3.2.4. I would check a newer version but am using this version due to a bug in the 3.3.0.

Edit2: This appears to be true for all nested serializers. Updating title.

**Comment by xordoquy** [comment]
IIRC extra_kwargs don't work with explicitly defined fields as all the definition should go in one single place. Maybe we should make it more explicit in the docs though.
