### ISSUE TITLE
Turn off paginator 

### ISSUE THREAD

**Issue by pcompassion** [tomchristie/django-rest-framework#3617]
http://djangorestframework.readthedocs.org/en/latest/api-guide/pagination/ says

 > Note that using a paginate_by value of None will turn off pagination for the view.

But correct way for current version seems `paginator = None`

**Comment by xordoquy** [comment]
Thanks !

**Comment by xordoquy** [comment]
mm, turns out the readthedocs are out of date.

**Comment by xordoquy** [comment]
I opened #3618 about that, the documentation on read the docs is based on an out of date fork (https://readthedocs.org/projects/django-rest-framework/).
The reference remains http://django-rest-framework.org/
