### ISSUE TITLE
Browsable API doesn't show lookup fields 

### ISSUE THREAD

**Issue by tezro** [tomchristie/django-rest-framework#3619]
Hi, I might be doing something wrong, but I cant get the lookup fields to show in the browsable API. I have django-filter and django-crispy-forms installed. Both of them are listed in the INSTALLED_APPS.

That's the viewset:

```
class EventsViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Event.get_current()
    serializer_class = EventSerializer
    filter_backends = (filters.DjangoFilterBackend,)
    filter_fields = ('venue',)
```

That's the serializer:

```
class EventSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Event
```

The browser shows all the objects perfectly fine, but not the filter input for "venue". Am I doing something wrong?

Thanks ahead.

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by tezro** [comment]
Yeah sure, no worries. I just thought it might be a bug.

**Comment by xordoquy** [comment]
@tezro If you think there's a bug we'll need more context. There's no mention of the DRF/django/python version for example. Does it work for other filter fields ?
We do have a couple of user related issue and can't afford to spend time digging through things that turns to be out of the DRF scope.

**Comment by tezro** [comment]
DRF latest, 3.2.5. Django 1.8. Python 2 latest. I mean I'm not completely sure it's bug, but I'm just following the docs and it's not really working. Should work as designed for the ReadOnlyModelViewSet?

**Comment by xordoquy** [comment]
It's something new to 3.3.x

**Comment by tezro** [comment]
Ok, got it. My bad. It works perfectly with 3.3. Thanks for help!
