### ISSUE TITLE
Read the Docs Disabling Pagination Erroneous Instructions / GitHub Documentation Missing Information

### ISSUE THREAD

**Issue by Aldarn** [tomchristie/django-rest-framework#3620]
When attempting to find out how to disable pagination for a specific view, a quick google search returns the `Read the Docs` documentation with out of date instructions at http://djangorestframework.readthedocs.org/en/latest/api-guide/pagination/. This page states:

> Note that using a paginate_by value of None will turn off pagination for the view.

However this is no longer the case. As far as I can tell, this documentation may no longer be supported given the documentation available on the DRF homepage and the fact it is no longer linked to from GitHub - but this is non-obvious when arriving on that page. Additionally there are no instructions for disabling pagination for a particular view in the DRF homepage documentation. 

If it is the case that this documentation is no longer supported, I promose a clear statement is placed at the top of the page stating this with a link directly to the currently maintained documentation. Additionally instructions on disabling pagination for a particular view should be added to the DRF homepage documentation on the `Filtering` page (http://www.django-rest-framework.org/api-guide/filtering/).

Cheers,
Aldarn

**Comment by xordoquy** [comment]
This site is out of control of the django rest framework team. Please refer to http://django-rest-framework.org/

**Comment by Aldarn** [comment]
OK that is fine, but as I mentioned turning off pagination is not even mentioned on the official documentation.

**Comment by tomchristie** [comment]
I believe it'd be reasonable to open a ticket for docs with "turning off pagination for a specific view".
You're right - we note how to set pagination explicitly per-view but don't make it clear that setting to `None` is also valid to turn it off for specific views only.

**Comment by xordoquy** [comment]
Done in #3621
