### ISSUE TITLE
Status code "200 No Content" on DELETE Method 

### ISSUE THREAD

**Issue by H0neyBadger** [tomchristie/django-rest-framework#3622]
I have a strange behavior when I call the DELETE method.
The api didn’t return the right status code = ***204***

The browsable API display the correct status "***HTTP 204 No Content***"
```
HTTP 204 No Content
Content-Type: application/json
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Vary: Accept
```

However, we can read the status code ***200*** in apache logs
```
"DELETE /accounts/drf_dev/ HTTP/1.1" 200
```

I got this issue with ```APITestCase  client.delete()```  and ```curl --request DELETE```.

Did I miss something with the status codes?

djangorestframework==3.3.1
Django==1.8.6

**Comment by tomchristie** [comment]
The browsable API content will masquerade as 204, but actually return a 200 (otherwise the page simply won't display). If any other renderer is used then you'll actually see a proper 204 response.

**Comment by H0neyBadger** [comment]
Thanks a lot @tomchristie,

```
curl --request DELETE -I \
"http://localhost:8080/accounts/drf_dev/" \
--header "Content-Type: application/json" \
--header "Accept: application/json" \
```
```
HTTP/1.0 204 NO CONTENT
Date: Tue, 10 Nov 2015 14:12:47 GMT
Server: WSGIServer/0.2 CPython/3.4.2
Allow: GET, DELETE, HEAD, OPTIONS
Vary: Accept, Cookie
Content-Length: 0
X-Frame-Options: SAMEORIGIN
```

**Comment by cnobile2012** [comment]
So I consider this a bit counter-intuitive. What needs to happen is to send a JSON mimetype in the `Accept` header to get a 204 instead of a 200 response when a good engineer knows full well that there should never be data returned with a 204 status.

**Comment by xordoquy** [comment]
@cnobile2012 I'm missing your point. You're getting some content with a 200 HTTP code when using the browsable API because it has content and a 204 HTTP code if it's JSON because there's no content returned.

**Comment by xordoquy** [comment]
@cnobile2012 I think you misread my comment. At this point, a failing test case to demonstrate the issue is required.
As far as I can see, DRF does not return a body when the HTTP code is 204.

**Comment by cnobile2012** [comment]
OK, so the `destroy` method, if not overridden, by default returns a 204, however, when I access the endpoint with an AJAX call I get a 200 with, by-the-way, HTML data. The issue I see is that I should not need to tell the endpoint that I want JSON data if I'm getting a 204, but I don't get a 204 I get a 200. Why is the DRF changing what is in the `destroy` method?  The default should be a 204, not a 200. Why is the DRF mucking with the return status when it is clearly being set to a 204?

**Comment by xordoquy** [comment]
> The default should be a 204, not a 200

I'd be interested in a more detailed explanation about that.
The [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.5) says:

> If a DELETE method is successfully applied, the origin server SHOULD send [...] a 200 (OK) status code if the action has been enacted and the response message includes a representation describing the status.

This is exactly what happens when you send an AJAX request that accepts HTML in return: the browsable API returns a representation of the status.

**Comment by rpkilby** [comment]
Hi @cnobile2012. By default, [DRF is configured](https://github.com/encode/django-rest-framework/blob/0ab527a3df39e344904f1e6543d76b6ce9b45c61/rest_framework/settings.py#L33-L36) to preference the JSON renderer over the browsable API. If you're getting an HTML response from the browsable API, then one of two things is happening:
- The ajax request has the `Accept: text/html` header set, which (via content negotiation) is specifically selecting the browsable API as the renderer.
- The ajax request hasn't explicitly set the `Accept` header, and is defaulting to `Accept: */*`. In this case, content negotiation defaults to the first renderer in the view's renderer list. This can either be set directly on the view's `renderer_classes` list, or the `DEFAULT_RENDERER_CLASSES` setting.

Without seeing your project, it's not really possible to tell you why you're getting a response from the browsable API instead of the JSON renderer. That said, DRF's default configuration should be correct.

**Comment by cnobile2012** [comment]
@xordoquy In [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.5) &#167; 4.3.5 Says:

> If a DELETE method is successfully applied, the origin server SHOULD
> send a 202 (Accepted) status code if the action will likely succeed
> but has not yet been enacted, a 204 (No Content) status code if the
> action has been enacted and no further information is to be supplied,
> or a 200 (OK) status code if the action has been enacted and the
>  response message includes a representation describing the status.

So clearly there are three choices for a delete. The DRF has decided on a 204 in the `destroy` method. (The DRF really only had two choices a 200 with a representation or a 204 without a representation. The 202 is only for async operations which is rare, but I have done this, though not in this case.)
```
class DestroyModelMixin(object):
    """
    Destroy a model instance.
    """
    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return Response(status=status.HTTP_204_NO_CONTENT)

    def perform_destroy(self, instance):
        instance.delete()
```

This is what I would expect to get from an external client, not the browsable API. It's perfectly fine to mung it for the browser API, but not for an external client, but it seems the DRF has done the exact opposite.

Do you understand where I'm coming from?

@rpkilby You need to read all the previous posts, I don't think you got the jist of the conversation.

**Comment by tomchristie** [comment]
> when I access the endpoint with an AJAX call I get a 200 with, by-the-way, HTML data.

You’ll only see that if your AJAX call is including an Accept: text/html header.

By default you’ll get a standard 204 and no data. (no accept header, accept: *, or accept: application/json)

I’d start by double checking the requests you’re sending in the dev console, and making sure they really are as you expect.

If you’re still seeing that behaviour then I’d suggest: 1. show us a screenshot of the request and response so we can see exactly what they both look like 2. show us what your renderer classes configuration looks like. 👍

**Comment by cnobile2012** [comment]
My original AJAX request was:

```
      const jqXHR = $.ajax({
        url: url,
        type: 'DELETE',
        timeout: 30000 // 30 seconds
      });
```

This returned a 200 with HTML. The only way I could get it to work was to change the above to:

```
      const jqXHR = $.ajax({
        url: url,
        type: 'DELETE',
        dataType: 'json',
        accepts: {json: mimetype},
        converters: {'text json': $.parseJSON},
        timeout: 30000 // 30 seconds
      });
```

So my point is that it shouldn't be necessary to tell the API that I want a JSON object if by default a 204 is returned with no representation of any kind. The only thing that would ever need an HTML representation is the browsable API.

Humm, just thought of something. I wonder if I passed empty objects for the `dataType`,  `accept`, and `converters` if `JQuery.ajax()` would do the right thing? I'll give that a try.

I'm in the US and it's late for me, so it must be real late for you guys.

**Comment by zebra-f** [comment]
I will refresh this issue, forget about the browser, but why on earth is the client from `rest_framework.test.APITestCase` also returning a 200 status code? I have to use the header to get 204:
```
response = self.client.delete(
    url,
    headers={
        "Accept": "application/json",
    },
)
```
This (
```
response = self.client.delete(url)
```
) should return 204 and have configures this header by default.  
Which bring me to next question, do I have to include `Accept` header for each method (`get`, `post` etc.)?
