### ISSUE TITLE
breaking data attribute change from api_view request

### ISSUE THREAD

**Issue by kaungst** [tomchristie/django-rest-framework#3623]
using Django 1.8.6, djangorestframework 3.3.1(though it is also true in 3.3.0).

a sample project
https://github.com/kaungst/wanda

runserver and hit the endpoint /polls/ to see the value of request.data

I believe it should be a QueryDict with only the body information, not a QueryDict with a key: value '_content': <body> with the <body> of type unicode.

If this is intended, seems like it should have been in the change log?

**Comment by kavirajk** [comment]
@kaungst I have tested your app as mentioned above. But it seems like its working as expected. request.data is QueryDict with only the body information. 

Can you more specific about the steps? I have tried with both python2.7 and python3.5 with django 1.8.6 and drf 3.3.1

If possible can you share the screenshot of request.data?

**Comment by tomchristie** [comment]
Closing pending reproducible case.
Thanks @kavirajk!

**Comment by irhs** [comment]
I was able to reproduce this case on Ubuntu 14.04 python3.4.2 with django 1.9 and drf 3.3.2 served by apache 2.4.7. If I test with 'python manage.py runserver'  on locally request.data is just the json body, as expected. But when running django with apache 2.4.7 request.data is as shown below.

JSON:
`
{
  "firstName": "John"
}
`

request.data:
`
{
    "_content_type": "application/json",
    "_content": "{\r\n  \"firstName\": \"John\"\r\n}"
}
`

**Comment by xordoquy** [comment]
Sounds like an Apache misconfiguration. I don't seem to face this issue with apache / mod wsgi

**Comment by irhs** [comment]
@xordoquy You are right. It was an Apache misconfiguration. Thanks for checking it on your end.

**Comment by kaungst** [comment]
@xordoquy @tomchristie @kavirajk 
I would bet this was my issue as well. We had some other apache misconfiguration issues, and in fixing those the problem seems to have gone away. Apologies for the delayed response, thanks for looking into it @kavirajk!

**Comment by ladyrassilon** [comment]
I'm currently experiencing this with both apache and the dev server with 
Django 1.9.2, and DRF 3.3.2.

I'm doing a JSON patch, 

this is what's being passed into the serializer as data
{
    'data': <QueryDict: {
        u'_content_type': [u'application/json'], 
        u'_content': [u'{"id":1,"csrfmiddlewaretoken":"wRA11YmQYiZHttSz0vaVRu9DrPTV31Nb","name":"hope.jpeg","visibility":"1","attachmentType":"108"}'], 
        u'_method': [u'PATCH']}>, 
        'partial': False, 
        u'context': {u'view': <borrower.views.library.DocumentAttachmentViewSet object at 0x104208f90>, u'request': <rest_framework.request.Request object at 0x10421bc10>, u'format': None}}

**Comment by tomchristie** [comment]
@ladyrassilon We no longer support the `_content_type`/`_content`/`_method` overloading style... http://www.django-rest-framework.org/topics/3.3-announcement/#deprecations

**Comment by sandeshnaroju** [comment]
I am facing the same issue in apache server. Django 1.8.17 and DRF 3.5.
Can any body tell me how to configure apache ? @irhs

**Comment by xordoquy** [comment]
@sandeshnaroju The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place for usage questions. Thanks!

**Comment by sandeshnaroju** [comment]
Thank you friend @xordoquy

**Comment by rohit2503** [comment]
Hi , 
I have a very weird error like this 

{"error_structure": null, "version": "1.1", "id": "25", "error": {"message": "AttributeError: 'int' object
 has no attribute 'encode'", "code": 100, "name": "JSONRPCError"}}

Same code runs perfectly fine locally but when deployed on apache httpd-2.4.29-1.x86_64. It throws above error. Do you guys have any idea what might have gone wrong with apache/mod_wsgi configuration.

**Comment by xordoquy** [comment]
@rohit2503: the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
