### ISSUE TITLE
Allow "search_fields" to be changed in SearchFilter

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#3625]
Right now `SearchFilter` expects to load the list of fields that will be searched on [from an attribute on the view called `search_fields`](https://github.com/tomchristie/django-rest-framework/blob/95f92e995c7c2822f3a6483a86f45ada34684c22/rest_framework/filters.py#L158-L159). There is no way to change this without copy/pasting all of `filter_queryset` and `to_html` which is not ideal.

I suggest allowing subclasses to change the value along the lines of `search_param`:
```python
class SearchFilter(BaseFilterBackend):
    # The URL query parameter used for the search.
    search_param = api_settings.SEARCH_PARAM
    search_fields = 'search_fields'
```

This change will allow using `SearchFilter` multiple times on the same view but having different fields searched.

**Comment by awwester** [comment]
working on this on topic branch https://github.com/awwester/django-rest-framework/tree/ticket_3625

**Comment by tomchristie** [comment]
I don't understand the motivation here.
You want to change the property name - why?

**Comment by awwester** [comment]
hmm I might have jumped the gun on this one. It seemed to make sense if you have many filters inherited from SearchFilter and wanted to apply the filters without rewriting the `search_fields` manually - however you're right - that would still work by just using `search_fields` on each SearchFilter class. We'll see if @cancan101 has some more input.

**Comment by tomchristie** [comment]
Going to close this off on current judgement.

**Comment by cancan101** [comment]
The issue that I ran into here is having the ability for two different search parameters on a given view. For example `search=XXX` to filter using one set of fields and `find=YYYY` to filter a different set of fields. At present I can customize the name of the query parameter but because the string `search_fields` is hard coded, there is no easy way to provide two different lists of fields.

**Comment by cancan101** [comment]
To make this concrete, I have a model `Person` with a `name_first`, `name_last` and `role`.

I would like to have:
```python
class PersonViewSet(....):
    queryset = Person.objects.all()
    serializer_class = PersonSerializer
    search_fields0 = ('^name_first', '^name_last', )
    search_fields1 = ('role', )
    filter_backends = (MySearchFilter(search_param='s0', search_fields_name='search_fields0'),
        MySearchFilter(search_param='s1', search_fields_name='search_fields1'))
```

**Comment by tomchristie** [comment]
I'm going to be annoying and push this into the category of "use a custom SearchFilter" if you want custom behavior. Sorry :-|

**Comment by cancan101** [comment]
@tomchristie That is the approach I have taken here, but because of how the code `SearchFilter` is structured, it just results in some copy and pasting.

**Comment by tomchristie** [comment]
Indeed.
