### ISSUE TITLE
Hyperlink Class Cannot Be Pickled

### ISSUE THREAD

**Issue by mlavin** [tomchristie/django-rest-framework#3628]
Related to #3350, the `rest_framework.relations.Hyperlink` instances cannot be pickled as demonstrated with this sample:
```
>>> import pickle
>>> from rest_framework.relations import Hyperlink
>>> link = Hyperlink('http://example.com', 'test')
>>> pickle.loads(pickle.dumps(link))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: __new__() missing 1 required positional argument: 'name'
```
For serializers which use the hyperlink relations, this breaks the caching of the response objects since most of the cache backends rely on pickle by default.

**Comment by xordoquy** [comment]
Thanks a lot @mlavin. I think this can be linked to another issue where cache was failing with a similar message though we were not able to identify where it did come from.

**Comment by Cheglader** [comment]
Hi @xordoquy, I would like to start contributing. Can I try this issue? I have solved @mlavin 's specific case by implementing the __getnewargs__() method https://docs.python.org/3.1/library/pickle.html#pickle.object.__getnewargs__  in https://github.com/Cheglader/django-rest-framework/commit/44a3d41ce928f10f719a84d4f4286a363ef33d15 , but I've yet to write a test case.

**Comment by xordoquy** [comment]
Hi @Cheglader, thanks for working at it. Looking forward to your pull request :)

**Comment by glynjackson** [comment]
Same issue using ''HyperlinkedIdentityField`` +1

**Comment by jpadilla** [comment]
I'd be great if anyone having this issue could give @Cheglader's PR #3701 a try.

**Comment by glynjackson** [comment]
This is my example code that fails.

```
class TestSerializer(serializers.HyperlinkedModelSerializer):
    url = serializers.HyperlinkedIdentityField(view_name='detail')
```

Error:

```
TypeError at /v1/vendor
__new__() takes exactly 3 arguments (2 given)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/v1/vendor
Django Version:	1.8.4
Exception Type:	TypeError
Exception Value:	
__new__() takes exactly 3 arguments (2 given)
Exception Location:	/Users/glyn/Documents/workspace/shortbite/django-env/lib/python2.7/site-packages/django/core/cache/backends/locmem.py in get, line 54
Python Executable:	/Users/glyn/Documents/workspace/shortbite/django-env/bin/python
Python Version:	2.7.8
```

**Comment by glynjackson** [comment]
@jpadilla yep @Cheglader's PR #3701 works for me! I'm using memcache and this has been a real pain. Any idea if/when the PR will be accepted?
