### ISSUE TITLE
mixins.CreateModelMixin causes timeout

### ISSUE THREAD

**Issue by variable** [tomchristie/django-rest-framework#3630]
This is a follow up of https://github.com/tomchristie/django-rest-framework/issues/3629

Somehow, if I add <code>mixins.CreateModelMixin</code> to the view class, see below:

```python
class GoPermissionViewSet(mixins.CreateModelMixin, mixins.ListModelMixin, mixins.RetrieveModelMixin, mixins.UpdateModelMixin, mixins.DestroyModelMixin, viewsets.GenericViewSet):
```
Above is effectively the same as extending <code>viewsets.ModelViewSet</code>

That, will cause the view to go through all the user records (in my case 1+ million).

The work around is to manually specify a custom user serializer

```python
class GoPermissionSerializer(serializers.ModelSerializer):
    user = UserSerializer()

    class Meta:
        model = GoPermission
```

What it seems to me is the <code>CreateModelMixin</code> is playing up with User model.

**Comment by xordoquy** [comment]
There's nothing tangible we can test or analyse here.
Please identify where the real bottleneck in Django REST framework is before reopening.
