### ISSUE TITLE
Document how to register function based API views in url route in the API docs

### ISSUE THREAD

**Issue by auvipy** [tomchristie/django-rest-framework#3633]
currently I found no reference for this looking at views and routes documentation.

**Comment by xordoquy** [comment]
Routers work with `ViewSet` while function based view only inherit from APIView.
This isn't a documentation issue.

**Comment by auvipy** [comment]
then how should I map that on router? register the function based view in router instead of viewset?

**Comment by xordoquy** [comment]
I can't think of a simpler way then to write your own router for that.

**Comment by auvipy** [comment]
then DRF should have built in solutions/guides for that :)

**Comment by auvipy** [comment]
@tomchristie what do you think?

**Comment by xordoquy** [comment]
Thoughts about that:
1. It's simple enough to write a ViewSet
2. It's fairly complex to figure that a single function can handle the 5 actions a `ViewSet` can do: list / create / show / update / delete.

Maybe create a 3rd party could solve this issue, I saw a similar question on SO this week.

**Comment by auvipy** [comment]
without binding in router, how should I handle function based API view in? how can I expose them in url?

**Comment by tomchristie** [comment]
We don't support function based views with routers, and I wouldn't want us to either.

If the custom `@detail_route`/`@list_route` decorators don't fit what you need then I'd suggest configuring the view in the URL conf explicitly.

**Comment by auvipy** [comment]
like normal django views right?

**Comment by tomchristie** [comment]
Yup

**Comment by auvipy** [comment]
thanks for clarification. A little indicator to this in the doc will really save both my and your precious time i guess :)

**Comment by AlJohri** [comment]
Gotta agree with this one. Had no idea how to register the function based views in urls.py.

**Comment by rizplate** [comment]
I agree with original OP, i know its recommended to write model and model serialized and viewset etc, however many cases do not fall neatly in these categories.

sometime people just want to write a handler to parse posted json, and all the urls patterns do not fall neatly into imaginary, best-practices patterns made up by someone's opinion. 

many of the functions or internal interactions of mixing, view sets , get_object etc are not obvious to someone from outside.

I know you all developers working on it know a lot, but community is sponsoring this project so if you have knowledge put it in documentation, otherwise someone else will fix those issues and crate a better project .

**Comment by auvipy** [comment]
@rizplate pr with suggested changes are wellcome

**Comment by rpkilby** [comment]
> Gotta agree with this one. Had no idea how to register the function based views in urls.py.

Hi @AlJohri, API views are an extension of standard Django views. As far as I understand it, there isn't anything special required to add them to your app's `url_patterns`.

----

> I agree with original OP, i know its recommended to write model and model serializer and viewset etc, however many cases do not fall neatly in these categories.

Hi @rizplate, these classes are recommended in so far as they reduce the amount of boilerplate necessary to create fully functional sets of views that map to your database models. Beyond that, there is no recommendation on the correct way of using the framework. 
That said, certain classes provide certain functionality, and they integrate accordingly. For example, the `ViewSet` is designed to be registered with a `Router`, and a `Router` outputs a set of url patterns that are suitable for Django's URL config. `APIView`/`@api_view` are simple extensions of existing Django view classes/functions and don't need or have the ability to be registered with a `Router`. 

> who is in charge of this project, can we change the documentation or create a fork to change the way simple things are handled.

There is a team of ~5 maintainers, including the original project creator. Documentation PRs are always welcome. If you'd like to see changes made to this project, there is an established [process](http://www.django-rest-framework.org/topics/contributing/) for contributing. Keep in mind that a lot of changes aren't accepted into the core framework, as they're better suited as a [third party package](http://www.django-rest-framework.org/topics/third-party-packages/).

**Comment by wdifruscio** [comment]
Bump :)

**Comment by xordoquy** [comment]
I'm locking this thread as it serves no purpose to just bump this issue.
If anyone wants a documentation improvement we'll consider PR about it based on their own merit.
I'm not really inclined to see DRF documentation duplicate content from Django's documentation such as [how to configure urls](https://docs.djangoproject.com/en/2.2/topics/http/urls/) but I'm fine to improve the documentation if that part isn't clear enough.
