### ISSUE TITLE
Relation fields no to_fields attribute attribute break serializer

### ISSUE THREAD

**Issue by martinhill** [tomchristie/django-rest-framework#3634]
Hello,

I have a ModelSerializer for the django-taggit package's Tag model. With DRF release 3.3.1 it began failing with `AttributeError: 'TaggableManager' object has no attribute 'to_fields'`.

I believe [this line](https://github.com/likeon/django-rest-framework/blob/322bda815969a49140ed02cab304e13e63b059d5/rest_framework/utils/model_meta.py#L95) from [PR 3526](https://github.com/tomchristie/django-rest-framework/pull/3526) assumes all relation fields have a to_fields attribute, but taggit's TaggableManager is an example of one that doesn't.

Replacing it with
```
    return field.to_fields[0] if hasattr(field, 'to_fields') else None
```
seems to solve the problem.

**Comment by xordoquy** [comment]
Seems sensible to me.

**Comment by jpadilla** [comment]
@martinhill wan't to put a PR together with your proposed changes?

**Comment by martinhill** [comment]
be happy to!
