### ISSUE TITLE
No submit button with Django-filters + Crispy forms

### ISSUE THREAD

**Issue by nanuxbe** [tomchristie/django-rest-framework#3636]
When using DjangoFilterBackend (might happen with other backends too but I didn't get a chance to test it) and crispy forms is installed, filter forms have no `Submit` button.

See attached screenshot:
![image](https://cloud.githubusercontent.com/assets/1215070/11168223/04919770-8b86-11e5-89d0-f92e77e99a71.png)

**Comment by xordoquy** [comment]
@nanuxbe thanks for the report. Do you have some sample project we could test against ? If not I'll set one up.

**Comment by nanuxbe** [comment]
@xordoquy this is highly pre-alpha but I just pushed https://bitbucket.org/levit_scs/djember_back, this is the project the screenshot is taken from. It is tested under python 3.5 (which I didn't mention in the initial report)

To reproduce:
- copy `environ.py.dist` to `environ.py` and edit to fit your local settings. (Postgres database is required)
- uncomment `crispy_forms` from `INSTALLED_APPS` in `settings.py`

The only api implementing filters so far is available at http://localhost:8000/api/v1/postalcodes/

**Comment by xordoquy** [comment]
@nanuxbe thanks a lot, will look at this today

**Comment by jpadilla** [comment]
@nanuxbe So the problem here is that `PostalCodeFilter` inherits from `django_filters.FilterSet` instead of [`rest_framework.filters.FilterSet`](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L28).

@tomchristie @xordoquy should people inherit instead from `rest_framework.filters.FilterSet` if they want their filter forms in HTML views?

**Comment by nanuxbe** [comment]
@jpadilla thanks :smile: 

If inheriting from `rest_framework.filters.FilterSet` is the way to go then the documentation [here](http://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend) needs to be updated.

**Comment by carltongibson** [comment]
The Crispy Forms `FormHelper` is not set on the `form` for a `django_filters.FilterSet` subclass. (This is what `rest_framework.filters.FilterSet` does.) 

**But** the selected template assumes that a `FormHelper` will be present if crispy forms is installed. We could make that check at runtime [when rendering the form](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/filters.py#L128)
