### ISSUE TITLE
Crispy Forms CSRF token error

### ISSUE THREAD

**Issue by nanuxbe** [tomchristie/django-rest-framework#3637]
Crispy forms default to POST method resulting in a CSRF Token exception when trying to use filters + crispy forms (submitting the form by hitting \<enter\> since there is no submit button, see #3636)
.

When initially rendering an API page with filters and crispy forms, the server also spits out this error (probably because crispy forms is trying to add the token to the form):
```venv/lib/python3.5/site-packages/django/template/defaulttags.py:66: UserWarning: A {% csrf_token %} was used in a template, but the context did not provide the value.  This is usually caused by not using RequestContext.```

**Comment by jpadilla** [comment]
This is related to https://github.com/tomchristie/django-rest-framework/issues/3636#issuecomment-157589259
