### ISSUE TITLE
Incorrect regex in URLPathVersioning documentation

### ISSUE THREAD

**Issue by bluetech** [tomchristie/django-rest-framework#3638]
Version: 3.3.1

The documentation for `versioning.URLPathVersioning` (both the docstring and the [API guide](http://www.django-rest-framework.org/api-guide/versioning/#urlpathversioning)) provides the following example for the URL regex: `r'^(?P<version>[v1|v2]+)/bookings/$'`. Unless I am misunderstanding, I think that `[v1|v2]` is supposed to be `(v1|v2)`, and that the `+` should be removed. Also, I am not sure whether it is customary to add a mandatory trailing slash or not.

(From git blame I see the regex was changed to the above in pull request #3037).

**Comment by tomchristie** [comment]
> I think that [v1|v2] is supposed to be (v1|v2), and that the + should be removed. 

Correct and correct.

> Also, I am not sure whether it is customary to add a mandatory trailing slash or not.

It's not mandatory (either would be valid) but I would like to leave the style as it is.

**Comment by jpadilla** [comment]
Both options seem to work fine. Can anyone explain the difference between `r'^(?P<version>[v1|v2]+)/bookings/$'` and `r'^(?P<version>(v1|v2))/bookings/$'`?

**Comment by xordoquy** [comment]
[] is for set of characters which means [abc] will match 'a', 'b', or 'c'.
() is for groups which takes the content as a whole.

**Comment by jpadilla** [comment]
@xordoquy got it, thanks! @bluetech want to put a PR together for this?

**Comment by jpadilla** [comment]
Closed by #3675
