### ISSUE TITLE
Import Error: No module named apps with django 1.6.11

### ISSUE THREAD

**Issue by zubairalam** [tomchristie/django-rest-framework#3639]
My project uses Django v1.6.11 with django-rest-framework v3.3.1
I'm getting following traceback when django loading project's urls.py
``

    from rest_framework import routers, serializers, viewsets
    web_1 |   File "/usr/local/lib/python2.7/site-packages/rest_framework/routers.py", line 25, in <module>
    web_1 |     from rest_framework import views
    web_1 |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 19, in <module>
    web_1 |     from rest_framework.response import Response
    web_1 |   File "/usr/local/lib/python2.7/site-packages/rest_framework/response.py", line 13, in <module>
    web_1 |     from rest_framework.serializers import Serializer
    web_1 |   File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 26, in <module>
    web_1 |     from rest_framework.utils import model_meta
    web_1 |   File "/usr/local/lib/python2.7/site-packages/rest_framework/utils/model_meta.py", line 11, in <module>
    web_1 |     from django.apps import apps
    web_1 | ImportError: No module named apps
``

**Comment by xordoquy** [comment]
3.3.x doesn't support Django < 1.7, please refer to the release notes for more informations.

**Comment by mzmmohideen** [comment]
I am also faced same issue, i simply downgrade my rest framework into 3.2 .. now its works fine
