### ISSUE TITLE
Removed method, get_paginate_by() referenced in docs

### ISSUE THREAD

**Issue by willdady** [tomchristie/django-rest-framework#3640]
The current docs for [Generic views](http://www.django-rest-framework.org/api-guide/generic-views/) has examples using `get_paginate_by()` but this method no longer exists (since 3.0.5?).

**Comment by jpadilla** [comment]
Seems like we could just remove any mention to `get_paginate_by()`. @willdady want to put a PR together?

**Comment by willdady** [comment]
@jpadilla done - #3642

**Comment by jpadilla** [comment]
Resolved by #3642
