### ISSUE TITLE
README Example UserSerializer error

### ISSUE THREAD

**Issue by imacleod** [tomchristie/django-rest-framework#3645]
The README Example's UserSerializer definition has an error. It includes a 'url' field that does not exist in a default Django User model. When following the current Example (with the 'url' field) an error is thrown:

'ImproperlyConfigured at /users/
Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.'

Removing the 'url' field from the UserSerializer definition fixes this.

**Comment by xordoquy** [comment]
I followed the direction on the README and got it working without changing a single line:

    [
        {
            "url": "http://localhost:8000/users/1/",
            "username": "admin",
            "email": "xxx@xxx.com",
            "is_staff": true
        }
    ]

**Comment by imacleod** [comment]
Using Python 3.5 and Django 1.8.4 I see this error. @xordoquy what Python and Django versions are you using?

**Comment by xordoquy** [comment]
Python 3.4 / Django 1.8.6 / DRF 3.3.1

**Comment by xordoquy** [comment]
Same result with Python 3.5

**Comment by xordoquy** [comment]
Please double check you're using an HyperlinkedModelSerializer

**Comment by imacleod** [comment]
Yes I am using HyperlinkedModelSerializer, I copied the Example directly.

**Comment by xordoquy** [comment]
If you go to an undefined page (like /alrinaoernazorf/) your urls should look like:

Using the URLconf defined in example.urls, Django tried these URL patterns, in this order:
^ ^$ [name='api-root']
^ ^\.(?P<format>[a-z0-9]+)/?$ [name='api-root']
^ ^users/$ [name='user-list']
^ ^users\.(?P<format>[a-z0-9]+)/?$ [name='user-list']
^ ^users/(?P<pk>[^/.]+)/$ [name='user-detail']
^ ^users/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$ [name='user-detail']
^api-auth/

**Comment by imacleod** [comment]
Right. I created another environment and the README's Example works correctly, so something odd is going on with the original environment I implemented this in.

**Comment by imacleod** [comment]
I've discovered what the issue is: namespaces. If you namespace the router url include like so:

urlpatterns = [
    url(r'^', include(router.urls, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

the error that I included in my first message is thrown. Remove the namespace and everything works as expected. Users should be warned about adding a namespace here, as they may very likely do so.
