### ISSUE TITLE
Empty requests treated differently from '{}'

### ISSUE THREAD

**Issue by sorenh** [tomchristie/django-rest-framework#3647]
This took me quite a while to work out :)

I have a Serializer with HyperlinkedRelatedField(many=True) on it. I had some API tests that would pass in an empty dict:

    self.client.post(list_url, {}, format='json')

The response yielded the expected 401, stating that the given field was required. So far, so good.

Much to my surprise, if I sent an empty POST request to the same url on my production system (or Django's built-in development server), the resource was created succesfully, with an empty list for that field.

After quite a bit of digging, I learned that an empty request invariably means that request.data is a QueryDict, rather than a simple, empty dict. During validation, many Field implementations call html.is_html_dictionary() on request.data. is_html_dictionary simply checks for a .getlist() method. Incidentally, this getlist() method is the culprit. When called, it will always return a list, even if the given key is not found at all, in which case it yields an empty list.

I feel that the result for an empty request and a request that passes in an empty json object should yield the exact same results.

**Comment by xordoquy** [comment]
Actually HTML forms and JSON requests differs a lot because there's no way we can  have as much details with the forms as we have with JSON.
Will keep this open, need to think if we can improve things here.

**Comment by sorenh** [comment]
I appreciate that, but I'm not using HTML forms anywhere. I'm even explicitly passing "application/json" as my content type.

**Comment by sorenh** [comment]
It's not very elegant, but this fixes it for me and doesn't break any tests:

    diff --git a/rest_framework/parsers.py b/rest_framework/parsers.py
    index 2dc808f..d99fef9 100644
    --- a/rest_framework/parsers.py
    +++ b/rest_framework/parsers.py
    @@ -62,6 +62,9 @@ class JSONParser(BaseParser):
             parser_context = parser_context or {}
             encoding = parser_context.get('encoding', settings.DEFAULT_CHARSET)
     
    +        if not stream:
    +            return {}
    +
             try:
                 data = stream.read().decode(encoding)
                 return json.loads(data)
    diff --git a/rest_framework/request.py b/rest_framework/request.py
    index 846cadc..785abd7 100644
    --- a/rest_framework/request.py
    +++ b/rest_framework/request.py
    @@ -275,7 +275,7 @@ class Request(object):
             stream = self.stream
             media_type = self.content_type
     
    -        if stream is None or media_type is None:
    +        if stream is None and not media_type:
                 empty_data = QueryDict('', encoding=self._request._encoding)
                 empty_files = MultiValueDict()
                 return (empty_data, empty_files)

**Comment by xordoquy** [comment]
@sorenh I think a failing test case would help more. Your workaround may not work with nested serializers for example.

**Comment by sorenh** [comment]
I'm working on a good test case right now. I'll have it ready tomorrow, probably.

**Comment by xordoquy** [comment]
Thanks, this will help a lot !

**Comment by sorenh** [comment]
I don't know.. I have test that fails, but I'm not sure if it's too specific:

https://github.com/sorenh/django-rest-framework/commit/f306988c1a10a384fcefcc425807fbb9cbb5e92e

**Comment by socketubs** [comment]
Hi,

I have a problem that could maybe similar (if not, I can create new issue).
When a send a empty `PUT`, `json` or `form-url-encoded`, my `request.data` (`QueryDict`) is immutable.
If I just add a single attribut in my `json`, my `request.data` (`QueryDict`) is mutable.

Any idea ? Is it related ?

Thank you guys :smiley:

**Comment by craigds** [comment]
I think I hit this problem, or something very similar. In my case I think the problem happens when selecting the parser. JSONParser never gets called:

https://github.com/tomchristie/django-rest-framework/blob/a101251a2adbe4c42d28a60732e2b4d505cc624b/rest_framework/request.py#L280-L283

In those lines, if the request is empty the parser selection is skipped altogether. I'd expect it to be called and to throw an error (since an empty string is not valid JSON).

**Comment by tomchristie** [comment]
Marking for 3.5.0 as may be a behavioral change worth mentioning in release notes if we do address this.
