### ISSUE TITLE
Django restframework upgrading from 0.4.0 to 3.3.1

### ISSUE THREAD

**Issue by Six-wars** [tomchristie/django-rest-framework#3653]
I've upgraded django restframework from 0.4.0 to 3.3.1 and there's some missing imports I'd like to know the current equivalents. 
       mixins import ReadModelMixin, PaginatorMixin
       views import View, ListModelView, ModelView

**Comment by tomchristie** [comment]
Not really in a position to support 3 year upgrades - I'd suggest taking any questions to the discussion group, rather than the issue tracker.
