### ISSUE TITLE
paginate_by does not work for restframework ListAPIView (v.3.3.1)

### ISSUE THREAD

**Issue by madEng84** [tomchristie/django-rest-framework#3657]
I like very much your work but sometimes i see you change a lot of things passing from one version to another. However i use restframework with django because it is actually the best toolkit for building Web APIs.
Unfortunately, I have noticed that with v 3.3.1 you have modified the pagination implementation for class based views
Now we have to set the same pagination class (and the same page size) for every api, or we have to create a pagination_class for every api if every api has different page_size from the other ones. Maybe I'm wrong. If not so, I think this change is not a DRY implementation and that the paginate_by variable was the better solution. However i see that the documentation is outgraded... as you can see in this link:
http://www.django-rest-framework.org/api-guide/generic-views/

Best regards

**Comment by xordoquy** [comment]
Pagination has changed back in [3.1](http://www.django-rest-framework.org/topics/3.1-announcement/#pagination).
The pagination change including  `paginate_by` was also mentioned in the [3.2 release notes](http://www.django-rest-framework.org/topics/3.2-announcement/#deprecations).

We have an ongoing issue about making the application fail loudly if they are still used and a pull request to make deprecations more visible to the developers.

As for the documentation, issues and even better, pull request helping us to keep it up to date are more than welcomed.
