### ISSUE TITLE
Model updated for serializer fields

### ISSUE THREAD

**Issue by kennydude** [tomchristie/django-rest-framework#3659]
Currently there is not a very clean way of just adding a field which has to do some work with the model once it is saved.

This is a feature request which would allow me to do something like:

```python
class MyField(serializers.Field):
    def model_saved(self, model):
        # do stuff with model
        pass
```

Currently the solution is to have a custom model serializer, but I don't think it's ideal.

**Comment by tomchristie** [comment]
The responsibility of field classes is validation & serialization. We're not likely to add anything that means they get hooked into `.save()`.
