### ISSUE TITLE
Invalid hyperlink - Object does not exist

### ISSUE THREAD

**Issue by davidmir** [tomchristie/django-rest-framework#3661]
Hi,

I'm having the following problem with relative hyperlinked fields when I try to create a resource:
{"resource":["Invalid hyperlink - Object does not exist."]}

Assuming that the link is as follows: http://localhost/api/resources/10/
When I make a GET to the API it returns me the object, but when is a relationship with the resource it returns me the error noted above (the relation in the database exists)

Thanks

**Comment by xordoquy** [comment]
Hi,

Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

If you think there is a bug with DRF please try to isolate to the simplest test case so we can reproduce it and feel free to reopen.

Thanks!
