### ISSUE TITLE
auto increment id in legacy db

### ISSUE THREAD

**Issue by capiman13** [tomchristie/django-rest-framework#3667]
Hello,

I am having troubles creating a new obj into a legacy db.
This is the model:
```python
class Contract(models.Model):
    idContract = models.AutoField(db_column='idContract',primary_key=True)  
    idClient = models.ForeignKey(Client, db_column='idClient',related_name='+') 

    class Meta:
        managed = False
        db_table = 'Contract'
        unique_together = (('idContract', 'idClient'),)
        default_permissions = ('add', 'change', 'delete', 'view')
```
When I try to create a contract pushing a post with content: 
    ```{"idClient": 1}```
I receive:
```
HTTP 400 Bad Request
{
    "idContract": [
        "This field is required."
    ]
}
```
I have been woking with REST FRAMEWORK for 2 months and this is the only problem I was not able to solve, I need help. Thanks.

**Comment by xordoquy** [comment]
Please, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

Note that you have a unique together constraint that requires DRF to know both value to sort out this constraint.

**Comment by capiman13** [comment]
Sorry, thank you very much.
