### ISSUE TITLE
After exception is raised, I can't see an exception raised, I'm redirected instead

### ISSUE THREAD

**Issue by jvorcak** [tomchristie/django-rest-framework#3669]
I've started a new app and installed drf=3.3.1. Whenever an exception is raised, I'm redirected to the original request's URL and I can't see the exception even though `DEBUG=True`

The last version where it behaves as expected is `3.2.5`, starting from `3.3.0` it doesn't work anymore. Is that a possible regression and a problem with an exception handler?

**Comment by xordoquy** [comment]
@jvorcak it may be a regression. To figure out you may try to isolate the issue to a simple test case.

**Comment by jvorcak** [comment]
@xordoquy I've tried to create a reproducible example, but there it works as expected. In a project where a problem persists, I have a custom user model, I'll try that one later. I'll keep you updated.

**Comment by xordoquy** [comment]
Thanks. I don't think it's linked to the custom user model. I'll tend to look at specific middlewares or custom 404 handler in your project.

**Comment by jvorcak** [comment]
Sorry for wasting your time. When trying to create a reproducible example, I've figured out it's causing one of the 3rd party Chrome extensions I've recently installed :/ Stupid of me, I should have checked that in a first place.

**Comment by xordoquy** [comment]
@jvorcak no worries about that and thanks for the feedback.
