### ISSUE TITLE
Django's get_object_or_404 default output gets hijacked by APIView

### ISSUE THREAD

**Issue by ryechus** [tomchristie/django-rest-framework#3671]
When using django's get_object_or_404 in a class-based view that abstracts from APIView the default output of get_object_or_404 gets hijacked by DRF. What I would like to see is the default django ouptut that tells me which url failed and why, but what I end up with is:

```
{"detail":"Not found."}
```

IMO, this is really invasive behavior and DRF's 404 output should only be returned if the developer explicitly uses status.HTTP_404_NOT_FOUND as a value for the status parameter in a Response. I could possibly understand this behavior if I was abstracting from GenericAPIView, the class meant for more plugging and playing, but I am not.

Is this something that could be addressed?

**Comment by xordoquy** [comment]
`GenericAPIView` is meant with Django models while `APIView` is more agnostic.
DRF handles that because it wouldn't make sense to display an HTML page when the client expects JSON or other formats.

I think if you're using the browsable API you still get the Django default 404 page benefits.

**Comment by ryechus** [comment]
Thanks for responding.

I'm not using the browsable API and while I understand what you are saying about the client expecting a JSON format I respectfully disagree. The client doesn't much care what kind of response it receives. A 404 error is a 404 error whether it returns JSON or HTML. I would rather receive django's HTML response when I am using django's helpers.

**Comment by tomchristie** [comment]
Your use case can be covered using a custom error handler (or say by having a mixing that override the default `get_object()`) On balance I believe that most API users would expect the current behavior, so I've no intention of altering that in the absence of any country evidence.

**Comment by ryechus** [comment]
I am already using a custom mixin. It is my mixin that uses django's get_object_or_404. I opened the ticket because I want my custom mixin to not be tampered with by DRF. Could it be a problem with the ordering of my class abstractions? Currently, I have my custom mixin being using before APIView because I have read class abstractions should go from least important to most important from left to right.

-Mike
