### ISSUE TITLE
Converting queryset to list in pagination classes

### ISSUE THREAD

**Issue by tsouvarev** [tomchristie/django-rest-framework#3673]
I need to add some prefetch_related/select_related calls on queryset in serializer, but serializer gets paginated queryset and DRF's paginators explicitly convert queryset to list. Is there any reason to do so?
By the way, if removed, tests still pass.

**Comment by tomchristie** [comment]
> Is there any reason to do so?

Yes. The page requires slicing the queryset, at which point the query has been evaluated.

> I need to add some prefetch_related/select_related calls on queryset in serializer

Adding there to `.queryset` or `.get_queryset` on the view is probably the right thing to do here (and they'll be applied before pagination then)

**Comment by tsouvarev** [comment]
> The page requires slicing the queryset, at which point the query has been evaluated

Slicing doesn't evaluate queryset. Removing `list` call works like a charm

> Adding there to .queryset or .get_queryset on the view is probably the right thing to do here

Seems right, but only serializer knows what fields will be in serilization, so view can't know which fields should be prefetched

**Comment by tomchristie** [comment]
> Removing list call works like a charm

Welcome to issue this as a PR and we could review further there. Not sure if it'd be accepted or not at this point, but it'd be an easier starting point than discussing it in abstract.
