### ISSUE TITLE
ListField and DictField do not recognize `child` specified as first arg

### ISSUE THREAD

**Issue by qwiglydee** [tomchristie/django-rest-framework#3681]
Following [the documentation](http://www.django-rest-framework.org/api-guide/fields/#listfield) of ListField, a user may expect that it is to be declared as:
```python
field_name = ListField(NestedField())
```
This looks quite natural and in consistency with former [drf-compound-fields](https://github.com/estebistec/drf-compound-fields).

However, [the implementation](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1431) expects the `child` to be specified in kwargs rather then args. This prevents a child to be specified as first arg and requires declaration to be:
```python
field_name = ListField(child=SubField())
```
Which is a bit confusing.

Te same applies to DictField.

**Comment by xordoquy** [comment]
The documentation doesn't show any mention of `child` being a positional argument.
Any proposal on how we could make this more explicit ?

**Comment by qwiglydee** [comment]
But why it should be explicitly non-positional?
Most other fields allow to specify their type-specific arguments as positional.
Half of other fields do not use `*args` at all.

**Comment by tomchristie** [comment]
Not particularly inclined to address this ATM. Could consider PRs on their own merits, but not convinced.
