### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by whoisearth** [tomchristie/django-rest-framework#3682]
Typo in code example for HTML and Forms.

http://www.django-rest-framework.org/topics/html-and-forms/

In the following code on the page there is a single quote `'` before the second `%` which should not be there (removed below)

    {% load rest_framework %}

    <html><body>

    <h1>Profile - {{ profile.name }}</h1>

    <form action="{% url 'profile-detail' pk=profile.pk %}" method="POST">
        {% csrf_token %}
        {% render_form serializer %}
        <input type="submit" value="Save">
    </form>

    </body></html>

Solution does not work out of the box in testing and wondering if there is extra code required such as what the valid urls.py should be.  Assumption is the following would be the urls.py

    urlpatterns = [
        url(r'^profiles/$', views.ProfileList.as_view(), name='profile-list'),
        url(r'^profiles/(?P<pk>[0-9]+)/$', views.ProfileDetail.as_view(), name='profile-detail'),
    ]

Which does not seem to address the problem.  Relevant stackoverflow here - 

http://stackoverflow.com/questions/33979468/drf-reverse-for-widget-detail-with-arguments-and-keyword-arguments-u/33981162#33981162

**Comment by tomchristie** [comment]
Note that edited docs directly in GitHub interface, but diff ended up being unexpected (whitespace changes?)
Won't be using 'edit directly' in future, even for one character changes like this.
