### ISSUE TITLE
Re-add ability to customize paginator class

### ISSUE THREAD

**Issue by jezdez** [tomchristie/django-rest-framework#3684]
As part of the 3.1 release DRF lost the ability to override the paginator class and replaced it with a custom implementation that uses Django's default paginator in the critical `paginate_queryset` method. This change severely limits the architectural separation of data pagination from view level pagination behavior.

E.g. code that happens when the pagination page queryset is evaluated now needs to be handled in an overridden `Pagination.paginate_queryset` method. Since the instantiation of the paginator is in the middle of the default `PageNumberPagination.paginate_queryset` method working around this deprecation results in effectively completely rewriting it and making it a future tech debt concern. The alternative to run queryset evaluation time code in `paginate_queryset` and then call the parent `paginate_queryset` is equally not satisfactory as at that point the page object hasn't been created yet which contains vital information that is not available on the pagination instance. Fetching that data after the fact would again require evaluation the queryset, again not wanted.

As such the removal of the ability to override the paginator class is a step backwards that leads to brittle workarounds (monkeypatches) and removed the ability to hook into a key moment of pagination. Please advise what I can do to improve this.

**Comment by tomchristie** [comment]
Is the crux of this issue that you'd like to be able to override the behavior of [this line](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/pagination.py#L198) without having to override the rest of the method?

If so, does this PR address your concerns?... https://github.com/tomchristie/django-rest-framework/pull/3631

**Comment by jezdez** [comment]
Yep!

**Comment by jezdez** [comment]
(to both questions)

**Comment by jezdez** [comment]
Closing as duplicated of #3631
