### ISSUE TITLE
Upgrade from v2 to v3 causes a lot of linter warnings - "must implement all abstract methods"

### ISSUE THREAD

**Issue by rschwiebert** [tomchristie/django-rest-framework#3686]
After switching to DRF 3.3.0 from 2.4.4, I am suddenly getting a lot of "must implement all abstract methods" warnings from PyCharm's linter. (They were not there when using 2.4.4.)

They are occurring on every ModelSerializer object we have. The serializers are not particularly complicated: nearly all of them match the example in the serializers documentation:

class AccountSerializer(serializers.ModelSerializer):
    class Meta:
        model = Account
        fields = ('id', 'account_name', 'users', 'created')

I thought that the linter might be triggered by NotImplemented exceptions, but the source code seems to eliminate that theory.

I'm not sure that this adversely affects functionality, but I figured I should ask, because it is a marked change in the analysis of the code.

**Comment by xordoquy** [comment]
Thanks for the report. Unfortunately without more informations there isn't much we could do. Do you have the list of the abstract methods that should be defined ?

**Comment by dimitrovskif** [comment]
DRF does not in any way use the decorator `@abstractmethod` which can cause the "Must implement abstract methods" error. Therefore, it is highly unlikely that this is an actual DRF error.

Can you make sure that:

* You are using a supported Python version (2.7 or 3.x)
* You are using a supported Django version (1.7, 1.8, 1.9)
* `serializers.ModelSerializer` points to the actual DRF `ModelSerializer`, and it points to the 3.3.0 version that you think are using
  * Get file location: `import rest_framework; print(rest_framework.__file__)`
  * Do this in python REPL interpreter `from rest_framework import serializers; help(serializers)`
  * Check `dist-packages` or `pip` if you are using it

If you are absolutely sure that none of these cause the problem, please send a traceback.

**Comment by tomchristie** [comment]
Not sufficiently enough evidence of an issue to keep this open, but more than welcome to reassess given more evidence.

**Comment by rschwiebert** [comment]
@dimitrovskif @tomchristie The version of django is 1.7.7, and the version of Python is 3.4.3.

`import rest_framework; print(rest_framework.__file__)` results in `/var/opt/www/venv/lib/python3.4/site-packages/rest_framework/__init__.py`

`rest_framework.VERSION` results in `'3.3.0'`, and ModelSerializer is imported directly from rest_framework.serializers in all locations.

There is no traceback, only this PyCharm linter warning. I'm attaching a screenshot of what I see.

I don't know what you mean by 'check pip,' but let me say that I am working on a virtual machine provisioned by a Chef recipe. All manual inspections confirm that the versions I've specified are those in use.

Perhaps I should also drop PyCharm a line and start them checking if it is a bug in their linter code. It's curious though that this only happened after upgrading DRF.
![screenshot 2015-12-02 09 41 16](https://cloud.githubusercontent.com/assets/8643352/11533721/28fe8c52-98d9-11e5-84e5-4715e9202b2a.png)

**Comment by rschwiebert** [comment]
@dimitrovskif @tomchristie Ah, sorry, this seems to be the issue: https://youtrack.jetbrains.com/issue/PY-16776  

The changes between DRF2 and DRF3 must have been such that they tickled this false positive. So, it looks like the issue really is PyCharm's linter and not caused by some defect in DRF. 

Thanks for your help.

**Comment by tomchristie** [comment]
:+1:

**Comment by dimitrovskif** [comment]
Told ya, it would have been weird if it was DRF's fault. Especially since it occured in one of the most common DRF usage case.
