### ISSUE TITLE
CSRF errors when supporting both token and session authentication

### ISSUE THREAD

**Issue by jonathan-golorry** [tomchristie/django-rest-framework#3690]
I have implemented a token login system similar to this: https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py

The problem occurs in a couple unusual cases.
1) If I login from the browsable api (token login), press back, and try to login again
2) If I login from an android simulator, do a code reload, and try to login again.

The error is:
{
    "detail": "CSRF Failed: CSRF token missing or incorrect."
}

My default authentication classes:
'DEFAULT_AUTHENTICATION_CLASSES': (
         'rest_framework.authentication.TokenAuthentication',
         'rest_framework.authentication.SessionAuthentication',
     ),

Note that if I remove SessionAuthentication the error does not occur, implying that session authentication is failing and giving an error before the token authentication has a chance of working.

**Comment by xordoquy** [comment]
Please upgrade to 3.3.1. 3.3.0 had a bug with authenticated users and CSRF.

**Comment by jonathan-golorry** [comment]
The problem is persisting in version 3.3.1

**Comment by xordoquy** [comment]
Looking closer at both, they will depend on your cookie management (try chrome or firefox if you're using Safari). Django documentation has a detailed explanation about how CSRF token work.
