### ISSUE TITLE
Add editable_fields or similar to Serializer Metaclass

### ISSUE THREAD

**Issue by HuffAndPuff** [tomchristie/django-rest-framework#3693]
Regarding read_only_fields in Serializer, I'm far more often concerned which fields I *can* edit rather which ones I can't. It would often be more intuitive and feel safer to have 
```python
fields = (
    # Long list of fields
)
editable_fields = (
  "first_name",
  "last_name"
)
```

rather than the calculating the intersection of `fields` and `read_only_fields` in my head:

```python
fields = (
    # Long list of fields
)
read_only_fields = (
    # Slightly shorter list of fields
)
```

Now I did this in a subclass by overriding `get_uniqueness_extra_kwargs` since `get_extra_kwargs` does not pass in the field_names necessary to change the read_only default on each field.

**Comment by tomchristie** [comment]
Reasonable enough idea, but I wouldn't want the additional complexity & API surface area this'd require.

**Comment by HuffAndPuff** [comment]
Fair enough. Would it be possible to adjust so that `get_extra_kwargs(self)` becomes `get_extra_kwargs(self, field_names)` ? That way we can do it in our own base project serializer but avoid the currently hackish way of implementing it in the `get_uniqueness_extra_kwargs` method.

**Comment by tomchristie** [comment]
Don't fully understand that on first pass, but welcome to open an issue describing the proposal more fully
