### ISSUE TITLE
table django_content_type is not match at test and manager

### ISSUE THREAD

**Issue by wuyazi** [tomchristie/django-rest-framework#3700]
In manager, i use ContentType to get a content_type by model name
In test, i use ContentType to get a content_type by object instance

I found a issues
My test get content_type from my test database
My manager get content_type from my local database

When the two database table django_content_type not match, it is too bad.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

Note that unless you are using your own test system manager will use the same DB as test.

**Comment by wuyazi** [comment]
as django, the command : 'python manage.py test' will create a database for test automaticly.
not i created
