### ISSUE TITLE
CSRF failure when creating object using admin browser

### ISSUE THREAD

**Issue by mcastle** [tomchristie/django-rest-framework#3706]
This is with drf version 3.3.1, using Django 1.8.7.
When trying to create an object, the admin browser displays the error: `CSRF Failed: CSRF token missing or incorrect.`
This error does not happen with the api browser. And it doesn't happen in drf version 3.2.4 in admin or api browser.

**Comment by jpadilla** [comment]
This is probably a duplicate of #3637
