### ISSUE TITLE
Crispy forms formatting error (Django 1.9.0 - DRF 3.2.3 - Crispy 1.5.2)

### ISSUE THREAD

**Issue by jphalis** [tomchristie/django-rest-framework#3707]
When I open the homepage for my API, the logout button that is usually on the top right is now HTML code that is spread across the entire header of the screen. There is no button to click, removing all functionality.

I am using Django 1.9, Crispy forms 1.5.2, and DRF 3.2.3. Is anyone else having this issue?

**Comment by jpadilla** [comment]
@jphalis this was fixed in #3546, released in 3.3.0.
