### ISSUE TITLE
Form in API browser never gets displayed

### ISSUE THREAD

**Issue by mikew** [tomchristie/django-rest-framework#3708]
<img width="919" alt="screen shot 2015-12-06 at 5 03 09 pm" src="https://cloud.githubusercontent.com/assets/4729/11615570/5d9b80b8-9c3b-11e5-87d3-966367830a29.png">

The empty well in the screenshot above is where the form should be, and in the Elements panel below you can see that the `.tab-pane` container never gets the `active` class.

So we're manually running `$('#post-generic-content-form').addClass('active')`, but would love to know what happened.

**Comment by xordoquy** [comment]
Should be solved by #3600.
