### ISSUE TITLE
issue with TemplateHTMLRenderer

### ISSUE THREAD

**Issue by mengjiin** [tomchristie/django-rest-framework#3719]
I'm using Django REST framework 3.3.1 and Django 1.8.7.
In my template, I have something like:
{% for message in messages %}
     {{ message }}
{% endfor %}

In my view, I do the following:
return Response({'form': form, 'messages': messages}, template_name='a.html')

Form gets displayed OK, but messages doesn't get displayed.
If I change my view to "return Response({'form': form, 'msgs': messages}, template_name='a.html')" and my template to "{% for message in msgs %}", both will get displayed fine.

However if I do "return render(request, 'a.html', {'form': form, 'messages': messages})", both will get displayed fine too. So it seems to me that 'messages' is not a keyword I should avoid using.

Though I have a workaround by changing 'messages' to 'msgs', I'd appreciate if someone looks into this.

Thanks!

**Comment by johnraz** [comment]
Sounds more like a django issue that may be related to the use of the message framework:
https://docs.djangoproject.com/en/1.9/ref/contrib/messages/#displaying-messages

**Comment by xordoquy** [comment]
@johnraz most probably yes.
Lets move this to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) which is the best place to take this discussion and other usage questions. Thanks!
