### ISSUE TITLE
Auto redirect with Apache?

### ISSUE THREAD

**Issue by andreage** [tomchristie/django-rest-framework#3724]
I'm experiencing this problem since recently, I guess after upgrading to Django 1.9. I'm using DRF 3.3.1.

With the following code I can reproduce the problem. The problem happens with Apache and not with the built-in Django web server.

    from rest_framework import status
    from rest_framework.views import APIView
    from rest_framework.response import Response

    class Test200(APIView):
        def get(self, request, format=None):
            return Response({'test': '200'}, status=status.HTTP_200_OK, headers={'Location': '/'})

    class Test202(APIView):
        def get(self, request, format=None):
             return Response({'test': '202'}, status=status.HTTP_202_ACCEPTED, headers={'Location': '/'})

[...]

    url(r'^test200/$', Test200.as_view(), name='test200'),
    url(r'^test202/$', Test202.as_view(), name='test202'),

With the Django built-in server, I get {"test":"200"} and {"test":"202"} respectively.
With Apache on production I get {"test":"202"} from the second view, meanwhile from the first view I get the content of the main page (that is the content of "/") even if the URL remains "/test200/".
Can someone reproduce the problem? Is it an Apache misconfiguration?

**Comment by xordoquy** [comment]
Hi,

This is an issue tracking. The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
