### ISSUE TITLE
Filter not working with genricipaddress field

### ISSUE THREAD

**Issue by LeoQuote** [tomchristie/django-rest-framework#3730]
I m using ``filters.DjangoFilterBackend`` & ``filter_fields``

```
filter_backends = (filters.SearchFilter,filters.DjangoFilterBackend,)
filter_fields = ('ip','hostname')
```
in ``serializers.py`` ,I used ``ModelSerializer`` 

I changed one field`` ip`` from charfield to GenericIPAddressField , and the filter for``ip`` does not work anymore

**Comment by carltongibson** [comment]
Looks like an issue on Django Filter. Please try against the latest `develop` branch there and if it's not already fixed open an issue with a simple reproduce cases.
