### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by simonsmiley** [tomchristie/django-rest-framework#3740]
I am packaging django-rest-framework for archlinux. I keep getting test errors for:
* python 2.7.11 using django 1.8 and 1.7  
* python 3.5.1 using django 1.9, 1.8 and 1.7 

Is something wrong with my setup? The travis builds look fine (but they are using older versions of python)

**Comment by xordoquy** [comment]
Python 3.5.1 isn't supported for Django 1.7 / 1.8 so I'm not surprised.
As for 2.7.11 I'm surprised tests won't pass.

**Comment by xordoquy** [comment]
Python 3.5 had an issue with Django 1.9 in our test matrix (see #3745).
Closing this as I don't think there's an issue with our tests. Will reopen if there's more info about what's broken on DRF.
Note that my Python versions (OS X / macports) are:
  python26 @2.6.9_3 (active)
  python27 @2.7.11_0 (active)
  python32 @3.2.6_2 (active)
  python33 @3.3.6_5 (active)
  python34 @3.4.3_5 (active)
  python35 @3.5.1_0 (active)
