### ISSUE TITLE
multiple detail_route for the same url_path

### ISSUE THREAD

**Issue by rexzhang** [tomchristie/django-rest-framework#3743]
~~~
class OrderBaseViewSet(viewsets.ViewSet):

    @detail_route(methods=['get', 'put'])
    #----------------------------------------------------------------------
    def trigger(self, request, pk=None):
        if request.method == 'GET':
            return Response(get_order_trigger_info(fsm))

        elif request.method != 'PUT':
            ...
~~~

well, it is work

~~~
class OrderBaseViewSet(viewsets.ViewSet):

    @detail_route(methods=['get'], url_path='trigger')
    #----------------------------------------------------------------------
    def trigger_get(self, request, pk=None):
        ...

    @detail_route(methods=['put'], url_path='trigger')
    #----------------------------------------------------------------------
    def trigger_put(self, request, pk=None):
        ...

~~~
we got this:
~~~
{
  "detail": "Method \"PUT\" not allowed."
}
~~~

my envt:
python 2.7.11
django 1.9
djangorestframework 3.3.2

ref: https://github.com/tomchristie/django-rest-framework/issues/2708
ref2: http://stackoverflow.com/questions/33862135/add-specific-method-handler-detail-route-in-django-rest-framework

**Comment by xordoquy** [comment]
I'm going to close this as the decision is already explained in #2708.

You could redesign your view to make trigger call trigger_put/get or write your own decorator to support multiple routes for a single url. You could make it a 3rd party and add it to [the documentation](http://www.django-rest-framework.org/topics/third-party-resources/#how-to-create-a-third-party-package).
