### ISSUE TITLE
How can I update data with POST request

### ISSUE THREAD

**Issue by lectricas** [tomchristie/django-rest-framework#3755]
Hi. I've been through this tutorial http://www.django-rest-framework.org/tutorial/ and it was nice. However, I have no idea how to implement update request.
I have 

```
def update(self, instance, validated_data):
        """
        Update and return an existing `Snippet` instance, given the validated data.
        """
        instance.title = validated_data.get('title', instance.title)
```

this method in my serializers.py class.
I can create snippets by this:
http -a user:pwd POST http://127.0.0.1:8000/snippets/ title="print 782", code="dsfs"
What line can I update existed snippet?
Thanks

**Comment by xordoquy** [comment]
If you need more in-depth informations, the view and possibly viewset sections of the documentation will provide more about the update process.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take usage questions. Thanks!
