### ISSUE TITLE
HTML Title Is Not Informative

### ISSUE THREAD

**Issue by mlissner** [tomchristie/django-rest-framework#3756]
In the HTML response type, the HTML title is always the same, simply: "Django REST Framework".

As I'm working on my API, this is a minor nuisance, and I'd bet it's an easy fix to simply put the `h1` value in there too, so it's:

> Django REST Framework &ndash ObjectType List

I could probably take a stab at this if this was a welcome improvement.

**Comment by tomchristie** [comment]
We use mkdocs for the documentation generation, so you'd probably need to take the issue there.

**Comment by tomchristie** [comment]
Seems reasonable, yup.

**Comment by mlissner** [comment]
The title is currently made using:

    <title>{% block title %}Django REST framework{% endblock %}</title>

And not a single page seems to override this block. Later in the base template, there's this:

          {% for breadcrumb_name, breadcrumb_url in breadcrumblist %}
            {% if forloop.last %}
              <li class="active"><a href="{{ breadcrumb_url }}">{{ breadcrumb_name }}</a></li>
            {% else %}
              <li><a href="{{ breadcrumb_url }}">{{ breadcrumb_name }}</a></li>
            {% endif %}
          {% endfor %}

A solution that could work would be something like:

    <title>
    {% block title %}
      {% for breadcrumbname, _ in breadcrumblist %}
        {% if forloop.last %}{{ breadcrumbname }} – Django REST framework{% endif %}
      {% empty %}
        Django REST framework
      {% endfor %}
    {% endblock %}
    </title>

That'll upgrade the title node's text to say the name of the last bread crumb in any page that has the `breadcrumblist` variable. In pages that don't, they'll be unaffected, returning the present value.

If this feels like a reasonable approach, I'll code it up and drop it in a PR.

Feedback requested, thanks!

**Comment by tomchristie** [comment]
Do we not already have the resource title available?
