### ISSUE TITLE
Error in running tests because of old django-guardian in requirements-optionals.txt

### ISSUE THREAD

**Issue by kavirajk** [tomchristie/django-rest-framework#3763]
getting `'guardian.templatetags.guardian_tags': cannot import name 'get_library'` errors while running tests using `./runtests.py` in python3.5 and django 1.9

Fixed after upgrading django-guardian-1.3.0 to django-guardian-1.3.2. Need to update in requirements

**Comment by xordoquy** [comment]
Good catch.

**Comment by jpadilla** [comment]
@kavirajk thanks for the heads up.
