### ISSUE TITLE
__init__() got an unexpected keyword argument 'cache'

### ISSUE THREAD

**Issue by JeffreyPYL** [tomchristie/django-rest-framework#3764]
I got an error of __init__() got an unexpected keyword argument 'cache'
and the trace back show there is an error at 
filters.py line 30
any idea why?
thanks

**Comment by xordoquy** [comment]
Hi,

This is an issue tracker. The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.
Please add some informations such as a traceback to the forum post so we can have a better understanding of your issue.

Thanks.
