### ISSUE TITLE
Serializer generates wrong field type derived from foreign models

### ISSUE THREAD

**Issue by variable** [tomchristie/django-rest-framework#3767]
Please refer to here for detailed explanation here:

http://stackoverflow.com/questions/34404613/django-rest-framework-gives-wrong-type-serializer-field-type-when-derived-from-p

**Comment by xordoquy** [comment]
The property isn't a Django field thus there's no way to guess what type it should be.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by variable** [comment]
```python
>>> OrderItem.objects.last().unit_price
Decimal('78.00')
>>> OrderItem.objects.last().unit_price.__class__
<class 'decimal.Decimal'>
```
Sorry I am not sure what you mean by no way to guess?

**Comment by xordoquy** [comment]
> Please note that the discussion group is the best place to take this discussion and other usage questions. Thanks!
