### ISSUE TITLE
Troubleshoot in Browsable API in 3.3.2

### ISSUE THREAD

**Issue by codespresso** [tomchristie/django-rest-framework#3768]
Hi,

I was just wondering how to troubleshoot during development while using Browsable API in 3.3.2. Earlier since it was not AJAX driven incase of any code error Django's Error page was displayed which helped in troubleshooting. Now since its ajax driven its difficult to troubleshoot.

Any ideas on how to troubleshoot while using Browsable API now ?

**Comment by xordoquy** [comment]
The BrowsableAPI still doesn't use AJAX. The Admin one does.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
