### ISSUE TITLE
More details in docs for Custom Validators.

### ISSUE THREAD

**Issue by klahnen** [tomchristie/django-rest-framework#3772]
Hi,

In docs (http://www.django-rest-framework.org/api-guide/validators/) is not clear that you can write a custom validator by naming your validator function as: validate_'serializer_field_name'.

I think that many users would find that information useful.

Regards.

**Comment by xordoquy** [comment]
It sounds like you are doing a confusion between the [serializer's validation](http://www.django-rest-framework.org/api-guide/serializers/#field-level-validation) and validators. However, I agree there should be a reference to the serializer's validation.

**Comment by tomchristie** [comment]
Yup, some leading text in the `validators` docs would be useful.

**Comment by tomchristie** [comment]
Closed via #4657
