### ISSUE TITLE
Show filters and ordering_fields in OPTIONS data

### ISSUE THREAD

**Issue by mlissner** [tomchristie/django-rest-framework#3779]
I just tried to document my API and realized that I would have to document all of the filters and `ordering_fields` that were in place, making for a LOT of work. 

I wrote a little class to display this data in the OPTIONS request:

```python
class SimpleMetadataWithFilters(SimpleMetadata):
    """Override SimpleMetadata, adding info about filters"""

    def determine_metadata(self, request, view):
        metadata = super(SimpleMetadataWithFilters, self).determine_metadata(request, view)
        filters = OrderedDict()
        for filter_name, filter_type in view.filter_class.base_filters.items():
            filter_name = filter_name.split('__')[0]
            attrs = OrderedDict()
            attrs['type'] = filter_type.__class__.__name__
            choices = filter_type.extra.get('choices', False)
            if choices:
                attrs['choices'] = [
                    {
                        'value': choice_value,
                        'display_name': force_text(choice_name, strings_only=True)
                    }
                    for choice_value, choice_name in choices
                ]
            filters[filter_name] = attrs
        metadata['filters'] = filters
        metadata['ordering'] = view.ordering_fields
        return metadata
```

The code above works well and is in my system, but I wonder if we can't merge this into DRF. I imagine more could be done here, but this alone is a big improvement.

**Comment by tomchristie** [comment]
Closing for similar reasons to https://github.com/tomchristie/django-rest-framework/issues/3808#issuecomment-179762439

Unless there's a proper schema or content-type for us to use for determine what we include in `OPTIONS` requests then I'm not in favor of us making changes there for the time being.

We allow for custom metadata classes if folks need particular requirements for OPTIONS requests.

**Comment by mlissner** [comment]
So the problem expressed in comment 3808 is that filters aren't a part of the `serializer_class`? I guess I don't understand why that matters, but I'll have to reiterate that most APIs will need filters, and without something like this ticket, there's no way I can think of to document them.

As somebody that provides a public API, this is really a vital part of providing an API. I suppose I'm surprised more people aren't crying for this feature.

**Comment by xordoquy** [comment]
@mlissner the current scope is too undefined / too open. We don't want to fallback to what happened with writable nested serializers where we spent lot of time fixing edge cases and for each fixed, two other would pop and code turned into a mess.

I think the next step here would be to address this as a third part app. It'll be a better option as it allows a different release cycle and avoid having a pending PR lasting for months.
This will also provide feedbacks about its usage.
This is possible because the metadata scheme is [configurable](http://www.django-rest-framework.org/api-guide/metadata/#setting-the-metadata-scheme)
