### ISSUE TITLE
Question or issue with unique_together and nullable fields

### ISSUE THREAD

**Issue by bufke** [tomchristie/django-rest-framework#3780]
I spent a good while documenting what I thought was a bug before finding #2547 and I have a question.

Say we have a model with 
```
user = models.ForeignKey(User, blank=True, null=True)
...
Meta:
    unique_together = ('user', 'foo')
```

And a ModelSerializer for said model. With or without
`user = serializers.PrimaryKeyRelatedField(required=False, allow_null=True)`

Without the user field set (or set to null) we would get "user": [  "This field is required." ]

Adding `default=None` to the serializer removes the unwanted validation error. Is this intentional? "Null values are not considered equal." At least as postgres defines it in uniqueness checking. I would expect the serializer to accept a null user value.

**Comment by xordoquy** [comment]
You won't get the "This field is required" if you provide an null value to the field. This will only happen if you don't provide the field at all. I just checked that and it seems that (null, <somevalue>) does pass the validation even if it's already in the Postgresql DB.
Please also don't open usage questions on the issue tracker. The mailing list is the best place to discuss those topics.
