### ISSUE TITLE
ImageField 'http' prefix lost, if I override ViewSet's method

### ISSUE THREAD

**Issue by mrgaolei** [tomchristie/django-rest-framework#3782]
`MEDIA_URL='//media.xx.com'`

Because I both support http and https protocol and I want auto use https prefix Image URL in https website.

In common ViewSet, everything is OK, API output ImageField URL auto add http or https.

But when I override some method, like `list`, the http prefix lost.
For example:
```
    def list(self, request, *args, **kwargs):
        return super(CartViewSet, self).list(request, args, kwargs)
```
I didn't do anything, why all of ImageField URL's `http` prefix lost?

**Comment by xordoquy** [comment]
I don't see any reason this would change something. Can you try to strip the example down to a minimal test case we could reproduce / investigate ?

**Comment by mrgaolei** [comment]
`django-admin.py startproject TestProj`
`./manage.py startapp TestApp`
settings.py:
```
MEDIA_URL='//media.xx.com'
INSTALLED_APPS=(
......
'TestApp',
'rest_framework',)
```

TestApp/models.py:
```
class Test:
    pic = ImageField(upload_up='pic')
```

TestApp/Serializers.py:
```
class TestSerializer(serializers.ModelSerializer):
    class Meta:
        model = Test
```

TestApp/views.py:
```
class TestViewSet(viewsets.ModelViewSet):
    queryset = Test.objects.all()
    serializer_class = TestSerializer
```

in shell or template:
```
test=Test.objects.get(pk=1)
print test.pic.url
```
output`//media.xx.com/pic/a.jpg` is OK.
Because Web Browser know that `//` prefix means auto add current web URL's prefix like `http` or `https`.
But at API, Mobile APP doesn't know `//` prefix, so django-rest-framework auto add `http` prefix to any ImageField, like:
`curl http://www.xx.com/api/test/`
```
[{'id':1,'pic':'http://media.xx.com/pic/a.jpg'}]
```
From start to here, everything is OK.

But sometime, I want change some data, so I override ModelViewSet's method like this:
```
def list(self, request, *args, **kwargs):
    // do something or do anything
    return super(TestViewSet, self).list(request, args, kwargs)
```
`curl http://www.xx.com/api/test/'`
```
[{'id':1,'pic':'//media.xx.com/pic/a.jpg'}]
```
You can see the `http` prefix lost, so all mobile APP can't display any picture.
Why this happend? How to fix it?

**Comment by jpadilla** [comment]
I wonder if it's because of not correctly unpacking arguments and keyword arguments. In your example you have:

```python
def list(self, request, *args, **kwargs):
    // do something or do anything
    return super(TestViewSet, self).list(request, args, kwargs)
```

instead of:

```python
def list(self, request, *args, **kwargs):
    // do something or do anything
    return super(TestViewSet, self).list(request, *args, **kwargs)
```

Notice the `*args` and `**kwargs`.

**Comment by mrgaolei** [comment]
Got it, thanks

**Comment by hack2024** [comment]
I have the same problem, but in a extra action, for example:

`class CapsuleViewSet(viewsets.ModelViewSet):

    queryset = Capsule.objects.all()
    serializer_class = CapsuleSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    @action(detail=True)
    def modules(self, request, pk=None):

        capsule = self.get_object()
        capsule_modules = Module.objects.filter(capsule=capsule)
        serializer = ModuleSerializer(capsule_modules, many=True)
        return Response(serializer.data)`

and in a imageField i get:

`"moduleImageURL": "/media/modulos/logocitbm.png",`

instead of:

`"moduleImageURL": "http://0.0.0.0:8000/media/modulos/logocitbm.png",`

I try def modules(self, request, pk=None, *args, **kwargs) but nothing

**Comment by karthikrp** [comment]
@hack2024 
I've have the same problem. Media_URL does not get appended to Image of File Field for any serialized data I send in my '@action' routes.
