### ISSUE TITLE
Rest Framework Settings file Performs an O(n) operation on settings access that could be O(1)

### ISSUE THREAD

**Issue by CuriousG102** [tomchristie/django-rest-framework#3786]
Calling .keys() on a dictionary returns an iterable, so doing a membership test against that iterable is an O(n) operation. By not including a call to .keys(), the same effect will be attained in O(1) time.

https://github.com/tomchristie/django-rest-framework/blob/af0ea8ef5136da30cb058b10a493d36619d24add/rest_framework/settings.py#L199

**Comment by jpadilla** [comment]
@CuriousG102 mind submitting a PR to discuss further?

**Comment by xordoquy** [comment]
Sounds like a smal improvement since values are cached after that but still possible

**Comment by CuriousG102** [comment]
Ah. I didn't notice the caching going on on line 214. That does indeed make this a small improvement. Otherwise it might have been a bit bigger depending on how often settings are accessed. In any case I'll make a PR after New Years celebrations.

**Comment by xordoquy** [comment]
Thanks and enjoy the celebrations !
