### ISSUE TITLE
Browsable API does not convert docstring markdown to HTML

### ISSUE THREAD

**Issue by cdax** [tomchristie/django-rest-framework#3796]
Case in point:

![screen shot 2016-01-05 at 9 25 42 am](https://cloud.githubusercontent.com/assets/7029291/12107266/6fa95cde-b38e-11e5-8fe7-ca3730880017.png)

is rendered like so:

![screen shot 2016-01-05 at 9 27 07 am](https://cloud.githubusercontent.com/assets/7029291/12107270/8cd9926a-b38e-11e5-94f2-1382969abc5d.png)

while it should be rendered somewhat like:

This viewset automatically provides `list`, `create`, `retrieve`, `update` and `destroy` actions.

**Comment by tomchristie** [comment]
Make sure you've installed the `mkdocs` package.
