### ISSUE TITLE
Make ValidationError class configurable

### ISSUE THREAD

**Issue by gonvaled** [tomchristie/django-rest-framework#3797]
This is my use case:

- EmberData [needs 422](http://stackoverflow.com/q/34609797/647991) for ValidationErrors
- But DRF is [replying](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/exceptions.py#L68) with 400

I would (`api/my_exceptions.py`):

```
from rest_framework import serializers

class EmberDataValidationError(serializers.ValidationError):
    status_code = 422
```

But at this point I am unable to tell drf to use my `EmberDataValidationError`. Is this configurable, or is there another way of achieving a similar effect?

Or is this maybe an extra configuration parameter that could be added to DRF?

**Comment by johnraz** [comment]
One option could be to change the `status_code` of the response in a custom exception handler:
http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

**Comment by johnraz** [comment]
And btw I think you'd better bring this kind of question to the google group first:
https://groups.google.com/forum/?fromgroups#!forum/django-rest-framework

**Comment by tomchristie** [comment]
Indeed  - Custom exception handlers are the way to go here.
