### ISSUE TITLE
Unique indexes are checked before validate is called on the serializer

### ISSUE THREAD

**Issue by lsapan** [tomchristie/django-rest-framework#3799]
Consider the following model and serializer:
```
from django.template.defaultfilters import slugify

class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    class meta:
        unique_together = ('title', 'slug')


class ArticleSerializer(serializers.ModelSerializer):
    def validate(self, attrs):
        attrs['slug'] = slugify(attrs.get('title'))

    class Meta:
        model = Article
```

As you can see, the `Article` model has a unique index on its two properties. When a request is made to create one, the serializer checks the unique constraint before calling validate. As a result, once the slug has been changed in the validate function, it's possible to get error 500's. (Duplicate slugs can be generated in this situation because they strip punctuation, making "great" and "great!" the same.)

Now I realize this isn't necessarily the most practical example, but it gets the idea across about changes in validate not being considered.

**Comment by xordoquy** [comment]
Validate is a cross field validation which requires all the field to be valid.
You should alter the field values in the field's validation method: `validate_<field_name>`

**Comment by lsapan** [comment]
I ordinarily would, but on this example, the field is dependent on the value of a different field. You don't have access to the values from within the individual validate functions.

**Comment by xordoquy** [comment]
@lsapan then it's your responsibility to perform the uniqueness constraint. This becomes complex business rules which you should handle by yourself.

**Comment by lsapan** [comment]
That makes sense. Is there perhaps a "hacky" way to get the value of a different field (before it's been validated of course) from within a field's validation call?

I'd rather do something like that to get the value beforehand rather than add a custom call to check the unique constraint.

**Comment by tomchristie** [comment]
>  Is there perhaps a "hacky" way to get the value of a different field (before it's been validated of course) from within a field's validation call?

No. If you want cross field validation then it *has* to happen inside `.validate()`.

**Comment by lsapan** [comment]
Alright, just figured I'd ask. Thanks guys.

**Comment by tomchristie** [comment]
:+1:
