### ISSUE TITLE
HTTP PUT Silently failing in 3.3.2 

### ISSUE THREAD

**Issue by rahul8590** [tomchristie/django-rest-framework#3806]
I have a simple CRUD application.  It seems to me that, DRF silently fails during HTTP PUT in 3.3.2 
For example, the following code is in my views.py. 

```python
elif request.method == 'PUT':
    print "Request data in HTTP Put ",request.data
    serializer = AlSerializer(alert, data=request.data, partial=True)
    if serializer.is_valid():
        print "data seems to be valid in HTTP PUT"
        if serializer.data['token'] == user_token:
            print "saving the seriaizerd data in PUT"
            serializer.save()
            return Response(serializer.data)
        else:
                return Response({'error': 'Not allowed to access'}, status=status.HTTP_400_BAD_REQUEST)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
```

As you can see, I am trying to access serializer.data before save. In version 3.3.1 , I explicit get an error. But in 3.3.2 , I guess that's not the case. 
 In both cases settings.py has DEBUG = True

**Comment by xordoquy** [comment]
You need to access `validated_data` not `data` which is for serialization.

**Comment by rahul8590** [comment]
duh, I know that!! (thanks for pointing out :) But, thats not the problem I am concerned with. As stated earlier, its the 3.3.2 version **silently failing** on it, without explicitly mentioning it, unlike in version 3.3.1

**Comment by xordoquy** [comment]
Could you be more specific about what the 3.3.1 was doing ? An exception maybe ?

**Comment by rahul8590** [comment]
well 3.3.1 was doing the right thing, by giving an error when the above posted code was executed against a HTTP PUT call.  But in 3.3.2, although it should have given error like 3.3.1, it dint! 
It just silently failed in the error log like 

```bash
[07/Jan/2016 07:59:02] "PUT /data/v1/ HTTP/1.1" 500 12595
```
This lead me to beleive that, I had accidentally set DEBUG as false,  which wasn't the case. So, even thought DEBUG was set to True 3.3.2 was silently failing by logging HTTP 500 (internal server error) , whereas 3.3.1 gave a full blown error page , describing the issue.

**Comment by tomchristie** [comment]
I'd be happy to consider this if it was reduced to a single failing test case - right now this isn't presented as a sufficiently identified issue.
