### ISSUE TITLE
OPTIONS metadata missing fields info on read-only views.

### ISSUE THREAD

**Issue by mordyovits** [tomchristie/django-rest-framework#3808]
Due to the loop at https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/metadata.py#L80 the metadata on fields is only showed for POSTs and PUTs.  I'm not sure what the reasoning is behind that, but I know why I'd want OPTIONS on a read-only endpoint to include fields info: it documents the choices fields.  If you have an IntegerField with choices, the only way a client/developer can see what those interger choices map to is with the OPTIONS method supplying that data.  But it's missing on read-only endpoints.

**Comment by nazarewk** [comment]
Today i had to reimplement quite a lot of redundant code exactly because of this issue when porting from v2 to v3.
Vote up.

**Comment by xordoquy** [comment]
>  If you have an IntegerField with choices, the only way a client/developer can see what those interger choices map to is with the OPTIONS method supplying that data.

Why don't you simply return the named choice itself instead of an integer ?
Seems to me it would make the API much more readable both for human and computers.

**Comment by mordyovits** [comment]
@xordoquy In my case, it's stored as integers because of a 1:1 mapping to the network device data it represents.  It's definitely the right choice, since it means no translation in the main path, and Choices make the user interfaces do the Right Thing anyway.  All this needs is for the OPTINS api to show the choices on read-only endpoints.  Seems reasonable to me; I can't even think of the reason it was excluded in the first place.

**Comment by mordyovits** [comment]
Submitted pull request #3823 
I'm successfully using that patch locally (it's trivial).

**Comment by tomchristie** [comment]
We don't do this because the default generic views *don't* use serializer_class for expressing query parameter filters.

The default OPTIONS behavior isn't going to change greatly at this point - if you want something else then use a custom metadata class.

http://www.django-rest-framework.org/api-guide/metadata/#setting-the-metadata-scheme
