### ISSUE TITLE
'request.data' empty when multipart form data POST in 3.3.x

### ISSUE THREAD

**Issue by richardasaurus** [tomchristie/django-rest-framework#3814]
With `django==1.9.1` and `djangorestframework>3.2.5`

When multipart form data is POSTed containing a file, I've found that `request.data` is an empty `QueryDict`.

Here's a failing create view (raising the assert):
```python
class ImageList(generics.ListCreateAPIView):
    queryset = models.Image.objects.all()
    serializer_class = serializers.ImageSerializer
    parser_classes = (
        parsers.JSONParser,
        parsers.MultiPartParser,
        parsers.FormParser,
    )

    def create(self, request, *args, **kwargs):
        assert 'image_file' in request.data
```

And the POST request:
```
POST /imageservice/images/ HTTP/1.1
Host: 10.10.10.10:8000
Content-Length: 4305
Origin: http://10.10.10.10:8000
X-CSRFToken: zm9YRuwpT760Gw33s8beRSwKnmS0B3Km
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarycb3xV3ESA8zRzpap
Accept: */*
Referer: http://redacted
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

------WebKitFormBoundarycb3xV3ESA8zRzpap
Content-Disposition: form-data; name="image_file"; filename="avatar.png"
Content-Type: image/png

... image data here, redacted
```

I've found if I apply this diff, it will work fine as it did back in version `3.2.5`: https://github.com/tomchristie/django-rest-framework/compare/master...richardasaurus:master

It looks like this code was removed in this commit https://github.com/tomchristie/django-rest-framework/commit/566812ac0b577f79801ec67f86f064cf39ebee01 but I see no mention of this in the `3.3.0` release notes (http://www.django-rest-framework.org/topics/release-notes/#330)

Am I doing something wrong with the request or view? Or is there another reason this has suddenly stopped working? Thanks in advance

**Comment by richardasaurus** [comment]
@tomchristie

**Comment by jholloway7** [comment]
@richardasaurus Do you by chance have any middleware or custom view/mixin, etc that is accessing the underlying Django request.POST before DRF has a chance to parse it with its content negotation mechanism?  

I'm seeing a behavior change here as well, but tracked it down to some middleware that I had written that is trying to generically access request.POST.  

It seems like the stream is 'exhausted' before DRF gets a chance to do anything with it.

I don't know if the regression is in Django or DRF.

**Comment by richardasaurus** [comment]
@jholloway7 the app has a bunch of custom middleware, I'll review behaviour with it all disabled tomorrow and update accordingly thanks.

**Comment by richardasaurus** [comment]
@jholloway7 the problem was this crusty old middleware

```
class AjaxHeaderSetFromPOST(object):
    def process_request(self, request):

        try:
            if ('HTTP_X_REQUESTED_WITH' in request.POST and request.POST.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'):
                request.META['HTTP_X_REQUESTED_WITH'] = 'XMLHttpRequest'
        except IOError:
            pass
        return None
```

which is going in the bin right now.
