### ISSUE TITLE
Returning json

### ISSUE THREAD

**Issue by TheDrifter254** [tomchristie/django-rest-framework#3827]
Hi,
I'm trying to fix a view that used to return data from haystack through django rest framework, I've rewrtitten the view and it's returning the json but the dictionary inside has " " around it so it's read as a string. I've asked the question on stackoverflow http://stackoverflow.com/questions/34765847/json-format-for-python they suggest I convert it to json but that only adds more escapes (double jsonify) will appreciate any help with this.

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by xordoquy** [comment]
On a side note, the answer on SO is correct:

    json.loads("{}") == {}

**Comment by TheDrifter254** [comment]
I fixed it, figured out the issue
