### ISSUE TITLE
Cann't create when using Nested relationships

### ISSUE THREAD

**Issue by mrgaolei** [tomchristie/django-rest-framework#3829]
There's my Example:
```
class Class(models.Model):
    level = models.CharField(u"Level", max_length=20)


class Student(models.Model):
    cls = models.ForeignKey(Class)
    name = models.CharField(u"name", max_length=20)
```

And there's the serializer:
```
class ClassSerializer(serializers.ModelSerializer):
    class Meta:
        model = Class

class StudentSerializer(serializers.ModelSerializer):
    cls = ClassSerializer(many=False, read_only=True)

    class Meta:
        model = Student
```
And I have a normal ViewSet for this.
When I GET /api/student/, everything is OK, Student's `cls` field show as JSON dict.
But I want POST /api/student/ {cls: 1, name: John}
It prompt me `Field cls required`.
What's wrong with it?
I tried set read_only=False, the `/api/student/` accept `Class` field, but I don't want this, I want POST cls_id only. What can I do?

**Comment by xordoquy** [comment]
Hi @mrgaolei 

Please note that this is an issue tracker. The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place for usage questions. 

Thanks!
