### ISSUE TITLE
Using permission_classes to append not replace

### ISSUE THREAD

**Issue by vyscond** [tomchristie/django-rest-framework#3834]
Hello everyone.

On my project i set the permissions below as the default:

```python
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ),
    'PAGE_SIZE': 10
}
```

Everything is working fine until i had to add a custom permissions in two of my classes. So just set the permissions directly on __permission_classes__ attribute:

```python
class MyModelCreate(generics.CreateAPIView):
    permission_classes = (permissions.IsVIPPermission,)
    queryset = models.MyModel.objects.all()
    serializer_class = serializers.MyModelSerializer
```

After a few hours getting the famous `TypeError: int() argument must be a string, a bytes-like object or a number, not AnonymousUser` i realized that view was not using the default permissions set on the __settings__. To solve the problem i just increase the __permission_classes__ set to include the __IsAuthenticated__ permission. No big deal.

So the scenario can resumed with: Every views needs an authenticated user to access them, but only VIP user can use __create views__. 

Now i'm thinking: If need more views using my custom permission i will probably end up write a custom mixin class, right? On this in mind i think that with we have a additional __permission_classes__ attribute like _permission_classes_additional_ that could be used to read the new permissions and append them to the default ones loaded from the settings would be helpful this case.

I know that not that hard write a mixin class, but i thinking with can cut as many line as we can from the code this is a good thing for maintenance?

Beside that it's a wonderful framework, thank to make it free and open!

**Comment by xordoquy** [comment]
Actually you don't even need a mixin:

```
class MyModelCreate(generics.CreateAPIView):
    permission_classes = settings.REST_FRAMEWORK['DEFAULT_PERMISSION_CLASSES'] + (permissions.IsVIPPermission,)
    queryset = models.MyModel.objects.all()
    serializer_class = serializers.MyModelSerializer
```

My 2 cents is that this is easy enough to avoid the addition of an extra configuration.
Maybe we could make it clearer that view permissions override the global settings instead of adding to it.

**Comment by rrauenza** [comment]
... I don't see how this workaround would work?

`settings.REST_FRAMEWORK['DEFAULT_PERMISSION_CLASSES']` is a tuple of strings.  When I try this I get `TypeError: 'str' object is not callable` because `permission_classes` expects classes.

Is there a legit way to get to the default (actual) classes?  

Ah,

```
> from rest_framework.settings import api_settings
> api_settings.DEFAULT_PERMISSION_CLASSES
Out[6]: [rest_framework.permissions.IsAuthenticated]
```

**Comment by pchabros** [comment]
Any solution for this?
