### ISSUE TITLE
Per Site Token

### ISSUE THREAD

**Issue by blaklites** [tomchristie/django-rest-framework#3838]
Right now, we have token generated per user. Unlike Django per-site session, the token of DRF can be used across sites. Can the Token model have a 'site' CharField which stores the domain of the site through which it was created. request.get_current_site().domain will be used here while creating the token? Later in the authentication classes, in addition to the the user, the Token's site is verified against the current request's site. 

If this is not always desirable, there can also be a settings like PER_SITE_TOKEN with default being False which will enable/disable per-site token.

**Comment by jpadilla** [comment]
@blaklites our token authentication is meant to be the most simple implementation possible. What you're describing could definitely be done as a [third party package](http://www.django-rest-framework.org/topics/third-party-resources/).
