### ISSUE TITLE
rest_framework.urls deprecation warnings

### ISSUE THREAD

**Issue by chemary** [tomchristie/django-rest-framework#3840]
I'm getting a ton of warnings when I updated to las Django version, the problem arises when including DRF url in my project urls.
  url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.

**Comment by xordoquy** [comment]
This was already removed some white ago.

**Comment by chemary** [comment]
Thanks, I have DRF 3.3.2 and Django 1.9.1 and I get this error, I will look if there is any error in my code.

**Comment by xordoquy** [comment]
Let us know if something went through.
