### ISSUE TITLE
Add support for timestamps

### ISSUE THREAD

**Issue by Visgean** [tomchristie/django-rest-framework#3856]
It would be handy to add support for timestamps. This could be either controlling by some variable in ``settings`` such as ``USE_TIMESTAMPS`` or by setting DATETIME_FORMATS to something special... 

The changes would very likely effect only https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1034 - methods ``to_internal_value`` and ``to_representation`` and of course, ``DateField`` implementation as well. 
What do you think?

**Comment by xordoquy** [comment]
Looks like a job for the `DurationField`.
It should gain an extra init argument to handle the duration parsing. With that you could either leave the current default or roll your own.

**Comment by tomchristie** [comment]
On balance I think we should just leave this down to custom fields.
