### ISSUE TITLE
No easy way to factor out common endpoint functionality 

### ISSUE THREAD

**Issue by dtheodor** [tomchristie/django-rest-framework#3857]
Hello!

I am having a hard time factoring out common functionality with ApiViews. For each request going through my endpoint, I want to do something like this:

```python
def get(request):
  try:
    data = prepare_data(request)
    result = handle_call(request, data) # this is the actual endpoint-specific work
    response = prepare_response(result)
    return response
  except MyException as e:
    handle_exc(e) # catches app-specific exceptions, re-raises as APIExceptions
```

Keep in mind that these calls do application-specific stuff, not the generic stuff that django rest framework already does such as json deserialization or `APIException` turned into a proper `Response`.

All this "wrapper" functionality is common among a collection of end points _and_ across different HTTP verbs (GET and POST), so I am trying to implement a base class that will take care of performing them. A subclass would then only have to implement their endpoint-specific functionality through `get` or `post`, while common stuff are taken care of outside of these methods.

Ideally, I wanted a single place where I can just wrap with this code. The following line inside `APIView.dispatch()` looks ideal: it is at the place where all django rest framework wrapping has taken place and the user code starts, and it can take care of all HTTP verbs as well.

```python
def dispatch():
  # ...
  response = handler(request, *args, **kwargs)
  # ...
```

However there is no hook that allows to override behavior at that point. I also don't want to copy the whole dispatch into my base class in order to stay compatible with django rest framework updates. The only alternative I have is sprinkling bits of this code in `self.initial()`, `self.finalize_response()` and the worst of all `self.handle_exception()` which is tied to an application-wide `exception_handler`. Doing this results in a really ugly and hacky base class.

With a small change inside dispatch(), factoring out common functionality becomes a piece of cake:

```python
def dispatch():
  # ...
  response = self.handle_request(handler, request, *args, **kwargs)
  # ...

def handle_request(handler, request, *args, **kwargs):
  # this can be overriden
  return handler(request, *args, **kwargs)
```

Thoughts?

**Comment by xordoquy** [comment]
I don't think adding another indirection level will help here.

> The only alternative I have is sprinkling bits of this code in self.initial(), self.finalize_response() and the worst of all self.handle_exception which is tied to an application-wide exception_handler. Doing this results in a really ugly and hacky base class.

Could you be more specific about your assertions ? According to me, they are appropriate.

**Comment by dtheodor** [comment]
Let's try to implement my requirements.

```python
class Base(APIView):
  def initial(request, *args, **kwargs):
    super().initial(request, *args, **kwargs)
    self.obj1, self.obj2 = self._get_obj1_and_obj2(request)

  def finalize_response(request, response, *args, **kwargs):
    response = self._result_to_dict(response)
    return super().finalize_response(request, response *args, **kwargs)
  
  def handle_exception(exc):
    # "re-writing" exceptions, need to instantiate them instead of raise
    if isinstance(exc, ExceptionA):
      exc = NotFound()
    elif isinstance(exc, ExceptionB):
      exc = APIException()
    return super().handle_exception(exc)

class Subclass(Base):
  def post(request, *args, **kwargs):
    a = self.obj1.do_something() # subclass specific
    return self.obj2.do_something_else(a)
```

Also, I tend to implement exception re-raising as a decorator:
```python
def handle_errors(f):
  def wrapped(*args, **kwargs):
    try:
      return f(*args, **kwargs)
    except ExceptionA:
      raise NotFound()
    except ExceptionB:
      raise APIException()
  return wrapped
```

I can decorate the overriden `handle_request`, but theres no way to use this in the `handle_exception`

My suggestion:
```python
class Base(APIView):
  @handle_errors
  def handle_request(handler, request, *args, **kwargs):
      obj1, obj2 = self._get_obj1_and_obj2(request)
      result = handler(request, obj1, obj2, *args, **kwargs)
      response = self._result_to_dict(result)
      return response

class Subclass(Base):
  def post(request, obj1, obj2, *args, **kwargs):
    a = obj1.do_something() # subclass specific
    return obj2.do_something_else(a)
```

I see a couple of things:
* having to set `self.` variables instead of explicitly passing them as arguments. it's been a while now that hidden state is not considered a good practice
* way easier to read what is happening in my suggestion, linear and imperative
* not sure that `initial` and `finalize_response` were designed as framework hooks, but rather as internal impl. (they are actually doing mandatory stuff, hence I need to call super()).

A bad thing about my suggestion:
* It is not easy to implement a second base class that subclasses the original base to further factor out functionality, as the solution has the same problem, i.e. the "wrapper" functionality is not easily re-usable.

**Comment by tomchristie** [comment]
Reasonable request, and appreciate the time put in to explain it thoroughly, but I don't think this is something we'll act on, as I don't believe the extra API surface area, extra indirection, and changes to some very core bits of REST framework is really worth it. There's plenty of ways of dealing with this, either using the public methods suggested, or overriding dispatch (chance of that changing between versions is pretty low by now - so unlikely to be terribly problematic). On balance I think we should just leave these kinds of customizations up to the user.
