### ISSUE TITLE
Clashing @list_routes with resource ids

### ISSUE THREAD

**Issue by faddey-w** [tomchristie/django-rest-framework#3859]
I want to create such viewset:
```python
class MyViewSet(RetrieveModelMixin, GenericViewSet):

    #blah blah...

    @list_route(['GET'])
    def some_action(self, request, *args, **kwargs):
        # do stuff...
```
My model has string primary keys.

Generated with `DefaultRouter` URL regexes list looks like this:
```
^api/resource/some_action/
^api/resource/(?P<pk>[^/.]+)/
```

If my model instance will have `pk` equal to `"some_action"`, this instance will be inaccessible through api.

I see the solution in adding some prefix before lookup portion:
```
^api/resource/some_action/
^api/resource/~(?P<pk>[^/.]+)/
```

It would be nice if `DefaultRouter` will support such feature.

**Comment by xordoquy** [comment]
You can already override your router's route and change the order.
There are pro and con for both order so I'm leaving at currently is.

**Comment by faddey-w** [comment]
Do you mean overriding class attribute `route`?
Overriding attribute `route`, I see two possible ways of getting rid of a conflict between `@list_route` and object with same key:
1) just reorder routes. it does not works
2) change directly Route.url attribute. I think it is quite dirty and not so handy as just adding one string to viewset definition.

**Comment by xordoquy** [comment]
> Do you mean overriding class attribute route?
Yes

1. Right, reordering isn't enough though rewriting the `Router.routes` to match your pattern should.
2. Agreed altering `Route.url` is dirty and should be avoided.
