### ISSUE TITLE
Validators are not thread safe

### ISSUE THREAD

**Issue by skyjur** [tomchristie/django-rest-framework#3863]
If I need extra context out of serializer for validators documentation suggest me to do:

```
class MyValidator(object):
    def set_context(self, serializer):
        self.some_state = True

    def __call__(self, data):
        return True
```

Looking at source code I see that validators have been made exempt from deepcopy, and comment misleadingly says that validators are immutable:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L582

I validated that state persist globally doing this:

```
>>> class MySerializer(serializers.Serializer):
    class Meta:
        validators = [MyValidator()]
>>>  MySerializer(data={}).is_valid()
True
>>> MySerializer.Meta.validators[0].some_state
True
```

**Comment by skyjur** [comment]
Fix could possibly look like this:
https://github.com/Tictrac/django-rest-framework/commit/0c301868a30f595dc7dc90ed7ebc4c129720ab39

**Comment by skyjur** [comment]
Or maybe this would be better fix https://github.com/Tictrac/django-rest-framework/commit/56f53a48bfe5adb7a62fb621e97c6e589789b9bf

Making a copy in the very last moment, and only when needed. This should guarantee that state is never shared.

**Comment by tomchristie** [comment]
Seems okay. Making that as a pull request would be a good plan. so we can see the tests run through.

**Comment by xordoquy** [comment]
Duplicates of #3713 ?

**Comment by skyjur** [comment]
Yes, duplicate indeed

**Comment by tomchristie** [comment]
Closing in favour of #3713.
