### ISSUE TITLE
Trigger user_logged_in signal after obtaining auth token

### ISSUE THREAD

**Issue by jpadilla** [tomchristie/django-rest-framework#3869]
I'm wondering what people think about triggering [`user_logged_in`](https://docs.djangoproject.com/en/1.9/ref/contrib/auth/#django.contrib.auth.signals.user_logged_in) after obtaining an auth token. It's something that's come up before in https://github.com/GetBlimp/django-rest-framework-jwt/pull/171.

**Comment by tomchristie** [comment]
I'd say no. It's not exactly equivalent to a login, so lets keep any behavior there in the realm of "customize this class if you want different behavior"
