### ISSUE TITLE
Getting Empty Ordereddict if no file is submitted

### ISSUE THREAD

**Issue by a1Gupta** [tomchristie/django-rest-framework#3871]
Its my model and I want to make ImageField optional in serializer -

class SbmWebsiteAdditionalScreenshot(TimeStampedModel):
    website = models.ForeignKey(
        'SbmWebsite', related_name='additional_screenshots')
    screenshot = models.ImageField(
        upload_to='website/interim/additional_screenshot/', blank=True)
    associated_additional_screenshot = models.ForeignKey(
        'websites.WebsiteAdditionalScreenshot',
        related_name='sbn_website_associated_additional_screenshot',
        null=True, editable=False, blank=True)
    request_deletion = models.BooleanField(default=False, editable=False)

I tried this three options.

class SbmWebsiteAdditionalScreenshotSerializer(serializers.ModelSerializer):
    is_interim = serializers.SerializerMethodField()

    def get_is_interim(self, obj):
        return True

    class Meta:
        model = SbmWebsiteAdditionalScreenshot
        fields = [
                'screenshot', 'associated_additional_screenshot',
                'request_deletion',
                'id', 'is_interim'
                ]

data =  [{'id': 28, 'associated_additional_screenshot': None, 'is_interim': True}]
>>f= SbmWebsiteAdditionalScreenshotSerializer(data=data, many=True)
>>f.is_valid()
>>True
>>f.validated_data[0].items()
>>[]

class SbmWebsiteAdditionalScreenshotSerializer(serializers.ModelSerializer):
    is_interim = serializers.SerializerMethodField()
   screenshot = serializers.ImageField(required=False)

    def get_is_interim(self, obj):
        return True

    class Meta:
        model = SbmWebsiteAdditionalScreenshot
        fields = [
                'screenshot', 'associated_additional_screenshot',
                'request_deletion',
                'id', 'is_interim'
                ]

>>f= SbmWebsiteAdditionalScreenshotSerializer(data=data, many=True)
>>f.is_valid()
>>True
>>f.validated_data[0].items()
>>[]

class SbmWebsiteAdditionalScreenshotSerializer(serializers.ModelSerializer):
    is_interim = serializers.SerializerMethodField()
    screenshot = ImageField(allow_empty_file=True, use_url=True)

    def get_is_interim(self, obj):
        return True

    class Meta:
        model = SbmWebsiteAdditionalScreenshot
        fields = [
                'screenshot', 'associated_additional_screenshot',
                'request_deletion',
                'id', 'is_interim'
                ]

>>f= SbmWebsiteAdditionalScreenshotSerializer(data=data, many=True)
>>f.is_valid()
>>False
>>f.errors
>>[OrderedDict([('screenshot', [u'No file was submitted.'])])]

How to make ImageField optional and serialize data without uploading image ?

**Comment by xordoquy** [comment]
Hi,

This is an issue tracker. The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by a1Gupta** [comment]
Same problem is mentioned here too in issue #2494

**Comment by xordoquy** [comment]
If you think there's a bug in Django REST framework, the first step would be to highlight that with a test case we can easily reproduce.
