### ISSUE TITLE
Difference between serialization of non-required fields with default-valued fields

### ISSUE THREAD

**Issue by dtheodor** [tomchristie/django-rest-framework#3873]
Hi,

I have an issue when trying to serialize data from instances. My serializers have a lot of non-required fields, some of which have default values. My  instance objects do not have _all_ attributes defined on the serializer, but they do have all _mandatory_ attributes defined there. I see a difference in behavior between these two types of non-required fields:

A non-required field is simply skipped from serialization:
```python
class Ser1(Serializer):
  field = CharField(required=False)

instance = object()
assert Ser1(instance).data == {}
```
A non-required field with a default value however throws an error
```python
class Ser2(Serializer):
  field = CharField(default='value1')

instance = object()
assert Ser2(instance).data == {'field': 'value1'} # throws AttributeError
```

I would expect the latest assertion to be true. At least this is how _deserialization_ works:

```python
class Ser3(Ser1, Ser2): pass

s = Ser3(data={})
s.is_valid()
assert s.data == {'field': 'value1'}
```

Is there a reason why serialization between these two field types is implemented differently and in contrast to its deserialization counterpart?

**Comment by xordoquy** [comment]
[default](http://www.django-rest-framework.org/api-guide/fields/#default) is for deserialization, not for serialization. Documentation should probably mention that.

**Comment by dtheodor** [comment]
I see. Does my request make sense as a patch?

**Comment by xordoquy** [comment]
I'm sorry, what request are you referring to ?

**Comment by dtheodor** [comment]
`assert Ser2(instance).data == {'field': 'value1'}` This to work.

**Comment by xordoquy** [comment]
I don't think so because:
- it changes the current behavior -a lot-
- your instances should handle that themselves already

I'm a bit curious though about the use case.

**Comment by dtheodor** [comment]
Use-case is exactly the same as deserialization. As you want to support missing fields with default values when data is coming in, you may also need to support missing fields with default values for data going out.

>your instances should handle that themselves already

Same can be said for data coming in right? Also, my 'instances' may happen to be dicts with missing keys, in which case I use the serializer as a dict specification.

**Comment by xordoquy** [comment]
> Same can be said for data coming in right?

Actually no. Serialization move data from unknown sources (the external world) into the safe one. Therefore you need sanitization. However, in the other direction you don't need all that since you're already in control of the data.

**Comment by dtheodor** [comment]
>However, in the other direction you don't need all that since you're already in control of the data.

Right... what's the point of response serializers then?

**Comment by xordoquy** [comment]
Serializing non basic types such as UUID, DateTime / Date and so on and avoid some boilerplate.

**Comment by dtheodor** [comment]
>avoid some boilerplate.

exactly what I want to achieve with this

**Comment by tomchristie** [comment]
As @xordoquy notes - we can teak the documentation to make it more clear that `default` is for validation/deserialization, but we won't be making any behavioral changes here. You can always use a custom field class if you need some specific behavior.

**Comment by dtheodor** [comment]
Ok, understandable. However I don't see why you are closing the issue, I do not see a documentation fix yet. I spent plenty of time trying to figure why this doesn't work as I expected.

**Comment by xordoquy** [comment]
@dtheodor Strictly speaking the issue isn't about documentation. Also the work is based on volunteer time, thus extremely limited and this is quite low priority. Will be happy to consider PR for that.
