### ISSUE TITLE
PAGE_SIZE_QUERY_PARAM is ignored

### ISSUE THREAD

**Issue by savvaoff** [tomchristie/django-rest-framework#3874]
The param is ignored.

in the settings:
```
REST_FRAMEWORK = {
    'PAGE_SIZE': 30,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
```

when we do:
```
/transactions?page_size=10&page=1
```

the "page_size" param is ignored. we get 30 records instead of 10.

**Comment by xordoquy** [comment]
The only attribute that can be set through settings is `PAGE_SIZE`. `page_size_query_param` needs to be set on the `PageNumberPagination` class as mentioned in the documentation.

**Comment by taojy123** [comment]
@xordoquy 
hi, why don't you make page_size_query_param settable in settings?
Now I have to create a new class that inherits from PageNumberPagination d and rewrite only page_size_query_param.
It would be much better if a PAGE_SIZE_QUERY_PARAM configuration was added to the settings.

**Comment by xordoquy** [comment]
Going down that way DRF would end with thousands of settings.
`PAGE_SIZE` covers the most common use case, the other use cases require to override the pagination class.

**Comment by taojy123** [comment]
Then could you set the default value of page_size_query_param in PageNumberPagination to "page_size" 😏

**Comment by xordoquy** [comment]
> Then could you set the default value of page_size_query_param in PageNumberPagination to "page_size" 😏

no, because that would allow clients to control the pagination by default which is not something you'd want for safety reasons. Imagine you have billons rows and a client send a `page_size=99999999999`.
