### ISSUE TITLE
"Serializing objects" section in documentation does not matches the actual behaviour

### ISSUE THREAD

**Issue by filipeximenes** [tomchristie/django-rest-framework#3881]
``Serializing objects`` section in the ``Serializers`` documentation page does not matches the real behaviour in a python shell.

Documentation shows:
```
{'email': u'leila@example.com', 'content': u'foo bar', 'created': datetime.datetime(2012, 8, 22, 16, 20, 9, 822774)}
```
as the expected result for
```
serializer.data
```
when running the code in the shell it will give:
```
{'content': u'foo bar', 'email': u'leila@example.com', 'created': '2016-01-27T19:00:52.355728'}
```
I'm not sure but I suspect this is due some change from DRF 2 to 3.

**Comment by xordoquy** [comment]
indeed, thanks for reporting.
