### ISSUE TITLE
AdminRenderer raises AttributeError while rendering serializer errors 

### ISSUE THREAD

**Issue by ugurunver** [tomchristie/django-rest-framework#3883]
Traceback:
```
File "/home/ugur/project/venv/lib/python3.4/site-packages/rest_framework/renderers.py", line 707, in render
    response = view.get(request, *view.args, **view.kwargs)
AttributeError: 'GGAdvertViewSet' object has no attribute 'get'
```

So it points that line:
https://github.com/tomchristie/django-rest-framework/blob/d738ad7ae603e58eedbc26b186878a199515cb86/rest_framework/renderers.py#L707

The actual problem is; when you use a list_route that accepts only POST method, your `view` object (on that line 707) will not have a `.get`  method. 

Ofcourse workaround is adding simply a 'GET' method to list_route methods list, but it is a dirty solution for a clean api. What is real solution?

**Comment by xordoquy** [comment]
Feel free to reopen if you think it is a Django REST framework bug. In that case we'll need a test case to highlight the bug.
Otherwise, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
