### ISSUE TITLE
List of Dictionaries passing being received as String

### ISSUE THREAD

**Issue by vyscond** [tomchristie/django-rest-framework#3884]
So i was trying to pass this JSON as payload to API
```json
{
  "field_1": 1,
  "field_2_uuid": "436c3e71-787e-4cd9-bbbb-284560cddde1",
  "field_3_list": [
    {"field_a": 1, "field_b": 18}
  ]
}
```

using the __Client__ object from __django.test__: 

```python
payload = {
  "field_1": 1,
  "field_2_uuid": "436c3e71-787e-4cd9-bbbb-284560cddde1",
  "field_3_list": [
    {"field_a": 1, "field_b": 18}
  ]
}
self.client.post("/api/url", json.dumps(payload), content_type="application/json")
```

The serializer responsible is this one:

```
class Table2_Serializer(serializers.Serializer):
    
    field_a = serializers.IntegerField(write_only=True)
    field_b = serializers.IntegerField(write_only=True)

class Table1_Serializer(serializers.ModelSerializer, SerializerUtils):
    field_1 = serializers.IntegerField(write_only=True)
    field_2 = serializers.CharField(write_only=True)
    field_3_list = serializers.ListField(child=Table2_Serializer(), write_only=True)
```

But all i got was a 400 error saying that __field_3_list__ was expecting a dictionary but got a str.

After that i changed __field_3_list__ to JSONField and overrided the __create__ function to see how was the structure of the data.

```
class Table2_Serializer(serializers.Serializer):
    
    field_a = serializers.IntegerField(write_only=True)
    field_b = serializers.IntegerField(write_only=True)

class Table1_Serializer(serializers.ModelSerializer, SerializerUtils):
    field_1 = serializers.IntegerField(write_only=True)
    field_2 = serializers.CharField(write_only=True)
    field_3_list = serializers.JSONField(write_only=True)

    @transaction.atomic
    def create(self, validated_data):
        logger.debug(validated_data)
```

The log show that the dictionary over the __field_3_list__ is being received as a string

```json
{
  "field_1": 1,
  "field_2_uuid": "436c3e71-787e-4cd9-bbbb-284560cddde1",
  "field_3_list": [
    "{'field_a': 1, 'field_b': 18}"
  ]
}
```

So i was thinking if this is a bug (for real) or am i missing something?

**Comment by xordoquy** [comment]
The test client already does the json dump. The examples at http://www.django-rest-framework.org/api-guide/testing/ show you pass it the raw structure while declaring the json content type.

**Comment by vyscond** [comment]
This link show how to pass with the rest_framework tools and the request factory. So it seems that i need to start using it?

I got other a 12 sets of post (create) request with the client configured like that and everything work fine on the other serializer that don't have nested json or use ListField.

Even though this does not explain why i'am receiving on the serializer the dictionaries as plain strings. Is the ListField only available to receive list of Strings?

**Comment by vyscond** [comment]
On the purpose of debugging i've created a custom Field. The __to_internal_value__ still receives the nested data from the list as plain strings and with single quotes.

**Comment by xordoquy** [comment]
> Even though this does not explain why i'am receiving on the serializer the dictionaries as plain strings.

This is exactly the reason *why* you do have that.

**Comment by vyscond** [comment]
So you are saying that nested json only working with the rest_framework request factory?

**Comment by xordoquy** [comment]
I'm sorry, my initial comment doesn't hold because DRF's does the json dump with the `format` extra arg and not just with the `content_type` one.

**Comment by vyscond** [comment]
What bothers me is that i'am almost sure the correct answer would be pass the __many__ arg to __Table2_Serializer__ but it's just not working as expected

**Comment by vyscond** [comment]
So i switched from the __django.test.Client__ to __rest_framework.test.APIClient__ and the results are:

1 - set __field_3_list__ to `serializers.ListField(child=Table2_Serializer(), write_only=True)` now works as expected.

2 - set __field_3_list__ to `Table2_Serializer(write_only=True, many=True)` returns error `{'field_3_list': {'non_field_errors': ['Expected a list of items but got type "dict".']}}`

There is something on the _path_ between __django.test.Client.post__ and the **Serializer.\_\_init\_\_** that makes the nested __List__ of __Dictionaries__ be casted as __List__ of __Strings__. 

I also debugged __data__ from the **Serializer.\_\_init\_\_** and it's confirmed that suspicious of the data being incorrectly modified before the __serializer__ receives it.

I'm worried if this is a issue is not only related to the __django.test.Client__ .-.

**Comment by angvp** [comment]
I'm having a similar issue but not with dictionaries but lists .. I even put debugger in the middle and from the view I got a list of strings (correct way) but when returns that to the client it returns just a string with the first element of the list :/

**Comment by tomchristie** [comment]
Someone want to try to break this issue down to a s smaller more clearly identified issue?

**Comment by vyscond** [comment]
If you replace the Django client with the DRF client for test everything will be fine. Yeah it's totally awkward that Django's client can't _mock_ the requests properly.

Why this is happening? Still don't know, and i might need more time to get back to project related to this issue. :/

**Comment by tomchristie** [comment]
Closing due to lack of properly delimited, replicable issue.

**Comment by angvp** [comment]
Hey @tomchristie I've digging about this issue and sadly, is not limited just to the test client, it's an actual bug on DRF, (actually had to use JsonResponse from django because the response from DRF was converting the list to string) I don't have plenty of time now for publishing the bug and the research, but I'll do it on a new issue when I'll be at home tonight and will reference this one. Sadly haven't found a patch for it, but as I said I will publish what I have late tonight. Regards

**Comment by tomchristie** [comment]
Okay, will reconsider when there's something clearer to work against.

**Comment by devrajvlpt** [comment]
Hi, @tomchristie This bharathi raja when i pop data of foreign key table value it becomes ordereddict 
which i couldn't  save the children table. Kindly help to find a way to solve this

**Comment by andrews88l** [comment]
@tomchristie I know this is a little stale, but I have the same issues with a nested serializer returning a list of strings rather than a list of objects. I think I've narrowed down the problem here walking through the deserialization process with pdb.set_trace().

When "run_validation()" is run on the serializer (line 421 in rest_framework.serializers), we move along to line 431, where the value is set value = self.to_internal_value()

From "to_internal_value()" (line 441 in rest_framework.serializers), we continue merrily until line 459 where we execute primitive_value = field.get_value(data). This is the point where I am returned an empty list from my list of strings.

Moving over to rest_framework.fields, there are a number of options, and I'm assuming it's being processed as either a SerializerMethodField (line 1763) or a ListField (line 1593), but I'm not sure which and frankly probably a little over my head.

I'd love to help if I can find a solution, but would definitely need some direction.

**Comment by xordoquy** [comment]
@andrews88l a code sample would be a good place to bootstrap the discussion otherwise it's a bit too abstract.

**Comment by andrews88l** [comment]
Sure thing, sorry about that, here you go:

Models.py

```
@python_2_unicode_compatible
class StyleTag(TimeStampedModel):
    text = models.CharField(max_length=500, unique=True)
    category = models.CharField(max_length=100, default='other')

    class Meta:
        unique_together = (('text', 'category'),)

    def __str__(self):
        return self.text

@python_2_unicode_compatible
class Style(TimeStampedModel):
    rootStyle = models.CharField(
        max_length=15,
        unique=True
    )
    price = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        default=0
    )
    dominantColors = models.ManyToManyField(
        StyleTag,
        blank=True,
        related_name='dominantColors',
    )
    accentColors = models.ManyToManyField(
        StyleTag,
        blank=True,
        related_name='accentColors'
    )
    tags = models.ManyToManyField(
        StyleTag,
        blank=True,
        related_name='tags'
    )

    def __str__(self):
        return self.rootStyle
```

Serializers.py

```
class StyleTagSerializer(serializers.ModelSerializer):
	class Meta:
		model = StyleTag
		fields = ('text', 'category')
		extra_kwargs = {
			'text' : {'validators' : []},
			'category' : {'validators' : []},
			'id' : {
				'read_only' : False,
				'required' : False
			}
		}


class StyleSerializer(serializers.ModelSerializer):
	dominantColors = StyleTagSerializer(many=True, required=False)
	accentColors = StyleTagSerializer(many=True, required=False)
	tags = StyleTagSerializer(many=True, required=False)

	class Meta:
		model = Style
		fields = (
			'rootStyle',
			'price',
			'dominantColors',
			'accentColors',
			'tags',

def get_tag_objects(self, raw_data):
		tag_objects = []
		for tag in raw_data:
			try:
				obj = StyleTag.objects.get(text=tag['text'], category=tag['category'])
			except StyleTag.DoesNotExist:
				serialized = StyleTagSerializer(data=tag)
				if serialized.is_valid(raise_exception=True):
					obj = serialized.create(serialized.data)
					obj.save()
			tag_objects.append(obj)
		return tag_objects

	def create(self, validated_data):
		dominantColor_data = validated_data.pop('dominantColors', None)
		accentColor_data = validated_data.pop('accentColors', None)
		tag_data = validated_data.pop('tags', None)
		m2mSave = False
		style = Style.objects.create(**validated_data)
		if dominantColor_data:
			m2mSave = True
			for tag in self.get_tag_objects(dominantColor_data):
				style.dominantColors.add(tag)
		if accentColor_data:
			m2mSave = True
			for tag in self.get_tag_objects(accentColor_data):
				style.accentColors.add(tag)
		if tag_data:
			m2mSave = True
			for tag in self.get_tag_objects(tag_data):
				style.tags.add(tag)
		if m2mSave:
			style.save()
		return style

	def update(self, instance, validated_data):
		dominantColor_data = validated_data.pop('dominantColors', None)
		accentColor_data = validated_data.pop('accentColors', None)
		tag_data = validated_data.pop('tags', None)
		instance.rootStyle = validated_data.get('rootStyle', instance.rootStyle)
		instance.price = validated_data.get('price', instance.price)
		if dominantColor_data:
			instance.dominantColors.set(self.get_tag_objects(dominantColor_data))
		else:
			instance.dominantColors.clear()
		if accentColor_data:
			instance.accentColors.set(self.get_tag_objects(accentColor_data))
		else:
			instance.accentColors.clear()
		if tag_data:
			instance.tags.set(self.get_tag_objects(tag_data))
		else:
			instance.tags.clear()
		instance.save()
		return instance
```

Views.py

```
class StyleTagViewSet(viewsets.ModelViewSet):
	queryset = StyleTag.objects.all().order_by('id')
	serializer_class = StyleTagSerializer

class StyleViewSet(viewsets.ModelViewSet):
	lookup_field = 'rootStyle'
	queryset = Style.objects.all().order_by('rootStyle')
	serializer_class = StyleSerializer
```

**Comment by andrews88l** [comment]
@xordoquy Hey, thanks for responding... the light of a new day seemed to have helped. I overwrote the to_internal_value method and everything seems to be working better...

Sorry about that.

**Comment by xordoquy** [comment]
@andrews88l no problem, glad you could got it working.

**Comment by Edison-A-N** [comment]
If use client.post(...., format='json'), then when use request.data.getlist method, it failed because request.data was set as a dict type but not QueryDict

**Comment by xordoquy** [comment]
The previous comment seems unrelated to the issue and sounds more appropriate in the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) that is the best place to take this discussion and other usage questions. Thanks!
