### ISSUE TITLE
Problem with HTML rendering for serializer fields API guide docs page?

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [tomchristie/django-rest-framework#3885]
Something is going wrong with how this line (299 in the md file)

   https://github.com/tomchristie/django-rest-framework/blame/master/docs/api-guide/fields.md#L299

is being rendered when output as HTML here

   http://www.django-rest-framework.org/api-guide/fields/#date-and-time-fields

That header has become mangled. Not sure about the nature of the problem since the markdown seems to render fine when viewed via Github.

**Comment by xordoquy** [comment]
not sure what happened, will regenerate it to see if that fixes.

**Comment by tomchristie** [comment]
Not clear to me what this refers to. Going to assume that the issue has since resolved itself. Happy to reconsider if anyone can give more info.

**Comment by i-s-o-g-r-a-m** [comment]
@tomchristie problem is still there, maybe shifted lines in the intervening 7 months, I'm not sure.

See this line https://github.com/tomchristie/django-rest-framework/blame/master/docs/api-guide/fields.md#L308

And then compare to how it is being rendered here http://www.django-rest-framework.org/api-guide/fields/

The words are being rendered out of order.

**Comment by anoopmalav** [comment]
Nothing seems to be wrong with **api-guide/fields.md**

After upgrading _mkdocs_ to 0.15.3 and building documentation from master branch It is working fine.

Please check attached screen-shots.

![screenshot from 2016-10-14 16-05-09](https://cloud.githubusercontent.com/assets/9918965/19384846/265e6d9c-9229-11e6-84e0-9bab8873fac5.png)

![screenshot from 2016-10-14 16-05-32](https://cloud.githubusercontent.com/assets/9918965/19384847/26fc1a24-9229-11e6-9507-26e3379a6c36.png)

Maybe rebuilding the docs will fix the issue.

**Comment by tomchristie** [comment]
Thanks folks! Updated, rebuilt and now resolved. 👍 

![image](https://cloud.githubusercontent.com/assets/647359/19389468/17d86ba4-921c-11e6-8d11-595766572ae2.png)
