### ISSUE TITLE
internationalization in admin interface rest_framework.authtoken

### ISSUE THREAD

**Issue by mnach** [tomchristie/django-rest-framework#3886]
Hello!

Made from [this](https://groups.google.com/forum/#!topic/django-rest-framework/P-Srq7wW87I) thread.

Suggested changes:
- new attributes in [models.Token fields](https://github.com/mnach/django-rest-framework/blob/master/rest_framework/authtoken/models.py#L20-L23) verbose_name=_("label")
- new [Meta-options](https://github.com/mnach/django-rest-framework/blob/master/rest_framework/authtoken/models.py#L25-L31) verbose_name & verbose_name_plural
- Labels in [AuthTokenSerializer](https://github.com/mnach/django-rest-framework/blob/master/rest_framework/authtoken/serializers.py#L8-L9) fields in case of usages in Brousable API
- provide AppConfig class as described in [django documentation](https://docs.djangoproject.com/en/1.7/ref/applications/#for-application-authors) with verbose_name came through ugettext_lazy

**Comment by xordoquy** [comment]
Thanks @mnach.

I'm going to close the issue as we won't have time to process it.
This doesn't mean this feature is refused: I will consider it if it comes with in the form of a pull request.
