### ISSUE TITLE
Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.exceptions.PermissionDenied'>

### ISSUE THREAD

**Issue by JensTimmerman** [tomchristie/django-rest-framework#3893]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 401, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 332, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'rest_framework.exceptions.PermissionDenied'>`.
```

When a request with insufficient permissions is made in views.dispatch the following happens:

in dispatch:
self.initial (request)
will call self.check_permissions(request)
which will call self.permission_denied(request)
this will raise a rest_framework.exceptions.PermissionDenied()

this exception is except'ed in dispatch, where
respons = self.handle_exception(exc) is called

handle_exception only checks for exceptions of instance `NotAuthenticated or AuthenticationFailed`, but not for PermissionDenied (which would also be appropriate for a 403_FORBIDDEN response, no?)

After this, response is generated as by `self.settings.EXCEPTION_HANDLER(exc)`
which in this case does not seem to generate a valid response, since I'm getting this internal server error.

It would be nice if:
1. The response was 403_FROBIDDEN if there's a Permissiondenied
2. The default self.settings.EXCEPTION_HANDLER would print out some info on how to change it's behavior (at the moment I don't know where to start looking to set the default exception handler)
3. The default EXCEPTION_HANDLER would generate valid HttpResponse's

**Comment by JensTimmerman** [comment]
Further investigation reveals that the default exception_handler is the `exception_handler` method in views.py

which does
```

    elif isinstance(exc, PermissionDenied):
        msg = _('Permission denied.')
        data = {'detail': six.text_type(msg)}

        set_rollback()
        return Response(data, status=status.HTTP_403_FORBIDDEN)
```

which looks ok at first, but it turns out `PermissionDenied` is `django.core.exceptions.PermissionDenied` whereas a `rest_framework.exceptions.PermissionDenied` was raised.

**Comment by JensTimmerman** [comment]
see https://github.com/tomchristie/django-rest-framework/pull/3894 for  a proposed fix.

**Comment by JensTimmerman** [comment]
The issue seems to be that `exceptions.PermissionDenied` is raised somewhere, instead of `exceptions.PermissionDenied()`

Since the error prints out `<class 'rest_framework.exceptions.PermissionDenied'>` instead of `PermissionDenied()`

But I can't seem to figure out where this is raised.

**Comment by tomchristie** [comment]
As it stands there's nothing to convince me that this isn't a case of the view returning PermissionDenied rather than returning a response object.

**Comment by JensTimmerman** [comment]
@tomchristie Thank you for this clarification of this error, you were completely right!

I had to convince myself by writing a few testcases first, so here you go https://github.com/tomchristie/django-rest-framework/pull/3895

For people ending up on this issue in the future
This happens when your view does
`return PermissionDenied()`
instead of 
`raise PermissionDenied()`

Thank you again @tomchristie

**Comment by tomchristie** [comment]
:+1:
