### ISSUE TITLE
Graphene integration

### ISSUE THREAD

**Issue by pezioz** [tomchristie/django-rest-framework#3899]
I think it would be a good idea to integrate [graphene](https://github.com/graphql-python/graphene) into django rest framework.

Graphene implement GraphQL from facebook with python and it also have an implementation for django.

Do you think about integrate it?

**Comment by xordoquy** [comment]
What do you mean by integrating it to Django REST framework ?
Graphene Python already seems to work with Django and has a different support scope from DRF.

**Comment by ankitml** [comment]
Restful APIs are very different from GraphQL ones. I agree with @xordoquy that this integration would not make sense.

**Comment by xordoquy** [comment]
I'm not saying it doesn't make sense, I want to understand what sort of integration is meant here before making my mind.

**Comment by tomchristie** [comment]
In all likelihood we *will* be looking into providing some level of GraphQL integration at some point, but this ticket isn't actionable or specific at this point in time.

**Comment by pezioz** [comment]
Sorry if put my ticket in the wrong place. It is an idea of evolution.

I think about choosing REST or GraphQL. It would be great to have the possibility to choose between of both.

The idea behind that is to use all the work already done in drf like permissions, admin... with graphql or rest

I know in the name of the project it is oriented REST. But it might be possible to have a common core and then choose to having a GraphQL endpoint or a REST endpoint.

I hope this will clarify my point.

**Comment by tomchristie** [comment]
Not a problem - all good feedback :+1:

**Comment by rattrayalex** [comment]
@tomchristie I'm curious if you have thoughts on the integration so far – I saw the possibility mentioned on a [funding page](https://github.com/tomchristie/django-rest-framework/blob/372acbc4e9f6a2407c5abca8da8512c9d1d0b03b/docs/topics/funding.md#roadmap). Have you had the chance to play around with graphql yet? Do you have any thoughts on how it might relate to drf in the future?

**Comment by rattrayalex** [comment]
Whoops, looks like that should probably be a topic for the discussion group - apologies!

**Comment by rattrayalex** [comment]
But for others who come here - [this](https://groups.google.com/forum/#!searchin/django-rest-framework/graphql/django-rest-framework/gjRBPQ5_7TY/cN-VPjy9mKUJ) seems to answer my question at a high level.

**Comment by Musbell** [comment]
https://github.com/graphql-python/graphene/issues/249

**Comment by Musbell** [comment]
How to use Graphene with Django REST Framework authentication https://github.com/graphql-python/graphene/issues/249

**Comment by esistgut** [comment]
Is there any plan to add GraphQL support?
