### ISSUE TITLE
Using non model backend

### ISSUE THREAD

**Issue by gulfpearl** [tomchristie/django-rest-framework#3907]
Is there a complete example somewhere of building a serializer for a rest API backend instead of a model? This would be a useful example to add to the docs, maybe use RIAK as an example with a GenericViewSet for full CRUD.

**Comment by auvipy** [comment]
you need to use/create RIAK serializer

**Comment by jpadilla** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
