### ISSUE TITLE
Pagination Docs not up-to-date

### ISSUE THREAD

**Issue by DESHRAJ** [tomchristie/django-rest-framework#3917]
For reference, see http://djangorestframework.readthedocs.org/en/latest/api-guide/pagination/

**Comment by xordoquy** [comment]
There isn't much we can do without further information.
Note that the official documentation is at http://django-rest-framework.org/ and the RTD one built 4 days ago so it should be up to date.

**Comment by DESHRAJ** [comment]
In the latest docs, it is mentioned that `PaginationSerializer` can still be used with the latest version of drf but what I find on stackoverflow answers that it is being removed for versions >=3.1. Please update the docs if this is correct otherwise ignore. 

Satckoverflow Link: https://stackoverflow.com/questions/31500192/django-rest-framework-error-cannot-import-name-paginationserializer/31500287#31500287

**Comment by xordoquy** [comment]
@DESHRAJ  feel free to contact whoever owns that project on readthedocs. This one is out of our reach.

**Comment by xordoquy** [comment]
also note that their documentation version *does* include PaginationSerializer as it's for 3.0.x
