### ISSUE TITLE
Metadata API showing different methods than browsable API

### ISSUE THREAD

**Issue by MattyDub** [tomchristie/django-rest-framework#3921]
I'm trying to get metadata on a `ModelViewSet`, and I am only seeing OPTIONS in the  `allowed_methods`. 

I have the following serializer:
```
class FooSerializer(serializers.ModelSerializer):

    class Meta:
        model = Foo
        fields = '__all__'
```
and the following ViewSet:

```
class FooViewSet(viewsets.ModelViewSet):
    queryset = Foo.objects.all()
    serializer_class = FooSerializer
```

...and the following code doesn't give me any actions:

```
        # this is in the post() of a View that extends APIView
        m_class = FooViewSet.metadata_class()
        metadata = m_class.determine_metadata(request, FooViewSet())
```

The results are:
```
    "foo_meta": {
        "description": "",
        "name": "Foo",
        "parses": [
            "application/json",
            "application/x-www-form-urlencoded",
            "multipart/form-data"
        ],
        "renders": [
            "application/json",
            "text/html"
        ]
    },
```

How do I get the `POST` options inside a view function? That is, how do I get the `metadata_obj["actions"]["POST"]` to show up? I see them fine when using the browsable API. I don't want to actually make an `OPTIONS` request from a view function, but clearly I am calling the metadata API incorrectly. Any help is appreciated.

**Comment by xordoquy** [comment]
Likely because you don't have permissions on the actions.

Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by MattyDub** [comment]
Actually, it wasn't permissions. I simply needed to use the metadata API a little differently. This is what I was looking for:

```
from rest_framework import metadata
...
        foo_meta = metadata.SimpleMetadata().get_serializer_info(FooSerializer())
...
```

Could I update the metadata docs to include something like this? I could have a pull request shortly if that would be helpful.

**Comment by MattyDub** [comment]
Oh and thanks for the link to the discussion group - didn't know that was there!
