### ISSUE TITLE
CSRF validation fails while posting via HTML Form but not on Raw data in rest framework backend

### ISSUE THREAD

**Issue by sspross** [tomchristie/django-rest-framework#3922]
- Django version 1.9.2
- Rest framework version 3.3.2:

I'm testing my API in the rest framework backend on localhost using `http://localhost:8000/api/v1/my-model/` in my browser. If I try to create a new instance of my model via a HTML Form POST , I'm getting the following CSRF Error:

````
{
    "detail": "CSRF Failed: CSRF token missing or incorrect."
}
````

But if I'm using the Raw data way it works fine. Just getting validation errors as expected. I couldn't find any misconfiguration or something.

**Comment by xordoquy** [comment]
Closing as duplicate of #3637.

**Comment by sspross** [comment]
ou i'm sorry, searched in open issues only.

**Comment by xordoquy** [comment]
@sspross no prob
