### ISSUE TITLE
Custom error message for unique validator does not work

### ISSUE THREAD

**Issue by sunenielsen** [tomchristie/django-rest-framework#3927]
Issue #2878 resulted in a fix where the error message for the key 'unique' set on a model, was used by the serializer validator.

Would it not be better to also use the value set in the serializers `extra_kwargs`, in case you do no want to define it on model itself?

In this example the new unique message is not respected, and I believe it should be:

```
class CustomerSerializer(serializers.ModelSerializer):
    class Meta:
        model = Customer
        extra_kwargs = {
            "email": {
                "error_messages": {
                    "unique": "ERROR_EMAIL_TAKEN"
                }
            }
        }
```

**Comment by xordoquy** [comment]
@sunenielsen the question is, why would you need to define an error message in the serializer instead of the model ?

**Comment by sunenielsen** [comment]
If that really is the question, then why even offer the option of changing all other error messages than the unique validator error?

Perhaps one would want an API where the error message handling was up to some external client, who then needs error codes like in the example.

**Comment by xordoquy** [comment]
@sunenielsen We want to make sure something we include will be used. Pull request are a part o the work but it also has to be maintained after.
The current validation messages you can change are linked to Django Validators as opposed to DRF ones which explains the difference. Min/MaxLength/ValueValidators do have the error message you're referring to, UniqueValidator, UniqueForDate/Month/YearValidator (to name a few) don't.

**Comment by sunenielsen** [comment]
Fair enough. It is not important enough for anything "hacky". Just thought is seemed inconsistent and it annoyed me not to be able to control them in the same way. I'll close the issue.

**Comment by erichonkanen** [comment]
+1 I agree with @sunenielsen why can't I do the same as the other messages and include it in the `extra_kwargs` dict? Currently I have to redefine an entire field on my serializer just to then set the validator with a unique custom message... seems like this could be cleaned up and more consistent to just check for `unique` key in the `extra_kwargs`
