### ISSUE TITLE
Possibility to filter HyperlinkedIdentityField with many=True with queryset

### ISSUE THREAD

**Issue by mvdwaeter** [tomchristie/django-rest-framework#3932]
Given:
A company has 1 or more offices. Company.offices.all()
However, some of these offices are out of order. They have Office.hidden = True

In the detail api-view of Company I'd like to only show the offices that are not hidden with a hyperlinked url.

But currently this seems not possible, as the queryset parameter is ignored for a HyperlinkedIdentityField with many=True. And thus resulting in showing all the offices.

What I want to do is this:

    class CompanySerializer(serializers.ModelSerializer):
        url = serializers.HyperlinkedIdentityField(
            read_only=True, view_name='rest_api:company-detail')

        offices = serializers.HyperlinkedRelatedField(
            queryset=models.Office.objects.filter(hidden=False),
            many=True,
            view_name='rest_api:office-detail')

        class Meta:
            model = models.Company
            fields = ('url', 'id', 'name', 'description', 'offices')

Or something like this:

    class CompanySerializer(serializers.ModelSerializer):
        url = serializers.HyperlinkedIdentityField(
            read_only=True, view_name='rest_api:company-detail')

        offices = serializers.HyperlinkedRelatedField(
            limit_choices_to=dict(hidden=False),
            many=True,
            view_name='rest_api:office-detail')

        class Meta:
            model = models.Company
            fields = ('url', 'id', 'name', 'description', 'offices')

Is this a bug/feature request or am I doing it wrong?

**Comment by mvdwaeter** [comment]
Currently I "solved" it by adding a property to the Company model like so:

    @property
    def active_offices(self):
        return self.offices.filter(hidden=False)


And adjusted the CompanySerializer to this:

    class CompanySerializer(serializers.ModelSerializer):
        url = serializers.HyperlinkedIdentityField(
        read_only=True, view_name='rest_api:company-detail')

        active_offices = serializers.HyperlinkedRelatedField(
            read_only=True,
            many=True,
            view_name='rest_api:office-detail')

         class Meta:
            model = models.Company
            fields = ('url', 'id', 'name', 'description', 'active_offices')

**Comment by tomchristie** [comment]
That's what I would do, yes.
I believe we have an outstanding feature request for this kind of filtering, but otherwise the pattern you've gone with is what we'd recommend.

**Comment by vhelke** [comment]
Hi, what's the status on "I believe we have an outstanding feature request for this kind of filtering" ?

I have a HyperlinkedRelatedField, with many=True, and I would need to do filtering on the queryset. I need to make sure that I only show URLs to other objects, where I have view_permissions.

**Comment by xordoquy** [comment]
@vhelke I think that should be covered by #3605 already.

**Comment by vhelke** [comment]
For some reason I didn't get the "get_queryset" working for the reverse-relations. I ended up doing something like this.
```
class PersonSerializer(serializers.HyperlinkedModelSerializer):
    employee = serializers.SerializerMethodField()

    class Meta:
        model = Person
        exclude = ('owner', )

    def get_employee(self, obj):
        request = self.context.get('request')
        user = request.user
        employees = []

        if user.is_anonymous:
            qs = Employees.objects.filter(Person=obj.pk).filter(owner__username="tester").order_by('pk')  # Show test-data for AnonymousUser
        else:
            qs = Employees.objects.filter(Person=obj.pk).filter(owner=user).order_by('pk')

        for employee in qs:
            employees.append(request.build_absolute_uri(reverse('employee-detail', kwargs={'pk': employee.pk})))

        return employees
```

**Comment by matthewcornell** [comment]
I didn't see how #3605 solved the problem, so I ended up using @vhelke 's approach - bypassing HyperlinkedIdentityField entirely. Question: Almost 2021, is there a cleaner way to do this? Thank you.
