### ISSUE TITLE
When deleted, the HTTP response code is 200 NO CONTENT, should it be `200 OK` or `204 NO CONTENT`?

### ISSUE THREAD

**Issue by jianlin** [tomchristie/django-rest-framework#3935]
should it be `200 OK` or `204 NO CONTENT`?  Right now it is `200 NO CONTENT`

**Comment by xordoquy** [comment]
Out of the context, it's hard to figure what you're relating to.
Do you have any pointer on where "200_NO_CONTENT" is mentioned ?

**Comment by jianlin** [comment]
it is when I try out http://restframework.herokuapp.com/
When I delete a record, I see the response coming back as `200 NO CONTENT`

**Comment by xordoquy** [comment]
Can't reproduce:

    $ http -a admin:admin DELETE http://restframework.herokuapp.com/snippets/2164/

    HTTP/1.1 204 NO CONTENT
    Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
    Connection: keep-alive
    Content-Length: 0
    Date: Wed, 17 Feb 2016 10:49:30 GMT
    Server: WSGIServer/0.1 Python/2.7.4
    Vary: Accept, Cookie
    Via: 1.1 vegur

**Comment by jianlin** [comment]
If I do that on http://restframework.herokuapp.com/ 

create and then delete row:

Request URL:http://restframework.herokuapp.com/snippets/2166/
Request Method:POST
Status Code:200 NO CONTENT

Response Header:
HTTP/1.1 200 NO CONTENT
Connection: close
Date: Thu, 18 Feb 2016 02:21:07 GMT
Server: WSGIServer/0.1 Python/2.7.4
Vary: Accept, Cookie
Content-Type: text/html; charset=utf-8
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Set-Cookie: csrftoken=QHmaHLzclj4ATdUR3mvGs7LFzB1ZUMde; expires=Thu, 16-Feb-2017 02:21:07 GMT; Max-Age=31449600; Path=/
Via: 1.1 vegur

Form data:
_method: DELETE

**Comment by jpadilla** [comment]
@jianlin I see what you mean. You're using the browsable API, you're clicking on the delete button, browsable API says `204 NO CONTENT` but your browser(probably using developer tools) says `200 NO CONTENT`. Am I right?

**Comment by tomchristie** [comment]
We have to coerce status codes to 200 when returning HTML content, otherwise the browser will not render the browsable API.

**Comment by jianlin** [comment]
@jpadilla yes thanks that's what I mean...  inside of the browser (Google Chrome)'s developer tool in the Network tab.
