### ISSUE TITLE
Hard code to get authenticate_header()?

### ISSUE THREAD

**Issue by sainttail** [tomchristie/django-rest-framework#3942]
In my setting I have something like this

```
'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
```
The problem is when calling API (Use JWT) anyone trying to access with invalid credential will result in response code `403` instead of `401` even though JWT already implement `authenticate_header()` but it never get called.

So after debug it, I found that it is hard code for selecting getting authentication header from this [line](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L182) to get that string header. This result in my code always return `403` since the first authentication in the configuration is `SessionAuthentication`. 

So I can fix this by swapping `JSONWebTokenAuthentication` and `SessionAuthentication `.
I'm open this to ask is this the way to get the correct authentication header?

Thanks.

**Comment by tomchristie** [comment]
> I'm open this to ask is this the way to get the correct authentication header?

Yes.

> The kind of response that will be used depends on the authentication scheme. Although multiple authentication schemes may be in use, only one scheme may be used to determine the type of response. The first authentication class set on the view is used when determining the type of response.

http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses
