### ISSUE TITLE
writte nested object doesnt work

### ISSUE THREAD

**Issue by stunaz** [tomchristie/django-rest-framework#3945]
Hi, I have the following models:
```
class Category(models.Model):
    code= models.CharField(max_length=2)
    name= models.CharField(max_length=100)
```

```
class Question(models.Model):
    category= models.ForeignKey(Category, related_name='categories')
    title = models.CharField(max_length=100)
```

and the following serializers:

```
class CategorySerializer(serializers.ModelSerializer):

    class Meta:
        model = Category
        fields = ('code', 'name')
```

```
class QuestionSerializer(serializers.ModelSerializer):
    category= CategorySerializer()

    class Meta:
        model = Question
        fields = ('category', 'title')

    def create(self, validated_data):
        category = validated_data.pop('category')
        category_obj = Category.objects.get(code=category)

        return self.Meta.model.objects.create(category= category_obj, **validated_date)
```

So I am just trying to `POST` a Question with an existing Category. unfortunately, it doesnt work, i get Http Status `400` with the message `The field category is required` : this si where I think there is a bug

My post looks like the following:
```
POST /api/question
DATA: {"title": "question title", "category": "AB"}
```

**Comment by xordoquy** [comment]
You're not posting nested data. Have a look at the serializer relation to see how you can map a relation accordingly to your use case.
Also please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by stunaz** [comment]
yeah, sorry will use the discussion group
