### ISSUE TITLE
Remove non-supported Django version checks  

### ISSUE THREAD

**Issue by akarambir** [tomchristie/django-rest-framework#3952]
Most of these checks are still there in tests where we are checking for older Django versions. Are we keeping them for a reason?

Some Examples [1](https://github.com/tomchristie/django-rest-framework/blob/master/tests/test_request.py#L204), [2](https://github.com/tomchristie/django-rest-framework/blob/master/tests/test_generics.py#L161), [3](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/test.py#L226) ...

If we do not need these checks, I can submit a PR.

**Comment by xordoquy** [comment]
@akarambir very good catch ! Feel free if you want to.
