### ISSUE TITLE
DicField does not valid a required field

### ISSUE THREAD

**Issue by dhararon** [tomchristie/django-rest-framework#3954]
Hi, I'm using `djangorestframework==3.3.2` and when i try to set my fields as required rest-framework ignore it.

This is my field
`questions = serializers.DictField(required=True)`

rest-framework setting to {} and pass the validation, i had to create my own validator for fix it. I dont know if just happened to me or is a issue in the code.

this is my fix:

```python 
def validate_questions(self, value):
		if value:
			return value
		else:
			raise serializers.ValidationError("This field is required.")
```

thanks for your attention.

**Comment by xordoquy** [comment]
Required is a different thing from non empty (see the definition of `required` from the documentation.
However `DictField` has no allow_empty option yet.
