### ISSUE TITLE
Allow removing Media type field from Browsable API

### ISSUE THREAD

**Issue by federicobond** [tomchristie/django-rest-framework#3956]
And provide an option to use a fixed default value.

I could not find a way to do this cleanly, short of overriding `get_raw_data_form` in `BrowsableAPIRenderer`, which is very big. If there isn't a better way, I could implement a patch after discussing the alternatives.

**Comment by tomchristie** [comment]
We could consider concrete PRs in this area - I'd recommend template blocks or similar to allow finer grained overriding of that part of the HTML.
