### ISSUE TITLE
`OrderingFilter` should call `get_serializer_class()` to determine default fields.

### ISSUE THREAD

**Issue by bmampaey** [tomchristie/django-rest-framework#3957]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

GenericAPIView says 
>  You'll need to either set these attributes,
>  or override `get_queryset()`/`get_serializer_class()`.

But in the method **get_valid_fields** of the **OrderingFilter** class, it gets the serializer_class like so
```python
serializer_class = getattr(view, 'serializer_class')
```

I believe it should be 
```python
serializer_class = view.get_serializer_class()
```

Benjamin

**Comment by tomchristie** [comment]
Thanks for the well written issue :+1:

**Comment by jpadilla** [comment]
Oh yeah, this is an actionable ticket! :clap: @bmampaey want to put a a PR together to address this?
