### ISSUE TITLE
CreateOnlyDefault should safely use hasattr(self, 'is_update') before self.is_update in __call__

### ISSUE THREAD

**Issue by edilio** [tomchristie/django-rest-framework#3963]
## Checklist

In fields.py we find:

```python
class CreateOnlyDefault(object): ...
    def __call__(self):
        if self.is_update:
            raise SkipField()
        if callable(self.default):
            return self.default()
        return self.default
```

## Steps to reproduce

If we use swagger (django-rest-swagger==0.3.2) with any models with created_date = models.DateTimeField(auto_now_add=True, blank=True, db_index=True)

Swagger code will brake:

```python
def get_default_value(field):
    default_value = getattr(field, 'default', None)
    if rest_framework.VERSION >= '3.0.0':
        from rest_framework.fields import empty
        if default_value == empty:
            default_value = None
    if callable(default_value):
        default_value = default_value()
    return default_value
```

Just because is_updated has not been set previously to the call but it we just use hasattr we have a safer code.

## Expected behavior

```python
class CreateOnlyDefault(object): ...
    def __call__(self):
        if hasattr(self, 'is_update') and self.is_update:
            raise SkipField()
        if callable(self.default):
            return self.default()
        return self.default
```

## Actual behavior

Return 500 error when using swagger. Of course swagger could be safer too

**Comment by xordoquy** [comment]
I'm not sure we'll want to do that.
`is_update` is called by `set_context` which may alter field behavior.
I'm more inclined to think that this should be fixed in Swagger as this will likely break any field that rely on  `set_context`.

**Comment by edilio** [comment]
You might be right, but then we should return an exception indicating that set_context should be called before using __call__

**Comment by xordoquy** [comment]
I'm against adding a specific exception for a very specific and unusual use case.
An assert would be the most I'm inclined to accept.
Note that in the end both solutions would end up in a 500 response anyway.

**Comment by tomchristie** [comment]
No longer an issue given updates to django-rest-swagger.
Happy to reconsider if anyone comes across this again in a different use-case.
