### ISSUE TITLE
There is not anything about 'ListSerializer' class in api guide.

### ISSUE THREAD

**Issue by iraj-jelo** [tomchristie/django-rest-framework#3975]
There is nothing about  **'ListSerializer'** class and its **'child'** attribute in **Api guide** and how should we use them.

**Comment by xordoquy** [comment]
That's because it's the part behind the scene for many=True on serializers.

**Comment by iraj-jelo** [comment]
so you have written in comments:

  "Serializers with many=True do not support multiple update by "
            "default, only multiple create. For updates it is unclear how to "
            "deal with insertions and deletions. If you need to support "
            "multiple update, **use a `ListSerializer` class and override "
            "`.update()`** so you can specify the behavior exactly."

**Comment by xordoquy** [comment]
And that part is already explained in the [documentation](http://www.django-rest-framework.org/api-guide/serializers/#listserializer)

**Comment by iraj-jelo** [comment]
thank you dude (y)
