### ISSUE TITLE
 CSRF Failed after sent correct CSRF token

### ISSUE THREAD

**Issue by Windsooon** [tomchristie/django-rest-framework#3979]
## Checklist
When I use browser to sent PUT request, it works well.but When I using ajax sent request just like before, it tell me csrf token is missing or incorrected.

## Steps to reproduce
My jQuery code looks like this:
```
$.ajax({
    url: "/api/users/1/",
    type: "PUT",
    datatype: "json",
    data:  {csrfmiddlewaretoken: csrf_token, "user_gender": 2, "user_details": 23 },
....
```
## Expected behavior
PUT users which id is 1.
## Actual behavior
    
    {"detail":"CSRF Failed: CSRF token missing or incorrect."}
In chrome console
```
csrfmiddlewaretoken:wUlPIaEmZd2FMA2ob9VRSVKWpOf6EQHn
user_gender:0
user_details:111asdfasdfsdf
```
I'd console.log(csrf_token), and it is as same as which I using in brower.

I followed Bryan here [CSRF Failed after sent correct CSRF token](https://stackoverflow.com/questions/5100539/django-csrf-check-failing-with-an-ajax-post-request) request and it works in other page using POST request, and permissions.py is also work well.

**Comment by tomchristie** [comment]
For JSON requests the CSRF token needs to be included as a header.

https://docs.djangoproject.com/en/1.7/ref/contrib/csrf/#ajax
