### ISSUE TITLE
RelatedField(required=False) throws KeyError when the data is missing

### ISSUE THREAD

**Issue by nazarewk** [tomchristie/django-rest-framework#3985]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a [pull request](https://github.com/tomchristie/django-rest-framework/pull/3984). (If you are unable to do so we can still accept the issue.)

Actually there is a [duplicate](https://github.com/tomchristie/django-rest-framework/issues/3976) but without a valid use case.

## User story

I want to fill in the non-nullable relational field on the `Model` (eg. in `save()`), i would make it `required=False` in the DRF to allow it.

## Steps to reproduce
```python
from django.db import models
from rest_framework import serializers

class Target(models.Model):
    pass

class Source(models.Model):
    target = models.ForeignKey(Target)

class ExampleSerializer(serializers.ModelSerializer):
    class Meta:
        model = Source
        fields = ('id', 'target')
        extra_kwargs = {'target': dict(required=False)}
        
serializer = ExampleSerializer(data={})
serializer.is_valid(raise_exception=True)
```

## Expected behavior
```python
assert 'target' not in serializer.data
```

## Actual behavior
```python
try:
    serializer.data
except KeyError:
    print('Nuff said')
```

**Comment by carltongibson** [comment]
Can you try this with allow_null please? allow_empty is for lists

**Comment by xordoquy** [comment]
I'm a bit mixed on that one but would tend to consider that valid.
`required` is a field core argument so it should be properly handled. However, this rings a bell about doing something wrong here though I can't name it yet.

**Comment by nazarewk** [comment]
Actually looks like neither `allow_empty` nor `allow_null` make any difference.

**Comment by xordoquy** [comment]
@nazarewk not really it's a different thing.

**Comment by nazarewk** [comment]
Well it feels weird for me to set the fields in either `Model.clean_fields()`, `Model.save()` or the likes, but sometimes it is extremely hard to avoid.

**Comment by carltongibson** [comment]
OK. This does seems a problem: 

``
ModelSerializer(data={u'name': u'test'}):
    id = IntegerField(label='ID', read_only=True)
    name = CharField(max_length=100)
    target = PrimaryKeyRelatedField(help_text='Target', queryset=[...], required=False)
```

We get the `KeyError` for `target` here, as per the report. #3984 looks neat enough.

**Comment by sdlm** [comment]
I have this problem too.

behavior:
https://gist.github.com/sdlm/7890303821aa8cd5c91ea712f8f51be4

[#3984](https://github.com/tomchristie/django-rest-framework/pull/3984) looks good !

**Comment by tomchristie** [comment]
Okay, thanks for the data point - we'll try to get this reviewed soon.

**Comment by tomchristie** [comment]
Closing with same resolution as #3984. Happy to reconsider if anyone believes that resolution isn't correct/sufficient.
