### ISSUE TITLE
CharField behavior mistmached between internal and representation mode with trim_whitespace option

### ISSUE THREAD

**Issue by evilNullPointer** [tomchristie/django-rest-framework#3987]
## Steps to reproduce
- Create a serializer with CharField members (rest_framework.serializers.CharField)
  - Can be bind or not to an actual Model
  - Set the trim_whitespace argument to True
-  Create an instance of the serializer with data
- Wrap it in a Response instance to trigger the serialization process

```python
from rest_framework import serializers


class TrimNotWorkingSerializer(serializers.Serializer):
    my_field = serializers.CharField(trim_whitespace=True)
   
    def create(self, validated_data):
        return SomeModel.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.my_field = validated_data.get('my_field', instance.my_field)
        instance.save()
        return instance
```

## Expected behavior
I was expecting a trimmed output for all fields with the trim option enabled.

```json
{
    "my_field": "My test string trimmed"
}
```

## Actual behavior
The output still contains padding whitespace. The *CharField::to_representation* method does not trim the value like *CharField::to_internal_value*

**serialized output**
```json
{
    "my_field": "My test string un-trimmed                     "
}
```

**rest_framework.fields.py**
The method *to_representation* should be identical to *to_internal_value* that support trimming.
```python
class CharField(Field):
     # .....

    def to_internal_value(self, data):
        value = six.text_type(data)
        return value.strip() if self.trim_whitespace else value

    def to_representation(self, value):
        return six.text_type(value)
```

## Workaround
Override the *to_representation* method in a subclass.

```python
from rest_framework import serializers


class TrimRepresentationField(serializers.CharField):
    def to_representation(self, data):
        return self.to_internal_value(data)

class TrimWorkingSerializer(serializers.Serializer):
    myField = TrimRepresentationField(trim_whitespace=True)
```

**Comment by tomchristie** [comment]
to_representation is not intended to forcibly sanitize output. We sanitize at the point of input.

**Comment by evilNullPointer** [comment]
The workaround I used, is it something that you recommend to do? How should we sanitize the output of the serializer, which is one of the primary goal of using an intermediate layer (encapsulation as well...)? It's a little bit confusing to have a trim property which doesn't always trim. Could you mention it in the api documentation and also in tutorials. 

Thanks for you time!

**Comment by kdazzle** [comment]
My preference is to just trim what `to_representation` normally outputs, rather than calling `to_internal_value`:

```
class TrimmedCharField(serializers.CharField):

    def to_representation(self, instance):
        serialized = super(TrimmedCharField, self).to_representation(instance)
        return serialized.strip()
```

**Comment by mixtah** [comment]
> to_representation is not intended to forcibly sanitize output. We sanitize at the point of input.

Never just sanitize on input, either just on output, or both.
The main reason is that if someone works around the standard input (get access to the database) they can perform XSS attacks and potentially capture raw passwords from users (as opposed to the hashed passwords in the db).

I was looking for a way to sanitize the output, either I'm not seeing/missing something that does this easily, or surprisingly few amounts of people are complaining about this.
