### ISSUE TITLE
JSONField in binary mode and json rendering

### ISSUE THREAD

**Issue by gtnx** [tomchristie/django-rest-framework#3992]
I cannot render a JSONField in binary mode (eg `binary=True`) with the default `rest_framework.JSONRenderer`. I get the following error: `b'{}' is not JSON serializable`

My environment is:

- python: 3.4
- drf: 3.3.2

My understanding is that the `JSONField.to_representation` method returns a `bytes` object ([See here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1558-L1559)). But in python3, `json.dumps` does not seem to accept bytes.

I think this a bug, no?

**Comment by xordoquy** [comment]
@gtnx Documentation states that binary mode will return an already encoded JSON string which means the result will be binary:

> binary - If set to True then the field will output and validate a JSON encoded string, rather than a primitive data structure. Defaults to False.

You can work this around by leaving the binary turned off.

**Comment by gtnx** [comment]
Let's say i have a serializer with a `foo` field which is a JSONField which content is a empty object (eg `{}`). My understanding was that:
- `binary=False` --> rendered json is `{"foo": {}}`
- `binary=True` --> rendered json is `{"foo": "{}"}`

Is that so? 

In that case, the `JSONField.to_representation` method should return:
- `binary=False` the value
- `binary=True` a **python3 str object** object and not a **bytes object** which is not accepted by `json.dumps` method

**Comment by gtnx** [comment]
I think @xordoquy closed this issue too quickly. Btw, the rendering with `JsonRenderer` is not tested.

**Comment by xordoquy** [comment]
@gtnx `binary=True` wouldn't make much sense if it wasn't binary (i.e. bytes).
@tomchristie could you confirm the intent here ?

**Comment by AdrianLC** [comment]
I'm also affected by this issue. Some of my views were returning raw JSON as string before we updated to the new postgres JSONFIeld for better support. I must still return the raw string in the response for backwards compatibility.

Having a field option that breaks rendering doesn't make much sense IMHO. And the encoder already has support for other, likely more edge case types, such as numpy arrays.

**Comment by xordoquy** [comment]
@AdrianLC What do the responses look like ? My understanding that you are casting json into string to be rendered into json. I don't get why t's not using the base structure (binary=False) and let the json renderer do the job.

**Comment by AdrianLC** [comment]
@xordoquy
The model had one of those third party JSONFields so of course it was not supported by Rest Framework and I did not implement any formatting myself. It was treated as an string by the ModelSerializer. So the response used to look like this:

```JSON
{"modelField": "{\"field\": \"value\"}"}
```

Now I'm using contrib.postgres' JSONField which is perfectly rendered by Rest Framework in the ModelSerializer as: 

```JSON
{"model_field": {
    "field": "value"
}}
```

Front end code still expects the string format and will attempt to parse it into an object so what I want is both versions of the field. As a deprecation step until I can permanently remove the string version.

```JSON
{
    "model_field": {
        "field": "value"
    },
    "modelField": "{\"field\": \"value\"}"}
}
```

I expected to achieve this simply by including `modelField = serializers.JSONField(binary=True, source='model_field')` in the serializer but encountered this TypeError.

**Comment by xordoquy** [comment]
As a workaround you could define a compatibility field that overrides the `to_representation`/`to_internal_value` to format to/from a string and call super before/after the translation has been done.

**Comment by gtnx** [comment]
> Having a field option that breaks rendering doesn't make much sense IMHO.

Agree on that.

Actually the issue is explained on [those two lines](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L1558-L1559). `JSONField.to_representation` returns a binary string which is not renderable. `CharField.to_representation` returns `six.text_type` for instance. Isn't it a weird behavior?

I think the word "binary" is misleading. "encoded" or "serialized" would be more appropriate.
