### ISSUE TITLE
Functions in class-based view taking different permission & authentication classes

### ISSUE THREAD

**Issue by jheld** [tomchristie/django-rest-framework#3997]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
-- I haven't seen any documentation for this
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
-- I have searched
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
-- Usage-y, but feels more like a feature request
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
-- Does not seem like anyone does this
- [x] I have reduced the issue to the simplest possible case.
-- Pretty simple way to test this
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)
-- No PR yet

## Steps to reproduce
Class-based view or global permissions and/or authentication  and decorator overriding on the function itself inside.
Run the URI request

## Expected behavior
The authentication and permissions classes should be for that functional context, nothing class or global
## Actual behavior
Only the class or global behavior (list of these permissions & authentications that are run)

Please let me know if you need clarity or more info.

**Comment by xordoquy** [comment]
> Class-based view or global permissions and/or authentication and decorator overriding on the function itself inside.

This is too abstract. Can we start with a concrete case ?

**Comment by jheld** [comment]
Sure!

Let's say I have ONE endpoint for signing in and out (get a token, release a token), for Token based authentication after email/password sign in.

So, the user hits the POST of the URI with their email & password and gets the token back.

The user then hits the DELETE of the URI with their signed token header.

In the case of the POST (sign in, get token), I want BasicAuthentication.
In the case of the DELETE (sign out, delete token (though that's an implementation detail)), I want TokenAuthentication. Right now I get an AnonymousUser. So, my idea is DOING_IT_WRONG || NO_CURRENT_SUPPORT.

Does that help?

**Comment by jheld** [comment]
OK, the functional (HTTP method) level can be resolved in my case by extending the get_authenticators method in my APIView subclass. I check for the method type on the request and make my magic/hack around it. 

This way is less official (and arguably I would think less maintainable) than I'd like than putting a decorator on the method in the class, but that's a different scope of the problem (can vs no "easy" support at all).

Using this implementation, I can force only the type of authentication I want to be accepted, and still allow other types for another HTTP method.

As far as Anonymous user is concerned, that still happened after I made this method extension, but then I "re"-added the IsAuthenticated permission_class in the method. I can keep that permission only on the DELETE, so that it doesn't affect the sign in process (which wouldn't [need to] be authenticated, by default reasoning).

So for clarification, if I don't specify a permission like IsAuthenticated, and there is no other overriding behavior, the AnonymousUser will come through? That's how it seemed. And I wouldn't want IsAuthenticated for a signing-in, user, right? I think that makes sense.

Thanks for the help & the project!

**Comment by tomchristie** [comment]
> `NO_CURRENT_SUPPORT`

Correct.

>  can be resolved in my case by extending the get_authenticators method in my APIView subclass. I check for the method type on the request and make my magic/hack around it.

Yup, that's the simplest way to do what you're looking for.

**Comment by jheld** [comment]
@tomchristie & @xordoquy Thanks for helping me through this and seeing if there was interest in implementing. Would you accept a PR if I got this working?

**Comment by tomchristie** [comment]
@jheld It'd be considered, but we're fairly unlikely to want to extend the API at the moment. We have to balance continually growing the framework, vs restricting what we accept, keeping the API surface area manageable, and closing off existing tickets. At the moment it's most likely we'd probably judge any changes here to be a not-common-enough use-case.
