### ISSUE TITLE
providing more parameters for exeptions

### ISSUE THREAD

**Issue by mousavian** [tomchristie/django-rest-framework#4001]
I suggest to change the exception classes the way that in the time of raising them, we will be able to add dynamic number of parameters for providing more information or customizing `detail` keyword. Something like:

```
raise ParseError(detail="Some detail", error=True, some_other_stuff=123)
````

Which will produce:
```
{
     "detail": "Some detail",
     "error": "true",
     "some_other_stuff": 123,
}
```

If anyone is wondering why I'm suggesting this, is because we have an existing system written in another programming language that in the time of raising error it sends the error detail in "message" & "error" attribute. since now we're going to implement another part of it with django+rest_framework, it doesn't seems unify.

**Comment by xordoquy** [comment]
Well, You should already be able to reach that result by using custom exceptions and custom exception handler.
