### ISSUE TITLE
Django Rest Serializer Class Cannot Attache Values. I suppose this is the default behavior of __getattribute__ from Fields

### ISSUE THREAD

**Issue by yiakwy** [tomchristie/django-rest-framework#4007]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
django-rest serializer has a very upset feature, "I cann not attached value to a serlializer class!!!"
## Expected behavior
for example:
```python
    def __init__(self, *args, **kwargs):
        super(DynamicFieldsModelSerializer, self).__init__(*args, **kwargs)
        self._drop_cols()

    def _drop_cols(self):
        if hasattr(self.Meta, '__sign') and \
                hasattr(self.Meta, '__fields'):
            try:
                # the following method doesn't work
                sign = self.Meta.sign
                fields = self.Meta.fields
            except:
                # always error!
                return
            if fields is not None:
                if sign \
                        == u'+':
                    allowed = set(self.__fields)
                    existing = set(self.fields.keys())
                    for field_name in existing - allowed:
                        self.fields.pop(field_name)
                elif sign \
                        == u'-':
                    for fields_name in self.__fields:
                        self.fields.pop(fields_name)
```
## Actual behavior
Here is confusion of the software
```python
hasattr(self, 'sign') == True # yes
self.sign # always KeyError or None
```

**Comment by xordoquy** [comment]
Unfortunately I don't get what you're trying to do. Could you provide more context about it ?

**Comment by yiakwy** [comment]
in my context,

I have a serlizer manager which is itself a context manager and a descriptor, for example:

```python
class SerializerManager(object):

    def __init__(self, cls):
        self.cls = cls

    def __get__(self, caller, caller_type=None):
        self.owner = caller
        return self

    @contextlib.contextmanager
    def only(self):
        try:
            if hasattr(self.owner, 'cols') and self.owner.sign:
                setattr(self.cls.Meta, '__sign', self.owner.sign)
                setattr(self.cls.Meta, '__fields', self.owner.cols)
            yield
        except:
            import traceback
            traceback.print_exc()
        finally:
            if hasattr(self.cls, '_fields') and\
                    (hasattr(self.owner, 'cols') or hasattr(self.owner, 'sign')):
                del self.cls._fields

            if hasattr(self.owner, 'cols'):
                self.owner.cols = None
            if hasattr(self.owner, 'sign'):
                self.owner.sign = None

    def __call__(self, objects, **kwargs):
        # self.cls.__sign, self.cls.__fields =
        #     self.owner.sign, self.owner.cols,
        many = kwargs.pop('many', False)
        if many:
            with self.only():
                repr = self.cls(data=objects, many=True,
                                sign=self.owner.sign,
                                fields=self.owner.cols,
                                **kwargs)
                repr.is_valid()
                data = repr.data
            return data
        else:
            return self.cls(objects, **kwargs).data
```
The reason why I write in this way is that I want abstract this sentence when I am writing dynamic Nth nested resources router and create a universal objests_fetcher_plural 

```python
    def get_response(self, req):

        def routine(req):

            query_set = self.get_object_plural(req)
            m_repr_data = self.serializer_class(query_set, many=True)
            if hasattr(m_repr, '__len__') and \
                            len(m_repr_data) < self.PAGINATION_DEF:
                return Response(data=m_repr_data)
            else:
                return self.get_paginated_response(data=m_repr_data)

        try:
            rep = routine(req)
        except Exception as err:
            import traceback
            traceback.print_exc()
            return handle_exc(None,
                              status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                              details=err.message)
        return rep
```

Where I record possible popup fields.

Two benefits to do this

(1) In ListSerializer, cls with fewer fields or already filtered fields will be used for initialize data when m_repr.data fired. It is much better to write in __new__ rather in __init__

(2) I cannot assign sign (+, -) and cols (field_1, fileds_2, ...) into cls -- a serializer class instance by using either setattr or assignment statements.

**Comment by tomchristie** [comment]
Closing as outside of supported usage.

**Comment by yiakwy** [comment]
Why close it? I think this might confuse a lot of developers who are trying to modify Serializer Class dynamically because it is a snippet of codes in python runtime, and it is pythonic.

**Comment by tomchristie** [comment]
If the case presented was simple and clear enough I might reconsider.

**Comment by yiakwy** [comment]
Ok, understand.

2016-03-24 16:46 GMT+08:00 Tom Christie <notifications@github.com>:
