### ISSUE TITLE
perform_create method in CreateModelMixin doesn't return model instance

### ISSUE THREAD

**Issue by likeon** [tomchristie/django-rest-framework#4015]
Why [perform_create method in CreateModelMixin](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L26) does not return model instance?

There is no way I could save base method behavior calling super and have a model instance at the same time.

**Comment by xordoquy** [comment]
@likeon You can access the object through serializer.instance

**Comment by piedrucci** [comment]
thanks @xordoquy works for me.

**Comment by sgaweda** [comment]
Why was it decided that `serializer.instance` was the preferred way to pass this along? `serializer.save` returns `self.instance`, so why not `perform_create`? I ask to gain a better understanding of the intended uses of these functions.

**Comment by xordoquy** [comment]
@sgaweda `perform_create` is a view method and the view doesn't have `self.instance`. Better option would be to handle logic in `perform_create`.

**Comment by askoretskiy** [comment]
Could we reopen that? When somebody writes `perform_create` it would allow to have more simple code:

This is how it could look like:

```python
def perform_create(self, serializer):
    instance = super().perform_create(serializer)
    # do something with `instance`
```

vs. current one:

```python
def perform_create(self, serializer):
    super().perform_create(serializer)
    instance = serializer.instance
    # do something with `instance`
```

or this one:

```python
def perform_create(self, serializer):
    instance = serializer.save()
    # do something with `instance`
```

Fix is exactly one-liner:

```patch
     def perform_create(self, serializer):
-        serializer.save()
+       return serializer.save()
```

Maybe it is not in line with other parts of DRF, it is quite handy. Also, if we change the state in the method, it makes sense to return the result to be available right away.

**Comment by tomchristie** [comment]
Perhaps, tho it’s not necessarily a clear win.

Flip side: Having two different ways to perform an equivalent operation is less beneficial than having a single way. Having a single way around means you end up with greater consistency across the entire ecosystem, eg code samples that follow a more familiar pattern throughout, and there’s no “should it be this way or that way” for the developer to consider.

**Comment by askoretskiy** [comment]
I just find `instance = serializer.instance` counter-intuitive and see our codebase being flooded with `instance = serializer.save()`. It would certainly benefit to have this change.

**Comment by rpkilby** [comment]
> and see our codebase being flooded with `instance = serializer.save()`.

I understand the argument for DRYness here, however the alternative in this case would be 
```python
instance = super().perform_create(serializer)
```
You'd be swapping one line for another, with the added layer of indirection. That said, if you do prefer to call `super()` over a call to `serializer.save()`, it should be safe to implement a mixin class that reimplements the `perform_*` methods.

```python
class ReturnableMixin:
    def perform_create(self, serializer):
        return serializer.save()

    def perform_update(self, serializer):
        return serializer.save()

    def perform_delete(self, instance):
        return instance.delete()

class MyViewSet(ReturnableMixin, ModelViewSet):
    ...
```

This should be safe, as viewsets are looking for the presence of `create`/`update`, not `perform_create`/`perform_update`.
