### ISSUE TITLE
Form not works in BrowsableAPIRenderer for a CreateAPIView (HTTP 400 Bad Request)

### ISSUE THREAD

**Issue by madEng84** [tomchristie/django-rest-framework#4017]
This is not an issue but a question

Why my form not works for my CreateAPIView?
I can post data only with Raw data..
If I use the form i get a **"HTTP 400 Bad Request"**

view definition:

```
class MyModelUpdateMultiLanguageAPIView(CreateAPIView):
    model =MyModel
    serializer_class = MyModelSerializer
    authentication_classes = (BasicAuthentication,) #to avoid CSRF Token missing exception
```

serializer definition:

```
class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = ('title', 'content',)  

```
I'm using:

> Django==1.8.11
> djangorestframework==3.3.3 (from pypy)

drf settings:

> REST_FRAMEWORK = {
>     'DEFAULT_AUTHENTICATION_CLASSES': (
>         'rest_framework.authentication.BasicAuthentication',
>         'rest_framework.authentication.SessionAuthentication',
>     ),
>                   
>     'DEFAULT_MODEL_SERIALIZER_CLASS':
>         'rest_framework.serializers.ModelSerializer',
>     
>     'DEFAULT_RENDERER_CLASSES' :[
>         'rest_framework.renderers.JSONRenderer',
>         'rest_framework.renderers.BrowsableAPIRenderer'
>     ],
>     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
>     'PAGE_SIZE': 10
> }

Any help is appreciated

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
