### ISSUE TITLE
Partial updates need every field listed in `ModelSerializer`

### ISSUE THREAD

**Issue by OJFord** [tomchristie/django-rest-framework#4023]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1.  
    ```python
    class ModelSerialiser(serializers.ModelSerializer):
        class Meta():
            model = Model
            fields = (
                # big list
            )
    ```

2. Create a `ViewSet` with a `partial_update` method

## Expected behavior

Be able to use the `PATCH` method without all fields.

## Actual behavior

Unable to use the `PATCH` method unless all fields present (equating it to `PUT`).

---

This has been addressed before in #965, which saw the introduction of `partial=True` for `serializers.*Field` properties.

However, the issue here is that with many fields, or really however many there are, it's frustrating to have to list them 'manually' just to be able to add `partial=True`:

```python
field1 = serializers.CharField(
    # copy out params from model
    , partial=True
)
# ...
fieldN = # ...
```

It would be great if we could add `partial = True` to `Meta` in order to apply this to all fields; or better yet, an iterable in the same way as `fields` (it could then be `partial = fields` in order to apply to all).

**Comment by xordoquy** [comment]
I haven't had issues with PATCH and viewsets.
My guess here is that you overrode the `partial_update` and instantiated a serializer without providing the partial argument.
"mixins.py" contains the `partial_update` original code which you should base yourself upon.

**Comment by OJFord** [comment]
@xordoquy 

> instantiated a serializer without providing the partial argument

Could you expand on that? With no `field = serializers.*Field`s, where should I be providing the partial argument?

As above:
```
class ModelSerialiser(serializers.ModelSerializer):
    class Meta():
        model = Model
        fields = (
            # big list
        )
```

**Comment by xordoquy** [comment]
Declaration isn't instantiation.

   serializer = XXXSerializer(..., partial=True)

**Comment by OJFord** [comment]
Right. I just misread the example in the documentation as being `SerializerField` instead of `Serializer`.

Cheers!
