### ISSUE TITLE
Admin Renderer and DELETE Method

### ISSUE THREAD

**Issue by GuillaumeCisco** [tomchristie/django-rest-framework#4032]
Currently using the Admin Renderer, if you delete an object, you're not redirected on the list page.
The object is well deleted, but code on https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/renderers.py#L717 redirect to a 302 on parent url with a `DELETE` method, so it breaks.
The returned message is `Method "DELETE" not allowed.`
It should be a `GET` on the list page.

**Comment by tomchristie** [comment]
Resolved via #4106.
