### ISSUE TITLE
Suppressed AttributeError When Authenticating

### ISSUE THREAD

**Issue by magnus-staberg** [tomchristie/django-rest-framework#4033]
My implementation of [BaseAuthentication's authenticate](https://github.com/tomchristie/django-rest-framework/blob/dd3b47ccbda59487e3768f3397a563fd740f667a/rest_framework/authentication.py#L40) had a bug where an AttributeError was thrown. DRF handles that by catching the thrown AttributeError and then accessing and returning "user" on Django's request instead.

The [perform_authenticate](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L310) tries to authenticate when "user" is missing (see [invoke _authenticate](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L195 ) but if the code for authenticating throws an AttributeError, then Django's request's user will be accessed instead, see [__getattribute__](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L354-L359).

The result of this behaviour was that the request was authorised when entering the DRF view but when executing request.user inside the view an AnonymousUser instance was received instead of an instance of my class that inherits BaseAuthentication and implements authenticate(self, request).

AttributeError thrown when accessing "user" attribute on a DRF request shouldn't be caught and it shouldn't access user on Django's request.

One simple but ugly way to solve it would be to check if attr is "user" at https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L357 and in that case rethrow the AttributeError instead of accessing the attribute on _request.

**Comment by xordoquy** [comment]
Unless we remove support for Python 2, using `hasattr` will not [be a better choice](https://hynek.me/articles/hasattr/).
I spent over 10 hours fixing this while porting raven to python 3 because of that subtle difference.

**Comment by magnus-staberg** [comment]
@xordoquy Sorry about that and thanks for answering.
However, that's not what I meant. Please see referenced pull request.

**Comment by pelme** [comment]
We found this problem when developing custom auth backends. Our implementation accidentally ate an AttributeError. This problem leads to difficult-to-debug problems. The AttributeError gets eaten because of the `__getattribute__` proxy to Django's request object. We're not sure how to actually fix this in the best way, but hopefully the test shows the issues.

**Comment by rpkilby** [comment]
Hi all, I've opened #5600, which aims to fix this. I see two possibilities:

- Have an exception in `__getattribute__` for "user", such that `AttributeError`s raised in `_authenticate` are not eaten/hidden.
- Catch `AttributeError`s in `_authenticate` and re-raise as a different exception class. 

The former does fix error hiding when calling `request.user`, but not `hasattr` checks, as an `AttributeError` is still raised here.
