### ISSUE TITLE
Third party package submission

### ISSUE THREAD

**Issue by raphaelgyory** [tomchristie/django-rest-framework#4037]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Hi! I coded this third party project for DRM. It is a real-time messaging solution composed of three packages. Would you link to it from the Third Party Packages section? Thanks!!
I think it would fit under the Misc section:

- [django-rest-messaging](https://github.com/raphaelgyory/django-rest-messaging), [django-rest-messaging-centrifugo](https://github.com/raphaelgyory/django-rest-messaging-centrifugo) and [django-rest-messaging-js](https://github.com/raphaelgyory/django-rest-messaging-js), a real-time messaging service using DRM. See [doc and demo](https://django-rest-messaging.raphaelgyory.com/site/).

**Comment by xordoquy** [comment]
The directions to get those packages mentioned in the documentation is explained at http://www.django-rest-framework.org/topics/third-party-resources/#once-your-package-is-available

**Comment by raphaelgyory** [comment]
http://www.django-rest-framework.org/topics/third-party-resources/ says "Create a Pull Request or Issue on GitHub". Sorry if I did it wrong, it's my first submission...

**Comment by tomchristie** [comment]
> Sorry if I did it wrong, it's my first submission...

Not to worry. The meaning there is to create a pull request for the docs update that you'd like to see.

**Comment by raphaelgyory** [comment]
Thanks! I just submitted the pull request.
