### ISSUE TITLE
Routes error with django models migrations

### ISSUE THREAD

**Issue by pdonaire1** [tomchristie/django-rest-framework#4051]
Hi!

I have a file named routes.py where I have that 
`router.register('orders',  OrderViewSet, 'order')`
If I comment that I don't have problems with the migrations, but in production, and my boss say I cannot comment that every time that I want to migrate.

In te serializer.py I have this:
```
class OrderSerializer(serializers.ModelSerializer):
    buyer_obj = serializers.SerializerMethodField()
    #items = ProductSerializer(many=True, read_only=True)
    class Meta:
        model = Order
        fields = ('id', 'url', 'buyer', 'items', 'store', 'buyer_obj',
            'browser_ip', 'currency', 'enabled',
            'financial_status', 'gateway', 'total_amount')
```
The Error is the next:

> django.db.utils.OperationalError: (1054), "Unkown column 'orders_order.currency' in 'field list'")

**Please exist another form to migrate that?**
Thank you.

**Comment by jpadilla** [comment]
You could try removing `currency` from your serializer's fields, seems like that column/field no longer exists.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.
