### ISSUE TITLE
Configurable offset cutoff with CursorPagination

### ISSUE THREAD

**Issue by rowanseymour** [tomchristie/django-rest-framework#4053]
Picking up where the https://github.com/tomchristie/django-rest-framework/pull/3143 ended.. in our API implementation we generally order by a combination of a millisecond accuracy timestamp and pk, e.g.

```python
class ModifiedOnCursorPagination(CursorPagination):
    ordering = ('-modified_on', '-pk')
```

It's possible sometimes for large numbers of items to end up with the same timestamp so we've been overriding `decode_cursor` so that we can increase `OFFSET_CUTOFF` (malicious queries are less of a concern in this case). Seems like that value could be configurable though, so happy to make a simple PR if there's a consensus on whether it should be a class variable or settings value.

**Comment by tomchristie** [comment]
> Seems like that value could be configurable though

I'd suggest subclassing, setting `offset_cutoff`, and then adding that new class as the default pagination class in the settings.

**Comment by rowanseymour** [comment]
Not a great solution for us because then we have to replicate the code in `CursorPagination.decode_cursor` in  our subclass

**Comment by tomchristie** [comment]
I'd have no problem with a PR that simply moved the `OFFSET_CUTOFF` to a class attribute `.offset_cutoff`. Ignore the test case in #3143 and that'd be fine as a two-liner change.
