### ISSUE TITLE
DRF does not accept unbounded RangeField

### ISSUE THREAD

**Issue by dbinetti** [tomchristie/django-rest-framework#4060]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Add  a [PostgreSQL RangeField] (https://docs.djangoproject.com/es/1.9/ref/contrib/postgres/fields/#range-fields) to your model.
2. Use the [drf-extra-fields] (https://github.com/Hipo/drf-extra-fields) library to create a serializer for that field.
3. POST an [unbounded] (http://initd.org/psycopg/docs/extras.html#range-data-types) RangeField object.  

## Expected behavior
Should return `201 Created`

## Actual behavior
Returns `400 BAD REQUEST - This field may not be null`

Repo with failing test here:  https://github.com/dbinetti/djangodaterange

I'm not sure if submitting a bug using third-party libraries is legit, but after checking with them they say the problem is not with them.  So submitting here in hopes i can get to the answer. 

Related issues and discussion:
https://github.com/Hipo/drf-extra-fields/issues/16
https://github.com/django-json-api/django-rest-framework-json-api/issues/227

**Comment by dbinetti** [comment]
So what is the process here?  Should I be doing anything else?  Are these triaged in some fashion?  How can I help?

**Comment by kevin-brown** [comment]
My instinctual reaction is that this is an issue in [drf-extra-fields](https://github.com/Hipo/drf-extra-fields), and not DRF. That is mostly because `RangeField` is not something which DRF supports at the moment.

**Comment by tomchristie** [comment]
Apologies, we're a little back logged at the moment. I had a bit of a look at this issue earlier but failed to narrow it down sufficiently on a quick scan.

What needs to happen next is really to break this down to a core issue (or not) as it stands there's too many elements at play. It seems like the issue reduces to something like "null is an allowed option on DictField but isn't actually respected" or *something* along similar lines. Is that right.

**Comment by dbinetti** [comment]
@kevin-brown They are pointing the finger back at DRF.  See [here](https://github.com/Hipo/drf-extra-fields/issues/16).

@tomchristie Apologies not necessary -- this is amazing work you're all doing.    

And yes, "null is an allowed option on DictField but isn't actually respected" is precisely the issue.  The problem (for me, at least) is that I don't know where to go next to debug it because of the moving parts involved.  I would like to simplify the test case, but I don't know where to even begin.  I was hoping the failing test case would others in the right direction.

**Comment by tomchristie** [comment]
Okay, there are tests for serializer fields in 'test_fields.py' - a (failing) pull request to that to add this 'null' case for DictField woul go a long way to getting this resolved. You'll see that we have a bunch of different inputs and outputs that we test for each field, adding a new case there is easy once you've understood how those tests are laid out.

Alternatively try to replicate the reduced problem described here - if you can show clear steps demonstrating the root issue that'd be the next best thing to a failing test case.

**Comment by tomchristie** [comment]
I've added some test cases, and I'm not able to replicate any issues with either:

* DictField(allow_null=True, ...)
* DictField(child=WhatEver(allow_null=True)

It's possible that there's an issue with the child fields not including `allow_null=True` in DRF extra fields, eg here: https://github.com/Hipo/drf-extra-fields/blob/master/drf_extra_fields/fields.py#L153

I would probably have expected that line to read

    child = DateField(allow_null=True)

But I'd start with making sure that there's a test case in extra fields covering the `null` range example.

**Comment by tomchristie** [comment]
Ooops. Reopening until the tests in #4348 have run and the PR is merged.
