### ISSUE TITLE
Setting PAGE_SIZE significantly changes the JSON output

### ISSUE THREAD

**Issue by ziima** [tomchristie/django-rest-framework#4063]
Defining positive `PAGE_SIZE` completely changes the output. The [documentation](http://www.django-rest-framework.org/api-guide/settings/#page_size) says that "...pagination is disabled by default.", but I wouldn't in any case expect it suddenly returns completely different output.

These are the results using REST tutorial as an example:
```
# Without PAGE_SIZE=None or PAGE_SIZE=0
$ curl -s http://127.0.0.1:8000/users/ | json_pp 
[
   {
      "email" : "admin@example.cz",
      "url" : "http://127.0.0.1:8000/users/1/",
      "groups" : [],
      "username" : "admin"
   }
]
# With PAGE_SIZE=10
$ curl -s http://127.0.0.1:8000/users/ | json_pp 
{
   "next" : null,
   "results" : [
      {
         "url" : "http://127.0.0.1:8000/users/1/",
         "email" : "admin@example.cz",
         "groups" : [],
         "username" : "admin"
      }
   ],
   "previous" : null,
   "count" : 1
}
```

I wouldn't at all expected the change of the output when setting as simple as PAGE_SIZE changes. I would expect that output may change, when I change `DEFAULT_PAGINATION_CLASS`. But personally I'd suggest to keep the basic output structure same regardless of pagination, i.e. objects always listed in `results`. If pagination is enabled, add and only add items to the output.

**Comment by xordoquy** [comment]
Pagination behavior is explained at the beginning of the [pagination documentation page](http://www.django-rest-framework.org/api-guide/pagination/).
> Pagination is only performed automatically if you're using the generic views or view sets.
> ...
> Pagination can be turned off by setting the pagination class to None.

When changing `PAGE_SIZE` to something different from `None` will activate the pagination as said in the PAGE_SIZE settings documentation page:

> If set to None, pagination is disabled by default.

Which means that anything different from `None` will activate it.

**Comment by ziima** [comment]
Yes, I checked the documentation, and I found no indication, that enabling the pagination will lead to a completely different structure on the output. I would expect a serious warning and that's what I object against.

**Comment by carltongibson** [comment]
@ziima I can see it's a surprise :)

The change isn't that serious for your client code. Assuming you're accessing the response data from a variable called `data` just add something like...

     all_data = data
     data = data["results"]

... and the rest of your code will remain unchanged.

**Comment by ziima** [comment]
I know how to fix it. But it was one hell of a surprise.

It is kind of a bummer, since probably the only reasonable way using the rest framework is to always define `PAGE_SIZE` in settings.

**Comment by truthdoug** [comment]
I stumbled on this discrepancy when updating an app from DRF 2.3.x to 3.6.x. In 3.1 DRF changed how pagination worked and my app had pagination defined in ViewSet classes. Since the syntax changed, there was effectively no pagination and I got everything.

**Comment by carltongibson** [comment]
@truthdoug These [changes were documented in the Version 3.1 Release Notes](http://www.django-rest-framework.org/topics/3.1-announcement/#pagination)

**Comment by ziima** [comment]
I still miss a significant warning about the major change of the output structure when the pagination is turned on. Or an option to enforce items listed in `results` regardless of whether the pagination is turned on.
