### ISSUE TITLE
Option to turn off filter form in browsable API

### ISSUE THREAD

**Issue by stevenhair** [tomchristie/django-rest-framework#4071]
I have a large table (about 400k rows) with a foreign key to another decently-sized table (about 30k rows). With the filtering form added in https://github.com/tomchristie/django-rest-framework/issues/2180, the browsable API doesn't load in a timely manner. Could a setting be added to disable this form?

Currently my workaround is to use v3.2.5.

**Comment by tomchristie** [comment]
> Currently my workaround is to use v3.2.5.

Overriding `to_html` on your filter classes will also work.

**Comment by tiagoboldt** [comment]
This is a duplicate of issue #4070

**Comment by tomchristie** [comment]
Thanks for pointing to that, @tiagoboldt
