### ISSUE TITLE
Idea/Request: Extend SimpleRouter get_default_base_name to also lookup serializer_class.Meta.model

### ISSUE THREAD

**Issue by anx-ckreuzberger** [tomchristie/django-rest-framework#4072]
I am using SimpleRouter to create routes for my viewsets. While doing this, I also have (several good) reasons to override the get_queryset method in my ViewSets.
This requires me to also set queryset MyModel.objects.none(), else I do get an error that base_name is not set for my ViewSet.

> `base_name` argument not specified, and could not automatically determine the name from the viewset, as it does not have a `.queryset` attribute.

Code looks as follows (simplified example, I'm also using my own Object Manager which implements created_by_current_user() and viewable() - you could replace that with objects.filter(...) in your mind, if you want)
```
class ProjectViewSetAuthenticated(ModelViewset):
    serializer_class = ProjectSerializer

    def get_queryset(self):        
        return Project.objects.created_by_current_user().viewable()
```

However, I do have a serializer on my model, which also has `class Meta` and sets `model = Project`.

```
class ProjectSerializer(ModelSerializer):
    class Meta:
        model = Project
```

Now we look at what `SimpleRouter.get_default_base_name` is doing:

```
    def get_default_base_name(self, viewset):
        queryset = getattr(viewset, 'queryset', None)

        assert queryset is not None, '`base_name` argument not specified, and could ' \
            'not automatically determine the name from the viewset, as ' \
            'it does not have a `.queryset` attribute.'

        return queryset.model._meta.object_name.lower()
```

So I'm wondering if it is possible/good practice to just extend it as follows:
```
from rest_framework import routers

class CustomSimpleRouter(routers.SimpleRouter):
    def get_default_base_name(self, viewset):
        # get the serializer class of the viewset
        serializer = getattr(viewset, 'serializer_class', None)
        # if serializer is set and .Meta.model is set, we can access the models name and return it
        if serializer is not None and serializer.Meta.model is not None:
            return serializer.Meta.model.__name__.lower()

        # else: do whatever the super class wants to do
        return super(CustomSimpleRouter, self).get_default_base_name(viewset)
```

This updated method has the benefit of also looking if serializer.meta.model is set, and in the same way it returns the name of the model. My preliminary testing shows that this works, though I'm sure I will be getting in deep trouble sooner or later. 
Anyway, what do you guys think about this? Would this be something that could be merged into DRF?

**Comment by xordoquy** [comment]
I'd rather have routers call the `get_serializer` instead of using the `.queryset` to fix this sort of issue.
I don't think there will be drawbacks to this as query sets are lazily evaluated.
Thoughts ?

**Comment by anx-ckreuzberger** [comment]
I'm not sure what exactly you mean, but I think it would go along the lines of
`viewset.get_queryset().model.__name__.lower()`?

**Comment by xordoquy** [comment]
Yes although there should be a bit more logic around to ensure that get_queryset().model exists (get_queryset could possibly return a list for example).

**Comment by tomchristie** [comment]
I'd suggest setting the base_name argument explicitly in this case. No particular need for us to cover ever edge case when we do provide an explicit option, right?

**Comment by tomchristie** [comment]
It's been a deliberate design decision for the default behaviour to be simple rather than automagical, so I think I'm okay with how this is, as it currently stands.

**Comment by fladi** [comment]
Isn't setting `base_name` against the DRY principle? There is usually a good chance that `get_queryset` returns just a limited queryset (e.g. filtering by owner/user) with the `model` property still available, thus it is not that different from setting the `queryset` property in the first place.

**Comment by tomchristie** [comment]
There's different concerns here. We're opting for the more explicit & simpler design choice.
