### ISSUE TITLE
Idea: pass additional arguments into get_serializer_class

### ISSUE THREAD

**Issue by resalisbury** [tomchristie/django-rest-framework#4077]
See PR https://github.com/tomchristie/django-rest-framework/pull/4078 for changes

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Rational

Passing in `*args` and `**kwargs` into `get_serializer_class` allows the method greater flexibility in determining which serializer class to use.  

For example, I want to return either a `RestaurantSerializer` or a `BarSerializer` (`Bar` and `Restaurant` are subclasses of `Place`)  from `get_serializer_class,` but, to do so, I need access to the `instance` that is passed as an argument to `get_serializer`, but is not passed into `get_serializer_class`.  

To solve this issue, I'm currently overriding `get_serializer` (which is not suggested via the docs), thusly:
```
    def get_serializer(self, instance, *args, **kwargs):
        kwargs['context'] = self.get_serializer_context()
        serializer_class = BarSerializer if isinstance(instance, Bar) else RestaurantSerializer
        return serializer_class(instance, *args, **kwargs)
```

The proposed change would allow me to instead override `get_serializer_class` thusly:
```
def get_serializer_class(self, instance, *args, **kwargs):
    return BarSerializer if isinstance(instance, Bar) else RestaurantSerializer
```

notes: there may be other use cases as well where this is helpful.  In my use case (shown above), it may be better to handle the polymorphism at the serializer level instead of at the view level.

**Comment by resalisbury** [comment]
I think I may just handle this with a Polymorphic serializer instead
```
class PlaceSerializer(serializers.ModelSerializer):

    class Meta:
        model = Place

    def to_representation(self, obj):
        if isinstance(obj, Restaurant):
            return RestaurantSerializer(obj, context=self.context).to_representation(obj)
        elif isinstance(obj, Bar):
           return BarSerializer(obj, context=self.context).to_representation(obj)
        raise Exception('Unexpected type of tagged object')
```

**Comment by tomchristie** [comment]
On balance I think we'd be better off leaving things as they are, and allowing the developer to override `get_serializer` (eg as you're already doing) if they want to modify this behavior.
