### ISSUE TITLE
docs.authentication: schema migration required by `authtoken` explained only for South

### ISSUE THREAD

**Issue by glarrain** [tomchristie/django-rest-framework#4081]
In `docs/api-guide/authentication.md`, section "API Reference" / "TokenAuthentication" / "Schema migrations", a migration requirement is mentioned if a custom user model is being used. However, it is explained how to do that only for South and not when using its official successor (Django migrations).

> You can do so by inserting a needed_by attribute in your user migration
> ...
> For more details, see the south documentation on dependencies.

It seems replacing `needed_by` with `run_before` is enough but I'm not sure.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

N/A

## Expected behavior

N/A

## Actual behavior

N/A

**Comment by xordoquy** [comment]
I don't think `run_before` is used in django migrations. You probably mean `dependencies`.

**Comment by xordoquy** [comment]
Note for later, this doesn't require much here.
The authtoken migration already has the AUTH_USER as a dependency, so we really just need to say there's basically nothing to do \o/

**Comment by glarrain** [comment]
@xordoquy `run_before` exists at least Django 1.8

https://docs.djangoproject.com/en/1.9/howto/writing-migrations/#controlling-the-order-of-migrations

**Comment by xordoquy** [comment]
Fair enough, didn't know about `run_before` but I'll stand by my previous comment, en particular since the Django documentation says:

> Prefer using dependencies over run_before when possible. You should only use run_before if it is undesirable or impractical to specify dependencies in the migration which you want to run after the one you are writing.

**Comment by glarrain** [comment]
@xordoquy ok. Then let's have docs either for both South and Django Migrations, or for none of them.
