### ISSUE TITLE
Maybe there is something wrong in ChoiceField.

### ISSUE THREAD

**Issue by jz0630** [tomchristie/django-rest-framework#4082]
## Steps to reproduce
My code just like this.
```
MY_CHOICES = (
    (0, 'happy'),
    (1, 'sad')
)
serializers.ChoiceField(MY_CHOICES)
```
## Expected behavior
When the value of the field is 0, I expect the representation is 'happy'.

## Actual behavior
It's representation 0 instead.

When I change the code of ChoiceField, it well be right. The diff of the change is https://github.com/jz0630/django-rest-framework/commit/958033ad878f3eb0d0dcbe45dd35c7a4bda53654

**Comment by carltongibson** [comment]
> The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name

So when serialised you get the first value. (You get the second value in things like form select options.)
