### ISSUE TITLE
Exceptions raised on request._authenticate

### ISSUE THREAD

**Issue by cristianocca** [tomchristie/django-rest-framework#4087]
Hello there,

I have come to a very odd behaviour, where I was getting exceptions raised twice, the first one correctly handled at the custom exception handler, but for my surprise, the exception handler failed with yet ANOTHER exception breaking the complete exception handling chain.

After looking a bit, I found out that the reason is that I'm trying to log on the exception handler the actual logged in user (using request.user), but since the first exception initially raised during authentication (at request._authenticate) and was not handled by the except part because it was not an APIException (it was another unexpected DB error), the actual request.user was not set, so it would try to authenticate again when trying to access the request.user property at my custom exception handler, resulting on a new exception that wouldn't get handled by any means.

Is there any specific reason that request._authenticate only handles APIException? Could it be safely changed to be an except Exception instead? Do I really need to surround all my request.user access in a try catch everywhere just in case the property wasn't cached due to non APIException? In my opinion the exception catched should be Exception and not APIException.

**Comment by xordoquy** [comment]
You really don't want to hide DB error. This is a sign that your system has a severe issue and you want to know about it.
Exception handler only deals with APIException but those are the only ones to be expected.
Anything else should either be caught in project's code or shouldn't go unnoticed as it'll be a sign of a real issue with the system.

**Comment by cristianocca** [comment]
Hello,
 
Maybe I wasn’t clear. I’m not saying to hide the error in any way and I agree with what you said. However what I’m asking is that there should be a way that the the request.user property gets cached even if there was a non APIException error. Right now it is quite a pain if you have multiple loggers and each one of them attempts to access the user variable, you end up calling the auth system over and over just to fall into the same error. Is there a way to prevent that? I think that the auth call should cache the user/non user in any exception (while still raising the exception)
Please consider re opening the issue.

**Comment by xordoquy** [comment]
Caching would create more issues than it solves.
Faced that with Django's form validation. I think when a validate function fails during is_valid, it'll crash on the first call, then it'll tell your form is valid which leads to a *lot* of confusion.

**Comment by cristianocca** [comment]
Hi, just to make sure we are talking about the same.
I'm talking about these lines: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L317

This has nothing to do with forms, the user is already cached on any APIException (and by cached I mean set on a private variable).

The issue is, if for some reason the authentication fails with another exception that's not an APIException, the value is not cached (no anonymous user, no user, nothing) and so any further access to request.user will re try to authenticate, either giving an okay result or failing again which doesn't seem completely correct.

The particular use case, is that if you have a few loggers that receive the request object, and any or all of them also tries to log the user, all of them will try to authenticate again probably failing for the same initial reason, chaining more exceptions unless request.user is surrounded in a try catch block, which will only mitigate the exception but still try to authenticate many times.

I'm wondering if there's a better approach rather than surrounding request.user on a try catch every time it is being accessed on a logger.
