### ISSUE TITLE
Website for DRF 2.x documentation is down

### ISSUE THREAD

**Issue by LukeSwart** [tomchristie/django-rest-framework#4088]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

The website for the DRF 2.x docs is down, which should be here: http://www.tomchristie.com/rest-framework-2-docs/

The site was working fine about 1-2 weeks ago. Perhaps the registrar was recently changed, and/or DNS records need to be updated?

Some links to the broken site can be found here: http://www.django-rest-framework.org/, and at the top of the README for this repo. At the very least, it would be nice to remove these links, or explain why the site no longer exists.

## Expected behavior

The site should take us to the docs for DRF version 2.x

## Actual behavior

The site is down.

## Note:
I am in the process of upgrading from DRF 2.3 to DRF 3.x, so the DRF version 2 docs are helpful in this process. Hopefully I won't need them much longer! But I imagine others may need the link to the version 2.x docs as well, so it would be nice to keep them around.

**Comment by jpadilla** [comment]
@LukeSwart I've assigned @tomchristie to this to get it sorted. In the meantime you can also find those docs at https://github.com/tomchristie/rest-framework-2-docs/tree/gh-pages

**Comment by LukeSwart** [comment]
@jpadilla Thanks!

**Comment by LukeSwart** [comment]
Looks like this issue has been resolved, and the website is currently up here: http://www.tomchristie.com/rest-framework-2-docs/

So I am closing this issue for now.

**Comment by xordoquy** [comment]
Thanks for the feedback.
