### ISSUE TITLE
'OrderedDict' object has no attribute 'id'

### ISSUE THREAD

**Issue by PrabhakarVijendar** [tomchristie/django-rest-framework#4092]
i get an Atrribute error when im trying to POST a request i see that data gets saved in database table but i get this error message in response.

Exception.....

Exception Type:	AttributeError
Exception Value:	
'OrderedDict' object has no attribute 'id'

my Save method is 

               def post(self, request, format=None):
		serializer = ProjectDetailsSerializer(data=request.DATA)
		projDetails = ProjectDetails()
		if serializer.is_valid():
			custid = request.POST.get("customer_id")
			empid = request.POST.get("employee_id")
			projectname=request.POST.get("project_name");
			projectstartdate=request.POST.get("project_startdate")
			projectmetadata = request.POST.get("meta",default = "")			
			projDetails.project_name=projectname
			projDetails.project_startdate=projectstartdate
			projDetails.customer = Customer.objects.get(pk=custid)			
			projDetails.employee = Employee.objects.get(pk=empid)			
			projDetails.meta = projectmetadata			
			projDetails.save()			
			return Response(serializer.data, status = status.HTTP_201_CREATED)
		    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

please let me know if something is wrong in my post method

## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by tomchristie** [comment]
Usage questions should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework).
