### ISSUE TITLE
503 Service Unavailable when deploy to www.openshift.com 

### ISSUE THREAD

**Issue by tdtanvn** [tomchristie/django-rest-framework#4095]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
when I try to include rest_framework.urls or router.urls on urls.py then see that deploy success but  when enter to webpage I get error 503
mycode

```python
from app import views
router = routers.SimpleRouter()
router.register(r'users', views.UserViewSet)
urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^api', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]
```
I can run normal with local host or deploy to openshift without include urls
I using:

```
djangorestframework>=3.3.3
Markdown>=2.6.6
django-filter>=0.13.0
django>=1.9.5
django-oauth-toolkit>=0.10.0
djangorestframework-oauth>=1.1.0
django-crispy-forms>=1.6.0
djangorestframework-gis>=0.10.1
```

**Comment by jpadilla** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.
