### ISSUE TITLE
quickstart import issues ？

### ISSUE THREAD

**Issue by iliul** [tomchristie/django-rest-framework#4099]
i use python (3.4)，Django (1.8.4)，djangorestframework (3.3.3)，when i try the  [tutorial](http://www.django-rest-framework.org/tutorial/quickstart/#urls) got a error :

> 	No module named 'tutorial.quickstart'

Then i change the "from tutorial.quickstart import views" to "from quickstart import views"  in “urls.py” and ”views.py“ ，its work.

is it a issue ?

**Comment by xordoquy** [comment]
You missed a step when creating the quickstart app

**Comment by HatemAlSum** [comment]
Same issue happened with python(3.5) , Django (1.10) , djangorestframework (3.4.6)
I repeated the tutorial many times , and same issue occur 
I think it is an issue

**Comment by xordoquy** [comment]
@HatemAlSum updated a bit more previous comment.

**Comment by LEE-nuuks** [comment]
i was getting this issues several times,

with-

python version3.6.9

django version3.2.14 and

restframework3.13.1

so, first step:

i just updated the python version to 3.9.13 and django version to 4.0.6 and restframework version was same as before.

second step:

Change from tutorial.quickstart import views to from quickstart import views in tutorial/urls.py file

as well as if you write

from serializers import UserSerializer, GroupSerializer

or

from tutorials.quickstart.serializers import UserSerializer, GroupSerializer

in tutorial/quickstart/views.py file then you can change it to

from quickstart.serializers import UserSerializer, GroupSerializer or from .serializers import UserSerializer, GroupSerializer.

Hopefully, This should work.


source : https://stackoverflow.com/questions/39890020/python-importerror-no-module-named-tutorial-quickstart/73170843#73170843
