### ISSUE TITLE
ReadOnly fields should not be sent in POST, PUT, PATCH request

### ISSUE THREAD

**Issue by hacknaked** [tomchristie/django-rest-framework#4100]
Sorry if I'm wrong with this, but if I set fields as `read_only=True` I'm expecting that those fields not to be included in writing requests as POST, PUT, PATCH.

Just to put some context, this is my scenario:

 - I have a `Model` with `slug` and `name` fields (both required).
 - I have a `ModelSerializer` with `read_only_fields=(slug,)` 
 - I'm expecting `slug` to be showed in GET requests but do not sent `slug` in POST (slugs are set automatically when object is created).
 - The problem is that an error is raised: "slug field cannot be blank".

I cannot realize why fields marked as `read_only=True` are sent on POST requests. It does not have any sense for me (sorry if my intuition is wrong here).

Thanks.

**Comment by hacknaked** [comment]
May be this is somewhat related to #3533.

**Comment by tomchristie** [comment]
Most likely you need to ensure that `slug` is being set when the Model is saved (eg overriding `MyModel.save()` or writing an explicit serializer.create method.

The `read_only` are not being included anywhere, but they are required by your model definition - so they've got to be set to *something*, by some part of your codebase.

**Comment by hacknaked** [comment]
Sorry for the noise. I was digging a bit more in this issue and the problem is that I defined `read_only_fields` in the base class, but not in the sub-class:

```
class MyModelSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.MyModel
        fields = ('name', 'slug',)
        read_only_fields = ('slug',)

class MyOtherModelSerializer(MyModelSerializer):
    class Meta:
        model = models.MyModel
        fields = ('name', 'slug',)
```

I assumed that `read_only_fields` are taken from super class but not. Seems a bit confuse for me but I think is my mistake. Many thanks for so quick response and support.

**Comment by tomchristie** [comment]
Your welcome. Afraid serializer subclassing like that has never really been a supported style, tho that's for a different conversation.
