### ISSUE TITLE
TimeField render returns None instead of 00:00:00

### ISSUE THREAD

**Issue by ehumet** [tomchristie/django-rest-framework#4105]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a model A with a TimeField B in it.
2. Create an instance C of the model A in which the TimeField B has a "00:00:00" value (midnight).
3. Create a default DRF serializer D for the model A.
4. Render the object C through serializer D

## Expected behavior

It should render the TimeField B as "00:00:00".

## Actual behavior

It actually gets rendered as None.

**Comment by tomchristie** [comment]
Confirmed.

**Comment by tomchristie** [comment]
Now resolved in master - thanks for raising the issue!
