### ISSUE TITLE
Request feature of List of List field in serailziers

### ISSUE THREAD

**Issue by anush0247** [tomchristie/django-rest-framework#4108]
I am experimenting with list fields of serailizers. I can able to get list fields of Integers, CharFields and others which will be list, but I am in the need of List of List fields.

I tried some thing like this

```
list_filed = serializers.ListField(child=serializers.ListField(child=serializers.CharField(max_length=20)))
````

But I am getting error when I am giving the input data like 

```
list_filed = [["aneesh"],["Kumar"]]
```
I am getting the below error, can any help me 

```
int() argument must be a string or a number, not 'list'
```

**Comment by tomchristie** [comment]
Not yet convinced from the ticket that the cause isn't some other issue here. (Eg the `int()` argument ... looks suspicious - there's no obvious reason that'd be called in this context, unless something wasn't set up quite how you think it is)
If a simple failing test case demonstrated the issue then I'd reconsider.
