### ISSUE TITLE
Array of Json deserializing error

### ISSUE THREAD

**Issue by khafan246** [tomchristie/django-rest-framework#4110]
A want to store an array of json in a field like this:
```py
name = ArrayField(JSONField(), null=True)
```
posting the corresponding object containing array of json objects like this:
```json
{
...
"name": [{"arg1": 1}, {"arg2": 2}, ...]
...
}
```
raises an exception saying i should not pass text[] in place of jsonb[]

**Comment by xordoquy** [comment]
Closing this as this isn't really actionnable.
Note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to discuss this further. Thanks!

**Comment by tomchristie** [comment]
Linking to discussion: https://groups.google.com/d/msg/django-rest-framework/UhZxda4c1gI/6UJyji5oKQAJ
