### ISSUE TITLE
v3.3.3: Browsable API returns "CSRF Failed: CSRF token missing or incorrect."

### ISSUE THREAD

**Issue by mbrochh** [tomchristie/django-rest-framework#4113]
I copied over my DRF setup from a project that used DRF v3.1.3 and it fails in v3.3.3.

Here are my settings:

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.DjangoFilterBackend', ],
    'DEFAULT_VERSIONING_CLASS':
        'rest_framework.versioning.URLPathVersioning',
    'ALLOWED_VERSIONS': ['v1', ],
}
```

Here is my ViewSet:

```
class ArtFairsAPIViewSet(viewsets.ModelViewSet):
    queryset = models.ArtFair.objects.all()
    serializer_class = serializers.ArtFairSerializer
    permission_classes = [permissions.DjangoModelPermissionsOrAnonReadOnly, ]
```

and here are my URLs:

```
router = DefaultRouter()
router.register(r'art-fairs', art_fairs_api.ArtFairsAPIViewSet)

urlpatterns = patterns(
    '',
    url(r'^api/(?P<version>v1)/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls',
        namespace='rest_framework')),
   ...
)
```

I think I'm not doing anything fancy here. When I access the browsable API, I can login and I can see the POST form. When I inspect the markup, I can see that the `csrftoken` hidden field is indeed there.

However, when I submit the POST request, I get "CSRF Failed: CSRF token missing or incorrect." as a response.

When I downgrade to "djangorestframework<3.3", it works.

Is this a bug or am I supposed to use DRF differently as of v3.3?

**Comment by johnraz** [comment]
@mbrochh usage questions like this are usually directed toward the [google group](https://groups.google.com/forum/#!forum/django-rest-framework). I have no idea what the issue may be though.

**Comment by xordoquy** [comment]
The behavior shouldn't have changed from 3.1 to 3.3. A mail to the google group with more context such as the view or even better an example of a failing project would help tracking down your issue.

**Comment by mbrochh** [comment]
If the behavior should not have changed, then this is a bug. I'll try to setup a sample project form a vanilla Django installation and post it here.

**Comment by tomchristie** [comment]
That'd be great - worth getting this nailed down to something more limited. *If* you can replicate this with a vanilla project, then clearly worth re-opening.
I would have *expected* to see other reports, if there was anything significantly wrong in this area.
Can you inspect the outgoing request with the network inspector, and verify what the request looks like there?

**Comment by Jaredn** [comment]
My browsable API does the same thing - used to work fine.  I know this is closed for like 2 years now, but just mentioning.
Django 1.11.5
DRF 3.6.4
