### ISSUE TITLE
Having filter_fields to serializer creates Too large Filter HTML controls in the browsable API

### ISSUE THREAD

**Issue by spreeker** [tomchristie/django-rest-framework#4116]
## Checklist

 I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Add filter_fields to serializer, the field is a foreign_key with A LOT of rows. 

## Expected behavior

Just an empty input field, not 500.000 or more options.. There should be some limit on it.

## Actual behavior

Loading a filtering form control with 500.000 or more items.

**Comment by xordoquy** [comment]
Assuming you're using the `DjangoFilterBackend` you have control how the filter forms are rendered thanks to the widget property.

**Comment by spreeker** [comment]
I think we are not talking about the same thing.. 

The `BrowsableAPIRenderer` do
If I'm correct the `DjangoFilteredBackend` has a `to_html`  method
which loads a` filter_template = 'rest_framework/filters/django_filter.html'`
this one renders a `filter.fom.as_p`. That one tries to put in a very large selectbox in the view.

**Comment by xordoquy** [comment]
`filter.fom.as_p` will be rendered by the filter, rendering that you can control through the widget property. The django-filter documentation should explain how to do that.

**Comment by spreeker** [comment]
I tried to fine the place where to control the widget for a specific field...

and I also came acros:

This is because REST framework 3.0 no longer supports the widget keyword argument since it now uses templated HTML generation.

**Comment by xordoquy** [comment]
> This is because REST framework 3.0 no longer supports the widget keyword argument since it now uses templated HTML generation.

This applies to the create/update form, not the filtering form.

**Comment by spreeker** [comment]
Well I'm diving into the django-filter now and it's interaction with django rest. It is not quire straightforward... if you know of any examples. Now I'm in the source code trying to figure out what happens with the filtered_field atrtribute. I haven't found a way to over ride the choice field yet.

**Comment by spreeker** [comment]
A widgets are not the way to go..

Just Writing a class inheriting from ` filters.FilterSet class` and then just give the offending super large choicebox a simple Charfilter..

`
                    
    class FilterThatWorks(filters.FilterSet):        
           
        super_large_data_field  = django_filters.CharFilter()      
                                                     
        class Meta:                                      
            model = models.Aantekening                   
            fields = [                                   
                'x_field',                      
                'y_field',                         
                'super_large_data_field'                      
            ]          


    class ListViewThatDoesNotWorkWith_HTML_APIVIew(ViewSet):
          ..theususal...
          filter_class = FilterThatWorks
           # do not use filter_fields
`

**Comment by spreeker** [comment]
Shall I add it do the documentation?
