### ISSUE TITLE
the security problem for rest_framework.authtoken.views.obtain_auth_token 

### ISSUE THREAD

**Issue by xiaotangyuan** [tomchristie/django-rest-framework#4126]
the token not change when i login again!!!
is that  security? i think it should gen new token everytime when login using rest_framework.authtoken.views.obtain_auth_token :
token, created = Token.objects.get_or_create(user=user),
here should  update token or create token?

**Comment by tomchristie** [comment]
1. There's plenty of fuller-featured third party options.
2. How you use the authtoken is up to you, perfectly legitimate for you to build 'new token on each login' behavior into your view, yes.
