### ISSUE TITLE
Token-based Authentication docs should note empty throttling/permission defaults.

### ISSUE THREAD

**Issue by tiagoboldt** [tomchristie/django-rest-framework#4128]
The ObtainAuthToken class starts as follows:
```
class ObtainAuthToken(APIView):
    throttle_classes = ()
```
This prevents it from using throttling if configured project-wide. I believe this is not a good practice. Throttling the authentication system is essential to prevent brute-force attacks. 

I know I could create a new class that extends that one and use it for my specific purposes, but i believe that removing the `throttle_classes` parameter from the class would be a more intuitive solution and benefit the project.

Also aligned with my argument, I couldn't find nothing in the documentation stating that `ObtainAuthToken` doesn't comply with the project-wide throttling configurations.

**Comment by tomchristie** [comment]
I think the best option would be for the documentation to explicitly state that default implementation of the `ObtainAuthToken` view has no permissions applied and is unthrottled.

**Comment by tiagoboldt** [comment]
Thanks for the quick answer @tomchristie. Do you see anything against using the project-wide throttling policy? If so, then changing the documentation to reflect it would be a good enough solution for the project and I'll extend the class to implement my own required behavior.

**Comment by tomchristie** [comment]
No there's no problem with using the project-wide settings, so long as whatever anonymous throttling you have configured is also suitable for the auth token view (which will always be an anonymous incoming request). The intent of not using the global defaults is that they may not be appropriate for this particular view (which is a rather diff use case to *other* anonymously accessed views)

I'll mark this ticket as a documentation issue. Thanks for the input!
