### ISSUE TITLE
Permission Classes makes get_queryset works twice in ViewSets 

### ISSUE THREAD

**Issue by realsby** [tomchristie/django-rest-framework#4129]
Sorry for my English. 

When I use this permissions globally in my settings.py.. It cause work twice `get_queryset()` in my ViewSets. Is this normal?

```python
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    )
}
```

**Comment by tomchristie** [comment]
I assume that's only with the browsable API, where we check permissions before displaying the various available actions.

**Comment by JustinAzoff** [comment]
Hi,

I just noticed this behavior in one of my apps, it appears this commit caused it:

https://github.com/tomchristie/django-rest-framework/commit/c2e536bfda6ca65fb3ecd94522ba50ca80279456

has_permission used to use the dummy queryset attribute but is now always calling get_queryset.

I'm doing
```
class BlockQueue(generics.ListAPIView):
    serializer_class = BlockQueueSerializer
    permission_classes = [DjangoModelPermissions]
    queryset = Block.objects.none()  # Required for DjangoModelPermissions

    def get_queryset(self):
        ....
```
I've been meaning to move away from modelpermissions anyway so not a huge issue for me, but this may be not the intended behavior.

If it helps, these are the two tracebacks for the calls to queryset:

```
('/usr/local/lib/python2.7/site-packages/rest_framework/permissions.py', 116, 'has_permission')
('/usr/local/lib/python2.7/site-packages/rest_framework/views.py', 318, 'check_permissions')
('/usr/local/lib/python2.7/site-packages/rest_framework/views.py', 377, 'initial')
('/usr/local/lib/python2.7/site-packages/rest_framework/views.py', 454, 'dispatch')



('/usr/local/lib/python2.7/site-packages/rest_framework/mixins.py', 40, 'list')
('/usr/local/lib/python2.7/site-packages/rest_framework/generics.py', 201, 'get')
('/usr/local/lib/python2.7/site-packages/rest_framework/views.py', 463, 'dispatch')
```

**Comment by xordoquy** [comment]
@JustinAzoff thanks for digging the issue.
I think we'll leave this is it currently is and will leave the optimizations up to the developers.

**Comment by tomchristie** [comment]
Note that this doesn't neccessarily mean that the queryset is *evaluated* twice.
We're not calling it in order to get the result set, only to determine the associated model class.

**Comment by eldano1995** [comment]
> I assume that's only with the browsable API, where we check permissions before displaying the various available actions.

Could you give details about this?? (a link to the section of the code where this is happening would be great)
