### ISSUE TITLE
Accept updated related pk to nested resource instead of read_only

### ISSUE THREAD

**Issue by shanemgrey** [tomchristie/django-rest-framework#4133]
After working around the inability to update a ForeignKey when it is serialized as a nested object, I have a suggestion for enhancement.

**Problem:**

Often it's desirable to change only the reference to a foreign model instance without changing the instance.

DRF offers only two options for nested data. The field is either completely read_only, or custom .create() and .update() methods must be written.

**Suggestion**

A new behavior should be added to remove the need for read_only, and the need to write custom methods when the only thing needing changing is the reference to the related instance.

When receiving an object with a nested field, DRF should read the PK field (id) of the nested object and ignore the rest of the data it contains.  In other words, it should treat the nested field as if it were only its PK.

To avoid leading a developer to believe the nested information is being updated without an .update() method, there could be a new param like "update_reference_only=True".  And when there is no parameter or custom method provided, the console error could be changed to the following:

    AssertionError: The `.update()` method does not support writable
    nested fields by default. Write an explicit `.update()` method for serializer
    or add `update_reference_only=True` to the field to update only the 
    reference to the foreign instance and not it's nested data. 

Same for .create().

This is the write up I did for my work around without this enhancement. http://stackoverflow.com/questions/37285305/update-only-foreignkey-reference-when-given-nested-object/37285306#37285306

**Comment by xordoquy** [comment]
> Often it's desirable to change only the reference to a foreign model instance without changing the instance.
> DRF offers only two options for nested data. The field is either completely read_only, or custom .create() and .update() methods must be written.

I'm really sorry but I don't see the problem here.
`.create()` and `.update()` have been added on purpose to handle all the possible use cases such as yours. Therefore you can override them and handle the logic there.

I'm closing this as there are so many similar edge cases we can't add property for each of them.
Override the create/update is simple enough though might not be as easy as a changing a flag.

**Comment by shanemgrey** [comment]
@xordoquy  My thinking on it was that this behavior would be more useful than that of read_only which from what I can tell only serves to make the developer explicitly flag the field as unwritable to acknowledge the behavior and avoid the assertion error.

While I agree with the comments on the assertion that the behavior should not be ambiguous, If the dev is going to explicitly define anything in a flag, it might as well be useful instead of just clarifying.  

The behavior of taking changes to the PK is the same behavior DRF would use with the data if it wasn't nested.  So it would make sense as a default if not for that ambiguity problem.  Which is why I suggested making it require an explicit flag instead of default behavior.  

The same behavior could be used for ForeignKey .create() . And I think it would apply to m2m .update() just as well. 

In any case, I truly appreciate that you reviewed and responded to the issue so quickly.  The high level of activity on this project is the primary reason I changed over from node based API building to django.  

It's far more mature. And the community you help maintain is so much stronger.

**Comment by xordoquy** [comment]
> My thinking on it was that this behavior would be more useful than that of read_only which from what I can tell only serves to make the developer explicitly flag the field as unwritable to acknowledge the behavior and avoid the assertion error.

`read_only` has an effect on on validation which makes it different from your flag.

There are a lot of APIs outside that do use that almost discards the ID and simply updates the various associated fields.
Overriding `create`/`update` allows everyone to define its own policy and keeps things open.
