### ISSUE TITLE
404 after browsable API login

### ISSUE THREAD

**Issue by kodeine** [tomchristie/django-rest-framework#4138]
when I try to login using the Rest Framework browsable API, I get a 404 after the login and the url points to /accounts/profile.
I dont have any of that url list. can anyone help?

```python
urlpatterns = [
    url(r'^$', views.hello_world, name='home'),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^geo/?$', GeoViewSet.as_view({'get': 'get_cities'})),
    url(r'^geo/(?P<city>[\w-]+)/$', GeoViewSet.as_view({'get': 'get_areas'})),

    url(r'^v1/', include(api_patterns)),
]

urlpatterns = format_suffix_patterns(urlpatterns)

```
Thanks

**Comment by xordoquy** [comment]
Hi,

This is not a support forum.
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by alfredrumss** [comment]
@kodeine did you solve this?  I'm having the same problem.
