### ISSUE TITLE
SerializableRelatedField

### ISSUE THREAD

**Issue by KhasanovBI** [tomchristie/django-rest-framework#4140]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Description

In my work in many cases we need pass to serializer in data primary keys, but have a represent of this field.
For example, we have one endpoint, where we are looking for people, and second endpoint where we create something, where there is a queue of people, where we specify the id of people, we don't create an object, so I do a field that take primary key as internal value, and represented by some serializer.

**Comment by tomchristie** [comment]
Custom fields like this should generally be handled as third party packages.

(Eg: http://www.django-rest-framework.org/api-guide/fields/#third-party-packages )
