### ISSUE TITLE
filter_backends remove filter_class

### ISSUE THREAD

**Issue by pythdasch** [tomchristie/django-rest-framework#4150]
Hi everyone,

I'm experiencing an issue when I try to add a filter_backends it disable my filter_class
I want to be able to search through the model via filter_class and also ordering via filtersOrdering backends.
When I remove the filter_backend, the filter_class works fine, but when I add it, it's no more working.

Here is my code : 

     class ProjectsFilter(filters.FilterSet):
         title = django_filters.CharFilter(name="title", lookup_type='icontains')
    ministery = django_filters.ModelChoiceFilter(name="ministery", label="Ministery",     queryset=Ministery.objects.all(), help_text="Ministery")
        city = django_filters.CharFilter(name="city__name", label="City", lookup_type="icontains", help_text="City?")
        tags = django_filters.CharFilter(name="tags__name", label="tag", lookup_type="icontains", help_text="tags?")

    class Meta:
        model = Project
        fields = ['ministery', 'title', 'city', 'tags',]

    class ProjectViewSet(viewsets.ModelViewSet):
        queryset = Project.objects.select_related("created_by", "ministery").all()
        serializer_class = ProjectSerializer
        filter_class = ProjectsFilter
        filter_backends = (filters.OrderingFilter,)
        ordering_fields = ("projectviews", "like", "created")

I search through other solutions and couldn't make it. Finally I tried to put filter_class as a backend but it's too heavy.

Is this normal ?
I've : 
djangorestframework==3.3.3
django-filter==0.13.0
django 1.9.2
Thanks in advance

**Comment by xordoquy** [comment]
Please use the mailing for usage questions.

**Comment by pythdasch** [comment]
it's not an issue ?

**Comment by tomchristie** [comment]
> it's not an issue?

Nope, it's not.

You're setting the filters on the view, and overriding the default filters, you almost certainly want...

    filter_backends = (filters.OrderingFilter, filters.DjangoFilterBackend)

instead of...

    filter_backends = (filters.OrderingFilter,)

**Comment by pythdasch** [comment]
If I remember well, I did it. But it wasn't using my custom filter class ...

**Comment by vantrong291** [comment]
I have same error, my solution is:

     filter_backends = (rest_framework.filters.OrderingFilter,  
     django_filters.rest_framework.DjangoFilterBackend)
