### ISSUE TITLE
Making the depth dynamically adjustable

### ISSUE THREAD

**Issue by samirotiv** [tomchristie/django-rest-framework#4163]
Hi,
It would be great if the depth field as well is dynamically adjustable! This would make it easy for the nesting level to change, depending on the request data coming in.

This is especially useful for applications which have some degree of offline-online synchronization, and want to sometimes update all related fields in one single request.

I have already implemented this, and will send you a pull request in a moment.

Best regards,

Samir.

**Comment by tomchristie** [comment]
Reasonable enough, but this isn't a use-case I particularly want to support.

Given that it adds a little complexity to the mechanics of `ModelSerializer`, and also that it allows users to do ever more complicated things with the API, I'd prefer to leave this out, and leave any changes like this to instead be made inside your own ocdebase.

If this is something you need widely, then perhaps implement it on a ModelSerializer base class that you use throughout the codebase. I assume you could implement it as a property that ends up setting `.Meta.depth`. If it's something you're particularly keen on it could even be distributed as a third party package, in which case we'd link to it from the main docs.
