### ISSUE TITLE
FileUploadParser, "filename" keyword argument is ignored

### ISSUE THREAD

**Issue by paweljasinski** [tomchristie/django-rest-framework#4168]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
setup a minimum raw file upload based on FileUploadParser 
upload file using: 
`curl 'http://d2:8000/uploadapp/uploadfile?filename=2.jpg --upload-file 1.jpg`

## Expected behavior
`request.data['file'].name` should be `2.jpg`

## Actual behavior
`request.data['file'].name` is tmp[random].upload, actual value: `tmpgxxugw2g.upload`

## Workaround
Use Content disposition header.

`curl 'http://d2:8000/uploadapp/uploadfile --upload-file 1.jpg --header "Content-Disposition: attachment; filename=1.jpg"`

gives the expected:
`request.data['file'].name` == `1.jpg`

## Investigated
`get_filename` in `parsers.py`, `parser_context['kwargs']` appears empty

dirty fix, just to demonstrate the problem
```
diff rest_framework/parsers.py .hide/rest_framework/parsers.py
192c196
<             return parser_context['kwargs']['filename']
---
>             return parser_context['request'].query_params['filename']
```

**Comment by tomchristie** [comment]
The behavior is as describe here: http://www.django-rest-framework.org/api-guide/parsers/#fileuploadparser

It supports the following style:

    http://api.example.com/upload/2.jpg

You need to make sure that your URL conf includes the `filename` portion of the path.

If you want to use a query parameter to set the filename (as you've described in this example), you'll need to customize `FileUploadParser`.
