### ISSUE TITLE
TimeField serializing to None when value is time(0, 0)

### ISSUE THREAD

**Issue by dursk** [tomchristie/django-rest-framework#4175]
If you have a `TimeField` and set the value to `time(0, 0)` it is serializeing to `None`, most likely as a result of this commit: https://github.com/tomchristie/django-rest-framework/pull/3731/commits/fc08236ab84ce7c348216e9662ebec4ac0dea9a8

`time(0, 0)` evaluates to falsey, yet it is a perfectly valid time value. Given why that change was made (to handle string values) I believe the check should explicltly be

```python
if value is None or value == '':
    return None
```

**Comment by jpadilla** [comment]
I think this was already resolved by @tomchristie via #4107.

**Comment by dursk** [comment]
Yup, that definitely fixes it. Sorry for opening, didn't see that in there already.
