### ISSUE TITLE
item.objects.filter(ondate__gt = timezone.now() )   not work

### ISSUE THREAD

**Issue by iloveyo123u1** [tomchristie/django-rest-framework#4186]
ubuntu 16.4 x64

Django (1.9.4)
drf 3.3.3

django  settings.py

```
# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-cn'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  
```

model

```
class item(models.Model):
    turl =  models.URLField('a url')
    ondate = models.DateTimeField('die datetime')
```

serializers
```
class itemSerializer(serializers.ModelSerializer):
 
    class Meta:
        model = item
        fields = ('id','turl','ondate')
```

view

```
class itemViewSet(viewsets.ModelViewSet):
    queryset = item.objects.filter(ondate__gt = timezone.now() )
    serializer_class = itemSerializer
```

then, i run  server
add a data,
ondate i set : 2016-06-10 16:15:00
now time is  2016-06-10 16:14:00

i  can got this data

but ,when now time change to  2016-06-10 16:16:00

I can still get this data

i try restart web server

it's work

--------------------
so , i add a data again

ondate i set : 2016-06-10 16:20:00
now time is  2016-06-10 16:19:00
i  can got this data

but ,when now time change to  2016-06-10 16:21:00

I can still get this data

i try restart web server

it's work again

----------------------
so, why ?

 i think mabye  **timezone.now()**  return datetime  is invalid

could you help me?

please

thank you very much

**Comment by tomchristie** [comment]
Usage questions should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework).

**Comment by tomchristie** [comment]
You're including `queryset = item.objects.filter(ondate__gt = timezone.now() )` which will run and once only, when the module is first loaded.

You need to instead ensure that `timezone.now()` runs on every request.

Use this approach instead:

    queryset = item.objects.all()

    def get_queryset(self):
        return self.queryset.filter(ondate__gt = timezone.now() )

**Comment by iloveyo123u1** [comment]
yes  it's work

thank you very much  dear @tomchristie
