### ISSUE TITLE
Always defer to explicit overrides.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#4198]
Some of these may already be covered, but we should make sure that all the following are satisfied:

* If a user declares a field explicitly, but also includes it in `extra_kwargs` then warn/error.
* If a user declares a field explicitly, but also includes it in `read_only_fields` then warn/error.
* Don't allow `get_uniqueness_extra_kwargs` to override a declared field.
* Don't allow `get_uniqueness_extra_kwargs` to override a flag that has been set in `extra_kwargs`.
* If a serializer field has a `default`, then ensure that uniqueness validators use that for empty, rather than forcing `required=True`

**Comment by gcbirzan** [comment]
> * Don't allow get_uniqueness_extra_kwargs to override a declared field.


This already happens, a declared field will not be re-declared with new args.

> * If a serializer field has a default, then ensure that uniqueness validators use that for empty, rather than forcing required=True

A default of None on a declared field will work for uniqueness validation.

**Comment by tomchristie** [comment]
Thanks for those confirmations @gcbirzan!
