### ISSUE TITLE
Nested serializer overwrites existing data in to_internal_value

### ISSUE THREAD

**Issue by wolfadactyl** [tomchristie/django-rest-framework#4207]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate. - #3999 is similar in that it involves nested serializers but not the same issue
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.) - No PR but have included a viable test case here instead.

## Steps to reproduce
1. Create a serializer with a nested serializer.
2. Create a field in the parent serializer with a source that points to a field in the nested serializer.
3. Serialize a data dict that sets the sourced field in the parent serializer but not the nested one.
4. Call is_valid on the parent serializer.

## Expected behavior
The nested serializer merges data with the existing dictionary.

## Actual behavior
The nested serializer overwrites the existing dictionary entirely.

## Test Case
```
class TestNestedOverlappingSerializer:
    def setup(self):
        class NestedOverlappingSerializer(serializers.Serializer):
            one = serializers.IntegerField(max_value=10)
            two = serializers.IntegerField(max_value=10)

        class TestSerializer(serializers.Serializer):
            onesie = CharField(source='nested.one')
            nested = NestedOverlappingSerializer()

        self.Serializer = TestSerializer

    def test_nested_overlapping_validate(self):
        input_data = {
            'onesie': '1',
            'nested': {
                'two': '2',
            }
        }
        expected_data = {
            'nested': {
                'one': 1,
                'two': 2,
            }
        }
        serializer = self.Serializer(data=input_data)
        assert serializer.is_valid()
        assert serializer.validated_data == expected_data
```

**Comment by wolfadactyl** [comment]
This is specifically an issue with [to_interal_value](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L417) in serializers.py and [set_value](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L97) in fields.py. 

The issue being that values passed in via the source attribute are sent in as individual keys of the nested dictionary whereas the nested serializer is sending in the entire dictionary for the object, which then overwrites any existing data.

**Comment by xordoquy** [comment]
In your case, you have 2 incoming data sources that you "merge" into one. What about:

     {
            'onesie': '1',
            'nested': {
                'one': '5',
                'two': '2',
            }
        }

Should it be 1 or 5 ?

In that case, I consider the developer should take care about that case.
DRF could possibly run a check to ensure the data source is unique but this validation would be quite complex.
I'm closing this because it's not actionnable.

**Comment by wolfadactyl** [comment]
Setting both seems to be a better scenario to handle than silently clobbering valid data as it currently stands. Setting duplicate fields is an invalid usage that is still an issue in either case (and should, in theory, be the responsibility of the developer to avoid), whereas setting one field is a valid usage that is currently unusable.
