### ISSUE TITLE
Serializer for ContentType

### ISSUE THREAD

**Issue by aamupadi1** [tomchristie/django-rest-framework#4208]
I am building an activity model, somewhat similar to this [package](https://github.com/justquick/django-activity-stream). It has an actor, verb and the target.

```
class Activity(models.Model):
    actor_type = models.ForeignKey(ContentType, related_name='actor_type_activities')
    actor_id = models.PositiveIntegerField()
    actor = GenericForeignKey('actor_type', 'actor_id')
    verb = models.CharField(max_length=10)
    target_type = models.ForeignKey(ContentType, related_name='target_type_activities')
    target_id = models.PositiveIntegerField()
    target = GenericForeignKey('target_type', 'target_id')
    pub_date = models.DateTimeField(default=timezone.now)
```
Now whenever a new object of whichever models (Tender, Job and News) is created, a new Activity object is created, with the target being the objects of any of these three models.

eg. user (actor) published (verb) title (target)
```
class Tender(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()

class Job(models.Model):
    title = models.CharField(max_length=256)
    qualification = models.CharField(max_length=256)

class News(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=150)
```
To get this data I am making an API which will get me the required json data. Now using django-rest-framework

```
class ActorSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('id', 'username', 'email')

class ActivitySerializer(serializers.HyperlinkedModelSerializer):
    actor = ActorSerializer()
    class Meta:
        model = Activity
        fields = ('url', 'actor', 'verb', 'pub_date')
```
In the above serializers, I knew that **actor** will be the User. And so I used the User model for the ActorSerializer class. But as for the **target**, it can be any of these three models (News/Job/Tender).

How can I make a serializer (eg. TargetSerialier class) for the ContentType object so that I can use the target in the ActivitySerializer class field?

**Comment by jpadilla** [comment]
Check out http://www.django-rest-framework.org/api-guide/relations/#generic-relationships
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

**Comment by aamupadi1** [comment]
I have changed the serializer class as in the documentation.

```
class ActivitySerializer(serializers.RelatedField):
    """
    A custom field to use for the `tagged_object` generic relationship.
    """

    def to_representation(self, value):
        """
        Serialize tagged objects to a simple textual representation.
        """
        if isinstance(value, User):
            return 'Bookmark: ' + value.username
        elif isinstance(value, Article):
            return 'Bookmark: ' + value.title
        elif isinstance(value, Job):
            return 'Note: ' + value.title
        elif isinstance(value, Tender):
            return 'Bookmark: ' + value.title
        raise Exception('Unexpected type of tagged object')
```

But now I am getting this error:

> TypeError at /postactivities/
> __init__() takes exactly 1 argument (3 given)

Why am I getting this?
