### ISSUE TITLE
`APIView` in line 423 unsupport syantax 

### ISSUE THREAD

**Issue by nooperpudd** [tomchristie/django-rest-framework#4211]
```python

      context = self.get_exception_handler_context()
        response = exception_handler(exc, context)

        if response is None:
            raise # in this bock is unsupport in python3.4 version.

        response.exception = True
        return response

```

**Comment by xordoquy** [comment]
This is perfectly valid in Python 3.4:

    $ python3.4
    Python 3.4.4 (default, Mar  2 2016, 03:31:27) 
    [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> try:
    ...   0/0
    ... except Exception:
    ...   raise
    ... 
    Traceback (most recent call last):
      File "<stdin>", line 2, in <module>
    ZeroDivisionError: division by zero
    >>> 

You probably called the `handle_exception` outside of the scope of an exception

**Comment by nooperpudd** [comment]
@xordoquy no


in a file:
```python
response = None
if response is None:
    raise # in this bock is unsupport in python3.4 version.
```
  File "ss.py", line 4, in <module>
    raise # in this bock is unsupport in python3.4 version.
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

**Comment by xordoquy** [comment]
> You probably called the handle_exception outside of the scope of an exception

**Comment by xordoquy** [comment]
Longer answer:

    def demo():
        response = None
        if response is None:
            raise # in this bock is unsupport in python3.4 version.
    
    try:
        0/0
    except:
        demo()

Save the previous code in a file and run it through Python3.4 and you'll get:

    $ python3.4 demo.py 
    Traceback (most recent call last):
      File "demo.py", line 11, in <module>
        demo()
      File "demo.py", line 9, in <module>
        0/0
    ZeroDivisionError: division by zero

**Comment by nooperpudd** [comment]
@xordoquy Fine.
