### ISSUE TITLE
list_route url conflicts with regex pattern repeat specific times

### ISSUE THREAD

**Issue by zheduanyin** [tomchristie/django-rest-framework#4232]
Hi,

I need to use this regex 

```
[a-z]{10}
```

 in list_route decorator.

Here's my code:

```
@list_route(methods=['GET'], url_path=r'tickets/(?P<ticket_id>[a-z]{10})')
def ticket(self, request, ticket_id=None):
    return Response(cache.get(ticket_id, {}))
```

Somehow it raises a problem below

> .../lib/python3.5/site-packages/rest_framework/routers.py", line 254
> trailing_slash=self.trailing_slash
> IndexError: tuple index out of range

Then I checked the official code of rest-framework, it uses `{xxx}` and `format` to expand url and feed to django regex parser. I guess that is why my regex doesn't work. Hope If this problem can be fixed.

Environment:
```
python @3.5.0
Django @1.9
Django-Rest-Framework @3.3.3
```

**Comment by xordoquy** [comment]
Where did you get that `url_path` is a valid argument ?

**Comment by xordoquy** [comment]
Note that `list_route` is not intended to be used with a regexp.
There's a [third party library](https://github.com/alanjds/drf-nested-routers) to handle nested urls.
