### ISSUE TITLE
How to modify DRF's localized string only in my project?

### ISSUE THREAD

**Issue by mrgaolei** [tomchristie/django-rest-framework#4234]
I'm using `ObtainAuthToken`, and when `username` and `password` is wrong, it return `Unable to log in with provided credentials.`.

I found this code on `AuthTokenSerializer`, like:
```
            if user:
                if not user.is_active:
                    msg = _('User account is disabled.')
                    raise serializers.ValidationError(msg)
            else:
                msg = _('Unable to log in with provided credentials.')
                raise serializers.ValidationError(msg)
```

But how can I customize this string?
I tried add this msgid in to my `.po` file, but there's no any effect.

**Comment by anoopmalav** [comment]
1. Create your own django-app in your django project.
2. Use code from following files:
> https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authtoken/serializers.py
> https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authtoken/views.py

3. Customize code as per your needs
4. And finally use your custom-app's authentication view.
```
from you_project.custom_app import views
urlpatterns += [
    url(r'^api-token-auth/', views.obtain_auth_token)
]
```

**Comment by mrgaolei** [comment]
I retry to modify my .po file, add new line:
```
msgid "Unable to log in with provided credentials."
msgstr "Your E-mail or Password is wrong."
```
 Now It's OK.
