### ISSUE TITLE
pagination.LimitOffsetPagination.paginate_queryset produces inefficient query

### ISSUE THREAD

**Issue by mmalek06** [tomchristie/django-rest-framework#4235]
In line 302 there's this call to _get_count function:

self.count = _get_count(queryset)

The problem is that when you annotate your queryset (in my case it was a restaurants queryset which I annotated with restaurant rating based on related comments rating, so something like annotate(rating=models.Avg('comments__rating'))) the annotation ends up in the count query. For most cases it's not that big of a problem, but if you for example do several geographical annotations this may get a bit too expensive for a simple query that should just return the count of rows in a table.

**Comment by xordoquy** [comment]
Closing this because there isn't enough actionable here.
This is a pretty edge use case which can be worked around by overriding the `paginate_queryset` to altering the query that is used for the count.

**Comment by mmalek06** [comment]
Yeah, and in order to override this method, I had to copy the original code and change one line. So very DRY... :) Not mentioning that it's a really strange behavior, because other columns (not coming from annotations) can be excluded using 'values' call and only annotations are kinda stuck there... That's not what one could expect from library as mature, as this one.

**Comment by tomchristie** [comment]
> Yeah, and in order to override this method, I had to copy the original code and change one line to use other (not annotated) queryset. So very DRY... :)

We can consider pull requests that add additional API override points on their own merits, sure. Tho keep in mind that "DRY" is not the only consideration. Extra API surface area = extra documentation, extra indirection. There's always a trade-off.

**Comment by xordoquy** [comment]
@tomchristie we could work this around by having the get_count moved to the class so it can be more easily overridden just like the other calls from the `paginate_queryset`.

@mmalek06 please, don't use aggressive tone, this will lead to the exact opposite of what you're looking for. There is no reason to be rude and avoid answering my points.

**Comment by mmalek06** [comment]
Och, I didn't intend my comment to be rude. If you felt it that way, then I'm sorry. Hope you guys will resolve this issue somehow.

**Comment by tomchristie** [comment]
@mmalek06 Not to worry, it's all good.

No particular intent to take it on unless someone leads in with a pull request, but we could consider it in that case.
