### ISSUE TITLE
DateTimeField representation sholud be not only in UTC but also settings.TIME_ZONE etc.

### ISSUE THREAD

**Issue by sohopro** [tomchristie/django-rest-framework#4238]
Django stores the models.DateTImeField to DB in UTC but representation is in settinngs.TIME_ZONE.
But rest_frmework.fields.DateTimeField representation is only in UTC.
I think  default representation should be settings.TIME_ZONE.

**Comment by tomchristie** [comment]
Standard practice with APIs is to use UTC, as it's unambiguous.
We could consider further options in this area (eg additional argument to TimeField/DateTimeField) but would consider those on their own merit, and with a pull request against which to discuss.
