### ISSUE TITLE
GenericAPIView without queryset attribute.

### ISSUE THREAD

**Issue by KhasanovBI** [tomchristie/django-rest-framework#4240]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

I want to use `get_serializer` method in GenericAPIView, so I create CBV inherited from GenericAPIView without `queryset` attribute, all ok in json, but in BrowsableAPIRenderer `get_queryset` called in `get_filter_form` and assertion raised.

**Comment by xordoquy** [comment]
Closing this as per #4239. Will consider reopening with evidences.
