### ISSUE TITLE
Schema & Hypermedia follow ups

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#4241]
Placeholder for now to ensure that anything from https://github.com/tomchristie/django-rest-framework/pull/4179 that doesn't make the 3.4.0 cut can be assigned to this ticket.

Currently:

- [ ] Add descriptions to schema generation, and document use of `describe`.
- [x] Supporting `id` as a keyword argument over `pk`.
- [x] Adding type annotations to fields (including in coreapi spec)
- [x] Handle binary downloads in `coreapi` library.
- [ ] Document file uploads and downloads in `API clients` docs.
- [ ] Add to quickstart?
- [ ] Document custom codecs.

**Comment by robermorales** [comment]
"Adding type annotations to fields" seems to be the needed feature to make swagger ui display properly the parameters types. When it will be available? Can I help in some way?

**Comment by tomchristie** [comment]
Already well underway in the existing 3.5 branch. Will be available later this month.

**Comment by tomchristie** [comment]
Folding remaining points into https://github.com/tomchristie/django-rest-framework/issues/4549 and https://github.com/tomchristie/django-rest-framework/issues/4555
