### ISSUE TITLE
to_representation is throwing UnicodeEncodeError

### ISSUE THREAD

**Issue by phr34ck** [tomchristie/django-rest-framework#4252]
I'm using DRF version 3.3.3. `to_representation` is throwing `UnicodeEncodeError` when I have arabic text. I'm using the default renderers. 

    class MySerializer(ModelSerializer):
         def to_representation(self, obj):
             return { 'name': obj.name }  <--- UnicodeEncodeError
        class Meta:
            model = MyModel

If I remove `to_representation` everything works fine and the data is rendered correctly (json):

    class MySerializer(ModelSerializer):
        class Meta:
            model = MyModel
            fields = ("name",)

Here's a sample content that causes `to_representation` to throw an exception:  بالعربي 
unicode: u'\u0628\u0627\u0644\u0639\u0631\u0628\u064a'

Is there any way I can use `to_representation` when I have arabic content?

**Comment by xordoquy** [comment]
@phr34ck At this point, it's not clear to us where the issue may be. Would help a lot if you could make the simpler test cases that would allow us to make sure it's not a user's error and help us understand where the issue might be.

**Comment by phr34ck** [comment]
@xordoquy sorry about the lack of information. I will include everything:

    # Model 
    class MyModel(models.Model):
        name = models.CharField(max_length=255)

    # Serializer
    class MyModelSerializer(serializers.ModelSerializer):
        def to_representation(self, obj):
            return { 'name': obj.name }

        class Meta:
            model = MyModel

    # Viewset
    class MyModelViewSet(viewsets.ReadOnlyModelViewSet):
        queryset = MyModel.objects.all()

    # Routing
    router = DefaultRouter()
    router.register(r'mine', viewsets.MyModelViewSet)

Sample data for name: 

- بالعربي    -- If you print it out from the console: `u'\u0628\u0627\u0644\u0639\u0631\u0628\u064a'`
- اللغة العربية --  If you print it out from the console:`u'\u0627\u0644\u0644\u063a\u0629 \u0627\u0644\u0639\u0631\u0628\u064a\u0629'`

When I visit: `url/mine/` which should return the list of objects I get the following error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0x89 in position 1: ordinal not in range(128)`

Full stacktrace:

> Traceback (most recent call last):
  File "/home/vagrant/project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/project/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/vagrant/project/local/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/vagrant/project/local/lib/python2.7/site-packages/rest_framework/response.py", line 71, in rendered_content
    ret = renderer.render(self.data, media_type, context)
  File "/home/vagrant/project/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 104, in render
    separators=separators
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)

Please note that none of that happens if I don't have `to_representation` defined and I'm simply using
    class MySerializer(ModelSerializer):
        class Meta:
            model = MyModel
            fields = ("name",)

That will return the data and they're rendered correctly. 

Please let me know if you need additional information.

**Comment by xordoquy** [comment]
Unicode with Python 2.7 is prone to a lot of user's errors. Any chance you could test against Python 3.x ?

**Comment by phr34ck** [comment]
It's almost impossible at this stage of the project to switch to a different python version. The testing will take quite a lot of time and I don't have time at all. What I don't understand is why everything is working fine except `to_representation` function. I'm going to find another way for my requirements.

**Comment by xordoquy** [comment]
Can't reproduce the issue on my side.
Will reopen if we have a failing test case.
Note that somehow it feels like you're passing a binary string to the serializer which can't then encode it.

**Comment by phr34ck** [comment]
for future reference: local environment variables were absent due to how uwsgi works, I had the add the following to my uwsgi config:

`env = LANG=en_US.utf8`
`env = LC_ALL=en_US.UTF-8`
`env = LC_LANG=en_US.UTF-8`
`env = PYTHONIOENCODING=UTF-8`
