### ISSUE TITLE
Allow configuration of DefaultRouter's root view renderer classes

### ISSUE THREAD

**Issue by marcgibbons** [tomchristie/django-rest-framework#4268]
Currently, we can set the schema_renderer classes as kwargs on the DefaultRouter, but can't override the renderer classes used on the root view which comes from the settings. 

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/routers.py#L292

It would be desirable to replace BrowsableAPI renderer with the SwaggerUI html renderer in Django REST Swagger.

Referencing issue:
https://github.com/marcgibbons/django-rest-swagger/issues/479#issuecomment-232998716

**Comment by tomchristie** [comment]
Thanks Marc. Getting back onto the project after DjangoCon - apologies for the delay.

**Comment by marcgibbons** [comment]
100% thanks for all the hard work!
