### ISSUE TITLE
Migration issue with authtoken

### ISSUE THREAD

**Issue by Tyndie** [tomchristie/django-rest-framework#4280]
I have been experiencing a migration issue with the authtoken model since 3.3.3 using mysql as my database host.

I am using email address as the user id in my auth model, which should get automatically picked up by the initial migration in the swappable dependency check.

Here is an output of the error: https://gist.github.com/Tyndie/6cb9f4a9f5c10ee660574ce9036259c5

**Comment by xordoquy** [comment]
This feels like you changed the user model after the database was created which is not something Django handles.
Will reopen if this proves to happen with a totally empty DB.
