### ISSUE TITLE
JSON indent parameter in Accept header ignored 

### ISSUE THREAD

**Issue by nealtodd** [tomchristie/django-rest-framework#4281]
Refactoring between 3.3.3 and 3.4.0 changed how `Response.render` passes `media_type` to its `renderer`.

[Response](https://github.com/tomchristie/django-rest-framework/blob/e476c222f98c4a455bf806fa05c5d70a9e0f37da/rest_framework/response.py#L60) sets it as `media_type = renderer.media_type` compared to `self.accepted_media_type` (set via `APIView.finalize_response` [here](https://github.com/tomchristie/django-rest-framework/blob/e476c222f98c4a455bf806fa05c5d70a9e0f37da/rest_framework/views.py#L405)).

Since `renderer.media_type` looses the indent parameter (i.e. `application/json; indent=4` becomes `application/json`), the resulting JSON rendering is not indented.

A 'simple' fix is to restore the 3.3.3 code where `media_type = getattr(self, 'accepted_media_type', None)` but I haven't made a PR yet because I'm not clear as to whether there was a specific reason for changing to `renderer.media_type` (which might have overlooked that it doesn't include `indent`).

**Comment by pembo13** [comment]
I can confirm, the media_type value that get_ident receives is stripped of params.

**Comment by tomchristie** [comment]
Thanks for raising this. Addressed in #4313.
