### ISSUE TITLE
Document the value type for the ALLOWED_VERSIONS setting

### ISSUE THREAD

**Issue by strife25** [tomchristie/django-rest-framework#4282]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

When looking through the documentation for API versioning, I came across the docs for [ALLOWED_VERSIONS](http://www.django-rest-framework.org/api-guide/settings/#allowed_versions). 

## Expected behavior

When reading through the documentation, I expected the type that the value should be set to to be defined. For example "This setting's value should be a list or tuple of string values".

## Actual behavior

The expected data type is not explicitly defined in the documentation. I had to [look up the code](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/versioning.py#L33) that checks the value to determine what the expected value is.

**Comment by xordoquy** [comment]
Will definitively consider a PR to improve that part but closing this issue meanwhile.

**Comment by strife25** [comment]
Ok! Thank you for responding. I didn't see it in the contribution docs, but is there a more appropriate place to open documentation issues or did I follow the correct process?

- John Ryding

**Comment by xordoquy** [comment]
It's ok, it's just that someone now needs to make it happen.
As we already have more than enough work to do we won't be able to deal with this.
