### ISSUE TITLE
SwaggerRenderer example doesn't match the ";version=2.0" part of media_type

### ISSUE THREAD

**Issue by osantana** [tomchristie/django-rest-framework#4287]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Implement the documentation example of SwaggerRenderer at: https://github.com/tomchristie/django-rest-framework/blame/master/docs/api-guide/schemas.md#L244

And try to get an HTTP request to an endpoint that uses this renderer:

```
http http://127.0.0.1:8000/v1/ Accept:application/openapi+json;version=2.0
```

## Expected behavior

Get a JSON with Swagger API Schema.

## Actual behavior

Get an HTTP 406:

```
HTTP/1.0 406 Not Acceptable
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Date: Tue, 19 Jul 2016 19:51:47 GMT
Server: WSGIServer/0.2 CPython/3.5.1+
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "detail": "Could not satisfy the request Accept header."
}
```

## Preliminar analisys

I've found that media_type doesn't match "version" parameter correctly in the following lines (even with `*/*; q=0.8` media type):

* https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/negotiation.py#L58
* https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/utils/mediatypes.py#L61

**Comment by tomchristie** [comment]
Thanks for raising this!

**Comment by tomchristie** [comment]
Note that this is actually a subtle command line issue...
This:

   http http://127.0.0.1:8000/v1/ Accept:application/openapi+json;version=2.0

In bash is actually treated as:

    http http://127.0.0.1:8000/v1/ Accept:application/openapi+json
    version=2.0

**Comment by tomchristie** [comment]
To simplify things I think we'll remove the optional "version=2.0" from the docs.

**Comment by osantana** [comment]
> To simplify things I think we'll remove the optional "version=2.0" from the docs.

I'm :+1: for this. I think that the version 2.0 is kind-of implicit in `application/openapi+json` content/mime-type.
