### ISSUE TITLE
raise_errors_on_nested_writes should allow BasicSerializer fields

### ISSUE THREAD

**Issue by pySilver** [tomchristie/django-rest-framework#4297]
While checking for nested writes at `raise_errors_on_nested_writes` DRF checks if a given field is an instance of `BaseSerializer` and this seems to be confusing. Why not checking is thats an instance of `ModelSerializer` instead?

Problem arises when you model have `text` (json/list) fields that you want to keep in a specific format using nested serializers validation.

For example:

```python
class SampleSerializer(ModelSerializer):
    # on a model lvl its just a text field
    filters = GenericFiltersSerializer(
        many=True,
        required=False,
        help_text="Search filters")

    # on a model lvl its just a text field
    items = WidgetItemSerializer(
        many=True,
        required=False,
        help_text="Widget items")

    class Meta:
        # ...
```

Both `GenericFiltersSerializer` and `WidgetItemSerializer` are simple serializers subclassed from `Serializer` *not* `ModelSerializer` so I cant see a reason why we should check for nested writes in that case? Why cant we simply assign representation results into parent serializer?

**Comment by xordoquy** [comment]
It checks against ´BaseSerializer' because ine doesn't always use ´ModelSerialzer' either for the top serializer or for the nested ones

**Comment by pySilver** [comment]
@xiaohanyu yeah, thats makes sense. Not 100% sure, but it looks like it might be an optional check (enabled by default). I've found myself coping original from ModelSerializer.update and just skipping that check.
