### ISSUE TITLE
Django Rest Framework TestCase checking response headers

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [tomchristie/django-rest-framework#4301]
I am trying to create automated tests and what I want is to check in my TestCase if there is a location header which it should be based on my code in views.py(Already tested it in Advanced REST Client). However, I can not to parse it in my tests.py

This is the code:
    from rest_framework import status
    from rest_framework.test import APITestCase
    url_1 = reverse('artists-list')

    class ArtistTest(APITestCase):
        def test_get(self):
            response = self.client.get(url_1)
            self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
            self.assertEqual(response.content, '')

        def test_post(self):
            _data = {"name": "50 Cent", "birth_date":"2005-02-13"}
            response = self.client.post(url_1, _data)
            data = json.loads(response.content)["data"]
            self.assertEqual(response.status_code, status.HTTP_201_CREATED)
            self.assertEqual(data, _data)
            self.assertEqual(Artist.objects.count(), 1)
            self.assertEqual(Artist.objects.get().name, '50 Cent')

Please be aware that:

    print response.headers # this throws an error
    print response # shows the header but I it cannot be parsed

**Comment by tomchristie** [comment]
The syntax is `response['Accept']`

**Comment by Dean-Christian-Armada** [comment]
Traceback (most recent call last):
 File "/Users/deanarmada/.virtualenvs/music_store/lib/python2.7/site-packages/django/http/response.py", line 152, in __getitem__
    return self._headers[header.lower()][1]
KeyError: 'accept'

This is the return when I tried printing response['Accept']

**Comment by tomchristie** [comment]
Sorry I should have used `Location` as in your example.

You can either do...

  `if 'Location' in response`  # Check existance

or...

    `response['Location']`  # Check value

**Comment by Dean-Christian-Armada** [comment]
It worked perfectly thanks!

**Comment by Olimhon31** [comment]
@tomchristie  where should we  write this condition ? in tests.py or views,py . Thank you!!!
