### ISSUE TITLE
SearchFilter raises error when using with related field.

### ISSUE THREAD

**Issue by grapo** [tomchristie/django-rest-framework#4302]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Use` SearchFilter` with serializer that has related field to `RelatedModel`
2. Set `search_fields = ('related_model__field', 'my_field')`

## Expected behavior
Correct filtering

## Actual behavior
Raises `"RelatedModel" has no field named 'my_field'`

I will submit pull request that fix this error. It is caused by overwriting `opts` in `SearchField.must_call_distinct`

**Comment by tomchristie** [comment]
Thanks for raising this! Resolved via #4298
Release will be incoming shortly.
