### ISSUE TITLE
The SAFE_METHODS constant is missing the 'TRACE' method

### ISSUE THREAD

**Issue by edmorley** [tomchristie/django-rest-framework#4320]
RFC 7231 [defines](https://tools.ietf.org/html/rfc7231#section-4.2.1) the safe HTTP methods as:
> GET, HEAD, OPTIONS, and TRACE

The `SAFE_METHODS` constant in the django-rest-framework permissions module [is currently](https://github.com/tomchristie/django-rest-framework/blob/6a7d34ec3452d4e8534f5c9bd238405548485a7a/rest_framework/permissions.py#L8):
```python
SAFE_METHODS = ('GET', 'HEAD', 'OPTIONS')
```

As a point of comparison, Django's CSRF middleware includes `TRACE` in its [list of safe methods](https://github.com/django/django/blob/cd2e4293cbf3416af6c478c5aaab711cae88892c/django/middleware/csrf.py#L185-L186).

Is there a reason it wasn't included, or should I open a PR to add it?

Many thanks :-)

**Comment by tomchristie** [comment]
Not really interested in supporting `TRACE`. Been some dispute over if it represents surface area for attacks, and haven't seen it used at an API application level in any valuable way. By all means use + support it at the server level if you've good reason to do so, but I don't see any need to support it in REST framework.
