### ISSUE TITLE
Possible exception during validation of IPAddressField

### ISSUE THREAD

**Issue by Stranger6667** [tomchristie/django-rest-framework#4335]
I faced with not expected behaviour of IPAddress field during validation certain types of input.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Create a serializer with IPAddressField
2. Pass not iterable object as input for the serializer. E.g. integer.

## Expected behavior

Validation error with usual text:
```['Enter a valid IPv4 or IPv6 address.']```

## Actual behavior
Exception:

```
rest_framework/fields.py:701: in run_validation
    return super(CharField, self).run_validation(data)
rest_framework/fields.py:487: in run_validation
    value = self.to_internal_value(data)
rest_framework/fields.py:807: in to_internal_value
    if data and ':' in data:
E   TypeError: argument of type 'int' is not iterable
```

**Comment by tomchristie** [comment]
Yup, looks valid, given your test case.
