### ISSUE TITLE
format_suffix_patterns does not handle formats with `.` in them

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#4341]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
* In a renderer, set the `format` to a string containing a `'.'`. For example: `'for.mat'`.
* Try to access the endpoint using `/.for.mat`.

## Expected behavior
* It selects the correct renderer.
* Note, if I use the the alternative `?format=for.mat` to specify the format, It works.

## Actual behavior
* There is no URL match due to the regex: `suffix_pattern = r'\.(?P<%s>[a-z0-9]+)/?$' % suffix_kwarg`.

I would suggest allowing for `'.'` in the regex. This comes up in extensions like `tar.gz`.

**Comment by tomchristie** [comment]
Not a use case I think we should support. Usage is for eg `foo.json`, I can't see `foo.some.thing` making sense. (And sure, it's inconsistent with the `?format=`, but they ya go)

**Comment by cancan101** [comment]
@tomchristie What about cases where the "underlying extension" has a ., for example `tar.gz`?

**Comment by tomchristie** [comment]
Then the dev will need to provide a custom `format_suffix_patterns` function.
Serving `.tar.gz` from an API isn't a use case I've seen in practice yet, so this doesn't particularly bother me, and handling `this.filename_has_a_dot.json` correctly seems more important.

**Comment by cancan101** [comment]
If the regex is modified to handle the `.`, would that have to cause problems with a . in the filename?

**Comment by tomchristie** [comment]
Presumably it'd `filename_has_a_dot.json` would be captured as the format portion, if you allow `.` as part of the regex.

**Comment by cancan101** [comment]
Given that the normal modifies are greedy, how would this come up that the format steals the filename? Not to mention if this were on a detail path, I assume that would be a constant any ways.
