### ISSUE TITLE
OPTIONS Broken if View Renderer does not Handle Dict

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#4343]
repost from: https://groups.google.com/forum/#!topic/django-rest-framework/A56MA9lfhT0

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] ? This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
* Add a renderer to a view that does not handle `dict`
* `OPTIONS` against the view.

## Expected behavior
* Anything other than 500. Ideally the standard DRF options formatted as JSON.

## Actual behavior
* 500

**Comment by tomchristie** [comment]
How would we differentiate between these two cases:

* The user has a different renderer and they want it to apply to all operations (Eg. YAML throughout, alphabetically-sorted JSON throughout, etc...)
* The user has a different renderer and wants it to apply to the standard operations, but not OPTIONS.

The resolution you've posted on that discussion thread is how I'd recommend handling your case.

**Comment by tomchristie** [comment]
I'd be happy to consider alternative suggestions, I can't seen any obviously good ways to *automatically* handle this case, so I'm happy for us to require it to be handled explicitly.
