### ISSUE TITLE
Browsable API markdown description broken if tabs are used in code indentation.

### ISSUE THREAD

**Issue by dvarrazzo** [tomchristie/django-rest-framework#4345]
get_view_description(html=True) with markdown installed is broken if the project uses tabs instead of spaces. Everything after the first line is rendered as a `<pre>` block.

The problem is in the [utils.formatting.dedent()](https://github.com/tomchristie/django-rest-framework/blob/4e5da16/rest_framework/utils/formatting.py#L25) function which only dedents spaces, not tabs.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
from rest_framework.utils.formatting import dedent
dedent("\tfirst string\n\n\tsecond string")
```

## Expected behavior

It returns:

```
u'first string\n\n\tsecond string'
```
## Actual behavior

It should return:

```
u'first string\n\nsecond string'
```

**Comment by tomchristie** [comment]
Thanks for raising this! Fix incoming.
