### ISSUE TITLE
Questionable Code in CursorPagination

### ISSUE THREAD

**Issue by cancan101** [tomchristie/django-rest-framework#4350]
this seems odd to bind the return of `get_page_size` to `self.page_size` rather than `page_size`:
```python
class CursorPagination(BasePagination):
    page_size = api_settings.PAGE_SIZE

    def paginate_queryset(self, queryset, request, view=None):
        self.page_size = self.get_page_size(request)
...
    def get_page_size(self, request):
        return self.page_size
```

It is inconsistent with how the other Pagination classes work. For example see `PageNumberPagination`:
```python
page_size = self.get_page_size(request)
```

This change was made in: https://github.com/tomchristie/django-rest-framework/commit/c879aaf39880a87c84ac7fd25e536087bdf35b5a.

I would say this makes understanding how these classes works a lot harder given the various mutable states.

**Comment by kevin-brown** [comment]
Might as well note that the commit directly references https://github.com/tomchristie/django-rest-framework/pull/3147.

**Comment by tomchristie** [comment]
This: https://github.com/tomchristie/django-rest-framework/pull/3147#commitcomment-12198529

**Comment by cancan101** [comment]
@tomchristie is there really no way around?:
>The statefulness on the pagination instances is necessary, but it is also a bit crufty.

**Comment by tomchristie** [comment]
Happy to consider suggestions. Otherwise not at the top of my queue right now.
