### ISSUE TITLE
Everything gets rendered as string in the response

### ISSUE THREAD

**Issue by MikiSoft** [tomchristie/django-rest-framework#4352]
https://github.com/tomchristie/django-rest-framework/pull/3908 - this fix ensures that every type of variable in Django model object is rendered as a string value in JSON response when going through serializer. I know that there's workaround for avoiding that but it's rather "non-robust" (because it requires overriding `init`), and I just think it's strange to enforce string for all fields without any specific reason. Therefore, can that function be made in more conventional way, e.g. to skip conversion of numbers to strings?

**Comment by xordoquy** [comment]
Closing this it as it isn't actionnable and too vague. Note that this only applies to exceptions.
Will consider a PR with test case though.

**Comment by tomchristie** [comment]
We could consider this, but I can't understand the issue from this description.

>  every type of variable in the exception response is rendered as a string value in JSON

Can you give an example? When wouldn't you want a string value in an error detail?

**Comment by MikiSoft** [comment]
@tomchristie: For example, when returning an error number and then using the comparison operator `==`.

**Comment by tomchristie** [comment]
Implement a custom exception handler if you want to be able to return integers as error messages.
Personally I can't see either a good use case for it, or a way of doing that, that'd be consistent with the kind error messages we return.
