### ISSUE TITLE
"schemas.py" lacks support of "HEAD"

### ISSUE THREAD

**Issue by fengsi** [tomchristie/django-rest-framework#4356]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create an APIView with `HEAD` allowed:
```python
class HeadAPIView(APIView):
    permission_classes = (AllowAny,)
    allowed_methods = ('POST', 'OPTIONS', 'HEAD')
```
And then use `django-rest-swagger` to browse API docs.

## Expected behavior
Just work.

## Actual behavior
```
["KeyError: 'head'", '  File "django/core/handlers/base.py", line 149, in get_response', '  File "django/core/handlers/base.py", line 147, in get_response', '  File "django/views/decorators/csrf.py", line 58, in wrapped_view', '  File "django/views/generic/base.py", line 68, in view', '  File "rest_framework/views.py", line 466, in dispatch', '  File "rest_framework/views.py", line 463, in dispatch', '  File "rest_framework/decorators.py", line 52, in handler', '  File "project/urls.py", line 32, in schema_view', '  File "rest_framework/schemas.py", line 78, in __init__', '  File "rest_framework/schemas.py", line 132, in get_api_endpoints', '  File "rest_framework/schemas.py", line 124, in get_api_endpoints', '  File "rest_framework/schemas.py", line 185, in get_key']
```
This is because `schemas.py` does not handle unexpected key (`method`) that is not defined in mapping dict (only `GET`, `POST`, `PUT`, `PATCH` and `DELETE` are there):
```python
default_mapping = {
    'get': 'read',
    'post': 'create',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy',
}
```
```python
actions = getattr(callback, 'actions', self.default_mapping)
action = actions[method.lower()]
```

Generally speaking, `schemas.py` cannot deal with unexpected method such as `HEAD`, and invalid method such as `INVALID`.

**Comment by tomchristie** [comment]
I don't believe we should support "HEAD" in schemas for similar reasons that we don't support "OPTIONS" - it doesn't actually represent an action.

You should omit "HEAD" and "OPTIONS" from `allowed_methods`, as they're handled by default.

I *might* accept a different ticket along the lines that we should error if `"HEAD" or "OPTIONS" are passed to `allowed_methods`

**Comment by kevin-brown** [comment]
> You should omit "HEAD" and "OPTIONS" from allowed_methods, as they're handled by default.

If I remember correctly, both `HEAD` and `OPTIONS` are in there by default.

If anything, `HEAD` should probably be filtered out of [`get_allowed_methods`](https://github.com/tomchristie/django-rest-framework/blob/54096dc22f255140f148906e85da5e4be0048f10/rest_framework/schemas.py#L161-L171) by default, just like `OPTIONS` is.

**Comment by tomchristie** [comment]
> HEAD should probably be filtered out

That's a good point. This line...

https://github.com/tomchristie/django-rest-framework/blob/54096dc22f255140f148906e85da5e4be0048f10/rest_framework/schemas.py#L170

Shold probably be tweaked to include `HEAD` too.

**Comment by tomchristie** [comment]
Okay, thanks for raising this @fengsi. Point still stands that you should remove `HEAD`/`OPTIONS` from that list, but #4357 gives us more graceful behavior.

**Comment by fengsi** [comment]
@kevin-brown good point!
@tomchristie I upgraded DRF to 3.4.x and also `django-rest-swagger` to 2.0.x, and then API docs stopped working, thus I checked the new `schemas.py`.  The `HEAD` is in `django-rest-auth` (https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/registration/views.py#L71) and I had to subclass to remove it.  Thanks for the upstream fix!
