### ISSUE TITLE
POST forms and buttons disabled after upgrade from 3.3.3 to 3.4.4

### ISSUE THREAD

**Issue by farice** [tomchristie/django-rest-framework#4364]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Upgrade to 3.4.3 from 3.3.3. The app I tested this with is essentially identical to the tutorial.

I ran makemigrations, migrate, and runserver to ensure django was not aware of any potential issues.  

## Expected behavior

Standard features you'd expect from the tutorial. 

## Actual behavior

No POST forms are loading (to post snippets in the context of the tutorial). In addition, most interaction is not functional. I cannot logout or press the GET button. I am obviously not particularly interested in getting the tutorial to work. I'm concerned that when I upgrade my own app it will have the same problems in terms of the browsable api being essentially non-functional. However, I can't seem to find anyone else that is experiencing similar issues.

**Comment by farice** [comment]
An upgrade from Django 1.9.7 to 1.10 solved my problem. It appears it must've been some sort of compatibility issue. If others experience the same, that is my recommended solution.

**Comment by tomchristie** [comment]
Thanks for the update!
