### ISSUE TITLE
Support Django 1.10

### ISSUE THREAD

**Issue by mathiasbc** [tomchristie/django-rest-framework#4368]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by kevin-brown** [comment]
Django 1.10 should already be supported in the latest version: https://github.com/tomchristie/django-rest-framework/pull/4158

If you're running into a specific issue on Django 1.10, then we're going to need to steps to reproduce, expected behaviour, and actual behaviour.

**Comment by mathiasbc** [comment]
Thanks I will install from github.
