### ISSUE TITLE
Type annotations for CoreAPI

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#4384]

**Comment by crearc** [comment]
Is it possible to get the Core API type annotations in earlier than 3.5? Feels necessary to describing APIs to have types. Thanks though!

**Comment by tomchristie** [comment]
Nope. Tho 3.5 is currently planned for the end of next month, so you probably won't have all that long to wait. What's driving the interest specifically? Swagger UI, or some other tooling that'd display them once they're available, or just a general desire to see them in there?

**Comment by crearc** [comment]
I use django-rest-swagger, recently upgraded to v2 of that. Might also be switching to use the Redoc UI. In both of them the types all show up as strings which is a bit confusing for API users.

**Comment by tomchristie** [comment]
Gotcha. We'll see. Needs a bit of design thought around eg composite types (may not follow swagger's lead exactly - json schema is rather over-complex)

**Comment by tomchristie** [comment]
The issue here was less about types, and more about us failing to set the correct encoding. We're now using `application/json` where applicable which largely resolves the previous issues around integration with Swagger UI.

**Comment by tomchristie** [comment]
Now resolved in the 3.5 branch.
There will likely be more coming at a future date (eg. input types / presenting choices /etc.) but the existing work now covers the basics.
