### ISSUE TITLE
Blank parameters are not passed into `next` field in results

### ISSUE THREAD

**Issue by MattHardcastle** [tomchristie/django-rest-framework#4393]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Visit a paginated API using blank URL parameter. For example: http://example.com/api/foo/?bar

## Expected behavior

The next link in the results meta data should preserve the blank parameter. Example:

```
{
    "next": "http://example.com/api/foo/?bar&page=2",
   ...
}
```

## Actual behavior

The next link in the results meta data swallows the blank parameter. Example:

```
{
    "next": "http://example.com/api/foo/?page=2",
   ...
}
```

I have an open [pull request](https://github.com/tomchristie/django-rest-framework/pull/4392) with a tests for this case.

**Comment by tomchristie** [comment]
Closed via #4260.
