### ISSUE TITLE
Getting '... must call is_valid() ...' Serializer AssertionError when 'data' keyword is NOT being used

### ISSUE THREAD

**Issue by lorenmh** [tomchristie/django-rest-framework#4397]
I have a subclass of Serializer with a custom \__init\__ method that has an additional parameter. Somehow this is causing DRF to output the following assertion error (when I am NOT using the data kwarg at all):

AssertionError: When a serializer is passed a `data` keyword argument you must call `.is_valid()` before attempting to access the serialized `.data` representation.
You should either call `.is_valid()` first, or access `.initial_data` instead.

I have a simple 'error.py' file here which demonstrates the issue:

    from rest_framework.serializers import Serializer, CharField

    class Foo(Serializer):
        foo = CharField()
        def __init__(self, some_param, *args, **kwargs):
            self.some_param = some_param
            super(Foo, self).__init__(*args, **kwargs)

    bar = [{'foo':1}, {'foo':2}, {'foo':3}]

    serializer = Foo('some_param', bar, many=True)
    print serializer.data

Also added this repo where you can clone it and run it (if you trust running a shell script from the internet ;) ):
https://github.com/lorenmh/drf-error

**Comment by candlejack297** [comment]
I, too, am having this issue, although using .initial_data seems to serve as a workaround.

I've found why it happens, but I'm not exactly sure what the problem is. In ListSerializer init,
```python
def __init__(self, *args, **kwargs):
        self.child = kwargs.pop('child', copy.deepcopy(self.child))
        self.allow_empty = kwargs.pop('allow_empty', True)
        assert self.child is not None, '`child` is a required argument.'
        assert not inspect.isclass(self.child), '`child` has not been instantiated.'
        super(ListSerializer, self).__init__(*args, **kwargs)
        self.child.bind(field_name='', parent=self)
```
The super call to BaseSerializer is being called with the original arguments. 
In BaseSerializer
```python
def __init__(self, instance=None, data=empty, **kwargs):
        if data is not empty:
                self.initial_data = data
```
The extra positional arg (in the example 'some_param' is taking the place of instance and the next arg  is being pushed to data. I'm not certain what exactly is supposed to happen here, though. Data isn't empty, so initial data is set.
The first line in the data prop is
`
if hasattr(self, 'initial_data') and not hasattr(self, '_validated_data'):
`
which immediately triggers an assert error.

**Comment by xordoquy** [comment]
Though it looks like a kwargs argument, instance is really used as a positional one here and there (https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L68 for ex).

What you're basically doing by providing a positional argument, the instance is shifted and may lead to issues.

I think we should make sure that both in the code and documentation we use keyword argument for instance.

**Comment by candlejack297** [comment]
Would it make sense to just change the BaseSerializer init signature to:
```python
def __init__(self, *args, instance=None, data=empty, **kwargs):
```

**Comment by xordoquy** [comment]
That's the documentation part of my previous comment

**Comment by tomchristie** [comment]
Perhaps we'll reconsider this at a future date, but the resolution for now is simply that I'd strongly advise for any extra arguments on *any* kind of subclass to be added as keyword arguments.

You're always going to be causing trouble for yourself if you redefine the positional arguments.
