### ISSUE TITLE
Feature Request: Disable router format suffix completely via DefaultRouter or SimpleRouter

### ISSUE THREAD

**Issue by erichonkanen** [tomchristie/django-rest-framework#4399]
Hello,

I have been digging around trying to figure out how to solve my issue where I have a username which is a PK and contains a dot ( . ) and it's breaking the api as it is breaking the username (e.g. mr.hello) into two parts, identifying the 2nd part after the dot as a format suffix so that'd turn into pk=mr, format=hello.

e.g. GET /api/users/mr.hello -> {'detail': 'Not Found'}
(http://i.imgur.com/U9fBvUV.png)

From what I can tell via looking through the routers.py and urlpatterns.py, there is no simple way to disable format suffix altogether which would be ideal for a case where I want to support lookups that contain a dot ( . )

I am proposing that a way to disable format suffix be added or some other way to handle this. Any thoughts?

Thanks

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by xordoquy** [comment]
Do you have a test case that shows this is the issue and not just my initial guess ?

**Comment by erichonkanen** [comment]
@xordoquy what was your initial guess?

**Comment by xordoquy** [comment]
Aren't you holler on irc ?

**Comment by erichonkanen** [comment]
@xordoquy yes are you linova?

**Comment by erichonkanen** [comment]
@xordoquy yes are you linova?

I did take your suggestion and look into the regex with the DefaultRouter (SimpleRouter) but that's where I was wondering if there is a way to just disable the format suffix instead of having to create my own custom router which adds more complexity

**Comment by erichonkanen** [comment]
I also thought maybe I could set this to `null` but that didn't work either https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/routers.py#L230

**Comment by erichonkanen** [comment]
fyi this does not work http://stackoverflow.com/a/27966110

**Comment by erichonkanen** [comment]
Discovered this https://github.com/tomchristie/django-rest-framework/pull/1333/files and I think it works now by doing `lookup_value_regex = '[^/]+'` phew

**Comment by derek-adair** [comment]
It would be nice to somehow set this with allowed=False in the router.  Not sure how that would be done or if it's even desirable for most, it seems pretty hacky to have to pass this specific incantation to turn off suffixes.

**Comment by derek-adair** [comment]
I was considering flat out abandoning the DRF router and/or viewsets until I found this. D:
