### ISSUE TITLE
Custom throttle headers

### ISSUE THREAD

**Issue by nick-allen** [tomchristie/django-rest-framework#4402]
Currently, the only option for providing clients context about throttle limits via the API requires them to reach their throttle limit, and inspect the X-Throttle-Wait-Seconds header if it was set when raising the Throttled exception with a wait argument.

Only option that seems possible right now would require a middleware class to inspect for a 429 response and add the headers, but that moves the logic outside the scope of the Throttle classes, and would lose some possibly useful context info about why it was throttled. 

One possible solution would be to accept an optional headers argument in the Throttled exception, allowing any custom response headers to be explicitly set in the Throttle classes. Better still would be allowing Throttle classes to operate like middleware, and optionally always provide X-RateLimit headers similar to the Github or Twitter APIs.

**Comment by tomchristie** [comment]
Okay - interesting input.
I'll milestone this for 3.5 for now, as it'll need some thinking about.

**Comment by tomchristie** [comment]
As reasonable as this feature would be, I don't see any obvious ways for us to achieve it right now, and I don't think it's something we especially need to have on our roadmap.

For now I think that any improvements in this area would likely start as a third party packages.

**Comment by sfdye** [comment]
+1 
Is there any third-party pacakge for this purpose now in 2018？

**Comment by rpkilby** [comment]
@sfdye If there is, it hasn't been added to the list of 3rd-party packages. 

@tomchristie It sounds like this would be a welcome addition to the core framework, but we're not focused on implementing this ourselves.

**Comment by sfdye** [comment]
Why is this closed please?

**Comment by rpkilby** [comment]
@sfdye - this issue is closed because there's nothing actionable for the maintainers at this point. If someone wants to contribute this feature, we'd be happy to look at and review that PR.

**Comment by sfdye** [comment]
@rpkilby
Sure, thanks for the feedback.
