### ISSUE TITLE
Docstring of Field.get_default is misleading

### ISSUE THREAD

**Issue by tyrion** [tomchristie/django-rest-framework#4404]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Issue

The docstring of `Field.get_default` says:

> If a default has not been set for this field then this will simply
        return `empty`, indicating that no value should be set in the
        validated data for this field.

But if default has not been set the method raises `SkipField` instead.
```python
if self.default is empty or getattr(self.root, 'partial', False):
    # No default, or this is a partial update.
    raise SkipField()
```
I suggest either to change the documentation to reflect the actual behaviour or change the code to reflect the doc.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L434

**Comment by tomchristie** [comment]
Tweaked the title and description slightly to make it clear it's the method docstring that's incorrect, rather than the documentation.

And yup, good catch - thanks!
