### ISSUE TITLE
Tutorial Step Four Last Example fails with 'HTTP/1.0 400 Bad Request'

### ISSUE THREAD

**Issue by ilovetogetspamed** [tomchristie/django-rest-framework#4411]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

Django==1.10
djangorestframework==3.4.4
httpie==0.9.6
Pygments==2.1.3
requests==2.11.0

Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

Darwin localhost.example.com 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

## Steps to reproduce

I followed all of tutorial part four and everything worked as described in the text except for the very last example:

`$ http -a tom:password123 POST http://127.0.0.1:8000/snippets/ code="print 789"`

**NOTE**: I got the expected behavior by adding "owner='1'" to the command line above (see below).

`$ http -a tom:password123 POST http://127.0.0.1:8000/snippets/ code="print 789" owner='1'`

of course this is contradictory to what I was reading in the tutorial.  I thought the POST would auto-magically add the owner id of the authenticated user.  In this case tom.  Which in my DB actually has the id of three, not one.  which is what I passed on the command line.

So it also looks like no validation was done on the POST as far as that goes too.  This is just an observation, not a criticism BTW.

My code is attached.  I'd really like to know if I missed something, because I checked twice.

Thank you
Chris

[tutorial4.tar.gz](https://github.com/tomchristie/django-rest-framework/files/421300/tutorial4.tar.gz)

## Expected behavior

```
HTTP/1.0 201 Created
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Date: Tue, 16 Aug 2016 20:44:48 GMT
Server: WSGIServer/0.1 Python/2.7.10
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
{
    "code": "print 789", 
    "id": 4, 
    "language": "python", 
    "linenos": false, 
    "owner": 3, 
    "style": "friendly", 
    "title": ""
}
```

## Actual behavior

```
HTTP/1.0 400 Bad Request
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Date: Tue, 16 Aug 2016 20:43:47 GMT
Server: WSGIServer/0.1 Python/2.7.10
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
{
    "owner": [
        "This field is required."
    ]
}
```

**Comment by xordoquy** [comment]
I don't have the time to get through your code to catch your issue.
I've been playing the tutorial several times and it worked fine.
You want to make sure you didn't skipped that line from the tutorial:

    owner = serializers.ReadOnlyField(source='owner.username')


Which means owner will never be required again. Also make sure you don't define owner twice.

**Comment by ilovetogetspamed** [comment]
OK Thanks.

**Comment by rainerbird** [comment]
Also followed this in the tutorial and got the same result -"this field is required". I can confirm I have this line in my serializer:

`owner = serializers.ReadOnlyField(source='owner.username')`
