### ISSUE TITLE
ObtainAuthToken view doesn't show specific message when the user is disbled

### ISSUE THREAD

**Issue by sh4r3m4n** [tomchristie/django-rest-framework#4413]
Hi, I am using that view for my project and noticed that if I specify the username and password of an inactive user (is_active=False) it fails, but the message is "Unable to log in with provided credentials.". Looking at the code at https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/authtoken/serializers.py it seems that the message should be "User account is disabled" but it isn't.

This problem happens becuase `django.contrib.auth.authenticate` returns None for an inactive user.
I think that getting the model and doing a `check_password` call instead of calling authenticate should fix it, but I'm not sure if this will break the compatibility with custom auth backends so I wanted to confirm it before sending a pull request.

**Comment by tomchristie** [comment]
Confirmed that Django's AuthenticationForm [differentiates between the two cases](https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L213).
Agree that we should follow their lead here.
Thanks for raising this!

**Comment by kevin-brown** [comment]
> This problem happens becuase django.contrib.auth.authenticate returns None for an inactive user.

By default, it shouldn't. Django's `AuthenticationForm` is relying on it returning a user, and it later does the check against `is_active` like we do. Our logic actually appears to closely (if not exactly) match the logic that Django is using for authenticating users.

For some reason, in your case it's not returning the user based on the username and password that you are providing. This is usually a sign that you have an authentication backend which is doing the `is_active` check ahead of time, or you are attempting to authenticate with the wrong credentials.

**Comment by tomchristie** [comment]
Yup, thanks for pointing that out @kevin-brown.

We *do* have an inactive user message. If the `authenticate` method is returning `None` that'll either be because the credentials really *are* incorrect, or because the auth backend you're using is returning `None` for some other reason.
