### ISSUE TITLE
PKOnlyObject doesn't have __str__/__unicode__ methods

### ISSUE THREAD

**Issue by thenewguy** [tomchristie/django-rest-framework#4419]
## Checklist

- [ x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.
- [x ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Select admin renderer. View a model that has a ForeignKey like `origin = models.ForeignKey(Address, related_name='+')`  See gibberish output like `<rest_framework.relations.PKOnlyObject object at 0x7f943b762950>`

## Expected behavior

my-pretty-pk-uuid-string

## Actual behavior

`<rest_framework.relations.PKOnlyObject object at 0x7f9a6903d510>`

Should be fairly simple to add __str__/__unicode__ methods so the link text is the pk value instead of something like `<rest_framework.relations.PKOnlyObject object at 0x7f9a6903d510>.`

This simple monkey patch fixes the issue so I assume adding the method won't cause any problems
```
from rest_framework.relations import PKOnlyObject

PKOnlyObject.__str__ = lambda obj: str(obj.pk)

```

**Comment by xordoquy** [comment]
Could you add a screenshot so we get the big picture ?

**Comment by thenewguy** [comment]
```
PKOnlyObject.__str__ = lambda obj: str(obj.pk)
PKOnlyObject.__unicode__ = lambda obj: text_type(obj.pk)
```

no monkeypatch:

<img width="959" alt="drf-issue-4419-no-monkeypatch" src="https://cloud.githubusercontent.com/assets/77731/17809717/989067d6-65e6-11e6-91b7-0b56a2c38db6.png">


has monkeypatch:

<img width="960" alt="drf-issue-4419-has-monkeypatch" src="https://cloud.githubusercontent.com/assets/77731/17809731/a4bcd74c-65e6-11e6-803c-03b5f63b976e.png">
