### ISSUE TITLE
SchemaGenerator add Serializer HiddenFields to parameters

### ISSUE THREAD

**Issue by Skorpyon** [tomchristie/django-rest-framework#4425]
When SchemaGenerator return `.get_schema()` data, HiddenFields included to views parameters:
### Serializer
```python
class CommonDriverVehiclePOSTSerializer(serializers.ModelSerializer):
    class Meta:
        model = vehicle_mdl.Vehicle
        exclude = ['deleted', ]
        read_only_fields = ['full_name', 'company']
        
    driver = serializers.HiddenField(default=CurrentDriverProfileDefault())
```
### Generator response
```
post: {
    description: "",
    parameters: [
        {type: "string", name: "driver", required: false, description: "", in: "formData"},
    ],
}
```

**Comment by tomchristie** [comment]
Thanks for the report!

**Comment by Skorpyon** [comment]
Giant thanks for you. DRF is amazing.
Actually, what you think about `channels` project? I try implement it in my last project now. Is it good idea to include support of it to DRF? It may be a first in the world REST framework via Websockets.

**Comment by tomchristie** [comment]
Work on docs and integration for using channels and REST framework together will be coming, yup.
