### ISSUE TITLE
Extend @api_view decorator to support custom kwargs which will be set to returned APIView instance

### ISSUE THREAD

**Issue by rmuslimov** [tomchristie/django-rest-framework#4427]
I found existing implementation to strict about attributes that @api_view decorator supports. My API implementation supports protobuf as input, and I found a beautiful solution from my point of view, use api_view as:

```
@api_view(['POST'], input_protobuf_cls=Protocls)
def some_view(request):
```

Please see PR attached, hope it for others as well. Thanks,

**Comment by tomchristie** [comment]
Not overly convinced by this use case. I'd suggest keeping your custom implementation of `api_view` in your own codebase for now. If we have similar requests, then perhaps we'll reconsider at some point in the future.
