### ISSUE TITLE
SchemaGenerator is not smart

### ISSUE THREAD

**Issue by nypisces** [tomchristie/django-rest-framework#4431]
If exists two api
/api/v1/users/{pk}/
/api/v1/users/{pk}/password/

It should all be included in users
but now split as two group: users and password

**Comment by lwm** [comment]
@nypisces 

You're missing context that could help track this problem down. Can you write a failing testcase for this and submit it as a PR?

For reporting, please check [the issues docs](http://www.django-rest-framework.org/topics/contributing/#issues).

**Comment by tomchristie** [comment]
Resolved via #4527. Now in the `version-3-5` branch.
