### ISSUE TITLE
Inconsistent behavior when authenticating users

### ISSUE THREAD

**Issue by jegesh** [tomchristie/django-rest-framework#4432]
## Steps to reproduce
Use `authtoken.views.ObtainAuthToken()` with a non-existent username.

## Expected behavior
I would expect to get a response (say, with code 404, or 400) with or without a message indicating what the problemis.

## Actual behavior
An exception is thrown.

While I realize this behavior is by design, it seems a bit wacky if we take a step back and think about it from a typical user perspective.  Let's say I have a login page on my website.  When a user forgets his username, or alternatively, if someone is trying to guess a username, I need to give some kind of intelligible response either way.  So in my view I'm going to have to catch the exception and return some other response in any case.  Why make people go through that extra step, instead of returning by default a response that makes sense and will be useful to some people?  And while we're at it, the 400 response code when the authentication is unsuccessful doesn't make a great deal of sense, either.  Why not 401 -- UNAUTHORIZED!?  In my mind, 401 is the perfect fit

**Comment by tomchristie** [comment]
> An exception is thrown.

I cannot replicate this. `authenticate(username=..., password=...)` with an incorrect username does not raise an exception, but returns `None`, that we return a validation error message with.

It's possible that if you are using a custom authentication backend, that the backend is misbehaving and incorrectly raising an exception rather than returning none, as it should do.

401 is not appropriate status code for the response because the HTTP spec specifies this, which is not relevant in the ObtainAuthToken case...

> "The server generating a 401 response MUST send a WWW-Authenticate header field1 containing at least one challenge applicable to the target resource."

In any case - when obtaining a token, the token view *itself* is unauthenticated.

**Comment by tomchristie** [comment]
Note for later reference. Confirming this behavior to myself in the shell, was:

    >>> from django.contrib.auth import authenticate
    >>> authenticate(username='sdfsd', password='ds')
    >>>

**Comment by jegesh** [comment]
I'm sorry if my complaint was not clear enough.  What I meant is that when calling `ObtainAuthToken.post()` the default behavior is to raise an exception rather than just return a different `Response` object.

**Comment by tomchristie** [comment]
A ValidationError exception is raised, which is handled by our exception handler, returning a 400 error message to the end user. As you say, that's by design, and the behavior is all as expected.

If you want an obtain token view with differing behavior then I'd suggest writing a completely custom view. There'll be less indirection that way.

**Comment by jegesh** [comment]
Again, it seems we're not talking about the same thing.  This is what I see:

```
class AuthTokenSerializer(serializers.Serializer):
    username = serializers.CharField(label=_("Username"))
    password = serializers.CharField(label=_("Password"), style={'input_type': 'password'})

    def validate(self, attrs):
        username = attrs.get('username')
        password = attrs.get('password')

        if username and password:
            user = authenticate(username=username, password=password)

            if user:
                if not user.is_active:
                    msg = _('User account is disabled.')
                    raise serializers.ValidationError(msg)
            else:
                msg = _('Unable to log in with provided credentials.')
                raise serializers.ValidationError(msg)
        else:
            msg = _('Must include "username" and "password".')
            raise serializers.ValidationError(msg)

        attrs['user'] = user
        return attrs
```

Why raise an exception when no username is present?  Why not return a 400 error in that situation, as well?

**Comment by jegesh** [comment]
For some reason, I keep getting exceptions instead of the 400 error that you say should be returned.  Some debugging led me to the clear culprit the `raise_exception=True` parameter that's passed to the `is_valid` method.  This is my code:
```
users = UserProfile.objects.filter(user__email=serialized_user.validated_data['username'])
            if users.count() == 1:
                user = users[0]
                if not user.mail_validated:
                    return Response(data={"error": "Email has not been validated"}, status=status.HTTP_400_BAD_REQUEST)
                if not user.phone_validated:
                    return Response(data={"error": "Phone number has not been validated"}, status=status.HTTP_400_BAD_REQUEST)
            authtoken_view = views.ObtainAuthToken()
            return authtoken_view.post(request)
```
The last line raises an exception every time the authentication fails, no matter what the reason.

**Comment by tomchristie** [comment]
The view *itself* raises an exception, yes. When the view is called normally, REST framework's exception handler catches and deals with it.

It looks like you're doing something slightly unusually, like calling into the post() method from a different view. In that case, yes the method will raise a ValidationError.

Either 1. Catch the exception. 2. Make sure you're calling the method inside an APIView will will handle the exception, or 3. Don't do that, and instead write the auth token logic explicitly in your view.

**Comment by jegesh** [comment]
I indeed had been calling the `post()` method from within a custom view. After your previous comment, I changed my view to extend the `ObtainAuthToken` class, but the exception is still being raised.  This is my class:

```
class BugeezAuthView(views.ObtainAuthToken):
    """
    extends django rest's authorization view in order to properly get error responses
    """

    def post(self, request, *args, **kwargs):
        """
       registration api
       :param request:
       :return:
       """

        serialized_user = LoginValidationSerializer(data=request.data)
        if serialized_user.is_valid():
            try:
                users = UserProfile.objects.filter(user__email=serialized_user.validated_data['username'])
                if users.count() == 1:
                    user = users[0]
                    if not user.mail_validated:
                        return Response(data={"error": "Email has not been validated"}, status=status.HTTP_400_BAD_REQUEST)
                    if not user.phone_validated:
                        return Response(data={"error": "Phone number has not been validated"}, status=status.HTTP_400_BAD_REQUEST)
                return super(BugeezAuthView, self).post(request, *args, **kwargs)
            except Exception, ex:
                return Response(data={"error": "Unable to authenticate user. Please try again later."}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        else:
            return Response(data=serialized_user._errors, status=status.HTTP_400_BAD_REQUEST)
```

If you see anything unusual here, please let me know.
