### ISSUE TITLE
Missing , in rest_framework/base.html window.drf script

### ISSUE THREAD

**Issue by ercwyne** [tomchristie/django-rest-framework#4435]
The change to the scripts block is missing a comma (,) between the two elements.

## Steps to reproduce
see line 266 rest_framework/templates/rest_framework/base.html

## Expected behavior
Web API PUT or DELETE to include CSRF token in the request

## Actual behavior
No token passed.
Returns HTTP403 Forbidden

**Comment by tomchristie** [comment]
Thanks for raising this. Now resolved in https://github.com/tomchristie/django-rest-framework/commit/97806f9724fc315518c881a439a5aa82a46c0e34
