### ISSUE TITLE
Routers in versions 3.4.X

### ISSUE THREAD

**Issue by jocecu** [tomchristie/django-rest-framework#4438]
Since I upgraded from version 3.3.3 to version 3.4 I'm have problems with routers

File "/urls.py", line 23, in <module>
    urlpatterns = router.urls
  File "~/Library/Python/2.7/lib/python/site-packages/rest_framework/routers.py", line 81, in urls
    self._urls = self.get_urls()
  File "~/Library/Python/2.7/lib/python/site-packages/rest_framework/routers.py", line 358, in get_urls
    view = self.get_api_root_view(api_urls=urls)
TypeError: get_api_root_view() got an unexpected keyword argument 'api_urls'

**Comment by jpadilla** [comment]
Signature seems to have been slightly changed in https://github.com/tomchristie/django-rest-framework/commit/061e0ed0841274da930f61838c60af1324ea04bc

**Comment by tomchristie** [comment]
It's true that the internal signature has changed there, but I can't see how it can cause any problems. Perhaps you've overridden the `get_api_root_view` method in your codebase? If so then, yes, it'll need to accept the new argument. However it isn't publically documented API, and isn't subject to our deprecation policy.
