### ISSUE TITLE
unsupported operand type(s) when using IsAuthenticated in Python 2.7 and 3.4.

### ISSUE THREAD

**Issue by cnobile2012** [tomchristie/django-rest-framework#4439]
Whenever I use IsAuthenticated I get an error.

In Python 2.7 "unsupported operand type(s) for |: 'bool' and 'instance'"
In Python 3.4 "unsupported operand type(s) for |: 'bool' and 'CallableBool'"

I tracked this down to:

    def is_authenticated(user):
        if django.VERSION < (1, 10):
            return user.is_authenticated()
        return user.is_authenticated

    In [5]: django.VERSION
    Out[5]: (1, 10, 0, u'final', 1)

    In [6]: django.VERSION < (1, 10)
    Out[6]: False

    In [7]: django.VERSION == (1, 10)
    Out[7]: False

    In [8]: django.VERSION > (1, 10)
    Out[8]: True

I'm not sure testing to ``(1, 10)`` is valid.

In any case ``IsAuthenticated`` seems to be broken.

**Comment by tomchristie** [comment]
Use the boolean `or` operator, rather than the bitwise `|` operator.

Raised this with the Django project to see if we might make the behavior here a little more seamless... https://code.djangoproject.com/ticket/27154
