### ISSUE TITLE
APIRequestFactory returns WSGIRequest objects

### ISSUE THREAD

**Issue by skolsuper** [tomchristie/django-rest-framework#4440]
I am trying to test a custom permissions class using APIRequestFactory to fabricate a request.  The custom permissions object checks the request body for an OTP using `request.data`, a convenience property added by DRF Request objects.  However this fails because APIRequestFactory directly returns the WSGIRequest object returned by Django's RequestFactory.

## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
    api_rf = APIRequestFactory()
    request = api_rf.post('/some/url', {})
    request.data.get('foo')
```

## Expected behavior

`None`

## Actual behavior

`AttributeError: 'WSGIRequest' object has no attribute 'data'`

**Comment by lwm** [comment]
This is a duplicate of #3608 (closed).

You can probably achieve what you want by following https://github.com/tomchristie/django-rest-framework/issues/3608#issuecomment-154427523.

**Comment by skolsuper** [comment]
So it is.

**Comment by tomchristie** [comment]
Aside: I have warmed to the idea of ensuring that this returns a fully fledged `Request` instance, and having views be able to handle either, so this might come up in the future.

**Comment by technodivesh** [comment]
try 
request.DATA   
(caps)

**Comment by mohit23x** [comment]
you can user this above your function defination in view.py

@api_view(["POST", "GET"])
def yourFunction():
    pass

**Comment by rpkilby** [comment]
https://github.com/encode/django-rest-framework/blob/1dc81acb4d351ef954291391b9151fa9c524ea43/rest_framework/request.py#L416-L421

**Comment by mesajidiqbal** [comment]
To resolve this issue, you need to wrap the `APIRequestFactory` request with `rest_framework.request.Request`. This will provide the necessary context and attributes expected in DRF views, including the `data` attribute.

Here's an example of how to correctly use `APIRequestFactory` for both GET and POST requests:

```python
# Imports
from rest_framework.test import APIRequestFactory
from rest_framework.request import Request
from rest_framework.parsers import JSONParser
import json

# Initialize the APIRequestFactory
request_factory = APIRequestFactory()

# Query Param or Data
data = {"key": "value"}

# Example for a GET request
request = request_factory.get('/api/url/', data)
request = Request(request)

# Example for a POST request
json_data = json.dumps(data)  # data must be converted to string for POST requests
request = request_factory.post('/api/url/', data=json_data, content_type='application/json')
request = Request(request, parsers=[JSONParser()])
