### ISSUE TITLE
Offline Documentation as PDF

### ISSUE THREAD

**Issue by GammaSQ** [tomchristie/django-rest-framework#4445]
Would it be possible to generate the documentation as PDF and make it available via download?
I like to have "pretty" offline-documentations as reference during travel. The readthedocs-PDF isn't up to date:
https://media.readthedocs.org/pdf/django-rest-framework/latest/django-rest-framework.pdf

**Comment by aliva** [comment]
while it's nice to have updated docs, you can generate your own pdf file using [mkdocs](http://www.mkdocs.org/)

just download DRF and install `mkdocs`

    mkdocs serve

or build your own pdf file using [this](https://github.com/jgrassler/mkdocs-pandoc)

**Comment by tomchristie** [comment]
Thanks @aliva.

**Comment by ftamy9** [comment]
This is an empty document. There is no technical description.
