### ISSUE TITLE
not filtering on view queryset nested relations in place of FilterSet model

### ISSUE THREAD

**Issue by mbande** [tomchristie/django-rest-framework#4446]
I'm prefetching some related filed based on some value in query params:
```py
def get_queryset(self):
    queryset = self.queryset
    foo = self.request.query_params.get('foo', None)
    if foo:
        queryset = queryset.prefetch_related(Prefetch('resources', queryset=Resource.objects.filter(bar=foo)))
    else:
        queryset = queryset.prefetch_related('resources')
    return queryset
```

also i defined a FilterSet for other query params that uses prefetched relation(i.e. ```resources```),
as DRF docs says: 
```Note that you can use both an overridden .get_queryset() and generic filtering together, and everything will work as expected. ```, i expect the FilterSet to use filtered relation if ```foo``` exists, But it uses it's own Model queryset (i.e. ```all()```), ignoring whatever queryset it is operating on

**Comment by tomchristie** [comment]
Filters *are* applied to the queryset that the view returns from `get_queryset`.

See here for where the filters get called:

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L84

`queryset = self.filter_queryset(self.get_queryset())`

I'm going to close the issue as it currently stands.

**Comment by mbande** [comment]
@tomchristie i've read the code before opening the issue, but it seems that the results is different than what it supposed to be

**Comment by tomchristie** [comment]
If you can reduce this to a clearer example case then we can consider it. The filters *are* applied to the result of `get_queryset`, so if there's an issue, then it's something that's either not been cleary enough described in this ticket, or else a problem in your codebase that needs resolving.

It's possible that your issue could be related to this line in your code...

    queryset = self.queryset

This should actually either be `self.queryset.all()` or `super(...).get_queryset()`, in order to ensure that the queryset is re-evaluated with each incoming request.

**Comment by mbande** [comment]
@tomchristie thank you for your suggestions. i tested them with no luck.
to make it more clear, lets see a simplified version of my code:
```py
# views.py
class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    filter_backends = (filters.DjangoFilterBackend, filters.OrderingFilter,)
    filter_class = ProductFilter

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.method == 'GET':
            brand_id = self.request.query_params.get('brand_id', None)
            if brand_id:
                queryset = queryset.prefetch_related(Prefetch('resources', queryset=Resource.objects.filter(brand_id=brand_id)))
            else:
                queryset = queryset.prefetch_related('resources')
        return queryset

```

```py
# filters.py
class ProductFilter(django_filters.FilterSet):
    min_score = django_filters.NumberFilter('resources__score', lookup_type='gte', distinct=True)

    class Meta:
        model = Product

```

```py
# models.py
class Resource(models.Model):
    brand = models.ForeignKey(Brand, related_name='resources')

    score = models.FloatField(null=True)

    # Generic relation to Product and like.
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.IntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
```

when some one query Product endpoint with 'brand_id=100&min_score=45', it means  "give me the Products that have a resource with brand_id 100 and scored more that 45". but the result set contains products that have any resource scored more than 45, whether it's brand_id is 100 or not

**Comment by johnraz** [comment]
Isn't the brand_id only filtering the prefetch related queryset and not the main one? just a wild guess though ^^

**Comment by mbande** [comment]
@johnraz there is corresponding filter in the FilterSet, i've just forget to put it here (i have pruned many other non related filters). post updated

**Comment by johnraz** [comment]
I guess you'd have to put together an example project demonstrating this and bring the discussion to the google group to get further guidance.

**Comment by mbande** [comment]
@johnraz i started a [discussion](https://groups.google.com/forum/#!topic/django-rest-framework/Hr-hfc3EjaE) on group
