### ISSUE TITLE
TokenAuthentication but getting CSRF verification failed

### ISSUE THREAD

**Issue by Gregoor** [tomchristie/django-rest-framework#4449]
Hi,

I'm getting `403 Forbidden - CSRF verification failed` despite using TokenAuthentication, as can be seen from my settings below. This is happening for signup as well as login.

settings.py
```
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
REST_SESSION_LOGIN = False
REST_FRAMEWORK = {    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}
```

Is that a bug?

**Comment by xordoquy** [comment]
CSRF is required for forms.
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
