### ISSUE TITLE
Unauthenticated response

### ISSUE THREAD

**Issue by MikiSoft** [tomchristie/django-rest-framework#4450]
Posted by Boris Burkov (@BurkovBA) [in Gitter chat group](https://gitter.im/tomchristie/django-rest-framework):
> I want `SessionAuthentication` to return 401 instead of 403 for unauthenticated users, but default `SessionAuthentication` doesn't support 401, cause there's no `authenticate_header()` method for it. Is this a totally bad design decision to use 401 with `SessionAuthentication`? If it's not, should I just create a custom `SessionAuthentication` subclass, which inherits from default and specifies `authenticate_header()`?

Andrew (@awbacker):
> I get a 401 but I am using JWT *and* SessionAuthentication. Removing JWT gives a 403 like you say. That is unexpected :confused:

**Comment by tomchristie** [comment]
> Is this a totally bad design decision to use 401 with SessionAuthentication

Not totally bad, just a little incorrect.

> I get a 401 but I am using JWT and SessionAuthentication. Removing JWT gives a 403 like you say.

See http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses...

> "The first authentication class set on the view is used when determining the type of response."

**Comment by BurkovBA** [comment]
@tomchristie Is it correct, that it is impossible to attain 401 with stock SessionAuthentication? So to get 401 I have to subclass SessionAuthentication and define some implementation of `authenticate_header()`, e.g.:

```
def authenticate_header(self, request):
        return 'Session authentication realm' 
```

@MikiSoft, Andrew (@awbacker) thanks for your help, guys

**Comment by tomchristie** [comment]
> SessionAuthentication doesn't allow to attain 401 by re-configuring it

That's correct, yes. Again, 401 isn't the correct response code.
