### ISSUE TITLE
[ModelSerializer] nullable&blankable fields are required (when unique_together used)?

### ISSUE THREAD

**Issue by rikva** [tomchristie/django-rest-framework#4456]
Hi! 

I'm running DRF 3.4.6 and experiencing unexpected behaviour.

I would expect fields with `null=True` and `blank=True` to be optional fields when using a `ModelSerializer`. However, this is not the case when using `unique_together`.

I could override the fields on the serializer but that kind of defeats the point of using a `ModelSerializer`.

Is this by design? Am I doing something wrong? Is this a bug?

(simplified) Model:

```python
class Domain(Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey("Domain", null=True, blank=True)

    class Meta:
        unique_together = (("parent", "name"),)
```

Serializer:

```python
class DomainSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Domain
```

View:

```python
class DomainViewSet(viewsets.ModelViewSet):
    queryset = models.Domain.objects.all()
    serializer_class = serializers.DomainSerializer
```

Request and response:

```python
    response = self.client.post(self.url, data={'name': 'example.com'})

    # response.content:
    # b'{"parent":["This field is required."]}'
```

**Comment by lwm** [comment]
This is existing behaviour.

http://www.django-rest-framework.org/api-guide/validators/#uniquetogethervalidator

> Note: The UniqueTogetherValidation class always imposes an implicit constraint that all the fields it applies to are always treated as required. Fields with default values are an exception to this as they always supply a value even when omitted from user input.

**Comment by rikva** [comment]
Oops! Didn't see that piece of documentation. Thanks!

Solved this issue by adding `default=None` to the model field declaration.

**Comment by melinath** [comment]
I just ran into this as well. TBH this seems like weird behavior to me. My use case is that I'm auto-generating part of the unique_together dynamically on save - on any save, not just DRF saves. The field is not always auto-generated, though, so I can't just make the field read-only.

But yeah. Definitely had to do some spelunking to figure out that my blank=True field was not only not automatically un-required, but also had a secret special thing that would make it required even if I explicitly marked it as required=False. This is super weird.

**Comment by melinath** [comment]
FWIW my workaround was setting the serializer field to `required=False, default=''`, _not_ the model field.

**Comment by melinath** [comment]
Haha. Just ran into this again and had to come back here to check how I fixed it last time.

**Comment by melinath** [comment]
Turns out I also needed to add `allow_blank=True`.

**Comment by yellowcap** [comment]
I had trouble with that too. Maybe it would be worth mentioning in the fields documentation that the `required` or `allow_blank` arguments have no effect if `unique_together` constraints exist on the model? 

For instance, add a comment here:
http://www.django-rest-framework.org/api-guide/fields/#required

**Comment by xordoquy** [comment]
@yellowcap we already have [something](http://www.django-rest-framework.org/api-guide/validators/#uniquetogethervalidator) but we may refer to it from the field page

**Comment by yellowcap** [comment]
Thanks @xordoquy I had found that, but only after a few hours of digging. It was hard to find out why the `required` flag was being ignored.

So a mentioning in the fields docs for the `required` and `allow_blank` args would be useful I think.

**Comment by xordoquy** [comment]
> So a mentioning in the fields docs for the required and allow_blank args would be useful I think.

Agreed.
