### ISSUE TITLE
APITestCase and to_representation problem

### ISSUE THREAD

**Issue by emamirazavi** [tomchristie/django-rest-framework#4466]
It lasts 2 days until i find the problem. In ``ModelSerializer``, the instance(raw model) passed to ``to_representation`` and instance created and returned via ``create`` or ``update`` methods are different! For now i can not provide many samples.
Therefore the result of the ``self.client.patch`` method is different from ``self.client.get``!

```
class BillViewSet(DefaultsMixin, viewsets.ModelViewSet):
    ...
```
```
class BillSerializer(ModelSerializer):
    ...
```

**Comment by tomchristie** [comment]
Hi.
As currently presented, this isn't a reproducible issue.
You'll need to do some more work on reducing this to a clear, obvious & reproducible case if you'd like us to look into it further.
