### ISSUE TITLE
Not picking up Danish translations

### ISSUE THREAD

**Issue by vesterbaek** [tomchristie/django-rest-framework#4469]
I'm sending requests with "Accept-Language: da". Translations originating from Django (eg. "This field is required.") and translations in my own apps work. Strings in rest framework always are always returned in english, eg. "This field may not be blank.". Looking into the locale folder of rest framework, I can see both "da" and "da_DK" where "da_DK" contains empty strings only. 

If I delete the da_DK folder in rest_framework, the Danish translations work. From looking at the gettext documentation, it seems empty value `""` means use the key as value.

I also looked a bit into the internals of Django wrt. translation in trans_real.py and gettext.py in gettext. My current language is correctly set to "da". gettext finds da/LC_MESSAGES/django.mo, da_DK/LC_MESSAGES/django.mo based on the locale dir provided to it by Django. gettext chains the two files via a _fallback parameter. And returns this to Django. Django then merges the translations from the given app into one translation dict. 

I couldn't entirely understand if the problem with the empty values are from gettext parsing of the mo-files where it replaces empty value with key or it's from Django's merging of the translation objects. Bottom line is that if I remove the empty entries (i.e. delete the da_DK dir) it works.

**Comment by xordoquy** [comment]
Make sure you have rest_framework in the `INSTALLED_APPS`.
I'm closing this issue because there it isn't actionnable in its current form. Translation are reported as working therefore I'd assume there's something wrong in your project.
We'll consider reopening with a test case that demonstrate the issue.

**Comment by vesterbaek** [comment]
It is added to installed apps, otherwise translated string would not get picked up correctly if I remove the da_DK folder.

See test case here: https://github.com/joblicate/django-rest-framework/commit/87ee48793dcc5c3fdb69b3767faf66101f19d579

It fails:
```
tests/test_localization.py F

============================================================================================================= FAILURES ==============================================================================================================
_________________________________________________________________________________________________ LocalizationTestCase.test_danish __________________________________________________________________________________________________
tests/test_localization.py:12: in test_danish
    self.assertEquals(_("Invalid token."), "Ugyldigt token.")
E   AssertionError: u'Invalid token.' != u'Ugyldigt token.'
E   - Invalid token.
E   + Ugyldigt token.
```

After removing the `rest_framework/locale/da_DK` folder:

```
tests/test_localization.py .

========================================================================================= 843 tests deselected by '-kLocalizationTestCase' ==========================================================================================
============================================================================================= 1 passed, 843 deselected in 1.27 seconds ==============================================================================================
```

**Comment by vesterbaek** [comment]
Also available as a pull request: https://github.com/tomchristie/django-rest-framework/pull/4470

**Comment by xordoquy** [comment]
Ok, I'm sorry I didn't clearly get the issue there.
Unfortunately I don't think the PR will fix the issue. It's likely that transifex will pull that file again during the next release.
The proper solution would be to remove all the empty translation from transifex *and* make sure they aren't uploaded again in the [process](http://www.django-rest-framework.org/topics/project-management/#upload-new-source-files)

**Comment by tomchristie** [comment]
Unable to forcibly delete from transifex. Continues to persist despite attempting deletion both in web app and from command line client.

Next step probably to remove them locally and deal with the hiccup manually, every time until we can find a proper resolution.

**Comment by tomchristie** [comment]
Updating the process notes to use `tx pull -a --minimum-perc=10`, which will prevent empty translation files being pulled in.
