### ISSUE TITLE
Missing comma in admin.html causes csrf error

### ISSUE THREAD

**Issue by danielkeller** [tomchristie/django-rest-framework#4472]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Load the admin

## Expected behavior
No javascript errors happen

## Actual behavior
Due to a missing comma [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templates/rest_framework/admin.html#L235) a javascript error occurs, causing requests made with the admin to fail with a CSRF error.

**Comment by xordoquy** [comment]
Is this related to #4471 ?
How can we reproduce the admin issue ? As you might see with #4471, it seems to be working.

**Comment by tomchristie** [comment]
Dammit, yup - needs resolving.
Same as https://github.com/tomchristie/django-rest-framework/issues/4435 but for the admin renderer.
Pull requests welcome.
