### ISSUE TITLE
Wrap docs/* to 80 chars where possible

### ISSUE THREAD

**Issue by lwm** [tomchristie/django-rest-framework#4474]
It is really inconvenient to read the documentation in a text editor without wrapping the lines as you go for those of us with small screens. Would you accept a PR to line wrap the docs?

**Comment by tomchristie** [comment]
Probably not, given that it'd have such a large footprint.
Also not clear that 80 chars would *necessarily* be most appropriate for docs.

This isn't a definite "no" - something like that *might* be considered, but I'd probably need to see how much of an impact it'd have first before figuring if it seems reasonable or not.

On balance I'm going to close this, but open to consideration if someone wanted to push ahead with demonstrating it (at 80, 120, or whatever) in a PR.

**Comment by lwm** [comment]
> Probably not, given that it'd have such a large footprint.

Fair enough. I dropped the diff anyway (probably more to laugh at). 

I'll be keeping that for a local copy ;)
