### ISSUE TITLE
Project level urls delegation and app level router

### ISSUE THREAD

**Issue by c17r** [tomchristie/django-rest-framework#4487]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

in project level urls.py
```python
from django.conf.urls import url, include

urlpatterns = [
    url(r'myapp/', include('myapp.urls')),
]
```

in myapp/urls.py
```python
from django.conf.urls import url, include
from rest_framework import routers

from myapp import views

router = routers.SimpleRouter()
router.register(r'', views.MyAppViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
]
``` 

## Expected behavior

Calls to `/myapp/` and `/myapp/1/` work

## Actual behavior

2 warnings:

- ?: (urls.W002) Your URL pattern '^/$' [name='myapp-list'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.
- ?: (urls.W002) Your URL pattern '^/(?P<pk>[^/.]+)/$' [name='myapp-detail'] has a regex beginning with a '/'. Remove this slash as it is unnecessary.

and the urls are actually `/myapp//` and `/myapp//1`

failing test cases at #4486

**Comment by tomchristie** [comment]
Closed via #4486
