### ISSUE TITLE
Make Reponse.json() work with JSON compatible custom content types

### ISSUE THREAD

**Issue by sametmax** [tomchristie/django-rest-framework#4491]
To allow versioning in headers, [as suggested in the doc](http://www.django-rest-framework.org/api-guide/versioning/#acceptheaderversioning), I have a custom content type "application/vnd.foo+json; version=1.0". Unfortunatly I can't benefit from the shortcut `Response.json()` when I use this header because I'd get the exception:

`*** ValueError: Content-Type header is "application/vnd.foo+json; version=1.0", not "application/json"`

**Comment by tomchristie** [comment]
Neither REST framework nor Django expose a `.json()` method on response objects.
Perhaps you're talking about using Python requests? If so, maybe try the latest versions, as I don't see any explicit check of the content-type... https://github.com/kennethreitz/requests/blob/master/requests/models.py#L802

**Comment by lsh-0** [comment]
Just an update, Django does support a `.json()` method in 1.9 with the test client: https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.Response.json

Just got bit by this myself upgrading to python3. Verbose workaround is:

`data = json.loads(response.content.decode('utf-8'))`
