### ISSUE TITLE
default_timezone not working

### ISSUE THREAD

**Issue by arkadiybag** [tomchristie/django-rest-framework#4496]
field in my serializer:
```
date_from = serializers.DateTimeField(default_timezone=settings.TIME_ZONE)
```

my settings.py:
`TIME_ZONE = 'Europe/Moscow'
`
data in admin site:
http://image.prntscr.com/image/4771143a26144f2e801928a197e186d8.png

and date in response:
`"date_from": "2016-08-19T21:00:00Z"`

Okay, i understand, what he return me time in UTC, but how i can get time in my timezone?
Only use `SerializerMethodField`?

**Comment by xordoquy** [comment]
Hi, the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
