### ISSUE TITLE
The list/detail_routes should be able to provide hints about the schema they use

### ISSUE THREAD

**Issue by gcbirzan** [tomchristie/django-rest-framework#4503]
Currently, these separate actions on the viewset inherit the schema from the viewset, but that's very often not correct. Even if it's not used to present data (which, btw, should also be an option, but that's a discussion for another time :P), you should be able to annotate the view somehow so that the schema generator can generate the correct schema. Right now, you're stuck doing ugly things in get_serializer(), but it can be standardized!

**Comment by tomchristie** [comment]
I'm not sure exactly what you mean. You can customize their behavior using eg `@detail_route(methods=['post'], serializer_class=SomeSerializer)`. Also there's a bunch of improvements in the schema generation upcoming in 3.5, which should make it far easier to customize that behaviour.

**Comment by tomchristie** [comment]
If there's something specific that you need beyond what either of those two provide for then very welcome to open a new issue with details.
