### ISSUE TITLE
Browsable API navbar gets overlapped by highlighted pagination item

### ISSUE THREAD

**Issue by rooterkyberian** [tomchristie/django-rest-framework#4512]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
enable browsable API and visit endpoint with enabled pagination

## Expected behavior
pagination is covered by top navigation bar like everything else

## Actual behavior
Highlighted (current) page is displayed on above the top navbar
http://i.imgur.com/yh7DPXs.png

![yh7dpxs](https://cloud.githubusercontent.com/assets/647359/18783376/5b22451e-8183-11e6-83e2-3b934918f40c.png)

Seems easily fixed by removing following line: https://github.com/tomchristie/django-rest-framework/blob/bb56ca46ed6c07db0146dbdc61c672ff25f127de/rest_framework/static/rest_framework/css/bootstrap-tweaks.css#L35

**Comment by tomchristie** [comment]
(Edited you comment to include the image inline)

**Comment by tomchristie** [comment]
I've not seen this issue before. Which browser is this with?

**Comment by rooterkyberian** [comment]
Screenshot comes from Firefox 48.0, but I can reproduce the same thing in Chromium 53.0.2785.116 .

Seems like a regression after https://github.com/twbs/bootstrap/commit/2a38a92324c26116126fde301e79eaf786c868ca ?
so it would have been broken in restframework after https://github.com/tomchristie/django-rest-framework/commit/8c6ded38de534498b7c930bb36f7c882b6176194#diff-2669be10c2acf561d7c10882cdc38708
or https://github.com/tomchristie/django-rest-framework/commit/b63099084f471fe3cd477fc5a5aa90cc97fca827#diff-2669be10c2acf561d7c10882cdc38708

**Comment by tomchristie** [comment]
Okay, thanks. Pull requests welcome, as are confirmations from anyone else.

**Comment by rpkilby** [comment]
I can confirm this for DRF 3.4 as well. This does *not* occur for me with DRF 3.3 however.

**Comment by tomchristie** [comment]
Thanks @rooterkyberian, @rpkilby.

**Comment by akshaysharma096** [comment]
Will submit a pull request.
Many thanks for raising this issue.

**Comment by tomchristie** [comment]
Closed via #4547. Thanks!
