### ISSUE TITLE
JSONField dumps instead of loads

### ISSUE THREAD

**Issue by nicodv** [tomchristie/django-rest-framework#4514]
```
    def to_internal_value(self, data):
        try:
            if self.binary:
                if isinstance(data, six.binary_type):
                    data = data.decode('utf-8')
                return json.loads(data)
            else:
                json.dumps(data)  # <------------ shouldn't that be 'loads'?
        except (TypeError, ValueError):
            self.fail('invalid')
        return data
```

See above code fragment. I'm having issues with this, and I suspect that `dumps` needs to be a `loads`.

**Comment by OJFord** [comment]
Whether it's `dumps` or `loads`, it's not doing anything - the return value is discarded.

**Comment by xordoquy** [comment]
Before theorizing on what it should be, you should start with writing a test case that demonstrate there's currently an issue.
The JSONField tests are at https://github.com/tomchristie/django-rest-framework/blob/master/tests/test_fields.py#L1666 with `TestJSONField` and `TestBinaryJSONField`.
