### ISSUE TITLE
Caching by passes TokenAuthentication in APIVIEW.

### ISSUE THREAD

**Issue by akshaysharma096** [tomchristie/django-rest-framework#4515]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
You can verify this bug, if you use any cache backend with your project.
## Expected behavior
TokenAuthentication should always check whether a request made is authenticated or not, before returning any response!
The authentication mechanism should work irrespective of the project.
## Actual behavior
Given, a user has configured Caching in the settings.py file and we are fetching some large datasets from the database using Django ORM, then Caching bypasses the TokenAuthentication scheme.
The previously cached query is returned.

**Comment by akshaysharma096** [comment]
I would like to contribute to the issue.

**Comment by xordoquy** [comment]
The first step would be to add a test case that demonstrate the issue

**Comment by akshaysharma096** [comment]
Yeah sure!

**Comment by akshaysharma096** [comment]
Can I upload a screenshot of the same issue ?

**Comment by akshaysharma096** [comment]
@tomchristie  @xordoquy any help will be appreciated.
I'd suggest that the permissions docs would be the right place to put this.
Also, I'd phrase it more about middleware as a whole being run before permissions, then perhaps use the cachingmiddleware of an example case to be aware of.

**Comment by xordoquy** [comment]
Well, this is expected from middleware caching. Note that it will have side effects on throttling, might also affect pagination though I'm not sure on that one.
I'm going to close it as it's not actionnable in its current state.
Will reconsider if we have a proof that Django's login isn't affected by the caching middleware.
