### ISSUE TITLE
Nested relationship serialization depends on related_name which is optional

### ISSUE THREAD

**Issue by ajostergaard** [tomchristie/django-rest-framework#4517]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [n/a] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Try to serialize a nested relationship without related_name defined

## Expected behavior
Should work as related_name is optional... Defaults to FOO_set if I'm not mistaken.

## Actual behavior
Nested field is ignored.

Either should fix code or document dependency.

**Comment by tomchristie** [comment]
Had a brief review of this. Don't think it's sufficiently descriptive as it currently stands. Could you include a brief example, and will consider reopening.
