### ISSUE TITLE
ObtainAuthToken nolonger returns if a user is inactive

### ISSUE THREAD

**Issue by flupzor** [tomchristie/django-rest-framework#4520]
I've made a test which succeeds on Django 1.9 but fails on Django 1.10.
https://github.com/flupzor/django-rest-framework/commit/10be6439a91facbef67ae6a34a2ac6ec9b6483c3

It fails due to a change in django.contrib.auth.authenticate in Django 1.10 which no longer returns a user if it is inactive. (https://github.com/django/django/blob/1.10.1/django/contrib/auth/backends.py#L23)

It can be reproduced by running the test on Django 1.9 and Django 1.10.

The expected behavior is that the view returns "'User account is disabled." in Django 1.10, but for me this is not a needed functionality, returning ''Unable to log in with provided credentials." is fine for me as well.

**Comment by tomchristie** [comment]
That's great - good work tracking it down. 😄 
Would you mind submitting that test as a pull request?

**Comment by flupzor** [comment]
I've just added a PR :) https://github.com/tomchristie/django-rest-framework/pull/4521

**Comment by tomchristie** [comment]
Alrighty. Thanks for calling this out.

I don't think there's anything sensible we can do about this, as we're simply following Django's latest behaviour in this regard. `authenticate` won't return us a user. We could get around it by replicating the `ModelBackend` behavior, but `ModelBackend` isn't the only possible authentication backend that could be installed, and we *should* simply be relying on the behavior of whatever authentication backend is used.

I've added a comment to make the behaviour more clear, at https://github.com/tomchristie/django-rest-framework/pull/4525/commits/b689a3bdaa521b14d13266c866180d19585babe4
