### ISSUE TITLE
Integrating serializers with Queryset.only()

### ISSUE THREAD

**Issue by jplock** [tomchristie/django-rest-framework#4537]
Has there been any work done to control the fields returned by the serializers with restricting the fields being returned from the database using `queryset.only()`?  I searched through the existing issues and pull requests and couldn't find any references to this.

**Comment by dhm116** [comment]
It seems like it could provide some nice performance improvements if a `ModelViewSet` was able to restrict the queryset and serializer fields easily without a lot of custom code... 👍

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by tomchristie** [comment]
Nothing in core, take a look through third party packages, and as @xordoquy mentions have an ask on the discussion group.
