### ISSUE TITLE
Is realtime support implemented yet?

### ISSUE THREAD

**Issue by sanchig** [tomchristie/django-rest-framework#4539]
As I read Django REST framework 3.4 announcement page I found "realtime support". We are using django rest framework for API.  Actually I am looking to work in realtime in django-rest-framework. I tried to find in website for realtime support page but not found. Can you please give me that realtime support reference URL or suggestion?. Thanks in advance.

**Comment by tomchristie** [comment]
@sanchig - We'll be doing work towards this in the future. You can get started with Django-channels already but we don't yet have any docs about using that together with REST framework.

**Comment by Eraldo** [comment]
Has there been quite a while. What is the current status? :)

**Comment by tomchristie** [comment]
Same situation ATM - there's some stuff roughly planned for a 3.7 release,
but no planned data on that currently.

Follow the monthly reports for more updates... https://fund.django-rest-framework.org/topics/funding/#accountability

**Comment by Eraldo** [comment]
Thanks Tom for the update.
In the provided link I read 'monthly updates' however the last post I see is titled February 2017.
I don't want to complain here I am just a little puzzled. :)

**Comment by tomchristie** [comment]
Looks like the link there is out of date...

Last few are here:

* http://www.encode.io/reports/may-2017
* http://www.encode.io/reports/june-2017
* http://www.encode.io/reports/july-2017

**Comment by Eraldo** [comment]
Thanks for sharing this.
