### ISSUE TITLE
DB transaction rollback on 400, 403 and 404

### ISSUE THREAD

**Issue by meshy** [tomchristie/django-rest-framework#4560]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Have `ATOMIC_REQUESTS` enabled.
1. Receive request.
1. Save something to the database.
1. Respond with `serializer.is_valid(raise_exception=True)` OR <br>
  `raise Http404` OR <br>
  `raise PermissionDenied`.

## Expected behavior
- Data is saved to the database.

## Actual behavior
- Database transaction is rolled back.

---

This came as something of a surprise!

This doesn't happen with `400`, `403`, or `404` from a `return Response` because this logic is in the of the [`exception_handler`](https://github.com/tomchristie/django-rest-framework/blob/0dec36eb413c98902d997ebd2f9cb2b7111e6e56/rest_framework/views.py#L78).

I was under the impression that raising these exceptions was an equivalent "shortcut" to manually returning these responses. I was not aware of this side-effect, but it does look as though it was intentionally introduced in `3.1.3` (https://github.com/tomchristie/django-rest-framework/pull/2887).

I've discovered that I can change this behaviour by overriding `EXCEPTION_HANDLER`, or by using the full form of `return Response(serializer.errors, status=400)` (etc), but it feels wrong somehow.

I've asked a few friends, and some of them suggest that rolling back the DB like this is a REST thing, but I'm not convinced of that. Otherwise, wouldn't all 400, 403, and 404 need to be rolled back regardless of if they're raised / returned?

**Comment by tomchristie** [comment]
I think we're consistent enough with Django's documented behaviour here...

> It works like this. Before calling a view function, Django starts a transaction. If the response is produced without problems, Django commits the transaction. If the view produces an exception, Django rolls back the transaction.

**Comment by meshy** [comment]
Ah, ok, I see the logic now. Does django normally roll back transactions on `Http404` and `PermissionDenied` then?

Do you think it would make sense for the docs for `raise_exception` to mention this?

**Comment by xordoquy** [comment]
It doesn't really make sense for 404 or 403 as they should be performed before any change.
400 also usually mean that the validation failed which also happens before any change is made.

The only case I can think of is when the user do some changes before raising those codes but in that case he should also be responsible to explicitly rollback.

**Comment by meshy** [comment]
Yeah, that's how I discovered this. I've tried to make changes before those codes are raised, and was surprised to find it didn't always work. The rollback was very unexpected.

**Comment by tomchristie** [comment]
I believe that the behavior as we currently have it most accurately matches Django's own transaction handling. If someone demonstrates that Django's behavior wrt ATOMIC_REQUESTS happens to be different for permission and 404 exceptions then we can reconsider.

**Comment by meshy** [comment]
Fair enough. Do you think it might be worth mentioning this in the docs for `raise_exception`?

**Comment by tomchristie** [comment]
I think the behavior of ATOMIC_REQUESTS could be worth mentioning, yes. Tho I don't think we need to call out that the different types of exception *all* behave the same. (Ie pretty much cloning Django's text on the subject would be reasonable)
