### ISSUE TITLE
Allow passing Authentication header through UI

### ISSUE THREAD

**Issue by amitt001** [tomchristie/django-rest-framework#4578]
It would be helpful if there is some way to pass authentication header in requests sent through Django rest UI.

**Comment by tomchristie** [comment]
That's not really going to be possible. When you follow links in the browsable API (eg breadcrumbs, pagination controls, hyperlinks in response content, etc...) you're making a regular ol' browser interaction. We're not able to set custom headers in the user's browser. (We can only do so for AJAX requests, which wouldn't properly handle the navigate (eg. update the URL in the browser).

Perhaps at some future date we'll figure some solution to making *all* the interactions be AJAX requests, or introduce a completely different method of interacting with and browsing the API. Or perhaps browsers will build in OAuth or JWT support that we can use. Until then the best we can do is offer authentication schemes that browsers *do* support (eg. SessionAuthentication, BasicAuthentication)
