### ISSUE TITLE
Tutorial has a lookup_field problem

### ISSUE THREAD

**Issue by smllmn** [tomchristie/django-rest-framework#4591]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Follow tutorial up to the generic class-based views section of chapter 3. Attempt to access a snippet detail (e.g. in the browser at localhost:8000/snippets/1)
## Expected behavior
Return the serialised snippet
## Actual behavior
> AssertionError: Expected view SnippetDetail to be called with a URL keyword argument named "pk"
> ...

The problem is that until that point in the tutorial the views were written out in full and used a keyword argument `id`. When changing to the class-based views, the expected argument is `pk`. Either `urls.py` should be updated to capture the argument as `pk` or the SnippetDetail class needs to have a `lookup_field` option.

**Comment by xordoquy** [comment]
Confirmed.

**Comment by jpadilla** [comment]
Probably go with this: 
> Either urls.py should be updated to capture the argument as pk

**Comment by xordoquy** [comment]
well, imho, a correct urls.py file would be better

**Comment by jpadilla** [comment]
@xordoquy yeah, that's what I meant. Wouldn't that mean using `pk` instead of `id` all throughout?

**Comment by tomchristie** [comment]
Okay, this is my screw-up. Incorrectly replaced the previous `pk` in the tutorial with `id` throughout as part of the upcoming 3.5 release.

**Comment by tomchristie** [comment]
Should be `pk` in the views and the URL conf.
