### ISSUE TITLE
APIClient should convert data dict to QueryDict

### ISSUE THREAD

**Issue by leonardoarroyo** [tomchristie/django-rest-framework#4598]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
from rest_framework.test import APIClient
client = APIClient()
response = client.post(reverse('upload-images-list'), {}, format="json")

# and on the view
print(type(request.data))
```

## Expected behavior
Expected output:
`<class 'django.http.request.QueryDict'>`

## Actual behavior
Actual output:
`<class 'dict'>`

**Comment by xordoquy** [comment]
Could you explain why this is an issue ?

**Comment by tomchristie** [comment]
Given that it's a json request I wouldn't expect a QueryDict.
