### ISSUE TITLE
ModelSerializer should be able to serialize without persisting.

### ISSUE THREAD

**Issue by stevecj** [tomchristie/django-rest-framework#4599]
In writing unit tests (and possibly in other situations) it is nice to be able to build a new instance of a Django model without saving the instance.

In the case of unit tests, it slows down tests to have to interact with the database for tests of model serializer functionality when there is already other test coverage of the model's persistence behavior either via direct tests on the model or via full-stack tests.

It would be nice it DRF's ModelSerializer had methods to just build (and possibly also just modify) model instances without persisting and have those methods be called by the `.create()` and `.update()` methods to perform those parts of their work.

**Comment by xordoquy** [comment]
If you're unit testing, you shouldn't call create / update.
If you have overridden both, you could pass an extra arg to the serializer.save() to desactivate the I/O with the database.

**Comment by tomchristie** [comment]
Seconding @xordoquy, with one more follow up:

Serializers deliberately don't return unsaved model instances, but plain data instead. (I won't go into the design reasons here.) Inspect `serializer.validated_data` if you want to ensure that the input validation behaviour is correct.

**Comment by stevecj** [comment]
…but the save() method of subclasses of ModelSerializer _do_ return instances of models.

There are cases where one wants to know that the combination of serializer behavior and model property setter behavior has worked properly, separate from actually interacting with the database. I am dealing with a case like that right now.

**Comment by xordoquy** [comment]
Then add an extra flag to serializer's save that would turn off the model's save in create/update

**Comment by stevecj** [comment]
Thanks. I'll give that a try.

**Comment by tomchristie** [comment]
> separate from actually interacting with the database

Except that we *don't* ever have an unsaved instance, because we're calling `MyModel.objects.create(...)`, rather than `instance = MyModel(...); instance.save()`

The `save()` method is responsible for taking validated data and persisting it. The separation of concerns you're describing *is* `serializer.validated_data` vs `serializer.save()`

**Comment by stevecj** [comment]
@xordoquy 
I ended up with is adding a dynamic `transient` property to the model and overriding `save()` to return without calling its super when `transient` is true. Works like a charm.

Thanks for pointing me in the right direction.

**Comment by xordoquy** [comment]
As a note for later readers, you shouldn't need to add a property to the model for that. You can use save's extra argument in the `create`/`update` `validated_data`.
