### ISSUE TITLE
Not calling function with source= anymore

### ISSUE THREAD

**Issue by debnet** [tomchristie/django-rest-framework#4602]
Here the serializer:

```python
class IndividuSerializer(ModelSerializer):
    # ...
    sexe_display = CharField(source='get_sexe_display', label='sexe', read_only=True)
```

The API doesn't display the choice values from Django models anymore.

```json
{
    "url": "http://localhost:8000/api/dsn/individu/1/",
    "id": 1,
    "metadatas": null,
    "sexe_display": "<bound method curry.<locals>._curried of <Individu: XXX XXX>>",
    "...": "..."
}
```

In the previous release it worked just fine. ;)

**Comment by tomchristie** [comment]
I'm not able to replicate this.

For example...

    class UserSerializer(serializers.ModelSerializer):
        username = serializers.CharField(source='get_username', read_only=True)

        class Meta:
            model = User
            fields = ('id', 'username', 'email')

Results in this...

![screen shot 2016-10-21 at 15 40 44](https://cloud.githubusercontent.com/assets/647359/19602352/d6d9e040-97a4-11e6-9fe7-7abe22c5e826.png)

**Comment by guinner** [comment]
```python
class IndividuSerializer(ModelSerializer):
    # ...
    sexe_display = CharField(source='get_sexe_display', label='sexe', read_only=True)
```
The field 'sexe' is defined in django model. And The method 'get_sexe_display' is django's '_get_FIELD_display'. It's returned '<bound method curry.<locals>._curried of <Individu: XXX XXX>>'. 

_curried(*moreargs, **morekwargs) is defined in django.utils.functional

But In drf 'fields.py' line 62, method 'is_simple_callable', param.default is always param.empty.

**Comment by rpkilby** [comment]
I've started a patch which is failing - will have to come back to this later.

The problem with the patch implementation is that it can't determine if *args and **kwargs are safely callable.

**Comment by rpkilby** [comment]
For those in need of a quick fix for `get_FIELD_display()`, you can add a `FIELD_display` property that simply calls the method.
