### ISSUE TITLE
`DjangoModelPermissions` doesn't take into account `user.is_superuser`

### ISSUE THREAD

**Issue by wimglenn** [tomchristie/django-rest-framework#4603]
Django's `is_superuser` doesn't appear to be respected by DRF.  

## Steps to reproduce

- We have a `ModelViewset` with `permissions.DjangoModelPermissions`
- `user.is_superuser` is True, whence `user.has_perm('delete_foo')` returns True irrespective of whatever is contained in `user.get_all_permissions()`.  
- user tries to delete at `/api/foo/1`

## Expected behavior

HTTP 204 No Content

## Actual behavior

HTTP 403 Forbidden 

(I just use delete as an example, same goes for other methods)

**Comment by kevin-brown** [comment]
Note that the default behaviour for `get_all_permissions` is to return `True` when the user is a superuser. As of Django 1.3, this should happen in the default permission backends: https://github.com/django/django/commit/5b8ef18dcc006c0fa53b356efbb7cf2c691463d5. The `has_perm` method [directly calls `get_all_permissions`](https://github.com/django/django/blob/1f5b69917dae2a2d5414560f3de9cd95a9adb812/django/contrib/auth/backends.py#L83-L86) when doing checks.

**Comment by wimglenn** [comment]
Did you mean to write that the default behavior is to return Permission.objects.all()? I will check my backend tomorrow, but I'm pretty sure has_perm simply returned True directly.  I'm on django 1.8

**Comment by xordoquy** [comment]
Seconding @kevin-brown.
Will reconsider opening with a simple failing test case.

**Comment by wimglenn** [comment]
@kevin-brown  I see what you're talking about, but it never gets that far because of this mixin -->  https://github.com/django/django/blob/9b9c8c4a81ab67d1bc392b6fd9cc17e0b844f7ff/django/contrib/auth/models.py#L261-L275

**Comment by xordoquy** [comment]
@wimglenn I'm a bit lost about your initial issue.

> user.is_superuser is True, whence user.has_perm('delete_foo') returns True irrespective of whatever is contained in user.get_all_permissions().

This should lead to HTTP 204 anyway. I just don't get this issue, could we have a failing test case ?
The current are located here: https://github.com/tomchristie/django-rest-framework/blob/master/tests/test_permissions.py#L72
