### ISSUE TITLE
Tutorial 7: Schemas & client libraries - Accept type appears incorrect

### ISSUE THREAD

**Issue by bendog** [tomchristie/django-rest-framework#4604]
Error when attempting to use the coreAPI tutorial code, mime type is not accepted.

> $ http http://127.0.0.1:8000/schema/ Accept:application/vnd.coreapi+json
> HTTP/1.0 406 Not Acceptable
> Allow: GET, HEAD, OPTIONS
> Content-Type: application/coreapi+json
> Date: Fri, 21 Oct 2016 02:27:22 GMT
> Server: WSGIServer/0.2 CPython/3.4.3
> Vary: Accept
> X-Frame-Options: SAMEORIGIN
> 
> {
>     "detail": "Could not satisfy the request Accept header."
> }
> 

this however does work

> $ http http://127.0.0.1:8000/schema/ 
> HTTP/1.0 200 OK
> Allow: GET, HEAD, OPTIONS
> Content-Type: application/coreapi+json
> Date: Fri, 21 Oct 2016 02:28:36 GMT
> Server: WSGIServer/0.2 CPython/3.4.3
> Vary: Accept, Cookie
> X-Frame-Options: SAMEORIGIN
> 
> {
>     "_meta": {
>         "title": "Pastern API"

>     },
>     "_type": "document",
>     "snippets": {
> ...

I believe 
`http http://127.0.0.1:8000/schema/ Accept:application/vnd.coreapi+json`  
should be 
`http http://127.0.0.1:8000/schema/ Accept:application/coreapi+json`

**Comment by tomchristie** [comment]
Yup, thanks for raising this!

**Comment by haolle** [comment]
seems the issue is still there.
