### ISSUE TITLE
Invalid prefix in Swagger.

### ISSUE THREAD

**Issue by PraveshKoirala** [tomchristie/django-rest-framework#4605]
I am using python 2.7 and rest framework 3.5. 
As the title suggests, the prefix is invalid in swagger. It's best shown by this image.
![image](https://cloud.githubusercontent.com/assets/2066100/19593172/f02ac27c-979e-11e6-8582-b1594fc3a0ce.png)

## Expected behavior
The prefixes should have been "api" and "auth" instead of "pi" and "uth".

I suspect that it is due to the behavior of "os.path.commonprefix" in python 2.7

**Comment by tomchristie** [comment]
Okay, thanks - can you include a minimal example that demonstrates reproducing the issue?

**Comment by tomchristie** [comment]
Confirmed. Register two API views with the URLs given above, and seeing the same issue.

**Comment by tomchristie** [comment]
See also http://nedbatchelder.com/blog/201003/whats_the_point_of_ospathcommonprefix.html

**Comment by PraveshKoirala** [comment]
> This function is in the wrong place, and has nothing to do with paths, don't use it if you are interested in file paths!

Thanks for the link Tom :D :D

**Comment by tomchristie** [comment]
That usage bug was reported *14 years ago*.

If anyone fancies making their first contribution to Python (2.7 docs), it'd be a good one to deal with! 😄 

https://docs.python.org/2/library/os.path.html#os.path.commonprefix
