### ISSUE TITLE
How to create the browsable api page

### ISSUE THREAD

**Issue by C0deZLee** [tomchristie/django-rest-framework#4623]
I have read through the document and googled a lot, but cannot find a word that is useful to tell me how to create the browsable api page. 
The document only talks about how to customization but doesn't touch the basic question, how can I create a browsable page?
If anyone knows the solution, I would be very appreciate.
Thanks.

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
