### ISSUE TITLE
BooleanField should also parse 'on'

### ISSUE THREAD

**Issue by rsalmaso** [tomchristie/django-rest-framework#4624]
## Checklist
- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)
## Steps to reproduce

`$(form).serialize()` serialize checkbox with no `value` to "`on`" or "`off`"
## Expected behavior

Add "`on`" to `TRUE_VALUES` and "`off`" to `FALSE_VALUES`
(I don't always have the control over html/js to add `value` to checkboxes).
## Actual behavior

Value is ignored

**Comment by tomchristie** [comment]
I'm a little lukewarm on this, but sure, let's go ahead. Seems a common enough style.
