### ISSUE TITLE
PEP8/Linter changes

### ISSUE THREAD

**Issue by adamn** [tomchristie/django-rest-framework#4626]
There are new flake8, pep8, twine, and transifex-client libraries in PyPI.  DRF should use them.

In order to use them, the `serializers` module will have to no longer `import *` from `relations` and `fields`.
- Get rid of the `import *` syntax in `serializers`
- Update the PyPI packages
- ~~Where we currently use `serializers.Example`, we will now use `fields.Example` or `relations.Example` if `Example` is a field or a relation that otherwise would have passed through the `serializers` module~~ [We're not doing this]
- Create a `.flake8` file with the equivalent of `FLAKE8_ARGS = ['rest_framework', 'tests', '--ignore=E501']` and take it out of `runtests.py`

See #4613 for more information

**Comment by xordoquy** [comment]
> Get rid of the import * syntax in serializers

I'm -1 on this.

Developers rely a *lot* on this as well as the documentation. This is going to be hard and painfull to remove.

What benefits do we have to weight against those objections ? Can't think of a good enough one thus my -1 on this

**Comment by tomchristie** [comment]
> Get rid of the import * syntax in serializers
> Where we currently use serializers.Example, we will now use fields.Example or relations.Example

That's not going to be acceptable.

* Is there any kind of ignore directive that we can use?
* Could we import each field explicitly in the serializers module, but still use `serializers.Example`?

**Comment by xordoquy** [comment]
> Could we import each field explicitly in the serializers module, but still use serializers.Example?

There's more than just the fields. It's likely be a long list

**Comment by tomchristie** [comment]
> There's more than just the fields.

The fields are the only one we care about I believe. We document `serializers.IntegerField` as usage. Doesn't mean we necessarily need to support `serializers.some_undocumented_non_public_api_function`. Although yes, we would need to limit that to a major version bump.

**Comment by adamn** [comment]
I think I mis-expressed myself.  There are many cases where we use `serializers.` but actually the class is not a `serializer`.  For instance in test_model_serializer.py:104:

```python
            non_model_field = serializers.CharField()
```

should be:

```python
            non_model_field = fields.CharField()
```

`CharField` is not a serializer and it's not defined in the `serializers` module.  Nonetheless, end users will still be able to access `serializers.CharField` because `serializers` would still import those classes from `fields` as can be seen in #4628 and they would be available from there.

**Comment by tomchristie** [comment]
> should be:

Except that we use the `serializers.CharField()` style intentionally because it's clearer. We don't want to change that usage, either inside our own codebase, or in our documented usage.

Using `fields.CharField()` is far less clear as it could refer to any of the following:

* A Django form field.
* A Django model field.
* A Django REST framework serializer field.

**Comment by adamn** [comment]
Ok, then this becomes much easier.  Let's disregard `Where we currently use serializers.Example, we will now use fields.Example or relations.Example if Example is a field or a relation that otherwise would have passed through the serializers module`.

In `serializers` it's just a matter of converting the `import *` to import all the fields and relations explicitly.

**Comment by tomchristie** [comment]
Exactly yup. #4628 looks on track here. Could fork that and try applying the linter package upgrades against it to see where that gets us too.

**Comment by tomchristie** [comment]
Righty #4628 is now merged. Happy to reconsider any PRs updating the versions of any or all of those libraries, and can see if there's any remaining issues at that point.
