### ISSUE TITLE
Autofill raw data content in ViewSet

### ISSUE THREAD

**Issue by moh3n9595** [tomchristie/django-rest-framework#4635]
hi, i use  "viewsets.ViewSet" for develope and i need raw data content autofill.
for example, this is api with ModelViewSet :  
![image](https://cloud.githubusercontent.com/assets/20948388/19828741/5b85140e-9ddb-11e6-93a1-9a3c50411be0.png)
and with ViewSet : 
![image](https://cloud.githubusercontent.com/assets/20948388/19828747/75c79544-9ddb-11e6-8bc4-6d96c9f98eb4.png)

this is a bug? please help.

**Comment by tomchristie** [comment]
You'll need a view/viewset with a `get_serializer` method if you want that field to be able to automatically populate.
