### ISSUE TITLE
Schema generation view (result of `get_schema_view`) returns HTTP 404 when some permission class raises Http404

### ISSUE THREAD

**Issue by szopu** [tomchristie/django-rest-framework#4645]
I found this bug when I was using django-rest-swagger, but during debugging I found out that the problem is in the DRF itself.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Use a ViewSet with DRF permission class raising Http404, for instance `DjangoObjectPermissions` from `rest_framework.permissions`
* Install django-rest-swagger in your django project
* Go to the URL where swagger view is configured to be called

## Expected behavior
The page loads and you can see all accessible endpoints.

## Actual behavior
The page loads but you see message like this: "Can't read swagger JSON from http://localhost:8000/?format=openapi". When you check in the developer console you notice that this URL returned HTTP 404.

**Comment by tomchristie** [comment]
Closed via #4645

**Comment by glarrain** [comment]
@tomchristie:

> Closed via #4645

You probably meant #4646

**Comment by tomchristie** [comment]
Thanks, yes - now updated the comment!

**Comment by georgetoloraia** [comment]
Can I reset the schema? i have Django project
