### ISSUE TITLE
Update Trove Classifers in setup.py

### ISSUE THREAD

**Issue by michaeljohnbarr** [tomchristie/django-rest-framework#4654]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
None. Issue is with the [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers) in the https://github.com/tomchristie/django-rest-framework/blob/master/setup.py

## Expected behavior
Have the [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers) to match the documented [Django REST Framework Requirements](http://www.django-rest-framework.org/#requirements) in future releases:
```
Framework :: Django
Framework :: Django :: 1.8
Framework :: Django :: 1.9
Framework :: Django :: 1.10
Programming Language :: Python :: 2
Programming Language :: Python :: 2.7
Programming Language :: Python :: 3
Programming Language :: Python :: 3.2
Programming Language :: Python :: 3.3
Programming Language :: Python :: 3.4
Programming Language :: Python :: 3.5
```

## Actual behavior
Currently, the below are listed:
```
Framework :: Django
Programming Language :: Python
Programming Language :: Python :: 3
```
If doing filtering by the [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers), it would be nice to see the exact versions of Django/Python supported. Additionally, it helps with third-party sites to list the correct requirements that are retrieved from the [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers) within the PyPI API ([example](https://pypi.python.org/pypi/djangorestframework/json)).

**Comment by tomchristie** [comment]
Seems fair enough. Pull requests welcome.
