### ISSUE TITLE
Cannot use full URL as lookup field because of urlconf pk regex

### ISSUE THREAD

**Issue by FalFire** [tomchristie/django-rest-framework#4658]
Hi,

I simply want to be able to query objects in my viewset by a field containing a full URL including dots and forward slashes. For this I started to override the get_object method of the viewset but I got stuck because this means that I have to be able to go to resource http://www.server.com/myresource/http%3A%2F%2Fwww%2Egoogle%2Ecom/ which yields a 404 even when urlencoding the URL because the default generated regex for pk fields is `(?P<pk>[^/.]+)`. I only need to be able to do this for a single endpoint in my urlconf, which is the detail URL of a viewset. All other endpoints of the viewset are OK and should remain standard. Is there a way to change the regex for only this endpoint?

**Comment by FalFire** [comment]
Well, I was able to fix it by using the totally undocumented attribute `lookup_value_regex` in my viewset, which I came across while looking through the source code in search for some workaround. I will leave this issue open as this now seems a documentation issue to me, unless it is explicitly unstable/experimental/meant to be a private API only?

**Comment by xordoquy** [comment]
It's already documented in the router section. It's there since the routers are responsible for the URL generation.
