### ISSUE TITLE
Can't delete validators in ModelSerializer

### ISSUE THREAD

**Issue by lorenzoponsb** [tomchristie/django-rest-framework#4664]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
On PUT method:
```python
{
    "name": "lamborghini",
    "price": {
        "pk": 1,
        "price": 3.0
    }
}
```
Models
```python
class Vehicle(models.Model):
    name = models.CharField(max_length=300)

class Sale(models.Model):
    vehicle = models.OneToOneField(Vehicle, related_name="sale", primary_key=True)
    price = models.FloatField()
```
Serializers:
```python
class SaleSerializer(serializers.ModelSerializer):
    class Meta:
        model= Sale
        fields =('pk','price',)

class VehicleSerializer(serializers.ModelSerializer):
    price = SaleSerializer(source='sale')
    class Meta:
        validators = []
    def validate(self, attrs):
        ...
```
## Expected behavior
Call validate method on VehicleSerializer

## Actual behavior
```python
{
  "price": {
    "pk": [
      "sale with this vehicle already exists."
    ]
  }
}
```

**Comment by xordoquy** [comment]
There's no point in calling a global validation when the fields themselves aren't valid
