### ISSUE TITLE
Question/Advise on many-to-many with through

### ISSUE THREAD

**Issue by jole78** [tomchristie/django-rest-framework#4673]
Tried posting this on the google discussion list but didn't get any answers so trying here instead...

I have a model like this:

```python
class Report(models.Model):
....
	incident_categories = models.ManyToManyField(IncidentCategory, through='IncidentCategoryMembership')

class IncidentCategory(models.Model):
...some properties here

class IncidentCategoryMembership(models.Model):
	report=models.ForeignKey(Report, on_delete=models.CASCADE)
	incident_category=models.ForeignKey(IncidentCategory, on_delete=models.CASCADE)
	comment=models.CharField(max_length=600)
```
This is all mapped in a viewset (for Report) that supports POST, PUT, GET....
The update and create works fine for the nested relationship Report > IncidentCategoryMembership > IncidentCategory
...basically I can create/update a report that has one or many categories with a comment...

However I get a problem when I request a report and want it to return me a report like this 

{
  id:1, 
  ....some other props , 
  incident_categories:
[
   {
     incident_category:1, 
     comment:'some comment'
   }, 
     ...more of the same
]
}

I get this error: 'IncidentCategory' object has no attribute 'incident_category'

serializers....

```python
class ReportSerializer(serializers.ModelSerializer):
	created_by = serializers.PrimaryKeyRelatedField(read_only=True, default=serializers.CurrentUserDefault())
	incident_categories = IncidentCategoryMembershipSerializer(many=True)

	class Meta:
		model = Report
		read_only_fields = ('state',)
		exclude = (...some excluded fields here)

class IncidentCategoryMembershipSerializer(serializers.ModelSerializer):
	incident_category = serializers.PrimaryKeyRelatedField(read_only=True)

	class Meta:
		model = IncidentCategoryMembership
		fields = ('incident_category', 'comment')
```

I must be missing something obvious here right?
However, I couldn't find any real solid advise/docs on many-to-many with a through/intermediate model anywhere really though...could that perhaps be added to the otherwise excellent docs?

**Comment by rpkilby** [comment]
You're operating on the wrong table. `incident_categories` returns `IncidentCategory`s, not `IncidentCategoryMembership`s. You need to access the through table instead by doing something like the below. Notice the additional `source` argument.

```py
class ReportSerializer(serializers.ModelSerializer):
	created_by = serializers.PrimaryKeyRelatedField(read_only=True, default=serializers.CurrentUserDefault())
	incident_categories = IncidentCategoryMembershipSerializer(many=True, source='incidentcategorymembership_set')
```

**Comment by jole78** [comment]
@rpkilby aaaahhhh...thanks man how did I ever miss that! Now it works of course.
