### ISSUE TITLE
Serializers output pk=None for created objects

### ISSUE THREAD

**Issue by FalFire** [tomchristie/django-rest-framework#4677]
When setting the pk field (id in my case) as a read_only_field on a serializer (subclass of ModelSerializer) used for creating objects, the outputted id is always None when used in combination with viewsets. Why is this? I am able to circumvent this issue by overwriting the create method on the viewset to query the just created object when it has some other field that is unique, however when the pk field is the only unique field this is not possible. I am using Django 1.9 with REST 3.4.0.

My current workaround when there is another unique field:
```
def create(self, request, *args, **kwargs):
        """Custom create method which outputs the ID of the created object correctly in the Response"""

        # Taken from CreateModelMixin implementation
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)

        # Query DB for created object, set correct ID in response data
        data = serializer.data
        data['myobject']['id'] = MyObject.objects.get(uniqueField=data['myobject']['uniqueField']).id
        return Response(data, status=status.HTTP_201_CREATED, headers=headers)
```

**Comment by tomchristie** [comment]
> When setting the pk field (id in my case) as a read_only_field on a serializer (subclass of ModelSerializer) used for creating objects, the outputted id is always None when used in combination with viewsets.

If you can give us a minimal replicable example we can look into the issue. Best thing would be to attempt to demonstrate it as a failing test case. If we don't have an example that we can replicate the issue from there's not a lot we can do.
