### ISSUE TITLE
RequestClient does not allow for client side SSL certificates to be used

### ISSUE THREAD

**Issue by IainColledge** [tomchristie/django-rest-framework#4684]
RequestsClient() should make use of the session.cert parameter as per the requests module and Session class it inherits from.

This is for example when using SSL with a client side certificate + unencrypted key to identify the client.

## Steps to reproduce

Using requests directly:

        cert = (cert_path,key_path)
        session = requests.Session()
        session.cert = cert
        response = session.get(url=url+"apilistresponse/")

Results in code working as expected, using RequestClient():

        cert = (cert_path,key_path)
        client = RequestsClient()
        client.cert = cert
        response = client.get(url=url+"apilistresponse/")

Results in the server stating "Authentication credentials were not provided.", the cert is not being sent.

## Expected behavior

Both requests.Session() and RequestsClient should be able to have the cert parameter set and used for connections.

## Actual behavior

RequestsClient can have the parameter set but does not make use of the parameter and send the cert.

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by tomchristie** [comment]
Gotcha - thanks for the clearly outlined issue.

**Comment by tomchristie** [comment]
Any obvious way of pulling together a test case for this?

**Comment by IainColledge** [comment]
Tom, you're welcome and thanks for your awesome DRF, only a few weeks into Django and this and blown away by how easy to do things, anyway enough of me being a star struck fan!!! :)

This is a bit of a post integration test and I'm using TeamCity + Ansible to Unit Test, Integration Test and then building a docker Image beforehand and have the following setup:

Client (Client Cert and Key) <--> Nginx Reverse Proxy (Valid SSL Server cert, key and CA cert) <--> DRF running in Docker

The reverse proxy basically SSL offloads and validates the client certificate, so if Django can present itself as an SSL Server with its built in web server then that makes it simple to have the infrastructure in place. Sorry am still learning Django and DRF so haven't explored if it can or not as no need. If the requests module is happy with self signed certs then that means a valid one doesn't have to be procured.

In terms of certs and keys I can mint some which should only ever be used for this test as they will be available to the world.

In terms of resolving will have a look through the code but if you're overiding anything when making a connection then that may be what is causing it. Still learning Python 3 so may take a while, some pointers would be good! :)

**Comment by IainColledge** [comment]
Looking at this it would seem that the request loops through the built in dev server which does not support SSL, hence the certs would not get sent as no SSL protocol.

The solution is to use something like Django SSL Server or nginx etc and then use a real client for the test that makes a real https connection rather than loop internally.

Will close this as isn't a bug, might be worth making a note in the docs about testing SSL?

**Comment by tomchristie** [comment]
> Looking at this it would seem that the request loops through the built in dev server which does not support SSL, hence the certs would not get sent as no SSL protocol.

That sounds exactly right to me, yup. I'd probably suggest if you want to test SSL then you may as well simply do so against the live and/or staging environment only in any case. Testing the certs is one thing, testing that the environment really is correctly configured is what you really want.

**Comment by IainColledge** [comment]
That's what I've now done, sorry for raising it as a bug, had wrong expectations for the test client.

**Comment by tomchristie** [comment]
No worries at all, still useful to talk through.
