### ISSUE TITLE
OneToOneField raise exception in related lookup 

### ISSUE THREAD

**Issue by kelly-apollo** [tomchristie/django-rest-framework#4687]
## Steps to reproduce

```python
from django.contrib.auth.models import User

class UserProfile(models.Model):
    name = models.CharField(max_length=64)
    user = models.OneToOneField(User)

class DeveloperViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    search_fields = ['userprofile__name', 'email']
```

## Expected behavior

> You can also perform a related lookup on a ForeignKey or ManyToManyField with the lookup API double-underscore notation:
http://www.django-rest-framework.org/api-guide/filtering/#searchfilter

`OneToOneField` should work like `ForeignKey` as a related relationship.

## Actual behavior

Raise `Cannot resolve keyword "userprofile"` exceptions.

**Comment by rpkilby** [comment]
Hi @kelly-apollo - The exception sounds like Django's internal field resolution is failing to recognize the field. My guess is that the model hasn't been properly registered or something. Do you get the same traceback with the following?

```py
User._meta.get_field('userprofile')
```

**Comment by kelly-apollo** [comment]
@rpkilby  django field resolution works.
```
>>> User._meta.get_field('userprofile')
<OneToOneRel: database.userprofile>
```

**Comment by kelly-apollo** [comment]
Because the app_label of `UserProfile` is not in the INSTALLED_APP.
