### ISSUE TITLE
API guide for serializers is outdated

### ISSUE THREAD

**Issue by wimglenn** [tomchristie/django-rest-framework#4706]
The latest docs have an outdated chunk mentioning 

> A new interface for controlling this behavior is currently planned for REST framework 3.1.

http://django-rest-framework.readthedocs.io/en/latest/api-guide/serializers/#customizing-the-default-fields 

Since we're well past 3.1, it should be updated to document the current interfaces.

**Comment by xordoquy** [comment]
django-rest-framework.readthedocs.io isn't the official documentation.

**Comment by xordoquy** [comment]
But it's still on the official doc.

**Comment by wimglenn** [comment]
Readthedocs watches github for any commits, so it should always be up to date with current, right? It's currently saying 3.5.3...

**Comment by xordoquy** [comment]
Closed by #4909
