### ISSUE TITLE
Filtering against current user and DjangoModelPermissions/DjangoObjectPermissions

### ISSUE THREAD

**Issue by fabien-michel** [tomchristie/django-rest-framework#4720]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. A ModelViewSet using DjangoModelPermissions or DjangoObjectPermissions permission class.
2. This model must override get_queryset method which must use self.request.user.something
3. DO NOT authenticate any user
3. Do a GET request on the ViewSet

## Expected behavior

Check that the user is authenticated and has the permission to GET on the ViewSet

## Actual behavior

Raise an AttributeError: 'AnonymousUser' object has no attribute 'something'

The problem is in DjangoModelPermissions.has_permission method
This method call the get_queryset method of the view if defined in order to fetch the model.
However as the user isn't authenticated, in the get_queryset method, self.request.user if an AnonymousUser object which don't implement "something" attribute

I think the has_permission method should check for user authentication before calling the get_queryset method.

**Comment by xordoquy** [comment]
I don't see any issue with drf here. It's up to the developer to ensure anonymous user can perform the get_queryset. It will be called anyway once the permissions are passed

**Comment by fabien-michel** [comment]
It won't be called after because the user isn't authenticated. At the end of DjangoModelPermissions.has_permission method it check `is_authenticated(request.user)`
I just suggest to check for user for authentication before calling get_queryset then perform `has_perm` check.
Futhermore, [the documentation](http://www.django-rest-framework.org/api-guide/filtering/#filtering-against-the-current-user) suggest to override get_queryset to filtering against current user.

**Comment by xordoquy** [comment]
The check is only taken into account if `authenticated_users_only` is False (default).
If `get_queryset` can not handle anonymous user, I suggest you add a `IsAuthenticated` permission before.

**Comment by fabien-michel** [comment]
Here is the modification I suggest : 
It avoid a useless call to get_queryset, do not change the expected behavior and avoid developers to add IsAuthenticated permission class (as it sound redundant because DjangoModelFramework should already do that)

```pyhon

    def has_permission(self, request, view):
        # Workaround to ensure DjangoModelPermissions are not applied
        # to the root view when using DefaultRouter.
        if getattr(view, '_ignore_model_permissions', False):
            return True

        if not request.user or (self.authenticated_users_only and not is_authenticated(request.user)):
            return False

        if hasattr(view, 'get_queryset'):
            queryset = view.get_queryset()
        else:
            queryset = getattr(view, 'queryset', None)

        assert queryset is not None, (
            'Cannot apply DjangoModelPermissions on a view that '
            'does not set `.queryset` or have a `.get_queryset()` method.'
        )

        perms = self.get_required_permissions(request.method, queryset.model)

        return request.user.has_perms(perms)
```

**Comment by tomchristie** [comment]
Check for `is_authenticated` in the `get_queryset` if you must do this.
An alternative backend *might* allow unauthenticated users some access, so it's not 100% clear that the change would work ok for everyone.

**Comment by fabien-michel** [comment]
I disagree because the conditions for checking user and his authentication state are made anyway. (with or without a call to get_queryset)
The early return I propose just avoid this call if not needed and makes the thing clearer because we expect by using DjangoModelPermission that an unauthenticated used should be always denied and so request.user should always be an authenticated user...
I hope that you understand me, I will not persist on it anymore.

**Comment by tomchristie** [comment]
I could be convinced by this, happy to hear comments from anyone else?
A pull request implementing it would be a good start, as that'd help demonstrate any obvious issues.

**Comment by xordoquy** [comment]
> An alternative backend might allow unauthenticated users some access

In which case, we'll blame the developer again for not making sure the `get_queryset` is safe against `AnonymousUser` and said developer will blame legacy developers for that.

In the current case, other backends will not be queried because the test for authentication will stop it anyway.

I'm standing ground about the fact that `get_queryset` should not fail on `AnonymousUser`. However I don't see any reason this would change anything except it'll rely on luck to work.
