### ISSUE TITLE
KeyError: 'Class UUID not found in lookup.'

### ISSUE THREAD

**Issue by ptcarino** [tomchristie/django-rest-framework#4728]
I'm currently working on a project that uses **django_cassandra_engine** and this package. Whenever I try to visit the json url I've set, django throws the error `KeyError: 'Class UUID not found in lookup.'`

I'm guessing because in my models, I'm using `from cassandra.cqlengine import columns` instead of `from django.db import models`. The UUID for cqlengine is just UUID while in django.db it's UUIDField.

Any work around for this?

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by ptcarino** [comment]
Just so anyone has the same problem, I was using ModelSerializer here and the names of django.db's field types do not match with cassandra.cqlengine thus the error.

What I did to solve this was use **Serializer** and specify the appropriate field type equivalents on each column.
