### ISSUE TITLE
Viewset breadcrumbs missing suffix

### ISSUE THREAD

**Issue by tuxredux** [tomchristie/django-rest-framework#4729]
If I have a `UserViewSet` that subclasses the `ModelViewSet`,  the breadcrumb for a User Instance (Detail) page is `Api Root > User > User` instead of the expected `Api Root > User List > User Instance`. I'm not sure if this is expected behavior, but I would argue against it if so. Thanks in advance for your time.

**Comment by pevzi** [comment]
`git bisect` revealed that this was introduced in #3273.

**Comment by tomchristie** [comment]
Thanks @pevzi.

**Comment by mmedal** [comment]
#3273 removes the `view.suffix` that gets passed along to `api_settings.VIEW_NAME_FUNCTION` in favor of always calling `cls().get_view_name`. As such, the way `APIView.get_view_name` is implemented makes this a little tricky. #4750 fixes this issue with minimal impact, although, it's not an ideal solution.
