### ISSUE TITLE
'is_valid' return Null data at Writable Nested ModelSerializer 

### ISSUE THREAD

**Issue by HyunSol** [tomchristie/django-rest-framework#4739]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.   
Yes I tested with the same version as the master, and I have identified the same problematic code.    
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
class CommentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Comment
        fields = ('pk', 'comment', 'created_date')

class PhotoSerializer(serializers.ModelSerializer):
    class Meta:
        model = Photo
        fields = ('pk', 'photo')

class PostSerializer(serializers.ModelSerializer):
    photos = PhotoSerializer(many=True, source='photo_set')
    comment = CommentSerializer(many=True, source='comment_set')

    class Meta:
        model = Post
        fields = ('content', 'photos', 'comment')

    def create(self, validated_data):
          . . . . .
```

## Expected behavior

validated_data is {'content': 'validated_value', 'photo_set': 'validated_value', 'comment_set': 'validated_value'}

## Actual behavior

validated_data {'content': 'validated_value', 'photo_set': [], 'comment_set': []}

**Comment by HyunSol** [comment]
#4739

**Comment by xordoquy** [comment]
This is usually the sign that you don't send the data with proper content type - i.e., you're likely sending form encoded data while nested serializers expects JSON or similar.

**Comment by HyunSol** [comment]
Umm.. Plz Listen to me

I send the data with proper content type
But .. In my think ..
In this case the '_writable_fields Method' (in serializers.py) works incorrectly.

**Comment by xordoquy** [comment]
If you think there's a bug in DRF, the best way would be to provide the simplest isolated and failing test case so we can reproduce.

**Comment by HyunSol** [comment]
falling test case를 어떻게 보내?
당신이 가장 원하는 방법이 있다면,
내가 그대로 하겠다.

그리고 나는 이 문제에 대해서 내 나름 해결책도 찾아보았다.

나는 '_writable_fields Method'(in serializers.py)이 self가 fields인 경우와 serializer인 경우를 다르게 행동하는 방법으로 바꾸어보았다.

나는 모든 것을 당신에게 제공하고 싶다.(failing test case와 my  solution)

**Comment by xordoquy** [comment]
First, you need to make sure that request.data has the data. Override some part of the view and print it.
If it has the nested data, then starting a new project that demonstrate the issue is a good way we can make sure it's isolated from the other parts of your code.

**Comment by HyunSol** [comment]
Here request.data

 <QueryDict: {'content': ['content-type str'], 'comment': ['first comment', 'second comment'], 'photo': [<InMemoryUploadedFile: sample1.png (image/png)>, <InMemoryUploadedFile: sample2.jpg (image/jpeg)>]}>

**Comment by HyunSol** [comment]
https://github.com/HyunSol/DRF-falling-case

![2016-12-05 9 02 16](https://cloud.githubusercontent.com/assets/22088047/20884367/3901d280-bb2e-11e6-9c69-9fa872ab3f35.png)

**Comment by tomchristie** [comment]
The screenshot seems to indicate that you're sending the request with form encoded data, rather than JSON. (form encoded data can't support nested data)

**Comment by xordoquy** [comment]
> <QueryDict: {'content': ['content-type str'], 'comment': ['first comment', 'second comment'], 'photo': [<InMemoryUploadedFile: sample1.png (image/png)>, <InMemoryUploadedFile: sample2.jpg (image/jpeg)>]}>

comment & photo aren't nested here although representing relational data.
You should read the [relational part](http://www.django-rest-framework.org/api-guide/relations/) of the documentation
