### ISSUE TITLE
RequestsClient documentation cut in the middle of sentence

### ISSUE THREAD

**Issue by jokimies** [tomchristie/django-rest-framework#4747]
I was looking for a way to write  tests against live server. In DRF docs there's a page about live testing, but it appears the the section describing RequestsClient() and working with databases ends abruptly.

## Steps to reproduce
Go to http://www.django-rest-framework.org/api-guide/testing/#requestsclient-and-working-with-the-database

## Expected behavior
It would be good see how the sentence and entire section ends

## Actual behavior
Section ends in the middle of sentence '...class is useful if'
It looks like something is missing from that section.

**Comment by jpadilla** [comment]
Good catch.

@tomchristie any chance you still remember what you were writing in https://github.com/tomchristie/django-rest-framework/commit/24791cb353d1924086b30abe2188280547d9a6c4#diff-3e991bb361d29d646894e3560f866e6dR208 ?

**Comment by tomchristie** [comment]
Thanks both - updated now.
