### ISSUE TITLE
Error when parser_context is none when using MultiPartParser

### ISSUE THREAD

**Issue by patrick91** [tomchristie/django-rest-framework#4754]
Hi, I was having a look at the code, and found something that might be a bug.
In `MultiPartParser`'s parse method there is a named parameter `parser_context` set to None by default.

When this parameter is set to None it will be set to an empty dict, but in the next we try to access the `request` key from it, but this throws an (non helpful) error, since the dict is empty (in this case).

If the request in the parser_context is required maybe we should make it explicit? 

```python
class MultiPartParser(BaseParser):
     # [snip...]    

    def parse(self, stream, media_type=None, parser_context=None):
       # [snip...]    

       parser_context = parser_context or {}
       request = parser_context['request']

       # [snip...]    
```

Here the link to the code for a better reference:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/parsers.py#L102

**Comment by tomchristie** [comment]
Looks like we could have better error handling there, yup.

**Comment by tomchristie** [comment]
Would accept PRs that raise an explicit error in this case, but otherwise not concerned enough about the current behavior to treat this as requiring action. (Since the behavior is still reasonable enough as it stands)
