### ISSUE TITLE
'Content-Type' header is deleted from Response after object deletion

### ISSUE THREAD

**Issue by roboslone** [tomchristie/django-rest-framework#4767]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Write a simple serializer and view for an existing model:
```python
#
# models.py
#
class Tag(Model):
    text = CharField(max_length=1023, unique=True, db_index=True)

#
# serializers.py
#
class TagSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tag
        fields = ('id', 'text')

#
# views.py
#
class TagDetail(generics.RetrieveUpdateDestroyAPIView, DjangoPermissionsMixin):
    queryset = Tag.objects.all()
    serializer_class = serializers.TagSerializer
```
2. Write middleware, that logs response object:
```python
#
# middleware.py
#
class LoggingMiddleware(object):
    def process_response(self, request, response):
        logging.warning(response)
        return response
```
3. Try to delete existing object: `DELETE https://example.com/api/tag/1234`

## Expected behavior
- object is deleted
- response object is logged
- response with no content returned, status is HTTP204

## Actual behavior
- object is deleted (indeed)
- response object is not logged, due to `KeyError`
- response with html content returned, status is HTTP500 (Django intercepted the exception)

I tried to log `response._headers` and noticed, that `content_type` is removed somewhere during request processing:
```python
# No 'content_type' key here.
{'allow': ('Allow', 'GET, PUT, PATCH, DELETE, HEAD, OPTIONS'), 'vary': ('Vary', 'Accept, Cookie'), ... }
```
This doesn't happen during `GET` or `POST` requests.

`KeyError` is raised in Django's `Response.__repr__`:
```python
class HttpResponse(HttpResponseBase):
   ...

   def __repr__(self):
       return '<%(cls)s status_code=%(status_code)d, "%(content_type)s">' % {
           'cls': self.__class__.__name__,
           'status_code': self.status_code,
           'content_type': self['Content-Type'],  # <- there's our KeyError
       }
```

**Comment by roboslone** [comment]
I believe this is breaking Django's `HttpResponse`:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/response.py#L81
```python
class Response(SimpleTemplateResponse):
    ...
    @property
    def rendered_content(self):
        ...
        ret = renderer.render(self.data, accepted_media_type, context)
        if isinstance(ret, six.text_type):
            assert charset, (
                'renderer returned unicode, and did not specify '
                'a charset value.'
            )
            return bytes(ret.encode(charset))

        if not ret:
            del self['Content-Type']  # <---
        ...
```

Why is that header removed completely? Wouldn't it be better to set it to `None` or don't touch it at all? I believe it would be `None` if not touched and I'm not sure how Django will react to this. So maybe it would be better to set it to `request.content_type` in `DestroyModelMixin`:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/mixins.py#L94
```python
class DestroyModelMixin(object):
    """
    Destroy a model instance.
    """
    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return Response(status=status.HTTP_204_NO_CONTENT, content_type=request.content_type)
```

**Comment by roboslone** [comment]
Well, I've fixed it locally by subclassing `Response` and `DestroyModelMixin`:
```python
class FixedResponse(Response):
    @property
    def rendered_content(self):
        renderer = getattr(self, 'accepted_renderer', None)
        accepted_media_type = getattr(self, 'accepted_media_type', None)
        context = getattr(self, 'renderer_context', None)

        assert renderer, ".accepted_renderer not set on Response"
        assert accepted_media_type, ".accepted_media_type not set on Response"
        assert context is not None, ".renderer_context not set on Response"
        context['response'] = self

        media_type = renderer.media_type
        charset = renderer.charset
        content_type = self.content_type

        if content_type is None and charset is not None:
            content_type = "{0}; charset={1}".format(media_type, charset)
        elif content_type is None:
            content_type = media_type
        self['Content-Type'] = content_type

        ret = renderer.render(self.data, accepted_media_type, context)
        if isinstance(ret, six.text_type):
            assert charset, (
                'renderer returned unicode, and did not specify '
                'a charset value.'
            )
            return bytes(ret.encode(charset))

        return ret


# noinspection PyUnresolvedReferences,PyUnusedLocal
class FixedDestroyModelMixin(mixins.DestroyModelMixin):
    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return FixedResponse(status=status.HTTP_204_NO_CONTENT, content_type=request.content_type)


class FixedRetrieveUpdateDestroyAPIView(mixins.RetrieveModelMixin, mixins.UpdateModelMixin, FixedDestroyModelMixin,
                                        generics.GenericAPIView):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.get = self.retrieve
        self.put = self.update
        self.patch = self.partial_update
        self.delete = self.destroy

class TagDetail(FixedRetrieveUpdateDestroyAPIView):
    queryset = Tag.objects.all()
    serializer_class = serializers.TagSerializer
```

Works like a charm, response content is empty, status is HTTP204 and `Content-Type` header matches same header in request. If no `Content-Type` header was set on request, response's `Content-Type` is set to `text/plain`.

**Comment by roboslone** [comment]
Just checked setting `self['Content-Type']` to `None` in `Response.rendered_content`. `None` is converted to string and `Content-Type: None` header is returned. It doesn't seem good to me, so basically deleting those line will fix the issue:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/response.py#L80-L82

**Comment by roboslone** [comment]
Checked blame on `response.py`, seems like deleting `Content-Type` header breaks WSGI (#1196). I'm not sure if that issue is still relevant, though.
I think this header removal could be optional, just not sure how to implement it yet...

**Comment by roboslone** [comment]
There's also a ticket on djangoproject concerning issue with `Response.__repr__`. It may be more appropriate to fix Django code instead of DRF's.

**Comment by adamchainz** [comment]
I agree that fixing in Django is the most appropriate course of action, and until that is done such code paths that log responses should just `try / except` around `repr`'ing responses.

**Comment by tomchristie** [comment]
Our current behaviour (Remove Content-Type header when there's no content) is correct. Let's fix Django's repr instead.
