### ISSUE TITLE
Why is the 'get_authorization_header' function outside of 'class BaseAuthentication' and 'class TokenAuthentication'?

### ISSUE THREAD

**Issue by HyunSol** [tomchristie/django-rest-framework#4775]
Why is 'get_authorization_header' in 'authentication.py' a function, not a method of 'class BaseAuthentication' and 'class TokenAuthentication'?

A problem has occurred in some applications.

It works fine in other views, but in certain views
'Request.meta' does not include 'HTTP_AUTHORIZATION'.
(Of course, 'WSGIPassAuthorization on' is set.)

I do not know the exact cause yet, but this is probably a client issue.

I had to solve the problem by using HTTP_X_AUTHORIZATION instead of HTTP_AUTHORIZATION.

Is it impossible to change the class to be able to call the 'self.get_authorization_header' method in the class?

**Comment by xordoquy** [comment]
Sounds like a good option to move the function in the the `BaseAuthentication`.

**Comment by tomchristie** [comment]
Users really shouldn't need to override this particular aspect, so I'm not especially minded to move this from a plain function into a method.

**Comment by HyunSol** [comment]
Thank you for your answer.
I will look for a better way without overriding it.

**Comment by kevin-brown** [comment]
> I had to solve the problem by using HTTP_X_AUTHORIZATION instead of HTTP_AUTHORIZATION.

It sounds like your client is passing in the authorization through the `X-Authorization` header (not correct, but also not invalid) instead of the `Authorization` header (which is the standard).

**Comment by HyunSol** [comment]
Initially, I requested through `Authorization`.

However, there was no token in request.META in any particular view.

The cause is not yet known.

I used `x-authorization` to solve it later.

To solve this problem, the article is not written.
Because it is assumed to be a client(IOS app) problem.

I just wondered why `get_authorization_header` should be a function.
