### ISSUE TITLE
Serializer Field Source Not Respected

### ISSUE THREAD

**Issue by mattpetrick** [tomchristie/django-rest-framework#4784]
it does not appear that the source property is being respected on deserialization.

`
def test_serializer(self):
        from rest_framework import serializers

        class TestSerializer(serializers.Serializer):
            better_named = serializers.CharField(source='PoorlyNamed')
            better_named_child = serializers.CharField(source='Child.MorePoorlyNamed')

        payload = {
            "PoorlyNamed": "abc123",
            "Child": {
                "MorePoorlyNamed": "def456"
            }
        }

        serializer = TestSerializer(data=payload)
        is_valid = serializer.is_valid()
        print serializer.errors
        self.assertTrue(is_valid)
`

console output:
{'better_named': [u'This field is required.'], 'better_named_child': [u'This field is required.']}

**Comment by kevin-brown** [comment]
The `source` specifies the field on the instance that will be used when populating that serializer field. This means that if you want to serialize an instance which had the field `PoorlyName`, it would be serialized as `better_named`. And when you are validating incoming data, it would map `better_named` back to `PoorlyNamed` when the data is validated.

You appear to be reversing that.

---

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
