### ISSUE TITLE
Road map to drop support of python 2.x

### ISSUE THREAD

**Issue by auvipy** [tomchristie/django-rest-framework#4799]
django is going to drop 2.x after 1.11 branch cut. how should drf approach to that?

 A version 4.0.0 based on django 2.0+ based on py3 only?

**Comment by xordoquy** [comment]
Drf aligns itself on Django's supported versions.
Not sure whether it'll be a major release or not, will depend on how much our API evolves around that time

**Comment by tomchristie** [comment]
Python 2+3 support isn't costing us an awful lot of effort at the moment, so we'll see.
I expect the next version to come out after Django 1.11 will probably also drop Python 2 support, but I don't particularly expect us to jump to a 4.0 version number.

**Comment by rpkilby** [comment]
> I expect the next version to come out after Django 1.11 will probably also drop Python 2 support

This is what's indicated by the roadmap on the [download](https://www.djangoproject.com/download/) page. Given that 1.11 is also the next LTS release, that means that Django supports python 2 right up until April of 2020.

**Comment by tomchristie** [comment]
Oops I miswrote that. I meant to write...

I expect the next version *(of Django REST framework)* to come out after Django *2.0* will probably also drop Python 2 support.

(Emphasis on my errors)

**Comment by tomchristie** [comment]
I don't think we particularly need an open ticket to track this.
We'll look at it once Django drops 2.7 support.
