### ISSUE TITLE
dispatch() swallows exception traceback

### ISSUE THREAD

**Issue by alfalfasprossen** [tomchristie/django-rest-framework#4809]
If an exception occurs in code that is being called through the rest api, the exceptions original traceback and line number are swallowed since the exception is re-raised at a different location. At least that is what I understand why the problem exists. It may be Python 2.x only.

Example traceback:
```
Traceback (most recent call last):
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\dev\test\test\helpers.py", line 127, in decorator
    return func(*args, **kwargs)
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\rest_framework\views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\jbecker\.virtualenvs\test\lib\site-packages\rest_framework\views.py", line 448, in raise_uncaught_exception
    raise exc
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

The location and cause of the `TypeError` is nowhere to be seen. All traceback listings are internal calls of django and the rest_framework.

What we did now is to explicitly print the traceback in `dispatch()` before the exception is handed to the exception handler, where it is possibly re-raised with a wrong traceback:

```
def dispatch(self, request, *args, **kwargs):
        """
        `.dispatch()` is pretty much the same as Django's regular dispatch,
        but with extra hooks for startup, finalize, and exception handling.
        """
        self.args = args
        self.kwargs = kwargs
        request = self.initialize_request(request, *args, **kwargs)
        self.request = request
        self.headers = self.default_response_headers  # deprecate?

        try:
            self.initial(request, *args, **kwargs)

            # Get the appropriate handler method
            if request.method.lower() in self.http_method_names:
                handler = getattr(self, request.method.lower(),
                                  self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            response = handler(request, *args, **kwargs)

        except Exception as exc:
            import traceback
            traceback.print_exc()  # Actual exception traceback here.
            response = self.handle_exception(exc)
...
```

I understand from other sources on the web, that this may be handled differently in Python 3, and that the original traceback of the re-raised exception is correct. Using the rest_framework with Python 2.x though makes this a real pain when trying to debug code errors that only happen when certain input or so is provided through the rest api.

**Comment by jdotjdot** [comment]
We have this same issue and it's made it extremely difficult to debug some errors, since the actual line causing the error gets swallowed up and only Rest Framework library lines are sent to our bugtrackers.

Is there another place that we could manually instrument to send the correct (original) traceback to our exception tracking tools?

**Comment by xordoquy** [comment]
It's likely oneneeds to inject the traceback into te exception. PR welcomed

**Comment by kevin-brown** [comment]
I believe that six supports reraising exceptions with the `six.reraise()` function.

https://pythonhosted.org/six/#six.reraise

**Comment by jdotjdot** [comment]
The issue though as I understand it is that DRF needs to catch the
exception and return a valid JSON response, and _separately_ send the trace
back to loggers.  Simply relying on the reraising of the traceback would
result in a 500 being returned to the client, unless somehow Django
channels or something similar was used--and I'm not even sure that would
work.

**Comment by kevin-brown** [comment]
@jdotjdot DRF actually has built-in exception handling, and you can override it to handle uncaught errors as well as implement your own exception logging.

http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

This ticket is about exceptions which pass though the exception handler (so, unhandled exceptions) and how the traceback on them is being thrown away.

**Comment by jdotjdot** [comment]
That is actually what I'm talking about as well.  It seems I assumed
incorrectly that DRF catches all exceptions-- which thinking to what I see
in my error logger, makes sense to not be the case.

**Comment by xordoquy** [comment]
Anyway, I'd be happy to review if anyone can come with a PR on the initial issue

**Comment by tomchristie** [comment]
Happy to consider any actionable tweaks to our current behavior. Not clear that we have one against this ticket right now, or what it would be.

**Comment by jdotjdot** [comment]
@tomchristie it would likely be adding a hook into the `Response` cycle for plugins to send original tracebacks to the regular Django error mail, Sentry, Opbeat, or other services.

This would be highly valuable since right now I have zero insight into bugs that occur within API calls because I lose the whole traceback.

**Comment by rpkilby** [comment]
@jdotjdot - are you also on python 2.x, or are you experiencing this on python 3.x?

**Comment by jdotjdot** [comment]
2.X.  We'll have to move to Python 3 with Django 2.0, though.

**Comment by tomchristie** [comment]
If there's some *other* way of re-raising the exception that more correctly preserves the stack info, then we can consider that, but esp given the py3 situation works as expected (right?) that's not something that I want to spend time trying to figure out myself. Happy to consider PRs tho.
