### ISSUE TITLE
ImportError: cannot import name MergeDict

### ISSUE THREAD

**Issue by sohamnavadiya** [tomchristie/django-rest-framework#4814]
I am trying to update django 1.7 to 1.9.12.
After updating django I am getting below error stack.

```
 File "/home/abc/Documents/venv/rest_api/api/all_utils/goal_utils.py", line 3, in <module>
    from rest_framework.request import MergeDict
ImportError: cannot import name MergeDict

```

I have installed **djangorestframework==3.5.3**.

How can I solve this error?
Thanks in advance.

**Comment by grapherd** [comment]
@sohamnavadiya , I found that in django rest framework 3.1.1 release note, it remove MergeDict.

You can see it at #2640, since Django remove MergeDict in 1.9 version.

**Comment by jpadilla** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Yup @grapherd is right.
