### ISSUE TITLE
MultipleFieldLookupMixin with ReadOnlyModelViewSet not working

### ISSUE THREAD

**Issue by Calion54** [tomchristie/django-rest-framework#4820]
Hello,

I would like two types of URL :
- /color_parts/test/ to list data object
- /api/color_parts/<pk1>/<pk2> to retrieve data object.

So, I created MultipleFieldLookupMixin as your tutorial, list working but retrieve not working.
It take juste one lookup_fild (pk) but I want two lookups_field.

class :
```
class ColorPartViewSet(MultipleFieldLookupMixin,
                       viewsets.ReadOnlyModelViewSet):
    queryset = ColorPart.objects.all()
    serializer_class = ColorPartWithNumberInSetSerializer
    lookup_fields = ('part__part', 'color__color',)
```

rooter :
`router.register(r'api/color_parts', ColorPartViewSet, 'color_parts')
`

Thank you in advance.

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
