### ISSUE TITLE
Wrong Authorization Error Message

### ISSUE THREAD

**Issue by mr-karan** [tomchristie/django-rest-framework#4826]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Send a GET request with a wrong Access Token, having permission settings as `rest_framework.permissions.IsAuthenticated`

## Expected behavior

Error message should be like "Authentication credential provided is Invalid" or "Invalid Access Token" or something like that.

## Actual behavior

Error message says "Authentication credentials were not provided."

**Comment by xordoquy** [comment]
You probably have a typo in the token name which means the auth can't find it and it results in a "Authentication credentials were not provided." where it might have been "Invalid token."

Without a test case to show case the issue it's a bit of a guesswork.

Also note that you can override the default authentication to make sure it returns an error if no token is found.

**Comment by mr-karan** [comment]
@xordoquy Okay, thanks. I've looked around but I am unable to find how to override this message. Any clues on it would be great?

**Comment by elcolie** [comment]
@mr-karan I guess you are using `FBV` with decorator. 
If I am correct. Here you can follow my solution in the latest comment.
https://github.com/encode/django-rest-framework/issues/5776
