### ISSUE TITLE
DateField accepts empty string but not None

### ISSUE THREAD

**Issue by markerdmann** [tomchristie/django-rest-framework#4835]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Add a DateField to the model with `null=True` and a DateField to the serializer with `required=False` and `allow_null=True`.
2. Send a POST with `self.client.post(url, data={'field_name': None})` using rest_framework.test.APITestCase.

## Expected behavior

A POST/PATCH that sets the value of the field to null should persist to the database as a null value and not return a validation error.

## Actual behavior

The API returns `{'field_name': ['Date has wrong format. Use one of these formats instead: YYYY[-MM[-DD]].']}` and an HTTP status code of 400.

Strangely, an empty string does not throw a validation error and persists to the database as a null value. A GET request then returns a null value instead of the empty string.

Would you agree that this behavior is a bug? If so, I'd be happy to write a test against master and submit a PR.

**Comment by xordoquy** [comment]
At first sight, it looks like a valid issue. Before submitting a PR to fix this, could you make a test case ?
One thing I'd like to make sure is that you're sending the data as JSON instead of forms which could explain why the empty string is treated as None.

**Comment by tomchristie** [comment]
Django's test client will use form encoding by default, so my suspicion is that this:

    self.client.post(url, data={'field_name': None})

is actually sending the literal string 'None'. Try either:

    self.client.post(url, data={'field_name': None}, format='json')

or:

    self.client.post(url, data={'field_name': ''})

Instead.

We could also consider if it's worth raising an issue against Django for if that's the case as it'd be nice if there was more intuitive behavior when passing non-string primitives to the test client. (Eg. either treat `None` as the empty string or raise an error)

If my hunch is wrong and using one of those alternatives *doesn't* resolve the issue then we can reopen this and reconsider.

**Comment by markerdmann** [comment]
Thanks Tom, that's very helpful! I didn't realize the API client was using form encoding by default.
