### ISSUE TITLE
Username shows instead of email

### ISSUE THREAD

**Issue by andela-mekwenugo** [tomchristie/django-rest-framework#4840]
<img width="847" alt="screen shot 2017-01-23 at 5 09 55 pm" src="https://cloud.githubusercontent.com/assets/9656531/22211859/d0224a42-e18e-11e6-9425-3c08bf98db40.png">

## Expected behavior
On the login page, Email should show rather than Username

## Actual behavior
Username shows instead of Email on the login page

**Comment by tomchristie** [comment]
To be more precise - whatever field the `USERNAME_FIELD` points at should be used. That might be 'username', or if you have a custom user model it might be 'email', (or something else)

Anyways, looks like a valid issue, yup.

**Comment by jpadilla** [comment]
@andela-mekwenugo if you want to put a PR together, fix should be pretty simple.

We should probably use `form.username.label` [here](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templates/rest_framework/login_base.html#L24). Django already [sets the label](https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L176) depending on `USERNAME_FIELD`.
