### ISSUE TITLE
Possible unnecessary get_queryset() call in get_filter_form method of BrowsableAPIRenderer

### ISSUE THREAD

**Issue by mjos** [tomchristie/django-rest-framework#4843]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I apologize if I get it wrong but if view attribute filter_backends is empty then elements list variable cannot be populated. However there is only check on the presence of filter_backends attribute not that it is not empty. Thus the view.get_queryset() is called unnecesarilly which can cause perfomance issues if get_queryset is not trivial.

**Comment by tomchristie** [comment]
If filter_backends is empty you still want the base queryset (you just don't want to filter it).
Possible that I've misunderstood the issue as raised, tho - do shout out if so.

**Comment by mjos** [comment]
Not exactly, if filter_backends is empty, the for loop is not run, elements will stay empty list and the function immediately returns, so the queryset is called unnecesarilly causing in my case another roundtrip to database (as a side effect). I admit, that it might be due to my poor implementation of get_queryset() but the call can be omitted anyways.

```python
        queryset = view.get_queryset()
        elements = []
        for backend in view.filter_backends:
            if hasattr(backend, 'to_html'):
                html = backend().to_html(request, queryset, view)
                if html:
                    elements.append(html)

        if not elements:
            return
```

**Comment by tomchristie** [comment]
Note that calling 'get_queryset' won't result in a DB call since that'd only occur at the point of evaluating a queryset.

**Comment by mjos** [comment]
@tomchristie Ok, I see. The problem I was encountering was due to my unfortunate implementation of pagination causing evaluating the queryset again at this point. Sorry for bothering you.

**Comment by tomchristie** [comment]
No worries :)
