### ISSUE TITLE
Duplicate Calling get_queryset() 

### ISSUE THREAD

**Issue by sohopro** [tomchristie/django-rest-framework#4847]
## Steps to reproduce
I override get_queryet() in views.py like this.

class GetArticles(generics.ListAPIView):
    serializer_class = ArticleSerializer
    filter_backends = (filters.OrderingFilter,)
    ordering_fields = ('updated',)
    ordering = ('-updated',)

    def get_queryset(self):
        #here is some code.
        return queryset

I used the django-debug-toolbar and found duplicated sqls.

Here is one:

/lib/python3.5/site-packages/rest_framework/views.py in dispatch(471)
  response = handler(request, *args, **kwargs)
/lib/python3.5/site-packages/rest_framework/generics.py in get(200)
  return self.list(request, *args, **kwargs)
/lib/python3.5/site-packages/rest_framework/mixins.py in list(40)
  queryset = self.filter_queryset(self.get_queryset())
/views.py in get_queryset(44)

another:

/lib/python3.5/site-packages/rest_framework/response.py in rendered_content(72)
  ret = renderer.render(self.data, accepted_media_type, context)
/lib/python3.5/site-packages/rest_framework/renderers.py in render(697)
  context = self.get_context(data, accepted_media_type, renderer_context)
/lib/python3.5/site-packages/rest_framework/renderers.py in get_context(674)
  'filter_form': self.get_filter_form(data, view, request),
/lib/python3.5/site-packages/rest_framework/renderers.py in get_filter_form(605)
  queryset = view.get_queryset()
/views.py in get_queryset(44)

## Expected behavior
get_queryset() should be called once.

## Actual behavior
get_queryset() is called multi-times.

**Comment by xordoquy** [comment]
This is expected with the BrowsableAPI as we need to QS for representation purposes.
As QS are lazy, they shouldn't be evaluated.
I'm closing this as we don't have much actionable content here. A test case that demonstrate the QS duplication would be a good starting point.

**Comment by sohopro** [comment]
Sorry, but What's meanQS?

**Comment by tomchristie** [comment]
QuerySet

**Comment by xordoquy** [comment]
Sorry, that stands for QuerySet.

**Comment by sohopro** [comment]
Is get_queryset() called multi-times OK?
It's waste of time and I increment access counter in get_queryset so one request counted two.

**Comment by xordoquy** [comment]
I don't see an issue here as queryset are lazy and I don't think it's evaluated in the order form display part. On the other hand, it's the authoritative source to get the associated model and its fields thus the call from the ordering form display in the renderer.

**Comment by tomchristie** [comment]
> Is get_queryset() called multi-times OK?

Certainly in the browsable API yes. We could consider pull requests on merit, but not esp interested in addressing this otherwise.
