### ISSUE TITLE
Auto-fill json post form with default template for browsable api

### ISSUE THREAD

**Issue by youneschaoui** [tomchristie/django-rest-framework#4858]
It would be greate if we could have a possibility to auto-fill post form with default json object for browsable api

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/tomchristie/django-rest-framework/issues/2150.

**Comment by youneschaoui** [comment]
It's not a duplicate since #1250 asks for remembering but I ask for specifying one time static json object like Postman client does.

**Comment by tomchristie** [comment]
For now I'm going to treat this as out-of-scope. I do think we might address this kind of requirement in the future, but it's more likely to happen as part of a bigger re-thinking of the browsable API.
