### ISSUE TITLE
Cannot import APITestClient

### ISSUE THREAD

**Issue by nesh170** [tomchristie/django-rest-framework#4861]
from rest_framework.test import APITestCase

causes an error

    class HeaderDict(requests.packages.urllib3._collections.HTTPHeaderDict):
AttributeError: module 'requests' has no attribute 'packages'

**Comment by nesh170** [comment]
Nevermind, this was on my end. Thanks

**Comment by glothos** [comment]
How did you fix this? Getting the same error in v3.11.0
