### ISSUE TITLE
WARNING: more than one target found for cross-reference u'list'

### ISSUE THREAD

**Issue by acidjunk** [tomchristie/django-rest-framework#4882]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
We use DRF in our app. The app is documented with Sphinx. When I override the list() method in a viewset, Sphinx get confused and doesn't build the docs anymore:
`docstring of myapp.actions.device.DeviceActionManager.update_or_create:None: WARNING: more than one target found for cross-reference u'list': views.api.MyViewSet.list, views.api.MyOtherViewSet.list`

For clarity: we have a 
`:rtype: list `
in a lot of places in our docs. It seems to clash with the list() method of the ViewSet.

## Expected behavior
I'm not sure this is a bug, or if there is an solution that doesn't involve renaming the current list() method in a viewset. I just stumbled on it when I did override the list method in one of my ViewSets; which forced me to change our docs in a lot of places.

**Comment by tomchristie** [comment]
Not sure what your issue is exactly, but certainly something around your sphinx config/docs, rather than an issue that we'd be able to resolve in REST framework.

**Comment by acidjunk** [comment]
Thanks for your quick reply, you're absolutely right.

FWIW -> just solved it in our docs with:
```
:rtype: :func:`list`
```
the list method in the ViewSet just clashes somehow with python's list function.

**Comment by tomchristie** [comment]
Great, good to hear! 😄

**Comment by tomchristie** [comment]
(And cheers for posting the update - always useful to have history for things like this in case someone else bumps into a similar issue)
