### ISSUE TITLE
CSRF error in Django Rest Framework when the user is logged in

### ISSUE THREAD

**Issue by tahmidkhan** [tomchristie/django-rest-framework#4887]
I am running an API built with Django Rest Framework(DRF). I am using AngularJs for my front-end, mainly for sending the requests to the API. However, I am facing a weird issue:

If I am logged in using the admin panel, and I send the POST request, I get this error from my API:

`CSRF token missing`

However, if I log out and try again, the request just works. What's going on? It doesn't make much sense to me as I am clearly sending the requests from the same domain, not cross domain.

Any help?

**Comment by xordoquy** [comment]
Hi,

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
