### ISSUE TITLE
Browseable API broken if CSRF_COOKIE_HTTPONLY enabled

### ISSUE THREAD

**Issue by daggaz** [tomchristie/django-rest-framework#4893]
## Steps to reproduce

* Enable [`CSRF_COOKIE_HTTPONLY`](https://docs.djangoproject.com/en/1.10/ref/settings/#csrf-cookie-httponly) in django settings
* Attempt to PUT through the Browsable API

If CSRF_COOKIE_HTTPONLY is enabled in the django settings then the existing method of accessing the CSRF token for including in the ajax requests (for the PUT form for example) is unable to access the value of the CSRF token:
https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/static/rest_framework/js/csrf.js#L41

According to the django docs, if this setting is enabled, the CSRF token should be supplied via alternative means (hidden field in the form for example).

## Expected behavior

The request to update (PUT) through the Browsable API works.

## Actual behavior

```
HTTP 403 Forbidden
Content-Type: application/json
Vary: Accept
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS

{
    "detail": "CSRF Failed: CSRF token missing or incorrect."
}
```

**Comment by tomchristie** [comment]
So `CSRF_COOKIE_HTTPONLY=True` is incompatible with the browsable API.
Just a constraint we have to live with.
Either disable the browsable API, or don't use that setting. (Or perhaps only use the browsable API in DEBUG mode)

**Comment by robvdl** [comment]
I have just come across this issue too and am wondering why it was closed.

There are ways to deal with this, CSRF_COOKIE_HTTPONLY is an optional security setting that means Javascript does not have access to cookies, this can help mitigate potential XSS attacks so some of us would prefer to have this turned on if possible.

It's not a huge deal because there are better ways to protect against XSS attacks such as CSP headers for example.

However, to me I think the issue is that the browsable API relies on reading cookies in the Javascript layer instead of using a hidden input on the POST form which would solve this issue, unless I am mistaken here?

**Comment by tomchristie** [comment]
> I think the issue is that the browsable API relies on reading cookies in the Javascript layer instead of using a hidden input on the POST form which would solve this issue, unless I am mistaken here?

Yes. Although substitute "issue" for "constraint", so...

"the *constraint* is that the browsable API relies on reading cookies in Javascript"

**Comment by tomchristie** [comment]
We can document this, and make it clear that the browsable API is not compatible with this setting, but there's no way around it.

Eg. there's no way to include CSRF tokens in HTTP `DELETE` requests made by the browsable API, *except* by using JavaScript.

The Django docs *do* include a section on how to include CSRF tokens in AJAX requests, and we're following that style here, so we're not outside of any expected behaviors.

**Comment by robvdl** [comment]
Cool thanks, I get it.

**Comment by daggaz** [comment]
Could the token not be embedded in the page itself (hidden field for example). 

The [JS](https://github.com/encode/django-rest-framework/blob/master/rest_framework/static/rest_framework/js/csrf.js#L41) could then read the value from the page itself:
```javascript
var csrftoken = $('#csrf_hidden_field').val();
```

**Comment by robvdl** [comment]
@daggaz It should work I think, I can't see why not really, but it's upto the authors.

**Comment by tomchristie** [comment]
> Could the token not be embedded in the page itself (hidden field for example).

Actually that's a good call, yup. Would be happy to consider a pull request along those lines.
