### ISSUE TITLE
Something swallows AttributeError on api_root view

### ISSUE THREAD

**Issue by kissgyorgy** [tomchristie/django-rest-framework#4896]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Make an Authentication class:
```
class AttributeErrorAuthentication(BaseAuthentication):
    def authenticate(self, request):
        raise AttributeError
    
    def authenticate_header(self, request):
        return 'NotImportant'
```
Set it in DEFAULT_AUTHENTICATION_CLASSES setting:
```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.authentication.AttributeErrorAuthentication',
    )
}
```

Make a simple view:
```
class UserView(generics.CreateAPIView, generics.RetrieveAPIView, generics.UpdateAPIView):
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user
```

Include an empty DefaultRouter and the UserView in the same urlpatterns :
```
router = DefaultRouter()
urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^user/$', views.UserView.as_view(), name='user-detail'),
]
```
or register something on it, doesn't matter I think.

Make a request to `http://localhost:8000/api/`.

## Expected behavior
Show AttributeError traceback, HTTP 500 server error

## Actual behavior
No traceback, HTTP 200 OK response.

On the `/user/` endpoint I got a traceback, but on api_root, nothing.

**Comment by carltongibson** [comment]
@kissgyorgy That's curious. Would you be able to work it into a test case so we step through it?

**Comment by kissgyorgy** [comment]
I actually found the thing, just totally forgot about this ticket.
