### ISSUE TITLE
Metadata should include choices for read-only ChoiceFields

### ISSUE THREAD

**Issue by danielkeller** [tomchristie/django-rest-framework#4898]
Right now, the metadata does not include choices for a `ChoiceField` if it is read-only. This can be a problem if, for example, I want to use the metadata to display human-readable text instead of a number. See [this line](https://github.com/tomchristie/django-rest-framework/blob/05b0c2adff35e136ca2022156534c87f8394f34a/rest_framework/metadata.py#L140) in the code.

It looks like this behaviour is actually unintentional. The check for read_only was added in a97c989, with the commit message 'fix read_only related field metadata.' But later in 014e24b0 and 05b0c2a, related fields were specifically excluded anyway. It appears that if just the check for read_only is removed, the test in a97c989 will still pass.

**Comment by tomchristie** [comment]
I think it's more intuitive not to include the choices by default for read only fields. Can see that there will be use cases where you might want to use this (as you describe) but I'm okay with users having to customize the metadata class if they want that.
