### ISSUE TITLE
Allowing excluding fields in Serializer initialization dynamically

### ISSUE THREAD

**Issue by levivm** [tomchristie/django-rest-framework#4899]
It is common to want to remove serializer fields dynamically based on any condition. 

So, I think we need to have an _exclude_fields_ parameter available in Serializer Initializator. 

```
if my_condition_to_exclude_fields:
    serializer = MySerializer(instance=myinstance, remove_fields = ['field_1', 'field_2'])
else:
     serializer = MySerializer(instance=myinstance)
```

I always create a mixin in order to handle that case, but why not has a parameter to allow that? 

```
class RemovableFieldsMixin(serializers.Serializer):
    def __init__(self, *args, **kwargs):
        remove_fields = kwargs.pop('remove_fields', None)
        super(RemovableFieldsMixin, self).__init__(*args, **kwargs)

        if remove_fields:
            # for multiple fields in a list
            for field_name in remove_fields:
                self.fields.pop(field_name)
```

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

Note that we tend to avoid such cases due to the inconsistencies it brings.
