### ISSUE TITLE
Serializers cannot handle instances of `ChainMap` because they check `isinstance(thing, dict)`

### ISSUE THREAD

**Issue by jisaacstone** [tomchristie/django-rest-framework#4901]
Ought instead check `isinstance(thing, collections.Mapping)`

https://docs.python.org/2.7/library/collections.html#collections.Mapping

Example here:

https://github.com/tomchristie/django-rest-framework/blob/300e46a9e5798ca56f56ba231de3d3fded860551/rest_framework/serializers.py#L445

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```python
from chainmap import ChainMap   #  py 2.7. py3: from collections import ChainMap
from rest_framework import serializers

class FooSerializer(serializers.Serializer):
     bar = serializers.CharField()

cm = ChainMap({'bar': 'molp'})

FooSerializer(data=cm).is_valid()  # False
```

## Expected behavior

Works same as dictionaries

## Actual behavior

    (400, {u'non_field_errors': [u'Invalid data. Expected a dictionary, but got ChainMap.']})

**Comment by carltongibson** [comment]
I'm inclined to say this is a valid request. (Why not?)

I'd view it as an enhancement rather than a bug. (Since the original use-case was very much `dict`s.)

**Comment by carltongibson** [comment]
@jisaacstone If you wanted to construct a PR with test cases for the serialiser validation flow using a `ChainMap` that would be a great start.

**Comment by jisaacstone** [comment]
Gonna try 7 get to this this weekend - is there a precedent for including 3rd party libs in tests (ChainMap is backported to py2.7 via library)

Else I'll just make a simple dictlike that inherits from `Mapping`.

**Comment by carltongibson** [comment]
* We definitely wouldn't want to pull in a dependency. 
* You can use [skipIf](http://doc.pytest.org/en/latest/skipping.html#id1) to scope the test to Py3. (Anyone object to that?)
* If we're really making sure we support any `Mapping` — and if that's the assert — then maybe that's the way to go. (But **if** `ChainMap` is the only genuine example...)

**Comment by jisaacstone** [comment]
`ChainMap`'s the only non-`dict` `Mapping` in the standard lib that I know of, but abstract base classes are in py2.7 (and 2.6 I think) so it seems maybe better to support both?

Maybe I'll write two tests. Beats doing taxes

**Comment by xordoquy** [comment]
Seconding @carltongibson here.

**Comment by xordoquy** [comment]
Also note that `collections.UserDict` is also a non `dict` `Mapping` object:

    >>> from collections import UserDict
    >>> u = UserDict()
    >>> isinstance(u, dict)
    False
    >>> isinstance(u, Mapping)
    True
