### ISSUE TITLE
Outdated docstring in _not_authenticated in Request class

### ISSUE THREAD

**Issue by pgergov** [tomchristie/django-rest-framework#4907]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

* Go to https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/request.py#L354-L360

## Expected behavior

* Function should return tuple of three elements

## Actual behavior

* Function sets `_authenticator`, `user` & `auth` attributes of the `Request` class.

## Solution

* PR here https://github.com/tomchristie/django-rest-framework/pull/4906

**Comment by tomchristie** [comment]
Closed via #4906 - thanks again!
