### ISSUE TITLE
Tutorial 1 - Use Django's JSONResponse class 

### ISSUE THREAD

**Issue by gitanupam** [tomchristie/django-rest-framework#4912]
In Tutorial-1 [here](http://www.django-rest-framework.org/tutorial/1-serialization/#writing-regular-django-views-using-our-serializer), looks like we could just use Django's [JSONResponse](https://docs.djangoproject.com/en/1.10/ref/request-response/#jsonresponse-objects) class instead of defining one separately.

Relevant discussion thread [here](https://groups.google.com/forum/#!topic/django-rest-framework/0RNC5N7xaCk).

best,
Anupam

**Comment by tomchristie** [comment]
Reasonable call there! I'd be happy for us to accept a pull request for that yup, tho otherwise not fussed enough about it to track it with an open issue.
