### ISSUE TITLE
Static asset breaking on S3 builds

### ISSUE THREAD

**Issue by dbinetti** [tomchristie/django-rest-framework#4914]
You have a static asset (a font: `rest_framework/fonts/glyphicons-halflings-regular.woff`) included in the DRF library that breaks when used in AWS S3 deployments.  There could be multiple reasons for this (I've included a full investigation below) but the net effect is that it causes a re-upload and file re-naming on every deploy, wasting some time, bandwidth and (ultimately) creating unnecessary cruft.

Now this is about as low-priority an issue as they come -- everything still works, it doesn't break the actual deploys, and in the final analysis is really more of an annoyance than anything else.  Still, if I read the code correctly then it doesn't even appear that this offending font is being used, so maybe it can just be nuked?  

I'm happy to include a PR for this if necessary, but I figured it might just be easier to `rm` them from this issue -- assuming, of course, that in fact the font is superfluous.  If it isn't, then perhaps uploading a new version of it might solve the problem. 

OK, have at it!

Investigation from other thread:
The offending file is `rest_framework/fonts/glyphicons-halflings-regular.woff` When looking in my AWS bucket there are many versions of the file, all with an appended hash; i.e., it just is creating a new copy of that particular file on every upload.  [screenshot](
https://www.dropbox.com/s/737dzpusn0rvp4v/Screen%20Shot%202017-02-13%20at%2011.39.34%20AM.png?dl=0
)

So I did some poking around and discovered the following, all related to that specific file:

[aws s3 sync doesn't guess MIME type for .woff file](
aws/aws-cli#1249)

[Bootstrap 3 Glyphicons are not working](
http://stackoverflow.com/questions/18369036/bootstrap-3-glyphicons-are-not-working
)

[Glyph icons don't work in the customized version](
twbs/bootstrap#9925)

[collectstatic can't find glyphicons when using ManifestStaticFilesStorage](
tomchristie/django-rest-framework#2008)

[Add Glyphicons font files to solve collectstatic issue](
tomchristie/django-rest-framework#2024)

My first thought was that DRF uploaded a corrupt file to its `static` files, but the DRF version and what's in Bootstrap `dist` have the same checksum.  So it might be the AWS mime-type issue.  It also seems like it might not be necessary at all, so perhaps they can be removed?

## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

**Comment by kevin-brown** [comment]
This is _almost guaranteed_ to be an issue in whatever storage plugin you are using for Django. I say this as the person who had to fix MIME type guessing in the [Azure storage plugin for Django](https://github.com/Rediker-Software/django-azure-storage), because that doesn't just happen magically.

**Comment by xordoquy** [comment]
While I agree this is annoying, it is unlikely an issue with Django REST framework's statics in particular since it works with the default static storage.
You should rather report the bug to the project that provides you the storage you are using.
