### ISSUE TITLE
Serializer field TimeField incorrectly handles midnight times (00:00)

### ISSUE THREAD

**Issue by bendholmes** [tomchristie/django-rest-framework#4915]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Serialize a `datetime.time` object using `fields.TimeField`:

```
t = datetime.time(0, 0)
serializers.TimeField(format="%H:%M").to_representation(t)
```

## Expected behavior

Output should be '00:00'

## Actual behavior

Output is null

**Comment by xordoquy** [comment]
tested on the latest stable:

    >>> import datetime
    >>> t = datetime.time(0, 0)
    >>> from rest_framework import serializers
    >>> serializers.TimeField(format="%H:%M").to_representation(t)
    '00:00'
    >>>
