### ISSUE TITLE
Serializer ManyToMany Problem

### ISSUE THREAD

**Issue by TopZJ** [tomchristie/django-rest-framework#4921]
### hello :
I want serializer  a ManyToMany field for my query results to return values.
But in the Documentation I did not understand whether to show a serializer ManyToMany  display.

Thanks ~

**Comment by tomchristie** [comment]
Usage questions like this so go to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework), although you'll need to make your question more clear if you want anyone to be able to help.
