### ISSUE TITLE
ability to assign validation errors to specific fields

### ISSUE THREAD

**Issue by jerzyk** [tomchristie/django-rest-framework#4924]
at the moment if you would validate field by using data from more than one field, you need to place your validation code in `validate` method of a serializer.

unfortunatelly at this momet you loose a possibility to assign error to specific fields, each `ValidationError` exception will add this message to `non_field_errors` list.

I would like to propose to add a new parameter `field` to existing `ValidationError` or a new exception `FieldValidationError` with this parameter.

This will allow more granular control of the error descriptions, which than can be used by client to pinpoint source of errors (e.g. to highlight errorneous field(s))

**Comment by xordoquy** [comment]
You simply need to raise the ValidationError with a dictionary instead of the message alone.
