### ISSUE TITLE
DjangoModelPermissions and DjangoObjectPermissions issue on "non allowed method"

### ISSUE THREAD

**Issue by tdruez** [tomchristie/django-rest-framework#4927]
This issue is a side effect of the Permissions classes:

* DjangoModelPermissions https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/permissions.py#L111
* DjangoObjectPermissions https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/permissions.py#L172

The permission code is called in the `initial()` method https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L471 , just before the request method validation https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L474

## Steps to reproduce
Enable `rest_framework.permissions.DjangoModelPermissions` on a ViewSet and submit any `Method Not Allowed`, one that is not in that dict: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/permissions.py#L90

## Expected behavior
A proper "405 Method Not Allowed" as returned by https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/views.py#L474

## Actual behavior
"500 Internal Server Error"

**Comment by xordoquy** [comment]
@tdruez Could you elaborate a bit on the use case without going too deep in the code ?

**Comment by xordoquy** [comment]
Thanks for bringing that issue.

**Comment by tomchristie** [comment]
Thanks @tdruez!

**Comment by tdruez** [comment]
Fix confirmed in new version. Closing.
