### ISSUE TITLE
Dicts with 'items' as key not rendered with AdminRenderer

### ISSUE THREAD

**Issue by readevalprint** [tomchristie/django-rest-framework#4931]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
class DummyView(APIView):
    renderer_classes = (AdminRenderer, )
    def get(self, request):
        return Response({'items' : 'a string'})
```

## Expected behavior

To see the table.

## Actual behavior

It `debug=True` an exception is raised.

It `debug=False` the DRF admin template is rendered with the header and forms, but the main content is empty.

**Comment by jpadilla** [comment]
Closed via #4932
