### ISSUE TITLE
JSONField with write_only

### ISSUE THREAD

**Issue by ZimmerHao** [tomchristie/django-rest-framework#4945]
The model serializer is defined as below

```
class OrderSerializer(serializers.ModelSerializer):
    product_info = serializers.JSONField(write_only=True, help_text='[{"id":1, "count":1},...]')
```

But the serializer can't get the product_info data use serializer.data in views and it shows:

```
TypeError: 'NoneType' object is not iterable
```

**Comment by xordoquy** [comment]
`serializer.data` should not be used for deserialization (write_only).

**Comment by xordoquy** [comment]
On a side note, couldn't reproduce either.

**Comment by ZimmerHao** [comment]
@xordoquy serializer.validated_data works fine
