### ISSUE TITLE
DRF does not return error code in response body?

### ISSUE THREAD

**Issue by user0007** [tomchristie/django-rest-framework#4946]
djangorestframework==3.5.4

Hello,

latly DRF provided "code" params to every exception. Despite this the response looks like this:

    class LoginSerializer(Serializer):
        username = serializers.CharField()

POST /login

    400: {'username': ['This field may not be blank.']}

Where is a parameter "code" with value "blank"? The same with a generic exceptions:

GET /profile

    401: {'detail': "Authentication credentials were not provided."}

Where is a parameter "code" with value "not_authenticated"? [source](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/exceptions.py#L158)

Thank you.

**Comment by jpadilla** [comment]
You can use a [custom exception handler](http://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling) to [expose the exception's code identifier](http://www.django-rest-framework.org/api-guide/exceptions/#inspecting-api-exceptions).

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.
