### ISSUE TITLE
Problems rendering html in the new Live API

### ISSUE THREAD

**Issue by atkawa7** [tomchristie/django-rest-framework#4952]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
I added live api docs  but instead of rendering as html it renders as text
## Expected behavior
![image](https://cloud.githubusercontent.com/assets/5673828/23766895/d5acaf72-04c3-11e7-8b34-b96b9ceace5f.png)

## Actual behavior
It should render forms

**Comment by tomchristie** [comment]
How do you reproduce this?
Is anyone else seeing the same behavior?
Somewhat odd that I've never see this kind of thing when working on the functionality.

**Comment by atkawa7** [comment]
I have created a PR to fix the error I was having by turning auto escaping off on the following [line](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templates/rest_framework/docs/interact.html#L23) and [this](https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/templates/rest_framework/docs/document.html#L7)

**Comment by atkawa7** [comment]
@tomchristie  See https://github.com/atkawa7/django-rest-framework/tree/rendering-issue

**Comment by toXel** [comment]
Yea I have the same behavior...
