### ISSUE TITLE
Error in 3.6 announcement

### ISSUE THREAD

**Issue by decibyte** [tomchristie/django-rest-framework#4958]
In the javascript client library example of the 3.6 announcement, [this line](https://github.com/tomchristie/django-rest-framework/blame/master/docs/topics/3.6-announcement.md#L108) says:

`<script src="/docs/schema.js' %}"></script>`

Is that Django template tag ending intended?

**Comment by tomchristie** [comment]
Thanks @decibyte - resolved now!
