### ISSUE TITLE
Safari, IE: Unable to interact with the server from the live documentation page.

### ISSUE THREAD

**Issue by xordoquy** [tomchristie/django-rest-framework#4959]
## Steps to reproduce

Go to the documentation page, click on an "interact" link and then the "send request" button

## Expected behavior

I interact with the server ;)

## Actual behavior

JS exception and no request is actually performed:

[Error] TypeError: formData.entries is not a function. (In 'formData.entries()', 'formData.entries' is undefined)
	(fonction anonyme) (api.js:40)
	dispatch (jquery-1.10.2.min.js:5:14135)
	handle (jquery-1.10.2.min.js:5:10872)

**Comment by tomchristie** [comment]
Got a simple view that'll reproduce this? You seeing this everywhere or in one particular case?

**Comment by xordoquy** [comment]
Ok, this isn't really funny, this does happen for all my entry points BUT only with Safari.
Works fine with firefox. :bomb:

**Comment by xordoquy** [comment]
Seems Internet Explorer doesn't support it either:
https://developer.mozilla.org/en-US/docs/Web/API/FormData/entries
