### ISSUE TITLE
Release notes not being updated?

### ISSUE THREAD

**Issue by jayfk** [tomchristie/django-rest-framework#4962]
The [release notes](https://github.com/tomchristie/django-rest-framework/blob/master/docs/topics/release-notes.md) page covers everything up to `3.5.4`, but `3.6.x` seems to be missing completely.

There is the [3.6 announcement](https://github.com/tomchristie/django-rest-framework/blob/master/docs/topics/3.6-announcement.md), but It'd great if the release notes would be updated as well.

Thanks!

**Comment by tomchristie** [comment]
Yup, incoming.

**Comment by tomchristie** [comment]
Wanted to jump on the new releases quickly, since there were blocking issues there.

**Comment by tomchristie** [comment]
Now resolved. Thanks!
