### ISSUE TITLE
Invalid content type for schema.js

### ISSUE THREAD

**Issue by khamaileon** [tomchristie/django-rest-framework#4968]
The browser throws this error when [SECURE_CONTENT_TYPE_NOSNIFF](https://docs.djangoproject.com/en/1.10/ref/middleware/#x-content-type-options) is enable.

```
Refused to execute script from 'http://127.0.0.1:8000/docs/schema.js' because its MIME type ('script/javascript') is not executable, and strict MIME type checking is enabled.
```

**Comment by tomchristie** [comment]
Thanks for the report!
Fixed the media type to `application/javascript`.
