### ISSUE TITLE
Allowing custom documentation in the api docs that isn't tied to a endpoint

### ISSUE THREAD

**Issue by mackeyja92** [tomchristie/django-rest-framework#4969]
I have been looking for a great way to document our entire platform along with our API documentation. It would be really nice if there was some sort of way to integrate plain old documentation in the docs that aren't tied to any specific endpoint. The other feature of this is to be able to show or hide sections of the documentation based on the user's permissions.

I'd be willing to contribute it with help of someone on the drf team to point me in the right direction and this is a good fit into the project.

**Comment by xordoquy** [comment]
>  integrate plain old documentation in the docs

What do you mean by that ?

**Comment by mackeyja92** [comment]
Sorry, that could've been clearer. I just mean any standard documentation engine like sphinx or even just markdown. But the key is to have it rendered by Django in the built in docs without it needing to be tied to an endpoint.

**Comment by tomchristie** [comment]
At the moment the best way to achieve this would be to use the `description` parameter.
You can pass a markdown string to that, and it'll be rendered in the docs, prior to the endpoint docs.

We'll likely add further support along these lines as the API docs mature, but I don't think it's something we want an open ticket to track right now.
