### ISSUE TITLE
No way to rasie an ValidationError with multiple error codes to one filed using `get_full_details`?

### ISSUE THREAD

**Issue by 990px** [tomchristie/django-rest-framework#4971]
DRF: 3.6.x

That works:

    exc = ValidationError({"my_field": ["blank message", "null message"]})
    print(exc.detail)

    {'my_field': ['blank message', 'null message']}

That works also (but with the same error code):

    exc = ValidationError({"my_field": ["blank message", "null message"]})
    print(exc.get_full_details())

    {'my_field': [{'code': 'invalid', 'message': 'blank message'},
      {'code': 'invalid', 'message': 'null message'}]}

The problem is to set different error messages with different error codes to one field:

That does not work:

    exc = ValidationError({"my_field": [{"code": "blank", "message": "blank message"}, {"code": "null", "message": "null message"}]})
    print(exc.get_full_details())

    {'my_field': [{'code': {'code': 'invalid', 'message': 'blank'},
       'message': {'code': 'invalid', 'message': 'blank message'}},
    {'code': {'code': 'invalid', 'message': 'null'},
        'message': {'code': 'invalid', 'message': 'null message'}}]}

That does not work as well:

    exc = ValidationError([{"code": "blank", "message": "blank message"}, {"code": "null", "message": "null message"}])
    print(exc.get_full_details())

    [{'code': {'code': 'invalid', 'message': 'blank'},
        'message': {'code': 'invalid', 'message': 'blank message'}},
     {'code': {'code': 'invalid', 'message': 'null'},
         'message': {'code': 'invalid', 'message': 'null message'}}]

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
On a side note, you shouldn't remove SO questions.
