### ISSUE TITLE
coreapi-0.0.20.js not found

### ISSUE THREAD

**Issue by mleonard87** [tomchristie/django-rest-framework#4974]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I'm using:
- `coreapi==2.3.0`
- `djangorestframework==3.6.2`

1. Configure the docs as per the [announcement](http://www.django-rest-framework.org/topics/3.6-announcement/).
2. Browse to the docs `/docs` and open the dev tools of your browser.
3. See that there is a failed request for `/static/rest_framework/js/coreapi-0.0.20.js`

I've taken a look in the `rest_framework/static/s` directory and can only see `coreapi-0.1.0.js`

## Expected behavior

Either coreapi-0.0.20.js be included or the front be updated to use `coreapi-0.1.0.js`.

## Actual behavior

Error retrieving `coreapi-0.0.20.js`

This script tag is actually included part-way through the body and `coreapi-0.1.0.js` is correctly included in the header. Not sure if this helps, but here is a snippet of the HTML:

```html
<pre class="highlight python hide" data-language="python"><code># Install the Python client library
$ pip install coreapi</code></pre>
    
<pre class="highlight javascript hide" data-language="javascript"><code><!-- Load the JavaScript client library -->
<script src="/static/rest_framework/js/coreapi-0.0.20.js"></script>
<script src="/docs/schema.js"></script></code></pre>

</div>
```

**Comment by jpadilla** [comment]
Fixed via #4967

**Comment by leota** [comment]
Hi,
I have same problem with this environment (latest from pip):

coreapi==2.3.1
coreapi-cli==1.0.6
coreschema==0.0.4
djangorestframework==3.6.4

Can someone help?

**Comment by madEng84** [comment]
Same problem here

**Comment by carltongibson** [comment]
The file that's in the repo is [`static/rest_framework/js/coreapi-0.1.0.js`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/static/rest_framework/js/coreapi-0.1.0.js).

This is unchanged since #4967, which fixed the original issue here. 

So:

* Do you have staticfiles configured correctly?
* Did you run collectstatic?
  * If so, did you look in STATIC_ROOT? Is the file there? 
* What does your browser's web inspector say? 

Etc. 

These are just (some of) the normal steps when debugging a static files issue. 

I'm afraid there's not enough info to say more.

**Comment by carltongibson** [comment]
I just thought I'd check, the package on PyPI looks good: 

```
~ $ mkvirtualenv drf-test
...
(drf-test)~ $ pip install djangorestframework
Collecting djangorestframework
  Downloading djangorestframework-3.6.4-py2.py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 355kB/s 
Installing collected packages: djangorestframework
Successfully installed djangorestframework-3.6.4
(drf-test)~ $ cdsitepackages 
0 directories, 0 files
(drf-test)~/ve/drf-test/lib/python3.5/site-packages $ tree rest_framework/static/rest_framework/js
rest_framework/static/rest_framework/js
├── ajax-form.js
├── bootstrap.min.js
├── coreapi-0.1.0.js                 # Here's the file. 
├── csrf.js
├── default.js
├── jquery-1.12.4.min.js
└── prettify-min.js
```
