### ISSUE TITLE
Is the interactive docs working with Viewsets only?

### ISSUE THREAD

**Issue by bluesurfer** [tomchristie/django-rest-framework#4977]
I have many `ModelViewSet` classes and a few `RetrieveAPIView`for some custom API views. In the new interactive docs (great work btw) it seems that one can interact only with the `ModelViewSet`API. Am I missing something? Is this intended?

**Comment by tomchristie** [comment]
No, the interactive docs should work for any API endpoints.
(Although they work best when it's possible to introspect eg. what serializers are used on the view, so won't work great with function based API views.)

If you're able to narrow things down to a minimal reproducible case, we could take a look.

**Comment by bluesurfer** [comment]
Something like this:

**serializers.py**
```
class BookSerializer(serializers.ModelSerializer):
    class Meta:
        model = Book
        fields = ('title', 'abstract')
```
**views.py**
```
class BookDetailView(RetrieveAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    permission_classes = (IsAuthenticated,)
```
**urls.py**
```
url_patterns = [
    url(r'books/(?P<pk>\d+)/detail/$',
        views.BookDetailView.as_view(),
        name='book_detail')
]
```
The interactive docs detects such API (there's the corresponding item in the menu) but I cannot interact with it.

**Comment by bluesurfer** [comment]
Oops.. Maybe I was using the wrong approach. I think this is the right one:

http://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing

**Comment by tomchristie** [comment]
@bluesurfer Don't really understand the last comment - do you believe there's an open issue here, still?

**Comment by michael-k** [comment]
@bluesurfer implemented his views and urls like this:

```python
class BookView(ModelViewSet):
    …

class BookDetailView(RetrieveAPIView):
    …

url_patterns = [
    url(r'books/(?P<pk>\d+)$', BookView),
    url(r'books/(?P<pk>\d+)/detail/$', BookDetailView),
]
```

and now he believes that he should have used this approach instead:

```python
class BookView(ModelViewSet):
    …

    @detail_route(methods=['get'], url_path='detail')
    def detail(self, …):
        …

url_patterns = [
    url(r'books/(?P<pk>\d+)$', BookView),
]
```
That's what his last comment was about, I guess.

I believe the above approach should work with the interactive docs as soon as tomchristie/django-rest-framework#4966 is merged and release.

@bluesurfer Maybe you can add this to your `requirements.txt` confirm that is solves your issue: `git+https://github.com/nanuxbe/django-rest-framework.git@issue-4965#egg=djangorestframework`

**Comment by bluesurfer** [comment]
@michael-k @tomchristie 

Yes, that's what I meant. Except, I have registered the `ViewSet` in the `router`:

```
router = routers.SimpleRouter()
router.register(r'books', views.BookViewSet)
``` 

This works and I think that this approach (i.e. adding methods to `BookViewSet`) better adapt to my scenario: implementing "extra API" related to a model.

But still, if I have to implement a custom view (that should not be included in a `ViewSet`) I will incur in the previous problem. I think this is related with #4965 

Maybe it would be good to point this out in the docs? The existence of two different approaches to implement extra API:

1. Adding extra methods to `ViewSet`with `@detail_route`and `@list_route`
2. Implementing a custom generic view

**Comment by tomchristie** [comment]
We could consider concrete suggestions towards docs improvements, as it stands I'm not sure where we'd act on that. We cover both different styles extensively, tho total see that it's confusing that there are several very different ways of building APIs using REST framework.
