### ISSUE TITLE
Document DefaultRouter configuration options

### ISSUE THREAD

**Issue by CloudNiner** [tomchristie/django-rest-framework#4982]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.

## Steps to reproduce

The `include_root_view` and `include_format_suffixes` appear to be part of the public API surface of `DefaultRouter` (names are not prefixed with underscore following python convention), but are not documented: http://www.django-rest-framework.org/api-guide/routers/#defaultrouter

## Expected behavior

One (or both!) of the following changes would be great:
1. Include documentation on these parameters with DefaultRouter
2. Allow the user to configure them as part of the kwargs of the DefaultRouter constructor

Not including these config options as part of kwargs is trivial to work around for now by doing:
```python
router = DefaultRouter()
router.include_root_view = False
```

**Comment by anshum17** [comment]
In line with this, I am attaching screenshots. Here with 405 error, anyone can see the whole hierarchy as well. Is there any way to not render any such info(eg all urls.) How do we hide root view?
<img width="1437" alt="screen shot 2017-03-16 at 1 51 01 pm" src="https://cloud.githubusercontent.com/assets/8734224/23987495/e25fab16-0a4f-11e7-8b8a-6131c4de51ff.png">
<img width="1439" alt="screen shot 2017-03-16 at 1 51 43 pm" src="https://cloud.githubusercontent.com/assets/8734224/23987496/e2632e08-0a4f-11e7-8fcb-623bb28b4bfc.png">

**Comment by xordoquy** [comment]
@anshum17 what's the point in using the `DefaultRouter` if you don't use that view ? Just go for `SimpleRouter` ?

**Comment by anshum17** [comment]
Yes. Changed it to `SimpleRouter`. Now its giving `404 Not Found`. Works for me.
Thanks.

**Comment by CloudNiner** [comment]
@xordoquy The DefaultRouter also provides the format suffix functionality, so it's not always the case that reverting to the SimpleRouter works for removing the root API view without additional configuration. 

It would still be helpful to know at a glance in the documentation that it's possible to individually disable the two features that the DefaultRouter provides, without having to dig into the source code.

I would be willing to submit a PR for this, either to just update the docs, or to also allow those two flags to be configured in the DefaultRouter constructor.
