### ISSUE TITLE
Switching from primaryrelatedField to Nestedserializer ?

### ISSUE THREAD

**Issue by amineparis** [tomchristie/django-rest-framework#4992]
I have a nested serializer. for get requests I need it to work as nested serializer to get all related object. for put/post requests I need it to work like related field since I need to switch Id instead of replacing all related object. any ideas how to achieve this ?

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
