### ISSUE TITLE
API documentation token authentication scheme error

### ISSUE THREAD

**Issue by eamigo86** [tomchristie/django-rest-framework#4994]
I am starting to test the new built-in DRF functionality: API documentation, and I have encountered the following error.
Token authentication scheme request always send 'Bearer' word.
Ex:
![image](https://cloud.githubusercontent.com/assets/11740026/24006184/6d18a820-0a41-11e7-9fdb-72723c1901f8.png)

Result:
![image](https://cloud.githubusercontent.com/assets/11740026/24006305/c72df234-0a41-11e7-9f99-60ef39599bdf.png)

**Comment by jpadilla** [comment]
@eamigo86 can you check what `window.auth` returns in the dev console?

**Comment by eamigo86** [comment]
windows.auth returns the correct value:

![image](https://cloud.githubusercontent.com/assets/11740026/24009442/622cc9aa-0a4b-11e7-9351-d767a0ea2838.png)

**Comment by leafyongzhong** [comment]
same issue I met

**Comment by tomchristie** [comment]
Which browser, operating system, and REST framework versions are you both using @eamigo86, @leafyongzhong?

**Comment by eamigo86** [comment]
Chrome 56.0.2924.87
Windows 10
django 1.9
rest-framework 3.6.2

By the way, the error is in the file: "_static/rest_framework/js/coreapi-0.1.0.js_" line **118**:
        `this.scheme = options.prefix || 'Bearer';`  
            instead of :
        `this.scheme = options.scheme || 'Bearer';`

The **options** object does not have a **sheme** attribute.

**Comment by tomchristie** [comment]
> By the way, the error is in the file: "static/rest_framework/js/coreapi-0.1.0.js" line 118:

That sounds promising, yes. Care to issue a pull request that I can then review.
Failing that will pick this up myself.
