### ISSUE TITLE
About "write_only_fields" being disabled

### ISSUE THREAD

**Issue by COCOLMAN** [tomchristie/django-rest-framework#4995]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

i know that 
```
The write _only_fields option on ModelSerializer has been moved to      
PendingDeprecation and replaced with a more generic extra_kwargs"
```
in documents..

I do not know why 'write_only_fields' has been removed.
But it seems to had been used in the past versions (#1306)

Anyway, I feel uncomfortable.
'Read_only_fields' is available but,
'Write_only_fields' is not available

At least until the day "read_only_fields" is available
I think you need a error(or warning) about 'write_only_fields'.
(Like 'write_only fields is not available')

I think it will reduce confusion.

**Comment by COCOLMAN** [comment]
OMG I accidentally pressed the enter key. sorry.

**Comment by tomchristie** [comment]
> I do not know why

Removing extra ways of doing things in favor of a single common option leads to more consistency across both individual projects, and across the ecosystem as a whole.

Given that we've deprecated this since 3.0, and are now on 3.6 I'm not particularly inclined to add an extra failsafe check in here.
