### ISSUE TITLE
'API Document'  ask for wrong params (page)

### ISSUE THREAD

**Issue by COCOLMAN** [tomchristie/django-rest-framework#4996]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```
# serializers.py
class PostSerializer(serializers.ModelSerializer):
    class Meta:
        model = Post
        fields = 'title', 'content'


# views.py
class PostView(generics.ListCreateAPIView):
    serializer_class = PostSerializer
    queryset = Post.objects.all()
```

I did not set the pagination.

but in the API Documentation

![sample](http://i.imgur.com/ENywCYW.png)

Because generics.views has a default value of 'PageNumberPagination'(in api_settings)
so..
`Not getattr (view, 'pagination_class', None)` value is always false.

**Comment by COCOLMAN** [comment]
`Not getattr (view, 'pagination_class', None)` is a phrase in the get_pagination_fields method of the SchemaGenerator class  in schemas.py .

**Comment by tomchristie** [comment]
From how you've explained this I don't see any issue.
It's picking up the default setting.
Set pagination_class = None on the view/viewset if you want to turn that off for one instance,
or set it to None in the settings to turn it off globally.

**Comment by COCOLMAN** [comment]
The 'page' parameter has no role in API Documents.
The default value of PAGE_SIZE is already None (rest_framework/settings.py)

I thought it would be better to eliminate the meaningless parameter than to add 'pagination_class = None' for each 'ListView Class'

**Comment by tomchristie** [comment]
Okay, I think I see - misunderstood the problem.
Issue being that pagination is turned off if `PAGE_SIZE=None` (regardless of the pagination class that's been set)
We still want to fix this in the schema generation rather than just changing the existings settings defaults tho - #4997 isn't the right approach.

**Comment by COCOLMAN** [comment]
Um .. If you do not adjust the default settings

In 'get_pagination_fields' method,  argument 'view' always has 'pagination_class'.

At this time, it seems difficult to check whether 'pageniation_class' is user-specified or default setting.

I will think more.
Thank you for your advice.
