### ISSUE TITLE
`BigAutoField` should be serialized as string instead of int

### ISSUE THREAD

**Issue by dczech** [tomchristie/django-rest-framework#5006]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Lets take a model 
```python
class Item(models.Model):
    id = BigAutoField(primary_key=True)
    name = models.CharField(max_length=50)
```
When `id ` is outside javascript mantissa range (>=2^53) it is rounded to fit the floating point representation. It leads to many unpredictable code breaks and bugs. It can be reproduced in API documentation where you cannot operate on objects outside of the range.

## Expected behavior
Assuming standard routes for `Item` model. 
In documentation API  for the route `item-detail`  when you try to retrieve details for `id=1474526976323617798` it should be evaluated to route `GET /items/1474526976323617798/`

## Actual behavior
The route is evaluated to:
`GET /items/1474526976323617800/`

**Comment by tomchristie** [comment]
Okay, so. For *most* users I'd strongly assume that mapping `BigAutoField` to an integer representation is preferable to using a string representation.

I'd suggest a better approach would be that by *default* we should map `BigAutoInteger` to an Integer serializer field with a maximum value constraint. (Probably of either 9007199254740991 or round that to 9,000,000,000,000,000
- http://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin )

If users want to use the available range above 2^53 then they're able to use an *explicit* CharField as the serializer field.

Closing this in favor of #5007 as a result.
