### ISSUE TITLE
Is it possible get JSON-Schema from API fitting for jsonschema2pojo.org?

### ISSUE THREAD

**Issue by proft** [tomchristie/django-rest-framework#5012]
Hello!
I have a django application with django-rest-framework and Android application. 
I want to generate JSON-Schema from my API fitting for jsonschema2pojo.org.
It means I want structure with ``properties`` like following
```
{
  "type":"object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "integer"
    },
    "baz": {
      "type": "boolean"
    }
  }
}
```

I know about ``coreapi`` but it generates  another schema.

**Comment by xordoquy** [comment]
Hi,
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
