### ISSUE TITLE
Docs - 401 on docs/ & schema.js

### ISSUE THREAD

**Issue by JakeMana** [tomchristie/django-rest-framework#5019]
After a fresh installation of django and drf, Ive followed the instructions on installing DRF's new docs. When I navigate to the link, the title on the left sidebar is missing even I've added it in urls.py.
When I check the network, I got 401 on /docs and schema.js. I ran collectstatic as well. 
Any idea why this is happening?
screen: http://pasteboard.co/4Tk1fRbnB.png

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
Note that you probably have an authentication / permission in your settings.

**Comment by vesterbaek** [comment]
Running into this as will with 
```
'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.IsAuthenticated',
]
```

Is there anyway to specify permission classes for the docs views @xordoquy?

**Comment by vesterbaek** [comment]
Also discussed here (without any conclusion): https://groups.google.com/forum/#!searchin/django-rest-framework/schema.js$20401%7Csort:relevance/django-rest-framework/JUlczAmbGPY/lD38iA1fAgAJ

**Comment by xordoquy** [comment]
my bet would be to [use an explicit view](http://www.django-rest-framework.org/api-guide/schemas/#using-an-explicit-schema-view) so you can tune the authentication / permissions for it.
