### ISSUE TITLE
Adding to Third Party Resources

### ISSUE THREAD

**Issue by aaronn** [tomchristie/django-rest-framework#5024]
As per the [docs](http://www.django-rest-framework.org/topics/third-party-resources/#existing-third-party-packages), here's an issue indicating that I'd like to add my project `drfpasswordless` to the Authentication section.

https://github.com/aaronn/django-rest-framework-passwordless

**Comment by xordoquy** [comment]
Sure, feel free to open a PR to tell us a bit about the project.
