### ISSUE TITLE
I use Django 1.6. What version of rest_framework i need for my django?

### ISSUE THREAD

**Issue by Gipi66** [tomchristie/django-rest-framework#5032]
I use Django 1.6. What version of rest_framework i need for my django?
And where i can download this?

**Comment by xordoquy** [comment]
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

You will need to go through the release notes to figure out what was the latest version of DRF to support Django 1.6.
