### ISSUE TITLE
HyperlinkedRelatedField lookup_url_kwarg population

### ISSUE THREAD

**Issue by lyssdod** [tomchristie/django-rest-framework#5034]
Why does `HyperlinkedRelatedField` get its `lookup_field` attribute from default (`pk`) and not from provided view name? https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L273

I've just discovered this issue. Consider this (models are neglectable):

```
class SessionsView(viewsets.ReadOnlyModelViewSet):
    lookup_url_kwarg = 'id'
    queryset = models.Session.objects.all()
    serializer_class = serializer.SessionsSerializer
```

```
class SessionsSerializer(serializers.ModelSerializer):
    stuff = serializers.HyperlinkedRelatedField(many = True,
                                                    lookup_url_kwarg = 'id', # if I won't specify this, I will get ImproperlyConfigured lookup error
                                                       view_name = 'stuff-detail',
                                                       read_only = True)

    class Meta:
        model = models.Session
        fields = ('id', 'project', 'stuff')
```

Later there, what's the reason to hardcoding `pk` once again in get_url method? https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/relations.py#L306

Is there a point to make `reverse` with `lookup_url_kwarg` obtained from the view (though it can require specifying full view class instead of just view)? 

Thank you!

**Comment by lyssdod** [comment]
I've made a simple PR to workaround this issue

**Comment by tomchristie** [comment]
> Why does HyperlinkedRelatedField get its lookup_field attribute from default (pk) and not from provided view name?

There's no easy way to automagically determine the view lookup kwarg given the view name.
Agree that setting up hyperlinked relationships can be fiddly, but there's no easy answers there.
