### ISSUE TITLE
Token Key in Token Authentication is not Encrypted

### ISSUE THREAD

**Issue by wiamsuri** [tomchristie/django-rest-framework#5041]
## Expected behavior
Any person, even with access to database, should not be able to see user's token key. The token key should be generated with a one-way function, making brute force attack the only way to gain access through token authentication.
## Actual behavior
The token key stored in the database is not encrypted.

**Comment by xordoquy** [comment]
The provided token authentication is very basic. If you are looking for something secure, best use alternatives such as OAuth.

**Comment by tomchristie** [comment]
As @xordoquy says, yup. It's possible that we could start recommending JWT as the default.
