### ISSUE TITLE
CSRF check not done for not authentificated users.

### ISSUE THREAD

**Issue by aldarund** [tomchristie/django-rest-framework#785]
Why the csrf not checked when user is not authenticated even if the SessionAuthentification used and the post request was done.
And if use restframework for login views ( i use it) - this will lead to  login CSRF attacks.

**Comment by tomchristie** [comment]
Closing this due to lack of anyone else following up on this or raising similar tickets. Perhaps our CSRF documentation has sufficiently improved that we don't need to consider this as active anymore.

Perfectly happy to reconsider if requested by anyone.

**Comment by tomchristie** [comment]
Closed by #2994.

**Comment by LizardWizzard** [comment]
Hi! Recently have discovered this. Why the decision is to ignore CSRF checks for unauthenticated requests? There are several use cases when it becomes very dangerous option. With login for example [this](https://support.detectify.com/customer/portal/articles/1969819-login-csrf) article shows potential troubles and PayPal 'experience'. Another case is a 'forgot password' form and forms like that. Can we perform csrf check before user authenticated/active one?

**Comment by xordoquy** [comment]
As the documentation states (thanks to #2994), the login views shouldn't be available as an API.

**Comment by xordoquy** [comment]
It would affect non session based clients.
SPA and mobile app *should* be using so called "stateless" authentication - usually tokens - in which case CSRF does not apply.
Session based auth only really make sense when you have a "traditional" website that performs a few API calls. In that case, the user will usually already be identified by a pure Django view.

**Comment by LizardWizzard** [comment]
But as I see it wouldnt :) As it stated [here in the source core](https://github.com/encode/django-rest-framework/blob/master/rest_framework/authentication.py#L116) what if just swap checks for csrf and active/authenticated user?

Also in several situations any authentication cant be fully stateless. In case you want for example have an ability to see all active sessions and invalidate particular one.

**Comment by xordoquy** [comment]
> But as I see it wouldnt :) As it stated here in the source core what if just swap checks for csrf and active/authenticated user?

This would require token based authenticated clients to provide CSRF if the server uses `[SessionAuthentication, TokenAuthentication]` as authentication settings.

**Comment by tomchristie** [comment]
@LizardWizzard If you're doing all those things and want CSRF then you should just use SessionAuthentication, since it *is* a cookie-based auth scheme, which is what you're describing.

**Comment by LizardWizzard** [comment]
I use SessionAuthentication with overridden authenticate method with force checking against CSRF. I'm just confused with a decision to ignore CSRF checks for all unauthenticated requests. I think there should be a better option suitable for all situations without any security tradeoffs. For example people who don't know about such a caveat can make a login (this covered by a warning in docs), reset password form, contact us form and so on and so forth. These views won't be covered by CSRF protection shield and this can lead to many bad things like spam phishing and so on (especially password reset form). Can there be a way to somehow improve the situation? I can dig into this and make a PR if needed
