### ISSUE TITLE
Better error messaging when hyperlinked relationship could not reverse view.

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#977]
It's very easy for new users to use a hyperlinked relationship without having a view that it resolves to.  The error messaging in this case should be very explicit and clear.

See: http://twentyeighttwelve.com/django-rest-framework-could-not-resolve-url-for-hyperlinked-relationship-using-view-name/

**Comment by tomchristie** [comment]
For now I'm going to drop the 3.1 milestone on this.
Given that serializers now have printable representations we already have an improvement here, and I'd like to allow us to 100% focus on headline features - at this point I don't this still makes that grade.

**Comment by tomchristie** [comment]
> Given that serializers now have printable representations we already have an improvement here

Given that, I'm also going to close this off now, although may reconsider if we have any renewed interest.

**Comment by onekiloparsec** [comment]
This is madness how many times even a not-so-new-user can stumble upon this error message. Or I must be configured to understand this stuff wrongly, don't know. I still don't get it.

**Comment by tomchristie** [comment]
100% agree that it is a horrible error message to have to show to users.
Difficult because the URL configuration is completely separate to the serializer configuration, but both need to match up. Not obv exactly what we should do, but would be nice if could print a contextually helpful error message...

1. Is there a view with this name, but different arguments?
2. Is there a view with this base name but under a different namespace?
3. No view with this name at all.

Furthermore, command-line options to print URL configurations / serializers might also be helpful?

**Comment by tomchristie** [comment]
Oops - going to leave this against #3291 instead.
